In [62]:
from pathlib import Path

import pandas as pd

DATA_DIR = Path("../datasets/final/ml")

In [63]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.expand_frame_repr", False)

pd.options.display.float_format = "{:.2f}".format

In [64]:

AVAILABLE_DATASETS = ["cicids2017", "unsw_nb15", "iot23"]
DATASET_NAME = AVAILABLE_DATASETS[0]

df = pd.read_parquet(
    DATA_DIR / f"{DATASET_NAME}_train.parquet"
)

In [65]:
display(df.shape)
df.info(verbose=True)# false para visão mais enxuta

(235490, 94)

<class 'pandas.DataFrame'>
RangeIndex: 235490 entries, 0 to 235489
Data columns (total 94 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id                            235490 non-null  int64
 1   expiration_id                 235490 non-null  int64
 2   src_ip                        235490 non-null  str
 3   src_mac                       235490 non-null  str
 4   src_oui                       235490 non-null  str
 5   src_port                      235490 non-null  int64
 6   dst_ip                        235490 non-null  str
 7   dst_mac                       235490 non-null  str
 8   dst_oui                       235490 non-null  str
 9   dst_port                      235490 non-null  int64
 10  protocol                      235490 non-null  int64
 11  ip_version                    235490 non-null  int64
 12  vlan_id                       235490 non-null  int64
 13  tunnel_id                     235490 non-null  int64
 14  bidirectional_first_seen_ms   235490 non-null  int64
 15  bidirectional_last_seen_ms    235490 non-null  int64
 16  bidirectional_duration_ms     235490 non-null  int64
 17  bidirectional_packets         235490 non-null  int64
 18  bidirectional_bytes           235490 non-null  int64
 19  src2dst_first_seen_ms         235490 non-null  int64
 20  src2dst_last_seen_ms          235490 non-null  int64
 21  src2dst_duration_ms           235490 non-null  int64
 22  src2dst_packets               235490 non-null  int64
 23  src2dst_bytes                 235490 non-null  int64
 24  dst2src_first_seen_ms         235490 non-null  int64
 25  dst2src_last_seen_ms          235490 non-null  int64
 26  dst2src_duration_ms           235490 non-null  int64
 27  dst2src_packets               235490 non-null  int64
 28  dst2src_bytes                 235490 non-null  int64
 29  bidirectional_min_ps          235490 non-null  int64
 30  bidirectional_mean_ps         235490 non-null  float64
 31  bidirectional_stddev_ps       235490 non-null  float64
 32  bidirectional_max_ps          235490 non-null  int64
 33  src2dst_min_ps                235490 non-null  int64
 34  src2dst_mean_ps               235490 non-null  float64
 35  src2dst_stddev_ps             235490 non-null  float64
 36  src2dst_max_ps                235490 non-null  int64
 37  dst2src_min_ps                235490 non-null  int64
 38  dst2src_mean_ps               235490 non-null  float64
 39  dst2src_stddev_ps             235490 non-null  float64
 40  dst2src_max_ps                235490 non-null  int64
 41  bidirectional_min_piat_ms     235490 non-null  int64
 42  bidirectional_mean_piat_ms    235490 non-null  float64
 43  bidirectional_stddev_piat_ms  235490 non-null  float64
 44  bidirectional_max_piat_ms     235490 non-null  int64
 45  src2dst_min_piat_ms           235490 non-null  int64
 46  src2dst_mean_piat_ms          235490 non-null  float64
 47  src2dst_stddev_piat_ms        235490 non-null  float64
 48  src2dst_max_piat_ms           235490 non-null  int64
 49  dst2src_min_piat_ms           235490 non-null  int64
 50  dst2src_mean_piat_ms          235490 non-null  float64
 51  dst2src_stddev_piat_ms        235490 non-null  float64
 52  dst2src_max_piat_ms           235490 non-null  int64
 53  bidirectional_syn_packets     235490 non-null  int64
 54  bidirectional_cwr_packets     235490 non-null  int64
 55  bidirectional_ece_packets     235490 non-null  int64
 56  bidirectional_urg_packets     235490 non-null  int64
 57  bidirectional_ack_packets     235490 non-null  int64
 58  bidirectional_psh_packets     235490 non-null  int64
 59  bidirectional_rst_packets     235490 non-null  int64
 60  bidirectional_fin_packets     235490 non-null  int64
 61  src2dst_syn_packets           235490 non-null  int64
 62  src2dst_cwr_packets           235490 non-null  int64
 63  src2dst_ece_packets           235490 non-null  int64
 64  src2dst_urg_packets           235490 non-null  int64
 65  src2dst_ack_packets           235490 non-null  int64
 66  src2dst_psh_packets           235490 non-null  int64
 67  src2dst_rst_packets           235490 non-null  int64
 68  src2dst_fin_packets           235490 non-null  int64
 69  dst2src_syn_packets           235490 non-null  int64
 70  dst2src_cwr_packets           235490 non-null  int64
 71  dst2src_ece_packets           235490 non-null  int64
 72  dst2src_urg_packets           235490 non-null  int64
 73  dst2src_ack_packets           235490 non-null  int64
 74  dst2src_psh_packets           235490 non-null  int64
 75  dst2src_rst_packets           235490 non-null  int64
 76  dst2src_fin_packets           235490 non-null  int64
 77  application_name              235490 non-null  str
 78  application_category_name     235490 non-null  str
 79  application_is_guessed        235490 non-null  int64
 80  application_confidence        235490 non-null  int64
 81  requested_server_name         115077 non-null  str
 82  client_fingerprint            23306 non-null   str
 83  server_fingerprint            23135 non-null   str
 84  user_agent                    25777 non-null   str
 85  content_type                  33915 non-null   str
 86  flow_key                      235490 non-null  str
 87  flow_key_rev                  235490 non-null  str
 88  label                         235490 non-null  str
 89  match_status                  235490 non-null  str
 90  match_direction               235490 non-null  str
 91  match_time_diff_ms            235490 non-null  float64
 92  label_binary                  235490 non-null  str
 93  dataset_name                  235490 non-null  str
dtypes: float64(13), int64(61), str(20)
memory usage: 220.6 MB

In [66]:
display(df.head())

       id  expiration_id         src_ip            src_mac   src_oui  src_port         dst_ip            dst_mac   dst_oui  dst_port  protocol  ip_version  vlan_id  tunnel_id  bidirectional_first_seen_ms  bidirectional_last_seen_ms  bidirectional_duration_ms  bidirectional_packets  bidirectional_bytes  src2dst_first_seen_ms  src2dst_last_seen_ms  src2dst_duration_ms  src2dst_packets  src2dst_bytes  dst2src_first_seen_ms  dst2src_last_seen_ms  dst2src_duration_ms  dst2src_packets  dst2src_bytes  bidirectional_min_ps  bidirectional_mean_ps  bidirectional_stddev_ps  bidirectional_max_ps  src2dst_min_ps  src2dst_mean_ps  src2dst_stddev_ps  src2dst_max_ps  dst2src_min_ps  dst2src_mean_ps  dst2src_stddev_ps  dst2src_max_ps  bidirectional_min_piat_ms  bidirectional_mean_piat_ms  bidirectional_stddev_piat_ms  bidirectional_max_piat_ms  src2dst_min_piat_ms  src2dst_mean_piat_ms  src2dst_stddev_piat_ms  src2dst_max_piat_ms  dst2src_min_piat_ms  dst2src_mean_piat_ms  dst2src_stddev_piat_ms  dst2src_max_piat_ms  bidirectional_syn_packets  bidirectional_cwr_packets  bidirectional_ece_packets  bidirectional_urg_packets  bidirectional_ack_packets  bidirectional_psh_packets  bidirectional_rst_packets  bidirectional_fin_packets  src2dst_syn_packets  src2dst_cwr_packets  src2dst_ece_packets  src2dst_urg_packets  src2dst_ack_packets  src2dst_psh_packets  src2dst_rst_packets  src2dst_fin_packets  dst2src_syn_packets  dst2src_cwr_packets  dst2src_ece_packets  dst2src_urg_packets  dst2src_ack_packets  dst2src_psh_packets  dst2src_rst_packets  dst2src_fin_packets application_name application_category_name  application_is_guessed  application_confidence        requested_server_name client_fingerprint server_fingerprint                                                 user_agent content_type                                 flow_key                             flow_key_rev     label    match_status match_direction  match_time_diff_ms label_binary dataset_name
0  431109              0  192.168.10.50  00:19:b9:0a:69:f1  00:19:b9     49868   192.168.10.3  18:66:da:9b:e3:7d  18:66:da        88        17           4        0          0                1499102531189               1499102531190                          1                      4                 3686          1499102531189         1499102531189                    0                2           3000          1499102531190         1499102531190                    0                2            686                   343                 921.50                   667.99                  1500            1500          1500.00               0.00            1500             343           343.00               0.00             343                          0                        0.33                          0.58                          1                    0                  0.00                    0.00                    0                    0                  0.00                    0.00                    0                          0                          0                          0                          0                          0                          0                          0                          0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0         Kerberos                   Network                       0                       6                          NaN                NaN                NaN                                                        NaN          NaN   192.168.10.50|192.168.10.3|49868|88|17   192.168.10.3|192.168.10.50|88|49868|17    BENIGN  benign_matched          direct              189.00       BENIGN   cicids2017
1  345786              0     172.16.0.1  00:c1:b1:14:eb:31  00:c1:b1     57928  192.168.10.50  00:19:b9:0a:69:f1  00:19:b9        80         6           4        0          0                1499263155409               1499263155480                         71                     13                12608          1499263155409         1499263155480                   71                8            745          1499263155409         1499263155468                   59                5          11863                    52                 969.85                  2164.99                  5844              52            93.12             113.12             373              52          2372.60            3168.94            5844                          0                        5.92                         13.74                         47                    0                 10.14                   22.00                   59                    0                 14.75                   22.23                   47                          2                          0                          0                          0                         12                          2                          1                          1                    1                    0                    0                    0                    7                    1                    1                    0                    1                    0                    0                    0                    5                    1                    0                    1             HTTP                       Web                       0                       6               205.174.165.68                NaN                NaN  Mozilla/5.0 (Windows; U; MSIE 7.0; Windows NT 6.0; en-US)    text/html      172.16.0.1|192.168.10.50|57928|80|6      192.168.10.50|172.16.0.1|80|57928|6  DoS Hulk  attack_matched          direct            15409.00       ATTACK   cicids2017
2  537857              0  192.168.10.15  00:1e:4f:d4:ca:28  00:1e:4f     60756  217.20.130.99  00:c1:b1:14:eb:31  00:c1:b1       443         6           4        0          0                1499368180564               1499368181953                       1389                      6                  272          1499368180564         1499368181824                 1260                3            152          1499368180694         1499368181953                 1259                3            120                    40                  45.33                     6.02                    52              48            50.67               2.31              52              40            40.00               0.00              40                        129                      277.80                        203.30                        501                  629                630.00                    1.41                  631                  629                629.50                    0.71                  630                          3                          0                          0                          0                          3                          0                          3                          0                    3                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    3                    0                    3                    0              TLS                       Web                       1                       1                          NaN                NaN                NaN                                                        NaN          NaN  192.168.10.15|217.20.130.99|60756|443|6  217.20.130.99|192.168.10.15|443|60756|6    BENIGN  benign_matched          direct            40564.00       BENIGN   cicids2017
3  593150              0   192.168.10.5  b8:ac:6f:36:0a:8b  b8:ac:6f     57927   192.168.10.3  18:66:da:9b:e3:7d  18:66:da        53        17           4        0          0                1499371298487               1499371298487                          0                      4                  320          1499371298487         1499371298487                    0                2            144          1499371298487         1499371298487                    0                2            176                    72                  80.00                     9.24                    88              72            72.00               0.00              72              88            88.00               0.00              88                          0                        0.00                          0.00                          0                    0                  0.00                    0.00                    0                    0                  0.00                    0.00                    0                          0                          0                          0                          0                          0                          0                          0                          0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0       DNS.Google                   Network                       0                       6   pagead46.l.doubleclick.net                NaN                NaN                                                        NaN          NaN    192.168.10.5|192.168.10.3|57927|53|17    192.168.10.3|192.168.10.5|53|57927|17    BENIGN  benign_matched          direct            38487.00       BENIGN   cicids2017
4  510944              0   192.168.10.3  18:66:da:9b:e3:7d  18:66:da     60494   192.168.10.1  00:c1:b1:14:eb:31  00:c1:b1        53        17           4        0          0                1499366838171               1499366838231                         60                      2                  286          1499366838171         1499366838171                    0                1             84          1499366838231         1499366838231                    0                1            202                    84                 143.00                    83.44                   202              84            84.00               0.00              84             202           202.00               0.00             202                         60                       60.00                          0.00                         60                    0                  0.00                    0.00                    0                    0                  0.00                    0.00                    0                          0                          0                          0                          0                          0                          0                          0                          0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0              DNS                   Network                       0                       6  ocsp.int-x3.letsencrypt.org                NaN                NaN                                                        NaN          NaN    192.168.10.3|192.168.10.1|60494|53|17    192.168.10.1|192.168.10.3|53|60494|17    BENIGN  benign_matched          direct            18171.00       BENIGN   cicids2017

In [67]:
df["label"].value_counts()

label
BENIGN                        188392
DoS Hulk                       16972
PortScan                       16800
DDoS                            9801
DoS GoldenEye                    928
DoS slowloris                    759
DoS Slowhttptest                 757
FTP-Patator                      437
SSH-Patator                      313
Web Attack  Brute Force         137
Bot                              126
Web Attack  XSS                  63
Heartbleed                         2
Infiltration                       2
Web Attack  Sql Injection         1
Name: count, dtype: int64

In [68]:
df["label_binary"].value_counts()

label_binary
BENIGN    188392
ATTACK     47098
Name: count, dtype: int64

In [69]:
((df.isnull().sum() / len(df)) * 100).sort_values(ascending=False)

server_fingerprint             90.18
client_fingerprint             90.10
user_agent                     89.05
content_type                   85.60
requested_server_name          51.13
id                              0.00
dst_ip                          0.00
dst_mac                         0.00
dst_oui                         0.00
expiration_id                   0.00
src_ip                          0.00
src_mac                         0.00
src_oui                         0.00
src_port                        0.00
bidirectional_first_seen_ms     0.00
bidirectional_last_seen_ms      0.00
bidirectional_duration_ms       0.00
bidirectional_packets           0.00
bidirectional_bytes             0.00
src2dst_first_seen_ms           0.00
src2dst_last_seen_ms            0.00
src2dst_duration_ms             0.00
src2dst_packets                 0.00
src2dst_bytes                   0.00
dst2src_first_seen_ms           0.00
dst_port                        0.00
protocol                        0.00
ip_version                      0.00
vlan_id                         0.00
tunnel_id                       0.00
bidirectional_min_ps            0.00
dst2src_bytes                   0.00
dst2src_packets                 0.00
dst2src_duration_ms             0.00
dst2src_last_seen_ms            0.00
bidirectional_mean_ps           0.00
bidirectional_max_ps            0.00
bidirectional_stddev_ps         0.00
dst2src_mean_ps                 0.00
dst2src_stddev_ps               0.00
dst2src_max_ps                  0.00
src2dst_min_ps                  0.00
src2dst_mean_ps                 0.00
src2dst_stddev_ps               0.00
src2dst_max_ps                  0.00
dst2src_min_ps                  0.00
src2dst_mean_piat_ms            0.00
src2dst_stddev_piat_ms          0.00
src2dst_max_piat_ms             0.00
dst2src_min_piat_ms             0.00
dst2src_mean_piat_ms            0.00
dst2src_stddev_piat_ms          0.00
dst2src_max_piat_ms             0.00
bidirectional_syn_packets       0.00
bidirectional_cwr_packets       0.00
bidirectional_ece_packets       0.00
bidirectional_urg_packets       0.00
bidirectional_min_piat_ms       0.00
bidirectional_mean_piat_ms      0.00
bidirectional_stddev_piat_ms    0.00
bidirectional_max_piat_ms       0.00
src2dst_min_piat_ms             0.00
src2dst_syn_packets             0.00
bidirectional_fin_packets       0.00
bidirectional_rst_packets       0.00
bidirectional_psh_packets       0.00
bidirectional_ack_packets       0.00
src2dst_cwr_packets             0.00
src2dst_urg_packets             0.00
src2dst_ece_packets             0.00
dst2src_cwr_packets             0.00
dst2src_ece_packets             0.00
dst2src_urg_packets             0.00
src2dst_ack_packets             0.00
src2dst_psh_packets             0.00
src2dst_rst_packets             0.00
src2dst_fin_packets             0.00
dst2src_syn_packets             0.00
application_name                0.00
dst2src_fin_packets             0.00
dst2src_rst_packets             0.00
dst2src_psh_packets             0.00
dst2src_ack_packets             0.00
application_confidence          0.00
application_category_name       0.00
application_is_guessed          0.00
flow_key                        0.00
flow_key_rev                    0.00
label                           0.00
match_status                    0.00
match_direction                 0.00
match_time_diff_ms              0.00
label_binary                    0.00
dataset_name                    0.00
dtype: float64

In [70]:
# busca por registros duplicados
df.duplicated().sum()

np.int64(0)

In [71]:
# visão geral dos dados
df.describe().T

                                 count             mean             std              min              25%              50%              75%              max
id                           235490.00        342282.41       199086.05             1.00        177701.25        338551.50        496909.75        768065.00
expiration_id                235490.00             0.00            0.03             0.00             0.00             0.00             0.00             1.00
src_port                     235490.00         47507.57        15245.01            21.00         41262.00         52026.00         58145.75         65535.00
dst_port                     235490.00          1346.25         6358.55             1.00            53.00            80.00           443.00         65509.00
protocol                     235490.00             9.24            5.01             6.00             6.00             6.00            17.00            17.00
ip_version                   235490.00             4.00            0.00             4.00             4.00             4.00             4.00             4.00
vlan_id                      235490.00             0.00            0.00             0.00             0.00             0.00             0.00             0.00
tunnel_id                    235490.00             0.00            0.00             0.00             0.00             0.00             0.00             0.00
bidirectional_first_seen_ms  235490.00 1499285390055.63    125092957.05 1499082999676.00 1499180048207.25 1499271616247.50 1499430412284.00 1499457758386.00
bidirectional_last_seen_ms   235490.00 1499285392063.91    125092935.54 1499082999706.00 1499180048767.75 1499271620996.50 1499430412465.00 1499457758459.00
bidirectional_duration_ms    235490.00          2008.28         7319.51             0.00            22.00            47.00           322.00        119999.00
bidirectional_packets        235490.00            22.66         2270.48             1.00             2.00             4.00            10.00        488437.00
bidirectional_bytes          235490.00         22301.53      2949852.54            40.00           104.00           296.00          1643.00     634555999.00
src2dst_first_seen_ms        235490.00 1499285390055.63    125092957.05 1499082999676.00 1499180048207.25 1499271616247.50 1499430412284.00 1499457758386.00
src2dst_last_seen_ms         235490.00 1499285392020.95    125092940.56 1499082999676.00 1499180048723.50 1499271620978.00 1499430412436.00 1499457758459.00
src2dst_duration_ms          235490.00          1965.32         7307.17             0.00             0.00             0.00           259.00        119999.00
src2dst_packets              235490.00            11.47         1199.27             1.00             1.00             2.00             6.00        281747.00
src2dst_bytes                235490.00         10300.58      2346671.28            40.00            52.00           121.00           352.00     626160223.00
dst2src_first_seen_ms        235490.00 1460205614391.94 238878558989.49             0.00 1499175969647.25 1499266413538.50 1499429154673.50 1499457758387.00
dst2src_last_seen_ms         235490.00 1460205616126.95 238878559273.22             0.00 1499175969647.25 1499266425506.50 1499429156785.25 1499457758417.00
dst2src_duration_ms          235490.00          1735.00         7211.93             0.00             0.00             0.00           160.00        119999.00
dst2src_packets              235490.00            11.19         1092.08             0.00             1.00             2.00             4.00        263409.00
dst2src_bytes                235490.00         12000.96      1721373.54             0.00            52.00           160.00           692.00     594038385.00
bidirectional_min_ps         235490.00            53.09           18.71            40.00            40.00            52.00            61.00          1500.00
bidirectional_mean_ps        235490.00           214.73          295.61            40.00            52.00            81.00           168.91          2076.20
bidirectional_stddev_ps      235490.00           312.93          642.07             0.00             2.83            18.74           179.48          4019.98
bidirectional_max_ps         235490.00          1060.37         2178.23            40.00            52.00            95.00           550.00         23400.00
src2dst_min_ps               235490.00            54.34           25.78            40.00            41.00            52.00            61.00          1500.00
src2dst_mean_ps              235490.00            82.94          120.87            40.00            52.00            60.00            81.40          5453.97
src2dst_stddev_ps            235490.00            51.53          176.89             0.00             0.00             0.00            18.50          5795.50
src2dst_max_ps               235490.00           195.70          479.76            40.00            52.00            62.00            92.00         23400.00
dst2src_min_ps               235490.00            74.82           62.20             0.00            40.00            52.00            88.00          1990.00
dst2src_mean_ps              235490.00           377.05          656.46             0.00            52.00            88.00           220.67          3919.67
dst2src_stddev_ps            235490.00           386.78          919.30             0.00             0.00             0.00            68.01          6692.07
dst2src_max_ps               235490.00          1022.65         2155.14             0.00            52.00            93.00           317.00         14668.00
bidirectional_min_piat_ms    235490.00            22.35           96.76             0.00             0.00             0.00            24.00          6017.00
bidirectional_mean_piat_ms   235490.00           216.92          576.13             0.00             5.08            24.00            83.33          6017.00
bidirectional_stddev_piat_ms 235490.00           431.68         1043.56             0.00             0.00             0.00            55.43          7035.01
bidirectional_max_piat_ms    235490.00          1258.21         2747.06             0.00            16.00            37.00           196.00          9999.00
src2dst_min_piat_ms          235490.00           158.81         1172.38             0.00             0.00             0.00             0.00         10396.00
src2dst_mean_piat_ms         235490.00           424.78         1389.88             0.00             0.00             0.00            39.67         10396.00
src2dst_stddev_piat_ms       235490.00           460.86         1135.50             0.00             0.00             0.00            52.00          7191.28
src2dst_max_piat_ms          235490.00          1232.52         2755.09             0.00             0.00             0.00           151.00         10406.00
dst2src_min_piat_ms          235490.00           257.93         1360.11             0.00             0.00             0.00             0.00         11036.00
dst2src_mean_piat_ms         235490.00           483.87         1551.46             0.00             0.00             0.00            28.77         11036.00
dst2src_stddev_piat_ms       235490.00           364.89         1085.55             0.00             0.00             0.00            21.37          9248.96
dst2src_max_piat_ms          235490.00          1069.15         2622.27             0.00             0.00             0.00           133.00         19340.00
bidirectional_syn_packets    235490.00             0.69            0.98             0.00             0.00             0.00             2.00            12.00
bidirectional_cwr_packets    235490.00             0.00            0.02             0.00             0.00             0.00             0.00             2.00
bidirectional_ece_packets    235490.00             0.00            0.03             0.00             0.00             0.00             0.00             2.00
bidirectional_urg_packets    235490.00             0.00            0.03             0.00             0.00             0.00             0.00             8.00
bidirectional_ack_packets    235490.00            21.03         2270.49             0.00             0.00             2.00             9.00        488437.00
bidirectional_psh_packets    235490.00             2.05           24.40             0.00             0.00             0.00             2.00          4900.00
bidirectional_rst_packets    235490.00             0.34            0.78             0.00             0.00             0.00             0.00            49.00
bidirectional_fin_packets    235490.00             0.46            0.85             0.00             0.00             0.00             1.00            11.00
src2dst_syn_packets          235490.00             0.41            0.59             0.00             0.00             0.00             1.00             9.00
src2dst_cwr_packets          235490.00             0.00            0.02             0.00             0.00             0.00             0.00             2.00
src2dst_ece_packets          235490.00             0.00            0.01             0.00             0.00             0.00             0.00             2.00
src2dst_urg_packets          235490.00             0.00            0.03             0.00             0.00             0.00             0.00             8.00
src2dst_ack_packets          235490.00            10.36         1199.28             0.00             0.00             1.00             4.00        281747.00
src2dst_psh_packets          235490.00             0.98           18.39             0.00             0.00             0.00             1.00          4787.00
src2dst_rst_packets          235490.00             0.22            0.71             0.00             0.00             0.00             0.00            49.00
src2dst_fin_packets          235490.00             0.19            0.44             0.00             0.00             0.00             0.00            10.00
dst2src_syn_packets          235490.00             0.28            0.48             0.00             0.00             0.00             1.00            10.00
dst2src_cwr_packets          235490.00             0.00            0.00             0.00             0.00             0.00             0.00             1.00
dst2src_ece_packets          235490.00             0.00            0.01             0.00             0.00             0.00             0.00             1.00
dst2src_urg_packets          235490.00             0.00            0.00             0.00             0.00             0.00             0.00             0.00
dst2src_ack_packets          235490.00            10.67         1092.08             0.00             0.00             1.00             4.00        263409.00
dst2src_psh_packets          235490.00             1.07           14.29             0.00             0.00             0.00             1.00          4547.00
dst2src_rst_packets          235490.00             0.11            0.37             0.00             0.00             0.00             0.00             6.00
dst2src_fin_packets          235490.00             0.27            0.49             0.00             0.00             0.00             1.00             7.00
application_is_guessed       235490.00             0.32            0.47             0.00             0.00             0.00             1.00             1.00
application_confidence       235490.00             3.88            2.57             0.00             1.00             6.00             6.00             7.00
match_time_diff_ms           235490.00         26311.39        18633.37             0.00          9257.25         25265.00         42488.00         59999.00

In [72]:
df["bidirectional_duration_ms"].min(), df["bidirectional_duration_ms"].max()

(np.int64(0), np.int64(119999))