In [1]:
from src.utils.notebook_setup import *
setup_pandas()

In [2]:
# passar path para analisar datset específico
df = load_dataset()

In [3]:
display(df.shape)
df.info(verbose=True)# false para visão mais enxuta

(2197457, 90)

<class 'pandas.DataFrame'>
RangeIndex: 2197457 entries, 0 to 2197456
Data columns (total 90 columns):
 #   Column                        Dtype
---  ------                        -----
 0   id                            int64
 1   expiration_id                 int64
 2   src_ip                        str
 3   src_mac                       str
 4   src_oui                       str
 5   src_port                      int64
 6   dst_ip                        str
 7   dst_mac                       str
 8   dst_oui                       str
 9   dst_port                      int64
 10  protocol                      int64
 11  ip_version                    int64
 12  vlan_id                       int64
 13  tunnel_id                     int64
 14  bidirectional_first_seen_ms   int64
 15  bidirectional_last_seen_ms    int64
 16  bidirectional_duration_ms     int64
 17  bidirectional_packets         int64
 18  bidirectional_bytes           int64
 19  src2dst_first_seen_ms         int64
 20  src2dst_last_seen_ms          int64
 21  src2dst_duration_ms           int64
 22  src2dst_packets               int64
 23  src2dst_bytes                 int64
 24  dst2src_first_seen_ms         int64
 25  dst2src_last_seen_ms          int64
 26  dst2src_duration_ms           int64
 27  dst2src_packets               int64
 28  dst2src_bytes                 int64
 29  bidirectional_min_ps          int64
 30  bidirectional_mean_ps         float64
 31  bidirectional_stddev_ps       float64
 32  bidirectional_max_ps          int64
 33  src2dst_min_ps                int64
 34  src2dst_mean_ps               float64
 35  src2dst_stddev_ps             float64
 36  src2dst_max_ps                int64
 37  dst2src_min_ps                int64
 38  dst2src_mean_ps               float64
 39  dst2src_stddev_ps             float64
 40  dst2src_max_ps                int64
 41  bidirectional_min_piat_ms     int64
 42  bidirectional_mean_piat_ms    float64
 43  bidirectional_stddev_piat_ms  float64
 44  bidirectional_max_piat_ms     int64
 45  src2dst_min_piat_ms           int64
 46  src2dst_mean_piat_ms          float64
 47  src2dst_stddev_piat_ms        float64
 48  src2dst_max_piat_ms           int64
 49  dst2src_min_piat_ms           int64
 50  dst2src_mean_piat_ms          float64
 51  dst2src_stddev_piat_ms        float64
 52  dst2src_max_piat_ms           int64
 53  bidirectional_syn_packets     int64
 54  bidirectional_cwr_packets     int64
 55  bidirectional_ece_packets     int64
 56  bidirectional_urg_packets     int64
 57  bidirectional_ack_packets     int64
 58  bidirectional_psh_packets     int64
 59  bidirectional_rst_packets     int64
 60  bidirectional_fin_packets     int64
 61  src2dst_syn_packets           int64
 62  src2dst_cwr_packets           int64
 63  src2dst_ece_packets           int64
 64  src2dst_urg_packets           int64
 65  src2dst_ack_packets           int64
 66  src2dst_psh_packets           int64
 67  src2dst_rst_packets           int64
 68  src2dst_fin_packets           int64
 69  dst2src_syn_packets           int64
 70  dst2src_cwr_packets           int64
 71  dst2src_ece_packets           int64
 72  dst2src_urg_packets           int64
 73  dst2src_ack_packets           int64
 74  dst2src_psh_packets           int64
 75  dst2src_rst_packets           int64
 76  dst2src_fin_packets           int64
 77  application_name              str
 78  application_category_name     str
 79  application_is_guessed        int64
 80  application_confidence        int64
 81  requested_server_name         str
 82  client_fingerprint            str
 83  server_fingerprint            str
 84  user_agent                    str
 85  content_type                  str
 86  flow_key                      str
 87  flow_key_rev                  str
 88  label                         str
 89  dataset_name                  str
dtypes: float64(12), int64(61), str(17)
memory usage: 1.9 GB

In [4]:
display(df.head())

    id  expiration_id         src_ip            src_mac   src_oui  src_port        dst_ip            dst_mac   dst_oui  dst_port  protocol  ip_version  vlan_id  tunnel_id  bidirectional_first_seen_ms  bidirectional_last_seen_ms  bidirectional_duration_ms  bidirectional_packets  bidirectional_bytes  src2dst_first_seen_ms  src2dst_last_seen_ms  src2dst_duration_ms  src2dst_packets  src2dst_bytes  dst2src_first_seen_ms  dst2src_last_seen_ms  dst2src_duration_ms  dst2src_packets  dst2src_bytes  bidirectional_min_ps  bidirectional_mean_ps  bidirectional_stddev_ps  bidirectional_max_ps  src2dst_min_ps  src2dst_mean_ps  src2dst_stddev_ps  src2dst_max_ps  dst2src_min_ps  dst2src_mean_ps  dst2src_stddev_ps  dst2src_max_ps  bidirectional_min_piat_ms  bidirectional_mean_piat_ms  bidirectional_stddev_piat_ms  bidirectional_max_piat_ms  src2dst_min_piat_ms  src2dst_mean_piat_ms  src2dst_stddev_piat_ms  src2dst_max_piat_ms  dst2src_min_piat_ms  dst2src_mean_piat_ms  dst2src_stddev_piat_ms  dst2src_max_piat_ms  bidirectional_syn_packets  bidirectional_cwr_packets  bidirectional_ece_packets  bidirectional_urg_packets  bidirectional_ack_packets  bidirectional_psh_packets  bidirectional_rst_packets  bidirectional_fin_packets  src2dst_syn_packets  src2dst_cwr_packets  src2dst_ece_packets  src2dst_urg_packets  src2dst_ack_packets  src2dst_psh_packets  src2dst_rst_packets  src2dst_fin_packets  dst2src_syn_packets  dst2src_cwr_packets  dst2src_ece_packets  dst2src_urg_packets  dst2src_ack_packets  dst2src_psh_packets  dst2src_rst_packets  dst2src_fin_packets application_name application_category_name  application_is_guessed  application_confidence       requested_server_name client_fingerprint server_fingerprint user_agent content_type                                flow_key                            flow_key_rev   label dataset_name
0   42              0  192.168.10.25  00:25:00:a8:c4:60  00:25:00     54967  192.168.10.3  18:66:da:9b:e3:7d  18:66:da        53        17           4        0          0                1499428842903               1499428842903                          0                      4                  350          1499428842903         1499428842903                    0                2            144          1499428842903         1499428842903                    0                2            206                    72                  87.50                    17.90                   103              72            72.00               0.00              72             103           103.00               0.00             103                          0                        0.00                          0.00                          0                    0                  0.00                    0.00                    0                    0                  0.00                    0.00                    0                          0                          0                          0                          0                          0                          0                          0                          0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0              DNS                   Network                       0                       6  25.10.168.192.in-addr.arpa                NaN                NaN        NaN          NaN  192.168.10.25|192.168.10.3|54967|53|17  192.168.10.3|192.168.10.25|53|54967|17  BENIGN   cicids2017
1   49              0  192.168.10.25  00:25:00:a8:c4:60  00:25:00     53893  192.168.10.3  18:66:da:9b:e3:7d  18:66:da        53        17           4        0          0                1499428841928               1499428841928                          0                      4                  372          1499428841928         1499428841928                    0                2            136          1499428841928         1499428841928                    0                2            236                    68                  93.00                    28.87                   118              68            68.00               0.00              68             118           118.00               0.00             118                          0                        0.00                          0.00                          0                    0                  0.00                    0.00                    0                    0                  0.00                    0.00                    0                          0                          0                          0                          0                          0                          0                          0                          0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0              DNS                   Network                       0                       6      _ldap._tcp.testbed1.ca                NaN                NaN        NaN          NaN  192.168.10.25|192.168.10.3|53893|53|17  192.168.10.3|192.168.10.25|53|53893|17  BENIGN   cicids2017
2   50              0   192.168.10.9  b8:ac:6f:1d:1f:6c  b8:ac:6f     50009  192.168.10.3  18:66:da:9b:e3:7d  18:66:da        53        17           4        0          0                1499428842855               1499428842856                          1                      4                  524          1499428842855         1499428842855                    0                2            262          1499428842856         1499428842856                    0                2            262                   131                 131.00                     0.00                   131             131           131.00               0.00             131             131           131.00               0.00             131                          0                        0.33                          0.58                          1                    0                  0.00                    0.00                    0                    0                  0.00                    0.00                    0                          0                          0                          0                          0                          0                          0                          0                          0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0              DNS                   Network                       0                       6                 testbed1.ca                NaN                NaN        NaN          NaN   192.168.10.9|192.168.10.3|50009|53|17   192.168.10.3|192.168.10.9|53|50009|17  BENIGN   cicids2017
3  107              0  192.168.10.14  b8:ac:6f:36:07:ee  b8:ac:6f     54608  192.168.10.3  18:66:da:9b:e3:7d  18:66:da        53        17           4        0          0                1499428850100               1499428850124                         24                      4                  280          1499428850100         1499428850100                    0                2            124          1499428850124         1499428850124                    0                2            156                    62                  70.00                     9.24                    78              62            62.00               0.00              62              78            78.00               0.00              78                          0                        8.00                         13.86                         24                    0                  0.00                    0.00                    0                    0                  0.00                    0.00                    0                          0                          0                          0                          0                          0                          0                          0                          0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0              DNS                   Network                       0                       6            dns.msftncsi.com                NaN                NaN        NaN          NaN  192.168.10.14|192.168.10.3|54608|53|17  192.168.10.3|192.168.10.14|53|54608|17  BENIGN   cicids2017
4  109              0   192.168.10.5  b8:ac:6f:36:0a:8b  b8:ac:6f     54106  192.168.10.3  18:66:da:9b:e3:7d  18:66:da       389        17           4        0          0                1499428850104               1499428850104                          0                      4                  938          1499428850104         1499428850104                    0                2            556          1499428850104         1499428850104                    0                2            382                   191                 234.50                    50.23                   278             278           278.00               0.00             278             191           191.00               0.00             191                          0                        0.00                          0.00                          0                    0                  0.00                    0.00                    0                    0                  0.00                    0.00                    0                          0                          0                          0                          0                          0                          0                          0                          0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0             LDAP                    System                       0                       6                         NaN                NaN                NaN        NaN          NaN  192.168.10.5|192.168.10.3|54106|389|17  192.168.10.3|192.168.10.5|389|54106|17  BENIGN   cicids2017

In [5]:
df["label"].value_counts()

label
BENIGN                        1777209
DoS Hulk                       160273
PortScan                       158616
DDoS                            75318
DoS GoldenEye                    8340
DoS slowloris                    7306
DoS Slowhttptest                 7256
Bot                              1200
Web Attack  Brute Force         1174
Web Attack  XSS                  611
SSH-Patator                        63
Infiltration                       50
FTP-Patator                        38
Web Attack  Sql Injection          3
Name: count, dtype: int64

In [6]:
(df.isnull().sum() / len(df)) * 100

id                              0.00
expiration_id                   0.00
src_ip                          0.00
src_mac                         0.00
src_oui                         0.00
src_port                        0.00
dst_ip                          0.00
dst_mac                         0.00
dst_oui                         0.00
dst_port                        0.00
protocol                        0.00
ip_version                      0.00
vlan_id                         0.00
tunnel_id                       0.00
bidirectional_first_seen_ms     0.00
bidirectional_last_seen_ms      0.00
bidirectional_duration_ms       0.00
bidirectional_packets           0.00
bidirectional_bytes             0.00
src2dst_first_seen_ms           0.00
src2dst_last_seen_ms            0.00
src2dst_duration_ms             0.00
src2dst_packets                 0.00
src2dst_bytes                   0.00
dst2src_first_seen_ms           0.00
dst2src_last_seen_ms            0.00
dst2src_duration_ms             0.00
dst2src_packets                 0.00
dst2src_bytes                   0.00
bidirectional_min_ps            0.00
bidirectional_mean_ps           0.00
bidirectional_stddev_ps         0.00
bidirectional_max_ps            0.00
src2dst_min_ps                  0.00
src2dst_mean_ps                 0.00
src2dst_stddev_ps               0.00
src2dst_max_ps                  0.00
dst2src_min_ps                  0.00
dst2src_mean_ps                 0.00
dst2src_stddev_ps               0.00
dst2src_max_ps                  0.00
bidirectional_min_piat_ms       0.00
bidirectional_mean_piat_ms      0.00
bidirectional_stddev_piat_ms    0.00
bidirectional_max_piat_ms       0.00
src2dst_min_piat_ms             0.00
src2dst_mean_piat_ms            0.00
src2dst_stddev_piat_ms          0.00
src2dst_max_piat_ms             0.00
dst2src_min_piat_ms             0.00
dst2src_mean_piat_ms            0.00
dst2src_stddev_piat_ms          0.00
dst2src_max_piat_ms             0.00
bidirectional_syn_packets       0.00
bidirectional_cwr_packets       0.00
bidirectional_ece_packets       0.00
bidirectional_urg_packets       0.00
bidirectional_ack_packets       0.00
bidirectional_psh_packets       0.00
bidirectional_rst_packets       0.00
bidirectional_fin_packets       0.00
src2dst_syn_packets             0.00
src2dst_cwr_packets             0.00
src2dst_ece_packets             0.00
src2dst_urg_packets             0.00
src2dst_ack_packets             0.00
src2dst_psh_packets             0.00
src2dst_rst_packets             0.00
src2dst_fin_packets             0.00
dst2src_syn_packets             0.00
dst2src_cwr_packets             0.00
dst2src_ece_packets             0.00
dst2src_urg_packets             0.00
dst2src_ack_packets             0.00
dst2src_psh_packets             0.00
dst2src_rst_packets             0.00
dst2src_fin_packets             0.00
application_name                0.00
application_category_name       0.00
application_is_guessed          0.00
application_confidence          0.00
requested_server_name          50.34
client_fingerprint             89.91
server_fingerprint             89.98
user_agent                     89.96
content_type                   87.22
flow_key                        0.00
flow_key_rev                    0.00
label                           0.00
dataset_name                    0.00
dtype: float64

In [7]:
# busca por registros duplicados
df.duplicated().sum()

np.int64(0)

In [8]:
# visão geral dos dados
df.describe().T

                                  count             mean             std              min              25%              50%              75%              max
id                           2197457.00        325957.43       201131.94            26.00        153081.00        310179.00        481654.00        767048.00
expiration_id                2197457.00             0.00            0.03             0.00             0.00             0.00             0.00             1.00
src_port                     2197457.00         47534.03        15582.09             0.00         41626.00         52234.00         58326.00         65535.00
dst_port                     2197457.00          1148.01         5929.37             0.00            53.00            80.00           443.00         65532.00
protocol                     2197457.00             9.42            5.11             1.00             6.00             6.00            17.00            58.00
ip_version                   2197457.00             4.00            0.08             4.00             4.00             4.00             4.00             6.00
vlan_id                      2197457.00             0.00            0.00             0.00             0.00             0.00             0.00             0.00
tunnel_id                    2197457.00             0.00            0.00             0.00             0.00             0.00             0.00             3.00
bidirectional_first_seen_ms  2197457.00 1499283221875.71    124698819.62 1499082997897.00 1499178735751.00 1499268780058.00 1499429130681.00 1499457760977.00
bidirectional_last_seen_ms   2197457.00 1499283223876.50    124698861.89 1499082999399.00 1499178736903.00 1499268780295.00 1499429132573.00 1499457761169.00
bidirectional_duration_ms    2197457.00          2000.79         7346.77             0.00            23.00            48.00           297.00        119999.00
bidirectional_packets        2197457.00            17.52         1698.87             1.00             2.00             4.00             9.00        509916.00
bidirectional_bytes          2197457.00         15839.74      2285864.93            28.00           104.00           293.00          1119.00     661709099.00
src2dst_first_seen_ms        2197457.00 1499283221875.71    124698819.62 1499082997897.00 1499178735751.00 1499268780058.00 1499429130681.00 1499457760977.00
src2dst_last_seen_ms         2197457.00 1499283223827.98    124698864.83 1499082999399.00 1499178736902.00 1499268780256.00 1499429132452.00 1499457761073.00
src2dst_duration_ms          2197457.00          1952.27         7331.68             0.00             0.00             0.00           237.00        119999.00
src2dst_packets              2197457.00             8.76          881.64             1.00             1.00             2.00             5.00        289583.00
src2dst_bytes                2197457.00          5474.00      1640529.55            28.00            52.00           122.00           352.00     651229990.00
dst2src_first_seen_ms        2197457.00 1450852393636.69 265074134154.28             0.00 1499174136294.00 1499263464655.00 1499369879084.00 1499457761073.00
dst2src_last_seen_ms         2197457.00 1450852395376.30 265074134472.06             0.00 1499174137645.00 1499263467596.00 1499369880286.00 1499457761169.00
dst2src_duration_ms          2197457.00          1739.61         7239.64             0.00             0.00             0.00           156.00        119999.00
dst2src_packets              2197457.00             8.77          833.76             0.00             1.00             2.00             4.00        291259.00
dst2src_bytes                2197457.00         10365.74      1548898.14             0.00            52.00           158.00           516.00     652648491.00
bidirectional_min_ps         2197457.00            54.02           21.27            28.00            40.00            52.00            62.00          1500.00
bidirectional_mean_ps        2197457.00           202.77          281.08            28.00            52.00            82.00           158.00          2166.56
bidirectional_stddev_ps      2197457.00           282.09          601.45             0.00             2.83            20.14           136.83          4413.13
bidirectional_max_ps         2197457.00           957.98         2042.49            28.00            52.00            97.00           329.00         24860.00
src2dst_min_ps               2197457.00            55.21           28.98            28.00            41.00            52.00            62.00          2035.00
src2dst_mean_ps              2197457.00            83.43          118.33            28.00            52.00            61.00            81.11          5868.00
src2dst_stddev_ps            2197457.00            50.75          176.35             0.00             0.00             0.00            18.39          8225.07
src2dst_max_ps               2197457.00           193.96          472.92            28.00            52.00            63.00            90.00         24860.00
dst2src_min_ps               2197457.00            76.28           61.79             0.00            40.00            52.00            94.00          2035.00
dst2src_mean_ps              2197457.00           346.27          616.44             0.00            52.00            88.00           205.00          4422.69
dst2src_stddev_ps            2197457.00           341.72          855.62             0.00             0.00             0.00            31.64          6713.43
dst2src_max_ps               2197457.00           919.74         2017.52             0.00            52.00            93.00           253.00         17428.00
bidirectional_min_piat_ms    2197457.00            23.50          102.85             0.00             0.00             0.00            29.00          9159.00
bidirectional_mean_piat_ms   2197457.00           222.51          596.23             0.00             7.67            25.07            83.00          9159.00
bidirectional_stddev_piat_ms 2197457.00           434.60         1063.00             0.00             0.00             0.00            52.93          7054.10
bidirectional_max_piat_ms    2197457.00          1252.99         2756.68             0.00            23.00            37.00           190.00          9999.00
src2dst_min_piat_ms          2197457.00           171.44         1211.71             0.00             0.00             0.00             0.00         10567.00
src2dst_mean_piat_ms         2197457.00           433.21         1422.97             0.00             0.00             0.00            41.00         10567.00
src2dst_stddev_piat_ms       2197457.00           451.73         1133.55             0.00             0.00             0.00            41.95          7192.69
src2dst_max_piat_ms          2197457.00          1222.80         2760.92             0.00             0.00             0.00           149.00         10702.00
dst2src_min_piat_ms          2197457.00           269.34         1397.38             0.00             0.00             0.00             0.00         31467.00
dst2src_mean_piat_ms         2197457.00           491.95         1581.74             0.00             0.00             0.00            27.00         31467.00
dst2src_stddev_piat_ms       2197457.00           361.24         1088.50             0.00             0.00             0.00            17.34         18156.38
dst2src_max_piat_ms          2197457.00          1074.16         2644.64             0.00             0.00             0.00           124.00         31467.00
bidirectional_syn_packets    2197457.00             0.63            0.97             0.00             0.00             0.00             2.00            51.00
bidirectional_cwr_packets    2197457.00             0.00            0.02             0.00             0.00             0.00             0.00            23.00
bidirectional_ece_packets    2197457.00             0.00            0.04             0.00             0.00             0.00             0.00            12.00
bidirectional_urg_packets    2197457.00             0.00            0.04             0.00             0.00             0.00             0.00            16.00
bidirectional_ack_packets    2197457.00            15.85         1698.87             0.00             0.00             2.00             8.00        509915.00
bidirectional_psh_packets    2197457.00             2.03           23.31             0.00             0.00             0.00             2.00          9814.00
bidirectional_rst_packets    2197457.00             0.29            0.79             0.00             0.00             0.00             0.00           173.00
bidirectional_fin_packets    2197457.00             0.45            0.84             0.00             0.00             0.00             0.00            26.00
src2dst_syn_packets          2197457.00             0.37            0.59             0.00             0.00             0.00             1.00            51.00
src2dst_cwr_packets          2197457.00             0.00            0.02             0.00             0.00             0.00             0.00            23.00
src2dst_ece_packets          2197457.00             0.00            0.02             0.00             0.00             0.00             0.00             4.00
src2dst_urg_packets          2197457.00             0.00            0.04             0.00             0.00             0.00             0.00            16.00
src2dst_ack_packets          2197457.00             7.63          881.64             0.00             0.00             1.00             4.00        289583.00
src2dst_psh_packets          2197457.00             0.95           15.27             0.00             0.00             0.00             1.00          9721.00
src2dst_rst_packets          2197457.00             0.20            0.72             0.00             0.00             0.00             0.00           173.00
src2dst_fin_packets          2197457.00             0.19            0.44             0.00             0.00             0.00             0.00            26.00
dst2src_syn_packets          2197457.00             0.26            0.48             0.00             0.00             0.00             1.00            13.00
dst2src_cwr_packets          2197457.00             0.00            0.00             0.00             0.00             0.00             0.00             2.00
dst2src_ece_packets          2197457.00             0.00            0.03             0.00             0.00             0.00             0.00            10.00
dst2src_urg_packets          2197457.00             0.00            0.00             0.00             0.00             0.00             0.00             0.00
dst2src_ack_packets          2197457.00             8.22          833.76             0.00             0.00             1.00             4.00        291259.00
dst2src_psh_packets          2197457.00             1.08           16.22             0.00             0.00             0.00             1.00          9085.00
dst2src_rst_packets          2197457.00             0.09            0.34             0.00             0.00             0.00             0.00            15.00
dst2src_fin_packets          2197457.00             0.26            0.48             0.00             0.00             0.00             0.00             9.00
application_is_guessed       2197457.00             0.33            0.47             0.00             0.00             0.00             1.00             1.00
application_confidence       2197457.00             3.96            2.53             0.00             1.00             6.00             6.00             7.00

In [10]:
df["bidirectional_duration_ms"].min(), df["bidirectional_duration_ms"].max()

(np.int64(0), np.int64(119999))