In [1]:
from pathlib import Path
from time import perf_counter
import json

import joblib
import pandas as pd
from scipy.stats import loguniform, randint, uniform

from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    f1_score,
    make_scorer,
    precision_score,
    recall_score,
)
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier

from xgboost import XGBClassifier

from src.utils.features import split_features

In [2]:
DATA_DIR = Path("../datasets/final/ml")
SEARCH_METHOD = "randomized_search"
MODEL_DIR = Path("../models") / SEARCH_METHOD
RESULTS_DIR = Path("../results/model_training") / SEARCH_METHOD

MODEL_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 1
N_SPLITS = 5
N_ITER = 12
N_JOBS = -1

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [3]:
#configurações de treinamento / organização / origem dos dados
TRAINING_CONFIGS = {
    "cicids2017": ["cicids2017"],
    "unsw_nb15": ["unsw_nb15"],
    "iot23": ["iot23"],
    "cicids2017_unsw_nb15": ["cicids2017", "unsw_nb15"],
    "cicids2017_iot23": ["cicids2017", "iot23"],
    "unsw_nb15_iot23": ["unsw_nb15", "iot23"],
}

In [4]:
# atributos
reference_df = pd.read_parquet(DATA_DIR / "cicids2017_train.parquet")

numerical_features, categorical_features = split_features(reference_df)
feature_columns = numerical_features + categorical_features

del reference_df

print("features num:", len(numerical_features))
print("features cat:", len(categorical_features))
print("Total de features antes do one-hot:", len(feature_columns))

features num: 14
features cat: 1
Total de features antes do one-hot: 15

In [5]:
#pipeline pré-rocessamento
def build_pipeline(estimator):
    preprocessor = ColumnTransformer(
        transformers=[
            ("numerical", StandardScaler(), numerical_features),
            ("categorical", OneHotEncoder(handle_unknown="ignore"),categorical_features),
        ]
    )

    return Pipeline(
        steps=[ ("preprocessor", preprocessor),
                ("classifier", estimator),
        ]
    )

In [6]:
#modelos e espaços de busca
MODEL_CONFIGS = {
    "decision_tree": {
        "estimator": DecisionTreeClassifier(
            random_state=RANDOM_STATE,
        ),
        "param_distributions": {
            "classifier__max_depth": [None, 3, 5, 8, 10, 15, 20, 30],
            "classifier__min_samples_split": randint(2, 21),
            "classifier__min_samples_leaf": randint(1, 11),
            "classifier__class_weight": [None, "balanced"],
        },
    },
    "random_forest": {
        "estimator": RandomForestClassifier(
            random_state=RANDOM_STATE,
            n_jobs=1,
        ),
        "param_distributions": {
            "classifier__n_estimators": randint(100, 301),
            "classifier__max_depth": [None, 10, 15, 20, 30],
            "classifier__min_samples_leaf": randint(1, 11),
            "classifier__class_weight": [None, "balanced"],
        },
    },
    "xgboost": {
        "estimator": XGBClassifier(
            random_state=RANDOM_STATE,
            n_jobs=1,
            eval_metric="logloss",
            tree_method="hist",
        ),
        "param_distributions": {
            "classifier__n_estimators": randint(100, 301),
            "classifier__max_depth": randint(3, 9),
            "classifier__learning_rate": loguniform(0.03, 0.3),
            "classifier__subsample": uniform(0.7, 0.3),
            "classifier__colsample_bytree": uniform(0.7, 0.3),
        },
    },
    "linear_svm": {
        "estimator": LinearSVC(
            random_state=RANDOM_STATE,
            dual=False,
            max_iter=10000,
        ),
        "param_distributions": {
            "classifier__C": loguniform(1e-3, 1e2),
            "classifier__class_weight": [None, "balanced"],
        },
    },
    "mlp": {
        "estimator": MLPClassifier(
            random_state=RANDOM_STATE,
            max_iter=300,
        ),
        "param_distributions": {
            "classifier__hidden_layer_sizes": [
                (50,),
                (100,),
                (50, 50),
                (100, 50),
            ],
            "classifier__alpha": loguniform(1e-5, 1e-2),
            "classifier__learning_rate_init": loguniform(1e-4, 1e-2),
            "classifier__early_stopping": [True, False],
        },
    },
}

In [7]:
#modelos para rodar
MODELS_TO_RUN = [
    "decision_tree",
    "random_forest",
    "xgboost",
    "linear_svm",
    "mlp",
]

In [8]:
# kfold estratificado + métricas
# buscar: melhores hiperparâmetros através do f1-score
cross_validation = StratifiedKFold(
    n_splits=N_SPLITS,
    shuffle=True,
    random_state=RANDOM_STATE,
)

scoring = {
    #o make_scorer cria um avaliador que calcula a métrica estabelecida, considerando a classe 1 ataque como positiva
    "precision_attack": make_scorer(
        precision_score,
        pos_label=1,
        zero_division=0,
    ),
    "recall_attack": make_scorer(
        recall_score,
        pos_label=1,
        zero_division=0,
    ),
    "f1_attack": make_scorer(
        f1_score,
        pos_label=1,
        zero_division=0,
    ),
    "precision_benign": make_scorer(
        precision_score,
        pos_label=0,
        zero_division=0,
    ),
    "recall_benign": make_scorer(
        recall_score,
        pos_label=0,
        zero_division=0,
    ),
    "f1_benign": make_scorer(
        f1_score,
        pos_label=0,
        zero_division=0,
    ),
    "f1_macro": make_scorer(
        f1_score,
        average="macro",
        labels=[0, 1],
        zero_division=0,
    ),
    "accuracy": "accuracy",
    "balanced_accuracy": "balanced_accuracy",
}

In [9]:
# carregamento de origem de treinamento
def load_training_data(dataset_names):
    columns = feature_columns + ["label_binary"]

    dataframes = []

    for dataset_name in dataset_names:
        #columns=columns (pandas pega apenas colunas necessárias)
        df = pd.read_parquet( DATA_DIR / f"{dataset_name}_train.parquet", columns=columns)
        dataframes.append(df)

    training_df = pd.concat( dataframes, ignore_index=True)

    features = training_df[feature_columns]
    # training_df["label_binary"].eq("ATTACK").astype("int8") -> 1 se equal, 0 se não, ou seja, 1 ataque, 0 benigno
    target = (training_df["label_binary"].eq("ATTACK").astype("int8"))

    return features, target

In [10]:
##treino, validação e save
def serialize_params(params):
    return json.dumps(
        params,
        sort_keys=True,
        default=lambda value: value.item(),
    )


def train_and_select_model(model_name, training_name, dataset_names):
    features, target = load_training_data(dataset_names)
    model_config = MODEL_CONFIGS[model_name]
    model_dir = MODEL_DIR / model_name
    results_dir = RESULTS_DIR / model_name

    model_dir.mkdir(parents=True, exist_ok=True)
    results_dir.mkdir(parents=True, exist_ok=True)

    search = RandomizedSearchCV(
        estimator=build_pipeline(model_config["estimator"]),
        param_distributions=model_config["param_distributions"],
        n_iter=N_ITER,
        scoring=scoring,
        # o refit treina novamente o pipeline com todo o conjunto de treino,
        # usando os melhores hiperparâmetros encontrados segundo o f1 de ataque na validação cruzada.
        refit="f1_attack",
        cv=cross_validation,
        n_jobs=N_JOBS,
        random_state=RANDOM_STATE,
        verbose=1,
        error_score="raise",
        return_train_score=False,
    )

    start = perf_counter()
    search.fit(features, target)
    elapsed_seconds = perf_counter() - start
    elapsed_minutes = elapsed_seconds / 60

    cv_results = pd.DataFrame(search.cv_results_)

    #informações da busca
    candidate_columns = ["params"]
    for metric in scoring:
        candidate_columns.extend(
            f"split{fold}_test_{metric}" for fold in range(N_SPLITS)
        )
        candidate_columns.extend([
            f"mean_test_{metric}",
            f"std_test_{metric}",
            f"rank_test_{metric}",
        ])
    candidate_columns.extend([
        "mean_fit_time",
        "std_fit_time",
        "mean_score_time",
        "std_score_time",
    ])

    candidate_results = cv_results[candidate_columns].copy()
    candidate_results.insert(0, "candidate_id", range(1, len(candidate_results) + 1))
    candidate_results["params"] = candidate_results["params"].map(serialize_params)
    candidate_results = candidate_results.sort_values("rank_test_f1_attack")
    candidate_results.insert(0, "random_state", RANDOM_STATE)
    candidate_results.insert(0, "n_splits", N_SPLITS)
    candidate_results.insert(0, "n_iter", N_ITER)
    candidate_results.insert(0, "training_rows", len(features))
    candidate_results.insert(0, "training_source", training_name)
    candidate_results.insert(0, "search_method", SEARCH_METHOD)
    candidate_results.insert(0, "model", model_name)

    print(f"resultados dos hiperparâmetros: {model_name} - {training_name}")

    #todas as colunas de informações definidas
    display(candidate_results)

    candidate_results.to_csv(
        results_dir / f"{training_name}_candidates.csv",
        index=False,
    )

    model_path = model_dir / f"{training_name}.joblib"
    # salva o pipeline da configuração com maior f1 de ataque na validação cruzada
    joblib.dump(
        search.best_estimator_,
        model_path,
        compress=3,
    )

    best_result = cv_results.loc[search.best_index_]

    result = {
        "model": model_name,
        "search_method": SEARCH_METHOD,
        "training_source": training_name,
        "training_rows": len(features),
        "n_iter": N_ITER,
        "n_splits": N_SPLITS,
        "random_state": RANDOM_STATE,
        "n_candidates": len(cv_results),
        "params": serialize_params(search.best_params_),
        "elapsed_seconds": elapsed_seconds,
        "elapsed_minutes": elapsed_minutes,
        "refit_time_seconds": search.refit_time_,
        "model_size_mb": (
                model_path.stat().st_size / 1024 ** 2
        ),
        "model_file": model_path.name,
    }

    for metric in scoring:
        result[f"{metric}_mean"] = best_result[f"mean_test_{metric}"]
        result[f"{metric}_std"] = best_result[f"std_test_{metric}"]

    return result

In [11]:
# exec
all_results = []

for model_name in MODELS_TO_RUN:
    model_results = []

    for training_name, dataset_names in TRAINING_CONFIGS.items():
        print(f"modelo: {model_name}\n origem do treinamento: {training_name}")

        result = train_and_select_model(
            model_name,
            training_name,
            dataset_names,
        )

        model_results.append(result)
        all_results.append(result)

    results_df = pd.DataFrame(model_results)
    results_df.to_csv(
        RESULTS_DIR / model_name / "summary.csv",
        index=False,
    )

all_results_df = pd.DataFrame(all_results)
display(all_results_df)

modelo: decision_tree
 origem do treinamento: cicids2017
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: decision_tree - cicids2017

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
10,decision_tree,randomized_search,cicids2017,235490,12,5,1,11,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17}",0.980514,0.978607,0.982280,0.979493,0.977034,0.979586,0.001766,2,0.988321,0.990763,0.988641,0.988747,0.989066,0.989108,0.000861,5,0.984402,0.984648,0.985451,0.984098,0.983013,0.984322,0.000794,1,0.997075,0.997684,0.997156,0.997180,0.997258,0.997270,0.000215,5,0.995090,0.994586,0.995541,0.994825,0.994188,0.994846,0.000457,2,0.996081,0.996132,0.996348,0.996001,0.995720,0.996057,0.000204,1,0.990242,0.990390,0.990899,0.990050,0.989367,0.990190,0.000499,1,0.993736,0.993821,0.994161,0.993609,0.993163,0.993698,0.000324,1,0.991706,0.992675,0.992091,0.991786,0.991627,0.991977,0.000383,5,2.450512,0.160435,0.055807,0.011576
6,decision_tree,randomized_search,cicids2017,235490,12,5,1,7,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 19}",0.972142,0.970123,0.974495,0.972847,0.968959,0.971713,0.001966,7,0.996603,0.996284,0.997771,0.996497,0.997452,0.996921,0.000582,1,0.984220,0.983030,0.985995,0.984530,0.982999,0.984155,0.001108,2,0.999145,0.999065,0.999439,0.999119,0.999358,0.999225,0.000146,1,0.992861,0.992330,0.993471,0.993046,0.992011,0.992744,0.000518,7,0.995993,0.995686,0.996446,0.996073,0.995671,0.995974,0.000286,3,0.990107,0.989358,0.991221,0.990302,0.989335,0.990064,0.000697,2,0.993609,0.993121,0.994331,0.993736,0.993099,0.993579,0.000454,3,0.994732,0.994307,0.995621,0.994772,0.994732,0.994833,0.000429,1,3.456787,0.193508,0.090832,0.008524
4,decision_tree,randomized_search,cicids2017,235490,12,5,1,5,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20}",0.982149,0.979014,0.984413,0.981096,0.976208,0.980576,0.002792,1,0.987154,0.990551,0.985563,0.986200,0.988747,0.987643,0.001807,8,0.984645,0.984749,0.984988,0.983641,0.982438,0.984092,0.000946,3,0.996785,0.997631,0.996389,0.996545,0.997178,0.996906,0.000450,8,0.995515,0.994692,0.996099,0.995249,0.993975,0.995106,0.000724,1,0.996149,0.996159,0.996244,0.995897,0.995574,0.996005,0.000245,2,0.990397,0.990454,0.990616,0.989769,0.989006,0.990048,0.000595,3,0.993843,0.993864,0.993991,0.993439,0.992930,0.993613,0.000389,2,0.991334,0.992622,0.990831,0.990724,0.991361,0.991374,0.000675,6,2.897488,0.282924,0.100240,0.010533
3,decision_tree,randomized_search,cicids2017,235490,12,5,1,4,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 20}",0.980105,0.978571,0.982434,0.978932,0.976517,0.979312,0.001943,3,0.988534,0.989065,0.985563,0.986518,0.988854,0.987707,0.001404,7,0.984301,0.983790,0.983996,0.982710,0.982647,0.983489,0.000682,4,0.997128,0.997259,0.996388,0.996623,0.997204,0.996920,0.000349,7,0.994984,0.994586,0.995594,0.994692,0.994055,0.994782,0.000505,3,0.996055,0.995921,0.995991,0.995656,0.995627,0.995850,0.000175,4,0.990178,0.989855,0.989993,0.989183,0.989137,0.989669,0.000428,4,0.993694,0.993482,0.993588,0.993057,0.993015,0.993367,0.000279,4,0.991759,0.991825,0.990578,0.990605,0.991454,0.991244,0.000547,7,2.828473,0.240014,0.097437,0.012305
7,decision_tree,randomized_search,cicids2017,235490,12,5,1,8,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 15}",0.968786,0.969286,0.973643,0.972962,0.973999,0.971735,0.002235,6,0.995116,0.995116,0.996072,0.993206,0.994161,0.994734,0.000974,3,0.981774,0.982032,0.984730,0.982980,0.983977,0.983098,0.001126,5,0.998771,0.998771,0.999012,0.998293,0.998533,0.998676,0.000244,3,0.991985,0.992118,0.993259,0.993099,0.993365,0.992765,0.000590,6,0.995366,0.995433,0.996127,0.995689,0.995942,0.995712,0.000291,5,0.988570,0.988732,0.990429,0.989334,0.989959,0.989405,0.000708,5,0.992611,0.992717,0.993821,0.993121,0.993524,0.993159,0.000462,5,0.993551,0.993617,0.994665,0.993153,0.993763,0.993750,0.000500,2,3.760776,0.218307,0.101882,0.013413
1,decision_tree,randomized_search,cicids2017,235490,12,5,1,2,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 18}",0.966323,0.964638,0.968447,0.974274,0.963373,0.967411,0.003830,8,0.996178,0.996284,0.997028,0.992994,0.996815,0.995860,0.001468,2,0.981024,0.980206,0.982530,0.983545,0.979809,0.981422,0.001412,6,0.999037,0.999063,0.999251,0.998240,0.999197,0.998958,0.000368,2,0.991321,0.990870,0.991879,0.993444,0.990525,0.991608,0.001024,8,0.995164,0.994950,0.995551,0.995836,0.994842,0.995269,0.000373,6,0.988094,0.987578,0.989040,0.989690,0.987326,0.988346,0.000893,6,0.992293,0.991953,0.992908,0.993354,0.991783,0.992458,0.000591,6,0.993750,0.993577,0.994453,0.993219,0.993670,0.993734,0.000403,3,3.736638,0.260741,0.094230,0.007007
9,decision_tree,randomized_search,cicids2017,235490,12,5,1,10,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10}",0.977400,0.976458,0.979546,0.975973,0.975438,0.976963,0.001444,4,0.982588,0.986410,0.981210,0.987473,0.986518,0.984840,0.002468,9,0.979987,0.981409,0.980378,0.981690,0.980947,0.980882,0.000631,7,0.995642,0.996594,0.995300,0.996859,0.996620,0.996203,0.000614,9,0.994320,0.994055,0.994878,0.993922,0.993789,0.994193,0.000385,4,0.994981,0.995323,0.995089,0.995388,0.995203,0.995197,0.000149,7,0.987484,0.988366,0.987733,0.988539,0.988075,0.988039,0.000390,7,0.991974,0.992526,0.992144,0.992632,0.992335,0.992322,0.000241,7,0.988454,0.990233,0.988044,0.990698,0.990154,0.989517,0.001059,8,2.680440,0.256794,0.082202,0.009933
2,decision_tree,randomized_search,cicids2017,235490,12,5,1,3,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 15}",0.956380,0.971939,0.958359,0.961112,0.970732,0.963704,0.006421,9,0.996284,0.992887,0.994374,0.994374,0.992887,0.994161,0.001252,4,0.975924,0.982301,0.976034,0.977460,0.981685,0.978681,0.002765,8,0.999061,0.998212,0.998580,0.998581,0.998212,0.998529,0.000313,4,0.988641,0.992834,0.989198,0.989941,0.992516,0.990626,0.001726,9,0.993824,0.995516,0.993867,0.994242,0.995355,0.994561,0.000731,8,0.984874,0.988909,0.984951,0.985851,0.988520,0.986621,0.001748,8,0.990169,0.992845,0.990233,0.990828,0.992590,0.991333,0.001156,8,0.992462,0.992860,0.991786,0.992157,0.992701,0.992394,0.000385,4,3.279324,0.207990,0.095169,0.014612
5,decision_tree,randomized_search,cicids2017,235490,12,5,1,6,"{""classifier__class_weight"": null, ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 6}",0.976769,0.974070,0.978430,0.972085,0.972088,0.974688,0.002540,5,0.973139,0.981102,0.972718,0.979618,0.979724,0.977260,0.003578,10,0.974951,0.977573,0.975566,0.975837,0.975891,0.975963,0.000871,9,0.993292,0.995267,0.993189,0.994894,0.994921,0.994313,0.000886,10,0.994214,0.993471,0.994639,0.992967,0.992967,0.993652,0.000673,5,0.993753,0.994368,0.993913,0.993930,0.993943,0.993981,0.000205,9,0.984352,0.985971,0.984739,0.984883,0.984917,0.984972,0.000538,9,0.990000,0.990997,0.990254,0.990297,0.990318,0.990373,0.000332,9,0.983677,0.987287,0.983678,0.986292,0.986345,0.985456,0.001494,10,2.283302,0.185747,0.093462,0.010524
0,decision_tree,randomized_search,cicids2017,235490,12,5,1,1,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 11}",0.967826,0.951587,0.965095,0.950947,0.945398,0.956171,0.008716,10,0.980465,0.993311,0.986200,0.985775,0.994374,0.988025,0.005173,6,0.974105,0.972001,0.975533,0.968048,0.969267,0.971791,0.002821,10,0.995101,0.998309,0.996531,0.996411,0.998575,0.996985,0.001294,6,0.991852,0.987367,0.991082,0.987287,0.985641,0.988646,0.002397,10,0.993474,0.992808,0.993799,0.991828,0.992066,0.992795,0.000766,10,0.983789,0.982405,0.984666,0.979938,0.980667,0.982293,0.001793,10,0.989575,0.988556,0.990106,0.986985,0.987388,0.988522,0.001206,10,0.986159,0.990339,0.988641,0.986531,0.990008,0.988335,0.001726,9,2.816376,0.031076,0.085301,0.003497
11,decision_tree,randomized_search,cicids2017,235490,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 9}",0.916145,0.921081,0.917747,0.919369,0.915406,0.917950,0.002078,11,0.917507,0.915702,0.916773,0.915074,0.912102,0.915432,0.001865,12,0.916826,0.918384,0.917260,0.917216,0.913751,0.916687,0.001557,11,0.979371,0.978958,0.979198,0.978792,0.978044,0.978873,0.000459,12,0.979007,0.980387,0.979458,0.979935,0.978927,0.979543,0.000555,11,0.979189,0.979672,0.979328,0.979363,0.978485,0.979207,0.000394,11,0.948007,0.949028,0.948294,0.948290,0.946118,0.947947,0.000975,11,0.966708,0.967451,0.966920,0.966963,0.965561,0.966720,0.000629,11,0.948257,0.948045,0.948115,0.947505,0.945514,0.947487,0.001019,12,0.878415,0.128295,0.073210,0.017804
8,decision_tree,randomized_search,cicids2017,235490,12,5,1,9,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 3}",0.873850,0.875872,0.873810,0.874262,0.872777,0.874114,0.001006,12,0.947977,0.946173,0.945329,0.943312,0.943100,0.945178,0.001825,11,0.909406,0.909666,0.908164,0.907475,0.906577,0.908258,0.001162,12,0.986714,0.986269,0.986046,0.985542,0.985482,0.986010,0.000461,11,0.965790,0.966480,0.965869,0.966081,0.965630,0.965970,0.000294,12,0.976140,0.976274,0.975853,0.975714,0.975455,0.975887,0.000294,12,0.942773,0.942970,0.942008,0.941595,0.941016,0.942072,0.000727,12,0.962228,0.962419,0.961761,0.961527,0.961124,0.961812,0.000469,12,0.956884,0.956326,0.955599,0.954697,0.954365,0.955574,0.000950,11,1.296199,0.078252,0.086372,0.006446

modelo: decision_tree
 origem do treinamento: unsw_nb15
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: decision_tree - unsw_nb15

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
9,decision_tree,randomized_search,unsw_nb15,235490,12,5,1,10,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10}",0.944243,0.944786,0.941147,0.941354,0.942122,0.942730,0.001502,5,0.994267,0.995541,0.994798,0.993418,0.995329,0.994671,0.000767,5,0.968609,0.969500,0.967229,0.966686,0.967995,0.968004,0.000994,1,0.998548,0.998870,0.998681,0.998331,0.998815,0.998649,0.000194,5,0.985323,0.985456,0.984447,0.984527,0.984713,0.984893,0.000417,5,0.991891,0.992118,0.991513,0.991381,0.991714,0.991723,0.000263,1,0.980250,0.980809,0.979371,0.979033,0.979854,0.979864,0.000628,1,0.987112,0.987473,0.986517,0.986305,0.986836,0.986849,0.000416,1,0.989795,0.990499,0.989623,0.988973,0.990021,0.989782,0.000500,5,2.656765,0.148603,0.101530,0.010989
2,decision_tree,randomized_search,unsw_nb15,235490,12,5,1,3,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 15}",0.941784,0.941071,0.936865,0.937961,0.938323,0.939201,0.001894,9,0.997877,0.998620,0.998726,0.998301,0.998089,0.998323,0.000318,1,0.969019,0.968991,0.966807,0.967191,0.967284,0.967859,0.000950,2,0.999461,0.999650,0.999676,0.999568,0.999515,0.999574,0.000081,1,0.984580,0.984368,0.983173,0.983492,0.983598,0.983842,0.000539,9,0.991965,0.991950,0.991356,0.991465,0.991492,0.991646,0.000259,2,0.980492,0.980471,0.979082,0.979328,0.979388,0.979752,0.000604,2,0.987239,0.987218,0.986284,0.986454,0.986496,0.986738,0.000407,2,0.991228,0.991494,0.990950,0.990897,0.990844,0.991082,0.000245,1,3.742907,0.861831,0.091958,0.009393
1,decision_tree,randomized_search,unsw_nb15,235490,12,5,1,2,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 18}",0.943784,0.943444,0.938256,0.940710,0.940215,0.941282,0.002076,6,0.994585,0.995329,0.996921,0.995435,0.995011,0.995456,0.000790,4,0.968519,0.968692,0.966699,0.967299,0.966837,0.967609,0.000839,3,0.998628,0.998816,0.999218,0.998842,0.998734,0.998848,0.000200,4,0.985191,0.985085,0.983598,0.984314,0.984182,0.984474,0.000594,7,0.991864,0.991903,0.991346,0.991525,0.991405,0.991609,0.000232,3,0.980191,0.980297,0.979023,0.979412,0.979121,0.979609,0.000535,3,0.987070,0.987133,0.986263,0.986539,0.986348,0.986670,0.000364,3,0.989888,0.990207,0.990260,0.989875,0.989596,0.989965,0.000243,4,3.952769,0.672464,0.097521,0.009635
6,decision_tree,randomized_search,unsw_nb15,235490,12,5,1,7,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 19}",0.941950,0.941690,0.937344,0.938888,0.936995,0.939374,0.002098,8,0.995753,0.996178,0.997346,0.996497,0.997771,0.996709,0.000745,3,0.968105,0.968168,0.966415,0.966835,0.966428,0.967190,0.000787,4,0.998923,0.999031,0.999326,0.999111,0.999433,0.999165,0.000188,3,0.984660,0.984580,0.983332,0.983784,0.983226,0.983917,0.000605,8,0.991740,0.991753,0.991265,0.991388,0.991264,0.991482,0.000221,4,0.979923,0.979960,0.978840,0.979111,0.978846,0.979336,0.000504,4,0.986878,0.986900,0.986135,0.986326,0.986135,0.986475,0.000345,4,0.990207,0.990379,0.990339,0.990140,0.990498,0.990313,0.000127,3,3.402353,0.429207,0.093689,0.006257
0,decision_tree,randomized_search,unsw_nb15,235490,12,5,1,1,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 11}",0.940776,0.939073,0.936005,0.937806,0.936484,0.938029,0.001742,10,0.996709,0.998195,0.996815,0.997240,0.997028,0.997197,0.000531,2,0.967935,0.967732,0.965453,0.966610,0.965808,0.966708,0.000995,5,0.999165,0.999542,0.999191,0.999299,0.999245,0.999288,0.000135,2,0.984315,0.983811,0.982961,0.983465,0.983094,0.983529,0.000493,10,0.991684,0.991614,0.991009,0.991319,0.991103,0.991346,0.000268,5,0.979810,0.979673,0.978231,0.978964,0.978456,0.979027,0.000631,5,0.986793,0.986687,0.985732,0.986220,0.985881,0.986263,0.000422,5,0.990512,0.991003,0.989888,0.990353,0.990061,0.990363,0.000387,2,3.224799,0.353862,0.105253,0.021346
10,decision_tree,randomized_search,unsw_nb15,235490,12,5,1,11,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17}",0.946430,0.947486,0.944614,0.945261,0.945285,0.945815,0.001020,3,0.986623,0.988428,0.988535,0.982590,0.988535,0.986942,0.002294,8,0.966109,0.967524,0.966075,0.963564,0.966426,0.965940,0.001299,6,0.996620,0.997076,0.997100,0.995604,0.997100,0.996700,0.000578,8,0.986040,0.986305,0.985509,0.985774,0.985695,0.985865,0.000279,3,0.991302,0.991661,0.991270,0.990665,0.991365,0.991253,0.000325,6,0.978705,0.979593,0.978673,0.977115,0.978895,0.978596,0.000812,6,0.986157,0.986730,0.986114,0.985137,0.986263,0.986080,0.000520,6,0.986331,0.987367,0.987022,0.984182,0.987115,0.986403,0.001162,8,2.824810,0.072254,0.062954,0.007678
7,decision_tree,randomized_search,unsw_nb15,235490,12,5,1,8,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 15}",0.945515,0.945182,0.941789,0.941461,0.941378,0.943065,0.001872,4,0.989383,0.990339,0.989278,0.990234,0.990446,0.989936,0.000500,6,0.966952,0.967234,0.964950,0.965232,0.965289,0.965931,0.000960,7,0.997315,0.997556,0.997285,0.997526,0.997580,0.997452,0.000126,6,0.985748,0.985642,0.984713,0.984606,0.984580,0.985058,0.000523,4,0.991498,0.991563,0.990959,0.991024,0.991037,0.991216,0.000259,7,0.979225,0.979398,0.977954,0.978128,0.978163,0.978574,0.000609,7,0.986475,0.986581,0.985626,0.985732,0.985753,0.986033,0.000408,7,0.987566,0.987990,0.986995,0.987420,0.987513,0.987497,0.000318,6,3.452087,0.224758,0.108409,0.017070
5,decision_tree,randomized_search,unsw_nb15,235490,12,5,1,6,"{""classifier__class_weight"": null, ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 6}",0.943022,0.943127,0.940132,0.939911,0.939651,0.941169,0.001564,7,0.989277,0.987684,0.995223,0.988004,0.988429,0.989724,0.002801,7,0.965596,0.964891,0.966894,0.963358,0.963423,0.964832,0.001341,8,0.997286,0.996885,0.998788,0.996962,0.997069,0.997398,0.000708,7,0.985058,0.985111,0.984155,0.984208,0.984129,0.984532,0.000452,6,0.991134,0.990963,0.991418,0.990544,0.990557,0.990923,0.000337,8,0.978365,0.977927,0.979156,0.976951,0.976990,0.977878,0.000839,8,0.985902,0.985626,0.986369,0.984968,0.984989,0.985571,0.000539,8,0.987167,0.986398,0.989689,0.986106,0.986279,0.987128,0.001331,7,2.281528,0.228907,0.091522,0.005407
3,decision_tree,randomized_search,unsw_nb15,235490,12,5,1,4,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 20}",0.948855,0.949423,0.946552,0.945566,0.947757,0.947631,0.001425,2,0.980890,0.978554,0.977601,0.979193,0.980255,0.979299,0.001174,9,0.964606,0.963768,0.961826,0.962086,0.963732,0.963204,0.001069,9,0.995182,0.994597,0.994354,0.994751,0.995021,0.994781,0.000295,9,0.986783,0.986969,0.986199,0.985907,0.986491,0.986470,0.000384,2,0.990965,0.990768,0.990259,0.990309,0.990737,0.990608,0.000276,9,0.977786,0.977268,0.976043,0.976198,0.977235,0.976906,0.000672,9,0.985604,0.985286,0.984479,0.984564,0.985244,0.985035,0.000439,9,0.983836,0.982761,0.981900,0.982550,0.983373,0.982884,0.000669,9,3.053549,0.355647,0.092416,0.009710
4,decision_tree,randomized_search,unsw_nb15,235490,12,5,1,5,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20}",0.950299,0.950320,0.947944,0.947303,0.947774,0.948728,0.001308,1,0.978448,0.978872,0.976221,0.971338,0.978662,0.976708,0.002850,10,0.964168,0.964385,0.961874,0.959170,0.962971,0.962514,0.001899,10,0.994572,0.994679,0.994010,0.992788,0.994621,0.994134,0.000714,10,0.987208,0.987208,0.986597,0.986491,0.986517,0.986804,0.000331,1,0.990876,0.990929,0.990290,0.989630,0.990553,0.990455,0.000473,10,0.977522,0.977657,0.976082,0.974400,0.976762,0.976484,0.001186,10,0.985456,0.985541,0.984522,0.983460,0.984946,0.984785,0.000758,10,0.982828,0.983040,0.981409,0.978914,0.982590,0.981756,0.001529,10,2.997566,0.326900,0.089619,0.006094
11,decision_tree,randomized_search,unsw_nb15,235490,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 9}",0.851349,0.853941,0.845585,0.851342,0.850480,0.850539,0.002736,11,0.931521,0.930460,0.934183,0.932590,0.931104,0.931972,0.001305,12,0.889632,0.890560,0.887678,0.890116,0.888968,0.889391,0.001006,11,0.982469,0.982218,0.983102,0.982735,0.982357,0.982576,0.000313,12,0.959341,0.960217,0.957349,0.959287,0.959074,0.959053,0.000938,11,0.970767,0.971093,0.970055,0.970869,0.970576,0.970672,0.000351,11,0.930200,0.930826,0.928867,0.930493,0.929772,0.930031,0.000678,11,0.953777,0.954266,0.952716,0.953947,0.953480,0.953637,0.000526,11,0.945431,0.945338,0.945766,0.945938,0.945089,0.945513,0.000304,12,1.003792,0.094997,0.081865,0.014948
8,decision_tree,randomized_search,unsw_nb15,235490,12,5,1,9,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 3}",0.786126,0.791627,0.782883,0.788548,0.785230,0.786883,0.002986,12,0.970910,0.971653,0.974947,0.970701,0.970701,0.971782,0.001621,11,0.868801,0.872450,0.868422,0.870194,0.868170,0.869607,0.001584,12,0.992274,0.992487,0.993327,0.992226,0.992215,0.992506,0.000422,11,0.933969,0.936065,0.932401,0.934922,0.933622,0.934196,0.001235,12,0.962239,0.963451,0.961900,0.962722,0.962027,0.962468,0.000566,12,0.915520,0.917950,0.915161,0.916458,0.915098,0.916038,0.001073,12,0.941356,0.943182,0.940910,0.942078,0.941038,0.941713,0.000839,12,0.952439,0.953859,0.953674,0.952811,0.952161,0.952989,0.000670,11,1.302846,0.118002,0.093945,0.009500

modelo: decision_tree
 origem do treinamento: iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: decision_tree - iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
5,decision_tree,randomized_search,iot23,235490,12,5,1,6,"{""classifier__class_weight"": null, ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 6}",0.999359,0.999465,0.999358,0.999680,0.999786,0.999530,0.000174,1,0.993842,0.992037,0.992144,0.994480,0.993524,0.993206,0.000961,11,0.996593,0.995737,0.995738,0.997073,0.996646,0.996358,0.000533,1,0.998463,0.998013,0.998040,0.998622,0.998384,0.998304,0.000240,11,0.999841,0.999867,0.999841,0.999920,0.999947,0.999883,0.000043,1,0.999151,0.998939,0.998939,0.999271,0.999165,0.999093,0.000132,1,0.997872,0.997338,0.997339,0.998172,0.997905,0.997725,0.000332,1,0.998641,0.998301,0.998301,0.998832,0.998662,0.998548,0.000212,1,0.996841,0.995952,0.995993,0.997200,0.996736,0.996544,0.000492,8,1.234480,0.127598,0.110278,0.010298
9,decision_tree,randomized_search,iot23,235490,12,5,1,10,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10}",0.999253,0.998931,0.999465,0.999680,0.999466,0.999359,0.000253,2,0.993842,0.992250,0.992357,0.994480,0.993843,0.993354,0.000890,8,0.996540,0.995579,0.995898,0.997073,0.996647,0.996347,0.000538,2,0.998463,0.998066,0.998092,0.998622,0.998463,0.998341,0.000222,8,0.999814,0.999735,0.999867,0.999920,0.999867,0.999841,0.000063,2,0.999138,0.998900,0.998979,0.999271,0.999165,0.999090,0.000133,2,0.997839,0.997239,0.997439,0.998172,0.997906,0.997719,0.000336,2,0.998620,0.998238,0.998365,0.998832,0.998662,0.998543,0.000214,2,0.996828,0.995992,0.996112,0.997200,0.996855,0.996598,0.000466,7,1.360995,0.127659,0.100521,0.012036
10,decision_tree,randomized_search,iot23,235490,12,5,1,11,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17}",0.999573,0.998931,0.999252,0.999467,0.999359,0.999316,0.000220,3,0.993736,0.992356,0.992357,0.994798,0.993631,0.993376,0.000927,7,0.996646,0.995633,0.995792,0.997127,0.996487,0.996337,0.000554,3,0.998436,0.998092,0.998092,0.998701,0.998410,0.998346,0.000231,7,0.999894,0.999735,0.999814,0.999867,0.999841,0.999830,0.000055,3,0.999165,0.998913,0.998953,0.999284,0.999125,0.999088,0.000138,3,0.997905,0.997273,0.997372,0.998205,0.997806,0.997712,0.000346,3,0.998662,0.998259,0.998323,0.998853,0.998599,0.998539,0.000220,3,0.996815,0.996045,0.996085,0.997333,0.996736,0.996603,0.000485,6,1.322553,0.094854,0.091289,0.019809
4,decision_tree,randomized_search,iot23,235490,12,5,1,5,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20}",0.999253,0.999358,0.999145,0.999360,0.998933,0.999210,0.000160,4,0.993630,0.992356,0.992038,0.994586,0.993524,0.993227,0.000924,9,0.996433,0.995845,0.995579,0.996967,0.996221,0.996209,0.000481,4,0.998410,0.998092,0.998013,0.998648,0.998383,0.998309,0.000230,9,0.999814,0.999841,0.999788,0.999841,0.999735,0.999804,0.000040,4,0.999112,0.998966,0.998900,0.999244,0.999058,0.999056,0.000119,4,0.997772,0.997405,0.997239,0.998106,0.997640,0.997632,0.000300,4,0.998577,0.998344,0.998238,0.998790,0.998493,0.998488,0.000191,4,0.996722,0.996098,0.995913,0.997213,0.996630,0.996515,0.000465,9,1.504421,0.229349,0.107868,0.009648
3,decision_tree,randomized_search,iot23,235490,12,5,1,4,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 20}",0.999253,0.999145,0.999145,0.999147,0.998720,0.999082,0.000186,5,0.993524,0.992356,0.992038,0.994586,0.993631,0.993227,0.000924,10,0.996380,0.995739,0.995579,0.996861,0.996169,0.996145,0.000459,5,0.998383,0.998092,0.998013,0.998648,0.998410,0.998309,0.000230,10,0.999814,0.999788,0.999788,0.999788,0.999682,0.999772,0.000046,5,0.999098,0.998939,0.998900,0.999217,0.999045,0.999040,0.000114,5,0.997739,0.997339,0.997239,0.998039,0.997607,0.997593,0.000287,5,0.998556,0.998301,0.998238,0.998747,0.998471,0.998463,0.000182,5,0.996669,0.996072,0.995913,0.997187,0.996656,0.996499,0.000459,10,1.295706,0.100252,0.107019,0.012465
2,decision_tree,randomized_search,iot23,235490,12,5,1,3,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 15}",0.988333,0.986362,0.988319,0.987606,0.985439,0.987212,0.001141,7,0.998301,0.998195,0.997028,0.998195,0.998620,0.998068,0.000543,5,0.993292,0.992243,0.992654,0.992873,0.991986,0.992610,0.000461,6,0.999574,0.999547,0.999255,0.999548,0.999654,0.999516,0.000136,4,0.997054,0.996550,0.997054,0.996868,0.996311,0.996767,0.000293,7,0.998313,0.998046,0.998153,0.998206,0.997980,0.998140,0.000117,6,0.995802,0.995145,0.995404,0.995539,0.994983,0.995375,0.000289,6,0.997303,0.996879,0.997049,0.997134,0.996773,0.997027,0.000187,6,0.997678,0.997372,0.997041,0.997532,0.997465,0.997418,0.000213,2,1.753818,0.362811,0.122611,0.037497
0,decision_tree,randomized_search,iot23,235490,12,5,1,1,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 11}",0.987400,0.986050,0.988114,0.988124,0.985128,0.986963,0.001189,8,0.998407,0.998089,0.997240,0.998089,0.998514,0.998068,0.000447,4,0.992873,0.992033,0.992656,0.993082,0.991776,0.992484,0.000499,7,0.999601,0.999521,0.999308,0.999521,0.999627,0.999516,0.000112,5,0.996815,0.996470,0.997001,0.997001,0.996231,0.996704,0.000306,8,0.998206,0.997993,0.998153,0.998259,0.997926,0.998108,0.000127,7,0.995540,0.995013,0.995405,0.995670,0.994851,0.995296,0.000313,7,0.997134,0.996794,0.997049,0.997219,0.996688,0.996977,0.000203,7,0.997611,0.997280,0.997120,0.997545,0.997373,0.997386,0.000178,4,1.413669,0.083515,0.106195,0.018635
7,decision_tree,randomized_search,iot23,235490,12,5,1,8,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 15}",0.987612,0.985842,0.987491,0.986781,0.985957,0.986736,0.000741,10,0.998726,0.997983,0.997240,0.998514,0.998726,0.998238,0.000568,1,0.993138,0.991875,0.992341,0.992613,0.992300,0.992453,0.000416,8,0.999681,0.999494,0.999308,0.999627,0.999680,0.999558,0.000142,1,0.996868,0.996417,0.996842,0.996656,0.996444,0.996645,0.000190,10,0.998272,0.997953,0.998073,0.998139,0.998059,0.998100,0.000105,8,0.995705,0.994914,0.995207,0.995376,0.995180,0.995277,0.000260,8,0.997240,0.996730,0.996921,0.997027,0.996900,0.996964,0.000168,8,0.997797,0.997200,0.997041,0.997585,0.997585,0.997442,0.000278,1,1.608558,0.164431,0.110649,0.013031
1,decision_tree,randomized_search,iot23,235490,12,5,1,2,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 18}",0.987609,0.985945,0.987902,0.986678,0.985854,0.986798,0.000838,9,0.998514,0.997983,0.996921,0.998514,0.998726,0.998132,0.000653,3,0.993031,0.991927,0.992391,0.992561,0.992248,0.992432,0.000365,9,0.999627,0.999494,0.999229,0.999627,0.999680,0.999532,0.000164,2,0.996868,0.996444,0.996948,0.996629,0.996417,0.996661,0.000216,9,0.998246,0.997967,0.998087,0.998126,0.998046,0.998094,0.000092,9,0.995639,0.994947,0.995239,0.995343,0.995147,0.995263,0.000229,9,0.997197,0.996751,0.996943,0.997006,0.996879,0.996955,0.000147,9,0.997691,0.997213,0.996935,0.997572,0.997572,0.997396,0.000281,3,1.827644,0.350102,0.114747,0.021589
6,decision_tree,randomized_search,iot23,235490,12,5,1,7,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 19}",0.987400,0.985226,0.987591,0.986882,0.983586,0.986137,0.001523,11,0.998407,0.998301,0.996921,0.998301,0.998726,0.998132,0.000625,2,0.992873,0.991721,0.992234,0.992559,0.991098,0.992097,0.000628,10,0.999601,0.999574,0.999228,0.999574,0.999680,0.999532,0.000156,3,0.996815,0.996258,0.996868,0.996682,0.995833,0.996491,0.000393,11,0.998206,0.997913,0.998047,0.998126,0.997753,0.998009,0.000160,10,0.995540,0.994817,0.995141,0.995343,0.994426,0.995053,0.000394,10,0.997134,0.996667,0.996879,0.997006,0.996412,0.996819,0.000256,10,0.997611,0.997280,0.996895,0.997492,0.997280,0.997311,0.000244,5,1.764738,0.283758,0.118562,0.027766
11,decision_tree,randomized_search,iot23,235490,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 9}",0.991782,0.991774,0.988946,0.991056,0.993172,0.991346,0.001382,6,0.986623,0.985561,0.987686,0.988110,0.988217,0.987239,0.001011,12,0.989196,0.988658,0.988315,0.989581,0.990688,0.989288,0.000824,11,0.996660,0.996396,0.996922,0.997030,0.997058,0.996813,0.000251,12,0.997956,0.997956,0.997240,0.997771,0.998301,0.997845,0.000348,6,0.997308,0.997176,0.997081,0.997400,0.997679,0.997329,0.000206,11,0.993252,0.992917,0.992698,0.993491,0.994184,0.993308,0.000515,11,0.995690,0.995478,0.995329,0.995838,0.996284,0.995724,0.000330,11,0.992290,0.991759,0.992463,0.992940,0.993259,0.992542,0.000521,12,0.663602,0.078056,0.073015,0.019892
8,decision_tree,randomized_search,iot23,235490,12,5,1,9,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 3}",0.975838,0.977648,0.976126,0.966112,0.965439,0.972233,0.005312,12,0.994798,0.993736,0.993949,0.998726,0.999363,0.996114,0.002427,6,0.985227,0.985626,0.984957,0.982148,0.982108,0.984013,0.001554,12,0.998693,0.998428,0.998480,0.999679,0.999839,0.999024,0.000609,6,0.993843,0.994320,0.993922,0.991242,0.991056,0.992877,0.001421,12,0.996262,0.996370,0.996196,0.995442,0.995428,0.995940,0.000416,12,0.990744,0.990998,0.990576,0.988795,0.988768,0.989977,0.000985,12,0.994034,0.994204,0.993928,0.992739,0.992717,0.993524,0.000656,12,0.994320,0.994028,0.993936,0.994984,0.995209,0.994495,0.000512,11,0.956549,0.161470,0.113342,0.009641

modelo: decision_tree
 origem do treinamento: cicids2017_unsw_nb15
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: decision_tree - cicids2017_unsw_nb15

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
10,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,11,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17}",0.959821,0.961334,0.958213,0.962188,0.960266,0.960364,0.001356,3,0.987791,0.988481,0.985933,0.986040,0.987739,0.987197,0.001023,5,0.973605,0.974719,0.971876,0.973968,0.973809,0.973595,0.000938,1,0.996925,0.997100,0.996458,0.996488,0.996912,0.996777,0.000257,5,0.989663,0.990061,0.989251,0.990313,0.989782,0.989814,0.000361,4,0.993281,0.993568,0.992841,0.993391,0.993334,0.993283,0.000241,1,0.983443,0.984143,0.982358,0.983679,0.983572,0.983439,0.000590,1,0.989288,0.989745,0.988588,0.989458,0.989373,0.989290,0.000384,1,0.988727,0.989271,0.987592,0.988176,0.988760,0.988505,0.000573,5,5.776203,0.171531,0.087471,0.011633
7,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,8,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 15}",0.952692,0.955920,0.955022,0.956726,0.954815,0.955035,0.001355,5,0.991985,0.993418,0.991825,0.992834,0.992622,0.992537,0.000580,3,0.971941,0.974308,0.973076,0.974446,0.973351,0.973424,0.000911,2,0.997975,0.998338,0.997937,0.998191,0.998137,0.998116,0.000147,3,0.987685,0.988548,0.988322,0.988773,0.988256,0.988317,0.000365,6,0.992804,0.993419,0.993106,0.993460,0.993172,0.993192,0.000237,2,0.982372,0.983864,0.983091,0.983953,0.983262,0.983308,0.000574,2,0.988545,0.989522,0.989023,0.989586,0.989129,0.989161,0.000377,2,0.989835,0.990983,0.990074,0.990804,0.990439,0.990427,0.000430,3,7.908791,0.322247,0.161123,0.016495
6,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,7,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 19}",0.951713,0.951934,0.950629,0.954349,0.952163,0.952158,0.001215,8,0.993896,0.995541,0.994480,0.995382,0.995223,0.994904,0.000622,1,0.972347,0.973249,0.972060,0.974434,0.973217,0.973061,0.000831,3,0.998457,0.998872,0.998604,0.998833,0.998792,0.998712,0.000157,1,0.987393,0.987433,0.987088,0.988097,0.987499,0.987502,0.000329,9,0.992894,0.993120,0.992813,0.993436,0.993114,0.993075,0.000217,3,0.982621,0.983185,0.982436,0.983935,0.983165,0.983068,0.000524,3,0.988694,0.989055,0.988566,0.989554,0.989044,0.988983,0.000344,3,0.990644,0.991487,0.990784,0.991739,0.991361,0.991203,0.000420,1,7.837660,0.470022,0.149299,0.009442
1,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,2,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 18}",0.950416,0.954215,0.949924,0.956584,0.952044,0.952637,0.002478,7,0.994055,0.995647,0.993843,0.994108,0.993684,0.994267,0.000707,2,0.971746,0.974491,0.971387,0.974985,0.972418,0.973005,0.001461,4,0.998496,0.998900,0.998443,0.998512,0.998403,0.998551,0.000179,2,0.987035,0.988057,0.986902,0.988720,0.987486,0.987640,0.000674,8,0.992733,0.993449,0.992639,0.993592,0.992915,0.993065,0.000385,4,0.982239,0.983970,0.982013,0.984289,0.982667,0.983035,0.000923,4,0.988439,0.989575,0.988290,0.989798,0.988726,0.988966,0.000609,4,0.990545,0.991852,0.990372,0.991414,0.990585,0.990954,0.000576,2,8.576774,0.728882,0.168289,0.020685
3,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,4,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 20}",0.961352,0.963699,0.959699,0.963404,0.962670,0.962165,0.001476,2,0.981050,0.980785,0.980891,0.982377,0.982803,0.981581,0.000839,8,0.971101,0.972167,0.970179,0.972798,0.972632,0.971775,0.000994,5,0.995238,0.995175,0.995196,0.995573,0.995678,0.995372,0.000210,8,0.990140,0.990764,0.989702,0.990671,0.990472,0.990350,0.000388,3,0.992683,0.992964,0.992442,0.993116,0.993068,0.992855,0.000255,5,0.981892,0.982566,0.981310,0.982957,0.982850,0.982315,0.000624,5,0.988322,0.988768,0.987940,0.989012,0.988938,0.988596,0.000406,5,0.985595,0.985774,0.985297,0.986524,0.986637,0.985965,0.000526,7,6.555060,0.390401,0.152366,0.008308
4,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,5,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20}",0.961619,0.964060,0.960266,0.963605,0.963102,0.962530,0.001399,1,0.980148,0.979617,0.981368,0.982377,0.980892,0.980880,0.000960,9,0.970795,0.971776,0.970703,0.972901,0.971915,0.971618,0.000809,6,0.995013,0.994884,0.995316,0.995573,0.995201,0.995197,0.000240,9,0.990220,0.990870,0.989848,0.990724,0.990605,0.990453,0.000372,2,0.992611,0.992873,0.992575,0.993143,0.992897,0.992820,0.000208,6,0.981703,0.982324,0.981639,0.983022,0.982406,0.982219,0.000509,6,0.988205,0.988619,0.988152,0.989055,0.988662,0.988539,0.000331,6,0.985184,0.985243,0.985608,0.986551,0.985748,0.985667,0.000491,8,7.075056,0.585684,0.161253,0.015222
9,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,10,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10}",0.956266,0.956878,0.956255,0.958596,0.957986,0.957196,0.000942,4,0.984235,0.984713,0.982802,0.984394,0.982749,0.983779,0.000833,7,0.970049,0.970596,0.969346,0.971324,0.970210,0.970305,0.000651,7,0.996030,0.996150,0.995670,0.996072,0.995659,0.995916,0.000209,7,0.988747,0.988906,0.988760,0.989371,0.989224,0.989002,0.000252,5,0.992375,0.992515,0.992203,0.992710,0.992431,0.992447,0.000167,7,0.981212,0.981555,0.980775,0.982017,0.981321,0.981376,0.000409,7,0.987844,0.988067,0.987568,0.988375,0.987929,0.987957,0.000265,7,0.986491,0.986809,0.985781,0.986882,0.985987,0.986390,0.000439,6,5.953899,0.447167,0.128641,0.012910
2,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,3,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 15}",0.943151,0.949438,0.941494,0.943402,0.944647,0.944426,0.002700,9,0.993365,0.990764,0.991719,0.992728,0.991879,0.992091,0.000891,4,0.967607,0.969661,0.965954,0.967437,0.967687,0.967669,0.001180,8,0.998319,0.997666,0.997902,0.998158,0.997944,0.997998,0.000224,4,0.985031,0.986809,0.984593,0.985111,0.985469,0.985403,0.000757,10,0.991631,0.992208,0.991203,0.991591,0.991667,0.991660,0.000321,8,0.979619,0.980934,0.978578,0.979514,0.979677,0.979665,0.000751,8,0.986698,0.987600,0.986019,0.986634,0.986751,0.986740,0.000505,8,0.989198,0.988787,0.988156,0.988919,0.988674,0.988747,0.000343,4,6.729770,0.743027,0.143228,0.015506
5,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,6,"{""classifier__class_weight"": null, ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 6}",0.953228,0.953805,0.954739,0.952499,0.954652,0.953785,0.000852,6,0.977971,0.978714,0.975264,0.979245,0.976592,0.977557,0.001453,10,0.965441,0.966099,0.964892,0.965687,0.965497,0.965523,0.000391,9,0.994457,0.994644,0.993783,0.994775,0.994114,0.994354,0.000362,10,0.988004,0.988150,0.988442,0.987791,0.988402,0.988158,0.000244,7,0.991220,0.991386,0.991105,0.991271,0.991250,0.991246,0.000090,9,0.978331,0.978743,0.977999,0.978479,0.978373,0.978385,0.000240,9,0.985997,0.986263,0.985806,0.986082,0.986040,0.986038,0.000147,9,0.982987,0.983432,0.981853,0.983518,0.982497,0.982858,0.000620,10,4.696239,0.216385,0.160434,0.016307
0,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,1,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 11}",0.938109,0.943400,0.931876,0.934594,0.941997,0.937995,0.004342,10,0.985615,0.985615,0.986783,0.989065,0.986146,0.986645,0.001284,6,0.961276,0.964046,0.958544,0.961058,0.963566,0.961698,0.001977,10,0.996358,0.996363,0.996646,0.997226,0.996495,0.996618,0.000322,6,0.983744,0.985217,0.981966,0.982696,0.984819,0.983688,0.001230,11,0.990011,0.990759,0.989252,0.989907,0.990623,0.990110,0.000542,10,0.975643,0.977402,0.973898,0.975483,0.977094,0.975904,0.001260,10,0.984118,0.985297,0.982929,0.983970,0.985084,0.984280,0.000852,10,0.984679,0.985416,0.984374,0.985880,0.985483,0.985167,0.000554,9,6.325920,0.486892,0.160443,0.017503
8,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,9,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 3}",0.553461,0.553332,0.548304,0.551048,0.546104,0.550450,0.002871,12,0.944636,0.945061,0.941451,0.946600,0.941189,0.943787,0.002120,11,0.697978,0.697991,0.693002,0.696588,0.691171,0.695346,0.002771,11,0.983189,0.983312,0.982166,0.983731,0.982050,0.982889,0.000664,11,0.809467,0.809281,0.806110,0.807198,0.804422,0.807295,0.001915,12,0.887910,0.887849,0.885471,0.886764,0.884405,0.886480,0.001366,12,0.792944,0.792920,0.789237,0.791676,0.787788,0.790913,0.002064,11,0.836500,0.836437,0.833178,0.835078,0.831776,0.834594,0.001855,12,0.877052,0.877171,0.873780,0.876899,0.872805,0.875541,0.001864,11,2.746072,0.122179,0.166882,0.020552
11,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 9}",0.919250,0.918819,0.921448,0.921038,0.917730,0.919657,0.001393,11,0.426615,0.434365,0.429641,0.437125,0.435191,0.432587,0.003870,12,0.582771,0.589872,0.586033,0.592873,0.590408,0.588392,0.003563,12,0.873591,0.875062,0.874198,0.875620,0.875196,0.874734,0.000735,12,0.990631,0.990406,0.990844,0.990631,0.990246,0.990552,0.000206,1,0.928437,0.929168,0.928873,0.929582,0.929174,0.929047,0.000379,11,0.755604,0.759520,0.757453,0.761227,0.759791,0.758719,0.001969,12,0.877829,0.879199,0.878604,0.879931,0.879231,0.878959,0.000704,11,0.708623,0.712385,0.710242,0.713878,0.712719,0.711569,0.001885,12,1.856700,0.215353,0.126606,0.009642

modelo: decision_tree
 origem do treinamento: cicids2017_iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: decision_tree - cicids2017_iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
3,decision_tree,randomized_search,cicids2017_iot23,470980,12,5,1,4,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 20}",0.987926,0.986884,0.987813,0.988827,0.989295,0.988149,0.000841,2,0.990233,0.990498,0.989543,0.991188,0.990870,0.990467,0.000564,6,0.989078,0.988688,0.988677,0.990006,0.990082,0.989306,0.000620,1,0.997557,0.997622,0.997385,0.997796,0.997717,0.997615,0.000141,6,0.996974,0.996709,0.996948,0.997200,0.997319,0.997030,0.000212,4,0.997266,0.997166,0.997166,0.997498,0.997518,0.997323,0.000156,1,0.993172,0.992927,0.992922,0.993752,0.993800,0.993314,0.000388,1,0.995626,0.995467,0.995467,0.995998,0.996030,0.995717,0.000249,1,0.993604,0.993604,0.993245,0.994194,0.994095,0.993748,0.000350,4,5.765782,0.193340,0.149283,0.005410
4,decision_tree,randomized_search,cicids2017_iot23,470980,12,5,1,5,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20}",0.988185,0.987820,0.988019,0.988615,0.990017,0.988531,0.000788,1,0.990074,0.990127,0.989278,0.991029,0.989597,0.990021,0.000594,7,0.989129,0.988972,0.988648,0.989821,0.989807,0.989275,0.000466,2,0.997517,0.997530,0.997319,0.997756,0.997399,0.997504,0.000148,7,0.997041,0.996948,0.997001,0.997147,0.997505,0.997128,0.000199,1,0.997279,0.997239,0.997160,0.997451,0.997452,0.997316,0.000117,2,0.993204,0.993105,0.992904,0.993636,0.993629,0.993296,0.000292,2,0.995647,0.995584,0.995456,0.995923,0.995923,0.995707,0.000187,2,0.993557,0.993537,0.993139,0.994088,0.993551,0.993575,0.000302,7,6.167660,0.981651,0.176236,0.033604
10,decision_tree,randomized_search,cicids2017_iot23,470980,12,5,1,11,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17}",0.987043,0.986983,0.987510,0.988202,0.989076,0.987763,0.000788,4,0.990711,0.990127,0.990445,0.991507,0.990021,0.990562,0.000531,5,0.988874,0.988553,0.988975,0.989852,0.989549,0.989160,0.000472,3,0.997676,0.997530,0.997610,0.997875,0.997505,0.997639,0.000133,5,0.996749,0.996736,0.996868,0.997041,0.997266,0.996932,0.000200,5,0.997212,0.997133,0.997239,0.997458,0.997385,0.997285,0.000119,3,0.993043,0.992843,0.993107,0.993655,0.993467,0.993223,0.000295,3,0.995541,0.995414,0.995584,0.995934,0.995817,0.995658,0.000190,3,0.993730,0.993431,0.993657,0.994274,0.993644,0.993747,0.000282,5,4.996929,0.282501,0.095051,0.017670
7,decision_tree,randomized_search,cicids2017_iot23,470980,12,5,1,8,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 15}",0.979293,0.979105,0.978587,0.977266,0.980214,0.978893,0.000969,7,0.996603,0.997399,0.997027,0.997134,0.996603,0.996953,0.000311,3,0.987872,0.988167,0.987721,0.987100,0.988341,0.987840,0.000429,4,0.999147,0.999347,0.999253,0.999280,0.999147,0.999235,0.000078,3,0.994732,0.994679,0.994546,0.994201,0.994971,0.994626,0.000253,7,0.996934,0.997007,0.996894,0.996734,0.997054,0.996925,0.000111,4,0.992403,0.992587,0.992308,0.991917,0.992698,0.992382,0.000270,4,0.995106,0.995223,0.995042,0.994787,0.995297,0.995091,0.000176,4,0.995667,0.996039,0.995787,0.995667,0.995787,0.995789,0.000136,2,7.066774,0.673297,0.162092,0.021872
6,decision_tree,randomized_search,cicids2017_iot23,470980,12,5,1,7,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 19}",0.979544,0.977424,0.977526,0.978031,0.978191,0.978143,0.000758,8,0.996390,0.997399,0.997399,0.997240,0.997505,0.997187,0.000407,2,0.987895,0.987311,0.987362,0.987542,0.987754,0.987573,0.000224,5,0.999094,0.999346,0.999346,0.999307,0.999373,0.999293,0.000102,2,0.994798,0.994241,0.994267,0.994400,0.994440,0.994429,0.000199,8,0.996941,0.996787,0.996800,0.996847,0.996900,0.996855,0.000059,5,0.992418,0.992049,0.992081,0.992195,0.992327,0.992214,0.000141,5,0.995117,0.994872,0.994894,0.994968,0.995053,0.994981,0.000093,5,0.995594,0.995820,0.995833,0.995820,0.995973,0.995808,0.000121,1,6.804613,0.880197,0.172788,0.012516
1,decision_tree,randomized_search,cicids2017_iot23,470980,12,5,1,2,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 18}",0.976757,0.977639,0.977922,0.976508,0.978432,0.977452,0.000720,9,0.997134,0.997930,0.996921,0.997346,0.996868,0.997240,0.000384,1,0.986840,0.987680,0.987330,0.986817,0.987564,0.987246,0.000359,6,0.999280,0.999480,0.999227,0.999333,0.999213,0.999306,0.000096,1,0.994068,0.994294,0.994373,0.994002,0.994506,0.994249,0.000188,9,0.996667,0.996880,0.996794,0.996660,0.996854,0.996771,0.000092,6,0.991754,0.992280,0.992062,0.991739,0.992209,0.992009,0.000226,6,0.994681,0.995021,0.994883,0.994671,0.994979,0.994847,0.000147,6,0.995601,0.996112,0.995647,0.995674,0.995687,0.995744,0.000186,3,7.193762,0.475277,0.163516,0.013204
9,decision_tree,randomized_search,cicids2017_iot23,470980,12,5,1,10,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10}",0.988898,0.986588,0.988051,0.987067,0.989756,0.988072,0.001160,3,0.983439,0.983969,0.983173,0.984447,0.984607,0.983927,0.000555,9,0.986161,0.985277,0.985606,0.985755,0.987175,0.985995,0.000655,7,0.995865,0.995995,0.995799,0.996114,0.996157,0.995986,0.000138,9,0.997240,0.996656,0.997027,0.996775,0.997452,0.997030,0.000292,3,0.996552,0.996325,0.996413,0.996445,0.996804,0.996508,0.000165,7,0.991356,0.990801,0.991009,0.991100,0.991989,0.991251,0.000410,7,0.994480,0.994119,0.994257,0.994310,0.994883,0.994410,0.000263,7,0.990339,0.990313,0.990100,0.990611,0.991030,0.990479,0.000320,9,4.567919,0.258893,0.155679,0.009320
5,decision_tree,randomized_search,cicids2017_iot23,470980,12,5,1,6,"{""classifier__class_weight"": null, ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 6}",0.984550,0.983037,0.984486,0.983055,0.987206,0.984467,0.001520,6,0.980944,0.981315,0.980201,0.982377,0.982962,0.981560,0.000992,10,0.982743,0.982176,0.982339,0.982716,0.985079,0.983011,0.001057,8,0.995240,0.995331,0.995056,0.995595,0.995745,0.995393,0.000247,10,0.996152,0.995767,0.996138,0.995767,0.996815,0.996128,0.000383,6,0.995696,0.995549,0.995597,0.995681,0.996280,0.995760,0.000265,8,0.989220,0.988862,0.988968,0.989198,0.990680,0.989386,0.000661,8,0.993110,0.992877,0.992951,0.993089,0.994044,0.993214,0.000424,8,0.988548,0.988541,0.988170,0.989072,0.989888,0.988844,0.000596,10,3.858799,0.338273,0.167489,0.008748
2,decision_tree,randomized_search,cicids2017_iot23,470980,12,5,1,3,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 15}",0.960029,0.975596,0.978493,0.972576,0.970444,0.971428,0.006317,11,0.995700,0.995223,0.992569,0.992091,0.996868,0.994490,0.001850,4,0.977539,0.985312,0.985481,0.982237,0.983479,0.982809,0.002896,9,0.998915,0.998800,0.998135,0.998013,0.999212,0.998615,0.000463,4,0.989636,0.993776,0.994546,0.993007,0.992409,0.992675,0.001681,11,0.994254,0.996282,0.996337,0.995503,0.995799,0.995635,0.000757,9,0.985897,0.990797,0.990909,0.988870,0.989639,0.989222,0.001827,9,0.990849,0.994066,0.994150,0.992823,0.993301,0.993038,0.001200,9,0.992668,0.994499,0.993557,0.992549,0.994639,0.993583,0.000879,6,5.840440,0.653367,0.177780,0.044765
0,decision_tree,randomized_search,cicids2017_iot23,470980,12,5,1,1,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 11}",0.969336,0.977326,0.971119,0.970071,0.970318,0.971634,0.002903,10,0.990021,0.988428,0.988800,0.987579,0.990764,0.989118,0.001138,8,0.979569,0.982846,0.979880,0.978747,0.980434,0.980295,0.001387,10,0.997492,0.997099,0.997187,0.996881,0.997679,0.997267,0.000284,8,0.992171,0.994267,0.992648,0.992383,0.992423,0.992778,0.000760,10,0.994824,0.995681,0.994913,0.994627,0.995044,0.995018,0.000358,10,0.987197,0.989264,0.987396,0.986687,0.987739,0.987656,0.000873,10,0.991741,0.993099,0.991879,0.991422,0.992091,0.992046,0.000570,10,0.991096,0.991348,0.990724,0.989981,0.991593,0.990948,0.000563,8,5.140851,0.662559,0.169037,0.005583
8,decision_tree,randomized_search,cicids2017_iot23,470980,12,5,1,9,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 3}",0.905727,0.905292,0.902239,0.902348,0.903896,0.903900,0.001445,12,0.973035,0.970646,0.970964,0.973141,0.973992,0.972355,0.001312,11,0.938175,0.936831,0.935341,0.936408,0.937636,0.936878,0.000984,11,0.993131,0.992527,0.992600,0.993151,0.993369,0.992956,0.000332,11,0.974681,0.974614,0.973699,0.973672,0.974110,0.974155,0.000431,12,0.983819,0.983489,0.983059,0.983315,0.983645,0.983465,0.000263,11,0.960997,0.960160,0.959200,0.959862,0.960640,0.960172,0.000623,11,0.974351,0.973821,0.973152,0.973566,0.974086,0.973795,0.000415,11,0.973858,0.972630,0.972332,0.973406,0.974051,0.973255,0.000673,11,2.226299,0.173534,0.155509,0.013611
11,decision_tree,randomized_search,cicids2017_iot23,470980,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 9}",0.986044,0.985263,0.985835,0.986170,0.986834,0.986029,0.000508,5,0.825097,0.819789,0.823823,0.821381,0.827495,0.823517,0.002716,12,0.898419,0.894941,0.897577,0.896264,0.900167,0.897474,0.001791,12,0.957989,0.956763,0.957694,0.957136,0.958545,0.957626,0.000627,12,0.997081,0.996935,0.997041,0.997120,0.997240,0.997083,0.000100,2,0.977144,0.976436,0.976972,0.976719,0.977510,0.976956,0.000366,12,0.937782,0.935689,0.937274,0.936492,0.938838,0.937215,0.001078,12,0.962684,0.961506,0.962398,0.961973,0.963289,0.962370,0.000608,12,0.911089,0.908362,0.910432,0.909251,0.912367,0.910300,0.001398,12,1.781749,0.258072,0.137428,0.019624

modelo: decision_tree
 origem do treinamento: unsw_nb15_iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: decision_tree - unsw_nb15_iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
10,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,5,1,11,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17}",0.970840,0.969168,0.970811,0.970390,0.972344,0.970711,0.001018,3,0.991454,0.992781,0.992197,0.993312,0.990924,0.992133,0.000865,6,0.981039,0.980832,0.981388,0.981717,0.981546,0.981304,0.000325,1,0.997852,0.998184,0.998038,0.998318,0.997720,0.998023,0.000216,6,0.992555,0.992104,0.992542,0.992423,0.992953,0.992516,0.000273,3,0.995197,0.995135,0.995283,0.995362,0.995331,0.995261,0.000084,1,0.988118,0.987984,0.988335,0.988539,0.988438,0.988283,0.000205,1,0.992335,0.992240,0.992473,0.992601,0.992547,0.992439,0.000134,1,0.992005,0.992443,0.992370,0.992867,0.991939,0.992325,0.000335,6,4.606132,0.269787,0.097149,0.018931
3,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,5,1,4,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 20}",0.972106,0.971600,0.971885,0.972922,0.973505,0.972404,0.000705,2,0.987844,0.987897,0.987207,0.987951,0.986837,0.987547,0.000446,8,0.979912,0.979681,0.979487,0.980379,0.980125,0.979917,0.000315,2,0.996949,0.996962,0.996789,0.996976,0.996698,0.996875,0.000111,8,0.992914,0.992781,0.992861,0.993126,0.993285,0.992993,0.000185,2,0.994927,0.994867,0.994821,0.995047,0.994989,0.994930,0.000081,2,0.987420,0.987274,0.987154,0.987713,0.987557,0.987423,0.000198,2,0.991900,0.991804,0.991730,0.992091,0.991995,0.991904,0.000129,2,0.990379,0.990339,0.990034,0.990538,0.990061,0.990270,0.000194,8,4.763307,0.418522,0.160828,0.008309
4,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,5,1,5,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20}",0.972388,0.972193,0.972820,0.973218,0.974450,0.973014,0.000801,1,0.986995,0.987314,0.986040,0.987579,0.985881,0.986762,0.000682,9,0.979637,0.979695,0.979385,0.980346,0.980132,0.979839,0.000349,3,0.996737,0.996816,0.996498,0.996883,0.996460,0.996679,0.000170,9,0.992993,0.992940,0.993113,0.993206,0.993537,0.993158,0.000211,1,0.994861,0.994874,0.994803,0.995041,0.994996,0.994915,0.000089,3,0.987249,0.987285,0.987094,0.987693,0.987564,0.987377,0.000219,3,0.991794,0.991815,0.991698,0.992080,0.992006,0.991879,0.000142,3,0.989994,0.990127,0.989576,0.990392,0.989709,0.989960,0.000292,9,4.966869,0.309813,0.162355,0.012736
1,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,5,1,2,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 18}",0.963412,0.961956,0.963582,0.962980,0.962840,0.962954,0.000568,7,0.996550,0.997240,0.997187,0.996921,0.997081,0.996996,0.000248,3,0.979700,0.979280,0.980097,0.979657,0.979661,0.979679,0.000259,4,0.999130,0.999304,0.999290,0.999223,0.999264,0.999242,0.000062,3,0.990538,0.990140,0.990578,0.990419,0.990379,0.990411,0.000154,8,0.994816,0.994701,0.994915,0.994802,0.994801,0.994807,0.000068,5,0.987258,0.986990,0.987506,0.987229,0.987231,0.987243,0.000163,4,0.991741,0.991560,0.991900,0.991719,0.991719,0.991728,0.000108,5,0.993544,0.993690,0.993882,0.993670,0.993730,0.993703,0.000109,1,6.361533,0.924654,0.164050,0.012983
9,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,5,1,10,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10}",0.969437,0.968320,0.969198,0.968659,0.969065,0.968936,0.000398,4,0.990021,0.989702,0.990445,0.990923,0.990977,0.990414,0.000498,7,0.979621,0.978894,0.979706,0.979665,0.979898,0.979557,0.000345,5,0.997492,0.997411,0.997598,0.997718,0.997731,0.997590,0.000125,7,0.992197,0.991905,0.992131,0.991985,0.992091,0.992062,0.000104,5,0.994837,0.994651,0.994857,0.994843,0.994903,0.994818,0.000087,4,0.987229,0.986772,0.987282,0.987254,0.987401,0.987188,0.000216,5,0.991762,0.991465,0.991794,0.991772,0.991868,0.991732,0.000139,4,0.991109,0.990804,0.991288,0.991454,0.991534,0.991238,0.000261,7,4.504188,0.186322,0.158895,0.022715
6,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,5,1,7,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 19}",0.963301,0.961574,0.963425,0.963427,0.961385,0.962622,0.000936,8,0.996231,0.997558,0.996921,0.996974,0.997718,0.997081,0.000528,2,0.979490,0.979236,0.979887,0.979913,0.979214,0.979548,0.000304,6,0.999050,0.999384,0.999224,0.999237,0.999424,0.999264,0.000133,2,0.990512,0.990034,0.990538,0.990538,0.989981,0.990321,0.000256,9,0.994762,0.994687,0.994862,0.994869,0.994680,0.994772,0.000082,6,0.987126,0.986961,0.987374,0.987391,0.986947,0.987160,0.000192,6,0.991656,0.991539,0.991815,0.991826,0.991528,0.991673,0.000129,6,0.993372,0.993796,0.993730,0.993756,0.993849,0.993701,0.000169,2,5.511081,0.405241,0.161999,0.013498
7,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,5,1,8,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 15}",0.964175,0.962271,0.964209,0.964089,0.963639,0.963677,0.000732,6,0.994320,0.995063,0.995276,0.994692,0.994533,0.994777,0.000348,5,0.979016,0.978392,0.979496,0.979151,0.978842,0.978980,0.000364,7,0.998569,0.998755,0.998809,0.998662,0.998622,0.998684,0.000088,5,0.990764,0.990246,0.990764,0.990737,0.990618,0.990626,0.000197,7,0.994651,0.994483,0.994770,0.994684,0.994604,0.994638,0.000095,7,0.986833,0.986438,0.987133,0.986918,0.986723,0.986809,0.000229,7,0.991475,0.991210,0.991666,0.991528,0.991401,0.991456,0.000151,7,0.992542,0.992655,0.993020,0.992715,0.992575,0.992701,0.000170,5,5.564288,0.523005,0.187008,0.026396
2,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,5,1,3,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 15}",0.961503,0.957277,0.962068,0.961975,0.960497,0.960664,0.001783,9,0.996974,0.997877,0.997611,0.997771,0.997611,0.997569,0.000314,1,0.978917,0.977155,0.979517,0.979546,0.978702,0.978768,0.000871,8,0.999237,0.999464,0.999397,0.999437,0.999397,0.999386,0.000079,1,0.990021,0.988866,0.990167,0.990140,0.989742,0.989787,0.000484,10,0.994607,0.994137,0.994761,0.994767,0.994546,0.994564,0.000230,8,0.986762,0.985646,0.987139,0.987157,0.986624,0.986666,0.000551,8,0.991412,0.990668,0.991656,0.991666,0.991316,0.991344,0.000364,8,0.993498,0.993372,0.993889,0.993955,0.993677,0.993678,0.000223,3,5.561831,0.907491,0.174159,0.035456
0,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,5,1,1,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 11}",0.958321,0.952214,0.959363,0.955255,0.957501,0.956531,0.002547,10,0.995913,0.996390,0.997505,0.997240,0.997346,0.996879,0.000619,4,0.976755,0.973802,0.978062,0.975796,0.977017,0.976286,0.001437,9,0.998968,0.999087,0.999370,0.999302,0.999330,0.999211,0.000156,4,0.989172,0.987500,0.989437,0.988322,0.988933,0.988673,0.000693,11,0.994046,0.993259,0.994379,0.993782,0.994104,0.993914,0.000378,9,0.985400,0.983531,0.986220,0.984789,0.985561,0.985100,0.000908,9,0.990520,0.989278,0.991051,0.990106,0.990615,0.990314,0.000599,9,0.992542,0.991945,0.993471,0.992781,0.993139,0.992776,0.000522,4,5.016925,0.793261,0.160425,0.020091
5,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,5,1,6,"{""classifier__class_weight"": null, ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 6}",0.967386,0.965110,0.965678,0.963561,0.967767,0.965900,0.001539,5,0.980891,0.980838,0.979723,0.981156,0.980096,0.980541,0.000540,10,0.974091,0.972910,0.972650,0.972279,0.973892,0.973165,0.000707,10,0.995206,0.995190,0.994912,0.995267,0.995008,0.995117,0.000134,10,0.991733,0.991136,0.991295,0.990724,0.991839,0.991345,0.000406,6,0.993466,0.993159,0.993100,0.992991,0.993421,0.993227,0.000185,10,0.983779,0.983034,0.982875,0.982635,0.983657,0.983196,0.000446,10,0.989564,0.989076,0.988980,0.988811,0.989490,0.989184,0.000294,10,0.986312,0.985987,0.985509,0.985940,0.985967,0.985943,0.000256,10,3.693027,0.306104,0.163057,0.008037
8,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,5,1,9,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 3}",0.695198,0.696552,0.695484,0.696440,0.695719,0.695879,0.000532,12,0.910558,0.911407,0.909125,0.907638,0.908386,0.909423,0.001384,11,0.788436,0.789625,0.788082,0.788136,0.787956,0.788447,0.000610,11,0.975763,0.976001,0.975392,0.975016,0.975200,0.975474,0.000361,11,0.900195,0.900739,0.900487,0.901097,0.900671,0.900638,0.000297,12,0.936457,0.936861,0.936444,0.936600,0.936455,0.936564,0.000160,12,0.862446,0.863243,0.862263,0.862368,0.862205,0.862505,0.000378,12,0.902268,0.902873,0.902215,0.902406,0.902215,0.902395,0.000249,12,0.905376,0.906073,0.904806,0.904368,0.904529,0.905030,0.000624,11,2.137374,0.170130,0.159338,0.020900
11,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 9}",0.956625,0.955974,0.957239,0.954514,0.952250,0.955320,0.001783,11,0.660279,0.652370,0.655927,0.653856,0.661571,0.656801,0.003575,12,0.781295,0.775517,0.778443,0.776084,0.780732,0.778414,0.002345,12,0.921175,0.919486,0.920258,0.919782,0.921388,0.920418,0.000750,12,0.992516,0.992489,0.992675,0.992210,0.991706,0.992319,0.000341,4,0.955516,0.954594,0.955096,0.954624,0.955255,0.955017,0.000359,11,0.868405,0.865055,0.866769,0.865354,0.867993,0.866715,0.001349,11,0.926069,0.924466,0.925326,0.924540,0.925676,0.925216,0.000628,11,0.826397,0.822430,0.824301,0.823033,0.826639,0.824560,0.001711,12,1.665302,0.257472,0.138527,0.040314

modelo: random_forest
 origem do treinamento: cicids2017
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: random_forest - cicids2017

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
1,random_forest,randomized_search,cicids2017,235490,12,5,1,2,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 229}",0.981963,0.980318,0.984534,0.982019,0.979705,0.981708,0.001679,1,0.994161,0.994161,0.993418,0.991401,0.994161,0.993460,0.001069,7,0.988024,0.987191,0.988956,0.986688,0.986880,0.987548,0.000839,1,0.998536,0.998535,0.998351,0.997845,0.998535,0.998360,0.000267,7,0.995435,0.995010,0.996099,0.995462,0.994851,0.995371,0.000434,1,0.996983,0.996770,0.997223,0.996652,0.996690,0.996864,0.000213,1,0.992504,0.991980,0.993090,0.991670,0.991785,0.992206,0.000526,1,0.995180,0.994841,0.995562,0.994649,0.994713,0.994989,0.000340,1,0.994798,0.994586,0.994758,0.993431,0.994506,0.994416,0.000504,3,113.226569,4.152870,0.716015,0.048810
0,random_forest,randomized_search,cicids2017,235490,12,5,1,1,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 237}",0.977933,0.975830,0.979990,0.978728,0.975402,0.977576,0.001735,11,0.997452,0.998726,0.998195,0.996391,0.997665,0.997686,0.000784,1,0.987596,0.987145,0.989009,0.987480,0.986408,0.987528,0.000849,2,0.999360,0.999680,0.999547,0.999094,0.999413,0.999418,0.000197,1,0.994374,0.993816,0.994904,0.994586,0.993710,0.994278,0.000454,11,0.996860,0.996739,0.997220,0.996835,0.996553,0.996841,0.000218,2,0.992228,0.991942,0.993114,0.992157,0.991480,0.992185,0.000533,2,0.994989,0.994798,0.995562,0.994947,0.994501,0.994959,0.000347,2,0.995913,0.996271,0.996550,0.995488,0.995687,0.995982,0.000385,1,114.626433,1.600613,0.692521,0.044629
3,random_forest,randomized_search,cicids2017,235490,12,5,1,4,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 246}",0.980312,0.979291,0.982083,0.980682,0.978668,0.980207,0.001180,3,0.993842,0.994055,0.995011,0.991614,0.993524,0.993609,0.001114,6,0.987031,0.986617,0.988505,0.986118,0.986040,0.986862,0.000896,3,0.998455,0.998508,0.998748,0.997897,0.998375,0.998397,0.000279,5,0.995010,0.994745,0.995462,0.995117,0.994586,0.994984,0.000304,4,0.996730,0.996623,0.997102,0.996505,0.996477,0.996687,0.000226,3,0.991880,0.991620,0.992803,0.991311,0.991258,0.991775,0.000561,3,0.994777,0.994607,0.995371,0.994416,0.994373,0.994709,0.000361,3,0.994426,0.994400,0.995236,0.993365,0.994055,0.994296,0.000606,4,129.556764,3.385246,0.682924,0.006623
4,random_forest,randomized_search,cicids2017,235490,12,5,1,5,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 168}",0.980812,0.979487,0.982884,0.981303,0.978561,0.980609,0.001493,2,0.993099,0.993630,0.993631,0.991720,0.993312,0.993078,0.000709,9,0.986917,0.986508,0.988228,0.986484,0.985881,0.986804,0.000785,4,0.998269,0.998402,0.998403,0.997924,0.998322,0.998264,0.000177,9,0.995143,0.994798,0.995674,0.995276,0.994559,0.995090,0.000386,2,0.996704,0.996597,0.997037,0.996598,0.996437,0.996674,0.000200,4,0.991810,0.991552,0.992632,0.991541,0.991159,0.991739,0.000493,4,0.994734,0.994565,0.995265,0.994565,0.994310,0.994688,0.000319,4,0.994121,0.994214,0.994652,0.993498,0.993936,0.994084,0.000376,9,92.461566,3.079067,0.522687,0.041598
2,random_forest,randomized_search,cicids2017,235490,12,5,1,3,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 125}",0.980205,0.978979,0.982699,0.980682,0.978452,0.980204,0.001485,4,0.993630,0.993842,0.994904,0.991614,0.992994,0.993397,0.001083,8,0.986872,0.986355,0.988764,0.986118,0.985669,0.986756,0.001077,5,0.998402,0.998455,0.998722,0.997897,0.998242,0.998344,0.000271,8,0.994984,0.994665,0.995621,0.995117,0.994533,0.994984,0.000382,3,0.996690,0.996557,0.997169,0.996505,0.996384,0.996661,0.000272,5,0.991781,0.991456,0.992967,0.991311,0.991026,0.991708,0.000675,5,0.994713,0.994501,0.995478,0.994416,0.994225,0.994666,0.000435,5,0.994307,0.994254,0.995263,0.993365,0.993763,0.994190,0.000637,5,67.365551,3.008238,0.396977,0.011920
10,random_forest,randomized_search,cicids2017,235490,12,5,1,11,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 249}",0.980404,0.979171,0.982478,0.980370,0.978245,0.980134,0.001423,5,0.993311,0.993205,0.994055,0.991401,0.992887,0.992972,0.000874,10,0.986816,0.986138,0.988233,0.985855,0.985512,0.986511,0.000962,6,0.998322,0.998295,0.998509,0.997844,0.998215,0.998237,0.000219,10,0.995037,0.994719,0.995568,0.995037,0.994480,0.994968,0.000366,7,0.996677,0.996504,0.997036,0.996439,0.996344,0.996600,0.000244,6,0.991746,0.991321,0.992635,0.991147,0.990928,0.991555,0.000603,6,0.994692,0.994416,0.995265,0.994310,0.994161,0.994569,0.000389,6,0.994174,0.993962,0.994811,0.993219,0.993684,0.993970,0.000528,10,131.173609,3.598416,0.639664,0.057475
9,random_forest,randomized_search,cicids2017,235490,12,5,1,10,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 300}",0.974678,0.972397,0.978861,0.978093,0.974782,0.975762,0.002387,12,0.997133,0.998620,0.997877,0.995329,0.997134,0.997219,0.001094,2,0.985778,0.985334,0.988277,0.986636,0.985831,0.986371,0.001041,7,0.999279,0.999653,0.999467,0.998827,0.999279,0.999301,0.000274,2,0.993524,0.992914,0.994612,0.994426,0.993551,0.993805,0.000629,12,0.996393,0.996272,0.997034,0.996622,0.996407,0.996545,0.000269,7,0.991086,0.990803,0.992655,0.991629,0.991119,0.991458,0.000655,7,0.994246,0.994055,0.995265,0.994607,0.994267,0.994488,0.000427,7,0.995329,0.995767,0.996245,0.994878,0.995342,0.995512,0.000462,2,151.418260,2.278613,0.838133,0.077946
5,random_forest,randomized_search,cicids2017,235490,12,5,1,6,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 196}",0.979191,0.977251,0.981351,0.979669,0.976312,0.978755,0.001789,8,0.994161,0.994267,0.994374,0.992357,0.993206,0.993673,0.000779,3,0.986619,0.985686,0.987820,0.985972,0.984687,0.986157,0.001039,8,0.998535,0.998561,0.998589,0.998083,0.998294,0.998412,0.000195,3,0.994719,0.994214,0.995276,0.994851,0.993975,0.994607,0.000463,8,0.996623,0.996383,0.996929,0.996464,0.996130,0.996506,0.000265,8,0.991621,0.991034,0.992375,0.991218,0.990408,0.991331,0.000652,8,0.994607,0.994225,0.995095,0.994352,0.993821,0.994420,0.000422,8,0.994440,0.994241,0.994825,0.993604,0.993591,0.994140,0.000481,6,93.056564,3.033766,0.506829,0.008750
7,random_forest,randomized_search,cicids2017,235490,12,5,1,8,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 228}",0.979191,0.977247,0.981351,0.979669,0.976312,0.978754,0.001789,9,0.994161,0.994055,0.994374,0.992357,0.993206,0.993630,0.000750,4,0.986619,0.985579,0.987820,0.985972,0.984687,0.986135,0.001049,9,0.998535,0.998507,0.998589,0.998083,0.998294,0.998402,0.000188,4,0.994719,0.994214,0.995276,0.994851,0.993975,0.994607,0.000463,8,0.996623,0.996356,0.996929,0.996464,0.996130,0.996501,0.000268,9,0.991621,0.990968,0.992375,0.991218,0.990408,0.991318,0.000659,9,0.994607,0.994182,0.995095,0.994352,0.993821,0.994412,0.000427,9,0.994440,0.994134,0.994825,0.993604,0.993591,0.994119,0.000479,7,110.977711,3.685657,0.587389,0.005094
11,random_forest,randomized_search,cicids2017,235490,12,5,1,12,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 296}",0.979088,0.977145,0.981247,0.979669,0.976109,0.978651,0.001827,10,0.994161,0.994055,0.994268,0.992357,0.993206,0.993609,0.000730,5,0.986567,0.985527,0.987714,0.985972,0.984583,0.986073,0.001046,10,0.998535,0.998507,0.998562,0.998083,0.998294,0.998396,0.000183,6,0.994692,0.994188,0.995249,0.994851,0.993922,0.994580,0.000473,10,0.996610,0.996343,0.996903,0.996464,0.996103,0.996485,0.000267,10,0.991588,0.990935,0.992309,0.991218,0.990343,0.991279,0.000656,10,0.994586,0.994161,0.995053,0.994352,0.993779,0.994386,0.000425,10,0.994426,0.994121,0.994758,0.993604,0.993564,0.994095,0.000463,8,107.078183,20.792477,0.535638,0.030120
8,random_forest,randomized_search,cicids2017,235490,12,5,1,9,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 241}",0.980846,0.978983,0.982312,0.979975,0.978357,0.980094,0.001397,6,0.989489,0.989065,0.990446,0.987049,0.988535,0.988917,0.001125,11,0.985149,0.983998,0.986362,0.983499,0.983420,0.984485,0.001123,11,0.997367,0.997259,0.997606,0.996756,0.997126,0.997223,0.000282,11,0.995170,0.994692,0.995541,0.994957,0.994533,0.994979,0.000356,5,0.996267,0.995974,0.996573,0.995856,0.995828,0.996099,0.000283,11,0.990708,0.989986,0.991467,0.989677,0.989624,0.990292,0.000703,11,0.994034,0.993567,0.994522,0.993376,0.993333,0.993766,0.000452,11,0.992330,0.991878,0.992994,0.991003,0.991534,0.991948,0.000679,11,123.009324,3.844052,0.658386,0.054175
6,random_forest,randomized_search,cicids2017,235490,12,5,1,7,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 107}",0.980844,0.978972,0.982312,0.980076,0.978247,0.980090,0.001425,7,0.989383,0.988534,0.990446,0.986943,0.988217,0.988704,0.001172,12,0.985095,0.983730,0.986362,0.983497,0.983207,0.984378,0.001185,12,0.997340,0.997127,0.997606,0.996730,0.997046,0.997170,0.000293,12,0.995170,0.994692,0.995541,0.994984,0.994506,0.994979,0.000363,5,0.996254,0.995908,0.996573,0.995856,0.995775,0.996073,0.000299,12,0.990674,0.989819,0.991467,0.989677,0.989491,0.990226,0.000742,12,0.994012,0.993460,0.994522,0.993376,0.993248,0.993724,0.000477,12,0.992276,0.991613,0.992994,0.990963,0.991361,0.991841,0.000717,12,53.900240,2.250691,0.347764,0.035923

modelo: random_forest
 origem do treinamento: unsw_nb15
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: random_forest - unsw_nb15

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
4,random_forest,randomized_search,unsw_nb15,235490,12,5,1,5,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 168}",0.945777,0.946339,0.942630,0.942151,0.942551,0.943890,0.001787,2,0.996284,0.996072,0.995966,0.995860,0.997983,0.996433,0.000788,11,0.970374,0.970568,0.968564,0.968261,0.969475,0.969449,0.000928,1,0.999059,0.999005,0.998977,0.998950,0.999488,0.999096,0.000200,11,0.985721,0.985881,0.984845,0.984713,0.984792,0.985190,0.000503,2,0.992345,0.992399,0.991861,0.991780,0.992086,0.992094,0.000249,1,0.981360,0.981484,0.980213,0.980021,0.980780,0.980771,0.000588,1,0.987834,0.987919,0.987070,0.986942,0.987430,0.987439,0.000392,1,0.991003,0.990976,0.990406,0.990286,0.991388,0.990812,0.000409,11,88.742907,3.914830,0.577904,0.038905
2,random_forest,randomized_search,unsw_nb15,235490,12,5,1,3,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 125}",0.944316,0.945255,0.942352,0.941843,0.942167,0.943187,0.001349,4,0.997452,0.997240,0.996072,0.997134,0.997877,0.997155,0.000598,9,0.970157,0.970552,0.968468,0.968700,0.969222,0.969420,0.000811,2,0.999354,0.999300,0.999004,0.999273,0.999461,0.999278,0.000152,9,0.985297,0.985562,0.984766,0.984606,0.984686,0.984983,0.000377,4,0.992276,0.992384,0.991834,0.991885,0.992019,0.992079,0.000216,2,0.981216,0.981468,0.980151,0.980293,0.980620,0.980750,0.000513,2,0.987728,0.987898,0.987027,0.987112,0.987324,0.987418,0.000341,2,0.991374,0.991401,0.990419,0.990870,0.991281,0.991069,0.000377,9,64.568381,2.225869,0.452045,0.032901
10,random_forest,randomized_search,unsw_nb15,235490,12,5,1,11,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 249}",0.944333,0.944707,0.941802,0.941188,0.941919,0.942790,0.001439,5,0.997770,0.997664,0.996391,0.997240,0.998514,0.997516,0.000696,8,0.970316,0.970464,0.968328,0.968404,0.969391,0.969380,0.000907,3,0.999435,0.999408,0.999084,0.999300,0.999623,0.999370,0.000177,8,0.985297,0.985403,0.984606,0.984421,0.984606,0.984867,0.000402,5,0.992315,0.992356,0.991793,0.991804,0.992058,0.992065,0.000241,3,0.981316,0.981410,0.980060,0.980104,0.980724,0.980723,0.000574,3,0.987791,0.987855,0.986963,0.986985,0.987388,0.987396,0.000380,3,0.991534,0.991534,0.990499,0.990830,0.991560,0.991191,0.000443,8,122.607619,3.221684,0.691616,0.064230
3,random_forest,randomized_search,unsw_nb15,235490,12,5,1,4,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 246}",0.944875,0.945687,0.942086,0.942092,0.941843,0.943316,0.001627,3,0.997240,0.996390,0.996391,0.996497,0.997134,0.996730,0.000376,10,0.970351,0.970377,0.968478,0.968531,0.968700,0.969287,0.000882,4,0.999300,0.999085,0.999084,0.999111,0.999273,0.999171,0.000095,10,0.985456,0.985695,0.984686,0.984686,0.984606,0.985026,0.000456,3,0.992330,0.992345,0.991833,0.991846,0.991885,0.992048,0.000237,4,0.981341,0.981361,0.980155,0.980188,0.980293,0.980668,0.000560,4,0.987813,0.987834,0.987027,0.987048,0.987112,0.987367,0.000374,4,0.991348,0.991043,0.990538,0.990591,0.990870,0.990878,0.000298,10,127.221040,3.117183,0.830118,0.056311
5,random_forest,randomized_search,unsw_nb15,235490,12,5,1,6,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 196}",0.942414,0.942797,0.939040,0.939309,0.939621,0.940636,0.001623,8,0.999044,0.999151,0.999151,0.998938,0.999469,0.999151,0.000178,1,0.969903,0.970156,0.968163,0.968207,0.968621,0.969010,0.000851,5,0.999757,0.999784,0.999784,0.999730,0.999865,0.999784,0.000045,1,0.984740,0.984846,0.983784,0.983863,0.983943,0.984235,0.000459,9,0.992192,0.992259,0.991719,0.991733,0.991840,0.991949,0.000231,6,0.981047,0.981208,0.979941,0.979970,0.980231,0.980479,0.000541,5,0.987600,0.987706,0.986857,0.986878,0.987048,0.987218,0.000363,6,0.991892,0.991998,0.991467,0.991401,0.991706,0.991693,0.000232,2,88.799548,1.452902,0.574006,0.044867
7,random_forest,randomized_search,unsw_nb15,235490,12,5,1,8,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 228}",0.942319,0.942797,0.939040,0.939309,0.939715,0.940636,0.001591,9,0.999044,0.999151,0.999151,0.998938,0.999469,0.999151,0.000178,1,0.969853,0.970156,0.968163,0.968207,0.968671,0.969010,0.000837,6,0.999757,0.999784,0.999784,0.999730,0.999865,0.999784,0.000045,2,0.984713,0.984846,0.983784,0.983863,0.983969,0.984235,0.000450,8,0.992178,0.992259,0.991719,0.991733,0.991854,0.991949,0.000227,5,0.981016,0.981208,0.979941,0.979970,0.980262,0.980479,0.000532,6,0.987579,0.987706,0.986857,0.986878,0.987070,0.987218,0.000357,5,0.991879,0.991998,0.991467,0.991401,0.991719,0.991693,0.000230,1,104.818434,1.378455,0.625959,0.047937
8,random_forest,randomized_search,unsw_nb15,235490,12,5,1,9,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 241}",0.942579,0.943224,0.939367,0.939842,0.940354,0.941073,0.001539,6,0.998620,0.998301,0.998301,0.998408,0.999151,0.998556,0.000319,6,0.969791,0.969981,0.967938,0.968240,0.968861,0.968962,0.000813,7,0.999650,0.999569,0.999569,0.999596,0.999784,0.999633,0.000081,6,0.984793,0.984978,0.983890,0.984023,0.984155,0.984368,0.000435,6,0.992166,0.992220,0.991667,0.991748,0.991908,0.991942,0.000220,7,0.980978,0.981101,0.979803,0.979994,0.980385,0.980452,0.000516,7,0.987558,0.987643,0.986772,0.986900,0.987154,0.987205,0.000346,7,0.991706,0.991640,0.991096,0.991215,0.991653,0.991462,0.000254,6,116.879467,2.927487,0.697191,0.077208
6,random_forest,randomized_search,unsw_nb15,235490,12,5,1,7,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 107}",0.942579,0.943313,0.939361,0.939830,0.939790,0.940975,0.001635,7,0.998620,0.998195,0.998195,0.998195,0.999151,0.998471,0.000377,7,0.969791,0.969978,0.967885,0.968134,0.968562,0.968870,0.000858,8,0.999650,0.999542,0.999542,0.999542,0.999784,0.999612,0.000096,7,0.984793,0.985005,0.983890,0.984023,0.983996,0.984341,0.000462,7,0.992166,0.992220,0.991654,0.991721,0.991827,0.991918,0.000232,8,0.980978,0.981099,0.979769,0.979928,0.980195,0.980394,0.000545,8,0.987558,0.987643,0.986751,0.986857,0.987027,0.987167,0.000365,8,0.991706,0.991600,0.991043,0.991109,0.991573,0.991406,0.000274,7,53.150708,3.122852,0.355286,0.032125
11,random_forest,randomized_search,unsw_nb15,235490,12,5,1,12,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 296}",0.942042,0.942508,0.938385,0.938928,0.938684,0.940109,0.001783,10,0.999151,0.999044,0.999151,0.998832,0.999469,0.999129,0.000206,3,0.969756,0.969953,0.967815,0.967954,0.968123,0.968720,0.000933,9,0.999784,0.999758,0.999784,0.999703,0.999865,0.999779,0.000052,3,0.984633,0.984766,0.983598,0.983757,0.983677,0.984086,0.000505,10,0.992151,0.992205,0.991625,0.991666,0.991705,0.991871,0.000253,9,0.980954,0.981079,0.979720,0.979810,0.979914,0.980295,0.000593,9,0.987537,0.987622,0.986709,0.986772,0.986836,0.987095,0.000398,9,0.991892,0.991905,0.991374,0.991295,0.991573,0.991608,0.000254,3,101.306579,19.729408,0.541795,0.030988
0,random_forest,randomized_search,unsw_nb15,235490,12,5,1,1,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 237}",0.942225,0.942419,0.936990,0.939022,0.938110,0.939753,0.002195,11,0.999044,0.999151,0.999257,0.998832,0.999257,0.999108,0.000159,4,0.969803,0.969956,0.967122,0.968004,0.967719,0.968521,0.001146,10,0.999757,0.999784,0.999811,0.999703,0.999811,0.999773,0.000040,4,0.984686,0.984740,0.983200,0.983784,0.983518,0.983986,0.000622,11,0.992165,0.992205,0.991436,0.991680,0.991598,0.991817,0.000311,10,0.980984,0.981081,0.979279,0.979842,0.979658,0.980169,0.000729,10,0.987558,0.987622,0.986411,0.986793,0.986666,0.987010,0.000489,10,0.991865,0.991945,0.991228,0.991308,0.991388,0.991547,0.000298,4,113.108809,3.395715,0.731181,0.082994
9,random_forest,randomized_search,unsw_nb15,235490,12,5,1,10,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 300}",0.941753,0.942231,0.936791,0.938928,0.937830,0.939507,0.002144,12,0.999044,0.999151,0.999045,0.998832,0.999257,0.999066,0.000141,5,0.969553,0.969856,0.966917,0.967954,0.967570,0.968370,0.001143,11,0.999757,0.999784,0.999757,0.999703,0.999811,0.999763,0.000036,5,0.984554,0.984686,0.983147,0.983757,0.983439,0.983917,0.000608,12,0.992097,0.992178,0.991382,0.991666,0.991557,0.991776,0.000310,11,0.980825,0.981017,0.979149,0.979810,0.979563,0.980073,0.000726,11,0.987452,0.987579,0.986326,0.986772,0.986602,0.986946,0.000488,11,0.991799,0.991919,0.991096,0.991295,0.991348,0.991491,0.000314,5,145.114571,5.157709,0.838594,0.070746
1,random_forest,randomized_search,unsw_nb15,235490,12,5,1,2,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 229}",0.947776,0.948336,0.946160,0.945349,0.945100,0.946544,0.001295,1,0.988428,0.986092,0.988747,0.986093,0.986837,0.987239,0.001138,12,0.967675,0.966845,0.966985,0.965291,0.965517,0.966463,0.000912,12,0.997076,0.996488,0.997155,0.996485,0.996672,0.996775,0.000287,12,0.986385,0.986571,0.985933,0.985748,0.985668,0.986061,0.000356,1,0.991702,0.991505,0.991512,0.991087,0.991140,0.991389,0.000236,12,0.979688,0.979175,0.979249,0.978189,0.978328,0.978926,0.000574,12,0.986793,0.986475,0.986496,0.985817,0.985902,0.986297,0.000375,12,0.987406,0.986331,0.987340,0.985921,0.986252,0.986650,0.000607,12,114.892727,5.206749,0.847037,0.046255

modelo: random_forest
 origem do treinamento: iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: random_forest - iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
4,random_forest,randomized_search,iot23,235490,12,5,1,5,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 168}",0.999573,0.999893,0.999679,1.000000,0.999893,0.999808,0.000157,5,0.993948,0.992037,0.992357,0.994374,0.993737,0.993291,0.000922,7,0.996753,0.995950,0.996004,0.997179,0.996805,0.996538,0.000481,1,0.998489,0.998013,0.998093,0.998595,0.998437,0.998325,0.000230,7,0.999894,0.999973,0.999920,1.000000,0.999973,0.999952,0.000039,5,0.999191,0.998992,0.999006,0.999297,0.999204,0.999138,0.000119,1,0.997972,0.997471,0.997505,0.998238,0.998005,0.997838,0.000300,1,0.998705,0.998386,0.998408,0.998875,0.998726,0.998620,0.000191,1,0.996921,0.996005,0.996139,0.997187,0.996855,0.996621,0.000464,7,61.178708,2.827307,0.503565,0.033010
3,random_forest,randomized_search,iot23,235490,12,5,1,4,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 246}",0.999680,0.999893,0.999786,1.000000,0.999893,0.999850,0.000109,2,0.993736,0.992037,0.992144,0.994161,0.993524,0.993121,0.000866,8,0.996699,0.995950,0.995951,0.997072,0.996699,0.996474,0.000449,2,0.998436,0.998013,0.998040,0.998542,0.998384,0.998283,0.000216,8,0.999920,0.999973,0.999947,1.000000,0.999973,0.999963,0.000027,2,0.999178,0.998992,0.998992,0.999271,0.999178,0.999122,0.000111,2,0.997938,0.997471,0.997471,0.998171,0.997938,0.997798,0.000280,2,0.998684,0.998386,0.998386,0.998832,0.998684,0.998594,0.000178,2,0.996828,0.996005,0.996046,0.997081,0.996749,0.996542,0.000436,8,87.158641,2.150236,0.713084,0.081309
2,random_forest,randomized_search,iot23,235490,12,5,1,3,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 125}",0.999573,0.999893,0.999786,0.999893,0.999893,0.999808,0.000125,6,0.993524,0.991825,0.992144,0.994161,0.993524,0.993036,0.000895,9,0.996539,0.995843,0.995951,0.997019,0.996699,0.996410,0.000448,3,0.998384,0.997961,0.998040,0.998542,0.998384,0.998262,0.000223,9,0.999894,0.999973,0.999947,0.999973,0.999973,0.999952,0.000031,5,0.999138,0.998966,0.998992,0.999257,0.999178,0.999106,0.000111,4,0.997839,0.997404,0.997471,0.998138,0.997938,0.997758,0.000280,3,0.998620,0.998344,0.998386,0.998811,0.998684,0.998569,0.000178,3,0.996709,0.995899,0.996046,0.997067,0.996749,0.996494,0.000446,9,44.514038,1.898508,0.379452,0.023701
10,random_forest,randomized_search,iot23,235490,12,5,1,11,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 249}",0.999680,0.999893,0.999786,1.000000,0.999893,0.999850,0.000109,3,0.993524,0.991825,0.991932,0.994161,0.993524,0.992993,0.000940,10,0.996592,0.995843,0.995844,0.997072,0.996699,0.996410,0.000489,4,0.998384,0.997961,0.997987,0.998542,0.998384,0.998251,0.000234,10,0.999920,0.999973,0.999947,1.000000,0.999973,0.999963,0.000027,2,0.999151,0.998966,0.998966,0.999271,0.999178,0.999106,0.000121,3,0.997872,0.997404,0.997405,0.998171,0.997938,0.997758,0.000305,4,0.998641,0.998344,0.998344,0.998832,0.998684,0.998569,0.000194,3,0.996722,0.995899,0.995939,0.997081,0.996749,0.996478,0.000474,10,86.238157,2.958679,0.585340,0.037572
6,random_forest,randomized_search,iot23,235490,12,5,1,7,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 107}",0.999786,0.999893,0.999786,1.000000,0.999893,0.999872,0.000080,1,0.993418,0.991613,0.991932,0.994055,0.993524,0.992908,0.000958,12,0.996592,0.995736,0.995844,0.997019,0.996699,0.996378,0.000501,5,0.998357,0.997908,0.997987,0.998516,0.998384,0.998230,0.000239,11,0.999947,0.999973,0.999947,1.000000,0.999973,0.999968,0.000020,1,0.999151,0.998939,0.998966,0.999257,0.999178,0.999098,0.000124,5,0.997872,0.997338,0.997405,0.998138,0.997938,0.997738,0.000313,5,0.998641,0.998301,0.998344,0.998811,0.998684,0.998556,0.000199,5,0.996682,0.995793,0.995939,0.997028,0.996749,0.996438,0.000483,11,36.019522,2.005917,0.329451,0.012735
8,random_forest,randomized_search,iot23,235490,12,5,1,9,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 241}",0.999786,0.999893,0.999786,1.000000,0.999786,0.999850,0.000085,4,0.993524,0.991613,0.991932,0.993949,0.993524,0.992908,0.000946,11,0.996645,0.995736,0.995844,0.996965,0.996646,0.996367,0.000487,6,0.998384,0.997908,0.997987,0.998489,0.998384,0.998230,0.000236,12,0.999947,0.999973,0.999947,1.000000,0.999947,0.999963,0.000021,4,0.999165,0.998939,0.998966,0.999244,0.999165,0.999096,0.000121,6,0.997905,0.997338,0.997405,0.998105,0.997905,0.997731,0.000304,6,0.998662,0.998301,0.998344,0.998790,0.998662,0.998552,0.000193,6,0.996735,0.995793,0.995939,0.996975,0.996736,0.996436,0.000475,12,79.247451,3.038643,0.600908,0.028734
1,random_forest,randomized_search,iot23,235490,12,5,1,2,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 229}",0.988647,0.987290,0.989670,0.988748,0.986990,0.988269,0.000993,7,0.998514,0.997877,0.996709,0.998089,0.998620,0.997962,0.000683,6,0.993556,0.992555,0.993177,0.993396,0.992771,0.993091,0.000376,7,0.999628,0.999468,0.999176,0.999521,0.999654,0.999489,0.000171,6,0.997134,0.996789,0.997399,0.997160,0.996709,0.997038,0.000255,7,0.998379,0.998126,0.998287,0.998339,0.998179,0.998262,0.000095,7,0.995967,0.995341,0.995732,0.995868,0.995475,0.995677,0.000236,7,0.997410,0.997006,0.997261,0.997346,0.997091,0.997223,0.000152,7,0.997824,0.997333,0.997054,0.997625,0.997664,0.997500,0.000274,3,82.590463,3.555533,0.649135,0.072423
5,random_forest,randomized_search,iot23,235490,12,5,1,6,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 196}",0.988335,0.987495,0.989671,0.988542,0.986576,0.988124,0.001040,8,0.998514,0.997664,0.996815,0.998301,0.998620,0.997983,0.000671,4,0.993398,0.992553,0.993230,0.993398,0.992561,0.993028,0.000389,8,0.999627,0.999415,0.999202,0.999574,0.999654,0.999495,0.000168,4,0.997054,0.996842,0.997399,0.997107,0.996603,0.997001,0.000267,8,0.998339,0.998127,0.998300,0.998339,0.998126,0.998246,0.000099,8,0.995869,0.995340,0.995765,0.995868,0.995344,0.995637,0.000244,8,0.997346,0.997006,0.997282,0.997346,0.997006,0.997197,0.000158,8,0.997784,0.997253,0.997107,0.997704,0.997611,0.997492,0.000264,4,66.593781,2.983990,0.526057,0.043196
7,random_forest,randomized_search,iot23,235490,12,5,1,8,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 228}",0.988335,0.987495,0.989567,0.988542,0.986576,0.988103,0.001009,9,0.998514,0.997664,0.996815,0.998301,0.998620,0.997983,0.000671,4,0.993398,0.992553,0.993178,0.993398,0.992561,0.993018,0.000384,9,0.999627,0.999415,0.999202,0.999574,0.999654,0.999495,0.000168,5,0.997054,0.996842,0.997372,0.997107,0.996603,0.996996,0.000259,9,0.998339,0.998127,0.998287,0.998339,0.998126,0.998243,0.000098,9,0.995869,0.995340,0.995732,0.995868,0.995344,0.995631,0.000241,9,0.997346,0.997006,0.997261,0.997346,0.997006,0.997193,0.000156,9,0.997784,0.997253,0.997094,0.997704,0.997611,0.997489,0.000268,5,74.808635,1.549751,0.581065,0.039974
11,random_forest,randomized_search,iot23,235490,12,5,1,12,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 296}",0.988234,0.987495,0.989672,0.988335,0.985852,0.987918,0.001249,10,0.998726,0.997664,0.996921,0.998408,0.998620,0.998068,0.000683,3,0.993452,0.992553,0.993284,0.993346,0.992195,0.992966,0.000499,10,0.999681,0.999415,0.999229,0.999601,0.999654,0.999516,0.000171,3,0.997028,0.996842,0.997399,0.997054,0.996417,0.996948,0.000321,10,0.998352,0.998127,0.998313,0.998326,0.998033,0.998230,0.000127,10,0.995902,0.995340,0.995798,0.995836,0.995114,0.995598,0.000313,10,0.997367,0.997006,0.997303,0.997325,0.996858,0.997172,0.000202,10,0.997877,0.997253,0.997160,0.997731,0.997518,0.997508,0.000273,2,65.300298,16.303528,0.498193,0.031703
0,random_forest,randomized_search,iot23,235490,12,5,1,1,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 237}",0.987509,0.987087,0.988946,0.987816,0.985437,0.987359,0.001142,11,0.998832,0.998195,0.997240,0.998408,0.998514,0.998238,0.000540,1,0.993138,0.992610,0.993076,0.993084,0.991933,0.992768,0.000459,11,0.999707,0.999548,0.999308,0.999601,0.999627,0.999558,0.000135,1,0.996842,0.996736,0.997213,0.996921,0.996311,0.996805,0.000293,11,0.998272,0.998140,0.998260,0.998259,0.997966,0.998179,0.000117,11,0.995705,0.995375,0.995668,0.995672,0.994949,0.995474,0.000288,11,0.997240,0.997027,0.997219,0.997219,0.996751,0.997091,0.000187,11,0.997837,0.997465,0.997227,0.997664,0.997412,0.997521,0.000211,1,81.241999,1.981355,0.639834,0.035656
9,random_forest,randomized_search,iot23,235490,12,5,1,10,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 300}",0.987302,0.986982,0.989152,0.987713,0.985436,0.987317,0.001198,12,0.998832,0.998089,0.997028,0.998408,0.998408,0.998153,0.000610,2,0.993034,0.992504,0.993074,0.993031,0.991879,0.992705,0.000463,12,0.999707,0.999521,0.999255,0.999601,0.999601,0.999537,0.000153,2,0.996789,0.996709,0.997266,0.996895,0.996311,0.996794,0.000308,12,0.998246,0.998113,0.998260,0.998246,0.997953,0.998164,0.000118,12,0.995640,0.995309,0.995667,0.995639,0.994916,0.995434,0.000291,12,0.997197,0.996985,0.997219,0.997197,0.996730,0.997066,0.000188,12,0.997810,0.997399,0.997147,0.997651,0.997359,0.997473,0.000233,6,102.724184,3.637791,0.775114,0.066513

modelo: random_forest
 origem do treinamento: cicids2017_unsw_nb15
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: random_forest - cicids2017_unsw_nb15

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
4,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,5,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 168}",0.960602,0.961756,0.960452,0.962889,0.962694,0.961678,0.001016,2,0.992675,0.994480,0.992622,0.992993,0.993047,0.993163,0.000679,3,0.976375,0.977844,0.976272,0.977709,0.977635,0.977167,0.000693,1,0.998153,0.998608,0.998140,0.998235,0.998248,0.998277,0.000171,3,0.989822,0.990114,0.989782,0.990432,0.990379,0.990106,0.000271,2,0.993970,0.994343,0.993943,0.994318,0.994298,0.994174,0.000179,1,0.985173,0.986093,0.985108,0.986014,0.985966,0.985671,0.000436,1,0.990392,0.990987,0.990350,0.990944,0.990913,0.990717,0.000284,1,0.991248,0.992297,0.991202,0.991713,0.991713,0.991634,0.000397,3,224.279831,4.458686,1.241000,0.027039
0,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,1,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 237}",0.956024,0.957762,0.956358,0.959414,0.958301,0.957572,0.001252,10,0.997027,0.997824,0.996868,0.997558,0.996603,0.997176,0.000450,1,0.976095,0.977383,0.976193,0.978114,0.977077,0.976972,0.000756,2,0.999249,0.999450,0.999209,0.999383,0.999142,0.999287,0.000114,1,0.988535,0.988999,0.988627,0.989450,0.989158,0.988954,0.000338,10,0.993863,0.994197,0.993890,0.994392,0.994125,0.994093,0.000198,3,0.984979,0.985790,0.985041,0.986253,0.985601,0.985533,0.000477,2,0.990233,0.990764,0.990276,0.991072,0.990647,0.990598,0.000314,3,0.992781,0.993411,0.992748,0.993504,0.992881,0.993065,0.000325,1,277.460174,5.802399,1.657356,0.108541
3,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,4,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 246}",0.960183,0.961264,0.960232,0.962936,0.962260,0.961375,0.001092,3,0.992038,0.994533,0.992038,0.992940,0.993365,0.992983,0.000931,5,0.975850,0.977615,0.975876,0.977708,0.977565,0.976923,0.000867,3,0.997993,0.998621,0.997993,0.998221,0.998328,0.998231,0.000235,5,0.989716,0.989981,0.989729,0.990445,0.990260,0.990026,0.000289,3,0.993837,0.994282,0.993844,0.994318,0.994277,0.994112,0.000222,2,0.984844,0.985949,0.984860,0.986013,0.985921,0.985517,0.000544,3,0.990180,0.990891,0.990191,0.990944,0.990881,0.990617,0.000353,2,0.990877,0.992257,0.990883,0.991693,0.991812,0.991504,0.000543,4,322.292826,6.161989,1.849466,0.143288
2,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,3,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 125}",0.959998,0.961086,0.959751,0.962683,0.961734,0.961050,0.001089,4,0.992356,0.993736,0.991082,0.992781,0.992516,0.992494,0.000853,9,0.975909,0.977139,0.975165,0.977500,0.976883,0.976519,0.000858,4,0.998073,0.998421,0.997752,0.998181,0.998114,0.998108,0.000215,9,0.989663,0.989941,0.989609,0.990379,0.990127,0.989944,0.000288,4,0.993850,0.994163,0.993664,0.994265,0.994104,0.994009,0.000220,4,0.984879,0.985651,0.984415,0.985882,0.985493,0.985264,0.000539,4,0.990201,0.990700,0.989904,0.990859,0.990605,0.990454,0.000350,4,0.991009,0.991839,0.990346,0.991580,0.991321,0.991219,0.000516,6,160.251868,3.615450,0.998693,0.073406
10,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,11,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 249}",0.959507,0.960536,0.959437,0.961918,0.961392,0.960558,0.000991,5,0.992409,0.993524,0.991879,0.993524,0.992622,0.992792,0.000645,8,0.975681,0.976751,0.975388,0.977466,0.976758,0.976409,0.000765,5,0.998086,0.998367,0.997952,0.998368,0.998140,0.998183,0.000163,8,0.989530,0.989795,0.989517,0.990167,0.990034,0.989808,0.000262,5,0.993789,0.994063,0.993717,0.994250,0.994071,0.993978,0.000197,5,0.984735,0.985407,0.984552,0.985858,0.985414,0.985193,0.000481,5,0.990106,0.990541,0.989989,0.990838,0.990552,0.990405,0.000313,5,0.990970,0.991660,0.990698,0.991845,0.991328,0.991300,0.000424,5,326.804125,13.188152,1.572742,0.141400
1,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,2,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 229}",0.962817,0.963411,0.962618,0.965148,0.964400,0.963679,0.000961,1,0.988269,0.989543,0.988269,0.989278,0.989278,0.988927,0.000546,10,0.975377,0.976302,0.975275,0.977064,0.976681,0.976140,0.000707,6,0.997048,0.997368,0.997048,0.997303,0.997302,0.997214,0.000138,10,0.990459,0.990605,0.990406,0.991069,0.990870,0.990682,0.000252,1,0.993742,0.993975,0.993716,0.994176,0.994076,0.993937,0.000182,6,0.984560,0.985138,0.984495,0.985620,0.985378,0.985038,0.000444,6,0.990021,0.990392,0.989978,0.990711,0.990552,0.990331,0.000289,6,0.989364,0.990074,0.989337,0.990173,0.990074,0.989805,0.000372,10,283.436798,4.051450,1.830270,0.120574
9,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,10,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 300}",0.955550,0.957843,0.955298,0.957475,0.956528,0.956539,0.001009,12,0.996178,0.997399,0.995966,0.996762,0.996231,0.996507,0.000517,2,0.975441,0.977221,0.975208,0.976724,0.975976,0.976114,0.000760,7,0.999034,0.999343,0.998981,0.999182,0.999048,0.999118,0.000131,2,0.988415,0.989026,0.988349,0.988933,0.988680,0.988681,0.000269,12,0.993696,0.994158,0.993636,0.994031,0.993837,0.993872,0.000197,7,0.984569,0.985689,0.984422,0.985377,0.984907,0.984993,0.000479,7,0.989968,0.990700,0.989872,0.990499,0.990191,0.990246,0.000313,7,0.992297,0.993212,0.992157,0.992847,0.992456,0.992594,0.000386,2,375.454183,3.266756,1.925453,0.175715
7,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,8,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 228}",0.955660,0.957449,0.957270,0.959756,0.958515,0.957730,0.001364,9,0.993046,0.993736,0.991772,0.993736,0.992144,0.992887,0.000808,6,0.973995,0.975255,0.974216,0.976451,0.975040,0.974991,0.000871,8,0.998244,0.998419,0.997924,0.998420,0.998019,0.998205,0.000204,6,0.988481,0.988959,0.988933,0.989583,0.989264,0.989044,0.000367,9,0.993339,0.993667,0.993408,0.993982,0.993622,0.993604,0.000226,8,0.983667,0.984461,0.983812,0.985216,0.984331,0.984297,0.000549,8,0.989394,0.989915,0.989501,0.990414,0.989840,0.989813,0.000359,8,0.990764,0.991348,0.990353,0.991660,0.990704,0.990966,0.000472,8,253.661154,2.800253,1.322109,0.077357
5,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,6,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 196}",0.955602,0.957398,0.957366,0.959705,0.958759,0.957766,0.001394,8,0.992834,0.993683,0.991719,0.993683,0.992091,0.992802,0.000804,7,0.973862,0.975203,0.974240,0.976398,0.975140,0.974969,0.000881,9,0.998191,0.998406,0.997911,0.998407,0.998005,0.998184,0.000203,7,0.988468,0.988946,0.988959,0.989570,0.989331,0.989055,0.000376,8,0.993306,0.993653,0.993415,0.993969,0.993649,0.993598,0.000229,9,0.983584,0.984428,0.983827,0.985184,0.984395,0.984284,0.000555,9,0.989341,0.989893,0.989511,0.990392,0.989883,0.989804,0.000363,9,0.990651,0.991315,0.990339,0.991626,0.990711,0.990928,0.000471,9,214.773385,6.635555,1.115364,0.021700
11,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,12,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 296}",0.955353,0.956957,0.956909,0.959414,0.958032,0.957333,0.001346,11,0.992728,0.993683,0.992516,0.993789,0.992357,0.993015,0.000602,4,0.973682,0.974975,0.974387,0.976299,0.974892,0.974847,0.000860,10,0.998164,0.998406,0.998111,0.998433,0.998072,0.998237,0.000152,4,0.988402,0.988827,0.988827,0.989490,0.989132,0.988935,0.000362,11,0.993259,0.993593,0.993447,0.993942,0.993582,0.993564,0.000224,10,0.983471,0.984284,0.983917,0.985120,0.984237,0.984206,0.000542,10,0.989267,0.989798,0.989564,0.990350,0.989777,0.989751,0.000355,10,0.990565,0.991255,0.990671,0.991640,0.990744,0.990975,0.000408,7,239.487277,49.499688,1.193597,0.060301
8,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,9,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 241}",0.958065,0.959637,0.958532,0.960986,0.960573,0.959558,0.001128,6,0.987154,0.986889,0.984023,0.987154,0.985403,0.986125,0.001236,11,0.972392,0.973072,0.971110,0.973894,0.972830,0.972660,0.000916,11,0.996764,0.996699,0.995979,0.996767,0.996327,0.996507,0.000310,11,0.989198,0.989623,0.989357,0.989981,0.989888,0.989609,0.000300,6,0.992967,0.993148,0.992657,0.993362,0.993097,0.993046,0.000233,11,0.982679,0.983110,0.981883,0.983628,0.982963,0.982853,0.000574,11,0.988789,0.989076,0.988290,0.989416,0.988991,0.988912,0.000371,11,0.988176,0.988256,0.986690,0.988568,0.987646,0.987867,0.000659,11,274.857987,3.359641,1.371976,0.111160
6,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,7,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 107}",0.958097,0.959575,0.958629,0.960883,0.960526,0.959542,0.001067,7,0.986730,0.986570,0.983969,0.987048,0.985456,0.985955,0.001128,12,0.972203,0.972885,0.971134,0.973790,0.972831,0.972569,0.000878,12,0.996657,0.996619,0.995966,0.996740,0.996340,0.996464,0.000283,12,0.989211,0.989609,0.989384,0.989954,0.989875,0.989607,0.000282,7,0.992920,0.993102,0.992664,0.993336,0.993097,0.993024,0.000223,12,0.982562,0.982994,0.981899,0.983563,0.982964,0.982796,0.000550,12,0.988715,0.989002,0.988301,0.989373,0.988991,0.988876,0.000356,12,0.987971,0.988090,0.986677,0.988501,0.987666,0.987781,0.000614,12,122.270865,5.555790,0.702634,0.050044

modelo: random_forest
 origem do treinamento: cicids2017_iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: random_forest - cicids2017_iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
3,random_forest,randomized_search,cicids2017_iot23,470980,12,5,1,4,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 246}",0.988842,0.988013,0.988690,0.988863,0.989848,0.988851,0.000587,4,0.992622,0.993153,0.992993,0.994480,0.993684,0.993386,0.000645,7,0.990728,0.990576,0.990837,0.991663,0.991762,0.991113,0.000497,1,0.998154,0.998286,0.998246,0.998618,0.998419,0.998345,0.000161,7,0.997200,0.996988,0.997160,0.997200,0.997452,0.997200,0.000148,4,0.997677,0.997636,0.997703,0.997908,0.997935,0.997772,0.000125,1,0.994203,0.994106,0.994270,0.994786,0.994849,0.994443,0.000311,1,0.996284,0.996221,0.996327,0.996656,0.996698,0.996437,0.000199,1,0.994911,0.995070,0.995077,0.995840,0.995568,0.995293,0.000351,5,302.006356,4.515637,1.595669,0.048568
4,random_forest,randomized_search,cicids2017_iot23,470980,12,5,1,5,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 168}",0.989100,0.988113,0.989207,0.988963,0.989894,0.989055,0.000570,1,0.992250,0.992781,0.992462,0.994055,0.993047,0.992919,0.000630,9,0.990673,0.990441,0.990832,0.991502,0.991468,0.990983,0.000428,2,0.998061,0.998193,0.998114,0.998512,0.998260,0.998228,0.000157,9,0.997266,0.997014,0.997293,0.997227,0.997465,0.997253,0.000145,1,0.997664,0.997603,0.997703,0.997869,0.997863,0.997740,0.000107,2,0.994168,0.994022,0.994268,0.994686,0.994665,0.994362,0.000268,2,0.996263,0.996168,0.996327,0.996592,0.996582,0.996386,0.000172,2,0.994758,0.994898,0.994878,0.995641,0.995256,0.995086,0.000323,9,204.402888,1.685709,1.130577,0.026481
2,random_forest,randomized_search,cicids2017_iot23,470980,12,5,1,3,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 125}",0.988686,0.988012,0.988689,0.988701,0.989740,0.988765,0.000554,5,0.992622,0.993046,0.992940,0.994002,0.993312,0.993184,0.000465,8,0.990650,0.990523,0.990810,0.991344,0.991523,0.990970,0.000393,3,0.998154,0.998259,0.998233,0.998498,0.998326,0.998294,0.000116,8,0.997160,0.996988,0.997160,0.997160,0.997426,0.997179,0.000140,5,0.997657,0.997623,0.997696,0.997829,0.997876,0.997736,0.000099,3,0.994153,0.994073,0.994253,0.994587,0.994699,0.994353,0.000246,3,0.996252,0.996199,0.996316,0.996529,0.996603,0.996380,0.000158,3,0.994891,0.995017,0.995050,0.995581,0.995369,0.995182,0.000254,8,152.181951,4.271555,0.886880,0.041563
10,random_forest,randomized_search,cicids2017_iot23,470980,12,5,1,11,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 249}",0.988733,0.987951,0.988682,0.988596,0.989733,0.988739,0.000572,6,0.992197,0.992303,0.992303,0.993896,0.992675,0.992675,0.000632,10,0.990462,0.990122,0.990489,0.991239,0.991202,0.990703,0.000442,4,0.998048,0.998074,0.998074,0.998472,0.998167,0.998167,0.000158,10,0.997173,0.996974,0.997160,0.997134,0.997426,0.997173,0.000145,6,0.997610,0.997524,0.997617,0.997802,0.997796,0.997670,0.000111,4,0.994036,0.993823,0.994053,0.994520,0.994499,0.994186,0.000276,4,0.996178,0.996040,0.996189,0.996486,0.996475,0.996274,0.000177,4,0.994685,0.994639,0.994732,0.995515,0.995050,0.994924,0.000329,10,300.479290,13.038117,1.472406,0.187546
1,random_forest,randomized_search,cicids2017_iot23,470980,12,5,1,2,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 229}",0.984399,0.982825,0.984199,0.984051,0.985024,0.984099,0.000719,7,0.994745,0.996284,0.995170,0.995647,0.994958,0.995361,0.000550,3,0.989545,0.989509,0.989654,0.989815,0.989966,0.989698,0.000171,5,0.998683,0.999068,0.998789,0.998909,0.998736,0.998837,0.000138,3,0.996059,0.995647,0.996006,0.995966,0.996218,0.995979,0.000187,7,0.997369,0.997355,0.997395,0.997435,0.997475,0.997406,0.000044,5,0.993457,0.993432,0.993525,0.993625,0.993721,0.993552,0.000108,5,0.995796,0.995775,0.995838,0.995902,0.995966,0.995855,0.000070,5,0.995402,0.995966,0.995588,0.995807,0.995588,0.995670,0.000196,3,251.195058,4.975769,1.558582,0.097243
0,random_forest,randomized_search,cicids2017_iot23,470980,12,5,1,1,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 237}",0.981349,0.980138,0.981150,0.981470,0.982488,0.981319,0.000750,11,0.997081,0.997983,0.997399,0.998089,0.997611,0.997633,0.000372,1,0.989152,0.988980,0.989208,0.989710,0.989992,0.989408,0.000380,6,0.999267,0.999493,0.999347,0.999520,0.999401,0.999406,0.000093,1,0.995263,0.994944,0.995209,0.995289,0.995554,0.995252,0.000195,11,0.997261,0.997214,0.997274,0.997400,0.997474,0.997324,0.000097,6,0.993207,0.993097,0.993241,0.993555,0.993733,0.993366,0.000238,6,0.995626,0.995552,0.995647,0.995849,0.995966,0.995728,0.000154,6,0.996172,0.996463,0.996304,0.996689,0.996583,0.996442,0.000186,1,255.933825,6.144525,1.585424,0.129873
9,random_forest,randomized_search,cicids2017_iot23,470980,12,5,1,10,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 300}",0.980419,0.979927,0.980227,0.979933,0.981104,0.980322,0.000433,12,0.996656,0.997664,0.997346,0.997983,0.997665,0.997463,0.000451,2,0.988471,0.988716,0.988713,0.988876,0.989315,0.988818,0.000280,7,0.999161,0.999413,0.999334,0.999493,0.999414,0.999363,0.000113,2,0.995024,0.994891,0.994971,0.994891,0.995196,0.994994,0.000113,12,0.997088,0.997147,0.997147,0.997187,0.997300,0.997174,0.000071,7,0.992779,0.992932,0.992930,0.993031,0.993308,0.992996,0.000175,7,0.995350,0.995446,0.995446,0.995509,0.995690,0.995488,0.000113,7,0.995840,0.996278,0.996158,0.996437,0.996430,0.996229,0.000220,2,329.036639,4.032100,1.824406,0.070672
11,random_forest,randomized_search,cicids2017_iot23,470980,12,5,1,12,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 296}",0.981974,0.980600,0.982291,0.982254,0.983113,0.982047,0.000817,10,0.994745,0.995435,0.995170,0.996019,0.995011,0.995276,0.000434,4,0.988318,0.987962,0.988688,0.989089,0.989026,0.988617,0.000427,8,0.998682,0.998854,0.998788,0.999001,0.998749,0.998815,0.000109,4,0.995435,0.995077,0.995515,0.995501,0.995727,0.995451,0.000211,10,0.997056,0.996962,0.997149,0.997248,0.997236,0.997130,0.000109,8,0.992687,0.992462,0.992919,0.993168,0.993131,0.992873,0.000268,8,0.995297,0.995148,0.995446,0.995605,0.995584,0.995416,0.000173,8,0.995090,0.995256,0.995342,0.995760,0.995369,0.995363,0.000221,4,212.887594,48.149654,1.146561,0.094628
7,random_forest,randomized_search,cicids2017_iot23,470980,12,5,1,8,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 228}",0.981973,0.981062,0.982336,0.982400,0.983215,0.982197,0.000698,8,0.994692,0.995435,0.994798,0.995541,0.994958,0.995085,0.000342,5,0.988292,0.988196,0.988528,0.988927,0.989052,0.988599,0.000339,9,0.998669,0.998855,0.998695,0.998882,0.998736,0.998767,0.000086,5,0.995435,0.995196,0.995528,0.995541,0.995753,0.995491,0.000180,8,0.997049,0.997022,0.997109,0.997209,0.997242,0.997126,0.000086,9,0.992671,0.992609,0.992818,0.993068,0.993147,0.992863,0.000213,9,0.995286,0.995244,0.995382,0.995541,0.995594,0.995410,0.000138,9,0.995063,0.995316,0.995163,0.995541,0.995356,0.995288,0.000165,6,209.983662,2.830130,1.201495,0.038154
5,random_forest,randomized_search,cicids2017_iot23,470980,12,5,1,6,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 196}",0.982025,0.980754,0.982324,0.982399,0.983112,0.982123,0.000772,9,0.994692,0.995435,0.994108,0.995488,0.994958,0.994936,0.000510,6,0.988318,0.988040,0.988181,0.988900,0.988999,0.988488,0.000389,10,0.998669,0.998854,0.998523,0.998868,0.998736,0.998730,0.000128,6,0.995448,0.995117,0.995528,0.995541,0.995727,0.995472,0.000200,9,0.997056,0.996982,0.997023,0.997202,0.997229,0.997098,0.000099,10,0.992687,0.992511,0.992602,0.993051,0.993114,0.992793,0.000244,10,0.995297,0.995180,0.995244,0.995531,0.995573,0.995365,0.000158,10,0.995070,0.995276,0.994818,0.995515,0.995342,0.995204,0.000240,7,183.586571,4.440948,1.053874,0.032031
8,random_forest,randomized_search,cicids2017_iot23,470980,12,5,1,9,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 241}",0.988936,0.987929,0.989134,0.988676,0.989683,0.988871,0.000576,2,0.986836,0.986146,0.985721,0.987101,0.987792,0.986719,0.000726,11,0.987885,0.987036,0.987425,0.987888,0.988737,0.987794,0.000568,11,0.996711,0.996538,0.996433,0.996777,0.996949,0.996682,0.000181,11,0.997240,0.996988,0.997293,0.997173,0.997426,0.997224,0.000144,2,0.996975,0.996763,0.996863,0.996975,0.997187,0.996953,0.000142,11,0.992430,0.991900,0.992144,0.992431,0.992962,0.992373,0.000355,11,0.995159,0.994819,0.994979,0.995159,0.995499,0.995123,0.000227,11,0.992038,0.991567,0.991507,0.992137,0.992609,0.991972,0.000404,11,232.278391,4.794413,1.292115,0.101435
6,random_forest,randomized_search,cicids2017_iot23,470980,12,5,1,7,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 107}",0.988935,0.987879,0.989079,0.988723,0.989685,0.988860,0.000586,3,0.986783,0.986411,0.985509,0.986623,0.988004,0.986666,0.000801,12,0.987858,0.987145,0.987291,0.987672,0.988844,0.987762,0.000599,12,0.996698,0.996604,0.996381,0.996658,0.997002,0.996668,0.000200,12,0.997240,0.996974,0.997280,0.997187,0.997426,0.997221,0.000147,3,0.996969,0.996789,0.996830,0.996922,0.997214,0.996945,0.000149,12,0.992413,0.991967,0.992060,0.992297,0.993029,0.992353,0.000374,12,0.995148,0.994862,0.994925,0.995074,0.995541,0.995110,0.000238,12,0.992011,0.991693,0.991394,0.991905,0.992715,0.991944,0.000439,12,103.396319,3.358606,0.665250,0.036776

modelo: random_forest
 origem do treinamento: unsw_nb15_iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: random_forest - unsw_nb15_iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
4,random_forest,randomized_search,unsw_nb15_iot23,470980,12,5,1,5,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 168}",0.971069,0.969832,0.970672,0.970909,0.972002,0.970897,0.000698,1,0.994161,0.994851,0.994373,0.995647,0.995064,0.994819,0.000525,8,0.982479,0.982182,0.982380,0.983123,0.983398,0.982712,0.000466,1,0.998532,0.998704,0.998585,0.998905,0.998758,0.998697,0.000132,8,0.992595,0.992263,0.992489,0.992542,0.992834,0.992545,0.000184,1,0.995555,0.995474,0.995528,0.995713,0.995787,0.995611,0.000119,1,0.989017,0.988828,0.988954,0.989418,0.989593,0.989162,0.000292,1,0.992908,0.992781,0.992866,0.993163,0.993280,0.993000,0.000189,1,0.993378,0.993557,0.993431,0.994095,0.993949,0.993682,0.000287,7,173.366917,4.655789,1.197555,0.057861
10,random_forest,randomized_search,unsw_nb15_iot23,470980,12,5,1,11,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 249}",0.970337,0.969181,0.970282,0.970319,0.970610,0.970146,0.000496,4,0.994957,0.994904,0.994798,0.996072,0.995648,0.995276,0.000498,6,0.982493,0.981874,0.982387,0.983027,0.982969,0.982550,0.000422,2,0.998731,0.998718,0.998691,0.999011,0.998905,0.998811,0.000125,6,0.992396,0.992091,0.992383,0.992383,0.992462,0.992343,0.000129,4,0.995554,0.995393,0.995527,0.995686,0.995673,0.995567,0.000107,2,0.989023,0.988634,0.988957,0.989357,0.989321,0.989058,0.000264,2,0.992908,0.992654,0.992866,0.993121,0.993099,0.992930,0.000171,2,0.993677,0.993498,0.993590,0.994227,0.994055,0.993809,0.000282,6,243.312193,8.418927,1.411699,0.094504
2,random_forest,randomized_search,unsw_nb15_iot23,470980,12,5,1,3,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 125}",0.970622,0.969520,0.970524,0.970762,0.970745,0.970435,0.000465,3,0.994373,0.994480,0.994480,0.995753,0.995117,0.994841,0.000527,7,0.982354,0.981841,0.982356,0.983099,0.982780,0.982486,0.000427,3,0.998585,0.998611,0.998611,0.998932,0.998771,0.998702,0.000132,7,0.992476,0.992184,0.992449,0.992502,0.992502,0.992423,0.000121,3,0.995521,0.995387,0.995521,0.995707,0.995627,0.995552,0.000108,3,0.988937,0.988614,0.988938,0.989403,0.989203,0.989019,0.000268,3,0.992855,0.992643,0.992855,0.993153,0.993025,0.992906,0.000173,3,0.993425,0.993332,0.993464,0.994128,0.993810,0.993632,0.000296,8,127.871204,3.866897,0.910298,0.060149
3,random_forest,randomized_search,unsw_nb15_iot23,470980,12,5,1,4,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 246}",0.970863,0.969667,0.970764,0.971053,0.970942,0.970658,0.000504,2,0.994002,0.994373,0.994055,0.995382,0.994958,0.994554,0.000536,10,0.982296,0.981865,0.982271,0.983067,0.982803,0.982460,0.000425,4,0.998491,0.998584,0.998505,0.998838,0.998731,0.998630,0.000135,10,0.992542,0.992224,0.992516,0.992582,0.992555,0.992484,0.000132,2,0.995508,0.995394,0.995501,0.995700,0.995634,0.995547,0.000108,4,0.988902,0.988629,0.988886,0.989384,0.989218,0.989004,0.000266,4,0.992834,0.992654,0.992823,0.993142,0.993036,0.992898,0.000172,4,0.993272,0.993299,0.993285,0.993982,0.993756,0.993519,0.000295,9,248.792970,4.252548,1.571691,0.046519
8,random_forest,randomized_search,unsw_nb15_iot23,470980,12,5,1,9,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 241}",0.969572,0.967559,0.969247,0.969042,0.969453,0.968974,0.000731,5,0.994533,0.994214,0.993736,0.995276,0.995541,0.994660,0.000667,9,0.981893,0.980705,0.981339,0.981984,0.982324,0.981649,0.000568,5,0.998624,0.998544,0.998424,0.998811,0.998878,0.998656,0.000168,9,0.992197,0.991666,0.992118,0.992051,0.992157,0.992038,0.000192,6,0.995400,0.995093,0.995261,0.995420,0.995506,0.995336,0.000145,5,0.988647,0.987899,0.988300,0.988702,0.988915,0.988493,0.000356,5,0.992664,0.992176,0.992441,0.992696,0.992834,0.992562,0.000231,5,0.993365,0.992940,0.992927,0.993663,0.993849,0.993349,0.000373,10,216.580660,3.827037,1.331560,0.090462
6,random_forest,randomized_search,unsw_nb15_iot23,470980,12,5,1,7,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 107}",0.969224,0.967654,0.969344,0.969083,0.969548,0.968970,0.000676,6,0.994639,0.994055,0.993630,0.994957,0.995382,0.994533,0.000625,11,0.981767,0.980677,0.981337,0.981850,0.982295,0.981585,0.000547,6,0.998651,0.998504,0.998398,0.998731,0.998838,0.998624,0.000157,11,0.992104,0.991693,0.992144,0.992064,0.992184,0.992038,0.000177,5,0.995367,0.995087,0.995261,0.995386,0.995500,0.995320,0.000139,6,0.988567,0.987882,0.988299,0.988618,0.988897,0.988453,0.000343,6,0.992611,0.992165,0.992441,0.992643,0.992823,0.992537,0.000222,6,0.993372,0.992874,0.992887,0.993511,0.993783,0.993285,0.000356,11,93.698527,1.191458,0.705807,0.062742
0,random_forest,randomized_search,unsw_nb15_iot23,470980,12,5,1,1,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 237}",0.962095,0.960384,0.962743,0.961818,0.962813,0.961971,0.000879,8,0.998354,0.998567,0.998567,0.998832,0.999098,0.998684,0.000257,2,0.979890,0.979103,0.980328,0.979976,0.980620,0.979983,0.000511,7,0.999585,0.999638,0.999638,0.999705,0.999772,0.999668,0.000065,2,0.990167,0.989702,0.990339,0.990087,0.990352,0.990130,0.000236,8,0.994853,0.994645,0.994967,0.994873,0.995040,0.994876,0.000133,7,0.987372,0.986874,0.987647,0.987424,0.987830,0.987430,0.000322,7,0.991804,0.991475,0.991985,0.991836,0.992102,0.991840,0.000212,7,0.994261,0.994135,0.994453,0.994460,0.994725,0.994407,0.000201,1,217.017073,6.018757,1.446035,0.079573
9,random_forest,randomized_search,unsw_nb15_iot23,470980,12,5,1,10,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 300}",0.961900,0.960235,0.962451,0.961820,0.962664,0.961814,0.000852,9,0.998408,0.998514,0.998673,0.998885,0.999045,0.998705,0.000234,1,0.979814,0.979000,0.980228,0.980002,0.980517,0.979912,0.000513,8,0.999598,0.999625,0.999665,0.999719,0.999759,0.999673,0.000059,1,0.990114,0.989663,0.990260,0.990087,0.990313,0.990087,0.000229,9,0.994833,0.994619,0.994940,0.994880,0.995013,0.994857,0.000134,8,0.987324,0.986809,0.987584,0.987441,0.987765,0.987385,0.000323,8,0.991772,0.991433,0.991942,0.991847,0.992059,0.991811,0.000212,8,0.994261,0.994088,0.994466,0.994486,0.994679,0.994396,0.000203,2,273.146171,2.988890,1.778324,0.145184
5,random_forest,randomized_search,unsw_nb15_iot23,470980,12,5,1,6,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 196}",0.961700,0.959747,0.961556,0.961271,0.961729,0.961201,0.000745,10,0.998301,0.998567,0.998408,0.998673,0.999045,0.998599,0.000257,3,0.979659,0.978772,0.979635,0.979615,0.980032,0.979543,0.000415,9,0.999571,0.999638,0.999598,0.999665,0.999759,0.999646,0.000065,3,0.990061,0.989530,0.990021,0.989941,0.990061,0.989923,0.000201,10,0.994793,0.994558,0.994786,0.994779,0.994886,0.994761,0.000108,10,0.987226,0.986665,0.987211,0.987197,0.987459,0.987152,0.000262,10,0.991709,0.991337,0.991698,0.991688,0.991857,0.991658,0.000172,10,0.994181,0.994048,0.994214,0.994307,0.994553,0.994261,0.000168,3,169.712182,4.039761,1.081455,0.047635
7,random_forest,randomized_search,unsw_nb15_iot23,470980,12,5,1,8,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 228}",0.961749,0.959600,0.961605,0.961222,0.961680,0.961171,0.000806,11,0.998301,0.998567,0.998408,0.998673,0.999045,0.998599,0.000257,3,0.979684,0.978696,0.979661,0.979590,0.980006,0.979527,0.000440,10,0.999571,0.999638,0.999598,0.999665,0.999759,0.999646,0.000065,4,0.990074,0.989490,0.990034,0.989928,0.990047,0.989915,0.000218,11,0.994800,0.994538,0.994793,0.994773,0.994879,0.994757,0.000115,11,0.987242,0.986617,0.987227,0.987181,0.987443,0.987142,0.000277,11,0.991719,0.991305,0.991709,0.991677,0.991847,0.991651,0.000182,11,0.994188,0.994028,0.994221,0.994300,0.994546,0.994257,0.000170,4,196.357728,5.220139,1.223037,0.093878
1,random_forest,randomized_search,unsw_nb15_iot23,470980,12,5,1,2,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 229}",0.967234,0.965720,0.967450,0.967063,0.967393,0.966972,0.000640,7,0.991879,0.992940,0.992356,0.992781,0.992091,0.992409,0.000401,12,0.979401,0.979141,0.979745,0.979753,0.979586,0.979525,0.000231,11,0.997957,0.998223,0.998077,0.998183,0.998010,0.998090,0.000101,12,0.991600,0.991189,0.991653,0.991547,0.991640,0.991526,0.000173,7,0.994768,0.994693,0.994855,0.994854,0.994815,0.994797,0.000061,9,0.987085,0.986917,0.987300,0.987304,0.987201,0.987161,0.000146,9,0.991656,0.991539,0.991794,0.991794,0.991730,0.991702,0.000096,9,0.991739,0.992064,0.992005,0.992164,0.991865,0.991968,0.000150,12,224.534757,7.562030,1.639228,0.109384
11,random_forest,randomized_search,unsw_nb15_iot23,470980,12,5,1,12,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 296}",0.961157,0.958820,0.960916,0.960586,0.961385,0.960573,0.000916,12,0.998248,0.998620,0.998354,0.998726,0.999045,0.998599,0.000282,3,0.979352,0.978315,0.979277,0.979285,0.979853,0.979216,0.000499,12,0.999558,0.999651,0.999585,0.999678,0.999759,0.999646,0.000071,5,0.989915,0.989278,0.989848,0.989755,0.989968,0.989753,0.000248,12,0.994713,0.994437,0.994693,0.994692,0.994839,0.994675,0.000131,12,0.987032,0.986376,0.986985,0.986988,0.987346,0.986946,0.000315,12,0.991581,0.991146,0.991550,0.991550,0.991783,0.991522,0.000207,12,0.994081,0.993949,0.994101,0.994241,0.994506,0.994176,0.000189,5,186.222954,33.191092,1.147517,0.084253

modelo: xgboost
 origem do treinamento: cicids2017
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: xgboost - cicids2017

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
6,xgboost,randomized_search,cicids2017,235490,12,5,1,7,"{""classifier__colsample_bytree"": 0.717772960390469, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9873668590451505}",0.980532,0.980411,0.982891,0.981481,0.979570,0.980977,0.001133,1,0.994585,0.993630,0.994055,0.990234,0.992569,0.993015,0.001540,3,0.987509,0.986976,0.988441,0.985838,0.986027,0.986958,0.000962,1,0.998642,0.998402,0.998509,0.997553,0.998136,0.998248,0.000385,3,0.995064,0.995037,0.995674,0.995329,0.994825,0.995186,0.000292,1,0.996849,0.996717,0.997090,0.996440,0.996478,0.996715,0.000241,1,0.992179,0.991846,0.992766,0.991139,0.991252,0.991836,0.000601,1,0.994968,0.994756,0.995350,0.994310,0.994373,0.994751,0.000386,1,0.994824,0.994333,0.994865,0.992781,0.993697,0.994100,0.000783,3,9.562765,0.088292,0.438146,0.039053
3,xgboost,randomized_search,cicids2017,235490,12,5,1,4,"{""classifier__colsample_bytree"": 0.7688731641189476, ""classifier__learning_rate"": 0.10269165750001427, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 196, ""classifier__subsample"": 0.93351677090096}",0.980940,0.979506,0.982265,0.981696,0.978962,0.980674,0.001260,4,0.994479,0.994585,0.993631,0.990658,0.992887,0.993248,0.001434,2,0.987663,0.986988,0.987915,0.986157,0.985875,0.986920,0.000803,2,0.998615,0.998641,0.998403,0.997659,0.998215,0.998307,0.000359,2,0.995170,0.994798,0.995515,0.995382,0.994665,0.995106,0.000327,4,0.996889,0.996716,0.996957,0.996519,0.996437,0.996704,0.000202,2,0.992276,0.991852,0.992436,0.991338,0.991156,0.991812,0.000502,2,0.995032,0.994756,0.995138,0.994437,0.994310,0.994734,0.000323,2,0.994824,0.994692,0.994573,0.993020,0.993776,0.994177,0.000684,2,8.028620,0.208197,0.352935,0.030399
4,xgboost,randomized_search,cicids2017,235490,12,5,1,5,"{""classifier__colsample_bytree"": 0.9147911547905092, ""classifier__learning_rate"": 0.19049288475798723, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 122, ""classifier__subsample"": 0.8554457646825666}",0.980626,0.979891,0.983388,0.981398,0.979466,0.980954,0.001384,2,0.994161,0.993311,0.992887,0.991295,0.992463,0.992824,0.000948,7,0.987347,0.986556,0.988115,0.986322,0.985921,0.986852,0.000784,3,0.998535,0.998322,0.998217,0.997818,0.998109,0.998200,0.000237,7,0.995090,0.994904,0.995807,0.995302,0.994798,0.995180,0.000357,2,0.996810,0.996610,0.997011,0.996559,0.996451,0.996688,0.000199,3,0.992078,0.991583,0.992563,0.991440,0.991186,0.991770,0.000492,3,0.994904,0.994586,0.995223,0.994501,0.994331,0.994709,0.000317,3,0.994625,0.994108,0.994347,0.993299,0.993630,0.994002,0.000480,5,5.681698,0.299886,0.298077,0.021531
1,xgboost,randomized_search,cicids2017,235490,12,5,1,2,"{""classifier__colsample_bytree"": 0.7277015784306393, ""classifier__learning_rate"": 0.046066102129245355, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 234, ""classifier__subsample"": 0.9806617212418095}",0.980622,0.979402,0.982180,0.980781,0.978550,0.980307,0.001244,8,0.993948,0.994479,0.994692,0.991401,0.992781,0.993460,0.001224,1,0.987240,0.986883,0.988397,0.986063,0.985614,0.986839,0.000969,4,0.998482,0.998615,0.998669,0.997844,0.998189,0.998360,0.000307,1,0.995090,0.994772,0.995488,0.995143,0.994559,0.995010,0.000320,8,0.996783,0.996689,0.997076,0.996492,0.996371,0.996682,0.000244,4,0.992012,0.991786,0.992736,0.991277,0.990992,0.991761,0.000607,4,0.994862,0.994713,0.995329,0.994395,0.994204,0.994700,0.000390,4,0.994519,0.994625,0.995090,0.993272,0.993670,0.994235,0.000665,1,11.143328,0.484542,0.437229,0.012170
2,xgboost,randomized_search,cicids2017,235490,12,5,1,3,"{""classifier__colsample_bytree"": 0.9538932750058051, ""classifier__learning_rate"": 0.061715573864800456, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 239, ""classifier__subsample"": 0.833035868133867}",0.980727,0.980205,0.982460,0.981184,0.978861,0.980687,0.001179,3,0.994055,0.993630,0.992994,0.990870,0.992994,0.992908,0.001096,5,0.987346,0.986872,0.987699,0.986003,0.985877,0.986759,0.000720,5,0.998509,0.998402,0.998244,0.997712,0.998242,0.998222,0.000274,5,0.995117,0.994984,0.995568,0.995249,0.994639,0.995111,0.000306,3,0.996810,0.996690,0.996904,0.996479,0.996437,0.996664,0.000182,5,0.992078,0.991781,0.992301,0.991241,0.991157,0.991712,0.000451,5,0.994904,0.994713,0.995053,0.994373,0.994310,0.994671,0.000290,5,0.994586,0.994307,0.994281,0.993060,0.993816,0.994010,0.000535,4,10.583407,0.459115,0.454696,0.057345
0,xgboost,randomized_search,cicids2017,235490,12,5,1,1,"{""classifier__colsample_bytree"": 0.8251066014107722, ""classifier__learning_rate"": 0.1575599187428391, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 233, ""classifier__subsample"": 0.7440267672451338}",0.980421,0.979983,0.982884,0.980876,0.978441,0.980521,0.001438,5,0.994161,0.992781,0.993631,0.990977,0.992463,0.992802,0.001094,8,0.987243,0.986340,0.988228,0.985901,0.985402,0.986623,0.001005,6,0.998535,0.998189,0.998403,0.997738,0.998109,0.998195,0.000274,8,0.995037,0.994931,0.995674,0.995170,0.994533,0.995069,0.000370,5,0.996783,0.996557,0.997037,0.996452,0.996318,0.996629,0.000254,6,0.992013,0.991449,0.992632,0.991176,0.990860,0.991626,0.000630,6,0.994862,0.994501,0.995265,0.994331,0.994119,0.994615,0.000406,6,0.994599,0.993856,0.994652,0.993073,0.993498,0.993936,0.000616,8,8.782702,0.499099,0.306505,0.026673
10,xgboost,randomized_search,cicids2017,235490,12,5,1,11,"{""classifier__colsample_bytree"": 0.9725786509279286, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 200, ""classifier__subsample"": 0.8574398130611336}",0.980824,0.980090,0.981956,0.980678,0.978548,0.980419,0.001114,7,0.993736,0.992993,0.993631,0.991401,0.992675,0.992887,0.000841,6,0.987238,0.986499,0.987759,0.986011,0.985561,0.986613,0.000798,7,0.998429,0.998243,0.998403,0.997844,0.998162,0.998216,0.000211,6,0.995143,0.994957,0.995435,0.995117,0.994559,0.995042,0.000287,7,0.996783,0.996597,0.996917,0.996479,0.996357,0.996627,0.000202,7,0.992011,0.991548,0.992338,0.991245,0.990959,0.991620,0.000500,7,0.994862,0.994565,0.995074,0.994373,0.994182,0.994611,0.000322,7,0.994440,0.993975,0.994533,0.993259,0.993617,0.993965,0.000483,6,8.722289,0.212229,0.332722,0.022922
9,xgboost,randomized_search,cicids2017,235490,12,5,1,10,"{""classifier__colsample_bytree"": 0.7895485884259134, ""classifier__learning_rate"": 0.08380226576125108, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 253, ""classifier__subsample"": 0.8343680578527715}",0.980109,0.979472,0.982362,0.980477,0.978045,0.980093,0.001405,10,0.993948,0.992887,0.993312,0.991614,0.993100,0.992972,0.000767,4,0.986980,0.986134,0.987807,0.986014,0.985515,0.986490,0.000810,8,0.998482,0.998216,0.998323,0.997897,0.998268,0.998237,0.000192,4,0.994957,0.994798,0.995541,0.995063,0.994426,0.994957,0.000363,10,0.996717,0.996504,0.996930,0.996478,0.996344,0.996595,0.000206,8,0.991848,0.991319,0.992369,0.991246,0.990929,0.991542,0.000508,8,0.994756,0.994416,0.995095,0.994373,0.994161,0.994560,0.000328,8,0.994453,0.993842,0.994427,0.993339,0.993763,0.993965,0.000424,7,8.829152,0.220250,0.308079,0.011623
11,xgboost,randomized_search,cicids2017,235490,12,5,1,12,"{""classifier__colsample_bytree"": 0.7250869013641078, ""classifier__learning_rate"": 0.24773227404307951, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 262, ""classifier__subsample"": 0.7896790336629148}",0.980620,0.979973,0.982152,0.980771,0.978931,0.980489,0.001054,6,0.993842,0.992250,0.993100,0.990870,0.991401,0.992293,0.001084,9,0.987187,0.986073,0.987596,0.985795,0.985127,0.986355,0.000909,9,0.998455,0.998056,0.998270,0.997712,0.997843,0.998067,0.000272,9,0.995090,0.994931,0.995488,0.995143,0.994665,0.995063,0.000270,6,0.996770,0.996491,0.996877,0.996426,0.996252,0.996563,0.000229,9,0.991978,0.991282,0.992236,0.991110,0.990689,0.991459,0.000569,9,0.994841,0.994395,0.995010,0.994289,0.994012,0.994509,0.000366,9,0.994466,0.993590,0.994294,0.993007,0.993033,0.993678,0.000612,9,5.854780,0.911895,0.189036,0.012103
7,xgboost,randomized_search,cicids2017,235490,12,5,1,8,"{""classifier__colsample_bytree"": 0.859949585491905, ""classifier__learning_rate"": 0.14757009901255264, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 143, ""classifier__subsample"": 0.905950278304475}",0.981219,0.978948,0.981839,0.980149,0.978134,0.980058,0.001376,11,0.992887,0.992356,0.992887,0.990658,0.992463,0.992250,0.000825,10,0.987018,0.985607,0.987332,0.985376,0.985246,0.986116,0.000878,10,0.998217,0.998083,0.998217,0.997658,0.998109,0.998057,0.000207,10,0.995249,0.994665,0.995408,0.994984,0.994453,0.994952,0.000355,11,0.996731,0.996371,0.996811,0.996319,0.996277,0.996502,0.000223,10,0.991875,0.990989,0.992072,0.990847,0.990762,0.991309,0.000551,10,0.994777,0.994204,0.994904,0.994119,0.994055,0.994412,0.000356,10,0.994068,0.993511,0.994148,0.992821,0.993458,0.993601,0.000480,10,4.629801,0.079823,0.204528,0.012581
5,xgboost,randomized_search,cicids2017,235490,12,5,1,6,"{""classifier__colsample_bytree"": 0.9595060755936949, ""classifier__learning_rate"": 0.20242687100180323, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 241, ""classifier__subsample"": 0.7819149922650241}",0.979987,0.979656,0.981748,0.980654,0.978630,0.980135,0.001038,9,0.992993,0.991825,0.993524,0.990127,0.991720,0.992038,0.001176,11,0.986447,0.985703,0.987601,0.985368,0.985131,0.986050,0.000894,11,0.998243,0.997950,0.998376,0.997526,0.997923,0.998003,0.000294,11,0.994931,0.994851,0.995382,0.995117,0.994586,0.994973,0.000266,9,0.996584,0.996398,0.996877,0.996320,0.996251,0.996486,0.000225,11,0.991516,0.991051,0.992239,0.990844,0.990691,0.991268,0.000559,11,0.994543,0.994246,0.995010,0.994119,0.994012,0.994386,0.000359,11,0.993962,0.993338,0.994453,0.992622,0.993153,0.993506,0.000639,11,6.608252,0.094766,0.272499,0.037903
8,xgboost,randomized_search,cicids2017,235490,12,5,1,9,"{""classifier__colsample_bytree"": 0.9503877015692118, ""classifier__learning_rate"": 0.03129028595344, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 115, ""classifier__subsample"": 0.8981907190714008}",0.973418,0.972372,0.974343,0.973504,0.970573,0.972842,0.001295,12,0.979722,0.975263,0.979618,0.978981,0.980361,0.978789,0.001817,12,0.976560,0.973815,0.976973,0.976235,0.975442,0.975805,0.001114,12,0.994923,0.993812,0.994897,0.994738,0.995078,0.994689,0.000452,12,0.993312,0.993073,0.993551,0.993338,0.992569,0.993168,0.000336,12,0.994117,0.993442,0.994223,0.994037,0.993822,0.993928,0.000276,12,0.985338,0.983629,0.985598,0.985136,0.984632,0.984867,0.000695,12,0.990594,0.989511,0.990764,0.990467,0.990127,0.990293,0.000443,12,0.986517,0.984168,0.986584,0.986160,0.986465,0.985979,0.000917,12,3.985355,0.142536,0.194827,0.014668

modelo: xgboost
 origem do treinamento: unsw_nb15
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: xgboost - unsw_nb15

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
10,xgboost,randomized_search,unsw_nb15,235490,12,5,1,11,"{""classifier__colsample_bytree"": 0.9725786509279286, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 200, ""classifier__subsample"": 0.8574398130611336}",0.944796,0.945070,0.943001,0.942184,0.941736,0.943358,0.001352,4,0.997558,0.997346,0.997558,0.998195,0.998620,0.997856,0.000477,5,0.970461,0.970505,0.969513,0.969381,0.969344,0.969841,0.000527,1,0.999381,0.999327,0.999381,0.999542,0.999650,0.999456,0.000121,4,0.985430,0.985509,0.984925,0.984686,0.984553,0.985021,0.000386,4,0.992356,0.992370,0.992100,0.992058,0.992044,0.992186,0.000146,2,0.981408,0.981437,0.980806,0.980720,0.980694,0.981013,0.000337,1,0.987855,0.987876,0.987452,0.987388,0.987367,0.987588,0.000229,2,0.991494,0.991427,0.991242,0.991441,0.991587,0.991438,0.000113,4,9.331659,0.162837,0.336002,0.047087
6,xgboost,randomized_search,unsw_nb15,235490,12,5,1,7,"{""classifier__colsample_bytree"": 0.717772960390469, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9873668590451505}",0.944948,0.946609,0.943992,0.943506,0.943267,0.944464,0.001217,2,0.996815,0.995753,0.996603,0.996391,0.997240,0.996560,0.000492,10,0.970189,0.970559,0.969584,0.969228,0.969503,0.969813,0.000488,2,0.999193,0.998924,0.999139,0.999085,0.999300,0.999128,0.000124,10,0.985483,0.985960,0.985217,0.985084,0.985005,0.985350,0.000346,2,0.992290,0.992400,0.992129,0.992035,0.992101,0.992191,0.000134,1,0.981239,0.981480,0.980857,0.980631,0.980802,0.981002,0.000311,2,0.987749,0.987919,0.987494,0.987346,0.987452,0.987592,0.000210,1,0.991149,0.990857,0.990910,0.990737,0.991122,0.990955,0.000158,10,10.555649,0.121694,0.441878,0.027455
1,xgboost,randomized_search,unsw_nb15,235490,12,5,1,2,"{""classifier__colsample_bytree"": 0.7277015784306393, ""classifier__learning_rate"": 0.046066102129245355, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 234, ""classifier__subsample"": 0.9806617212418095}",0.944160,0.945025,0.942350,0.941624,0.941547,0.942941,0.001404,6,0.998089,0.998301,0.997771,0.998301,0.998620,0.998216,0.000280,2,0.970376,0.970933,0.969269,0.969135,0.969244,0.969791,0.000728,3,0.999515,0.999569,0.999434,0.999569,0.999650,0.999548,0.000071,2,0.985244,0.985483,0.984739,0.984527,0.984500,0.984899,0.000396,6,0.992328,0.992476,0.992032,0.991991,0.992017,0.992169,0.000197,3,0.981352,0.981704,0.980651,0.980563,0.980631,0.980980,0.000462,3,0.987813,0.988046,0.987346,0.987282,0.987324,0.987562,0.000310,3,0.991666,0.991892,0.991255,0.991414,0.991560,0.991557,0.000217,2,11.877264,0.778732,0.582087,0.103759
0,xgboost,randomized_search,unsw_nb15,235490,12,5,1,1,"{""classifier__colsample_bytree"": 0.8251066014107722, ""classifier__learning_rate"": 0.1575599187428391, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 233, ""classifier__subsample"": 0.7440267672451338}",0.944612,0.945489,0.941612,0.941224,0.941359,0.942859,0.001815,7,0.997664,0.998089,0.998089,0.997877,0.998620,0.998068,0.000318,3,0.970414,0.971077,0.969029,0.968723,0.969144,0.969677,0.000908,4,0.999408,0.999516,0.999515,0.999461,0.999650,0.999510,0.000080,3,0.985376,0.985615,0.984527,0.984421,0.984447,0.984877,0.000512,7,0.992343,0.992517,0.991964,0.991884,0.991990,0.992140,0.000246,5,0.981378,0.981797,0.980496,0.980303,0.980567,0.980908,0.000577,4,0.987834,0.988110,0.987239,0.987112,0.987282,0.987515,0.000387,5,0.991520,0.991852,0.991308,0.991149,0.991534,0.991473,0.000238,3,9.266012,0.592272,0.297135,0.018888
3,xgboost,randomized_search,unsw_nb15,235490,12,5,1,4,"{""classifier__colsample_bytree"": 0.7688731641189476, ""classifier__learning_rate"": 0.10269165750001427, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 196, ""classifier__subsample"": 0.93351677090096}",0.944601,0.946000,0.942877,0.942209,0.941990,0.943536,0.001536,3,0.997452,0.996921,0.997028,0.996921,0.998089,0.997282,0.000448,9,0.970307,0.970793,0.969197,0.968794,0.969228,0.969664,0.000756,5,0.999354,0.999220,0.999246,0.999219,0.999515,0.999311,0.000114,9,0.985376,0.985775,0.984898,0.984713,0.984633,0.985079,0.000433,3,0.992316,0.992452,0.992020,0.991913,0.992018,0.992144,0.000204,4,0.981312,0.981623,0.980608,0.980353,0.980623,0.980904,0.000480,5,0.987791,0.988004,0.987324,0.987154,0.987324,0.987520,0.000322,4,0.991414,0.991348,0.990963,0.990817,0.991361,0.991181,0.000243,9,9.246402,0.196429,0.383564,0.082220
2,xgboost,randomized_search,unsw_nb15,235490,12,5,1,3,"{""classifier__colsample_bytree"": 0.9538932750058051, ""classifier__learning_rate"": 0.061715573864800456, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 239, ""classifier__subsample"": 0.833035868133867}",0.944439,0.945244,0.942173,0.941506,0.942078,0.943088,0.001472,5,0.997983,0.997027,0.997983,0.997877,0.997983,0.997771,0.000374,6,0.970473,0.970445,0.969275,0.968872,0.969225,0.969658,0.000669,6,0.999488,0.999247,0.999488,0.999461,0.999488,0.999434,0.000095,6,0.985323,0.985562,0.984686,0.984500,0.984659,0.984946,0.000417,5,0.992355,0.992357,0.992032,0.991924,0.992018,0.992137,0.000183,6,0.981414,0.981401,0.980654,0.980398,0.980622,0.980898,0.000426,6,0.987855,0.987855,0.987346,0.987176,0.987324,0.987511,0.000287,6,0.991653,0.991295,0.991335,0.991189,0.991321,0.991358,0.000156,5,11.297064,0.397881,0.465018,0.098871
9,xgboost,randomized_search,unsw_nb15,235490,12,5,1,10,"{""classifier__colsample_bytree"": 0.7895485884259134, ""classifier__learning_rate"": 0.08380226576125108, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 253, ""classifier__subsample"": 0.8343680578527715}",0.943742,0.944651,0.940870,0.940394,0.941459,0.942223,0.001671,10,0.999151,0.998407,0.998301,0.998195,0.998726,0.998556,0.000346,1,0.970656,0.970786,0.968736,0.968433,0.969247,0.969572,0.000975,7,0.999785,0.999596,0.999569,0.999542,0.999677,0.999634,0.000088,1,0.985111,0.985376,0.984314,0.984182,0.984474,0.984691,0.000468,10,0.992394,0.992435,0.991883,0.991802,0.992017,0.992106,0.000261,7,0.981525,0.981610,0.980309,0.980118,0.980632,0.980839,0.000618,7,0.987919,0.987983,0.987112,0.986985,0.987324,0.987464,0.000412,7,0.992131,0.991892,0.991308,0.991189,0.991600,0.991624,0.000352,1,9.193097,0.091387,0.343214,0.031102
11,xgboost,randomized_search,unsw_nb15,235490,12,5,1,12,"{""classifier__colsample_bytree"": 0.7250869013641078, ""classifier__learning_rate"": 0.24773227404307951, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 262, ""classifier__subsample"": 0.7896790336629148}",0.944121,0.944981,0.940723,0.940664,0.941713,0.942440,0.001784,8,0.997346,0.997452,0.997346,0.997983,0.998195,0.997664,0.000355,8,0.970004,0.970508,0.968207,0.968476,0.969132,0.969265,0.000877,8,0.999327,0.999354,0.999326,0.999488,0.999542,0.999407,0.000090,8,0.985244,0.985483,0.984288,0.984261,0.984553,0.984766,0.000504,8,0.992235,0.992370,0.991750,0.991816,0.991991,0.992033,0.000238,8,0.981120,0.981439,0.979979,0.980146,0.980561,0.980649,0.000558,8,0.987664,0.987876,0.986900,0.987006,0.987282,0.987346,0.000375,8,0.991295,0.991467,0.990817,0.991122,0.991374,0.991215,0.000229,8,6.107083,1.004058,0.182135,0.039600
5,xgboost,randomized_search,unsw_nb15,235490,12,5,1,6,"{""classifier__colsample_bytree"": 0.9595060755936949, ""classifier__learning_rate"": 0.20242687100180323, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 241, ""classifier__subsample"": 0.7819149922650241}",0.943669,0.944796,0.941006,0.940841,0.940865,0.942235,0.001670,9,0.997770,0.997558,0.997346,0.997771,0.998195,0.997728,0.000282,7,0.969966,0.970461,0.968357,0.968470,0.968682,0.969187,0.000859,9,0.999435,0.999381,0.999326,0.999434,0.999542,0.999424,0.000071,7,0.985111,0.985430,0.984368,0.984314,0.984314,0.984707,0.000471,9,0.992221,0.992356,0.991791,0.991817,0.991870,0.992011,0.000232,10,0.981094,0.981408,0.980074,0.980143,0.980276,0.980599,0.000545,9,0.987643,0.987855,0.986963,0.987006,0.987091,0.987312,0.000366,9,0.991441,0.991494,0.990857,0.991043,0.991255,0.991218,0.000240,7,6.907472,0.201155,0.256555,0.016835
7,xgboost,randomized_search,unsw_nb15,235490,12,5,1,8,"{""classifier__colsample_bytree"": 0.859949585491905, ""classifier__learning_rate"": 0.14757009901255264, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 143, ""classifier__subsample"": 0.905950278304475}",0.943658,0.944227,0.940647,0.940564,0.941359,0.942091,0.001547,11,0.997558,0.997558,0.997665,0.997877,0.998620,0.997856,0.000400,4,0.969860,0.970160,0.968317,0.968373,0.969144,0.969171,0.000751,10,0.999381,0.999381,0.999407,0.999461,0.999650,0.999456,0.000101,5,0.985111,0.985270,0.984261,0.984235,0.984447,0.984665,0.000438,11,0.992195,0.992275,0.991776,0.991789,0.991990,0.992005,0.000204,11,0.981027,0.981218,0.980047,0.980081,0.980567,0.980588,0.000477,10,0.987600,0.987728,0.986942,0.986963,0.987282,0.987303,0.000321,10,0.991335,0.991414,0.990963,0.991056,0.991534,0.991260,0.000216,6,4.867900,0.108874,0.230757,0.026065
4,xgboost,randomized_search,unsw_nb15,235490,12,5,1,5,"{""classifier__colsample_bytree"": 0.9147911547905092, ""classifier__learning_rate"": 0.19049288475798723, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 122, ""classifier__subsample"": 0.8554457646825666}",0.945921,0.947769,0.945297,0.945354,0.943533,0.945575,0.001359,1,0.993524,0.992144,0.994268,0.993524,0.995117,0.993715,0.000981,11,0.969138,0.969449,0.969164,0.968841,0.968639,0.969046,0.000280,11,0.998360,0.998013,0.998548,0.998360,0.998762,0.998409,0.000247,11,0.985801,0.986332,0.985615,0.985641,0.985111,0.985700,0.000392,1,0.992041,0.992138,0.992039,0.991960,0.991889,0.992014,0.000084,9,0.980590,0.980793,0.980602,0.980400,0.980264,0.980530,0.000182,11,0.987346,0.987494,0.987346,0.987218,0.987112,0.987303,0.000129,11,0.989662,0.989238,0.989941,0.989583,0.990114,0.989708,0.000303,11,6.175682,0.300753,0.280904,0.007726
8,xgboost,randomized_search,unsw_nb15,235490,12,5,1,9,"{""classifier__colsample_bytree"": 0.9503877015692118, ""classifier__learning_rate"": 0.03129028595344, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 115, ""classifier__subsample"": 0.8981907190714008}",0.940828,0.940445,0.937322,0.936864,0.937825,0.938657,0.001649,12,0.977386,0.979085,0.979512,0.976645,0.976752,0.977876,0.001196,12,0.958759,0.959376,0.957953,0.956341,0.956893,0.957864,0.001128,12,0.994292,0.994717,0.994819,0.994098,0.994127,0.994411,0.000301,12,0.984633,0.984501,0.983624,0.983545,0.983810,0.984023,0.000455,12,0.989439,0.989583,0.989190,0.988793,0.988942,0.989189,0.000295,12,0.974099,0.974479,0.973571,0.972567,0.972917,0.973527,0.000711,12,0.983184,0.983418,0.982802,0.982165,0.982398,0.982793,0.000468,12,0.981010,0.981793,0.981568,0.980095,0.980281,0.980949,0.000674,12,4.180690,0.143213,0.203554,0.033586

modelo: xgboost
 origem do treinamento: iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: xgboost - iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
9,xgboost,randomized_search,iot23,235490,12,5,1,10,"{""classifier__colsample_bytree"": 0.7895485884259134, ""classifier__learning_rate"": 0.08380226576125108, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 253, ""classifier__subsample"": 0.8343680578527715}",0.999573,0.999679,0.999679,0.999787,0.999786,0.999701,0.000080,2,0.993948,0.992144,0.992463,0.994374,0.993843,0.993354,0.000882,3,0.996753,0.995897,0.996058,0.997073,0.996806,0.996517,0.000457,1,0.998489,0.998040,0.998119,0.998595,0.998463,0.998341,0.000220,1,0.999894,0.999920,0.999920,0.999947,0.999947,0.999926,0.000020,2,0.999191,0.998979,0.999019,0.999271,0.999204,0.999133,0.000113,1,0.997972,0.997438,0.997538,0.998172,0.998005,0.997825,0.000285,1,0.998705,0.998365,0.998429,0.998832,0.998726,0.998611,0.000181,1,0.996921,0.996032,0.996192,0.997160,0.996895,0.996640,0.000444,1,9.076676,0.240673,0.340675,0.052181
6,xgboost,randomized_search,iot23,235490,12,5,1,7,"{""classifier__colsample_bytree"": 0.717772960390469, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9873668590451505}",0.999573,0.999572,0.999572,0.999893,0.999786,0.999679,0.000135,8,0.993948,0.992144,0.992463,0.994480,0.993737,0.993354,0.000897,2,0.996753,0.995844,0.996005,0.997179,0.996752,0.996507,0.000503,2,0.998489,0.998040,0.998119,0.998622,0.998436,0.998341,0.000224,2,0.999894,0.999894,0.999894,0.999973,0.999947,0.999920,0.000034,5,0.999191,0.998966,0.999006,0.999297,0.999191,0.999130,0.000125,3,0.997972,0.997405,0.997505,0.998238,0.997972,0.997818,0.000314,2,0.998705,0.998344,0.998408,0.998875,0.998705,0.998607,0.000200,2,0.996921,0.996019,0.996178,0.997227,0.996842,0.996637,0.000461,2,9.114581,0.126470,0.450117,0.069819
3,xgboost,randomized_search,iot23,235490,12,5,1,4,"{""classifier__colsample_bytree"": 0.7688731641189476, ""classifier__learning_rate"": 0.10269165750001427, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 196, ""classifier__subsample"": 0.93351677090096}",0.999573,0.999679,0.999572,0.999893,0.999786,0.999701,0.000125,3,0.993842,0.992144,0.992463,0.994374,0.993843,0.993333,0.000869,7,0.996699,0.995897,0.996005,0.997126,0.996806,0.996507,0.000476,3,0.998463,0.998040,0.998119,0.998595,0.998463,0.998336,0.000216,5,0.999894,0.999920,0.999894,0.999973,0.999947,0.999926,0.000031,4,0.999178,0.998979,0.999006,0.999284,0.999204,0.999130,0.000118,2,0.997939,0.997438,0.997505,0.998205,0.998005,0.997818,0.000297,3,0.998684,0.998365,0.998408,0.998853,0.998726,0.998607,0.000189,3,0.996868,0.996032,0.996178,0.997174,0.996895,0.996629,0.000444,5,7.217835,0.151532,0.327135,0.018332
11,xgboost,randomized_search,iot23,235490,12,5,1,12,"{""classifier__colsample_bytree"": 0.7250869013641078, ""classifier__learning_rate"": 0.24773227404307951, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 262, ""classifier__subsample"": 0.7896790336629148}",0.999573,0.999786,0.999572,0.999680,0.999786,0.999679,0.000096,5,0.993948,0.992250,0.992357,0.994374,0.993737,0.993333,0.000866,5,0.996753,0.996004,0.995951,0.997020,0.996752,0.996496,0.000435,4,0.998489,0.998066,0.998093,0.998595,0.998436,0.998336,0.000216,6,0.999894,0.999947,0.999894,0.999920,0.999947,0.999920,0.000024,8,0.999191,0.999006,0.998992,0.999257,0.999191,0.999128,0.000108,5,0.997972,0.997505,0.997472,0.998139,0.997972,0.997812,0.000271,4,0.998705,0.998408,0.998386,0.998811,0.998705,0.998603,0.000173,5,0.996921,0.996098,0.996125,0.997147,0.996842,0.996627,0.000432,6,6.156079,1.318124,0.181774,0.040726
1,xgboost,randomized_search,iot23,235490,12,5,1,2,"{""classifier__colsample_bytree"": 0.7277015784306393, ""classifier__learning_rate"": 0.046066102129245355, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 234, ""classifier__subsample"": 0.9806617212418095}",0.999573,0.999679,0.999572,1.000000,0.999680,0.999701,0.000157,4,0.993842,0.992144,0.992357,0.994374,0.993843,0.993312,0.000891,8,0.996699,0.995897,0.995951,0.997179,0.996753,0.996496,0.000496,5,0.998463,0.998040,0.998093,0.998595,0.998463,0.998331,0.000222,8,0.999894,0.999920,0.999894,1.000000,0.999920,0.999926,0.000039,2,0.999178,0.998979,0.998992,0.999297,0.999191,0.999128,0.000123,4,0.997939,0.997438,0.997472,0.998238,0.997972,0.997812,0.000309,5,0.998684,0.998365,0.998386,0.998875,0.998705,0.998603,0.000197,4,0.996868,0.996032,0.996125,0.997187,0.996882,0.996619,0.000456,8,9.078398,0.217130,0.360372,0.015440
5,xgboost,randomized_search,iot23,235490,12,5,1,6,"{""classifier__colsample_bytree"": 0.9595060755936949, ""classifier__learning_rate"": 0.20242687100180323, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 241, ""classifier__subsample"": 0.7819149922650241}",0.999573,0.999786,0.999572,0.999680,0.999573,0.999637,0.000085,10,0.993948,0.992144,0.992569,0.994374,0.993737,0.993354,0.000851,3,0.996753,0.995950,0.996058,0.997020,0.996646,0.996485,0.000413,6,0.998489,0.998040,0.998145,0.998595,0.998436,0.998341,0.000212,3,0.999894,0.999947,0.999894,0.999920,0.999894,0.999910,0.000021,10,0.999191,0.998992,0.999019,0.999257,0.999165,0.999125,0.000102,8,0.997972,0.997471,0.997539,0.998139,0.997905,0.997805,0.000257,6,0.998705,0.998386,0.998429,0.998811,0.998662,0.998599,0.000164,6,0.996921,0.996045,0.996231,0.997147,0.996815,0.996632,0.000421,3,6.242549,0.094376,0.259062,0.033336
7,xgboost,randomized_search,iot23,235490,12,5,1,8,"{""classifier__colsample_bytree"": 0.859949585491905, ""classifier__learning_rate"": 0.14757009901255264, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 143, ""classifier__subsample"": 0.905950278304475}",0.999680,0.999786,0.999359,0.999573,0.999893,0.999658,0.000184,9,0.993948,0.992144,0.992357,0.994374,0.993843,0.993333,0.000904,6,0.996806,0.995950,0.995845,0.996967,0.996859,0.996485,0.000484,7,0.998489,0.998040,0.998092,0.998595,0.998463,0.998336,0.000225,7,0.999920,0.999947,0.999841,0.999894,0.999973,0.999915,0.000046,9,0.999204,0.998992,0.998966,0.999244,0.999218,0.999125,0.000120,7,0.998005,0.997471,0.997406,0.998105,0.998038,0.997805,0.000302,7,0.998726,0.998386,0.998344,0.998790,0.998747,0.998599,0.000192,6,0.996934,0.996045,0.996099,0.997134,0.996908,0.996624,0.000458,7,4.175391,0.167510,0.205977,0.014183
2,xgboost,randomized_search,iot23,235490,12,5,1,3,"{""classifier__colsample_bytree"": 0.9538932750058051, ""classifier__learning_rate"": 0.061715573864800456, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 239, ""classifier__subsample"": 0.833035868133867}",0.999573,0.999679,0.999572,0.999787,0.999786,0.999679,0.000096,6,0.993842,0.992037,0.992463,0.994374,0.993843,0.993312,0.000898,9,0.996699,0.995844,0.996005,0.997073,0.996806,0.996485,0.000477,8,0.998463,0.998013,0.998119,0.998595,0.998463,0.998331,0.000224,9,0.999894,0.999920,0.999894,0.999947,0.999947,0.999920,0.000024,6,0.999178,0.998966,0.999006,0.999271,0.999204,0.999125,0.000118,6,0.997939,0.997405,0.997505,0.998172,0.998005,0.997805,0.000297,8,0.998684,0.998344,0.998408,0.998832,0.998726,0.998599,0.000189,6,0.996868,0.995979,0.996178,0.997160,0.996895,0.996616,0.000455,9,8.766333,0.190992,0.383995,0.033265
0,xgboost,randomized_search,iot23,235490,12,5,1,1,"{""classifier__colsample_bytree"": 0.8251066014107722, ""classifier__learning_rate"": 0.1575599187428391, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 233, ""classifier__subsample"": 0.7440267672451338}",0.999573,0.999679,0.999465,0.999680,0.999680,0.999615,0.000086,11,0.993948,0.992250,0.992357,0.994374,0.993843,0.993354,0.000877,1,0.996753,0.995951,0.995898,0.997020,0.996753,0.996475,0.000460,9,0.998489,0.998066,0.998092,0.998595,0.998463,0.998341,0.000219,4,0.999894,0.999920,0.999867,0.999920,0.999920,0.999904,0.000021,12,0.999191,0.998992,0.998979,0.999257,0.999191,0.999122,0.000114,9,0.997972,0.997471,0.997439,0.998139,0.997972,0.997799,0.000287,9,0.998705,0.998386,0.998365,0.998811,0.998705,0.998594,0.000183,9,0.996921,0.996085,0.996112,0.997147,0.996882,0.996629,0.000443,4,8.028750,0.323725,0.334104,0.077691
10,xgboost,randomized_search,iot23,235490,12,5,1,11,"{""classifier__colsample_bytree"": 0.9725786509279286, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 200, ""classifier__subsample"": 0.8574398130611336}",0.999573,0.999679,0.999572,0.999787,0.999786,0.999679,0.000096,7,0.993736,0.992037,0.992357,0.994374,0.993843,0.993269,0.000907,11,0.996646,0.995844,0.995951,0.997073,0.996806,0.996464,0.000483,10,0.998436,0.998013,0.998093,0.998595,0.998463,0.998320,0.000226,11,0.999894,0.999920,0.999894,0.999947,0.999947,0.999920,0.000024,6,0.999165,0.998966,0.998992,0.999271,0.999204,0.999120,0.000120,10,0.997905,0.997405,0.997472,0.998172,0.998005,0.997792,0.000302,10,0.998662,0.998344,0.998386,0.998832,0.998726,0.998590,0.000192,10,0.996815,0.995979,0.996125,0.997160,0.996895,0.996595,0.000460,11,8.280197,0.201717,0.393034,0.058215
4,xgboost,randomized_search,iot23,235490,12,5,1,5,"{""classifier__colsample_bytree"": 0.9147911547905092, ""classifier__learning_rate"": 0.19049288475798723, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 122, ""classifier__subsample"": 0.8554457646825666}",0.999466,0.999465,0.999572,0.999787,0.999786,0.999615,0.000145,12,0.993842,0.992037,0.992463,0.994374,0.993843,0.993312,0.000898,9,0.996646,0.995737,0.996005,0.997073,0.996806,0.996453,0.000502,11,0.998463,0.998013,0.998119,0.998595,0.998463,0.998331,0.000224,10,0.999867,0.999867,0.999894,0.999947,0.999947,0.999904,0.000036,11,0.999165,0.998939,0.999006,0.999271,0.999204,0.999117,0.000124,11,0.997905,0.997338,0.997505,0.998172,0.998005,0.997785,0.000313,11,0.998662,0.998301,0.998408,0.998832,0.998726,0.998586,0.000199,11,0.996855,0.995952,0.996178,0.997160,0.996895,0.996608,0.000461,10,4.998356,0.194470,0.267901,0.016772
8,xgboost,randomized_search,iot23,235490,12,5,1,9,"{""classifier__colsample_bytree"": 0.9503877015692118, ""classifier__learning_rate"": 0.03129028595344, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 115, ""classifier__subsample"": 0.8981907190714008}",0.999893,0.999893,0.999679,0.999786,0.999786,0.999807,0.000080,1,0.992250,0.989277,0.991614,0.991614,0.991614,0.991273,0.001028,12,0.996057,0.994557,0.995630,0.995683,0.995683,0.995522,0.000506,12,0.998066,0.997327,0.997908,0.997908,0.997908,0.997823,0.000256,12,0.999973,0.999973,0.999920,0.999947,0.999947,0.999952,0.000020,1,0.999019,0.998648,0.998913,0.998926,0.998926,0.998887,0.000125,12,0.997538,0.996602,0.997271,0.997305,0.997305,0.997204,0.000316,12,0.998429,0.997834,0.998259,0.998280,0.998280,0.998216,0.000201,12,0.996112,0.994625,0.995767,0.995780,0.995780,0.995613,0.000511,12,3.748188,0.133492,0.215536,0.015833

modelo: xgboost
 origem do treinamento: cicids2017_unsw_nb15
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: xgboost - cicids2017_unsw_nb15

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
6,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,7,"{""classifier__colsample_bytree"": 0.717772960390469, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9873668590451505}",0.959656,0.961414,0.960101,0.961797,0.961754,0.960944,0.000892,2,0.993683,0.994586,0.993736,0.994267,0.993047,0.993864,0.000529,4,0.976373,0.977719,0.976629,0.977763,0.977150,0.977127,0.000561,1,0.998407,0.998635,0.998420,0.998555,0.998247,0.998453,0.000133,4,0.989556,0.990021,0.989676,0.990127,0.990127,0.989901,0.000239,2,0.993962,0.994309,0.994029,0.994323,0.994171,0.994159,0.000145,1,0.985167,0.986014,0.985329,0.986043,0.985660,0.985643,0.000353,1,0.990382,0.990934,0.990488,0.990955,0.990711,0.990694,0.000231,1,0.991620,0.992303,0.991706,0.992197,0.991587,0.991883,0.000304,3,22.608724,0.491375,0.932454,0.056817
4,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,5,"{""classifier__colsample_bytree"": 0.9147911547905092, ""classifier__learning_rate"": 0.19049288475798723, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 122, ""classifier__subsample"": 0.8554457646825666}",0.960695,0.961940,0.960754,0.962629,0.962393,0.961682,0.000813,1,0.992516,0.992781,0.992781,0.992675,0.992941,0.992739,0.000140,6,0.976346,0.977117,0.976505,0.977421,0.977428,0.976964,0.000456,2,0.998113,0.998181,0.998180,0.998154,0.998221,0.998170,0.000035,6,0.989848,0.990180,0.989862,0.990366,0.990299,0.990111,0.000217,1,0.993964,0.994164,0.994003,0.994245,0.994244,0.994124,0.000119,2,0.985155,0.985641,0.985254,0.985833,0.985836,0.985544,0.000288,2,0.990382,0.990700,0.990445,0.990828,0.990828,0.990637,0.000189,2,0.991182,0.991481,0.991321,0.991520,0.991620,0.991425,0.000155,6,13.493208,0.822527,0.559666,0.035027
3,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,4,"{""classifier__colsample_bytree"": 0.7688731641189476, ""classifier__learning_rate"": 0.10269165750001427, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 196, ""classifier__subsample"": 0.93351677090096}",0.959209,0.960385,0.960144,0.961594,0.961420,0.960550,0.000876,3,0.993577,0.994745,0.993577,0.994108,0.993365,0.993874,0.000500,3,0.976091,0.977263,0.976574,0.977581,0.977132,0.976928,0.000530,3,0.998380,0.998674,0.998380,0.998514,0.998327,0.998455,0.000126,3,0.989437,0.989742,0.989689,0.990074,0.990034,0.989795,0.000235,3,0.993888,0.994188,0.994016,0.994276,0.994163,0.994106,0.000138,3,0.984989,0.985726,0.985295,0.985928,0.985647,0.985517,0.000334,3,0.990265,0.990743,0.990467,0.990881,0.990700,0.990611,0.000218,3,0.991507,0.992244,0.991633,0.992091,0.991700,0.991835,0.000283,4,19.424669,1.380993,0.789141,0.089090
10,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,11,"{""classifier__colsample_bytree"": 0.9725786509279286, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 200, ""classifier__subsample"": 0.8574398130611336}",0.958395,0.960045,0.959565,0.961497,0.961041,0.960109,0.001098,5,0.994108,0.994851,0.993896,0.994161,0.993790,0.994161,0.000371,2,0.975925,0.977138,0.976429,0.977556,0.977141,0.976838,0.000583,4,0.998513,0.998701,0.998460,0.998528,0.998434,0.998527,0.000093,1,0.989211,0.989649,0.989530,0.990047,0.989928,0.989673,0.000296,5,0.993840,0.994155,0.993975,0.994269,0.994163,0.994080,0.000153,4,0.984883,0.985646,0.985202,0.985913,0.985652,0.985459,0.000368,4,0.990191,0.990690,0.990403,0.990870,0.990700,0.990571,0.000242,4,0.991660,0.992250,0.991713,0.992104,0.991859,0.991917,0.000227,1,20.381792,0.190529,0.623133,0.064984
1,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,2,"{""classifier__colsample_bytree"": 0.7277015784306393, ""classifier__learning_rate"": 0.046066102129245355, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 234, ""classifier__subsample"": 0.9806617212418095}",0.958148,0.960191,0.959330,0.961501,0.960932,0.960020,0.001186,6,0.994055,0.994798,0.994161,0.994267,0.993524,0.994161,0.000408,1,0.975771,0.977188,0.976435,0.977610,0.976957,0.976792,0.000636,5,0.998500,0.998688,0.998527,0.998555,0.998367,0.998527,0.000103,2,0.989145,0.989689,0.989463,0.990047,0.989901,0.989649,0.000320,6,0.993800,0.994168,0.993975,0.994283,0.994116,0.994068,0.000167,5,0.984786,0.985678,0.985205,0.985946,0.985536,0.985430,0.000401,5,0.990127,0.990711,0.990403,0.990891,0.990626,0.990552,0.000264,5,0.991600,0.992244,0.991812,0.992157,0.991713,0.991905,0.000252,2,28.211579,0.711358,1.171348,0.279422
2,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,3,"{""classifier__colsample_bytree"": 0.9538932750058051, ""classifier__learning_rate"": 0.061715573864800456, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 239, ""classifier__subsample"": 0.833035868133867}",0.958566,0.960115,0.959797,0.961296,0.961066,0.960168,0.000978,4,0.993471,0.994108,0.993524,0.994055,0.993153,0.993662,0.000366,5,0.975706,0.976816,0.976369,0.977401,0.976846,0.976628,0.000565,6,0.998353,0.998514,0.998367,0.998501,0.998274,0.998402,0.000092,5,0.989264,0.989676,0.989596,0.989994,0.989941,0.989694,0.000263,4,0.993788,0.994075,0.993962,0.994229,0.994090,0.994029,0.000147,6,0.984747,0.985445,0.985166,0.985815,0.985468,0.985328,0.000356,6,0.990106,0.990562,0.990382,0.990806,0.990583,0.990488,0.000234,6,0.991368,0.991892,0.991560,0.992025,0.991547,0.991678,0.000242,5,26.185915,1.458770,0.864300,0.054087
0,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,1,"{""classifier__colsample_bytree"": 0.8251066014107722, ""classifier__learning_rate"": 0.1575599187428391, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 233, ""classifier__subsample"": 0.7440267672451338}",0.958348,0.959658,0.958990,0.960987,0.960335,0.959664,0.000937,7,0.991719,0.993736,0.991772,0.992409,0.990817,0.992091,0.000966,7,0.974748,0.976400,0.975106,0.976445,0.975338,0.975607,0.000692,7,0.997912,0.998420,0.997925,0.998087,0.997686,0.998006,0.000243,7,0.989225,0.989556,0.989397,0.989928,0.989769,0.989575,0.000252,7,0.993549,0.993968,0.993643,0.993991,0.993711,0.993773,0.000177,7,0.984149,0.985184,0.984374,0.985218,0.984525,0.984690,0.000434,7,0.989724,0.990392,0.989872,0.990424,0.989978,0.990078,0.000282,7,0.990472,0.991646,0.990585,0.991169,0.990293,0.990833,0.000502,7,17.756051,0.751643,0.626824,0.108691
9,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,10,"{""classifier__colsample_bytree"": 0.7895485884259134, ""classifier__learning_rate"": 0.08380226576125108, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 253, ""classifier__subsample"": 0.8343680578527715}",0.958139,0.959787,0.959012,0.960477,0.960329,0.959549,0.000872,8,0.992622,0.993259,0.991082,0.991985,0.990658,0.991921,0.000957,8,0.975076,0.976236,0.974783,0.975977,0.975258,0.975466,0.000550,8,0.998139,0.998300,0.997752,0.997980,0.997646,0.997963,0.000241,8,0.989158,0.989596,0.989410,0.989795,0.989769,0.989546,0.000238,8,0.993628,0.993929,0.993564,0.993871,0.993692,0.993737,0.000140,8,0.984352,0.985082,0.984173,0.984924,0.984475,0.984601,0.000345,8,0.989851,0.990329,0.989745,0.990233,0.989946,0.990021,0.000224,8,0.990890,0.991427,0.990246,0.990890,0.990213,0.990733,0.000456,8,18.859814,0.363563,0.679140,0.056884
11,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,12,"{""classifier__colsample_bytree"": 0.7250869013641078, ""classifier__learning_rate"": 0.24773227404307951, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 262, ""classifier__subsample"": 0.7896790336629148}",0.957902,0.959372,0.958654,0.960399,0.959994,0.959264,0.000901,9,0.991613,0.992728,0.991985,0.991242,0.989650,0.991443,0.001023,9,0.974466,0.975765,0.975035,0.975577,0.974596,0.975088,0.000516,9,0.997885,0.998166,0.997979,0.997793,0.997392,0.997843,0.000257,9,0.989105,0.989490,0.989304,0.989782,0.989689,0.989474,0.000247,9,0.993476,0.993809,0.993623,0.993771,0.993526,0.993641,0.000131,9,0.983971,0.984787,0.984329,0.984674,0.984061,0.984364,0.000323,9,0.989607,0.990138,0.989840,0.990074,0.989681,0.989868,0.000209,9,0.990359,0.991109,0.990644,0.990512,0.989669,0.990459,0.000468,9,12.593995,2.578226,0.376164,0.111970
5,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,6,"{""classifier__colsample_bytree"": 0.9595060755936949, ""classifier__learning_rate"": 0.20242687100180323, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 241, ""classifier__subsample"": 0.7819149922650241}",0.957765,0.959135,0.958998,0.960297,0.959454,0.959130,0.000818,10,0.990658,0.991719,0.989490,0.989861,0.988482,0.990042,0.001092,10,0.973933,0.975155,0.974005,0.974855,0.973752,0.974340,0.000557,10,0.997644,0.997912,0.997351,0.997446,0.997098,0.997490,0.000274,10,0.989079,0.989437,0.989424,0.989769,0.989556,0.989453,0.000224,10,0.993343,0.993656,0.993372,0.993592,0.993313,0.993455,0.000141,10,0.983638,0.984406,0.983689,0.984224,0.983532,0.983898,0.000349,10,0.989394,0.989893,0.989437,0.989787,0.989341,0.989571,0.000225,10,0.989868,0.990578,0.989457,0.989815,0.989019,0.989747,0.000515,10,14.810671,0.477645,0.566592,0.044441
7,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,8,"{""classifier__colsample_bytree"": 0.859949585491905, ""classifier__learning_rate"": 0.14757009901255264, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 143, ""classifier__subsample"": 0.905950278304475}",0.957699,0.958389,0.958187,0.959907,0.958901,0.958617,0.000751,11,0.989065,0.989065,0.987738,0.987473,0.985775,0.987823,0.001217,11,0.973130,0.973486,0.972738,0.973495,0.972152,0.973000,0.000507,11,0.997244,0.997244,0.996911,0.996846,0.996418,0.996933,0.000305,11,0.989079,0.989264,0.989225,0.989689,0.989437,0.989339,0.000209,11,0.993144,0.993238,0.993053,0.993254,0.992915,0.993121,0.000126,11,0.983137,0.983362,0.982896,0.983375,0.982534,0.983061,0.000316,11,0.989076,0.989225,0.988927,0.989246,0.988704,0.989036,0.000201,11,0.989072,0.989165,0.988481,0.988581,0.987606,0.988581,0.000555,11,10.332085,0.337809,0.382517,0.018128
8,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,9,"{""classifier__colsample_bytree"": 0.9503877015692118, ""classifier__learning_rate"": 0.03129028595344, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 115, ""classifier__subsample"": 0.8981907190714008}",0.952651,0.952941,0.945985,0.953686,0.952488,0.951550,0.002813,12,0.964382,0.963108,0.966824,0.966240,0.964066,0.964924,0.001391,12,0.958481,0.957998,0.956291,0.959922,0.958242,0.958187,0.001160,12,0.991068,0.990753,0.991660,0.991532,0.990989,0.991200,0.000342,12,0.988017,0.988110,0.986199,0.988269,0.987977,0.987714,0.000764,12,0.989540,0.989429,0.988922,0.989898,0.989481,0.989454,0.000313,12,0.974010,0.973714,0.972607,0.974910,0.973861,0.973820,0.000736,12,0.983290,0.983110,0.982324,0.983863,0.983195,0.983156,0.000493,12,0.976200,0.975609,0.976512,0.977255,0.976021,0.976319,0.000551,12,8.534993,0.282130,0.363281,0.024253

modelo: xgboost
 origem do treinamento: cicids2017_iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: xgboost - cicids2017_iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
6,xgboost,randomized_search,cicids2017_iot23,470980,12,5,1,7,"{""classifier__colsample_bytree"": 0.717772960390469, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9873668590451505}",0.988054,0.988360,0.988266,0.989171,0.989943,0.988759,0.000703,2,0.992250,0.991560,0.992516,0.994002,0.992675,0.992601,0.000798,5,0.990148,0.989957,0.990386,0.991581,0.991307,0.990676,0.000647,1,0.998060,0.997888,0.998127,0.998499,0.998167,0.998148,0.000199,5,0.997001,0.997081,0.997054,0.997280,0.997479,0.997179,0.000177,2,0.997530,0.997484,0.997590,0.997889,0.997823,0.997663,0.000162,1,0.993839,0.993721,0.993988,0.994735,0.994565,0.994170,0.000405,1,0.996051,0.995976,0.996146,0.996624,0.996518,0.996263,0.000259,1,0.994626,0.994320,0.994785,0.995641,0.995077,0.994890,0.000448,4,20.574379,0.340658,0.853779,0.037138
10,xgboost,randomized_search,cicids2017_iot23,470980,12,5,1,11,"{""classifier__colsample_bytree"": 0.9725786509279286, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 200, ""classifier__subsample"": 0.8574398130611336}",0.988474,0.987790,0.988838,0.988757,0.989469,0.988666,0.000545,4,0.992409,0.991985,0.992197,0.994320,0.992463,0.992675,0.000840,1,0.990438,0.989883,0.990515,0.991531,0.990964,0.990666,0.000552,2,0.998100,0.997994,0.998048,0.998578,0.998114,0.998167,0.000210,1,0.997107,0.996935,0.997200,0.997173,0.997359,0.997155,0.000138,4,0.997604,0.997464,0.997624,0.997875,0.997737,0.997661,0.000138,2,0.994021,0.993673,0.994069,0.994703,0.994350,0.994163,0.000345,2,0.996168,0.995945,0.996199,0.996603,0.996380,0.996259,0.000221,2,0.994758,0.994460,0.994699,0.995747,0.994911,0.994915,0.000441,1,18.430778,0.359794,0.651466,0.044357
3,xgboost,randomized_search,cicids2017_iot23,470980,12,5,1,4,"{""classifier__colsample_bytree"": 0.7688731641189476, ""classifier__learning_rate"": 0.10269165750001427, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 196, ""classifier__subsample"": 0.93351677090096}",0.987853,0.987887,0.988835,0.989124,0.989576,0.988655,0.000683,5,0.992834,0.991401,0.991985,0.994426,0.992675,0.992664,0.001019,2,0.990337,0.989641,0.990408,0.991768,0.991123,0.990655,0.000728,3,0.998206,0.997848,0.997995,0.998605,0.998167,0.998164,0.000255,2,0.996948,0.996961,0.997200,0.997266,0.997386,0.997152,0.000172,5,0.997577,0.997405,0.997597,0.997935,0.997776,0.997658,0.000182,3,0.993957,0.993523,0.994002,0.994852,0.994450,0.994157,0.000455,3,0.996125,0.995849,0.996157,0.996698,0.996444,0.996255,0.000291,3,0.994891,0.994181,0.994592,0.995846,0.995030,0.994908,0.000552,2,16.793955,0.476247,0.803038,0.096623
1,xgboost,randomized_search,cicids2017_iot23,470980,12,5,1,2,"{""classifier__colsample_bytree"": 0.7277015784306393, ""classifier__learning_rate"": 0.046066102129245355, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 234, ""classifier__subsample"": 0.9806617212418095}",0.988317,0.987786,0.988731,0.989019,0.989524,0.988675,0.000593,3,0.992409,0.991666,0.991985,0.994373,0.992728,0.992632,0.000943,3,0.990359,0.989722,0.990355,0.991689,0.991124,0.990650,0.000683,4,0.998100,0.997915,0.997995,0.998591,0.998180,0.998156,0.000236,3,0.997067,0.996935,0.997173,0.997240,0.997372,0.997158,0.000149,3,0.997584,0.997424,0.997584,0.997915,0.997776,0.997657,0.000171,4,0.993971,0.993573,0.993969,0.994802,0.994450,0.994153,0.000427,4,0.996136,0.995881,0.996136,0.996667,0.996444,0.996252,0.000273,4,0.994738,0.994300,0.994579,0.995807,0.995050,0.994895,0.000516,3,22.762357,1.291419,0.858958,0.043812
2,xgboost,randomized_search,cicids2017_iot23,470980,12,5,1,3,"{""classifier__colsample_bytree"": 0.9538932750058051, ""classifier__learning_rate"": 0.061715573864800456, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 239, ""classifier__subsample"": 0.833035868133867}",0.987801,0.987783,0.988837,0.988862,0.989729,0.988603,0.000736,7,0.992887,0.991401,0.992144,0.994373,0.992304,0.992622,0.000996,4,0.990338,0.989589,0.990488,0.991610,0.991015,0.990608,0.000678,5,0.998220,0.997848,0.998034,0.998591,0.998075,0.998154,0.000249,4,0.996935,0.996935,0.997200,0.997200,0.997426,0.997139,0.000186,7,0.997577,0.997391,0.997617,0.997895,0.997750,0.997646,0.000169,5,0.993957,0.993490,0.994052,0.994753,0.994382,0.994127,0.000424,5,0.996125,0.995828,0.996189,0.996635,0.996401,0.996236,0.000271,5,0.994911,0.994168,0.994672,0.995787,0.994865,0.994880,0.000524,5,20.618331,0.385147,0.823765,0.056864
9,xgboost,randomized_search,cicids2017_iot23,470980,12,5,1,10,"{""classifier__colsample_bytree"": 0.7895485884259134, ""classifier__learning_rate"": 0.08380226576125108, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 253, ""classifier__subsample"": 0.8343680578527715}",0.988423,0.987371,0.988525,0.988650,0.989466,0.988487,0.000669,8,0.992516,0.991879,0.992303,0.994055,0.992197,0.992590,0.000761,6,0.990465,0.989620,0.990411,0.991345,0.990830,0.990534,0.000566,6,0.998127,0.997967,0.998074,0.998512,0.998048,0.998146,0.000190,6,0.997094,0.996828,0.997120,0.997147,0.997359,0.997110,0.000169,8,0.997610,0.997398,0.997597,0.997829,0.997703,0.997627,0.000142,6,0.994038,0.993509,0.994004,0.994587,0.994267,0.994081,0.000354,6,0.996178,0.995838,0.996157,0.996529,0.996327,0.996206,0.000227,6,0.994805,0.994353,0.994712,0.995601,0.994778,0.994850,0.000409,6,18.201057,0.780050,0.715851,0.053138
4,xgboost,randomized_search,cicids2017_iot23,470980,12,5,1,5,"{""classifier__colsample_bytree"": 0.9147911547905092, ""classifier__learning_rate"": 0.19049288475798723, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 122, ""classifier__subsample"": 0.8554457646825666}",0.988206,0.988562,0.988728,0.989481,0.989885,0.988972,0.000618,1,0.991825,0.990976,0.991719,0.993630,0.992144,0.992059,0.000874,9,0.990012,0.989768,0.990221,0.991551,0.991013,0.990513,0.000666,7,0.997955,0.997743,0.997928,0.998406,0.998035,0.998013,0.000218,9,0.997041,0.997134,0.997173,0.997359,0.997465,0.997234,0.000155,1,0.997497,0.997438,0.997551,0.997882,0.997750,0.997624,0.000166,7,0.993755,0.993603,0.993886,0.994717,0.994382,0.994068,0.000416,7,0.995998,0.995902,0.996083,0.996613,0.996401,0.996199,0.000266,7,0.994433,0.994055,0.994446,0.995495,0.994805,0.994647,0.000486,8,11.448383,0.261773,0.626388,0.123570
0,xgboost,randomized_search,cicids2017_iot23,470980,12,5,1,1,"{""classifier__colsample_bytree"": 0.8251066014107722, ""classifier__learning_rate"": 0.1575599187428391, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 233, ""classifier__subsample"": 0.7440267672451338}",0.988370,0.987574,0.988677,0.988858,0.989674,0.988631,0.000682,6,0.992462,0.991401,0.991879,0.994002,0.992038,0.992356,0.000890,7,0.990412,0.989484,0.990275,0.991423,0.990855,0.990490,0.000643,8,0.998114,0.997848,0.997968,0.998499,0.998008,0.998087,0.000222,7,0.997081,0.996882,0.997160,0.997200,0.997412,0.997147,0.000172,6,0.997597,0.997365,0.997564,0.997849,0.997710,0.997617,0.000161,8,0.994004,0.993424,0.993920,0.994636,0.994283,0.994053,0.000402,8,0.996157,0.995785,0.996104,0.996560,0.996337,0.996189,0.000257,8,0.994772,0.994141,0.994519,0.995601,0.994725,0.994752,0.000479,7,15.020518,0.663619,0.565344,0.082336
11,xgboost,randomized_search,cicids2017_iot23,470980,12,5,1,12,"{""classifier__colsample_bytree"": 0.7250869013641078, ""classifier__learning_rate"": 0.24773227404307951, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 262, ""classifier__subsample"": 0.7896790336629148}",0.988050,0.987260,0.988312,0.988541,0.989465,0.988326,0.000715,10,0.991879,0.991348,0.991932,0.993683,0.992091,0.992187,0.000789,8,0.989961,0.989300,0.990118,0.991105,0.990777,0.990252,0.000635,9,0.997968,0.997835,0.997981,0.998419,0.998021,0.998045,0.000197,8,0.997001,0.996802,0.997067,0.997120,0.997359,0.997070,0.000180,10,0.997484,0.997318,0.997524,0.997769,0.997690,0.997557,0.000159,9,0.993722,0.993309,0.993821,0.994437,0.994233,0.993905,0.000397,9,0.995976,0.995711,0.996040,0.996433,0.996306,0.996093,0.000254,9,0.994440,0.994075,0.994499,0.995402,0.994725,0.994628,0.000440,9,12.054676,2.544288,0.324286,0.047371
5,xgboost,randomized_search,cicids2017_iot23,470980,12,5,1,6,"{""classifier__colsample_bytree"": 0.9595060755936949, ""classifier__learning_rate"": 0.20242687100180323, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 241, ""classifier__subsample"": 0.7819149922650241}",0.987942,0.987210,0.987948,0.988536,0.988781,0.988083,0.000546,11,0.991613,0.991507,0.992091,0.993206,0.991720,0.992027,0.000621,10,0.989774,0.989354,0.990015,0.990865,0.990248,0.990051,0.000503,10,0.997901,0.997874,0.998021,0.998299,0.997928,0.998005,0.000155,10,0.996974,0.996789,0.996974,0.997120,0.997187,0.997009,0.000138,11,0.997438,0.997331,0.997497,0.997710,0.997557,0.997507,0.000126,10,0.993606,0.993343,0.993756,0.994287,0.993903,0.993779,0.000315,10,0.995902,0.995732,0.995998,0.996337,0.996093,0.996013,0.000201,10,0.994294,0.994148,0.994533,0.995163,0.994453,0.994518,0.000349,10,13.453123,0.217359,0.524718,0.092888
7,xgboost,randomized_search,cicids2017_iot23,470980,12,5,1,8,"{""classifier__colsample_bytree"": 0.859949585491905, ""classifier__learning_rate"": 0.14757009901255264, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 143, ""classifier__subsample"": 0.905950278304475}",0.988606,0.987155,0.988153,0.988642,0.989094,0.988330,0.000659,9,0.990233,0.991295,0.991719,0.993418,0.991667,0.991666,0.001026,11,0.989419,0.989221,0.989933,0.991024,0.990379,0.989995,0.000655,11,0.997557,0.997821,0.997928,0.998353,0.997915,0.997915,0.000256,11,0.997147,0.996775,0.997027,0.997147,0.997266,0.997073,0.000167,9,0.997352,0.997298,0.997478,0.997749,0.997591,0.997494,0.000163,11,0.993386,0.993259,0.993705,0.994387,0.993985,0.993744,0.000409,11,0.995764,0.995679,0.995966,0.996401,0.996146,0.995991,0.000261,11,0.993690,0.994035,0.994373,0.995282,0.994466,0.994369,0.000532,11,9.523775,0.233619,0.408186,0.025689
8,xgboost,randomized_search,cicids2017_iot23,470980,12,5,1,9,"{""classifier__colsample_bytree"": 0.9503877015692118, ""classifier__learning_rate"": 0.03129028595344, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 115, ""classifier__subsample"": 0.8981907190714008}",0.986750,0.986594,0.987050,0.986783,0.987926,0.987021,0.000476,12,0.968523,0.964913,0.966930,0.966983,0.968471,0.967164,0.001320,12,0.977552,0.975633,0.976886,0.976783,0.978102,0.976991,0.000830,12,0.992167,0.991276,0.991775,0.991787,0.992156,0.991832,0.000326,12,0.996749,0.996722,0.996828,0.996762,0.997041,0.996820,0.000116,12,0.994453,0.993992,0.994295,0.994268,0.994592,0.994320,0.000201,12,0.986002,0.984813,0.985591,0.985526,0.986347,0.985656,0.000516,12,0.991104,0.990361,0.990849,0.990806,0.991327,0.990889,0.000324,12,0.982636,0.980818,0.981879,0.981873,0.982756,0.981992,0.000693,12,8.246445,0.237001,0.368672,0.044514

modelo: xgboost
 origem do treinamento: unsw_nb15_iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: xgboost - unsw_nb15_iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
6,xgboost,randomized_search,unsw_nb15_iot23,470980,12,5,1,7,"{""classifier__colsample_bytree"": 0.717772960390469, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9873668590451505}",0.971221,0.970011,0.971283,0.970960,0.972247,0.971144,0.000715,2,0.994214,0.994108,0.994639,0.995647,0.994798,0.994681,0.000547,8,0.982583,0.981912,0.982822,0.983149,0.983393,0.982772,0.000511,1,0.998545,0.998518,0.998652,0.998905,0.998692,0.998662,0.000137,8,0.992635,0.992317,0.992648,0.992555,0.992900,0.992611,0.000187,2,0.995581,0.995408,0.995641,0.995720,0.995788,0.995627,0.000130,1,0.989082,0.988660,0.989232,0.989434,0.989590,0.989200,0.000321,1,0.992951,0.992675,0.993046,0.993174,0.993280,0.993025,0.000208,1,0.993425,0.993212,0.993644,0.994101,0.993849,0.993646,0.000312,6,20.470226,0.502581,0.883066,0.049544
3,xgboost,randomized_search,unsw_nb15_iot23,470980,12,5,1,4,"{""classifier__colsample_bytree"": 0.7688731641189476, ""classifier__learning_rate"": 0.10269165750001427, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 196, ""classifier__subsample"": 0.93351677090096}",0.970770,0.969371,0.970745,0.970817,0.971516,0.970644,0.000698,3,0.994267,0.994533,0.995170,0.995913,0.995701,0.995117,0.000639,4,0.982378,0.981791,0.982806,0.983205,0.983460,0.982728,0.000595,2,0.998558,0.998624,0.998785,0.998972,0.998918,0.998771,0.000161,4,0.992516,0.992144,0.992502,0.992516,0.992701,0.992476,0.000182,3,0.995528,0.995374,0.995634,0.995733,0.995800,0.995614,0.000151,2,0.988953,0.988582,0.989220,0.989469,0.989630,0.989171,0.000373,2,0.992866,0.992622,0.993036,0.993195,0.993301,0.993004,0.000241,2,0.993391,0.993338,0.993836,0.994214,0.994201,0.993796,0.000378,4,16.392014,0.692461,0.725713,0.041721
1,xgboost,randomized_search,unsw_nb15_iot23,470980,12,5,1,2,"{""classifier__colsample_bytree"": 0.7277015784306393, ""classifier__learning_rate"": 0.046066102129245355, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 234, ""classifier__subsample"": 0.9806617212418095}",0.970287,0.969088,0.970188,0.970272,0.971368,0.970240,0.000722,7,0.994957,0.995117,0.995010,0.996178,0.995807,0.995414,0.000490,1,0.982467,0.981930,0.982442,0.983054,0.983436,0.982666,0.000524,3,0.998731,0.998771,0.998745,0.999038,0.998945,0.998846,0.000123,1,0.992383,0.992064,0.992356,0.992370,0.992662,0.992367,0.000189,7,0.995547,0.995406,0.995540,0.995693,0.995793,0.995596,0.000134,3,0.989007,0.988668,0.988991,0.989374,0.989614,0.989131,0.000329,3,0.992898,0.992675,0.992887,0.993131,0.993291,0.992976,0.000213,3,0.993670,0.993590,0.993683,0.994274,0.994234,0.993890,0.000299,1,21.650686,0.944854,1.089345,0.219425
10,xgboost,randomized_search,unsw_nb15_iot23,470980,12,5,1,11,"{""classifier__colsample_bytree"": 0.9725786509279286, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 200, ""classifier__subsample"": 0.8574398130611336}",0.970383,0.968934,0.970291,0.970270,0.971469,0.970269,0.000804,6,0.994798,0.995010,0.995117,0.996125,0.995807,0.995371,0.000506,2,0.982439,0.981799,0.982547,0.983028,0.983487,0.982660,0.000570,4,0.998691,0.998744,0.998771,0.999025,0.998945,0.998835,0.000127,2,0.992409,0.992025,0.992383,0.992370,0.992688,0.992375,0.000211,6,0.995540,0.995373,0.995567,0.995686,0.995807,0.995595,0.000146,4,0.988990,0.988586,0.989057,0.989357,0.989647,0.989127,0.000358,4,0.992887,0.992622,0.992930,0.993121,0.993312,0.992974,0.000232,4,0.993604,0.993517,0.993750,0.994247,0.994247,0.993873,0.000314,2,17.948193,0.198237,0.624972,0.017567
2,xgboost,randomized_search,unsw_nb15_iot23,470980,12,5,1,3,"{""classifier__colsample_bytree"": 0.9538932750058051, ""classifier__learning_rate"": 0.061715573864800456, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 239, ""classifier__subsample"": 0.833035868133867}",0.970533,0.969083,0.970328,0.970316,0.971517,0.970355,0.000775,4,0.994798,0.994957,0.994639,0.995966,0.995754,0.995223,0.000534,3,0.982516,0.981850,0.982333,0.982974,0.983486,0.982632,0.000559,5,0.998691,0.998731,0.998651,0.998985,0.998932,0.998798,0.000134,3,0.992449,0.992064,0.992396,0.992383,0.992701,0.992399,0.000203,4,0.995561,0.995386,0.995514,0.995673,0.995807,0.995588,0.000143,5,0.989038,0.988618,0.988923,0.989323,0.989647,0.989110,0.000351,5,0.992919,0.992643,0.992845,0.993099,0.993312,0.992964,0.000227,5,0.993624,0.993511,0.993517,0.994174,0.994228,0.993811,0.000322,3,20.559956,0.581354,0.835100,0.054834
9,xgboost,randomized_search,unsw_nb15_iot23,470980,12,5,1,10,"{""classifier__colsample_bytree"": 0.7895485884259134, ""classifier__learning_rate"": 0.08380226576125108, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 253, ""classifier__subsample"": 0.8343680578527715}",0.970325,0.968526,0.970527,0.970213,0.970912,0.970101,0.000823,9,0.994533,0.994745,0.994586,0.995860,0.995701,0.995085,0.000574,5,0.982280,0.981460,0.982409,0.982869,0.983150,0.982434,0.000579,6,0.998625,0.998677,0.998638,0.998958,0.998918,0.998763,0.000144,5,0.992396,0.991918,0.992449,0.992356,0.992542,0.992332,0.000216,9,0.995501,0.995286,0.995534,0.995646,0.995720,0.995537,0.000148,6,0.988890,0.988373,0.988972,0.989258,0.989435,0.988986,0.000363,6,0.992823,0.992484,0.992877,0.993057,0.993174,0.992883,0.000236,6,0.993464,0.993332,0.993517,0.994108,0.994121,0.993709,0.000337,5,17.577241,0.406818,0.715661,0.050034
4,xgboost,randomized_search,unsw_nb15_iot23,470980,12,5,1,5,"{""classifier__colsample_bytree"": 0.9147911547905092, ""classifier__learning_rate"": 0.19049288475798723, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 122, ""classifier__subsample"": 0.8554457646825666}",0.971245,0.970140,0.971408,0.971332,0.972717,0.971368,0.000818,1,0.993259,0.993365,0.993683,0.994586,0.993524,0.993683,0.000474,11,0.982128,0.981615,0.982419,0.982821,0.983011,0.982399,0.000498,7,0.998305,0.998331,0.998412,0.998638,0.998372,0.998412,0.000119,11,0.992648,0.992356,0.992688,0.992662,0.993033,0.992678,0.000215,1,0.995469,0.995335,0.995542,0.995641,0.995696,0.995536,0.000128,7,0.988798,0.988475,0.988981,0.989231,0.989353,0.988968,0.000313,7,0.992770,0.992558,0.992887,0.993046,0.993131,0.992879,0.000203,7,0.992953,0.992861,0.993186,0.993624,0.993279,0.993180,0.000268,10,11.572313,0.512928,0.641736,0.077182
11,xgboost,randomized_search,unsw_nb15_iot23,470980,12,5,1,12,"{""classifier__colsample_bytree"": 0.7250869013641078, ""classifier__learning_rate"": 0.24773227404307951, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 262, ""classifier__subsample"": 0.7896790336629148}",0.970226,0.968815,0.970568,0.970298,0.971504,0.970282,0.000864,5,0.994586,0.994373,0.994267,0.995329,0.995276,0.994766,0.000450,7,0.982255,0.981428,0.982275,0.982654,0.983246,0.982371,0.000593,8,0.998638,0.998584,0.998558,0.998825,0.998812,0.998683,0.000113,7,0.992370,0.991998,0.992463,0.992383,0.992701,0.992383,0.000226,5,0.995494,0.995280,0.995501,0.995593,0.995747,0.995523,0.000152,8,0.988874,0.988354,0.988888,0.989124,0.989497,0.988947,0.000373,8,0.992813,0.992473,0.992823,0.992972,0.993216,0.992860,0.000242,8,0.993478,0.993186,0.993365,0.993856,0.993989,0.993575,0.000302,8,11.901763,2.370510,0.333978,0.078545
0,xgboost,randomized_search,unsw_nb15_iot23,470980,12,5,1,1,"{""classifier__colsample_bytree"": 0.8251066014107722, ""classifier__learning_rate"": 0.1575599187428391, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 233, ""classifier__subsample"": 0.7440267672451338}",0.970268,0.968918,0.970363,0.970158,0.970817,0.970105,0.000634,8,0.994320,0.994480,0.994108,0.995700,0.995860,0.994894,0.000735,6,0.982147,0.981532,0.982092,0.982763,0.983179,0.982343,0.000572,9,0.998571,0.998611,0.998518,0.998918,0.998958,0.998715,0.000185,6,0.992383,0.992025,0.992409,0.992343,0.992516,0.992335,0.000165,8,0.995467,0.995307,0.995454,0.995620,0.995726,0.995515,0.000145,9,0.988807,0.988420,0.988773,0.989191,0.989453,0.988929,0.000358,9,0.992770,0.992516,0.992749,0.993015,0.993184,0.992847,0.000231,9,0.993352,0.993252,0.993259,0.994022,0.994188,0.993614,0.000405,7,16.166879,0.266071,0.587396,0.056781
5,xgboost,randomized_search,unsw_nb15_iot23,470980,12,5,1,6,"{""classifier__colsample_bytree"": 0.9595060755936949, ""classifier__learning_rate"": 0.20242687100180323, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 241, ""classifier__subsample"": 0.7819149922650241}",0.969708,0.968348,0.970357,0.970033,0.970998,0.969889,0.000881,11,0.994055,0.993843,0.993896,0.994851,0.995170,0.994363,0.000543,9,0.981730,0.980929,0.981985,0.982285,0.982935,0.981973,0.000659,10,0.998504,0.998450,0.998465,0.998705,0.998785,0.998582,0.000137,9,0.992237,0.991879,0.992409,0.992317,0.992569,0.992282,0.000230,11,0.995361,0.995154,0.995428,0.995500,0.995667,0.995422,0.000168,10,0.988546,0.988042,0.988706,0.988893,0.989301,0.988698,0.000414,10,0.992601,0.992271,0.992707,0.992823,0.993089,0.992698,0.000268,10,0.993146,0.992861,0.993153,0.993584,0.993869,0.993322,0.000358,9,13.698738,0.258183,0.528513,0.054828
7,xgboost,randomized_search,unsw_nb15_iot23,470980,12,5,1,8,"{""classifier__colsample_bytree"": 0.859949585491905, ""classifier__learning_rate"": 0.14757009901255264, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 143, ""classifier__subsample"": 0.905950278304475}",0.970285,0.968606,0.970244,0.969764,0.970916,0.969963,0.000771,10,0.993153,0.994108,0.993471,0.994267,0.994055,0.993811,0.000425,10,0.981585,0.981191,0.981720,0.981863,0.982349,0.981742,0.000377,11,0.998278,0.998517,0.998358,0.998558,0.998505,0.998443,0.000107,10,0.992396,0.991945,0.992383,0.992250,0.992555,0.992306,0.000205,10,0.995328,0.995220,0.995361,0.995394,0.995521,0.995365,0.000097,11,0.988457,0.988206,0.988541,0.988628,0.988935,0.988553,0.000237,11,0.992547,0.992378,0.992601,0.992654,0.992855,0.992607,0.000155,11,0.992774,0.993026,0.992927,0.993259,0.993305,0.993058,0.000200,11,9.556357,0.346199,0.429650,0.040981
8,xgboost,randomized_search,unsw_nb15_iot23,470980,12,5,1,9,"{""classifier__colsample_bytree"": 0.9503877015692118, ""classifier__learning_rate"": 0.03129028595344, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 115, ""classifier__subsample"": 0.8981907190714008}",0.967912,0.966205,0.967992,0.967119,0.968153,0.967476,0.000729,12,0.984713,0.981899,0.982430,0.983598,0.984289,0.983386,0.001072,12,0.976240,0.973989,0.975157,0.975289,0.976154,0.975366,0.000816,12,0.996162,0.995456,0.995591,0.995882,0.996056,0.995829,0.000268,12,0.991839,0.991414,0.991879,0.991640,0.991905,0.991735,0.000186,12,0.993995,0.993431,0.993731,0.993756,0.993976,0.993778,0.000205,12,0.985118,0.983710,0.984444,0.984523,0.985065,0.984572,0.000510,12,0.990414,0.989511,0.989989,0.990031,0.990382,0.990065,0.000327,12,0.988276,0.986657,0.987154,0.987619,0.988097,0.987561,0.000597,12,8.014498,0.335728,0.360599,0.019943

modelo: linear_svm
 origem do treinamento: cicids2017
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: linear_svm - cicids2017

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
1,linear_svm,randomized_search,cicids2017,235490,12,5,1,2,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced""}",0.758667,0.766255,0.761348,0.757855,0.758205,0.760466,0.003145,6,0.964221,0.967194,0.961465,0.960191,0.961359,0.962886,0.002528,1,0.849182,0.855078,0.849784,0.847108,0.847781,0.849787,0.002813,1,0.990406,0.991224,0.989688,0.989335,0.989646,0.990060,0.000680,1,0.923326,0.926245,0.924651,0.923297,0.923350,0.924174,0.001156,6,0.955690,0.957634,0.956065,0.955176,0.955349,0.955983,0.000880,1,0.902436,0.906356,0.902924,0.901142,0.901565,0.902885,0.001845,1,0.931505,0.934435,0.932014,0.930676,0.930952,0.931916,0.001341,1,0.943774,0.946720,0.943058,0.941744,0.942355,0.943530,0.001734,1,19.017824,4.938620,0.095080,0.002201
10,linear_svm,randomized_search,cicids2017,235490,12,5,1,11,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced""}",0.740859,0.746078,0.742448,0.740906,0.736150,0.741288,0.003194,7,0.957320,0.959231,0.957537,0.953503,0.956369,0.956792,0.001886,2,0.835294,0.839333,0.836386,0.833867,0.831933,0.835363,0.002483,2,0.988490,0.989025,0.988555,0.987477,0.988210,0.988351,0.000510,2,0.916293,0.918390,0.916954,0.916636,0.914300,0.916514,0.001317,7,0.951023,0.952399,0.951409,0.950738,0.949819,0.951078,0.000844,2,0.893159,0.895866,0.893897,0.892303,0.890876,0.893220,0.001661,2,0.924498,0.926557,0.925071,0.924010,0.922714,0.924570,0.001262,2,0.936807,0.938810,0.937246,0.935069,0.935335,0.936653,0.001362,2,12.352850,2.298007,0.068974,0.017118
5,linear_svm,randomized_search,cicids2017,235490,12,5,1,6,"{""classifier__C"": 2.23218499287176, ""classifier__class_weight"": ""balanced""}",0.740713,0.746078,0.742042,0.740906,0.736003,0.741148,0.003219,8,0.956896,0.959231,0.957643,0.953503,0.955945,0.956644,0.001903,3,0.835040,0.839333,0.836168,0.833867,0.831679,0.835217,0.002539,3,0.988377,0.989025,0.988581,0.987477,0.988096,0.988311,0.000515,3,0.916266,0.918390,0.916768,0.916636,0.914274,0.916467,0.001317,8,0.950956,0.952399,0.951321,0.950738,0.949753,0.951034,0.000858,3,0.892998,0.895866,0.893745,0.892303,0.890716,0.893125,0.001697,3,0.924392,0.926557,0.924944,0.924010,0.922608,0.924502,0.001285,3,0.936581,0.938810,0.937206,0.935069,0.935109,0.936555,0.001401,3,14.801666,5.252319,0.122449,0.026818
11,linear_svm,randomized_search,cicids2017,235490,12,5,1,12,"{""classifier__C"": 0.1932075262142986, ""classifier__class_weight"": ""balanced""}",0.737542,0.740348,0.738089,0.736760,0.730626,0.736673,0.003251,9,0.953817,0.956896,0.955520,0.951062,0.954777,0.954414,0.001955,5,0.831852,0.834808,0.832848,0.830306,0.827796,0.831522,0.002368,4,0.987542,0.988375,0.987995,0.986805,0.987754,0.987694,0.000524,5,0.915152,0.916107,0.915229,0.915043,0.911991,0.914704,0.001409,9,0.949970,0.950870,0.950221,0.949570,0.948362,0.949799,0.000833,4,0.890911,0.892839,0.891534,0.889938,0.888079,0.890660,0.001597,4,0.922884,0.924264,0.923288,0.922247,0.920549,0.922646,0.001237,4,0.934484,0.936501,0.935375,0.933052,0.933384,0.934559,0.001272,4,8.256934,2.311704,0.078945,0.013135
2,linear_svm,randomized_search,cicids2017,235490,12,5,1,3,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": ""balanced""}",0.737080,0.739016,0.737161,0.736968,0.729892,0.736023,0.003158,10,0.953923,0.955409,0.955414,0.951486,0.954671,0.954181,0.001456,7,0.831598,0.833395,0.832216,0.830600,0.827285,0.831019,0.002075,5,0.987567,0.987973,0.987962,0.986919,0.987722,0.987629,0.000386,7,0.914939,0.915656,0.914831,0.915096,0.911673,0.914439,0.001412,10,0.949867,0.950441,0.949991,0.949652,0.948175,0.949625,0.000770,5,0.890733,0.891918,0.891104,0.890126,0.887730,0.890322,0.001420,5,0.922736,0.923606,0.922948,0.922375,0.920273,0.922387,0.001131,5,0.934431,0.935533,0.935122,0.933291,0.933172,0.934310,0.000949,6,9.535025,4.288122,0.105672,0.015916
4,linear_svm,randomized_search,cicids2017,235490,12,5,1,5,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced""}",0.736343,0.738756,0.736782,0.736423,0.729633,0.735587,0.003104,12,0.955940,0.955622,0.955626,0.951486,0.954565,0.954648,0.001648,4,0.831894,0.833310,0.832055,0.830253,0.827079,0.830918,0.002152,6,0.988099,0.988028,0.988016,0.986916,0.987692,0.987750,0.000440,4,0.914435,0.915523,0.914645,0.914857,0.911566,0.914205,0.001369,12,0.949841,0.950395,0.949916,0.949521,0.948104,0.949555,0.000778,6,0.890867,0.891852,0.890985,0.889887,0.887591,0.890237,0.001462,6,0.922736,0.923542,0.922842,0.922184,0.920166,0.922294,0.001148,6,0.935188,0.935572,0.935136,0.933172,0.933066,0.934427,0.001079,5,3.814183,0.169662,0.096519,0.007051
3,linear_svm,randomized_search,cicids2017,235490,12,5,1,4,"{""classifier__C"": 0.015151125123102896, ""classifier__class_weight"": ""balanced""}",0.736393,0.738652,0.737083,0.736544,0.729914,0.735717,0.003010,11,0.953817,0.955409,0.955626,0.951486,0.954777,0.954223,0.001506,6,0.831121,0.833164,0.832247,0.830330,0.827339,0.830840,0.001999,7,0.987535,0.987971,0.988018,0.986916,0.987750,0.987638,0.000400,6,0.914647,0.915497,0.914778,0.914911,0.911673,0.914301,0.001346,11,0.949695,0.950354,0.949988,0.949550,0.948188,0.949555,0.000737,7,0.890408,0.891759,0.891118,0.889940,0.887763,0.890198,0.001365,7,0.922481,0.923479,0.922948,0.922226,0.920294,0.922285,0.001084,7,0.934232,0.935453,0.935202,0.933198,0.933225,0.934262,0.000950,7,5.671133,2.114070,0.110890,0.012663
6,linear_svm,randomized_search,cicids2017,235490,12,5,1,7,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null}",0.827674,0.834349,0.825212,0.830479,0.820879,0.827719,0.004575,1,0.551226,0.552394,0.557325,0.550743,0.549257,0.552189,0.002758,8,0.661738,0.664708,0.665315,0.662284,0.658144,0.662438,0.002545,8,0.896461,0.896823,0.897634,0.896404,0.895919,0.896648,0.000571,8,0.971310,0.972584,0.970487,0.971893,0.970036,0.971262,0.000922,1,0.932386,0.933169,0.932640,0.932624,0.931505,0.932465,0.000544,8,0.797062,0.798938,0.798977,0.797454,0.794825,0.797451,0.001523,8,0.887299,0.888552,0.887851,0.887660,0.885876,0.887447,0.000885,8,0.761268,0.762489,0.763906,0.761318,0.759646,0.761726,0.001417,8,13.090420,5.855220,0.141340,0.075002
0,linear_svm,randomized_search,cicids2017,235490,12,5,1,1,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null}",0.826482,0.834805,0.824603,0.828987,0.820273,0.827030,0.004819,2,0.550695,0.552076,0.556476,0.550106,0.548938,0.551658,0.002612,9,0.660975,0.664622,0.664512,0.661349,0.657721,0.661836,0.002563,9,0.896330,0.896768,0.897450,0.896247,0.895843,0.896527,0.000547,9,0.971098,0.972690,0.970407,0.971628,0.969929,0.971151,0.000964,2,0.932217,0.933187,0.932504,0.932416,0.931415,0.932348,0.000569,9,0.796596,0.798905,0.798508,0.796883,0.794568,0.797092,0.001546,9,0.887023,0.888573,0.887617,0.887320,0.885728,0.887252,0.000923,9,0.760897,0.762383,0.763441,0.760867,0.759434,0.761404,0.001381,9,8.132361,2.637161,0.102928,0.012133
9,linear_svm,randomized_search,cicids2017,235490,12,5,1,10,"{""classifier__C"": 0.014056787147388339, ""classifier__class_weight"": null}",0.826059,0.833976,0.823059,0.828590,0.820244,0.826386,0.004719,5,0.550589,0.551439,0.557006,0.550106,0.548832,0.551595,0.002834,10,0.660763,0.663897,0.664387,0.661222,0.657635,0.661581,0.002433,10,0.896301,0.896623,0.897527,0.896239,0.895821,0.896502,0.000573,10,0.971018,0.972558,0.970062,0.971548,0.969929,0.971023,0.000975,5,0.932165,0.933048,0.932386,0.932376,0.931403,0.932276,0.000528,10,0.796464,0.798473,0.798387,0.796799,0.794519,0.796928,0.001452,10,0.886938,0.888339,0.887447,0.887256,0.885706,0.887137,0.000853,10,0.760804,0.761998,0.763534,0.760827,0.759381,0.761309,0.001388,10,3.977561,0.413012,0.101767,0.006384
8,linear_svm,randomized_search,cicids2017,235490,12,5,1,9,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null}",0.825900,0.834029,0.823520,0.828430,0.820086,0.826393,0.004706,4,0.550483,0.551651,0.556794,0.550000,0.548726,0.551531,0.002794,11,0.660636,0.664068,0.664387,0.661095,0.657508,0.661539,0.002521,11,0.896276,0.896667,0.897493,0.896215,0.895796,0.896490,0.000573,11,0.970992,0.972558,0.970168,0.971522,0.969903,0.971028,0.000958,4,0.932139,0.933072,0.932417,0.932350,0.931378,0.932271,0.000545,12,0.796388,0.798570,0.798402,0.796722,0.794443,0.796905,0.001508,11,0.886895,0.888382,0.887490,0.887214,0.885664,0.887129,0.000884,12,0.760737,0.762104,0.763481,0.760761,0.759314,0.761280,0.001411,11,3.887684,0.174895,0.123125,0.014986
7,linear_svm,randomized_search,cicids2017,235490,12,5,1,8,"{""classifier__C"": 0.03684406880492199, ""classifier__class_weight"": null}",0.826191,0.834431,0.822662,0.829120,0.819927,0.826466,0.005055,3,0.550589,0.551651,0.556476,0.550106,0.548620,0.551488,0.002678,12,0.660805,0.664195,0.663880,0.661391,0.657381,0.661531,0.002465,12,0.896303,0.896675,0.897412,0.896250,0.895772,0.896482,0.000546,12,0.971045,0.972637,0.970009,0.971655,0.969876,0.971044,0.001034,3,0.932178,0.933113,0.932299,0.932430,0.931352,0.932275,0.000563,11,0.796492,0.798654,0.798090,0.796911,0.794367,0.796903,0.001488,12,0.886959,0.888445,0.887299,0.887341,0.885621,0.887133,0.000906,11,0.760817,0.762144,0.763242,0.760880,0.759248,0.761266,0.001349,12,4.731595,0.497770,0.105661,0.006384

modelo: linear_svm
 origem do treinamento: unsw_nb15
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: linear_svm - unsw_nb15

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
6,linear_svm,randomized_search,unsw_nb15,235490,12,5,1,7,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null}",0.938383,0.938623,0.935919,0.938254,0.936646,0.937565,0.001079,1,0.824610,0.826415,0.832590,0.833970,0.822399,0.827997,0.004519,8,0.877825,0.878952,0.881236,0.883044,0.875813,0.879374,0.002538,1,0.957446,0.957866,0.959270,0.959613,0.956911,0.958221,0.001047,8,0.986465,0.986491,0.985748,0.986278,0.986093,0.986215,0.000274,2,0.971739,0.971968,0.972328,0.972763,0.971283,0.972016,0.000504,1,0.924782,0.925460,0.926782,0.927903,0.923548,0.925695,0.001520,1,0.954096,0.954478,0.955115,0.955816,0.953353,0.954571,0.000844,1,0.905537,0.906453,0.909169,0.910124,0.904246,0.907106,0.002211,5,12.850188,3.152866,0.110504,0.012721
1,linear_svm,randomized_search,unsw_nb15,235490,12,5,1,2,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced""}",0.856917,0.855124,0.936190,0.937248,0.856011,0.888298,0.039541,5,0.862193,0.861026,0.867516,0.862527,0.860191,0.862691,0.002553,3,0.859547,0.858065,0.900545,0.898336,0.858096,0.874918,0.020042,2,0.965498,0.965199,0.967474,0.966301,0.965003,0.965895,0.000905,1,0.964012,0.963534,0.985217,0.985562,0.963825,0.972430,0.010583,6,0.964754,0.964366,0.976265,0.975837,0.964414,0.969127,0.005656,3,0.912151,0.911215,0.938405,0.937086,0.911255,0.922022,0.012849,2,0.943649,0.943034,0.961676,0.960954,0.943097,0.950482,0.008850,3,0.913103,0.912280,0.926366,0.924044,0.912008,0.917560,0.006296,1,9.178674,1.222208,0.112896,0.010248
0,linear_svm,randomized_search,unsw_nb15,235490,12,5,1,1,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null}",0.937269,0.937738,0.934542,0.937151,0.935146,0.936369,0.001275,2,0.809003,0.810702,0.815393,0.819958,0.806688,0.812349,0.004756,9,0.868426,0.869605,0.870911,0.874646,0.866180,0.869954,0.002815,3,0.953834,0.954229,0.955271,0.956352,0.953274,0.954592,0.001096,9,0.986465,0.986544,0.985721,0.986252,0.986013,0.986199,0.000302,3,0.969875,0.970118,0.970257,0.971072,0.969367,0.970138,0.000557,2,0.919150,0.919861,0.920584,0.922859,0.917774,0.920046,0.001685,3,0.950975,0.951378,0.951654,0.952992,0.950147,0.951429,0.000932,2,0.897734,0.898623,0.900557,0.903105,0.896350,0.899274,0.002352,8,15.311976,6.516835,0.111839,0.012412
5,linear_svm,randomized_search,unsw_nb15,235490,12,5,1,6,"{""classifier__C"": 2.23218499287176, ""classifier__class_weight"": ""balanced""}",0.856390,0.854674,0.858779,0.937248,0.855649,0.872548,0.032378,7,0.862300,0.861026,0.867622,0.862527,0.860191,0.862733,0.002589,1,0.859334,0.857838,0.863178,0.898336,0.857914,0.867320,0.015629,4,0.965518,0.965195,0.966818,0.966301,0.964999,0.965766,0.000688,2,0.963853,0.963401,0.964329,0.985562,0.963719,0.968173,0.008700,7,0.964685,0.964297,0.965572,0.975837,0.964359,0.966950,0.004467,5,0.912010,0.911068,0.914375,0.937086,0.911136,0.917135,0.010047,4,0.943543,0.942928,0.944987,0.960954,0.943012,0.947085,0.006974,4,0.913076,0.912213,0.915976,0.924044,0.911955,0.915453,0.004527,2,9.917882,2.759458,0.117736,0.021944
10,linear_svm,randomized_search,unsw_nb15,235490,12,5,1,11,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced""}",0.856570,0.854584,0.856798,0.937248,0.855649,0.872170,0.032548,8,0.862300,0.861026,0.867622,0.862527,0.860191,0.862733,0.002589,1,0.859425,0.857793,0.862176,0.898336,0.857914,0.867129,0.015683,5,0.965520,0.965194,0.966799,0.966301,0.964999,0.965763,0.000683,3,0.963906,0.963375,0.963745,0.985562,0.963719,0.968061,0.008752,8,0.964712,0.964283,0.965270,0.975837,0.964359,0.966892,0.004486,6,0.912069,0.911038,0.913723,0.937086,0.911136,0.917011,0.010084,5,0.943586,0.942906,0.944520,0.960954,0.943012,0.946996,0.007002,5,0.913103,0.912200,0.915684,0.924044,0.911955,0.915397,0.004521,3,9.420176,1.786315,0.084161,0.010399
7,linear_svm,randomized_search,unsw_nb15,235490,12,5,1,8,"{""classifier__C"": 0.03684406880492199, ""classifier__class_weight"": null}",0.935488,0.935939,0.933367,0.935347,0.933503,0.934729,0.001075,3,0.783629,0.787982,0.788110,0.795541,0.780892,0.787231,0.004971,10,0.852851,0.855611,0.854610,0.859798,0.850405,0.854655,0.003120,6,0.948021,0.949015,0.949009,0.950724,0.947371,0.948828,0.001135,10,0.986491,0.986518,0.985933,0.986252,0.986093,0.986257,0.000226,1,0.966873,0.967403,0.967119,0.968162,0.966344,0.967180,0.000602,4,0.909862,0.911507,0.910865,0.913980,0.908374,0.910918,0.001861,6,0.945921,0.946813,0.946367,0.948108,0.945051,0.946452,0.001012,6,0.885060,0.887250,0.887022,0.890897,0.883492,0.886744,0.002489,10,10.133346,2.985156,0.106638,0.006580
11,linear_svm,randomized_search,unsw_nb15,235490,12,5,1,12,"{""classifier__C"": 0.1932075262142986, ""classifier__class_weight"": ""balanced""}",0.821859,0.821965,0.818127,0.933663,0.820820,0.843287,0.045209,9,0.860601,0.859752,0.866242,0.862102,0.858811,0.861501,0.002606,4,0.840784,0.840434,0.841497,0.896457,0.839386,0.851712,0.022383,7,0.964737,0.964533,0.966060,0.966172,0.964288,0.965158,0.000796,4,0.953369,0.953449,0.951855,0.984686,0.953129,0.959298,0.012707,9,0.959020,0.958959,0.958905,0.975341,0.958676,0.962180,0.006582,7,0.899902,0.899696,0.900201,0.935899,0.899031,0.906946,0.014482,7,0.934817,0.934711,0.934732,0.960168,0.934265,0.939738,0.010217,7,0.906985,0.906600,0.909049,0.923394,0.905970,0.910400,0.006579,4,8.948328,1.676336,0.068442,0.019700
2,linear_svm,randomized_search,unsw_nb15,235490,12,5,1,3,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": ""balanced""}",0.819990,0.820620,0.816768,0.818292,0.818879,0.818910,0.001346,10,0.853594,0.850940,0.858386,0.857643,0.850000,0.854113,0.003405,5,0.836454,0.835505,0.837060,0.837506,0.834149,0.836135,0.001198,8,0.963023,0.962391,0.964138,0.963976,0.962138,0.963133,0.000809,5,0.953157,0.953502,0.951855,0.952386,0.952996,0.952779,0.000587,10,0.958064,0.957926,0.957957,0.958146,0.957546,0.957928,0.000206,10,0.897259,0.896715,0.897509,0.897826,0.895847,0.897031,0.000695,8,0.933246,0.932991,0.933161,0.933437,0.932396,0.933046,0.000355,9,0.903375,0.902221,0.905121,0.905015,0.901498,0.903446,0.001454,6,8.778378,2.551731,0.134789,0.047281
3,linear_svm,randomized_search,unsw_nb15,235490,12,5,1,4,"{""classifier__C"": 0.015151125123102896, ""classifier__class_weight"": ""balanced""}",0.818191,0.819444,0.815605,0.816538,0.817295,0.817415,0.001325,11,0.848073,0.845631,0.852229,0.853291,0.844798,0.848805,0.003421,6,0.832864,0.832332,0.833515,0.834510,0.830819,0.832808,0.001231,9,0.961671,0.961100,0.962636,0.962903,0.960868,0.961836,0.000810,6,0.952892,0.953422,0.951829,0.952068,0.952784,0.952599,0.000579,11,0.957261,0.957246,0.957202,0.957455,0.956809,0.957195,0.000211,11,0.895063,0.894789,0.895358,0.895982,0.893814,0.895001,0.000714,9,0.931929,0.931865,0.931908,0.932311,0.931186,0.931840,0.000364,10,0.900482,0.899527,0.902029,0.902679,0.898791,0.900702,0.001466,7,6.997835,3.059105,0.115518,0.025393
4,linear_svm,randomized_search,unsw_nb15,235490,12,5,1,5,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced""}",0.817034,0.818829,0.814143,0.814943,0.816179,0.816226,0.001638,12,0.845313,0.843083,0.848195,0.847558,0.841826,0.845195,0.002466,7,0.830933,0.830779,0.830820,0.830931,0.828804,0.830454,0.000827,10,0.960994,0.960481,0.961646,0.961502,0.960141,0.960953,0.000577,7,0.952679,0.953369,0.951590,0.951882,0.952598,0.952424,0.000629,12,0.956818,0.956912,0.956591,0.956668,0.956355,0.956669,0.000193,12,0.893876,0.893845,0.893706,0.893799,0.892580,0.893561,0.000494,10,0.931207,0.931313,0.930910,0.931016,0.930443,0.930978,0.000302,12,0.898996,0.898226,0.899893,0.899720,0.897212,0.898809,0.000993,9,5.281780,0.881192,0.107380,0.008438
9,linear_svm,randomized_search,unsw_nb15,235490,12,5,1,10,"{""classifier__C"": 0.014056787147388339, ""classifier__class_weight"": null}",0.889055,0.891553,0.885426,0.890002,0.886062,0.888419,0.002334,4,0.759741,0.761970,0.762951,0.773036,0.757856,0.763111,0.005269,11,0.819327,0.821684,0.819638,0.827406,0.816959,0.821003,0.003535,11,0.942047,0.942583,0.942716,0.945061,0.941574,0.942796,0.001203,11,0.976300,0.976831,0.975317,0.976113,0.975636,0.976039,0.000526,4,0.958868,0.959402,0.958739,0.960336,0.958302,0.959129,0.000698,8,0.889097,0.890543,0.889189,0.893871,0.887631,0.890066,0.002114,11,0.932991,0.933861,0.932842,0.935496,0.932078,0.933454,0.001168,8,0.868020,0.869401,0.869134,0.874575,0.866746,0.869575,0.002670,11,5.758856,0.570247,0.106072,0.011008
8,linear_svm,randomized_search,unsw_nb15,235490,12,5,1,9,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null}",0.887941,0.889972,0.884213,0.888218,0.883234,0.886716,0.002559,6,0.751247,0.755707,0.753928,0.765074,0.751592,0.755510,0.005050,12,0.813895,0.817362,0.813890,0.822060,0.812113,0.815864,0.003535,12,0.940121,0.941151,0.940665,0.943233,0.940126,0.941059,0.001152,12,0.976300,0.976645,0.975317,0.975928,0.975158,0.975869,0.000566,5,0.957869,0.958569,0.957677,0.959302,0.957322,0.958148,0.000706,9,0.885882,0.887966,0.885783,0.890681,0.884717,0.887006,0.002118,12,0.931292,0.932460,0.931037,0.933755,0.930443,0.931798,0.001178,11,0.863774,0.866176,0.864622,0.870501,0.863375,0.865690,0.002590,12,4.987503,0.325154,0.108991,0.011194

modelo: linear_svm
 origem do treinamento: iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: linear_svm - iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
6,linear_svm,randomized_search,iot23,235490,12,5,1,7,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null}",0.995419,0.993605,0.995407,0.996479,0.995737,0.995329,0.000946,1,0.992037,0.989702,0.989384,0.991401,0.991826,0.990870,0.001107,11,0.993725,0.991649,0.992387,0.993934,0.993778,0.993095,0.000912,1,0.998011,0.997428,0.997350,0.997853,0.997958,0.997720,0.000276,11,0.998859,0.998408,0.998859,0.999124,0.998938,0.998838,0.000236,1,0.998435,0.997918,0.998104,0.998488,0.998448,0.998278,0.000227,1,0.996080,0.994784,0.995245,0.996211,0.996113,0.995687,0.000570,1,0.997495,0.996667,0.996964,0.997580,0.997516,0.997244,0.000364,1,0.995448,0.994055,0.994122,0.995263,0.995382,0.994854,0.000628,1,7.687804,2.961192,0.110612,0.009903
0,linear_svm,randomized_search,iot23,235490,12,5,1,1,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null}",0.996056,0.993604,0.995195,0.996904,0.994465,0.995245,0.001159,2,0.992037,0.989595,0.989384,0.991295,0.991826,0.990828,0.001121,12,0.994043,0.991596,0.992281,0.994092,0.993144,0.993031,0.000978,2,0.998012,0.997402,0.997350,0.997827,0.997958,0.997709,0.000280,12,0.999018,0.998408,0.998806,0.999230,0.998620,0.998816,0.000289,2,0.998515,0.997904,0.998077,0.998528,0.998289,0.998263,0.000244,2,0.996279,0.994750,0.995179,0.996310,0.995716,0.995647,0.000611,2,0.997622,0.996645,0.996921,0.997643,0.997261,0.997219,0.000390,2,0.995528,0.994002,0.994095,0.995263,0.995223,0.994822,0.000641,3,7.387395,2.341363,0.123266,0.017908
7,linear_svm,randomized_search,iot23,235490,12,5,1,8,"{""classifier__C"": 0.03684406880492199, ""classifier__class_weight"": null}",0.996693,0.993605,0.993075,0.995310,0.995313,0.994799,0.001305,3,0.992037,0.989808,0.989490,0.991295,0.991826,0.990891,0.001048,10,0.994360,0.991703,0.991279,0.993299,0.993566,0.992841,0.001164,3,0.998012,0.997455,0.997375,0.997826,0.997958,0.997725,0.000262,10,0.999177,0.998408,0.998275,0.998832,0.998832,0.998705,0.000325,3,0.998594,0.997931,0.997825,0.998329,0.998395,0.998215,0.000291,3,0.996477,0.994817,0.994552,0.995814,0.995981,0.995528,0.000727,3,0.997749,0.996688,0.996518,0.997325,0.997431,0.997142,0.000465,3,0.995607,0.994108,0.993883,0.995064,0.995329,0.994798,0.000681,4,4.758528,0.651095,0.116590,0.010971
9,linear_svm,randomized_search,iot23,235490,12,5,1,10,"{""classifier__C"": 0.014056787147388339, ""classifier__class_weight"": null}",0.996162,0.994136,0.993500,0.994463,0.994571,0.994566,0.000881,4,0.992144,0.989914,0.989809,0.991401,0.991826,0.991019,0.000974,9,0.994149,0.992020,0.991651,0.992930,0.993197,0.992789,0.000886,4,0.998038,0.997481,0.997454,0.997852,0.997958,0.997757,0.000243,9,0.999045,0.998540,0.998381,0.998620,0.998646,0.998646,0.000220,4,0.998541,0.998011,0.997918,0.998236,0.998302,0.998201,0.000221,4,0.996345,0.995015,0.994784,0.995583,0.995749,0.995495,0.000553,4,0.997664,0.996815,0.996667,0.997176,0.997282,0.997121,0.000353,4,0.995594,0.994227,0.994095,0.995011,0.995236,0.994833,0.000581,2,4.411553,0.411887,0.105866,0.004126
8,linear_svm,randomized_search,iot23,235490,12,5,1,9,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null}",0.994043,0.993818,0.993184,0.994145,0.994466,0.993931,0.000428,5,0.992144,0.989914,0.989915,0.991401,0.991932,0.991061,0.000967,8,0.993092,0.991862,0.991547,0.992771,0.993197,0.992494,0.000667,5,0.998037,0.997481,0.997481,0.997852,0.997984,0.997767,0.000241,8,0.998514,0.998461,0.998301,0.998540,0.998620,0.998487,0.000106,5,0.998275,0.997971,0.997891,0.998196,0.998302,0.998127,0.000166,5,0.995684,0.994916,0.994719,0.995484,0.995750,0.995310,0.000417,5,0.997240,0.996751,0.996624,0.997112,0.997282,0.997002,0.000266,5,0.995329,0.994187,0.994108,0.994971,0.995276,0.994774,0.000526,5,4.199397,0.441917,0.103139,0.004808
5,linear_svm,randomized_search,iot23,235490,12,5,1,6,"{""classifier__C"": 2.23218499287176, ""classifier__class_weight"": ""balanced""}",0.988477,0.990025,0.992339,0.992563,0.991407,0.990962,0.001531,6,0.992674,0.990551,0.990021,0.991826,0.992038,0.991422,0.000983,6,0.990571,0.990288,0.991179,0.992195,0.991722,0.991191,0.000706,6,0.998167,0.997638,0.997507,0.997957,0.998009,0.997855,0.000245,6,0.997107,0.997505,0.998089,0.998142,0.997850,0.997739,0.000388,6,0.997637,0.997571,0.997798,0.998049,0.997930,0.997797,0.000178,6,0.994104,0.993930,0.994488,0.995122,0.994826,0.994494,0.000442,6,0.996221,0.996114,0.996475,0.996879,0.996688,0.996475,0.000284,6,0.994891,0.994028,0.994055,0.994984,0.994944,0.994580,0.000441,7,11.410335,5.493560,0.101328,0.011177
1,linear_svm,randomized_search,iot23,235490,12,5,1,2,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced""}",0.988477,0.990236,0.992023,0.992458,0.991302,0.990899,0.001426,8,0.992674,0.990551,0.990127,0.991826,0.992038,0.991443,0.000953,4,0.990571,0.990393,0.991074,0.992142,0.991670,0.991170,0.000658,7,0.998167,0.997638,0.997533,0.997957,0.998009,0.997861,0.000238,4,0.997107,0.997558,0.998009,0.998116,0.997824,0.997723,0.000361,8,0.997637,0.997598,0.997771,0.998036,0.997916,0.997792,0.000166,8,0.994104,0.993996,0.994423,0.995089,0.994793,0.994481,0.000412,7,0.996221,0.996157,0.996433,0.996858,0.996667,0.996467,0.000265,7,0.994891,0.994055,0.994068,0.994971,0.994931,0.994583,0.000427,6,13.869192,3.633529,0.121628,0.018527
10,linear_svm,randomized_search,iot23,235490,12,5,1,11,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced""}",0.988477,0.990236,0.992233,0.992247,0.991407,0.990920,0.001426,7,0.992674,0.990551,0.990021,0.991826,0.992038,0.991422,0.000983,6,0.990571,0.990393,0.991126,0.992037,0.991722,0.991170,0.000636,8,0.998167,0.997638,0.997507,0.997957,0.998009,0.997855,0.000245,7,0.997107,0.997558,0.998063,0.998063,0.997850,0.997728,0.000361,7,0.997637,0.997598,0.997784,0.998010,0.997930,0.997792,0.000160,7,0.994104,0.993996,0.994455,0.995023,0.994826,0.994481,0.000398,8,0.996221,0.996157,0.996454,0.996815,0.996688,0.996467,0.000256,7,0.994891,0.994055,0.994042,0.994944,0.994944,0.994575,0.000431,8,8.316531,2.043060,0.075574,0.025301
11,linear_svm,randomized_search,iot23,235490,12,5,1,12,"{""classifier__C"": 0.1932075262142986, ""classifier__class_weight"": ""balanced""}",0.988163,0.989710,0.989812,0.991722,0.991406,0.990163,0.001288,9,0.992674,0.990551,0.990127,0.991932,0.991932,0.991443,0.000951,5,0.990414,0.990131,0.989970,0.991827,0.991669,0.990802,0.000787,9,0.998167,0.997637,0.997532,0.997983,0.997983,0.997860,0.000237,5,0.997028,0.997426,0.997452,0.997930,0.997850,0.997537,0.000326,9,0.997597,0.997532,0.997492,0.997956,0.997916,0.997699,0.000197,9,0.994005,0.993831,0.993731,0.994892,0.994793,0.994250,0.000492,9,0.996157,0.996051,0.995987,0.996730,0.996667,0.996318,0.000316,9,0.994851,0.993988,0.993790,0.994931,0.994891,0.994490,0.000496,9,6.306138,0.993167,0.090597,0.026212
4,linear_svm,randomized_search,iot23,235490,12,5,1,5,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced""}",0.989104,0.989081,0.988448,0.990569,0.989415,0.989323,0.000697,10,0.992674,0.990551,0.990127,0.992357,0.992251,0.991592,0.001041,1,0.990886,0.989815,0.989287,0.991462,0.990831,0.990456,0.000789,10,0.998167,0.997637,0.997531,0.998088,0.998061,0.997897,0.000260,1,0.997266,0.997266,0.997107,0.997638,0.997346,0.997325,0.000175,10,0.997717,0.997452,0.997319,0.997863,0.997703,0.997611,0.000197,10,0.994301,0.993634,0.993303,0.994663,0.994267,0.994033,0.000493,10,0.996348,0.995923,0.995711,0.996582,0.996327,0.996178,0.000315,10,0.994970,0.993909,0.993617,0.994997,0.994798,0.994458,0.000579,10,4.352498,0.872860,0.107518,0.006544
2,linear_svm,randomized_search,iot23,235490,12,5,1,3,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": ""balanced""}",0.987850,0.989186,0.989497,0.989832,0.989099,0.989093,0.000673,11,0.992674,0.990551,0.990127,0.992038,0.992144,0.991507,0.000987,3,0.990256,0.989868,0.989812,0.990934,0.990620,0.990298,0.000431,11,0.998167,0.997637,0.997531,0.998008,0.998034,0.997876,0.000246,3,0.996948,0.997293,0.997372,0.997452,0.997266,0.997266,0.000172,11,0.997557,0.997465,0.997452,0.997730,0.997650,0.997571,0.000107,11,0.993907,0.993666,0.993632,0.994332,0.994135,0.993934,0.000269,11,0.996093,0.995945,0.995923,0.996369,0.996242,0.996114,0.000171,11,0.994811,0.993922,0.993750,0.994745,0.994705,0.994387,0.000454,12,6.740933,2.085439,0.116668,0.029514
3,linear_svm,randomized_search,iot23,235490,12,5,1,4,"{""classifier__C"": 0.015151125123102896, ""classifier__class_weight"": ""balanced""}",0.987746,0.989081,0.988345,0.990673,0.988995,0.988968,0.000980,12,0.992674,0.990551,0.990234,0.992251,0.992144,0.991571,0.000984,2,0.990204,0.989815,0.989288,0.991461,0.990567,0.990267,0.000732,12,0.998166,0.997637,0.997557,0.998062,0.998034,0.997891,0.000246,2,0.996921,0.997266,0.997081,0.997664,0.997240,0.997234,0.000248,12,0.997544,0.997452,0.997319,0.997863,0.997637,0.997563,0.000183,12,0.993874,0.993634,0.993304,0.994662,0.994102,0.993915,0.000458,12,0.996072,0.995923,0.995711,0.996582,0.996221,0.996102,0.000293,12,0.994798,0.993909,0.993657,0.994957,0.994692,0.994403,0.000519,11,5.556959,1.054767,0.106385,0.008410

modelo: linear_svm
 origem do treinamento: cicids2017_unsw_nb15
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: linear_svm - cicids2017_unsw_nb15

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
1,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,2,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced""}",0.696466,0.687143,0.668045,0.619426,0.685654,0.671347,0.027539,6,0.892404,0.875790,0.865916,0.873029,0.862527,0.873933,0.010391,1,0.782354,0.770082,0.754219,0.724681,0.763987,0.759064,0.019461,1,0.971066,0.966660,0.963799,0.964638,0.963260,0.965885,0.002837,1,0.902769,0.900315,0.892432,0.865905,0.901136,0.892511,0.013772,6,0.935673,0.932308,0.926744,0.912609,0.931163,0.927699,0.008068,3,0.859014,0.851195,0.840481,0.818645,0.847575,0.843382,0.013735,1,0.900696,0.895410,0.887129,0.867330,0.893414,0.888796,0.011578,2,0.897587,0.888052,0.879174,0.869467,0.881831,0.883222,0.009351,1,35.701615,12.201788,0.190052,0.005325
5,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,6,"{""classifier__C"": 2.23218499287176, ""classifier__class_weight"": ""balanced""}",0.695762,0.680732,0.663980,0.617282,0.685596,0.668670,0.027672,7,0.891502,0.875206,0.865757,0.872923,0.862527,0.873583,0.010076,2,0.781563,0.765815,0.751561,0.723175,0.763951,0.757213,0.019508,2,0.970824,0.966402,0.963680,0.964562,0.963259,0.965746,0.002759,2,0.902544,0.897382,0.890468,0.864697,0.901109,0.891240,0.013914,8,0.935440,0.930614,0.925629,0.911904,0.931148,0.926947,0.008139,4,0.858501,0.848215,0.838595,0.817539,0.847550,0.842080,0.013796,2,0.900335,0.892947,0.885526,0.866343,0.893393,0.887709,0.011666,3,0.897023,0.886294,0.878113,0.868810,0.881818,0.882411,0.009299,2,31.558326,11.008680,0.168612,0.008881
10,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,11,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced""}",0.693075,0.683070,0.664629,0.616264,0.685596,0.668527,0.027756,8,0.877647,0.875312,0.865757,0.872499,0.862527,0.870748,0.005727,3,0.774517,0.767334,0.751977,0.722331,0.763951,0.756022,0.018354,3,0.967231,0.966469,0.963693,0.964427,0.963259,0.965016,0.001562,3,0.902836,0.898470,0.890787,0.864180,0.901109,0.891476,0.014257,7,0.933925,0.931230,0.925807,0.911556,0.931148,0.926733,0.008033,5,0.854221,0.849282,0.838892,0.816943,0.847550,0.841377,0.013181,3,0.897798,0.893838,0.885781,0.865844,0.893393,0.887331,0.011426,4,0.890242,0.886891,0.878272,0.868339,0.881818,0.881112,0.007595,3,27.182237,6.596891,0.129838,0.036859
11,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,12,"{""classifier__C"": 0.1932075262142986, ""classifier__class_weight"": ""balanced""}",0.689176,0.615259,0.610461,0.612104,0.683683,0.642137,0.036239,9,0.866235,0.860821,0.864218,0.870800,0.861571,0.864729,0.003595,4,0.767628,0.717614,0.715507,0.718887,0.762388,0.736405,0.023438,4,0.964264,0.961349,0.962118,0.963885,0.962983,0.962920,0.001082,4,0.902332,0.865427,0.862136,0.862043,0.900340,0.878456,0.018732,9,0.932270,0.910870,0.909387,0.910124,0.930608,0.918652,0.010465,9,0.849949,0.814242,0.812447,0.814505,0.846498,0.827528,0.016948,4,0.895112,0.864506,0.862553,0.863795,0.892586,0.875710,0.014845,9,0.884283,0.863124,0.863177,0.866422,0.880955,0.871592,0.009143,4,19.898586,1.754111,0.146077,0.023785
2,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,3,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": ""balanced""}",0.615070,0.613408,0.608414,0.611022,0.611912,0.611965,0.002246,10,0.862254,0.860184,0.862838,0.868677,0.860510,0.862892,0.003062,7,0.717983,0.716132,0.713627,0.717417,0.715225,0.716077,0.001559,5,0.961718,0.961138,0.961707,0.963301,0.961183,0.961809,0.000786,7,0.865095,0.864472,0.861168,0.861751,0.863554,0.863208,0.001521,10,0.910851,0.910246,0.908664,0.909701,0.909757,0.909844,0.000720,10,0.814417,0.813189,0.811146,0.813559,0.812491,0.812960,0.001100,6,0.864527,0.863614,0.861502,0.863136,0.862945,0.863145,0.000987,10,0.863675,0.862328,0.862003,0.865214,0.862032,0.863050,0.001243,5,21.242470,4.352231,0.185947,0.030563
3,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,4,"{""classifier__C"": 0.015151125123102896, ""classifier__class_weight"": ""balanced""}",0.614384,0.613211,0.608117,0.610605,0.610623,0.611388,0.002200,11,0.862466,0.860396,0.862997,0.868571,0.860350,0.862956,0.003004,6,0.717589,0.716072,0.713477,0.717094,0.714289,0.715704,0.001586,6,0.961756,0.961188,0.961741,0.963263,0.961109,0.961812,0.000774,6,0.864671,0.864326,0.860968,0.861526,0.862838,0.862866,0.001469,11,0.910633,0.910187,0.908569,0.909558,0.909326,0.909655,0.000712,11,0.814111,0.813129,0.811023,0.813326,0.811807,0.812679,0.001111,7,0.864230,0.863540,0.861374,0.862935,0.862340,0.862884,0.000982,11,0.863568,0.862361,0.861983,0.865048,0.861594,0.862911,0.001257,7,22.120024,8.119071,0.175256,0.016231
4,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,5,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced""}",0.614023,0.612800,0.608052,0.610332,0.610358,0.611113,0.002091,12,0.863262,0.860502,0.863422,0.868571,0.860722,0.863296,0.002908,5,0.717617,0.715828,0.713578,0.716905,0.714235,0.715633,0.001534,7,0.961955,0.961206,0.961850,0.963256,0.961200,0.961894,0.000751,5,0.864339,0.864074,0.860862,0.861367,0.862625,0.862653,0.001395,12,0.910538,0.910055,0.908559,0.909467,0.909249,0.909574,0.000680,12,0.814078,0.812942,0.811068,0.813186,0.811742,0.812603,0.001070,8,0.864124,0.863359,0.861374,0.862807,0.862245,0.862782,0.000939,12,0.863801,0.862288,0.862142,0.864969,0.861674,0.862975,0.001226,6,18.613207,6.083145,0.173360,0.008407
6,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,7,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null}",0.811922,0.795824,0.807738,0.797749,0.807596,0.804166,0.006252,1,0.620309,0.613037,0.615054,0.613249,0.614013,0.615132,0.002683,8,0.703298,0.692573,0.698349,0.693437,0.697624,0.697056,0.003851,8,0.910367,0.908514,0.909181,0.908598,0.908954,0.909123,0.000667,8,0.964078,0.960680,0.963401,0.961132,0.963427,0.962544,0.001366,1,0.936453,0.933869,0.935506,0.934127,0.935398,0.935071,0.000953,1,0.819875,0.813221,0.816927,0.813782,0.816511,0.816063,0.002398,5,0.895325,0.891152,0.893732,0.891556,0.893541,0.893061,0.001531,1,0.792193,0.786859,0.789227,0.787190,0.788720,0.788838,0.001900,8,44.517697,15.882704,0.183211,0.016895
0,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,1,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null}",0.778692,0.733949,0.734836,0.731967,0.773217,0.750532,0.020850,2,0.618026,0.611657,0.614151,0.612453,0.612951,0.613848,0.002241,9,0.689118,0.667246,0.669096,0.666898,0.683819,0.675235,0.009354,9,0.909192,0.906798,0.907343,0.906914,0.908000,0.907649,0.000879,9,0.956089,0.944571,0.944597,0.943934,0.955053,0.948849,0.005504,2,0.932051,0.925299,0.925596,0.925054,0.930933,0.927786,0.003051,2,0.810585,0.796272,0.797346,0.795976,0.807376,0.801511,0.006199,9,0.888477,0.877988,0.878509,0.877638,0.886630,0.881848,0.004703,5,0.787058,0.778114,0.779374,0.778193,0.784002,0.781348,0.003576,9,22.540718,4.981736,0.182393,0.010997
7,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,8,"{""classifier__C"": 0.03684406880492199, ""classifier__class_weight"": null}",0.731110,0.726092,0.725184,0.723344,0.729067,0.726959,0.002780,3,0.616859,0.611391,0.613090,0.612187,0.611890,0.613083,0.001967,10,0.669143,0.663823,0.664442,0.663140,0.665358,0.665181,0.002111,10,0.907817,0.906540,0.906872,0.906635,0.906716,0.906916,0.000464,10,0.943283,0.942341,0.941916,0.941465,0.943150,0.942431,0.000700,3,0.925211,0.924094,0.924062,0.923722,0.924574,0.924333,0.000516,6,0.797177,0.793959,0.794252,0.793431,0.794966,0.794757,0.001308,10,0.877999,0.876152,0.876152,0.875610,0.876895,0.876562,0.000827,6,0.780071,0.776866,0.777503,0.776826,0.777520,0.777757,0.001195,10,24.164446,14.813402,0.165737,0.006606
9,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,10,"{""classifier__C"": 0.014056787147388339, ""classifier__class_weight"": null}",0.727746,0.724655,0.723930,0.721819,0.725433,0.724717,0.001934,4,0.616222,0.610489,0.612453,0.611816,0.610881,0.612372,0.002045,11,0.667357,0.662691,0.663542,0.662281,0.663247,0.663823,0.001820,11,0.907597,0.906313,0.906706,0.906517,0.906410,0.906709,0.000463,11,0.942368,0.942009,0.941611,0.941054,0.942194,0.941847,0.000470,4,0.924655,0.923817,0.923829,0.923463,0.923956,0.923944,0.000392,7,0.796006,0.793254,0.793686,0.792872,0.793602,0.793884,0.001099,11,0.877139,0.875706,0.875780,0.875207,0.875929,0.875952,0.000641,7,0.779295,0.776249,0.777032,0.776435,0.776538,0.777110,0.001123,11,17.073828,3.637773,0.176303,0.017251
8,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,9,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null}",0.727278,0.724334,0.723735,0.721495,0.724775,0.724323,0.001859,5,0.615903,0.610064,0.612134,0.611657,0.610403,0.612032,0.002081,12,0.666973,0.662306,0.663273,0.662051,0.662691,0.663459,0.001805,12,0.907518,0.906216,0.906634,0.906475,0.906293,0.906627,0.000468,12,0.942262,0.941956,0.941585,0.940974,0.942048,0.941765,0.000452,5,0.924563,0.923741,0.923779,0.923402,0.923825,0.923862,0.000381,8,0.795768,0.793023,0.793526,0.792727,0.793258,0.793660,0.001086,12,0.876991,0.875579,0.875695,0.875111,0.875717,0.875819,0.000626,8,0.779082,0.776010,0.776860,0.776315,0.776226,0.776899,0.001127,12,18.696279,6.771139,0.181399,0.009617

modelo: linear_svm
 origem do treinamento: cicids2017_iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: linear_svm - cicids2017_iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
6,linear_svm,randomized_search,cicids2017_iot23,470980,12,5,1,7,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null}",0.892397,0.888440,0.882826,0.884427,0.888999,0.887418,0.003417,1,0.948246,0.944795,0.944636,0.946866,0.950531,0.947015,0.002213,8,0.919474,0.915751,0.912686,0.914582,0.918736,0.916246,0.002542,1,0.986856,0.985977,0.985913,0.986478,0.987414,0.986527,0.000562,8,0.971416,0.970341,0.968656,0.969067,0.970328,0.969962,0.000990,1,0.979075,0.978096,0.977208,0.977695,0.978796,0.978174,0.000688,1,0.949275,0.946924,0.944947,0.946138,0.948766,0.947210,0.001615,1,0.966782,0.965232,0.963852,0.964627,0.966368,0.965372,0.001083,1,0.959831,0.957568,0.956646,0.957966,0.960429,0.958488,0.001420,4,44.102950,21.837370,0.147254,0.049679
0,linear_svm,randomized_search,cicids2017_iot23,470980,12,5,1,1,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null}",0.890647,0.886110,0.881274,0.882280,0.885618,0.885186,0.003305,2,0.947237,0.944105,0.944052,0.945645,0.948514,0.945911,0.001750,9,0.918071,0.914189,0.911584,0.912864,0.915987,0.914539,0.002291,2,0.986597,0.985794,0.985760,0.986163,0.986895,0.986242,0.000445,9,0.970925,0.969664,0.968205,0.968457,0.969372,0.969325,0.000968,2,0.978698,0.977663,0.976903,0.977230,0.978055,0.977710,0.000629,2,0.948384,0.945926,0.944244,0.945047,0.947021,0.946124,0.001459,2,0.966188,0.964553,0.963374,0.963894,0.965200,0.964642,0.000987,2,0.959081,0.956885,0.956128,0.957051,0.958943,0.957618,0.001181,5,29.442731,12.598443,0.167732,0.006704
7,linear_svm,randomized_search,cicids2017_iot23,470980,12,5,1,8,"{""classifier__C"": 0.03684406880492199, ""classifier__class_weight"": null}",0.890237,0.885771,0.880864,0.881453,0.884724,0.884610,0.003377,3,0.946706,0.943415,0.943893,0.945273,0.948355,0.945528,0.001821,10,0.917603,0.913685,0.911290,0.912248,0.915435,0.914052,0.002260,3,0.986462,0.985620,0.985718,0.986066,0.986852,0.986144,0.000461,10,0.970819,0.969585,0.968085,0.968218,0.969107,0.969163,0.000998,3,0.978578,0.977537,0.976822,0.977061,0.977899,0.977579,0.000623,3,0.948091,0.945611,0.944056,0.944654,0.946667,0.945816,0.001441,3,0.965996,0.964351,0.963247,0.963629,0.964956,0.964436,0.000978,3,0.958763,0.956500,0.955989,0.956746,0.958731,0.957346,0.001170,6,21.161049,11.030520,0.177906,0.003461
9,linear_svm,randomized_search,cicids2017_iot23,470980,12,5,1,10,"{""classifier__C"": 0.014056787147388339, ""classifier__class_weight"": null}",0.889643,0.885424,0.880846,0.881305,0.884543,0.884352,0.003186,4,0.946547,0.943468,0.943734,0.945114,0.948301,0.945433,0.001807,11,0.917213,0.913525,0.911206,0.912095,0.915313,0.913870,0.002174,4,0.986420,0.985632,0.985678,0.986026,0.986837,0.986119,0.000458,11,0.970646,0.969479,0.968085,0.968178,0.969054,0.969088,0.000940,4,0.978470,0.977488,0.976802,0.977020,0.977865,0.977529,0.000598,4,0.947841,0.945507,0.944004,0.944558,0.946589,0.945700,0.001385,4,0.965827,0.964277,0.963215,0.963565,0.964903,0.964357,0.000938,4,0.958597,0.956473,0.955909,0.956646,0.958678,0.957261,0.001150,7,13.278033,4.371974,0.195421,0.032696
8,linear_svm,randomized_search,cicids2017_iot23,470980,12,5,1,9,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null}",0.889732,0.885424,0.880803,0.881261,0.884455,0.884335,0.003233,5,0.946547,0.943468,0.943734,0.945114,0.948301,0.945433,0.001807,11,0.917260,0.913525,0.911183,0.912071,0.915266,0.913861,0.002192,5,0.986420,0.985632,0.985678,0.986026,0.986837,0.986118,0.000458,12,0.970673,0.969479,0.968072,0.968165,0.969027,0.969083,0.000954,5,0.978483,0.977488,0.976796,0.977014,0.977851,0.977526,0.000603,5,0.947872,0.945507,0.943989,0.944542,0.946559,0.945694,0.001397,5,0.965848,0.964277,0.963204,0.963555,0.964882,0.964353,0.000946,5,0.958610,0.956473,0.955903,0.956639,0.958664,0.957258,0.001152,8,8.715156,1.569994,0.188172,0.024313
1,linear_svm,randomized_search,cicids2017_iot23,470980,12,5,1,2,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced""}",0.861436,0.857893,0.852493,0.852743,0.861601,0.857233,0.003995,6,0.973831,0.970964,0.969107,0.972875,0.973142,0.971984,0.001724,1,0.914192,0.910933,0.907067,0.908856,0.913981,0.911006,0.002798,6,0.993237,0.992494,0.992003,0.992971,0.993061,0.992753,0.000449,1,0.960840,0.959791,0.958080,0.958000,0.960919,0.959526,0.001277,6,0.976770,0.975869,0.974746,0.975172,0.976725,0.975857,0.000811,6,0.945481,0.943401,0.940907,0.942014,0.945353,0.943431,0.001804,6,0.963438,0.962026,0.960285,0.960975,0.963364,0.962017,0.001258,6,0.967335,0.965378,0.963593,0.965438,0.967031,0.965755,0.001345,1,44.559339,8.575935,0.179503,0.010671
10,linear_svm,randomized_search,cicids2017_iot23,470980,12,5,1,11,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced""}",0.832628,0.823444,0.823452,0.824309,0.836340,0.828035,0.005404,7,0.971761,0.968735,0.968045,0.970540,0.972134,0.970243,0.001617,2,0.896830,0.890200,0.889914,0.891468,0.899138,0.893510,0.003762,7,0.992632,0.991823,0.991645,0.992293,0.992738,0.992226,0.000432,2,0.951166,0.948074,0.948114,0.948286,0.952439,0.949616,0.001832,7,0.971457,0.969455,0.969391,0.969791,0.972171,0.970453,0.001142,7,0.934144,0.929828,0.929652,0.930629,0.935655,0.931982,0.002452,7,0.955285,0.952206,0.952100,0.952737,0.956378,0.953741,0.001755,7,0.961463,0.958404,0.958079,0.959413,0.962286,0.959929,0.001669,2,27.562623,3.949412,0.156102,0.047659
5,linear_svm,randomized_search,cicids2017_iot23,470980,12,5,1,6,"{""classifier__C"": 2.23218499287176, ""classifier__class_weight"": ""balanced""}",0.832553,0.823482,0.823444,0.824160,0.836301,0.827988,0.005395,8,0.971761,0.968735,0.967992,0.970540,0.972134,0.970232,0.001631,3,0.896787,0.890222,0.889887,0.891381,0.899116,0.893478,0.003759,8,0.992632,0.991823,0.991631,0.992293,0.992738,0.992223,0.000435,3,0.951139,0.948087,0.948114,0.948233,0.952426,0.949600,0.001829,8,0.971443,0.969462,0.969384,0.969763,0.972164,0.970443,0.001141,8,0.934115,0.929842,0.929635,0.930572,0.935640,0.931961,0.002450,8,0.955263,0.952217,0.952089,0.952694,0.956368,0.953726,0.001753,8,0.961450,0.958411,0.958053,0.959386,0.962280,0.959916,0.001671,3,28.113589,7.330967,0.179311,0.026382
11,linear_svm,randomized_search,cicids2017_iot23,470980,12,5,1,12,"{""classifier__C"": 0.1932075262142986, ""classifier__class_weight"": ""balanced""}",0.814048,0.809664,0.808001,0.808903,0.815632,0.811250,0.003020,9,0.970168,0.966877,0.967036,0.968417,0.970966,0.968693,0.001641,4,0.885278,0.881314,0.880394,0.881502,0.886546,0.883007,0.002435,9,0.992167,0.991297,0.991333,0.991695,0.992378,0.991774,0.000435,4,0.944597,0.943177,0.942553,0.942806,0.945127,0.943652,0.001022,9,0.967798,0.966639,0.966328,0.966632,0.968177,0.967115,0.000731,9,0.926538,0.923976,0.923361,0.924067,0.927361,0.925061,0.001583,9,0.949711,0.947917,0.947450,0.947928,0.950295,0.948660,0.001125,9,0.957383,0.955027,0.954795,0.955611,0.958047,0.956172,0.001304,9,16.064449,2.771194,0.119381,0.038330
2,linear_svm,randomized_search,cicids2017_iot23,470980,12,5,1,3,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": ""balanced""}",0.812347,0.807863,0.805600,0.806385,0.812506,0.808940,0.002938,10,0.969478,0.966399,0.966771,0.968098,0.970435,0.968236,0.001544,6,0.883984,0.880048,0.878857,0.879873,0.884476,0.881448,0.002313,10,0.991982,0.991167,0.991256,0.991604,0.992231,0.991648,0.000410,6,0.944013,0.942540,0.941678,0.941890,0.944012,0.942827,0.001009,10,0.967403,0.966242,0.965831,0.966108,0.967521,0.966621,0.000701,10,0.925694,0.923145,0.922344,0.922990,0.925999,0.924034,0.001507,10,0.949106,0.947312,0.946696,0.947132,0.949297,0.947909,0.001076,10,0.956746,0.954470,0.954224,0.954994,0.957224,0.955532,0.001222,10,10.554864,1.493134,0.194202,0.025851
3,linear_svm,randomized_search,cicids2017_iot23,470980,12,5,1,4,"{""classifier__C"": 0.015151125123102896, ""classifier__class_weight"": ""balanced""}",0.812014,0.807595,0.805377,0.806054,0.812181,0.808644,0.002910,11,0.969425,0.966293,0.966718,0.968257,0.970435,0.968226,0.001570,7,0.883765,0.879845,0.878703,0.879741,0.884283,0.881268,0.002292,11,0.991967,0.991138,0.991241,0.991644,0.992230,0.991644,0.000416,7,0.943894,0.942447,0.941598,0.941757,0.943893,0.942718,0.001001,11,0.967334,0.966180,0.965782,0.966057,0.967458,0.966562,0.000694,11,0.925549,0.923012,0.922243,0.922899,0.925871,0.923915,0.001493,11,0.949000,0.947216,0.946622,0.947057,0.949202,0.947819,0.001066,11,0.956659,0.954370,0.954158,0.955007,0.957164,0.955472,0.001219,11,8.410081,0.876428,0.168499,0.006820
4,linear_svm,randomized_search,cicids2017_iot23,470980,12,5,1,5,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced""}",0.812014,0.807639,0.805271,0.805849,0.811901,0.808535,0.002902,12,0.969425,0.966346,0.966718,0.968310,0.970488,0.968258,0.001573,5,0.883765,0.879894,0.878639,0.879641,0.884139,0.881216,0.002276,12,0.991967,0.991152,0.991241,0.991657,0.992243,0.991652,0.000417,5,0.943894,0.942461,0.941558,0.941678,0.943787,0.942675,0.001001,12,0.967334,0.966193,0.965761,0.966021,0.967408,0.966543,0.000690,12,0.925549,0.923043,0.922200,0.922831,0.925774,0.923880,0.001483,12,0.949000,0.947238,0.946590,0.947004,0.949127,0.947792,0.001060,12,0.956659,0.954403,0.954138,0.954994,0.957138,0.955467,0.001211,12,7.705210,0.756483,0.173900,0.022366

modelo: linear_svm
 origem do treinamento: unsw_nb15_iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: linear_svm - unsw_nb15_iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
1,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,5,1,2,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced""}",0.923607,0.944622,0.940231,0.918435,0.919222,0.929223,0.011011,4,0.925421,0.928075,0.925208,0.925845,0.925955,0.926101,0.001024,1,0.924513,0.936275,0.932659,0.922125,0.922577,0.927630,0.005755,1,0.981346,0.982097,0.981377,0.981424,0.981454,0.981540,0.000281,1,0.980864,0.986398,0.985297,0.979445,0.979657,0.982332,0.002932,5,0.981105,0.984243,0.983333,0.980433,0.980554,0.981934,0.001558,1,0.952809,0.960259,0.957996,0.951279,0.951565,0.954782,0.003656,1,0.969776,0.974734,0.973279,0.968725,0.968916,0.971086,0.002454,1,0.953143,0.957236,0.955252,0.952645,0.952806,0.954216,0.001778,1,19.893159,4.426598,0.186487,0.032046
5,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,5,1,6,"{""classifier__C"": 2.23218499287176, ""classifier__class_weight"": ""balanced""}",0.914538,0.944468,0.939521,0.909911,0.911732,0.924034,0.014822,6,0.925315,0.928075,0.925208,0.925898,0.926008,0.926101,0.001035,2,0.919894,0.936200,0.932310,0.917835,0.918815,0.925011,0.007675,2,0.981274,0.982097,0.981373,0.981393,0.981428,0.981513,0.000296,2,0.978383,0.986358,0.985111,0.977082,0.977586,0.980904,0.003985,7,0.979826,0.984223,0.983239,0.979233,0.979504,0.981205,0.002094,4,0.949860,0.960211,0.957774,0.948534,0.949159,0.953108,0.004884,3,0.967769,0.974702,0.973130,0.966846,0.967270,0.969944,0.003294,3,0.951849,0.957217,0.955160,0.951490,0.951797,0.953503,0.002290,2,18.229511,3.738118,0.161719,0.002895
6,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,5,1,7,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null}",0.946951,0.947892,0.947104,0.947445,0.949902,0.947859,0.001072,1,0.900154,0.904772,0.901959,0.901428,0.903769,0.902416,0.001654,8,0.922960,0.925830,0.923980,0.923864,0.926261,0.924579,0.001256,3,0.975343,0.976461,0.975779,0.975653,0.976229,0.975893,0.000402,8,0.987393,0.987566,0.987407,0.987500,0.988083,0.987590,0.000255,3,0.981331,0.981982,0.981558,0.981540,0.982121,0.981707,0.000296,2,0.952146,0.953906,0.952769,0.952702,0.954191,0.953143,0.000776,2,0.969946,0.971007,0.970317,0.970285,0.971220,0.970555,0.000479,2,0.943774,0.946169,0.944683,0.944464,0.945926,0.945003,0.000907,7,18.706979,1.158340,0.176848,0.012906
10,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,5,1,11,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced""}",0.913005,0.944468,0.939521,0.907497,0.908452,0.922589,0.016031,7,0.925315,0.928075,0.925208,0.925898,0.925955,0.926090,0.001037,3,0.919118,0.936200,0.932310,0.916605,0.917120,0.924271,0.008287,4,0.981266,0.982097,0.981373,0.981380,0.981398,0.981503,0.000300,3,0.977958,0.986358,0.985111,0.976406,0.976671,0.980501,0.004324,8,0.979609,0.984223,0.983239,0.978887,0.979029,0.980997,0.002266,5,0.949364,0.960211,0.957774,0.947746,0.948074,0.952634,0.005277,4,0.967430,0.974702,0.973130,0.966304,0.966527,0.969619,0.003564,5,0.951636,0.957217,0.955160,0.951152,0.951313,0.953296,0.002455,3,18.617617,3.904108,0.127076,0.028973
0,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,5,1,1,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null}",0.946398,0.947935,0.946655,0.947386,0.949840,0.947643,0.001225,2,0.895961,0.901693,0.897712,0.897500,0.899575,0.898488,0.001971,9,0.920489,0.924236,0.921534,0.921769,0.924025,0.922411,0.001471,5,0.974332,0.975720,0.974755,0.974708,0.975220,0.974947,0.000478,9,0.987314,0.987619,0.987354,0.987539,0.988123,0.987590,0.000290,2,0.980780,0.981633,0.981014,0.981082,0.981629,0.981228,0.000344,3,0.950634,0.952935,0.951274,0.951425,0.952827,0.951819,0.000907,5,0.969043,0.970434,0.969425,0.969532,0.970413,0.969769,0.000558,4,0.941637,0.944656,0.942533,0.942520,0.943849,0.943039,0.001074,9,26.361235,8.184170,0.191463,0.015825
7,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,5,1,8,"{""classifier__C"": 0.03684406880492199, ""classifier__class_weight"": null}",0.946224,0.947182,0.947181,0.947204,0.949465,0.947451,0.001074,3,0.887308,0.891926,0.887149,0.886618,0.889544,0.888509,0.001981,10,0.915820,0.918724,0.916182,0.915910,0.918528,0.917033,0.001308,6,0.972259,0.973370,0.972228,0.972101,0.972813,0.972554,0.000476,10,0.987393,0.987566,0.987632,0.987645,0.988163,0.987680,0.000258,1,0.979768,0.980417,0.979869,0.979812,0.980428,0.980059,0.000299,6,0.947794,0.949570,0.948026,0.947861,0.949478,0.948546,0.000803,6,0.967377,0.968438,0.967536,0.967440,0.968438,0.967846,0.000486,6,0.937351,0.939746,0.937391,0.937132,0.938853,0.938095,0.001027,10,20.277530,5.170571,0.169146,0.011226
11,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,5,1,12,"{""classifier__C"": 0.1932075262142986, ""classifier__class_weight"": ""balanced""}",0.887762,0.939172,0.905212,0.887672,0.887080,0.901380,0.020104,9,0.924943,0.927756,0.924624,0.925368,0.925265,0.925591,0.001113,4,0.905971,0.933429,0.914815,0.906128,0.905770,0.913223,0.010671,7,0.981037,0.981994,0.981055,0.981142,0.981112,0.981268,0.000365,4,0.970766,0.984978,0.975795,0.970726,0.970553,0.974564,0.005572,9,0.975875,0.983484,0.978418,0.975906,0.975804,0.977897,0.002964,7,0.940923,0.958457,0.946617,0.941017,0.940787,0.945560,0.006817,7,0.961601,0.973534,0.965561,0.961654,0.961495,0.964769,0.004646,7,0.947854,0.956367,0.950210,0.948047,0.947909,0.950077,0.003266,4,15.875765,3.001553,0.095549,0.020560
2,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,5,1,3,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": ""balanced""}",0.887202,0.889268,0.886200,0.887521,0.886774,0.887393,0.001037,10,0.921440,0.925898,0.919316,0.922289,0.922452,0.922279,0.002127,5,0.903997,0.907214,0.902454,0.904571,0.904261,0.904499,0.001540,8,0.980169,0.981282,0.979639,0.980380,0.980415,0.980377,0.000531,5,0.970713,0.971177,0.970487,0.970779,0.970553,0.970742,0.000242,11,0.975418,0.976203,0.975042,0.975556,0.975459,0.975536,0.000377,9,0.939707,0.941709,0.938748,0.940064,0.939860,0.940018,0.000959,8,0.960858,0.962122,0.960253,0.961081,0.960933,0.961049,0.000606,9,0.946076,0.948538,0.944902,0.946534,0.946503,0.946510,0.001174,5,19.098285,4.297367,0.184809,0.026692
3,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,5,1,4,"{""classifier__C"": 0.015151125123102896, ""classifier__class_weight"": ""balanced""}",0.886446,0.889263,0.885749,0.887012,0.886830,0.887060,0.001184,12,0.918255,0.924147,0.916875,0.919688,0.919639,0.919721,0.002443,6,0.902070,0.906370,0.901043,0.903054,0.902937,0.903095,0.001789,9,0.979379,0.980849,0.979035,0.979736,0.979721,0.979744,0.000610,6,0.970593,0.971230,0.970434,0.970713,0.970659,0.970726,0.000269,12,0.974966,0.976016,0.974715,0.975203,0.975169,0.975214,0.000437,10,0.938518,0.941193,0.937879,0.939129,0.939053,0.939154,0.001113,9,0.960126,0.961814,0.959722,0.960508,0.960455,0.960525,0.000703,10,0.944424,0.947688,0.943654,0.945200,0.945149,0.945223,0.001355,6,16.058996,3.774040,0.182433,0.022175
4,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,5,1,5,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced""}",0.886760,0.888855,0.886450,0.887169,0.887566,0.887360,0.000837,11,0.916556,0.921599,0.915388,0.918626,0.918047,0.918043,0.002109,7,0.901412,0.904931,0.900687,0.902623,0.902549,0.902440,0.001441,10,0.978963,0.980218,0.978673,0.979475,0.979333,0.979332,0.000524,7,0.970739,0.971190,0.970686,0.970792,0.970925,0.970867,0.000180,10,0.974834,0.975683,0.974663,0.975114,0.975111,0.975081,0.000346,11,0.938123,0.940307,0.937675,0.938869,0.938830,0.938761,0.000894,10,0.959903,0.961272,0.959627,0.960359,0.960349,0.960302,0.000559,11,0.943648,0.946395,0.943037,0.944709,0.944486,0.944455,0.001139,8,14.352991,3.369479,0.167007,0.011788
9,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,5,1,10,"{""classifier__C"": 0.014056787147388339, ""classifier__class_weight"": null}",0.921013,0.945449,0.919730,0.921769,0.922038,0.926000,0.009758,5,0.874569,0.882266,0.873985,0.874993,0.876964,0.876555,0.003025,11,0.897190,0.912765,0.896274,0.897772,0.898936,0.900588,0.006150,11,0.969033,0.971050,0.968884,0.969140,0.969611,0.969544,0.000792,11,0.981249,0.987274,0.980931,0.981435,0.981461,0.982470,0.002409,4,0.975103,0.979095,0.974870,0.975249,0.975500,0.975963,0.001579,8,0.936147,0.945930,0.935572,0.936511,0.937218,0.938275,0.003864,11,0.959913,0.966272,0.959542,0.960147,0.960561,0.961287,0.002515,8,0.927909,0.934770,0.927458,0.928214,0.929213,0.929513,0.002691,11,14.205348,1.889171,0.177059,0.015088
8,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,5,1,9,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null}",0.919587,0.923218,0.917763,0.919664,0.919926,0.920032,0.001769,8,0.870481,0.879505,0.870216,0.871384,0.872611,0.872840,0.003436,12,0.894361,0.900832,0.893357,0.894873,0.895644,0.895813,0.002617,12,0.968047,0.970229,0.967969,0.968263,0.968556,0.968613,0.000833,12,0.980971,0.981714,0.980506,0.980971,0.981010,0.981034,0.000387,6,0.974466,0.975938,0.974197,0.974575,0.974743,0.974784,0.000604,12,0.934413,0.938385,0.933777,0.934724,0.935194,0.935299,0.001610,12,0.958873,0.961272,0.958448,0.959053,0.959329,0.959395,0.000981,12,0.925726,0.930609,0.925361,0.926177,0.926811,0.926937,0.001899,12,13.311668,1.611037,0.170617,0.007328

modelo: mlp
 origem do treinamento: cicids2017
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: mlp - cicids2017

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
10,mlp,randomized_search,cicids2017,235490,12,5,1,11,"{""classifier__alpha"": 1.9726066891840947e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.008237189558335287}",0.979889,0.975417,0.979707,0.974167,0.977211,0.977278,0.002275,7,0.993205,0.994161,0.994268,0.992781,0.992357,0.993354,0.000752,1,0.986502,0.984700,0.986934,0.983386,0.984726,0.985249,0.001300,1,0.998296,0.998533,0.998561,0.998187,0.998082,0.998332,0.000189,1,0.994904,0.993737,0.994851,0.993418,0.994214,0.994225,0.000591,7,0.996597,0.996129,0.996703,0.995797,0.996144,0.996274,0.000333,1,0.991550,0.990414,0.991818,0.989591,0.990435,0.990762,0.000817,1,0.994565,0.993821,0.994734,0.993291,0.993843,0.994051,0.000530,1,0.994055,0.993949,0.994559,0.993100,0.993285,0.993790,0.000533,1,46.007006,6.561582,0.099638,0.018647
9,mlp,randomized_search,cicids2017,235490,12,5,1,10,"{""classifier__alpha"": 1.3096774493777596e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.005705385668376793}",0.978368,0.977513,0.979914,0.976895,0.974183,0.977374,0.001891,6,0.993948,0.992250,0.994374,0.991932,0.993418,0.993184,0.000948,2,0.986096,0.984826,0.987091,0.984356,0.983707,0.985215,0.001222,2,0.998481,0.998055,0.998588,0.997975,0.998346,0.998289,0.000238,2,0.994506,0.994294,0.994904,0.994135,0.993418,0.994251,0.000490,6,0.996490,0.996171,0.996743,0.996051,0.995876,0.996266,0.000311,2,0.991293,0.990499,0.991917,0.990204,0.989791,0.990741,0.000766,2,0.994395,0.993885,0.994798,0.993694,0.993418,0.994038,0.000496,2,0.994227,0.993272,0.994639,0.993033,0.993418,0.993718,0.000611,2,56.381245,9.131128,0.094954,0.023082
5,mlp,randomized_search,cicids2017,235490,12,5,1,6,"{""classifier__alpha"": 0.001026603003516424, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0013103269001464436}",0.977560,0.977901,0.978975,0.976574,0.976121,0.977426,0.001007,4,0.994373,0.991294,0.993524,0.991295,0.993737,0.992845,0.001296,3,0.985895,0.984552,0.986196,0.983879,0.984850,0.985074,0.000858,3,0.998587,0.997816,0.998375,0.997815,0.998427,0.998204,0.000325,3,0.994294,0.994400,0.994665,0.994055,0.993922,0.994267,0.000261,5,0.996436,0.996105,0.996517,0.995932,0.996169,0.996232,0.000216,3,0.991165,0.990329,0.991356,0.989906,0.990510,0.990653,0.000537,3,0.994310,0.993779,0.994437,0.993503,0.993885,0.993983,0.000345,3,0.994333,0.992847,0.994095,0.992675,0.993829,0.993556,0.000671,3,78.266393,16.684635,0.157511,0.028507
6,mlp,randomized_search,cicids2017,235490,12,5,1,7,"{""classifier__alpha"": 2.6373077790924614e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.003994745694560914}",0.978842,0.976859,0.977532,0.977801,0.976096,0.977426,0.000922,5,0.992144,0.990445,0.992994,0.991295,0.992675,0.991910,0.000932,4,0.985448,0.983605,0.985202,0.984502,0.984316,0.984614,0.000657,4,0.998029,0.997603,0.998241,0.997816,0.998161,0.997970,0.000233,4,0.994639,0.994135,0.994294,0.994373,0.993922,0.994273,0.000239,4,0.996331,0.995866,0.996264,0.996092,0.996037,0.996118,0.000166,4,0.990889,0.989735,0.990733,0.990297,0.990176,0.990366,0.000412,4,0.994140,0.993397,0.994034,0.993758,0.993673,0.993800,0.000265,4,0.993391,0.992290,0.993644,0.992834,0.993299,0.993092,0.000479,4,23.175225,7.841375,0.124382,0.007644
3,mlp,randomized_search,cicids2017,235490,12,5,1,4,"{""classifier__alpha"": 0.0004134759007834719, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.002346599645859086}",0.979002,0.977282,0.979327,0.977843,0.975702,0.977831,0.001299,3,0.985030,0.991082,0.985669,0.988535,0.984713,0.987006,0.002445,5,0.982007,0.984134,0.982488,0.983160,0.980187,0.982395,0.001315,5,0.996252,0.997763,0.996411,0.997126,0.996169,0.996744,0.000611,5,0.994719,0.994241,0.994798,0.994400,0.993869,0.994405,0.000337,3,0.995485,0.995999,0.995604,0.995761,0.995018,0.995573,0.000327,5,0.988746,0.990066,0.989046,0.989460,0.987602,0.988984,0.000821,5,0.992781,0.993609,0.992972,0.993227,0.992038,0.992925,0.000523,5,0.989874,0.992661,0.990233,0.991467,0.989291,0.990706,0.001210,5,26.310266,4.697067,0.112154,0.008574
2,mlp,randomized_search,cicids2017,235490,12,5,1,3,"{""classifier__alpha"": 3.620600725744737e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0006216342697722397}",0.979695,0.976938,0.979700,0.978726,0.976286,0.978269,0.001414,2,0.983544,0.984924,0.983652,0.981635,0.983333,0.983418,0.001051,6,0.981616,0.980915,0.981672,0.980178,0.979797,0.980835,0.000752,6,0.995882,0.996224,0.995909,0.995405,0.995826,0.995849,0.000262,6,0.994904,0.994188,0.994904,0.994665,0.994028,0.994538,0.000365,2,0.995393,0.995205,0.995406,0.995035,0.994926,0.995193,0.000191,6,0.988504,0.988060,0.988539,0.987607,0.987362,0.988014,0.000471,6,0.992632,0.992335,0.992654,0.992059,0.991889,0.992314,0.000304,6,0.989224,0.989556,0.989278,0.988150,0.988681,0.988978,0.000502,6,58.874168,6.135739,0.102653,0.014002
7,mlp,randomized_search,cicids2017,235490,12,5,1,8,"{""classifier__alpha"": 0.008031279258119075, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0024246286430387822}",0.978201,0.978238,0.980207,0.978848,0.976715,0.978442,0.001128,1,0.986198,0.983119,0.983121,0.977601,0.979618,0.981931,0.003005,7,0.982183,0.980672,0.981662,0.978224,0.978164,0.980181,0.001694,7,0.996543,0.995775,0.995777,0.994402,0.994900,0.995479,0.000749,7,0.994506,0.994533,0.995037,0.994718,0.994161,0.994591,0.000287,1,0.995523,0.995153,0.995407,0.994560,0.994531,0.995035,0.000417,7,0.988853,0.987913,0.988534,0.986392,0.986347,0.987608,0.001055,7,0.992845,0.992250,0.992654,0.991295,0.991252,0.992059,0.000670,7,0.990352,0.988826,0.989079,0.986160,0.986889,0.988261,0.001527,7,47.083948,2.745195,0.121143,0.009761
1,mlp,randomized_search,cicids2017,235490,12,5,1,2,"{""classifier__alpha"": 8.072307884499753e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0001529949829431265}",0.977015,0.975729,0.978025,0.976932,0.974288,0.976398,0.001282,8,0.979297,0.977386,0.978025,0.975584,0.977495,0.977557,0.001198,10,0.978155,0.976557,0.978025,0.976258,0.975889,0.976977,0.000934,8,0.994822,0.994345,0.994506,0.993898,0.994369,0.994388,0.000298,10,0.994241,0.993922,0.994506,0.994241,0.993551,0.994092,0.000328,8,0.994531,0.994133,0.994506,0.994069,0.993960,0.994240,0.000234,8,0.986343,0.985345,0.986266,0.985163,0.984924,0.985608,0.000584,8,0.991252,0.990615,0.991210,0.990509,0.990339,0.990785,0.000375,8,0.986769,0.985654,0.986266,0.984912,0.985523,0.985825,0.000639,10,44.578399,7.024750,0.100760,0.013191
11,mlp,randomized_search,cicids2017,235490,12,5,1,12,"{""classifier__alpha"": 0.0003976453011700043, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0004275936647080326}",0.976017,0.974340,0.975455,0.975090,0.973676,0.974916,0.000825,12,0.980784,0.979616,0.978769,0.976539,0.977707,0.978683,0.001472,8,0.978394,0.976971,0.977109,0.975814,0.975687,0.976795,0.000988,9,0.995190,0.994897,0.994687,0.994132,0.994421,0.994666,0.000367,8,0.993975,0.993551,0.993843,0.993763,0.993391,0.993705,0.000209,12,0.994583,0.994224,0.994265,0.993948,0.993906,0.994185,0.000245,9,0.986488,0.985597,0.985687,0.984881,0.984797,0.985490,0.000616,9,0.991337,0.990764,0.990828,0.990318,0.990254,0.990700,0.000393,9,0.987379,0.986583,0.986306,0.985151,0.985549,0.986194,0.000784,8,14.931771,4.934177,0.087123,0.016877
8,mlp,randomized_search,cicids2017,235490,12,5,1,9,"{""classifier__alpha"": 0.004257625486011381, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.00014794095665996457}",0.974551,0.975757,0.976082,0.974997,0.973250,0.974928,0.000998,11,0.979828,0.978554,0.979087,0.976964,0.977176,0.978322,0.001101,9,0.977182,0.977153,0.977582,0.975980,0.975209,0.976621,0.000886,10,0.994951,0.994635,0.994767,0.994238,0.994288,0.994576,0.000275,9,0.993604,0.993922,0.994002,0.993736,0.993285,0.993710,0.000254,11,0.994277,0.994279,0.994384,0.993987,0.993786,0.994143,0.000222,10,0.985730,0.985716,0.985983,0.984983,0.984498,0.985382,0.000554,10,0.990849,0.990849,0.991019,0.990382,0.990063,0.990632,0.000355,10,0.986716,0.986238,0.986544,0.985350,0.985231,0.986016,0.000613,9,27.001586,3.943496,0.121262,0.010217
0,mlp,randomized_search,cicids2017,235490,12,5,1,1,"{""classifier__alpha"": 0.00017826497151386962, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.00010005268542378313}",0.975421,0.975323,0.976054,0.975268,0.973746,0.975162,0.000762,9,0.977492,0.977705,0.977919,0.975372,0.976433,0.976984,0.000955,12,0.976456,0.976512,0.976986,0.975320,0.975087,0.976072,0.000736,11,0.994371,0.994423,0.994477,0.993842,0.994104,0.994243,0.000238,12,0.993843,0.993816,0.994002,0.993816,0.993418,0.993779,0.000193,9,0.994107,0.994120,0.994239,0.993829,0.993761,0.994011,0.000184,11,0.985281,0.985316,0.985613,0.984574,0.984424,0.985042,0.000460,11,0.990573,0.990594,0.990785,0.990127,0.990021,0.990420,0.000294,11,0.985668,0.985760,0.985961,0.984594,0.984926,0.985382,0.000527,12,29.865805,2.364177,0.097305,0.008617
4,mlp,randomized_search,cicids2017,235490,12,5,1,5,"{""classifier__alpha"": 4.105412016858889e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.00011344234265835253}",0.975530,0.974820,0.975643,0.975157,0.974055,0.975041,0.000572,10,0.977705,0.978235,0.978025,0.975053,0.976433,0.977090,0.001195,11,0.976616,0.976525,0.976833,0.975105,0.975243,0.976064,0.000735,12,0.994423,0.994555,0.994503,0.993763,0.994104,0.994270,0.000298,11,0.993869,0.993683,0.993896,0.993789,0.993498,0.993747,0.000145,10,0.994146,0.994119,0.994199,0.993776,0.993801,0.994008,0.000181,12,0.985381,0.985322,0.985516,0.984441,0.984522,0.985036,0.000458,12,0.990637,0.990594,0.990721,0.990042,0.990085,0.990416,0.000291,12,0.985787,0.985959,0.985961,0.984421,0.984965,0.985419,0.000620,11,26.263687,4.047905,0.099768,0.007436

modelo: mlp
 origem do treinamento: unsw_nb15
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: mlp - unsw_nb15

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
5,mlp,randomized_search,unsw_nb15,235490,12,5,1,6,"{""classifier__alpha"": 0.001026603003516424, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0013103269001464436}",0.942312,0.942038,0.938194,0.936130,0.940054,0.939745,0.002342,2,0.995435,0.997346,0.995860,0.997346,0.993843,0.995966,0.001312,2,0.968145,0.968903,0.966167,0.965769,0.966201,0.967037,0.001247,1,0.998842,0.999327,0.998949,0.999325,0.998438,0.998976,0.000332,2,0.984766,0.984660,0.983598,0.982987,0.984155,0.984033,0.000668,7,0.991754,0.991939,0.991214,0.991089,0.991245,0.991448,0.000335,1,0.979950,0.980421,0.978691,0.978429,0.978723,0.979243,0.000791,1,0.986900,0.987197,0.986050,0.985859,0.986093,0.986420,0.000528,1,0.990100,0.991003,0.989729,0.990167,0.988999,0.990000,0.000651,2,59.354794,12.786752,0.149906,0.014264
2,mlp,randomized_search,unsw_nb15,235490,12,5,1,3,"{""classifier__alpha"": 3.620600725744737e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0006216342697722397}",0.942915,0.943205,0.938804,0.940363,0.938325,0.940722,0.002026,1,0.996072,0.996178,0.993418,0.989278,0.996497,0.994289,0.002738,5,0.968765,0.968968,0.965339,0.964201,0.966536,0.966762,0.001871,2,0.999004,0.999031,0.998330,0.997284,0.999110,0.998552,0.000693,5,0.984925,0.985005,0.983810,0.984314,0.983624,0.984336,0.000562,4,0.991915,0.991968,0.991017,0.990757,0.991307,0.991393,0.000481,2,0.980340,0.980468,0.978178,0.977479,0.978922,0.979077,0.001176,2,0.987154,0.987239,0.985732,0.985307,0.986199,0.986326,0.000765,2,0.990499,0.990591,0.988614,0.986796,0.990061,0.989312,0.001444,5,115.577383,8.820712,0.099240,0.008524
6,mlp,randomized_search,unsw_nb15,235490,12,5,1,7,"{""classifier__alpha"": 2.6373077790924614e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.003994745694560914}",0.941465,0.941265,0.937338,0.937406,0.936625,0.938820,0.002097,6,0.997240,0.997027,0.995648,0.996815,0.994692,0.996284,0.000968,1,0.968550,0.968344,0.965613,0.966198,0.964786,0.966698,0.001498,3,0.999300,0.999246,0.998895,0.999191,0.998652,0.999057,0.000246,1,0.984501,0.984448,0.983359,0.983359,0.983173,0.983768,0.000581,10,0.991845,0.991791,0.991066,0.991212,0.990852,0.991353,0.000397,3,0.980198,0.980068,0.978340,0.978705,0.977819,0.979026,0.000948,3,0.987048,0.986963,0.985817,0.986050,0.985477,0.986271,0.000628,3,0.990870,0.990737,0.989503,0.990087,0.988933,0.990026,0.000734,1,23.049874,6.315932,0.128324,0.005727
7,mlp,randomized_search,unsw_nb15,235490,12,5,1,8,"{""classifier__alpha"": 0.008031279258119075, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0024246286430387822}",0.940357,0.941123,0.937369,0.936026,0.938169,0.938609,0.001886,8,0.995966,0.996178,0.994586,0.994055,0.995435,0.995244,0.000809,4,0.967363,0.967868,0.965130,0.964168,0.965954,0.966097,0.001372,4,0.998976,0.999030,0.998625,0.998490,0.998841,0.998793,0.000206,4,0.984209,0.984421,0.983386,0.983014,0.983598,0.983725,0.000521,11,0.991538,0.991672,0.990947,0.990692,0.991161,0.991202,0.000363,4,0.979450,0.979770,0.978038,0.977430,0.978558,0.978649,0.000868,4,0.986560,0.986772,0.985626,0.985222,0.985965,0.986029,0.000575,4,0.990087,0.990299,0.988986,0.988535,0.989517,0.989485,0.000660,3,73.013991,3.525559,0.109522,0.003129
3,mlp,randomized_search,unsw_nb15,235490,12,5,1,4,"{""classifier__alpha"": 0.0004134759007834719, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.002346599645859086}",0.943137,0.941602,0.938213,0.936824,0.938790,0.939713,0.002313,3,0.991400,0.994585,0.994586,0.993312,0.994798,0.993736,0.001281,6,0.966667,0.967369,0.965578,0.964242,0.965983,0.965968,0.001057,5,0.997822,0.998627,0.998626,0.998302,0.998680,0.998411,0.000324,6,0.985058,0.984580,0.983624,0.983253,0.983784,0.984060,0.000661,6,0.991399,0.991554,0.991068,0.990720,0.991176,0.991184,0.000287,5,0.979033,0.979461,0.978323,0.977481,0.978579,0.978576,0.000672,5,0.986326,0.986581,0.985817,0.985265,0.985987,0.985995,0.000451,5,0.988229,0.989583,0.989105,0.988282,0.989291,0.988898,0.000546,6,22.079474,1.518765,0.104484,0.001680
10,mlp,randomized_search,unsw_nb15,235490,12,5,1,11,"{""classifier__alpha"": 1.9726066891840947e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.008237189558335287}",0.940958,0.938867,0.935513,0.933021,0.938505,0.937373,0.002784,9,0.996603,0.997877,0.996391,0.995223,0.991507,0.995520,0.002176,3,0.967981,0.967473,0.964993,0.963119,0.964278,0.965569,0.001868,6,0.999138,0.999461,0.999083,0.998785,0.997846,0.998863,0.000552,3,0.984368,0.983758,0.982828,0.982138,0.983757,0.983370,0.000788,12,0.991698,0.991547,0.990889,0.990392,0.990752,0.991055,0.000493,6,0.979840,0.979510,0.977941,0.976755,0.977515,0.978312,0.001180,6,0.986815,0.986581,0.985541,0.984755,0.985307,0.985800,0.000780,6,0.990485,0.990817,0.989609,0.988681,0.987632,0.989445,0.001172,4,30.082003,8.593871,0.093878,0.010322
1,mlp,randomized_search,unsw_nb15,235490,12,5,1,2,"{""classifier__alpha"": 8.072307884499753e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0001529949829431265}",0.941864,0.941762,0.938692,0.937036,0.937106,0.939292,0.002142,4,0.992462,0.994055,0.993100,0.992144,0.993312,0.993015,0.000669,7,0.966501,0.967202,0.965129,0.963803,0.964391,0.965405,0.001273,7,0.998090,0.998493,0.998249,0.998007,0.998302,0.998228,0.000170,7,0.984686,0.984633,0.983784,0.983332,0.983332,0.983954,0.000600,8,0.991343,0.991515,0.990964,0.990615,0.990761,0.991040,0.000341,7,0.978922,0.979358,0.978047,0.977209,0.977576,0.978222,0.000807,7,0.986241,0.986517,0.985647,0.985095,0.985328,0.985766,0.000538,7,0.988574,0.989344,0.988442,0.987738,0.988322,0.988484,0.000516,7,137.620577,3.650698,0.099564,0.007134
11,mlp,randomized_search,unsw_nb15,235490,12,5,1,12,"{""classifier__alpha"": 0.0003976453011700043, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0004275936647080326}",0.941899,0.940337,0.937099,0.937807,0.936503,0.938729,0.002054,7,0.993099,0.993948,0.991614,0.992463,0.991083,0.992441,0.001023,8,0.966822,0.966400,0.963586,0.964361,0.963020,0.964838,0.001515,8,0.998251,0.998465,0.997872,0.998088,0.997738,0.998083,0.000260,8,0.984686,0.984235,0.983359,0.983545,0.983200,0.983805,0.000565,9,0.991422,0.991299,0.990563,0.990763,0.990415,0.990892,0.000400,8,0.979122,0.978850,0.977074,0.977562,0.976718,0.977865,0.000957,8,0.986369,0.986178,0.985010,0.985328,0.984776,0.985532,0.000633,8,0.988893,0.989092,0.987486,0.988004,0.987141,0.988123,0.000763,8,35.813583,3.274058,0.059358,0.004010
9,mlp,randomized_search,unsw_nb15,235490,12,5,1,10,"{""classifier__alpha"": 1.3096774493777596e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.005705385668376793}",0.936976,0.940623,0.937344,0.941279,0.938757,0.938996,0.001716,5,0.997558,0.997346,0.995754,0.862739,0.990977,0.968875,0.053121,9,0.966319,0.968154,0.965666,0.900299,0.964160,0.952920,0.026342,9,0.999380,0.999326,0.998922,0.966384,0.997712,0.992345,0.012994,9,0.983227,0.984262,0.983359,0.986544,0.983837,0.984246,0.001206,5,0.991237,0.991737,0.991079,0.976360,0.990726,0.988228,0.005943,9,0.978778,0.979946,0.978373,0.938330,0.977443,0.970574,0.016142,9,0.986093,0.986878,0.985838,0.961782,0.985265,0.981171,0.009709,9,0.990392,0.990804,0.989556,0.924641,0.987407,0.976560,0.025986,9,24.658961,10.093730,0.116485,0.001648
8,mlp,randomized_search,unsw_nb15,235490,12,5,1,9,"{""classifier__alpha"": 0.004257625486011381, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.00014794095665996457}",0.937175,0.937898,0.934817,0.937263,0.935361,0.936503,0.001193,10,0.861556,0.861026,0.869321,0.864331,0.861783,0.863603,0.003078,10,0.897776,0.897819,0.900880,0.899321,0.897066,0.898572,0.001368,10,0.966076,0.965957,0.967891,0.966728,0.966111,0.966552,0.000721,10,0.985562,0.985748,0.984845,0.985535,0.985111,0.985360,0.000331,1,0.975722,0.975752,0.976294,0.976041,0.975518,0.975866,0.000272,10,0.936749,0.936786,0.938587,0.937681,0.936292,0.937219,0.000819,10,0.960763,0.960805,0.961739,0.961293,0.960444,0.961009,0.000455,10,0.923559,0.923387,0.927083,0.924933,0.923447,0.924482,0.001421,10,39.051259,9.853473,0.110222,0.002969
4,mlp,randomized_search,unsw_nb15,235490,12,5,1,5,"{""classifier__alpha"": 4.105412016858889e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.00011344234265835253}",0.937039,0.937074,0.934104,0.934248,0.933102,0.935113,0.001635,12,0.862724,0.861663,0.866773,0.859766,0.857325,0.861650,0.003151,11,0.898347,0.897788,0.899180,0.895461,0.893610,0.896877,0.002048,11,0.966351,0.966100,0.967281,0.965625,0.965039,0.966079,0.000749,11,0.985509,0.985536,0.984713,0.984872,0.984633,0.985052,0.000391,3,0.975836,0.975721,0.975919,0.975153,0.974738,0.975473,0.000455,11,0.937092,0.936754,0.937549,0.935307,0.934174,0.936175,0.001251,11,0.960954,0.960763,0.961124,0.959850,0.959170,0.960372,0.000745,11,0.924117,0.923599,0.925743,0.922319,0.920979,0.923351,0.001616,11,30.564381,3.887793,0.102204,0.010748
0,mlp,randomized_search,unsw_nb15,235490,12,5,1,1,"{""classifier__alpha"": 0.00017826497151386962, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.00010005268542378313}",0.936605,0.936987,0.934035,0.935853,0.932223,0.935141,0.001777,11,0.861132,0.860389,0.867304,0.859554,0.855626,0.860801,0.003766,12,0.897284,0.897056,0.899433,0.896082,0.892284,0.896428,0.002343,12,0.965971,0.965799,0.967406,0.965588,0.964631,0.965879,0.000893,12,0.985430,0.985536,0.984686,0.985270,0.984447,0.985074,0.000429,2,0.975603,0.975567,0.975970,0.975330,0.974438,0.975382,0.000514,12,0.936444,0.936312,0.937701,0.935706,0.933361,0.935905,0.001428,12,0.960572,0.960508,0.961209,0.960126,0.958682,0.960219,0.000844,12,0.923281,0.922962,0.925995,0.922412,0.920037,0.922937,0.001906,12,33.701210,6.623987,0.097658,0.010264

modelo: mlp
 origem do treinamento: iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: mlp - iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
10,mlp,randomized_search,iot23,235490,12,5,1,11,"{""classifier__alpha"": 1.9726066891840947e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.008237189558335287}",1.000000,0.999143,0.999358,0.999573,0.999893,0.999593,0.000320,3,0.992568,0.990551,0.991932,0.992887,0.993737,0.992335,0.001065,1,0.996270,0.994829,0.995631,0.996219,0.996805,0.995951,0.000673,1,0.998146,0.997643,0.997987,0.998225,0.998437,0.998087,0.000265,1,1.000000,0.999788,0.999841,0.999894,0.999973,0.999899,0.000079,3,0.999072,0.998714,0.998913,0.999059,0.999204,0.998992,0.000167,1,0.997671,0.996771,0.997272,0.997639,0.998005,0.997472,0.000420,1,0.998514,0.997940,0.998259,0.998493,0.998726,0.998386,0.000268,1,0.996284,0.995169,0.995886,0.996391,0.996855,0.996117,0.000565,1,30.581736,4.066486,0.099454,0.020852
9,mlp,randomized_search,iot23,235490,12,5,1,10,"{""classifier__alpha"": 1.3096774493777596e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.005705385668376793}",0.999573,0.999678,0.998078,0.999786,0.999893,0.999402,0.000670,7,0.993311,0.989808,0.992357,0.991295,0.991826,0.991719,0.001165,2,0.996432,0.994719,0.995209,0.995522,0.995843,0.995545,0.000578,2,0.998331,0.997458,0.998092,0.997828,0.997960,0.997934,0.000290,2,0.999894,0.999920,0.999522,0.999947,0.999973,0.999851,0.000167,7,0.999112,0.998688,0.998807,0.998886,0.998966,0.998892,0.000143,2,0.997772,0.996703,0.997008,0.997204,0.997405,0.997218,0.000361,2,0.998577,0.997898,0.998089,0.998216,0.998344,0.998225,0.000230,2,0.996603,0.994864,0.995939,0.995621,0.995900,0.995785,0.000562,2,37.558630,5.760585,0.121408,0.016192
5,mlp,randomized_search,iot23,235490,12,5,1,6,"{""classifier__alpha"": 0.001026603003516424, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0013103269001464436}",0.999466,0.999785,0.999571,0.998827,0.999679,0.999466,0.000337,6,0.994267,0.987791,0.989809,0.994374,0.991826,0.991613,0.002552,3,0.996860,0.993752,0.994666,0.996595,0.995737,0.995522,0.001171,3,0.998569,0.996957,0.997458,0.998595,0.997960,0.997908,0.000635,3,0.999867,0.999947,0.999894,0.999708,0.999920,0.999867,0.000084,6,0.999218,0.998450,0.998675,0.999151,0.998939,0.998886,0.000289,3,0.998039,0.996101,0.996670,0.997873,0.997338,0.997204,0.000730,3,0.998747,0.997516,0.997877,0.998641,0.998301,0.998216,0.000464,3,0.997067,0.993869,0.994851,0.997041,0.995873,0.995740,0.001246,3,59.293621,22.036605,0.146247,0.022594
2,mlp,randomized_search,iot23,235490,12,5,1,3,"{""classifier__alpha"": 3.620600725744737e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0006216342697722397}",0.999786,0.999893,0.999357,1.000000,0.999679,0.999743,0.000221,1,0.992887,0.989489,0.989703,0.991932,0.991720,0.991146,0.001327,4,0.996325,0.994664,0.994506,0.995950,0.995683,0.995426,0.000718,4,0.998225,0.997379,0.997432,0.997987,0.997934,0.997791,0.000330,4,0.999947,0.999973,0.999841,1.000000,0.999920,0.999936,0.000055,1,0.999085,0.998675,0.998635,0.998992,0.998926,0.998863,0.000178,4,0.997705,0.996669,0.996571,0.997471,0.997305,0.997144,0.000448,4,0.998535,0.997877,0.997813,0.998386,0.998280,0.998178,0.000285,4,0.996417,0.994731,0.994772,0.995966,0.995820,0.995541,0.000674,4,12.892169,1.997540,0.101172,0.013871
7,mlp,randomized_search,iot23,235490,12,5,1,8,"{""classifier__alpha"": 0.008031279258119075, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0024246286430387822}",0.999572,1.000000,0.999678,0.999572,0.999572,0.999679,0.000166,2,0.992568,0.989702,0.989172,0.991932,0.991720,0.991019,0.001332,7,0.996058,0.994824,0.994397,0.995737,0.995630,0.995329,0.000618,5,0.998145,0.997432,0.997300,0.997987,0.997934,0.997760,0.000331,7,0.999894,1.000000,0.999920,0.999894,0.999894,0.999920,0.000041,2,0.999019,0.998714,0.998608,0.998939,0.998913,0.998839,0.000153,5,0.997538,0.996769,0.996503,0.997338,0.997272,0.997084,0.000386,5,0.998429,0.997940,0.997771,0.998301,0.998259,0.998140,0.000245,5,0.996231,0.994851,0.994546,0.995913,0.995807,0.995470,0.000652,7,21.305517,4.975210,0.136967,0.018489
3,mlp,randomized_search,iot23,235490,12,5,1,4,"{""classifier__alpha"": 0.0004134759007834719, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.002346599645859086}",0.999679,0.999785,0.999250,0.999358,0.999358,0.999486,0.000208,5,0.992568,0.989595,0.989703,0.992038,0.991720,0.991125,0.001236,5,0.996111,0.994664,0.994453,0.995685,0.995524,0.995288,0.000629,6,0.998145,0.997406,0.997432,0.998013,0.997934,0.997786,0.000308,5,0.999920,0.999947,0.999814,0.999841,0.999841,0.999873,0.000051,5,0.999032,0.998675,0.998622,0.998926,0.998886,0.998828,0.000155,6,0.997572,0.996670,0.996537,0.997305,0.997205,0.997058,0.000392,6,0.998450,0.997877,0.997792,0.998280,0.998216,0.998123,0.000249,6,0.996244,0.994771,0.994758,0.995939,0.995780,0.995499,0.000618,5,10.476600,1.873739,0.103371,0.011400
6,mlp,randomized_search,iot23,235490,12,5,1,7,"{""classifier__alpha"": 2.6373077790924614e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.003994745694560914}",0.999359,0.999678,0.999571,0.999144,0.999679,0.999486,0.000207,4,0.992887,0.989171,0.989809,0.991826,0.991720,0.991082,0.001378,6,0.996112,0.994397,0.994666,0.995472,0.995683,0.995266,0.000640,7,0.998225,0.997300,0.997458,0.997960,0.997934,0.997775,0.000343,6,0.999841,0.999920,0.999894,0.999788,0.999920,0.999873,0.000051,4,0.999032,0.998608,0.998675,0.998873,0.998926,0.998823,0.000158,7,0.997572,0.996503,0.996670,0.997172,0.997305,0.997044,0.000399,7,0.998450,0.997771,0.997877,0.998195,0.998280,0.998115,0.000254,7,0.996364,0.994546,0.994851,0.995807,0.995820,0.995478,0.000674,6,12.587170,1.256229,0.140667,0.018031
11,mlp,randomized_search,iot23,235490,12,5,1,12,"{""classifier__alpha"": 0.0003976453011700043, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0004275936647080326}",0.999679,0.999893,0.999035,0.999144,0.999251,0.999401,0.000329,8,0.992356,0.989595,0.989490,0.991507,0.991720,0.990934,0.001170,9,0.996004,0.994717,0.994240,0.995311,0.995471,0.995149,0.000612,8,0.998093,0.997406,0.997379,0.997881,0.997934,0.997738,0.000291,9,0.999920,0.999973,0.999761,0.999788,0.999814,0.999851,0.000082,8,0.999006,0.998688,0.998569,0.998833,0.998873,0.998794,0.000151,8,0.997505,0.996703,0.996404,0.997072,0.997172,0.996971,0.000382,8,0.998408,0.997898,0.997707,0.998132,0.998195,0.998068,0.000243,8,0.996138,0.994784,0.994626,0.995648,0.995767,0.995393,0.000586,9,9.432056,0.969287,0.075502,0.020871
1,mlp,randomized_search,iot23,235490,12,5,1,2,"{""classifier__alpha"": 8.072307884499753e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0001529949829431265}",0.999145,0.999893,0.998821,0.999037,0.998931,0.999165,0.000379,9,0.992674,0.989489,0.989490,0.991614,0.991720,0.990997,0.001285,8,0.995899,0.994664,0.994134,0.995312,0.995312,0.995064,0.000608,9,0.998172,0.997379,0.997379,0.997907,0.997934,0.997754,0.000320,8,0.999788,0.999973,0.999708,0.999761,0.999735,0.999793,0.000094,9,0.998979,0.998675,0.998542,0.998833,0.998833,0.998772,0.000150,9,0.997439,0.996669,0.996338,0.997072,0.997073,0.996918,0.000379,9,0.998365,0.997877,0.997664,0.998132,0.998132,0.998034,0.000241,9,0.996231,0.994731,0.994599,0.995687,0.995727,0.995395,0.000627,8,17.458694,0.817447,0.096427,0.004099
8,mlp,randomized_search,iot23,235490,12,5,1,9,"{""classifier__alpha"": 0.004257625486011381, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.00014794095665996457}",0.999358,0.999678,0.995407,0.999251,0.998397,0.998418,0.001564,10,0.992250,0.989489,0.989384,0.991507,0.991720,0.990870,0.001195,10,0.995791,0.994558,0.992387,0.995364,0.995047,0.994629,0.001192,10,0.998066,0.997379,0.997350,0.997881,0.997933,0.997722,0.000298,10,0.999841,0.999920,0.998859,0.999814,0.999602,0.999607,0.000389,10,0.998953,0.998648,0.998104,0.998847,0.998767,0.998664,0.000297,10,0.997372,0.996603,0.995245,0.997105,0.996907,0.996647,0.000744,10,0.998323,0.997834,0.996964,0.998153,0.998025,0.997860,0.000476,10,0.996045,0.994705,0.994122,0.995661,0.995661,0.995239,0.000713,10,19.167697,4.693651,0.131336,0.015859
4,mlp,randomized_search,iot23,235490,12,5,1,5,"{""classifier__alpha"": 4.105412016858889e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.00011344234265835253}",0.999359,0.997004,0.995833,0.997650,0.997117,0.997393,0.001148,11,0.992462,0.989277,0.989384,0.991507,0.991295,0.990785,0.001251,12,0.995898,0.993125,0.992598,0.994569,0.994197,0.994078,0.001155,11,0.998119,0.997325,0.997350,0.997880,0.997827,0.997700,0.000312,12,0.999841,0.999257,0.998965,0.999416,0.999283,0.999352,0.000285,11,0.998979,0.998290,0.998157,0.998647,0.998555,0.998526,0.000287,11,0.997439,0.995708,0.995378,0.996608,0.996376,0.996302,0.000721,11,0.998365,0.997261,0.997049,0.997834,0.997686,0.997639,0.000460,11,0.996151,0.994267,0.994175,0.995462,0.995289,0.995069,0.000751,12,12.895346,0.709034,0.108097,0.011044
0,mlp,randomized_search,iot23,235490,12,5,1,1,"{""classifier__alpha"": 0.00017826497151386962, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.00010005268542378313}",0.999252,0.996791,0.995620,0.997756,0.997117,0.997307,0.001194,12,0.992568,0.989383,0.989384,0.991401,0.991295,0.990806,0.001245,11,0.995899,0.993073,0.992492,0.994569,0.994197,0.994046,0.001191,12,0.998145,0.997351,0.997350,0.997854,0.997827,0.997705,0.000311,11,0.999814,0.999204,0.998912,0.999443,0.999283,0.999331,0.000297,12,0.998979,0.998277,0.998130,0.998648,0.998555,0.998518,0.000296,12,0.997439,0.995675,0.995311,0.996608,0.996376,0.996282,0.000744,12,0.998365,0.997240,0.997006,0.997834,0.997686,0.997626,0.000475,12,0.996191,0.994293,0.994148,0.995422,0.995289,0.995069,0.000759,11,15.751843,1.524981,0.138752,0.041244

modelo: mlp
 origem do treinamento: cicids2017_unsw_nb15
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: mlp - cicids2017_unsw_nb15

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
6,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,7,"{""classifier__alpha"": 2.6373077790924614e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.003994745694560914}",0.950759,0.951325,0.952760,0.951047,0.951869,0.951552,0.000706,7,0.986995,0.990764,0.985987,0.983810,0.990924,0.987696,0.002769,3,0.968538,0.970644,0.969088,0.967151,0.971004,0.969285,0.001411,1,0.996718,0.997667,0.996466,0.995917,0.997707,0.996895,0.000697,3,0.987221,0.987327,0.987778,0.987340,0.987473,0.987428,0.000193,8,0.991946,0.992470,0.992103,0.991610,0.992564,0.992139,0.000349,1,0.980242,0.981557,0.980596,0.979381,0.981784,0.980712,0.000880,1,0.987176,0.988014,0.987420,0.986634,0.988163,0.987481,0.000559,1,0.987108,0.989045,0.986882,0.985575,0.989198,0.987562,0.001378,2,59.842393,3.357850,0.240226,0.010130
5,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,6,"{""classifier__alpha"": 0.001026603003516424, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0013103269001464436}",0.945225,0.942242,0.955650,0.946736,0.955298,0.949030,0.005458,11,0.992940,0.994108,0.974521,0.995382,0.992516,0.989893,0.007751,1,0.968495,0.967480,0.964993,0.970450,0.973551,0.968994,0.002879,2,0.998213,0.998506,0.993599,0.998830,0.998110,0.997452,0.001943,1,0.985615,0.984766,0.988694,0.986000,0.988388,0.986693,0.001564,11,0.991874,0.991589,0.991140,0.992374,0.993226,0.992040,0.000715,2,0.980184,0.979534,0.978067,0.981412,0.983388,0.980517,0.001796,2,0.987080,0.986634,0.985859,0.987876,0.989214,0.987333,0.001145,2,0.989278,0.989437,0.981607,0.990691,0.990452,0.988293,0.003388,1,237.101107,35.865207,0.301672,0.033978
9,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,10,"{""classifier__alpha"": 1.3096774493777596e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.005705385668376793}",0.951160,0.939953,0.948747,0.953467,0.954868,0.949639,0.005271,9,0.978980,0.990445,0.992409,0.974521,0.991614,0.985594,0.007384,4,0.964870,0.964539,0.970087,0.963879,0.972894,0.967254,0.003586,3,0.994706,0.997579,0.998080,0.993595,0.997883,0.996369,0.001852,4,0.987433,0.984182,0.986597,0.988110,0.988282,0.986921,0.001492,9,0.991056,0.990835,0.992305,0.990845,0.993059,0.991620,0.000903,3,0.977963,0.977687,0.981196,0.977362,0.982977,0.979437,0.002244,3,0.985742,0.985435,0.987760,0.985392,0.988949,0.986655,0.001442,3,0.983206,0.987314,0.989503,0.981315,0.989948,0.986257,0.003435,4,94.276803,11.718800,0.221440,0.010928
10,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,11,"{""classifier__alpha"": 1.9726066891840947e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.008237189558335287}",0.943070,0.941748,0.937494,0.955893,0.941548,0.943950,0.006256,12,0.989224,0.992887,0.993577,0.975529,0.990074,0.988259,0.006572,2,0.965596,0.966642,0.964721,0.965611,0.965201,0.965554,0.000633,4,0.997273,0.998197,0.998370,0.993851,0.997486,0.997035,0.001645,2,0.985071,0.984646,0.983439,0.988747,0.984633,0.985307,0.001804,12,0.991134,0.991376,0.990848,0.991292,0.991018,0.991134,0.000189,5,0.978365,0.979009,0.977785,0.978452,0.978110,0.978344,0.000405,4,0.985902,0.986295,0.985466,0.986103,0.985721,0.985897,0.000289,5,0.987148,0.988767,0.988508,0.982138,0.987354,0.986783,0.002406,3,106.709197,12.055542,0.136329,0.019865
3,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,4,"{""classifier__alpha"": 0.0004134759007834719, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.002346599645859086}",0.949056,0.951113,0.940620,0.954111,0.952113,0.949403,0.004684,10,0.986889,0.982112,0.981262,0.981156,0.979352,0.982154,0.002532,5,0.967603,0.966364,0.960511,0.967445,0.965541,0.965493,0.002601,5,0.996689,0.995491,0.995264,0.995255,0.994801,0.995500,0.000635,5,0.986756,0.987380,0.984514,0.988203,0.987685,0.986908,0.001285,10,0.991698,0.991419,0.989860,0.991717,0.991230,0.991185,0.000687,4,0.979650,0.978891,0.975186,0.979581,0.978385,0.978339,0.001644,5,0.986783,0.986326,0.983863,0.986793,0.986019,0.985957,0.001087,4,0.986823,0.984746,0.982888,0.984679,0.983519,0.984531,0.001345,5,50.731966,12.511839,0.205816,0.014181
2,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,3,"{""classifier__alpha"": 3.620600725744737e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0006216342697722397}",0.955300,0.946127,0.955040,0.955112,0.954085,0.953133,0.003528,4,0.974468,0.983492,0.964064,0.935188,0.983811,0.968204,0.018021,6,0.964789,0.964447,0.959531,0.945045,0.968720,0.960506,0.008262,6,0.993585,0.995832,0.990995,0.983881,0.995921,0.992043,0.004461,6,0.988601,0.986000,0.988654,0.989012,0.988163,0.988086,0.001077,6,0.991087,0.990892,0.989823,0.986440,0.992027,0.990054,0.001938,6,0.977938,0.977669,0.974677,0.965742,0.980373,0.975280,0.005100,6,0.985774,0.985498,0.983736,0.978247,0.987292,0.984110,0.003141,6,0.981534,0.984746,0.976359,0.962100,0.985987,0.978145,0.008685,6,266.529523,15.914944,0.192450,0.013469
7,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,8,"{""classifier__alpha"": 0.008031279258119075, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0024246286430387822}",0.957770,0.937684,0.938234,0.953731,0.961988,0.949881,0.010080,8,0.917352,0.983226,0.979670,0.930039,0.904034,0.942864,0.032579,7,0.937126,0.959915,0.958504,0.941736,0.932111,0.945878,0.011311,7,0.979554,0.995755,0.994861,0.982618,0.976363,0.985830,0.007992,7,0.989888,0.983664,0.983877,0.988720,0.991069,0.987444,0.003090,7,0.984694,0.989673,0.989338,0.985660,0.983661,0.986605,0.002453,7,0.960910,0.974794,0.973921,0.963698,0.957886,0.966242,0.006882,7,0.975381,0.983577,0.983035,0.976984,0.973661,0.978528,0.004044,7,0.953620,0.983445,0.981773,0.959380,0.947552,0.965154,0.014744,7,136.008158,16.457570,0.236404,0.010156
11,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,12,"{""classifier__alpha"": 0.0003976453011700043, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0004275936647080326}",0.954485,0.955326,0.952823,0.953384,0.955533,0.954310,0.001061,1,0.920590,0.918308,0.915548,0.922767,0.917038,0.918850,0.002563,8,0.937231,0.936451,0.933813,0.937825,0.935890,0.936242,0.001382,8,0.980323,0.979773,0.979092,0.980846,0.979465,0.979900,0.000622,8,0.989026,0.989264,0.988667,0.988720,0.989331,0.989002,0.000272,2,0.984655,0.984496,0.983856,0.984767,0.984373,0.984429,0.000317,8,0.960943,0.960474,0.958835,0.961296,0.960132,0.960336,0.000849,8,0.975339,0.975073,0.974043,0.975530,0.974872,0.974971,0.000515,8,0.954808,0.953786,0.952107,0.955743,0.953184,0.953926,0.001262,8,56.597451,9.153100,0.126252,0.021996
1,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,2,"{""classifier__alpha"": 8.072307884499753e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0001529949829431265}",0.954223,0.955061,0.952672,0.953394,0.955130,0.954096,0.000953,3,0.920590,0.916025,0.918892,0.922979,0.910669,0.917831,0.004238,9,0.937105,0.935136,0.935477,0.937940,0.932370,0.935605,0.001919,9,0.980321,0.979219,0.979901,0.980897,0.977923,0.979652,0.001024,9,0.988959,0.989225,0.988588,0.988720,0.989304,0.988959,0.000277,3,0.984621,0.984196,0.984225,0.984793,0.983581,0.984283,0.000419,9,0.960863,0.959666,0.959851,0.961367,0.957975,0.959944,0.001169,9,0.975286,0.974585,0.974649,0.975572,0.973576,0.974734,0.000689,9,0.954775,0.952625,0.953740,0.955850,0.949986,0.953395,0.002013,9,216.234116,33.073229,0.167546,0.004773
8,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,9,"{""classifier__alpha"": 0.004257625486011381, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.00014794095665996457}",0.953844,0.955146,0.952784,0.954107,0.955567,0.954290,0.000986,2,0.915972,0.913318,0.913690,0.919263,0.914331,0.915315,0.002173,10,0.934525,0.933764,0.932828,0.936361,0.934494,0.934394,0.001162,10,0.979200,0.978564,0.978642,0.979999,0.978810,0.979043,0.000526,10,0.988919,0.989278,0.988681,0.988946,0.989370,0.989039,0.000252,1,0.984036,0.983892,0.983636,0.984452,0.984062,0.984015,0.000266,10,0.959280,0.958828,0.958232,0.960407,0.959278,0.959205,0.000713,10,0.974330,0.974086,0.973683,0.975010,0.974362,0.974294,0.000432,10,0.952446,0.951298,0.951185,0.954105,0.951851,0.952177,0.001063,10,111.652167,7.335283,0.232543,0.033369
0,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,1,"{""classifier__alpha"": 0.00017826497151386962, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.00010005268542378313}",0.952437,0.953205,0.951288,0.952813,0.954010,0.952750,0.000898,5,0.907745,0.900685,0.903923,0.919635,0.902866,0.906971,0.006732,12,0.929554,0.926201,0.927001,0.935930,0.927734,0.929284,0.003503,11,0.977204,0.975509,0.976276,0.980082,0.976036,0.977022,0.001626,12,0.988667,0.988946,0.988428,0.988614,0.989118,0.988755,0.000246,4,0.982902,0.982181,0.982315,0.984330,0.982534,0.982852,0.000778,11,0.956228,0.954191,0.954658,0.960130,0.955134,0.956068,0.002141,11,0.972483,0.971294,0.971527,0.974818,0.971867,0.972398,0.001275,11,0.948206,0.944815,0.946176,0.954124,0.945992,0.947863,0.003315,12,93.369192,17.379803,0.177370,0.014278
4,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,5,"{""classifier__alpha"": 4.105412016858889e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.00011344234265835253}",0.949447,0.954146,0.950754,0.952350,0.954143,0.952168,0.001858,6,0.906205,0.904613,0.900791,0.920856,0.903397,0.907172,0.007067,11,0.927322,0.928719,0.925098,0.936338,0.928077,0.929111,0.003815,12,0.976816,0.976459,0.975520,0.980376,0.976165,0.977067,0.001708,11,0.987937,0.989132,0.988336,0.988481,0.989145,0.988606,0.000470,5,0.982345,0.982755,0.981886,0.984412,0.982612,0.982802,0.000858,12,0.954834,0.955737,0.953492,0.960375,0.955344,0.955956,0.002336,12,0.971591,0.972228,0.970827,0.974956,0.971995,0.972319,0.001402,12,0.947071,0.946872,0.944563,0.954669,0.946271,0.947889,0.003503,11,82.339657,14.741654,0.190122,0.017186

modelo: mlp
 origem do treinamento: cicids2017_iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: mlp - cicids2017_iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
5,mlp,randomized_search,cicids2017_iot23,470980,12,5,1,6,"{""classifier__alpha"": 0.001026603003516424, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0013103269001464436}",0.987094,0.987434,0.987281,0.987630,0.988165,0.987521,0.000367,1,0.990605,0.988534,0.988906,0.991719,0.988323,0.989617,0.001323,1,0.988846,0.987984,0.988093,0.989671,0.988244,0.988568,0.000627,1,0.997649,0.997133,0.997225,0.997928,0.997080,0.997403,0.000330,1,0.996762,0.996855,0.996815,0.996895,0.997041,0.996874,0.000094,1,0.997205,0.996994,0.997020,0.997411,0.997061,0.997138,0.000155,1,0.993026,0.992489,0.992557,0.993541,0.992652,0.992853,0.000391,1,0.995531,0.995191,0.995233,0.995860,0.995297,0.995422,0.000248,1,0.993683,0.992695,0.992861,0.994307,0.992682,0.993245,0.000646,1,193.250445,12.960066,0.279842,0.011784
6,mlp,randomized_search,cicids2017_iot23,470980,12,5,1,7,"{""classifier__alpha"": 2.6373077790924614e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.003994745694560914}",0.986806,0.985533,0.987620,0.987490,0.986963,0.986882,0.000741,2,0.988534,0.987154,0.986623,0.988853,0.988535,0.987940,0.000882,4,0.987669,0.986343,0.987121,0.988171,0.987749,0.987411,0.000630,2,0.997132,0.996787,0.996657,0.997212,0.997132,0.996984,0.000220,3,0.996696,0.996377,0.996908,0.996868,0.996735,0.996717,0.000187,2,0.996914,0.996582,0.996782,0.997040,0.996934,0.996851,0.000157,2,0.992292,0.991463,0.991952,0.992606,0.992341,0.992131,0.000394,2,0.995063,0.994533,0.994851,0.995265,0.995095,0.994962,0.000252,2,0.992615,0.991766,0.991766,0.992861,0.992635,0.992328,0.000467,2,37.538498,4.708741,0.240365,0.007583
3,mlp,randomized_search,cicids2017_iot23,470980,12,5,1,4,"{""classifier__alpha"": 0.0004134759007834719, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.002346599645859086}",0.987375,0.963213,0.987037,0.985297,0.987297,0.982044,0.009446,3,0.988057,0.982642,0.982165,0.988906,0.985934,0.985541,0.002743,5,0.987716,0.972831,0.984595,0.987098,0.986615,0.983771,0.005569,3,0.997014,0.995639,0.995547,0.997224,0.996485,0.996382,0.000688,5,0.996842,0.990618,0.996775,0.996311,0.996828,0.995475,0.002436,3,0.996928,0.993122,0.996161,0.996767,0.996656,0.995927,0.001426,3,0.992322,0.982976,0.990378,0.991933,0.991636,0.989849,0.003497,3,0.995085,0.989023,0.993853,0.994830,0.994649,0.993488,0.002270,3,0.992449,0.986630,0.989470,0.992608,0.991381,0.990508,0.002239,5,51.710343,14.908279,0.208542,0.011637
9,mlp,randomized_search,cicids2017_iot23,470980,12,5,1,10,"{""classifier__alpha"": 1.3096774493777596e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.005705385668376793}",0.981142,0.964502,0.987105,0.987276,0.966471,0.977299,0.009914,4,0.994214,0.987951,0.987367,0.988481,0.988376,0.989278,0.002499,2,0.987635,0.976086,0.987236,0.987878,0.977301,0.983227,0.005353,4,0.998549,0.996969,0.996841,0.997119,0.997077,0.997311,0.000626,2,0.995223,0.990910,0.996775,0.996815,0.991427,0.994230,0.002570,4,0.996883,0.993930,0.996808,0.996967,0.994244,0.995767,0.001376,4,0.992259,0.985008,0.992022,0.992423,0.985773,0.989497,0.003364,4,0.995021,0.990318,0.994894,0.995148,0.990817,0.993240,0.002189,4,0.994718,0.989430,0.992071,0.992648,0.989902,0.991754,0.001925,3,95.197887,27.665113,0.183732,0.045908
10,mlp,randomized_search,cicids2017_iot23,470980,12,5,1,11,"{""classifier__alpha"": 1.9726066891840947e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.008237189558335287}",0.966895,0.986020,0.964661,0.965385,0.987218,0.974036,0.010306,5,0.989118,0.988375,0.983863,0.990392,0.987951,0.987940,0.002201,3,0.977880,0.987196,0.974168,0.977729,0.987584,0.980911,0.005456,5,0.997264,0.997092,0.995946,0.997582,0.996987,0.996974,0.000552,4,0.991534,0.996497,0.990990,0.991122,0.996802,0.993389,0.002670,5,0.994391,0.996794,0.993461,0.994342,0.996894,0.995177,0.001402,5,0.986135,0.991995,0.983815,0.986035,0.992239,0.988044,0.003429,5,0.991051,0.994872,0.989564,0.990976,0.995032,0.992299,0.002231,5,0.990326,0.992436,0.987426,0.990757,0.992377,0.990664,0.001826,4,45.754235,6.601323,0.175527,0.040652
2,mlp,randomized_search,cicids2017_iot23,470980,12,5,1,3,"{""classifier__alpha"": 3.620600725744737e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0006216342697722397}",0.965831,0.963530,0.962282,0.965322,0.965211,0.964435,0.001326,7,0.985774,0.981687,0.980466,0.984076,0.980786,0.982558,0.002046,6,0.975701,0.972524,0.971289,0.974608,0.972936,0.973412,0.001562,6,0.996425,0.995400,0.995093,0.996000,0.995177,0.995619,0.000513,6,0.991282,0.990711,0.990392,0.991162,0.991162,0.990942,0.000337,7,0.993847,0.993050,0.992737,0.993575,0.993165,0.993275,0.000392,6,0.984774,0.982787,0.982013,0.984092,0.983051,0.983343,0.000977,6,0.990180,0.988906,0.988407,0.989745,0.989087,0.989265,0.000627,6,0.988528,0.986199,0.985429,0.987619,0.985974,0.986750,0.001146,6,77.584951,30.385463,0.197854,0.019106
11,mlp,randomized_search,cicids2017_iot23,470980,12,5,1,12,"{""classifier__alpha"": 0.0003976453011700043, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0004275936647080326}",0.964089,0.960858,0.961366,0.963846,0.963113,0.962654,0.001310,8,0.984713,0.979882,0.978767,0.980678,0.981210,0.981050,0.002008,7,0.974292,0.970277,0.969989,0.972189,0.972078,0.971765,0.001551,7,0.996158,0.994946,0.994668,0.995148,0.995280,0.995240,0.000503,7,0.990830,0.990021,0.990167,0.990804,0.990605,0.990485,0.000332,8,0.993487,0.992477,0.992412,0.992971,0.992937,0.992857,0.000389,7,0.983889,0.981377,0.981200,0.982580,0.982507,0.982311,0.000970,7,0.989607,0.987993,0.987887,0.988779,0.988726,0.988598,0.000623,7,0.987771,0.984951,0.984467,0.985741,0.985907,0.985768,0.001131,7,30.522667,6.690008,0.127140,0.030177
1,mlp,randomized_search,cicids2017_iot23,470980,12,5,1,2,"{""classifier__alpha"": 8.072307884499753e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0001529949829431265}",0.963146,0.961374,0.961400,0.963509,0.963021,0.962490,0.000915,9,0.982165,0.978980,0.977016,0.981103,0.980042,0.979861,0.001775,9,0.972562,0.970097,0.969145,0.972227,0.971457,0.971098,0.001293,8,0.995519,0.994721,0.994231,0.995254,0.994988,0.994943,0.000444,9,0.990605,0.990167,0.990193,0.990711,0.990591,0.990453,0.000227,9,0.993056,0.992439,0.992208,0.992977,0.992785,0.992693,0.000323,8,0.982809,0.981268,0.980676,0.982602,0.982121,0.981895,0.000808,8,0.988917,0.987929,0.987558,0.988789,0.988481,0.988335,0.000517,8,0.986385,0.984573,0.983605,0.985907,0.985317,0.985157,0.000984,9,62.442954,6.230826,0.162874,0.009826
8,mlp,randomized_search,cicids2017_iot23,470980,12,5,1,9,"{""classifier__alpha"": 0.004257625486011381, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.00014794095665996457}",0.963127,0.960289,0.960661,0.963164,0.962577,0.961964,0.001239,10,0.981634,0.979404,0.978661,0.979882,0.981635,0.980243,0.001201,8,0.972292,0.969753,0.969577,0.971451,0.972013,0.971017,0.001138,9,0.995386,0.994825,0.994640,0.994949,0.995386,0.995037,0.000301,8,0.990605,0.989875,0.989981,0.990631,0.990459,0.990310,0.000319,10,0.992990,0.992344,0.992305,0.992785,0.992916,0.992668,0.000288,9,0.982641,0.981048,0.980941,0.982118,0.982464,0.981843,0.000713,9,0.988811,0.987781,0.987717,0.988481,0.988694,0.988297,0.000460,9,0.986119,0.984640,0.984321,0.985257,0.986047,0.985277,0.000724,8,49.183071,5.644563,0.214933,0.003679
7,mlp,randomized_search,cicids2017_iot23,470980,12,5,1,8,"{""classifier__alpha"": 0.008031279258119075, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0024246286430387822}",0.969219,0.963427,0.963182,0.965093,0.968025,0.965789,0.002434,6,0.966081,0.980201,0.978980,0.981793,0.965764,0.974564,0.007112,12,0.967648,0.971741,0.971016,0.973371,0.966893,0.970134,0.002471,10,0.991527,0.995029,0.994723,0.995429,0.991446,0.993631,0.001765,12,0.992330,0.990698,0.990645,0.991122,0.992025,0.991364,0.000691,6,0.991928,0.992858,0.992680,0.993271,0.991735,0.992494,0.000577,10,0.979788,0.982300,0.981848,0.983321,0.979314,0.981314,0.001524,10,0.987080,0.988598,0.988312,0.989256,0.986772,0.988004,0.000937,10,0.979205,0.985449,0.984812,0.986458,0.978894,0.982964,0.003240,12,64.922331,13.028702,0.239327,0.016766
4,mlp,randomized_search,cicids2017_iot23,470980,12,5,1,5,"{""classifier__alpha"": 4.105412016858889e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.00011344234265835253}",0.962932,0.960660,0.958880,0.961992,0.961844,0.961262,0.001393,11,0.979033,0.977334,0.972928,0.978077,0.975425,0.976560,0.002168,10,0.970916,0.968925,0.965853,0.969968,0.968587,0.968850,0.001707,11,0.994736,0.994309,0.993207,0.994496,0.993834,0.994117,0.000543,10,0.990578,0.989994,0.989570,0.990339,0.990326,0.990161,0.000349,11,0.992653,0.992147,0.991385,0.992414,0.992077,0.992135,0.000427,11,0.981784,0.980536,0.978619,0.981191,0.980332,0.980492,0.001067,11,0.988269,0.987462,0.986241,0.987887,0.987346,0.987441,0.000683,11,0.984806,0.983664,0.981249,0.984208,0.982875,0.983360,0.001232,10,37.526258,13.042036,0.177318,0.007244
0,mlp,randomized_search,cicids2017_iot23,470980,12,5,1,1,"{""classifier__alpha"": 0.00017826497151386962, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.00010005268542378313}",0.962928,0.960159,0.959029,0.962611,0.960955,0.961136,0.001471,12,0.978927,0.977334,0.972875,0.978502,0.974522,0.976432,0.002350,11,0.970862,0.968670,0.965903,0.970491,0.967691,0.968723,0.001829,12,0.994710,0.994308,0.993194,0.994603,0.993608,0.994085,0.000588,11,0.990578,0.989862,0.989609,0.990499,0.990100,0.990130,0.000369,12,0.992640,0.992080,0.991399,0.992547,0.991851,0.992103,0.000457,12,0.981751,0.980375,0.978651,0.981519,0.979771,0.980413,0.001143,12,0.988248,0.987356,0.986263,0.988099,0.986985,0.987390,0.000731,12,0.984752,0.983598,0.981242,0.984500,0.982311,0.983281,0.001330,11,39.318190,14.825010,0.161000,0.007829

modelo: mlp
 origem do treinamento: unsw_nb15_iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: mlp - unsw_nb15_iot23

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,candidate_id,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
5,mlp,randomized_search,unsw_nb15_iot23,470980,12,5,1,6,"{""classifier__alpha"": 0.001026603003516424, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0013103269001464436}",0.970628,0.967591,0.966504,0.966749,0.969843,0.968263,0.001669,1,0.985827,0.990498,0.990976,0.992356,0.991773,0.990286,0.002319,2,0.978169,0.978911,0.978587,0.979385,0.980685,0.979148,0.000866,1,0.996443,0.997610,0.997730,0.998076,0.997931,0.997558,0.000580,2,0.992542,0.991706,0.991414,0.991467,0.992290,0.991884,0.000453,1,0.994489,0.994650,0.994562,0.994761,0.995103,0.994713,0.000215,1,0.986329,0.986780,0.986575,0.987073,0.987894,0.986930,0.000540,1,0.991199,0.991465,0.991327,0.991645,0.992187,0.991564,0.000345,1,0.989185,0.991102,0.991195,0.991912,0.992031,0.991085,0.001020,1,233.384618,46.350864,0.305920,0.013091
6,mlp,randomized_search,unsw_nb15_iot23,470980,12,5,1,7,"{""classifier__alpha"": 2.6373077790924614e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.003994745694560914}",0.966758,0.967905,0.962517,0.965895,0.967110,0.966037,0.001874,3,0.991082,0.986093,0.989596,0.992197,0.992622,0.990318,0.002358,1,0.978769,0.976914,0.975869,0.978869,0.979700,0.978024,0.001411,2,0.997757,0.996507,0.997381,0.998036,0.998143,0.997565,0.000591,1,0.991481,0.991826,0.990366,0.991242,0.991560,0.991295,0.000500,3,0.994609,0.994161,0.993861,0.994627,0.994841,0.994420,0.000356,2,0.986689,0.985537,0.984865,0.986748,0.987270,0.986222,0.000884,2,0.991401,0.990679,0.990212,0.991433,0.991772,0.991099,0.000569,2,0.991281,0.988959,0.989981,0.991719,0.992091,0.990806,0.001166,2,67.607709,15.079777,0.236384,0.012310
9,mlp,randomized_search,unsw_nb15_iot23,470980,12,5,1,10,"{""classifier__alpha"": 1.3096774493777596e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.005705385668376793}",0.969012,0.965832,0.967248,0.964384,0.964724,0.966240,0.001709,2,0.985987,0.988800,0.989171,0.984553,0.988535,0.987409,0.001816,3,0.977426,0.977181,0.978087,0.974364,0.976484,0.976708,0.001279,3,0.996481,0.997183,0.997277,0.996118,0.997116,0.996835,0.000455,3,0.992118,0.991255,0.991627,0.990910,0.990963,0.991374,0.000451,2,0.994295,0.994210,0.994444,0.993507,0.994030,0.994097,0.000324,3,0.985860,0.985696,0.986265,0.983936,0.985257,0.985403,0.000802,3,0.990891,0.990764,0.991136,0.989639,0.990477,0.990581,0.000517,3,0.989052,0.990027,0.990399,0.987732,0.989749,0.989392,0.000940,3,102.871101,27.229295,0.196344,0.056343
10,mlp,randomized_search,unsw_nb15_iot23,470980,12,5,1,11,"{""classifier__alpha"": 1.9726066891840947e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.008237189558335287}",0.967868,0.965152,0.964217,0.964800,0.964059,0.965219,0.001382,4,0.989702,0.986464,0.988375,0.974786,0.989490,0.985764,0.005607,4,0.978663,0.975692,0.976147,0.969767,0.976609,0.975376,0.002982,4,0.997411,0.996597,0.997076,0.993680,0.997355,0.996424,0.001402,4,0.991786,0.991096,0.990830,0.991109,0.990777,0.991120,0.000359,4,0.994590,0.993839,0.993943,0.992393,0.994055,0.993764,0.000733,4,0.986627,0.984765,0.985045,0.981080,0.985332,0.984570,0.001858,4,0.991369,0.990169,0.990339,0.987844,0.990520,0.990048,0.001177,4,0.990744,0.988780,0.989603,0.982948,0.990134,0.988442,0.002822,4,90.606203,19.531362,0.160426,0.039295
3,mlp,randomized_search,unsw_nb15_iot23,470980,12,5,1,4,"{""classifier__alpha"": 0.0004134759007834719, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.002346599645859086}",0.962834,0.961738,0.963336,0.964401,0.964405,0.963343,0.001008,5,0.968098,0.961994,0.963745,0.966346,0.966401,0.965317,0.002167,7,0.965459,0.961866,0.963541,0.965373,0.965402,0.964328,0.001429,5,0.992014,0.990498,0.990936,0.991582,0.991596,0.991325,0.000538,7,0.990658,0.990432,0.990830,0.991082,0.991082,0.990817,0.000251,5,0.991335,0.990465,0.990883,0.991332,0.991339,0.991071,0.000350,5,0.978397,0.976166,0.977212,0.978353,0.978370,0.977700,0.000889,5,0.986146,0.984745,0.985413,0.986135,0.986146,0.985717,0.000562,5,0.979378,0.976213,0.977288,0.978714,0.978742,0.978067,0.001152,7,35.015759,7.026954,0.191582,0.006350
2,mlp,randomized_search,unsw_nb15_iot23,470980,12,5,1,3,"{""classifier__alpha"": 3.620600725744737e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0006216342697722397}",0.953667,0.952624,0.953062,0.950469,0.953010,0.952566,0.001100,12,0.971283,0.971283,0.973247,0.972769,0.988217,0.975360,0.006476,5,0.962394,0.961863,0.963049,0.961490,0.970294,0.963818,0.003280,6,0.992788,0.992786,0.993276,0.993152,0.997027,0.993806,0.001622,5,0.988203,0.987924,0.988017,0.987327,0.987818,0.987858,0.000294,12,0.990490,0.990349,0.990640,0.990231,0.992401,0.990822,0.000801,6,0.976442,0.976106,0.976844,0.975861,0.981347,0.977320,0.002041,6,0.984819,0.984596,0.985063,0.984415,0.987898,0.985358,0.001288,6,0.979743,0.979604,0.980632,0.980048,0.988017,0.981609,0.003224,5,221.252845,40.993620,0.188491,0.018367
7,mlp,randomized_search,unsw_nb15_iot23,470980,12,5,1,8,"{""classifier__alpha"": 0.008031279258119075, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0024246286430387822}",0.958653,0.950606,0.951835,0.958215,0.964097,0.956681,0.004932,10,0.967355,0.970487,0.974521,0.966506,0.960669,0.967907,0.004584,6,0.962984,0.960443,0.963045,0.962342,0.962380,0.962239,0.000944,7,0.991820,0.992583,0.993592,0.991608,0.990175,0.991956,0.001130,6,0.989570,0.987393,0.987672,0.989463,0.991056,0.989031,0.001349,11,0.990694,0.989981,0.990623,0.990535,0.990615,0.990490,0.000259,7,0.976839,0.975212,0.976834,0.976439,0.976498,0.976364,0.000599,7,0.985127,0.984012,0.985042,0.984872,0.984978,0.984806,0.000406,7,0.978462,0.978940,0.981096,0.977985,0.975862,0.978469,0.001683,6,118.061891,10.302211,0.223900,0.009492
11,mlp,randomized_search,unsw_nb15_iot23,470980,12,5,1,12,"{""classifier__alpha"": 0.0003976453011700043, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0004275936647080326}",0.960829,0.959673,0.960770,0.960026,0.961984,0.960657,0.000796,6,0.929667,0.929720,0.926907,0.926801,0.925425,0.927704,0.001707,9,0.944992,0.944459,0.943535,0.943121,0.943350,0.943891,0.000714,8,0.982558,0.982566,0.981887,0.981857,0.981531,0.982080,0.000413,9,0.990525,0.990233,0.990538,0.990353,0.990857,0.990501,0.000211,6,0.986526,0.986385,0.986194,0.986087,0.986172,0.986272,0.000160,8,0.965759,0.965422,0.964864,0.964604,0.964761,0.965082,0.000436,8,0.978354,0.978131,0.977812,0.977642,0.977770,0.977942,0.000261,8,0.960096,0.959977,0.958723,0.958577,0.958141,0.959103,0.000787,9,35.138742,7.734364,0.139452,0.017362
1,mlp,randomized_search,unsw_nb15_iot23,470980,12,5,1,2,"{""classifier__alpha"": 8.072307884499753e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0001529949829431265}",0.962751,0.945707,0.962671,0.961627,0.950307,0.956613,0.007187,11,0.930198,0.930145,0.928128,0.928499,0.929777,0.929349,0.000866,8,0.946195,0.937861,0.945084,0.944773,0.939930,0.942769,0.003264,9,0.982696,0.982608,0.982192,0.982278,0.982538,0.982462,0.000194,8,0.991003,0.986650,0.991003,0.990737,0.987844,0.989448,0.001838,10,0.986832,0.984625,0.986578,0.986489,0.985184,0.985942,0.000872,9,0.966513,0.961243,0.965831,0.965631,0.962557,0.964355,0.002068,9,0.978842,0.975349,0.978428,0.978290,0.976230,0.977428,0.001378,9,0.960600,0.958398,0.959565,0.959618,0.958811,0.959398,0.000757,8,150.288309,28.251997,0.168661,0.008029
4,mlp,randomized_search,unsw_nb15_iot23,470980,12,5,1,5,"{""classifier__alpha"": 4.105412016858889e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.00011344234265835253}",0.959264,0.958942,0.959700,0.959681,0.962592,0.960035,0.001309,9,0.923722,0.927332,0.924041,0.924837,0.927389,0.925464,0.001590,10,0.941157,0.942872,0.941533,0.941937,0.944662,0.942432,0.001253,10,0.981106,0.981982,0.981185,0.981378,0.982011,0.981532,0.000389,10,0.990193,0.990074,0.990300,0.990286,0.990989,0.990368,0.000321,9,0.985629,0.986011,0.985721,0.985812,0.986480,0.985931,0.000302,11,0.963393,0.964441,0.963627,0.963874,0.965571,0.964181,0.000777,10,0.976899,0.977526,0.977048,0.977196,0.978269,0.977388,0.000487,11,0.956958,0.958703,0.957170,0.957562,0.959189,0.957916,0.000876,10,57.150118,4.742847,0.178609,0.015590
8,mlp,randomized_search,unsw_nb15_iot23,470980,12,5,1,9,"{""classifier__alpha"": 0.004257625486011381, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.00014794095665996457}",0.958937,0.959162,0.960172,0.960461,0.962763,0.960299,0.001361,7,0.921015,0.926323,0.926482,0.924518,0.927707,0.925209,0.002331,12,0.939593,0.942457,0.943026,0.942147,0.944910,0.942427,0.001711,11,0.980447,0.981737,0.981781,0.981305,0.982089,0.981472,0.000570,12,0.990140,0.990140,0.990392,0.990485,0.991029,0.990437,0.000326,7,0.985270,0.985921,0.986068,0.985874,0.986539,0.985934,0.000407,10,0.962432,0.964189,0.964547,0.964010,0.965724,0.964180,0.001059,11,0.976315,0.977377,0.977611,0.977292,0.978364,0.977392,0.000658,10,0.955578,0.958232,0.958437,0.957502,0.959368,0.957823,0.001271,12,61.518551,11.391725,0.206538,0.009050
0,mlp,randomized_search,unsw_nb15_iot23,470980,12,5,1,1,"{""classifier__alpha"": 0.00017826497151386962, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.00010005268542378313}",0.959087,0.958880,0.960300,0.959905,0.962665,0.960167,0.001353,8,0.923297,0.927119,0.925739,0.923881,0.926539,0.925315,0.001487,11,0.940852,0.942732,0.942703,0.941549,0.944257,0.942418,0.001163,12,0.981002,0.981930,0.981601,0.981147,0.981805,0.981497,0.000363,11,0.990154,0.990061,0.990432,0.990353,0.991016,0.990403,0.000334,8,0.985556,0.985978,0.985997,0.985729,0.986389,0.985930,0.000282,12,0.963204,0.964355,0.964350,0.963639,0.965323,0.964174,0.000723,12,0.976782,0.977473,0.977494,0.977058,0.978120,0.977385,0.000454,12,0.956725,0.958590,0.958086,0.957117,0.958778,0.957859,0.000808,11,61.882395,4.975783,0.169269,0.022714

,model,search_method,training_source,training_rows,n_iter,n_splits,random_state,n_candidates,params,elapsed_seconds,elapsed_minutes,refit_time_seconds,model_size_mb,model_file,precision_attack_mean,precision_attack_std,recall_attack_mean,recall_attack_std,f1_attack_mean,f1_attack_std,precision_benign_mean,precision_benign_std,recall_benign_mean,recall_benign_std,f1_benign_mean,f1_benign_std,f1_macro_mean,f1_macro_std,accuracy_mean,accuracy_std,balanced_accuracy_mean,balanced_accuracy_std
0,decision_tree,randomized_search,cicids2017,235490,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17}",19.661492,0.327692,1.380483,0.016391,cicids2017.joblib,0.979586,0.001766,0.989108,0.000861,0.984322,0.000794,0.997270,0.000215,0.994846,0.000457,0.996057,0.000204,0.990190,0.000499,0.993698,0.000324,0.991977,0.000383
1,decision_tree,randomized_search,unsw_nb15,235490,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10}",16.897677,0.281628,1.485629,0.013993,unsw_nb15.joblib,0.942730,0.001502,0.994671,0.000767,0.968004,0.000994,0.998649,0.000194,0.984893,0.000417,0.991723,0.000263,0.979864,0.000628,0.986849,0.000416,0.989782,0.000500
2,decision_tree,randomized_search,iot23,235490,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 6}",8.468512,0.141142,0.456563,0.005307,iot23.joblib,0.999530,0.000174,0.993206,0.000961,0.996358,0.000533,0.998304,0.000240,0.999883,0.000043,0.999093,0.000132,0.997725,0.000332,0.998548,0.000212,0.996544,0.000492
3,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17}",35.891478,0.598191,3.638380,0.037752,cicids2017_unsw_nb15.joblib,0.960364,0.001356,0.987197,0.001023,0.973595,0.000938,0.996777,0.000257,0.989814,0.000361,0.993283,0.000241,0.983439,0.000590,0.989290,0.000384,0.988505,0.000573
4,decision_tree,randomized_search,cicids2017_iot23,470980,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 20}",30.642596,0.510710,2.950768,0.024882,cicids2017_iot23.joblib,0.988149,0.000841,0.990467,0.000564,0.989306,0.000620,0.997615,0.000141,0.997030,0.000212,0.997323,0.000156,0.993314,0.000388,0.995717,0.000249,0.993748,0.000350
5,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17}",26.691578,0.444860,2.330632,0.029032,unsw_nb15_iot23.joblib,0.970711,0.001018,0.992133,0.000865,0.981304,0.000325,0.998023,0.000216,0.992516,0.000273,0.995261,0.000084,0.988283,0.000205,0.992439,0.000134,0.992325,0.000335
6,random_forest,randomized_search,cicids2017,235490,12,5,1,12,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 229}",622.521286,10.375355,47.460043,7.689332,cicids2017.joblib,0.981708,0.001679,0.993460,0.001069,0.987548,0.000839,0.998360,0.000267,0.995371,0.000434,0.996864,0.000213,0.992206,0.000526,0.994989,0.000340,0.994416,0.000504
7,random_forest,randomized_search,unsw_nb15,235490,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 168}",592.863899,9.881065,37.218539,7.578541,unsw_nb15.joblib,0.943890,0.001787,0.996433,0.000788,0.969449,0.000928,0.999096,0.000200,0.985190,0.000503,0.992094,0.000249,0.980771,0.000588,0.987439,0.000392,0.990812,0.000409
8,random_forest,randomized_search,iot23,235490,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 168}",403.117249,6.718621,17.444867,1.047265,iot23.joblib,0.999808,0.000157,0.993291,0.000922,0.996538,0.000481,0.998325,0.000230,0.999952,0.000039,0.999138,0.000119,0.997838,0.000300,0.998620,0.000191,0.996621,0.000464
9,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 168}",1491.183474,24.853058,102.189504,10.958267,cicids2017_unsw_nb15.joblib,0.961678,0.001016,0.993163,0.000679,0.977167,0.000693,0.998277,0.000171,0.990106,0.000271,0.994174,0.000179,0.985671,0.000436,0.990717,0.000284,0.991634,0.000397
10,random_forest,randomized_search,cicids2017_iot23,470980,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 246}",1343.521462,22.392024,119.275517,6.447956,cicids2017_iot23.joblib,0.988851,0.000587,0.993386,0.000645,0.991113,0.000497,0.998345,0.000161,0.997200,0.000148,0.997772,0.000125,0.994443,0.000311,0.996437,0.000199,0.995293,0.000351
11,random_forest,randomized_search,unsw_nb15_iot23,470980,12,5,1,12,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 168}",1134.499830,18.908330,71.249165,8.392435,unsw_nb15_iot23.joblib,0.970897,0.000698,0.994819,0.000525,0.982712,0.000466,0.998697,0.000132,0.992545,0.000184,0.995611,0.000119,0.989162,0.000292,0.993000,0.000189,0.993682,0.000287
12,xgboost,randomized_search,cicids2017,235490,12,5,1,12,"{""classifier__colsample_bytree"": 0.717772960390469, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9873668590451505}",50.081530,0.834692,6.043281,0.256427,cicids2017.joblib,0.980977,0.001133,0.993015,0.001540,0.986958,0.000962,0.998248,0.000385,0.995186,0.000292,0.996715,0.000241,0.991836,0.000601,0.994751,0.000386,0.994100,0.000783
13,xgboost,randomized_search,unsw_nb15,235490,12,5,1,12,"{""classifier__colsample_bytree"": 0.9725786509279286, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 200, ""classifier__subsample"": 0.8574398130611336}",52.228643,0.870477,5.258541,0.470984,unsw_nb15.joblib,0.943358,0.001352,0.997856,0.000477,0.969841,0.000527,0.999456,0.000121,0.985021,0.000386,0.992186,0.000146,0.981013,0.000337,0.987588,0.000229,0.991438,0.000113
14,xgboost,randomized_search,iot23,235490,12,5,1,12,"{""classifier__colsample_bytree"": 0.7895485884259134, ""classifier__learning_rate"": 0.08380226576125108, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 253, ""classifier__subsample"": 0.8343680578527715}",46.119371,0.768656,5.402304,0.123423,iot23.joblib,0.999701,0.000080,0.993354,0.000882,0.996517,0.000457,0.998341,0.000220,0.999926,0.000020,0.999133,0.000113,0.997825,0.000285,0.998611,0.000181,0.996640,0.000444
15,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,12,"{""classifier__colsample_bytree"": 0.717772960390469, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9873668590451505}",111.757761,1.862629,12.570497,0.334027,cicids2017_unsw_nb15.joblib,0.960944,0.000892,0.993864,0.000529,0.977127,0.000561,0.998453,0.000133,0.989901,0.000239,0.994159,0.000145,0.985643,0.000353,0.990694,0.000231,0.991883,0.000304
16,xgboost,randomized_search,cicids2017_iot23,470980,12,5,1,12,"{""classifier__colsample_bytree"": 0.717772960390469, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9873668590451505}",99.891910,1.664865,11.744246,0.275344,cicids2017_iot23.joblib,0.988759,0.000703,0.992601,0.000798,0.990676,0.000647,0.998148,0.000199,0.997179,0.000177,0.997663,0.000162,0.994170,0.000405,0.996263,0.000259,0.994890,0.000448
17,xgboost,randomized_search,unsw_nb15_iot23,470980,12,5,1,12,"{""classifier__colsample_bytree"": 0.717772960390469, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9873668590451505}",100.434760,1.673913,12.495847,0.292947,unsw_nb15_iot23.joblib,0.971144,0.000715,0.994681,0.000547,0.982772,0.000511,0.998662,0.000137,0.992611,0.000187,0.995627,0.000130,0.989200,0.000321,0.993025,0.000208,0.993646,0.000312
18,linear_svm,randomized_search,cicids2017,235490,12,5,1,12,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced""}",55.001995,0.916700,5.579139,0.001999,cicids2017.joblib,0.760466,0.003145,0.962886,0.002528,0.849787,0.002813,0.990060,0.000680,0.924174,0.001156,0.955983,0.000880,0.902885,0.001845,0.931916,0.001341,0.943530,0.001734
19,linear_svm,randomized_search,unsw_nb15,235490,12,5,1,12,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null}",54.998012,0.916634,5.208250,0.002011,unsw_nb15.joblib,0.937565,0.001079,0.827997,0.004519,0.879374,0.002538,0.958221,0.001047,0.986215,0.000274,0.972016,0.000504,0.925695,0.001520,0.954571,0.000844,0.907106,0.002211
20,linear_svm,randomized_search,iot23,235490,12,5,1,12,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null}",41.596527,0.693275,2.320128,0.001993,iot23.joblib,0.995329,0.000946,0.990870,0.001107,0.993095,0.000912,0.997720,0.000276,0.998838,0.000236,0.998278,0.000227,0.995687,0.000570,0.997244,0.000364,0.994854,0.000628
21,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,12,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced""}",143.871452,2.397858,8.932112,0.002011,cicids2017_unsw_nb15.joblib,0.671347,0.027539,0.873933,0.010391,0.759064,0.019461,0.965885,0.002837,0.892511,0.013772,0.927699,0.008068,0.843382,0.013735,0.888796,0.011578,0.883222,0.009351
22,linear_svm,randomized_search,cicids2017_iot23,470980,12,5,1,12,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null}",142.201567,2.370026,22.302443,0.001997,cicids2017_iot23.joblib,0.887418,0.003417,0.947015,0.002213,0.916246,0.002542,0.986527,0.000562,0.969962,0.000990,0.978174,0.000688,0.947210,0.001615,0.965372,0.001083,0.958488,0.001420
23,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,5,1,12,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced""}",102.314495,1.705242,4.994679,0.002008,unsw_nb15_iot23.joblib,0.929223,0.011011,0.926101,0.001024,0.927630,0.005755,0.981540,0.000281,0.982332,0.002932,0.981934,0.001558,0.954782,0.003656,0.971086,0.002454,0.954216,0.001778
24,mlp,randomized_search,cicids2017,235490,12,5,1,12,"{""classifier__alpha"": 1.9726066891840947e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.008237189558335287}",230.235576,3.837260,21.293389,0.101001,cicids2017.joblib,0.977278,0.002275,0.993354,0.000752,0.985249,0.001300,0.998332,0.000189,0.994225,0.000591,0.996274,0.000333,0.990762,0.000817,0.994051,0.000530,0.993790,0.000533
25,mlp,randomized_search,unsw_nb15,235490,12,5,1,12,"{""classifier__alpha"": 0.001026603003516424, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0013103269001464436}",326.839419,5.447324,51.571146,0.197846,unsw_nb15.joblib,0.939745,0.002342,0.995966,0.001312,0.967037,0.001247,0.998976,0.000332,0.984033,0.000668,0.991448,0.000335,0.979243,0.000791,0.986420,0.000528,0.990000,0.000651
26,mlp,randomized_search,iot23,235490,12,5,1,12,"{""classifier__alpha"": 1.9726066891840947e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.008237189558335287}",130.310537,2.171842,15.559455,0.099761,iot23.joblib,0.999593,0.000320,0.992335,0.001065,0.995951,0.000673,0.998087,0.000265,0.999899,0.000079,0.998992,0.000167,0.997472,0.000420,0.998386,0.000268,0.996117,0.000565
27,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,12,"{""classifier__alpha"": 2.6373077790924614e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.003994745694560914}",718.215151,11.970253,52.550314,0.078990,cicids2017_unsw_nb15.joblib,0.951552,0.000706,0.987696,0.002769,0.969285,0.001411,0.996895,0.000697,0.987428,0.000193,0.992139,0.000349,0.980712,0.000880,0.987481,0.000559,0.987562,0.001378
28,mlp,randomized_search,cicids2017_iot23,470980,12,5,1,12,"{""classifier__alpha"": 0.001026603003516424, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0013103269001464436}",498.192450,8.303208,145.423687,0.175910,cicids2017_iot23.joblib,0.987521,0.000367,0.989617,0.001323,0.988568,0.000627,0.997403,0.000330,0.996874,0.000094,0.997138,0.000155,0.992853,0.000391,0.995422,0.000248,0.993245,0.000646
29,mlp,randomized_search,unsw_nb15_iot23,470980,12,5,1,12,"{""classifier__alpha"": 0.001026603003516424, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0013103269001464436}",675.503067,11.258384,129.018252,0.190155,unsw_nb15_iot23.joblib,0.968263,0.001669,0.990286,0.002319,0.979148,0.000866,0.997558,0.000580,0.991884,0.000453,0.994713,0.000215,0.986930,0.000540,0.991564,0.000345,0.991085,0.001020