In [1]:
from pathlib import Path
from time import perf_counter
import json

import joblib
import pandas as pd
from scipy.stats import loguniform, randint, uniform
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    f1_score,
    make_scorer,
    precision_score,
    recall_score,
)
from sklearn.model_selection import ParameterSampler, RandomizedSearchCV, StratifiedKFold
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier

from xgboost import XGBClassifier

from src.utils.features import split_features

In [2]:
DATA_DIR = Path("../datasets/final/ml")
SEARCH_METHOD = "randomized_search"
MODEL_DIR = Path("../models") / SEARCH_METHOD
RESULTS_DIR = Path("../results/model_training") / SEARCH_METHOD

MODEL_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 1
N_SPLITS = 5
N_RANDOM_CANDIDATES = 12
N_JOBS = -1

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [3]:
#configurações de treinamento / organização / origem dos dados
TRAINING_CONFIGS = {
    "cicids2017": ["cicids2017"],
    "unsw_nb15": ["unsw_nb15"],
    "iot23": ["iot23"],
    "cicids2017_unsw_nb15": ["cicids2017", "unsw_nb15"],
    "cicids2017_iot23": ["cicids2017", "iot23"],
    "unsw_nb15_iot23": ["unsw_nb15", "iot23"],
}

In [4]:
# atributos
reference_df = pd.read_parquet(DATA_DIR / "cicids2017_train.parquet")

numerical_features, categorical_features = split_features(reference_df)
feature_columns = numerical_features + categorical_features

del reference_df

print("features num:", len(numerical_features))
print("features cat:", len(categorical_features))
print("Total de features antes do one-hot:", len(feature_columns))

features num: 14
features cat: 1
Total de features antes do one-hot: 15

In [5]:
#pipeline pré-rocessamento
def build_pipeline(estimator):
    preprocessor = ColumnTransformer(
        transformers=[
            ("numerical", StandardScaler(), numerical_features),
            ("categorical", OneHotEncoder(handle_unknown="ignore"),categorical_features),
        ]
    )

    return Pipeline(
        steps=[ ("preprocessor", preprocessor),
                ("classifier", estimator),
        ]
    )

In [6]:
#modelos e espaços de busca
MODEL_CONFIGS = {
    "decision_tree": {
        "estimator": DecisionTreeClassifier(
            random_state=RANDOM_STATE,
        ),
        "param_distributions": {
            "classifier__max_depth": [None, 3, 5, 8, 10, 15, 20, 30],
            "classifier__min_samples_split": randint(2, 21),
            "classifier__min_samples_leaf": randint(1, 11),
            "classifier__class_weight": [None, "balanced"],
        },
        "baseline_params": {
            "classifier__max_depth": None,
            "classifier__min_samples_split": 2,
            "classifier__min_samples_leaf": 1,
            "classifier__class_weight": None,
        },
    },
    "random_forest": {
        "estimator": RandomForestClassifier(
            random_state=RANDOM_STATE,
            n_jobs=1,
        ),
        "param_distributions": {
            "classifier__n_estimators": randint(100, 301),
            "classifier__max_depth": [None, 10, 15, 20, 30],
            "classifier__min_samples_leaf": randint(1, 11),
            "classifier__max_features": ["sqrt", "log2", 0.5, 1.0],
            "classifier__class_weight": [None, "balanced", "balanced_subsample"],
        },
        "baseline_params": {
            "classifier__n_estimators": 100,
            "classifier__max_depth": None,
            "classifier__min_samples_leaf": 1,
            "classifier__max_features": "sqrt",
            "classifier__class_weight": None,
        },
    },
    "xgboost": {
        "estimator": XGBClassifier(
            random_state=RANDOM_STATE,
            n_jobs=1,
            eval_metric="logloss",
            tree_method="hist",
        ),
        "param_distributions": {
            "classifier__n_estimators": randint(100, 301),
            "classifier__max_depth": randint(3, 9),
            "classifier__learning_rate": loguniform(0.03, 0.3),
            "classifier__subsample": uniform(0.7, 0.3),
            "classifier__colsample_bytree": uniform(0.7, 0.3),
        },
        # Valores efetivos dos defaults do XGBoost 3.4.1. O wrapper retorna None,
        # mas o booster usa estes valores quando os hiperparâmetros não são informados.
        "baseline_params": {
            "classifier__n_estimators": 100,
            "classifier__max_depth": 6,
            "classifier__learning_rate": 0.3,
            "classifier__subsample": 1.0,
            "classifier__colsample_bytree": 1.0,
            "classifier__eval_metric": "logloss",
            "classifier__tree_method": "hist",
        },
    },
    "linear_svm": {
        "estimator": LinearSVC(
            random_state=RANDOM_STATE,
        ),
        "param_distributions": {
            "classifier__C": loguniform(1e-3, 1e2),
            "classifier__class_weight": [None, "balanced"],
        },
        "baseline_params": {
            "classifier__C": 1.0,
            "classifier__class_weight": None,
            "classifier__dual": "auto",
            "classifier__max_iter": 1000,
        },
    },
    "mlp": {
        "estimator": MLPClassifier(
            random_state=RANDOM_STATE,
        ),
        "param_distributions": {
            "classifier__hidden_layer_sizes": [
                (50,),
                (100,),
                (50, 50),
                (100, 50),
            ],
            "classifier__alpha": loguniform(1e-5, 1e-2),
            "classifier__learning_rate_init": loguniform(1e-4, 1e-2),
            "classifier__early_stopping": [True, False],
        },
        "baseline_params": {
            "classifier__hidden_layer_sizes": (100,),
            "classifier__alpha": 0.0001,
            "classifier__learning_rate_init": 0.001,
            "classifier__early_stopping": False,
            "classifier__max_iter": 200,
        },
    },
}

In [7]:
#modelos para rodar
MODELS_TO_RUN = [
    "decision_tree",
    "random_forest",
    "xgboost",
    "linear_svm",
    "mlp",
]

In [8]:
# kfold estratificado + métricas
# buscar os melhores hiperparâmetros pelo F1 macro
cross_validation = StratifiedKFold(
    n_splits=N_SPLITS,
    shuffle=True,
    random_state=RANDOM_STATE,
)

scoring = {
    #o make_scorer cria um avaliador que calcula a métrica estabelecida, considerando a classe 1 ataque como positiva
    "precision_attack": make_scorer(
        precision_score,
        pos_label=1,
        zero_division=0,
    ),
    "recall_attack": make_scorer(
        recall_score,
        pos_label=1,
        zero_division=0,
    ),
    "f1_attack": make_scorer(
        f1_score,
        pos_label=1,
        zero_division=0,
    ),
    "precision_benign": make_scorer(
        precision_score,
        pos_label=0,
        zero_division=0,
    ),
    "recall_benign": make_scorer(
        recall_score,
        pos_label=0,
        zero_division=0,
    ),
    "f1_benign": make_scorer(
        f1_score,
        pos_label=0,
        zero_division=0,
    ),
    "f1_macro": make_scorer(
        f1_score,
        average="macro",
        labels=[0, 1],
        zero_division=0,
    ),
    "accuracy": "accuracy",
    "balanced_accuracy": "balanced_accuracy",
}

In [9]:
# carregamento de origem de treinamento
def load_training_data(dataset_names):
    columns = feature_columns + ["label_binary", "dataset_name"]

    dataframes = []

    for dataset_name in dataset_names:
        #columns=columns (pandas pega apenas colunas necessárias)
        df = pd.read_parquet( DATA_DIR / f"{dataset_name}_train.parquet", columns=columns)
        dataframes.append(df)

    training_df = pd.concat( dataframes, ignore_index=True)

    features = training_df[feature_columns]
    # training_df["label_binary"].eq("ATTACK").astype("int8") -> 1 se equal, 0 se não, ou seja, 1 ataque, 0 benigno
    target = (training_df["label_binary"].eq("ATTACK").astype("int8"))
    # Nos treinos combinados, cada fold preserva simultaneamente a origem e a classe.
    stratification_labels = (
        training_df["dataset_name"].astype("string")
        + "__"
        + target.astype("string")
    )
    cv_splits = list(cross_validation.split(features, stratification_labels))

    return features, target, cv_splits

In [10]:
##treino, validação e save
def serialize_params(params):
    return json.dumps(
        params,
        sort_keys=True,
        default=lambda value: value.item(),
    )


def resolve_candidate_params(model_config, candidate_params):
    # Registra a configuração completa e reproduzível do estimador.
    effective_params = {
        f"classifier__{name}": value
        for name, value in model_config["estimator"].get_params(deep=False).items()
    }
    # Alguns wrappers expõem None, embora a biblioteca use outro valor efetivo.
    effective_params.update(model_config["baseline_params"])
    effective_params.update(candidate_params)
    return effective_params


def build_candidate_grid(model_config):
    # O primeiro candidato é exatamente o baseline, sem sobrescrever parâmetros.
    baseline_fingerprint = serialize_params(
        resolve_candidate_params(model_config, {})
    )
    seen = {baseline_fingerprint}
    random_candidates = []

    # A amostragem excedente permite descartar uma eventual repetição do baseline
    # ou de outro candidato sem reduzir as 12 configurações aleatórias.
    sampled_candidates = ParameterSampler(
        model_config["param_distributions"],
        n_iter=N_RANDOM_CANDIDATES * 20,
        random_state=RANDOM_STATE,
    )

    for candidate_params in sampled_candidates:
        fingerprint = serialize_params(
            resolve_candidate_params(model_config, candidate_params)
        )
        if fingerprint in seen:
            continue

        seen.add(fingerprint)
        random_candidates.append(candidate_params)
        if len(random_candidates) == N_RANDOM_CANDIDATES:
            break

    if len(random_candidates) != N_RANDOM_CANDIDATES:
        raise RuntimeError(
            "Não foi possível gerar 12 candidatos aleatórios únicos."
        )

    # RandomizedSearchCV recebe somente estes candidatos já definidos. Cada valor
    # fica em uma lista unitária para representar uma configuração completa.
    return [{}] + [
        {name: [value] for name, value in params.items()}
        for params in random_candidates
    ]


def train_and_select_model(model_name, training_name, dataset_names):
    features, target, cv_splits = load_training_data(dataset_names)
    model_config = MODEL_CONFIGS[model_name]
    model_dir = MODEL_DIR / model_name
    results_dir = RESULTS_DIR / model_name

    model_dir.mkdir(parents=True, exist_ok=True)
    results_dir.mkdir(parents=True, exist_ok=True)

    candidate_grid = build_candidate_grid(model_config)

    search = RandomizedSearchCV(
        estimator=build_pipeline(model_config["estimator"]),
        param_distributions=candidate_grid,
        # Como o espaço finito contém exatamente 13 configurações e n_iter=13,
        # os 12 sorteios e o baseline são obrigatoriamente avaliados uma vez.
        n_iter=len(candidate_grid),
        scoring=scoring,
        # O refit treina novamente o pipeline com todo o conjunto de treino,
        # usando os melhores hiperparâmetros encontrados segundo o F1 macro.
        refit="f1_macro",
        cv=cv_splits,
        n_jobs=N_JOBS,
        random_state=RANDOM_STATE,
        verbose=1,
        error_score="raise",
        return_train_score=False,
    )

    start = perf_counter()
    search.fit(features, target)
    elapsed_seconds = perf_counter() - start
    elapsed_minutes = elapsed_seconds / 60

    cv_results = pd.DataFrame(search.cv_results_)

    #informações da busca
    candidate_columns = ["params"]
    for metric in scoring:
        candidate_columns.extend(
            f"split{fold}_test_{metric}" for fold in range(N_SPLITS)
        )
        candidate_columns.extend([
            f"mean_test_{metric}",
            f"std_test_{metric}",
            f"rank_test_{metric}",
        ])
    candidate_columns.extend([
        "mean_fit_time",
        "std_fit_time",
        "mean_score_time",
        "std_score_time",
    ])

    candidate_results = cv_results[candidate_columns].copy()
    candidate_results.insert(0, "candidate_id", range(1, len(candidate_results) + 1))
    candidate_results.insert(
        1,
        "candidate_type",
        candidate_results["params"].map(
            lambda params: "baseline" if not params else "random"
        ),
    )
    candidate_results["params"] = candidate_results["params"].map(
        lambda params: serialize_params(
            resolve_candidate_params(model_config, params)
        )
    )
    candidate_results = candidate_results.sort_values("rank_test_f1_macro")
    candidate_results.insert(0, "random_state", RANDOM_STATE)
    candidate_results.insert(0, "n_splits", N_SPLITS)
    candidate_results.insert(0, "n_candidates", len(cv_results))
    candidate_results.insert(0, "n_random_candidates", N_RANDOM_CANDIDATES)
    candidate_results.insert(0, "training_rows", len(features))
    candidate_results.insert(0, "training_source", training_name)
    candidate_results.insert(0, "search_method", SEARCH_METHOD)
    candidate_results.insert(0, "model", model_name)

    print(f"resultados dos hiperparâmetros: {model_name} - {training_name}")

    #todas as colunas de informações definidas
    display(candidate_results)

    candidate_results.to_csv(
        results_dir / f"{training_name}_candidates.csv",
        index=False,
    )

    model_path = model_dir / f"{training_name}.joblib"
    # Salva o pipeline vencedor, já reajustado com todos os dados de treinamento.
    joblib.dump(
        search.best_estimator_,
        model_path,
        compress=3,
    )

    best_result = cv_results.loc[search.best_index_]
    best_candidate_type = (
        "baseline" if not search.best_params_ else "random"
    )
    best_effective_params = resolve_candidate_params(
        model_config,
        search.best_params_,
    )

    result = {
        "model": model_name,
        "search_method": SEARCH_METHOD,
        "training_source": training_name,
        "training_rows": len(features),
        "n_random_candidates": N_RANDOM_CANDIDATES,
        "n_splits": N_SPLITS,
        "random_state": RANDOM_STATE,
        "n_candidates": len(cv_results),
        "best_candidate_type": best_candidate_type,
        "selection_metric": "f1_macro",
        "params": serialize_params(best_effective_params),
        "elapsed_seconds": elapsed_seconds,
        "elapsed_minutes": elapsed_minutes,
        "refit_time_seconds": search.refit_time_,
        "model_size_mb": (
                model_path.stat().st_size / 1024 ** 2
        ),
        "model_file": model_path.name,
    }

    for metric in scoring:
        result[f"{metric}_mean"] = best_result[f"mean_test_{metric}"]
        result[f"{metric}_std"] = best_result[f"std_test_{metric}"]

    return result

In [11]:
# exec
all_results = []

for model_name in MODELS_TO_RUN:
    model_results = []

    for training_name, dataset_names in TRAINING_CONFIGS.items():
        print(f"modelo: {model_name}\n origem do treinamento: {training_name}")

        result = train_and_select_model(
            model_name,
            training_name,
            dataset_names,
        )

        model_results.append(result)
        all_results.append(result)

    results_df = pd.DataFrame(model_results)
    results_df.to_csv(
        RESULTS_DIR / model_name / "summary.csv",
        index=False,
    )

all_results_df = pd.DataFrame(all_results)
display(all_results_df)

modelo: decision_tree
 origem do treinamento: cicids2017
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: decision_tree - cicids2017

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
0,decision_tree,randomized_search,cicids2017,235490,12,13,5,1,1,baseline,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.982275,0.979886,0.982771,0.982841,0.980332,0.981621,0.001258,1,0.988428,0.987897,0.987049,0.985032,0.989490,0.987579,0.001500,9,0.985342,0.983875,0.984905,0.983935,0.984890,0.984589,0.000582,1,0.997103,0.996968,0.996759,0.996256,0.997366,0.996890,0.000374,9,0.995541,0.994931,0.995674,0.995700,0.995037,0.995377,0.000327,1,0.996321,0.995949,0.996216,0.995978,0.996200,0.996133,0.000145,1,0.990831,0.989912,0.990561,0.989957,0.990545,0.990361,0.000363,1,0.994119,0.993524,0.993949,0.993567,0.993928,0.993817,0.000232,1,0.991984,0.991414,0.991361,0.990366,0.992264,0.991478,0.000652,6,3.085615,0.329186,0.110409,0.018605
11,decision_tree,randomized_search,cicids2017,235490,12,13,5,1,12,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.980514,0.978607,0.982280,0.979493,0.977034,0.979586,0.001766,3,0.988321,0.990763,0.988641,0.988747,0.989066,0.989108,0.000861,5,0.984402,0.984648,0.985451,0.984098,0.983013,0.984322,0.000794,2,0.997075,0.997684,0.997156,0.997180,0.997258,0.997270,0.000215,5,0.995090,0.994586,0.995541,0.994825,0.994188,0.994846,0.000457,3,0.996081,0.996132,0.996348,0.996001,0.995720,0.996057,0.000204,2,0.990242,0.990390,0.990899,0.990050,0.989367,0.990190,0.000499,2,0.993736,0.993821,0.994161,0.993609,0.993163,0.993698,0.000324,2,0.991706,0.992675,0.992091,0.991786,0.991627,0.991977,0.000383,5,2.839196,0.208980,0.067943,0.008208
7,decision_tree,randomized_search,cicids2017,235490,12,13,5,1,8,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 30, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 19, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.972142,0.970123,0.974495,0.972847,0.968959,0.971713,0.001966,8,0.996603,0.996284,0.997771,0.996497,0.997452,0.996921,0.000582,1,0.984220,0.983030,0.985995,0.984530,0.982999,0.984155,0.001108,3,0.999145,0.999065,0.999439,0.999119,0.999358,0.999225,0.000146,1,0.992861,0.992330,0.993471,0.993046,0.992011,0.992744,0.000518,8,0.995993,0.995686,0.996446,0.996073,0.995671,0.995974,0.000286,4,0.990107,0.989358,0.991221,0.990302,0.989335,0.990064,0.000697,3,0.993609,0.993121,0.994331,0.993736,0.993099,0.993579,0.000454,4,0.994732,0.994307,0.995621,0.994772,0.994732,0.994833,0.000429,1,3.588828,0.334001,0.114982,0.026875
5,decision_tree,randomized_search,cicids2017,235490,12,13,5,1,6,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.982149,0.979014,0.984413,0.981096,0.976208,0.980576,0.002792,2,0.987154,0.990551,0.985563,0.986200,0.988747,0.987643,0.001807,8,0.984645,0.984749,0.984988,0.983641,0.982438,0.984092,0.000946,4,0.996785,0.997631,0.996389,0.996545,0.997178,0.996906,0.000450,8,0.995515,0.994692,0.996099,0.995249,0.993975,0.995106,0.000724,2,0.996149,0.996159,0.996244,0.995897,0.995574,0.996005,0.000245,3,0.990397,0.990454,0.990616,0.989769,0.989006,0.990048,0.000595,4,0.993843,0.993864,0.993991,0.993439,0.992930,0.993613,0.000389,3,0.991334,0.992622,0.990831,0.990724,0.991361,0.991374,0.000675,7,2.936998,0.245217,0.111510,0.014681
4,decision_tree,randomized_search,cicids2017,235490,12,13,5,1,5,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 20, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.980105,0.978571,0.982434,0.978932,0.976517,0.979312,0.001943,4,0.988534,0.989065,0.985563,0.986518,0.988854,0.987707,0.001404,7,0.984301,0.983790,0.983996,0.982710,0.982647,0.983489,0.000682,5,0.997128,0.997259,0.996388,0.996623,0.997204,0.996920,0.000349,7,0.994984,0.994586,0.995594,0.994692,0.994055,0.994782,0.000505,4,0.996055,0.995921,0.995991,0.995656,0.995627,0.995850,0.000175,5,0.990178,0.989855,0.989993,0.989183,0.989137,0.989669,0.000428,5,0.993694,0.993482,0.993588,0.993057,0.993015,0.993367,0.000279,5,0.991759,0.991825,0.990578,0.990605,0.991454,0.991244,0.000547,8,2.873181,0.173693,0.093741,0.008912
8,decision_tree,randomized_search,cicids2017,235490,12,13,5,1,9,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 15, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.968786,0.969286,0.973643,0.972962,0.973999,0.971735,0.002235,7,0.995116,0.995116,0.996072,0.993206,0.994161,0.994734,0.000974,3,0.981774,0.982032,0.984730,0.982980,0.983977,0.983098,0.001126,6,0.998771,0.998771,0.999012,0.998293,0.998533,0.998676,0.000244,3,0.991985,0.992118,0.993259,0.993099,0.993365,0.992765,0.000590,7,0.995366,0.995433,0.996127,0.995689,0.995942,0.995712,0.000291,6,0.988570,0.988732,0.990429,0.989334,0.989959,0.989405,0.000708,6,0.992611,0.992717,0.993821,0.993121,0.993524,0.993159,0.000462,6,0.993551,0.993617,0.994665,0.993153,0.993763,0.993750,0.000500,2,4.017540,0.408582,0.120083,0.041261
2,decision_tree,randomized_search,cicids2017,235490,12,13,5,1,3,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 18, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.966323,0.964638,0.968447,0.974274,0.963373,0.967411,0.003830,9,0.996178,0.996284,0.997028,0.992994,0.996815,0.995860,0.001468,2,0.981024,0.980206,0.982530,0.983545,0.979809,0.981422,0.001412,7,0.999037,0.999063,0.999251,0.998240,0.999197,0.998958,0.000368,2,0.991321,0.990870,0.991879,0.993444,0.990525,0.991608,0.001024,9,0.995164,0.994950,0.995551,0.995836,0.994842,0.995269,0.000373,7,0.988094,0.987578,0.989040,0.989690,0.987326,0.988346,0.000893,7,0.992293,0.991953,0.992908,0.993354,0.991783,0.992458,0.000591,7,0.993750,0.993577,0.994453,0.993219,0.993670,0.993734,0.000403,3,3.703637,0.316024,0.109973,0.020814
10,decision_tree,randomized_search,cicids2017,235490,12,13,5,1,11,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.977400,0.976458,0.979546,0.975973,0.975438,0.976963,0.001444,5,0.982588,0.986410,0.981210,0.987473,0.986518,0.984840,0.002468,10,0.979987,0.981409,0.980378,0.981690,0.980947,0.980882,0.000631,8,0.995642,0.996594,0.995300,0.996859,0.996620,0.996203,0.000614,10,0.994320,0.994055,0.994878,0.993922,0.993789,0.994193,0.000385,5,0.994981,0.995323,0.995089,0.995388,0.995203,0.995197,0.000149,8,0.987484,0.988366,0.987733,0.988539,0.988075,0.988039,0.000390,8,0.991974,0.992526,0.992144,0.992632,0.992335,0.992322,0.000241,8,0.988454,0.990233,0.988044,0.990698,0.990154,0.989517,0.001059,9,2.629282,0.399986,0.108023,0.028918
3,decision_tree,randomized_search,cicids2017,235490,12,13,5,1,4,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 15, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.956380,0.971939,0.958359,0.961112,0.970732,0.963704,0.006421,10,0.996284,0.992887,0.994374,0.994374,0.992887,0.994161,0.001252,4,0.975924,0.982301,0.976034,0.977460,0.981685,0.978681,0.002765,9,0.999061,0.998212,0.998580,0.998581,0.998212,0.998529,0.000313,4,0.988641,0.992834,0.989198,0.989941,0.992516,0.990626,0.001726,10,0.993824,0.995516,0.993867,0.994242,0.995355,0.994561,0.000731,9,0.984874,0.988909,0.984951,0.985851,0.988520,0.986621,0.001748,9,0.990169,0.992845,0.990233,0.990828,0.992590,0.991333,0.001156,9,0.992462,0.992860,0.991786,0.992157,0.992701,0.992394,0.000385,4,3.222218,0.358290,0.099581,0.008149
6,decision_tree,randomized_search,cicids2017,235490,12,13,5,1,7,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 8, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 6, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.976769,0.974070,0.978430,0.972085,0.972088,0.974688,0.002540,6,0.973139,0.981102,0.972718,0.979618,0.979724,0.977260,0.003578,11,0.974951,0.977573,0.975566,0.975837,0.975891,0.975963,0.000871,10,0.993292,0.995267,0.993189,0.994894,0.994921,0.994313,0.000886,11,0.994214,0.993471,0.994639,0.992967,0.992967,0.993652,0.000673,6,0.993753,0.994368,0.993913,0.993930,0.993943,0.993981,0.000205,10,0.984352,0.985971,0.984739,0.984883,0.984917,0.984972,0.000538,10,0.990000,0.990997,0.990254,0.990297,0.990318,0.990373,0.000332,10,0.983677,0.987287,0.983678,0.986292,0.986345,0.985456,0.001494,11,2.151654,0.198908,0.118032,0.042149
1,decision_tree,randomized_search,cicids2017,235490,12,13,5,1,2,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 8, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 11, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.967826,0.951587,0.965095,0.950947,0.945398,0.956171,0.008716,11,0.980465,0.993311,0.986200,0.985775,0.994374,0.988025,0.005173,6,0.974105,0.972001,0.975533,0.968048,0.969267,0.971791,0.002821,11,0.995101,0.998309,0.996531,0.996411,0.998575,0.996985,0.001294,6,0.991852,0.987367,0.991082,0.987287,0.985641,0.988646,0.002397,11,0.993474,0.992808,0.993799,0.991828,0.992066,0.992795,0.000766,11,0.983789,0.982405,0.984666,0.979938,0.980667,0.982293,0.001793,11,0.989575,0.988556,0.990106,0.986985,0.987388,0.988522,0.001206,11,0.986159,0.990339,0.988641,0.986531,0.990008,0.988335,0.001726,10,2.810726,0.269495,0.106975,0.021296
12,decision_tree,randomized_search,cicids2017,235490,12,13,5,1,13,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 3, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 9, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.916145,0.921081,0.917747,0.919369,0.915406,0.917950,0.002078,12,0.917507,0.915702,0.916773,0.915074,0.912102,0.915432,0.001865,13,0.916826,0.918384,0.917260,0.917216,0.913751,0.916687,0.001557,12,0.979371,0.978958,0.979198,0.978792,0.978044,0.978873,0.000459,13,0.979007,0.980387,0.979458,0.979935,0.978927,0.979543,0.000555,12,0.979189,0.979672,0.979328,0.979363,0.978485,0.979207,0.000394,12,0.948007,0.949028,0.948294,0.948290,0.946118,0.947947,0.000975,12,0.966708,0.967451,0.966920,0.966963,0.965561,0.966720,0.000629,12,0.948257,0.948045,0.948115,0.947505,0.945514,0.947487,0.001019,13,0.956422,0.149628,0.085687,0.006445
9,decision_tree,randomized_search,cicids2017,235490,12,13,5,1,10,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 3, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 3, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.873850,0.875872,0.873810,0.874262,0.872777,0.874114,0.001006,13,0.947977,0.946173,0.945329,0.943312,0.943100,0.945178,0.001825,12,0.909406,0.909666,0.908164,0.907475,0.906577,0.908258,0.001162,13,0.986714,0.986269,0.986046,0.985542,0.985482,0.986010,0.000461,12,0.965790,0.966480,0.965869,0.966081,0.965630,0.965970,0.000294,13,0.976140,0.976274,0.975853,0.975714,0.975455,0.975887,0.000294,13,0.942773,0.942970,0.942008,0.941595,0.941016,0.942072,0.000727,13,0.962228,0.962419,0.961761,0.961527,0.961124,0.961812,0.000469,13,0.956884,0.956326,0.955599,0.954697,0.954365,0.955574,0.000950,12,1.284711,0.146758,0.115808,0.045654

modelo: decision_tree
 origem do treinamento: unsw_nb15
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: decision_tree - unsw_nb15

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
10,decision_tree,randomized_search,unsw_nb15,235490,12,13,5,1,11,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.944243,0.944786,0.941147,0.941354,0.942122,0.942730,0.001502,6,0.994267,0.995541,0.994798,0.993418,0.995329,0.994671,0.000767,5,0.968609,0.969500,0.967229,0.966686,0.967995,0.968004,0.000994,1,0.998548,0.998870,0.998681,0.998331,0.998815,0.998649,0.000194,5,0.985323,0.985456,0.984447,0.984527,0.984713,0.984893,0.000417,6,0.991891,0.992118,0.991513,0.991381,0.991714,0.991723,0.000263,1,0.980250,0.980809,0.979371,0.979033,0.979854,0.979864,0.000628,1,0.987112,0.987473,0.986517,0.986305,0.986836,0.986849,0.000416,1,0.989795,0.990499,0.989623,0.988973,0.990021,0.989782,0.000500,5,2.849159,0.478447,0.093570,0.011423
3,decision_tree,randomized_search,unsw_nb15,235490,12,13,5,1,4,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 15, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.941784,0.941071,0.936865,0.937961,0.938323,0.939201,0.001894,10,0.997877,0.998620,0.998726,0.998301,0.998089,0.998323,0.000318,1,0.969019,0.968991,0.966807,0.967191,0.967284,0.967859,0.000950,2,0.999461,0.999650,0.999676,0.999568,0.999515,0.999574,0.000081,1,0.984580,0.984368,0.983173,0.983492,0.983598,0.983842,0.000539,10,0.991965,0.991950,0.991356,0.991465,0.991492,0.991646,0.000259,2,0.980492,0.980471,0.979082,0.979328,0.979388,0.979752,0.000604,2,0.987239,0.987218,0.986284,0.986454,0.986496,0.986738,0.000407,2,0.991228,0.991494,0.990950,0.990897,0.990844,0.991082,0.000245,1,3.542330,1.143072,0.138245,0.079517
2,decision_tree,randomized_search,unsw_nb15,235490,12,13,5,1,3,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 18, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.943784,0.943444,0.938256,0.940710,0.940215,0.941282,0.002076,7,0.994585,0.995329,0.996921,0.995435,0.995011,0.995456,0.000790,4,0.968519,0.968692,0.966699,0.967299,0.966837,0.967609,0.000839,3,0.998628,0.998816,0.999218,0.998842,0.998734,0.998848,0.000200,4,0.985191,0.985085,0.983598,0.984314,0.984182,0.984474,0.000594,8,0.991864,0.991903,0.991346,0.991525,0.991405,0.991609,0.000232,3,0.980191,0.980297,0.979023,0.979412,0.979121,0.979609,0.000535,3,0.987070,0.987133,0.986263,0.986539,0.986348,0.986670,0.000364,3,0.989888,0.990207,0.990260,0.989875,0.989596,0.989965,0.000243,4,4.149517,1.830329,0.116883,0.044635
7,decision_tree,randomized_search,unsw_nb15,235490,12,13,5,1,8,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 30, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 19, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.941950,0.941690,0.937344,0.938888,0.936995,0.939374,0.002098,9,0.995753,0.996178,0.997346,0.996497,0.997771,0.996709,0.000745,3,0.968105,0.968168,0.966415,0.966835,0.966428,0.967190,0.000787,4,0.998923,0.999031,0.999326,0.999111,0.999433,0.999165,0.000188,3,0.984660,0.984580,0.983332,0.983784,0.983226,0.983917,0.000605,9,0.991740,0.991753,0.991265,0.991388,0.991264,0.991482,0.000221,4,0.979923,0.979960,0.978840,0.979111,0.978846,0.979336,0.000504,4,0.986878,0.986900,0.986135,0.986326,0.986135,0.986475,0.000345,4,0.990207,0.990379,0.990339,0.990140,0.990498,0.990313,0.000127,3,3.778197,0.715337,0.120127,0.044207
1,decision_tree,randomized_search,unsw_nb15,235490,12,13,5,1,2,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 8, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 11, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.940776,0.939073,0.936005,0.937806,0.936484,0.938029,0.001742,11,0.996709,0.998195,0.996815,0.997240,0.997028,0.997197,0.000531,2,0.967935,0.967732,0.965453,0.966610,0.965808,0.966708,0.000995,5,0.999165,0.999542,0.999191,0.999299,0.999245,0.999288,0.000135,2,0.984315,0.983811,0.982961,0.983465,0.983094,0.983529,0.000493,11,0.991684,0.991614,0.991009,0.991319,0.991103,0.991346,0.000268,5,0.979810,0.979673,0.978231,0.978964,0.978456,0.979027,0.000631,5,0.986793,0.986687,0.985732,0.986220,0.985881,0.986263,0.000422,5,0.990512,0.991003,0.989888,0.990353,0.990061,0.990363,0.000387,2,4.317346,1.534461,0.108808,0.026771
11,decision_tree,randomized_search,unsw_nb15,235490,12,13,5,1,12,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.946430,0.947486,0.944614,0.945261,0.945285,0.945815,0.001020,4,0.986623,0.988428,0.988535,0.982590,0.988535,0.986942,0.002294,8,0.966109,0.967524,0.966075,0.963564,0.966426,0.965940,0.001299,6,0.996620,0.997076,0.997100,0.995604,0.997100,0.996700,0.000578,8,0.986040,0.986305,0.985509,0.985774,0.985695,0.985865,0.000279,4,0.991302,0.991661,0.991270,0.990665,0.991365,0.991253,0.000325,6,0.978705,0.979593,0.978673,0.977115,0.978895,0.978596,0.000812,6,0.986157,0.986730,0.986114,0.985137,0.986263,0.986080,0.000520,6,0.986331,0.987367,0.987022,0.984182,0.987115,0.986403,0.001162,8,3.070317,0.353983,0.069289,0.017266
8,decision_tree,randomized_search,unsw_nb15,235490,12,13,5,1,9,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 15, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.945515,0.945182,0.941789,0.941461,0.941378,0.943065,0.001872,5,0.989383,0.990339,0.989278,0.990234,0.990446,0.989936,0.000500,6,0.966952,0.967234,0.964950,0.965232,0.965289,0.965931,0.000960,7,0.997315,0.997556,0.997285,0.997526,0.997580,0.997452,0.000126,6,0.985748,0.985642,0.984713,0.984606,0.984580,0.985058,0.000523,5,0.991498,0.991563,0.990959,0.991024,0.991037,0.991216,0.000259,7,0.979225,0.979398,0.977954,0.978128,0.978163,0.978574,0.000609,7,0.986475,0.986581,0.985626,0.985732,0.985753,0.986033,0.000408,7,0.987566,0.987990,0.986995,0.987420,0.987513,0.987497,0.000318,6,3.387472,0.133678,0.100533,0.011257
6,decision_tree,randomized_search,unsw_nb15,235490,12,13,5,1,7,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 8, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 6, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.943022,0.943127,0.940132,0.939911,0.939651,0.941169,0.001564,8,0.989277,0.987684,0.995223,0.988004,0.988429,0.989724,0.002801,7,0.965596,0.964891,0.966894,0.963358,0.963423,0.964832,0.001341,8,0.997286,0.996885,0.998788,0.996962,0.997069,0.997398,0.000708,7,0.985058,0.985111,0.984155,0.984208,0.984129,0.984532,0.000452,7,0.991134,0.990963,0.991418,0.990544,0.990557,0.990923,0.000337,8,0.978365,0.977927,0.979156,0.976951,0.976990,0.977878,0.000839,8,0.985902,0.985626,0.986369,0.984968,0.984989,0.985571,0.000539,8,0.987167,0.986398,0.989689,0.986106,0.986279,0.987128,0.001331,7,2.881194,1.185979,0.111998,0.013396
4,decision_tree,randomized_search,unsw_nb15,235490,12,13,5,1,5,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 20, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.948855,0.949423,0.946552,0.945566,0.947757,0.947631,0.001425,3,0.980890,0.978554,0.977601,0.979193,0.980255,0.979299,0.001174,9,0.964606,0.963768,0.961826,0.962086,0.963732,0.963204,0.001069,9,0.995182,0.994597,0.994354,0.994751,0.995021,0.994781,0.000295,9,0.986783,0.986969,0.986199,0.985907,0.986491,0.986470,0.000384,3,0.990965,0.990768,0.990259,0.990309,0.990737,0.990608,0.000276,9,0.977786,0.977268,0.976043,0.976198,0.977235,0.976906,0.000672,9,0.985604,0.985286,0.984479,0.984564,0.985244,0.985035,0.000439,9,0.983836,0.982761,0.981900,0.982550,0.983373,0.982884,0.000669,9,4.536858,2.039097,0.138003,0.060861
5,decision_tree,randomized_search,unsw_nb15,235490,12,13,5,1,6,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.950299,0.950320,0.947944,0.947303,0.947774,0.948728,0.001308,2,0.978448,0.978872,0.976221,0.971338,0.978662,0.976708,0.002850,10,0.964168,0.964385,0.961874,0.959170,0.962971,0.962514,0.001899,10,0.994572,0.994679,0.994010,0.992788,0.994621,0.994134,0.000714,10,0.987208,0.987208,0.986597,0.986491,0.986517,0.986804,0.000331,2,0.990876,0.990929,0.990290,0.989630,0.990553,0.990455,0.000473,10,0.977522,0.977657,0.976082,0.974400,0.976762,0.976484,0.001186,10,0.985456,0.985541,0.984522,0.983460,0.984946,0.984785,0.000758,10,0.982828,0.983040,0.981409,0.978914,0.982590,0.981756,0.001529,10,2.761539,0.101694,0.099501,0.009940
0,decision_tree,randomized_search,unsw_nb15,235490,12,13,5,1,1,baseline,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.951099,0.952986,0.949668,0.950269,0.950524,0.950909,0.001135,1,0.960187,0.955515,0.957431,0.955414,0.952442,0.956198,0.002554,12,0.955621,0.954249,0.953534,0.952835,0.951482,0.953544,0.001383,11,0.990024,0.988872,0.989335,0.988838,0.988104,0.989035,0.000632,12,0.987659,0.988216,0.987314,0.987499,0.987605,0.987659,0.000303,1,0.988840,0.988544,0.988323,0.988168,0.987855,0.988346,0.000334,11,0.972231,0.971397,0.970929,0.970501,0.969668,0.970945,0.000858,11,0.982165,0.981677,0.981337,0.981082,0.980572,0.981367,0.000538,11,0.973923,0.971866,0.972372,0.971457,0.970024,0.971928,0.001267,11,4.047050,0.954167,0.104630,0.013694
12,decision_tree,randomized_search,unsw_nb15,235490,12,13,5,1,13,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 3, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 9, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.851349,0.853941,0.845585,0.851342,0.850480,0.850539,0.002736,12,0.931521,0.930460,0.934183,0.932590,0.931104,0.931972,0.001305,13,0.889632,0.890560,0.887678,0.890116,0.888968,0.889391,0.001006,12,0.982469,0.982218,0.983102,0.982735,0.982357,0.982576,0.000313,13,0.959341,0.960217,0.957349,0.959287,0.959074,0.959053,0.000938,12,0.970767,0.971093,0.970055,0.970869,0.970576,0.970672,0.000351,12,0.930200,0.930826,0.928867,0.930493,0.929772,0.930031,0.000678,12,0.953777,0.954266,0.952716,0.953947,0.953480,0.953637,0.000526,12,0.945431,0.945338,0.945766,0.945938,0.945089,0.945513,0.000304,13,1.034868,0.294368,0.084177,0.013291
9,decision_tree,randomized_search,unsw_nb15,235490,12,13,5,1,10,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 3, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 3, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.786126,0.791627,0.782883,0.788548,0.785230,0.786883,0.002986,13,0.970910,0.971653,0.974947,0.970701,0.970701,0.971782,0.001621,11,0.868801,0.872450,0.868422,0.870194,0.868170,0.869607,0.001584,13,0.992274,0.992487,0.993327,0.992226,0.992215,0.992506,0.000422,11,0.933969,0.936065,0.932401,0.934922,0.933622,0.934196,0.001235,13,0.962239,0.963451,0.961900,0.962722,0.962027,0.962468,0.000566,13,0.915520,0.917950,0.915161,0.916458,0.915098,0.916038,0.001073,13,0.941356,0.943182,0.940910,0.942078,0.941038,0.941713,0.000839,13,0.952439,0.953859,0.953674,0.952811,0.952161,0.952989,0.000670,12,1.794474,0.541962,0.123842,0.040224

modelo: decision_tree
 origem do treinamento: iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: decision_tree - iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
6,decision_tree,randomized_search,iot23,235490,12,13,5,1,7,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 8, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 6, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.999359,0.999465,0.999358,0.999680,0.999786,0.999530,0.000174,1,0.993842,0.992037,0.992144,0.994480,0.993524,0.993206,0.000961,12,0.996593,0.995737,0.995738,0.997073,0.996646,0.996358,0.000533,1,0.998463,0.998013,0.998040,0.998622,0.998384,0.998304,0.000240,12,0.999841,0.999867,0.999841,0.999920,0.999947,0.999883,0.000043,1,0.999151,0.998939,0.998939,0.999271,0.999165,0.999093,0.000132,1,0.997872,0.997338,0.997339,0.998172,0.997905,0.997725,0.000332,1,0.998641,0.998301,0.998301,0.998832,0.998662,0.998548,0.000212,1,0.996841,0.995952,0.995993,0.997200,0.996736,0.996544,0.000492,9,1.247426,0.312080,0.124842,0.034041
10,decision_tree,randomized_search,iot23,235490,12,13,5,1,11,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.999253,0.998931,0.999465,0.999680,0.999466,0.999359,0.000253,2,0.993842,0.992250,0.992357,0.994480,0.993843,0.993354,0.000890,9,0.996540,0.995579,0.995898,0.997073,0.996647,0.996347,0.000538,2,0.998463,0.998066,0.998092,0.998622,0.998463,0.998341,0.000222,9,0.999814,0.999735,0.999867,0.999920,0.999867,0.999841,0.000063,2,0.999138,0.998900,0.998979,0.999271,0.999165,0.999090,0.000133,2,0.997839,0.997239,0.997439,0.998172,0.997906,0.997719,0.000336,2,0.998620,0.998238,0.998365,0.998832,0.998662,0.998543,0.000214,2,0.996828,0.995992,0.996112,0.997200,0.996855,0.996598,0.000466,8,1.541126,0.375064,0.099866,0.006601
11,decision_tree,randomized_search,iot23,235490,12,13,5,1,12,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.999573,0.998931,0.999252,0.999467,0.999359,0.999316,0.000220,3,0.993736,0.992356,0.992357,0.994798,0.993631,0.993376,0.000927,8,0.996646,0.995633,0.995792,0.997127,0.996487,0.996337,0.000554,3,0.998436,0.998092,0.998092,0.998701,0.998410,0.998346,0.000231,8,0.999894,0.999735,0.999814,0.999867,0.999841,0.999830,0.000055,3,0.999165,0.998913,0.998953,0.999284,0.999125,0.999088,0.000138,3,0.997905,0.997273,0.997372,0.998205,0.997806,0.997712,0.000346,3,0.998662,0.998259,0.998323,0.998853,0.998599,0.998539,0.000220,3,0.996815,0.996045,0.996085,0.997333,0.996736,0.996603,0.000485,7,1.163282,0.086030,0.107338,0.011558
0,decision_tree,randomized_search,iot23,235490,12,13,5,1,1,baseline,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.998827,0.998505,0.999145,0.999041,0.998826,0.998869,0.000220,6,0.994055,0.992568,0.992781,0.995011,0.993843,0.993652,0.000892,7,0.996435,0.995528,0.995953,0.997022,0.996328,0.996253,0.000499,4,0.998516,0.998145,0.998198,0.998754,0.998463,0.998415,0.000222,7,0.999708,0.999628,0.999788,0.999761,0.999708,0.999719,0.000055,6,0.999111,0.998886,0.998992,0.999257,0.999085,0.999066,0.000124,4,0.997773,0.997207,0.997473,0.998139,0.997707,0.997660,0.000312,4,0.998577,0.998216,0.998386,0.998811,0.998535,0.998505,0.000199,4,0.996881,0.996098,0.996284,0.997386,0.996775,0.996685,0.000457,6,1.615945,0.316046,0.136411,0.040112
5,decision_tree,randomized_search,iot23,235490,12,13,5,1,6,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.999253,0.999358,0.999145,0.999360,0.998933,0.999210,0.000160,4,0.993630,0.992356,0.992038,0.994586,0.993524,0.993227,0.000924,10,0.996433,0.995845,0.995579,0.996967,0.996221,0.996209,0.000481,5,0.998410,0.998092,0.998013,0.998648,0.998383,0.998309,0.000230,10,0.999814,0.999841,0.999788,0.999841,0.999735,0.999804,0.000040,4,0.999112,0.998966,0.998900,0.999244,0.999058,0.999056,0.000119,5,0.997772,0.997405,0.997239,0.998106,0.997640,0.997632,0.000300,5,0.998577,0.998344,0.998238,0.998790,0.998493,0.998488,0.000191,5,0.996722,0.996098,0.995913,0.997213,0.996630,0.996515,0.000465,10,1.574815,0.409883,0.123432,0.016735
4,decision_tree,randomized_search,iot23,235490,12,13,5,1,5,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 20, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.999253,0.999145,0.999145,0.999147,0.998720,0.999082,0.000186,5,0.993524,0.992356,0.992038,0.994586,0.993631,0.993227,0.000924,11,0.996380,0.995739,0.995579,0.996861,0.996169,0.996145,0.000459,6,0.998383,0.998092,0.998013,0.998648,0.998410,0.998309,0.000230,11,0.999814,0.999788,0.999788,0.999788,0.999682,0.999772,0.000046,5,0.999098,0.998939,0.998900,0.999217,0.999045,0.999040,0.000114,6,0.997739,0.997339,0.997239,0.998039,0.997607,0.997593,0.000287,6,0.998556,0.998301,0.998238,0.998747,0.998471,0.998463,0.000182,6,0.996669,0.996072,0.995913,0.997187,0.996656,0.996499,0.000459,11,1.405619,0.481243,0.119293,0.023109
3,decision_tree,randomized_search,iot23,235490,12,13,5,1,4,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 15, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.988333,0.986362,0.988319,0.987606,0.985439,0.987212,0.001141,8,0.998301,0.998195,0.997028,0.998195,0.998620,0.998068,0.000543,5,0.993292,0.992243,0.992654,0.992873,0.991986,0.992610,0.000461,7,0.999574,0.999547,0.999255,0.999548,0.999654,0.999516,0.000136,4,0.997054,0.996550,0.997054,0.996868,0.996311,0.996767,0.000293,8,0.998313,0.998046,0.998153,0.998206,0.997980,0.998140,0.000117,7,0.995802,0.995145,0.995404,0.995539,0.994983,0.995375,0.000289,7,0.997303,0.996879,0.997049,0.997134,0.996773,0.997027,0.000187,7,0.997678,0.997372,0.997041,0.997532,0.997465,0.997418,0.000213,2,1.330728,0.105537,0.109881,0.019852
1,decision_tree,randomized_search,iot23,235490,12,13,5,1,2,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 8, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 11, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.987400,0.986050,0.988114,0.988124,0.985128,0.986963,0.001189,9,0.998407,0.998089,0.997240,0.998089,0.998514,0.998068,0.000447,4,0.992873,0.992033,0.992656,0.993082,0.991776,0.992484,0.000499,8,0.999601,0.999521,0.999308,0.999521,0.999627,0.999516,0.000112,5,0.996815,0.996470,0.997001,0.997001,0.996231,0.996704,0.000306,9,0.998206,0.997993,0.998153,0.998259,0.997926,0.998108,0.000127,8,0.995540,0.995013,0.995405,0.995670,0.994851,0.995296,0.000313,8,0.997134,0.996794,0.997049,0.997219,0.996688,0.996977,0.000203,8,0.997611,0.997280,0.997120,0.997545,0.997373,0.997386,0.000178,4,2.033249,0.655056,0.145873,0.055075
8,decision_tree,randomized_search,iot23,235490,12,13,5,1,9,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 15, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.987612,0.985842,0.987491,0.986781,0.985957,0.986736,0.000741,11,0.998726,0.997983,0.997240,0.998514,0.998726,0.998238,0.000568,1,0.993138,0.991875,0.992341,0.992613,0.992300,0.992453,0.000416,9,0.999681,0.999494,0.999308,0.999627,0.999680,0.999558,0.000142,1,0.996868,0.996417,0.996842,0.996656,0.996444,0.996645,0.000190,11,0.998272,0.997953,0.998073,0.998139,0.998059,0.998100,0.000105,9,0.995705,0.994914,0.995207,0.995376,0.995180,0.995277,0.000260,9,0.997240,0.996730,0.996921,0.997027,0.996900,0.996964,0.000168,9,0.997797,0.997200,0.997041,0.997585,0.997585,0.997442,0.000278,1,2.134007,0.368542,0.125047,0.030664
2,decision_tree,randomized_search,iot23,235490,12,13,5,1,3,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 18, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.987609,0.985945,0.987902,0.986678,0.985854,0.986798,0.000838,10,0.998514,0.997983,0.996921,0.998514,0.998726,0.998132,0.000653,3,0.993031,0.991927,0.992391,0.992561,0.992248,0.992432,0.000365,10,0.999627,0.999494,0.999229,0.999627,0.999680,0.999532,0.000164,2,0.996868,0.996444,0.996948,0.996629,0.996417,0.996661,0.000216,10,0.998246,0.997967,0.998087,0.998126,0.998046,0.998094,0.000092,10,0.995639,0.994947,0.995239,0.995343,0.995147,0.995263,0.000229,10,0.997197,0.996751,0.996943,0.997006,0.996879,0.996955,0.000147,10,0.997691,0.997213,0.996935,0.997572,0.997572,0.997396,0.000281,3,1.954426,0.767976,0.139509,0.072124
7,decision_tree,randomized_search,iot23,235490,12,13,5,1,8,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 30, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 19, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.987400,0.985226,0.987591,0.986882,0.983586,0.986137,0.001523,12,0.998407,0.998301,0.996921,0.998301,0.998726,0.998132,0.000625,2,0.992873,0.991721,0.992234,0.992559,0.991098,0.992097,0.000628,11,0.999601,0.999574,0.999228,0.999574,0.999680,0.999532,0.000156,3,0.996815,0.996258,0.996868,0.996682,0.995833,0.996491,0.000393,12,0.998206,0.997913,0.998047,0.998126,0.997753,0.998009,0.000160,11,0.995540,0.994817,0.995141,0.995343,0.994426,0.995053,0.000394,11,0.997134,0.996667,0.996879,0.997006,0.996412,0.996819,0.000256,11,0.997611,0.997280,0.996895,0.997492,0.997280,0.997311,0.000244,5,1.649735,0.087349,0.208491,0.125401
12,decision_tree,randomized_search,iot23,235490,12,13,5,1,13,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 3, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 9, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.991782,0.991774,0.988946,0.991056,0.993172,0.991346,0.001382,7,0.986623,0.985561,0.987686,0.988110,0.988217,0.987239,0.001011,13,0.989196,0.988658,0.988315,0.989581,0.990688,0.989288,0.000824,12,0.996660,0.996396,0.996922,0.997030,0.997058,0.996813,0.000251,13,0.997956,0.997956,0.997240,0.997771,0.998301,0.997845,0.000348,7,0.997308,0.997176,0.997081,0.997400,0.997679,0.997329,0.000206,12,0.993252,0.992917,0.992698,0.993491,0.994184,0.993308,0.000515,12,0.995690,0.995478,0.995329,0.995838,0.996284,0.995724,0.000330,12,0.992290,0.991759,0.992463,0.992940,0.993259,0.992542,0.000521,13,0.691220,0.090247,0.085885,0.029882
9,decision_tree,randomized_search,iot23,235490,12,13,5,1,10,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 3, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 3, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.975838,0.977648,0.976126,0.966112,0.965439,0.972233,0.005312,13,0.994798,0.993736,0.993949,0.998726,0.999363,0.996114,0.002427,6,0.985227,0.985626,0.984957,0.982148,0.982108,0.984013,0.001554,13,0.998693,0.998428,0.998480,0.999679,0.999839,0.999024,0.000609,6,0.993843,0.994320,0.993922,0.991242,0.991056,0.992877,0.001421,13,0.996262,0.996370,0.996196,0.995442,0.995428,0.995940,0.000416,13,0.990744,0.990998,0.990576,0.988795,0.988768,0.989977,0.000985,13,0.994034,0.994204,0.993928,0.992739,0.992717,0.993524,0.000656,13,0.994320,0.994028,0.993936,0.994984,0.995209,0.994495,0.000512,12,1.439207,0.370645,0.174505,0.100300

modelo: decision_tree
 origem do treinamento: cicids2017_unsw_nb15
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: decision_tree - cicids2017_unsw_nb15

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
11,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,12,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.959399,0.960341,0.964125,0.959732,0.958471,0.960413,0.001952,4,0.985933,0.987207,0.987102,0.986730,0.987367,0.986868,0.000512,5,0.972485,0.973588,0.975478,0.973044,0.972704,0.973460,0.001076,1,0.996459,0.996779,0.996756,0.996659,0.996818,0.996694,0.000129,5,0.989570,0.989809,0.990817,0.989649,0.989304,0.989830,0.000520,5,0.993002,0.993282,0.993778,0.993142,0.993047,0.993250,0.000281,1,0.982744,0.983435,0.984628,0.983093,0.982876,0.983355,0.000678,1,0.988842,0.989288,0.990074,0.989065,0.988917,0.989237,0.000445,1,0.987751,0.988508,0.988959,0.988190,0.988336,0.988349,0.000395,5,7.360192,0.295412,0.096114,0.009553
7,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,8,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 30, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 19, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.951145,0.954145,0.953544,0.951683,0.948609,0.951825,0.001958,9,0.994214,0.994108,0.996868,0.996338,0.995435,0.995393,0.001106,1,0.972203,0.973716,0.974725,0.973499,0.971458,0.973120,0.001156,2,0.998537,0.998511,0.999208,0.999073,0.998844,0.998835,0.000279,1,0.987234,0.988057,0.987858,0.987353,0.986517,0.987404,0.000538,10,0.992853,0.993257,0.993500,0.993179,0.992643,0.993086,0.000303,2,0.982528,0.983487,0.984113,0.983339,0.982050,0.983103,0.000729,2,0.988630,0.989267,0.989660,0.989150,0.988301,0.989002,0.000481,2,0.990724,0.991082,0.992363,0.991845,0.990976,0.991398,0.000610,1,8.291131,0.670323,0.174908,0.050994
8,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,9,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 15, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.952146,0.954176,0.956277,0.956166,0.952871,0.954327,0.001679,6,0.991772,0.991507,0.993737,0.992251,0.992675,0.992388,0.000784,3,0.971555,0.972483,0.974647,0.973874,0.972366,0.972985,0.001117,3,0.997922,0.997856,0.998419,0.998044,0.998149,0.998078,0.000198,3,0.987539,0.988097,0.988641,0.988627,0.987725,0.988126,0.000452,8,0.992703,0.992952,0.993506,0.993313,0.992910,0.993077,0.000291,3,0.982129,0.982718,0.984076,0.983594,0.982638,0.983031,0.000704,3,0.988386,0.988779,0.989660,0.989352,0.988715,0.988978,0.000461,3,0.989656,0.989802,0.991189,0.990439,0.990200,0.990257,0.000543,3,8.998600,0.371520,0.164644,0.014351
2,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,3,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 18, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.949343,0.951979,0.953317,0.955558,0.950518,0.952143,0.002170,8,0.993842,0.994479,0.996125,0.992887,0.994108,0.994288,0.001059,2,0.971083,0.972765,0.974251,0.973865,0.971824,0.972758,0.001194,4,0.998442,0.998604,0.999020,0.998204,0.998510,0.998556,0.000267,2,0.986743,0.987460,0.987805,0.988455,0.987061,0.987505,0.000595,9,0.992558,0.993001,0.993381,0.993306,0.992753,0.993000,0.000315,4,0.981821,0.982883,0.983816,0.983585,0.982289,0.982879,0.000754,4,0.988163,0.988864,0.989469,0.989341,0.988471,0.988862,0.000498,4,0.990293,0.990970,0.991965,0.990671,0.990585,0.990897,0.000576,2,9.600961,1.338302,0.153053,0.008986
4,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,5,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 20, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.960131,0.962075,0.966263,0.962537,0.959391,0.962079,0.002397,3,0.981792,0.984393,0.982059,0.981900,0.983121,0.982653,0.000991,8,0.970841,0.973106,0.974097,0.972122,0.971111,0.972255,0.001220,5,0.995423,0.996076,0.995496,0.995452,0.995754,0.995640,0.000247,8,0.989809,0.990300,0.991427,0.990445,0.989596,0.990315,0.000637,4,0.992608,0.993179,0.993458,0.992942,0.992665,0.992970,0.000318,6,0.981724,0.983143,0.983777,0.982532,0.981888,0.982613,0.000769,5,0.988205,0.989118,0.989554,0.988736,0.988301,0.988783,0.000505,5,0.985800,0.987346,0.986743,0.986173,0.986359,0.986484,0.000527,6,7.686260,0.578364,0.157113,0.011635
5,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,6,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.961282,0.963042,0.967733,0.963167,0.959227,0.962890,0.002813,2,0.980571,0.983491,0.980626,0.981316,0.982749,0.981751,0.001172,9,0.970831,0.973159,0.974137,0.972157,0.970846,0.972226,0.001295,6,0.995119,0.995851,0.995140,0.995307,0.995661,0.995415,0.000292,9,0.990127,0.990565,0.991825,0.990618,0.989556,0.990538,0.000748,3,0.992617,0.993201,0.993480,0.992957,0.992599,0.992971,0.000339,5,0.981724,0.983180,0.983809,0.982557,0.981722,0.982598,0.000817,6,0.988216,0.989150,0.989586,0.988757,0.988195,0.988781,0.000538,6,0.985349,0.987028,0.986226,0.985967,0.986153,0.986145,0.000539,7,7.152141,0.402724,0.163782,0.015440
10,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,11,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.955118,0.957137,0.959871,0.956587,0.954852,0.956713,0.001799,5,0.982801,0.983862,0.981423,0.983599,0.983386,0.983014,0.000869,7,0.968761,0.970316,0.970527,0.969905,0.968909,0.969684,0.000723,7,0.995669,0.995938,0.995329,0.995870,0.995815,0.995724,0.000216,7,0.988455,0.988986,0.989742,0.988840,0.988375,0.988880,0.000488,6,0.992049,0.992450,0.992528,0.992343,0.992081,0.992290,0.000193,7,0.980405,0.981383,0.981527,0.981124,0.980495,0.980987,0.000458,7,0.987324,0.987961,0.988078,0.987791,0.987377,0.987706,0.000305,7,0.985628,0.986424,0.985582,0.986219,0.985881,0.985947,0.000329,8,6.408142,0.892997,0.163690,0.044018
3,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,4,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 15, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.939077,0.948782,0.947028,0.952140,0.948168,0.947039,0.004330,10,0.991719,0.990233,0.994480,0.990499,0.990393,0.991465,0.001597,4,0.964680,0.969064,0.970174,0.970941,0.968821,0.968736,0.002168,8,0.997900,0.997531,0.998602,0.997600,0.997571,0.997841,0.000402,4,0.983917,0.986637,0.986093,0.987552,0.986464,0.986133,0.001208,11,0.990859,0.992054,0.992308,0.992551,0.991987,0.991952,0.000582,9,0.977770,0.980559,0.981241,0.981746,0.980404,0.980344,0.001375,8,0.985477,0.987356,0.987770,0.988142,0.987250,0.987199,0.000917,8,0.987818,0.988435,0.990286,0.989026,0.988429,0.988799,0.000836,4,6.981014,0.397072,0.161379,0.016680
0,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,1,baseline,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.963463,0.964897,0.968073,0.966009,0.962439,0.964976,0.001969,1,0.970061,0.970326,0.972081,0.971444,0.971072,0.970997,0.000736,11,0.966750,0.967604,0.970073,0.968719,0.966736,0.967976,0.001275,9,0.992503,0.992572,0.993013,0.992850,0.992751,0.992738,0.000185,11,0.990804,0.991175,0.991985,0.991454,0.990525,0.991189,0.000508,1,0.991653,0.991873,0.992498,0.992152,0.991637,0.991963,0.000326,8,0.979202,0.979738,0.981285,0.980435,0.979187,0.979969,0.000801,9,0.986655,0.987006,0.988004,0.987452,0.986634,0.987150,0.000520,9,0.980432,0.980751,0.982033,0.981449,0.980799,0.981093,0.000574,11,8.378788,0.190625,0.172970,0.018989
6,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,7,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 8, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 6, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.952662,0.952615,0.957500,0.955043,0.951881,0.953940,0.002075,7,0.977492,0.978607,0.975796,0.976486,0.977548,0.977186,0.000966,10,0.964917,0.965436,0.966562,0.965646,0.964544,0.965421,0.000689,10,0.994337,0.994615,0.993920,0.994088,0.994349,0.994262,0.000239,10,0.987858,0.987831,0.989171,0.988508,0.987645,0.988203,0.000565,7,0.991087,0.991212,0.991540,0.991290,0.990986,0.991223,0.000190,10,0.978002,0.978324,0.979051,0.978468,0.977765,0.978322,0.000439,10,0.985785,0.985987,0.986496,0.986103,0.985626,0.985999,0.000298,10,0.982675,0.983219,0.982484,0.982497,0.982597,0.982694,0.000272,10,4.558478,0.336367,0.159218,0.014446
1,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,2,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 8, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 11, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.930008,0.941356,0.939589,0.945383,0.940630,0.939393,0.005087,11,0.986782,0.984181,0.990658,0.985828,0.983917,0.986273,0.002434,6,0.957554,0.962292,0.964448,0.965182,0.961787,0.962253,0.002672,11,0.996645,0.996000,0.997632,0.996419,0.995932,0.996526,0.000613,6,0.981435,0.984673,0.984076,0.985761,0.984474,0.984084,0.001437,12,0.988981,0.990304,0.990808,0.991061,0.990170,0.990265,0.000719,11,0.973268,0.976298,0.977628,0.978122,0.975978,0.976259,0.001695,11,0.982505,0.984575,0.985392,0.985774,0.984362,0.984522,0.001133,11,0.984109,0.984427,0.987367,0.985794,0.984195,0.985178,0.001253,9,7.794718,1.596524,0.157216,0.013177
9,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,10,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 3, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 3, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.549289,0.551465,0.551723,0.550190,0.549541,0.550442,0.000989,13,0.942988,0.947075,0.943259,0.942887,0.942941,0.943830,0.001628,12,0.694205,0.697050,0.696219,0.694897,0.694393,0.695353,0.001103,12,0.982637,0.983879,0.982754,0.982620,0.982625,0.982903,0.000490,12,0.806577,0.807439,0.808390,0.807275,0.806757,0.807287,0.000636,13,0.885945,0.886970,0.887085,0.886359,0.886048,0.886481,0.000468,13,0.790075,0.792010,0.791652,0.790628,0.790221,0.790917,0.000776,12,0.833857,0.835365,0.835365,0.834398,0.833995,0.834596,0.000652,13,0.874782,0.877257,0.875824,0.875081,0.874849,0.875559,0.000926,12,2.703227,0.174652,0.159710,0.006498
12,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,13,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 3, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 9, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.918351,0.922592,0.920353,0.920576,0.916394,0.919653,0.002112,12,0.434069,0.435290,0.431794,0.431263,0.430520,0.432587,0.001798,13,0.589503,0.591503,0.587810,0.587364,0.585822,0.588400,0.001945,13,0.875006,0.875299,0.874586,0.874488,0.874287,0.874733,0.000368,13,0.990353,0.990870,0.990658,0.990697,0.990180,0.990552,0.000250,2,0.929113,0.929506,0.929010,0.928972,0.928631,0.929047,0.000281,12,0.759308,0.760504,0.758410,0.758168,0.757227,0.758723,0.001110,13,0.879103,0.879761,0.878880,0.878806,0.878243,0.878959,0.000491,12,0.712211,0.713080,0.711226,0.710980,0.710350,0.711570,0.000964,13,2.373864,0.540012,0.140236,0.014524

modelo: decision_tree
 origem do treinamento: cicids2017_iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: decision_tree - cicids2017_iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
0,decision_tree,randomized_search,cicids2017_iot23,470980,12,13,5,1,1,baseline,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.988773,0.989234,0.990289,0.989076,0.988564,0.989187,0.000598,1,0.991135,0.990179,0.990499,0.989968,0.991083,0.990573,0.000469,5,0.989953,0.989707,0.990394,0.989522,0.989822,0.989879,0.000294,1,0.997783,0.997544,0.997624,0.997491,0.997769,0.997642,0.000117,5,0.997187,0.997306,0.997572,0.997266,0.997134,0.997293,0.000152,1,0.997485,0.997425,0.997598,0.997379,0.997451,0.997468,0.000074,1,0.993719,0.993566,0.993996,0.993450,0.993637,0.993673,0.000184,1,0.995976,0.995881,0.996157,0.995807,0.995923,0.995949,0.000118,1,0.994161,0.993743,0.994035,0.993617,0.994108,0.993933,0.000214,4,6.476694,0.615096,0.160771,0.008974
5,decision_tree,randomized_search,cicids2017_iot23,470980,12,13,5,1,6,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.989024,0.987980,0.989186,0.988805,0.987720,0.988543,0.000584,2,0.990126,0.990445,0.990446,0.989172,0.990499,0.990138,0.000501,7,0.989575,0.989211,0.989815,0.988988,0.989108,0.989339,0.000308,2,0.997531,0.997610,0.997611,0.997293,0.997623,0.997533,0.000125,7,0.997253,0.996988,0.997293,0.997200,0.996921,0.997131,0.000149,2,0.997392,0.997299,0.997452,0.997246,0.997272,0.997332,0.000077,2,0.993483,0.993255,0.993634,0.993117,0.993190,0.993336,0.000193,2,0.995828,0.995679,0.995923,0.995594,0.995637,0.995732,0.000124,2,0.993690,0.993716,0.993869,0.993186,0.993710,0.993634,0.000233,5,6.456170,0.503252,0.176059,0.010653
11,decision_tree,randomized_search,cicids2017_iot23,470980,12,13,5,1,12,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.988866,0.988386,0.989149,0.988703,0.986826,0.988386,0.000818,3,0.990073,0.989383,0.991879,0.989437,0.990021,0.990159,0.000906,6,0.989469,0.988884,0.990512,0.989070,0.988421,0.989271,0.000706,3,0.997518,0.997345,0.997968,0.997359,0.997503,0.997539,0.000226,6,0.997213,0.997094,0.997280,0.997173,0.996696,0.997091,0.000207,4,0.997366,0.997220,0.997624,0.997266,0.997099,0.997315,0.000177,3,0.993417,0.993052,0.994068,0.993168,0.992760,0.993293,0.000441,3,0.995785,0.995552,0.996199,0.995626,0.995361,0.995705,0.000283,3,0.993643,0.993239,0.994579,0.993305,0.993358,0.993625,0.000497,6,5.241926,0.175739,0.102183,0.017264
4,decision_tree,randomized_search,cicids2017_iot23,470980,12,13,5,1,5,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 20, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.988237,0.988187,0.988766,0.988489,0.986358,0.988007,0.000850,4,0.990073,0.990286,0.990446,0.989066,0.990127,0.990000,0.000485,8,0.989154,0.989235,0.989605,0.988777,0.988239,0.989002,0.000464,4,0.997517,0.997570,0.997610,0.997266,0.997529,0.997499,0.000121,8,0.997054,0.997041,0.997187,0.997120,0.996576,0.996996,0.000216,6,0.997286,0.997305,0.997398,0.997193,0.997053,0.997247,0.000117,4,0.993220,0.993270,0.993502,0.992985,0.992646,0.993125,0.000290,4,0.995658,0.995690,0.995838,0.995509,0.995286,0.995596,0.000187,4,0.993564,0.993663,0.993816,0.993093,0.993352,0.993498,0.000252,8,6.454862,0.458387,0.161165,0.010688
8,decision_tree,randomized_search,cicids2017_iot23,470980,12,13,5,1,9,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 15, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.978068,0.976750,0.980330,0.978639,0.978272,0.978412,0.001151,8,0.996656,0.996868,0.997293,0.997028,0.996550,0.996879,0.000265,3,0.987275,0.986707,0.988739,0.987748,0.987326,0.987559,0.000677,5,0.999160,0.999213,0.999320,0.999253,0.999133,0.999216,0.000067,3,0.994413,0.994068,0.994997,0.994559,0.994466,0.994501,0.000299,8,0.996781,0.996634,0.997154,0.996901,0.996794,0.996853,0.000173,5,0.992028,0.991670,0.992946,0.992324,0.992060,0.992206,0.000425,5,0.994862,0.994628,0.995456,0.995053,0.994883,0.994976,0.000275,5,0.995535,0.995468,0.996145,0.995793,0.995508,0.995690,0.000255,2,7.112566,0.417233,0.178601,0.015695
7,decision_tree,randomized_search,cicids2017_iot23,470980,12,13,5,1,8,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 30, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 19, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.979709,0.977220,0.978757,0.977422,0.975962,0.977814,0.001297,9,0.997027,0.997399,0.997771,0.997240,0.997771,0.997441,0.000294,1,0.988292,0.987206,0.988172,0.987231,0.986746,0.987530,0.000600,6,0.999254,0.999346,0.999440,0.999306,0.999440,0.999357,0.000074,1,0.994838,0.994188,0.994586,0.994241,0.993856,0.994342,0.000339,9,0.997041,0.996760,0.997007,0.996767,0.996640,0.996843,0.000155,6,0.992667,0.991983,0.992590,0.991999,0.991693,0.992186,0.000378,6,0.995276,0.994830,0.995223,0.994841,0.994639,0.994962,0.000246,6,0.995933,0.995793,0.996178,0.995740,0.995813,0.995892,0.000157,1,6.702913,0.154145,0.160843,0.005393
2,decision_tree,randomized_search,cicids2017_iot23,470980,12,13,5,1,3,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 18, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.977412,0.975435,0.977826,0.976210,0.975842,0.976545,0.000920,10,0.996921,0.997027,0.997134,0.997558,0.996975,0.997123,0.000229,2,0.987070,0.986113,0.987386,0.986769,0.986295,0.986727,0.000473,7,0.999226,0.999253,0.999280,0.999386,0.999239,0.999277,0.000057,2,0.994241,0.993723,0.994347,0.993922,0.993829,0.994012,0.000241,10,0.996727,0.996480,0.996807,0.996647,0.996527,0.996638,0.000122,7,0.991899,0.991297,0.992096,0.991708,0.991411,0.991682,0.000297,7,0.994777,0.994384,0.994904,0.994649,0.994458,0.994635,0.000193,7,0.995581,0.995375,0.995740,0.995740,0.995402,0.995568,0.000158,3,6.684762,0.701506,0.261254,0.188880
10,decision_tree,randomized_search,cicids2017_iot23,470980,12,13,5,1,11,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.988857,0.987623,0.988923,0.987620,0.986892,0.987983,0.000788,5,0.984606,0.982695,0.985669,0.982378,0.983068,0.983683,0.001253,10,0.986727,0.985152,0.987293,0.984992,0.984976,0.985828,0.000983,8,0.996156,0.995679,0.996420,0.995600,0.995771,0.995925,0.000312,10,0.997227,0.996921,0.997240,0.996921,0.996735,0.997009,0.000195,5,0.996691,0.996300,0.996830,0.996260,0.996253,0.996467,0.000244,8,0.991709,0.990726,0.992062,0.990626,0.990615,0.991147,0.000614,8,0.994703,0.994076,0.994925,0.994012,0.994002,0.994344,0.000391,8,0.990916,0.989808,0.991454,0.989650,0.989902,0.990346,0.000711,10,4.603986,0.159765,0.165025,0.009753
6,decision_tree,randomized_search,cicids2017_iot23,470980,12,13,5,1,7,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 8, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 6, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.985574,0.983770,0.984856,0.983546,0.984442,0.984438,0.000736,7,0.982801,0.981367,0.983758,0.980414,0.980732,0.981815,0.001271,11,0.984185,0.982567,0.984307,0.981978,0.982584,0.983124,0.000942,9,0.995704,0.995345,0.995940,0.995107,0.995187,0.995457,0.000317,11,0.996404,0.995953,0.996218,0.995899,0.996125,0.996120,0.000183,7,0.996054,0.995649,0.996079,0.995503,0.995656,0.995788,0.000234,9,0.990119,0.989108,0.990193,0.988740,0.989120,0.989456,0.000588,9,0.993683,0.993036,0.993726,0.992802,0.993046,0.993259,0.000375,9,0.989602,0.988660,0.989988,0.988157,0.988429,0.988967,0.000705,11,3.625642,0.357409,0.165431,0.017974
3,decision_tree,randomized_search,cicids2017_iot23,470980,12,13,5,1,4,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 15, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.969134,0.960248,0.974194,0.975931,0.975723,0.971046,0.005931,12,0.996709,0.996337,0.993843,0.994321,0.991985,0.994639,0.001729,4,0.982728,0.977960,0.983920,0.985040,0.983787,0.982687,0.002475,10,0.999171,0.999076,0.998453,0.998573,0.997988,0.998652,0.000433,4,0.992065,0.989689,0.993418,0.993869,0.993829,0.992574,0.001584,12,0.995605,0.994360,0.995929,0.996216,0.995904,0.995603,0.000651,10,0.989167,0.986160,0.989925,0.990628,0.989846,0.989145,0.001563,10,0.992993,0.991019,0.993503,0.993959,0.993460,0.992987,0.001031,10,0.994387,0.993013,0.993630,0.994095,0.992907,0.993606,0.000581,7,5.379503,0.360021,0.226545,0.065452
1,decision_tree,randomized_search,cicids2017_iot23,470980,12,13,5,1,2,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 8, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 11, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.970938,0.970674,0.972180,0.979731,0.968912,0.972487,0.003769,11,0.989595,0.989224,0.990499,0.985191,0.989278,0.988758,0.001841,9,0.980178,0.979861,0.981254,0.982453,0.978989,0.980547,0.001197,11,0.997387,0.997293,0.997613,0.996292,0.997305,0.997178,0.000458,9,0.992595,0.992529,0.992914,0.994904,0.992064,0.993001,0.000989,11,0.994985,0.994905,0.995258,0.995598,0.994678,0.995085,0.000316,11,0.987581,0.987383,0.988256,0.989026,0.986834,0.987816,0.000757,11,0.991995,0.991868,0.992431,0.992961,0.991507,0.992153,0.000501,11,0.991095,0.990876,0.991706,0.990048,0.990671,0.990879,0.000541,9,4.802199,0.571012,0.167841,0.011505
9,decision_tree,randomized_search,cicids2017_iot23,470980,12,13,5,1,10,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 3, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 3, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.902316,0.904896,0.907003,0.902758,0.902535,0.903902,0.001806,13,0.974307,0.972290,0.972718,0.971231,0.971231,0.972356,0.001138,12,0.936930,0.937383,0.938712,0.935744,0.935624,0.936879,0.001138,12,0.993447,0.992942,0.993053,0.992668,0.992668,0.992956,0.000288,12,0.973633,0.974455,0.975065,0.973844,0.973778,0.974155,0.000535,13,0.983440,0.983612,0.983977,0.983166,0.983132,0.983465,0.000311,12,0.960185,0.960497,0.961344,0.959455,0.959378,0.960172,0.000725,12,0.973767,0.974022,0.974596,0.973322,0.973269,0.973795,0.000489,12,0.973970,0.973373,0.973891,0.972538,0.972505,0.973255,0.000634,12,2.277433,0.143861,0.195803,0.038726
12,decision_tree,randomized_search,cicids2017_iot23,470980,12,13,5,1,13,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 3, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 9, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.986474,0.984822,0.987581,0.986013,0.985446,0.986067,0.000938,6,0.824610,0.823177,0.827282,0.819427,0.823036,0.823506,0.002548,13,0.898309,0.896773,0.900352,0.895034,0.896949,0.897483,0.001772,13,0.957883,0.957540,0.958502,0.956684,0.957508,0.957623,0.000590,13,0.997173,0.996828,0.997399,0.997094,0.996961,0.997091,0.000194,3,0.977134,0.976789,0.977564,0.976471,0.976836,0.976959,0.000368,13,0.937721,0.936781,0.938958,0.935753,0.936892,0.937221,0.001070,13,0.962663,0.962100,0.963374,0.961559,0.962175,0.962374,0.000610,13,0.910892,0.910003,0.912341,0.908260,0.909999,0.910299,0.001331,13,1.586044,0.246335,0.128818,0.023609

modelo: decision_tree
 origem do treinamento: unsw_nb15_iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: decision_tree - unsw_nb15_iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
11,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,12,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.971549,0.972695,0.970448,0.970426,0.970445,0.971112,0.000900,4,0.991560,0.992781,0.991773,0.992781,0.991667,0.992112,0.000550,6,0.981452,0.982635,0.980994,0.981477,0.980941,0.981500,0.000610,1,0.997879,0.998186,0.997932,0.998185,0.997905,0.998017,0.000138,6,0.992741,0.993033,0.992449,0.992436,0.992449,0.992622,0.000236,4,0.995304,0.995603,0.995183,0.995302,0.995170,0.995312,0.000156,1,0.988378,0.989119,0.988089,0.988389,0.988055,0.988406,0.000383,1,0.992505,0.992983,0.992314,0.992505,0.992293,0.992520,0.000248,1,0.992150,0.992907,0.992111,0.992609,0.992058,0.992367,0.000334,6,4.950589,0.484098,0.129463,0.027769
10,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,11,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.970418,0.969429,0.968132,0.967889,0.968854,0.968945,0.000915,5,0.989118,0.989808,0.993312,0.990340,0.992304,0.990976,0.001577,7,0.979679,0.979513,0.980561,0.978986,0.980438,0.979835,0.000590,2,0.997266,0.997439,0.998317,0.997571,0.998064,0.997731,0.000395,7,0.992463,0.992197,0.991825,0.991786,0.992025,0.992059,0.000250,5,0.994859,0.994811,0.995061,0.994670,0.995035,0.994887,0.000145,2,0.987269,0.987162,0.987811,0.986828,0.987737,0.987361,0.000368,2,0.991794,0.991719,0.992123,0.991496,0.992080,0.991843,0.000233,2,0.990790,0.991003,0.992569,0.991063,0.992164,0.991518,0.000711,7,4.848775,0.387044,0.153220,0.015744
2,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,3,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 18, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.963661,0.964222,0.962062,0.961570,0.961725,0.962648,0.001082,7,0.996656,0.997133,0.997399,0.997399,0.997611,0.997240,0.000329,3,0.979880,0.980401,0.979412,0.979157,0.979340,0.979638,0.000450,3,0.999157,0.999277,0.999344,0.999344,0.999397,0.999304,0.000083,3,0.990605,0.990751,0.990167,0.990034,0.990074,0.990326,0.000294,7,0.994862,0.994996,0.994734,0.994667,0.994714,0.994795,0.000120,5,0.987371,0.987699,0.987073,0.986912,0.987027,0.987216,0.000285,3,0.991815,0.992027,0.991613,0.991507,0.991581,0.991709,0.000189,5,0.993630,0.993942,0.993783,0.993717,0.993843,0.993783,0.000106,2,5.887937,0.770433,0.165251,0.012517
5,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,6,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.973903,0.974543,0.972894,0.972278,0.972712,0.973266,0.000832,2,0.984553,0.985614,0.986837,0.984766,0.987633,0.985880,0.001188,9,0.979199,0.980048,0.979816,0.978482,0.980115,0.979532,0.000616,4,0.996128,0.996394,0.996697,0.996179,0.996896,0.996459,0.000297,9,0.993405,0.993564,0.993126,0.992980,0.993073,0.993230,0.000219,2,0.994764,0.994977,0.994908,0.994577,0.994981,0.994841,0.000154,3,0.986982,0.987512,0.987362,0.986530,0.987548,0.987187,0.000385,4,0.991634,0.991974,0.991868,0.991337,0.991985,0.991760,0.000246,3,0.988979,0.989589,0.989981,0.988873,0.990353,0.989555,0.000569,9,5.117842,0.212399,0.191424,0.019284
4,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,5,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 20, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.973737,0.973690,0.973090,0.971782,0.972044,0.972868,0.000817,3,0.986039,0.986198,0.986571,0.985244,0.987367,0.986284,0.000694,8,0.979849,0.979904,0.979784,0.978467,0.979646,0.979530,0.000539,5,0.996499,0.996539,0.996631,0.996298,0.996829,0.996559,0.000173,8,0.993352,0.993338,0.993179,0.992847,0.992900,0.993123,0.000213,3,0.994923,0.994936,0.994902,0.994570,0.994861,0.994838,0.000137,4,0.987386,0.987420,0.987343,0.986518,0.987253,0.987184,0.000338,5,0.991889,0.991910,0.991857,0.991327,0.991794,0.991755,0.000218,4,0.989695,0.989768,0.989875,0.989046,0.990134,0.989704,0.000361,8,5.317177,0.561802,0.156000,0.003266
7,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,8,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 30, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 19, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.963672,0.964911,0.960662,0.960941,0.960266,0.962090,0.001852,8,0.996974,0.997027,0.998089,0.997665,0.997983,0.997548,0.000468,2,0.980040,0.980706,0.979018,0.978958,0.978761,0.979497,0.000751,6,0.999237,0.999251,0.999518,0.999410,0.999491,0.999381,0.000118,2,0.990605,0.990937,0.989782,0.989861,0.989676,0.990172,0.000503,8,0.994902,0.995076,0.994626,0.994613,0.994559,0.994755,0.000200,6,0.987471,0.987891,0.986822,0.986786,0.986660,0.987126,0.000475,6,0.991879,0.992155,0.991443,0.991422,0.991337,0.991647,0.000316,6,0.993790,0.993982,0.993936,0.993763,0.993829,0.993860,0.000085,1,5.607534,0.238502,0.168415,0.017863
8,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,9,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 15, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.964363,0.965398,0.963707,0.962613,0.962461,0.963708,0.001099,6,0.994055,0.995276,0.995064,0.994904,0.994798,0.994819,0.000415,5,0.978984,0.980109,0.979135,0.978492,0.978362,0.979016,0.000618,7,0.998502,0.998810,0.998756,0.998715,0.998688,0.998694,0.000104,5,0.990817,0.991083,0.990631,0.990339,0.990299,0.990634,0.000295,6,0.994645,0.994931,0.994677,0.994510,0.994476,0.994648,0.000161,7,0.986814,0.987520,0.986906,0.986501,0.986419,0.986832,0.000390,7,0.991465,0.991921,0.991518,0.991252,0.991199,0.991471,0.000256,7,0.992436,0.993179,0.992847,0.992622,0.992549,0.992727,0.000263,5,5.470247,0.353115,0.209281,0.026420
3,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,4,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 15, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.962037,0.961786,0.960372,0.959855,0.959679,0.960746,0.000982,10,0.996815,0.998036,0.998195,0.997505,0.998036,0.997718,0.000508,1,0.979117,0.979576,0.978918,0.978318,0.978482,0.978882,0.000451,8,0.999197,0.999504,0.999544,0.999370,0.999504,0.999424,0.000128,1,0.990167,0.990087,0.989702,0.989570,0.989516,0.989808,0.000268,10,0.994661,0.994774,0.994599,0.994446,0.994485,0.994593,0.000119,8,0.986889,0.987175,0.986759,0.986382,0.986484,0.986738,0.000285,8,0.991496,0.991677,0.991401,0.991157,0.991220,0.991390,0.000188,8,0.993491,0.994062,0.993949,0.993537,0.993776,0.993763,0.000223,3,5.340542,0.469563,0.161503,0.006794
1,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,2,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 8, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 11, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.959752,0.957089,0.954545,0.957311,0.953966,0.956533,0.002089,11,0.996231,0.996921,0.997611,0.996285,0.997665,0.996943,0.000618,4,0.977652,0.976599,0.975603,0.976409,0.975326,0.976318,0.000820,9,0.999049,0.999222,0.999396,0.999062,0.999409,0.999228,0.000156,4,0.989557,0.988827,0.988123,0.988893,0.987964,0.988673,0.000576,11,0.994280,0.993997,0.993728,0.993951,0.993654,0.993922,0.000221,9,0.985966,0.985298,0.984665,0.985180,0.984490,0.985120,0.000520,9,0.990891,0.990445,0.990021,0.990371,0.989904,0.990327,0.000348,9,0.992894,0.992874,0.992867,0.992589,0.992814,0.992808,0.000113,4,4.916728,0.376221,0.176961,0.032533
0,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,1,baseline,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.974354,0.976099,0.974095,0.973849,0.975027,0.974685,0.000809,1,0.976112,0.973405,0.976008,0.974469,0.973992,0.974797,0.001086,11,0.975232,0.974750,0.975051,0.974159,0.974509,0.974740,0.000382,10,0.994026,0.993356,0.993999,0.993616,0.993499,0.993699,0.000269,11,0.993577,0.994042,0.993511,0.993458,0.993763,0.993670,0.000213,1,0.993802,0.993699,0.993755,0.993537,0.993631,0.993685,0.000093,10,0.984517,0.984225,0.984403,0.983848,0.984070,0.984212,0.000238,10,0.990085,0.989915,0.990010,0.989660,0.989808,0.989896,0.000150,10,0.984845,0.983723,0.984760,0.983963,0.983877,0.984234,0.000471,11,5.062260,0.238134,0.182238,0.029380
6,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,7,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 8, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 6, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.967679,0.967921,0.953068,0.964558,0.954543,0.961554,0.006454,9,0.979032,0.980253,0.988429,0.980839,0.987527,0.983216,0.003942,10,0.973322,0.974048,0.970427,0.972630,0.970755,0.972236,0.001420,11,0.994743,0.995048,0.997080,0.995189,0.996854,0.995783,0.000980,10,0.991826,0.991879,0.987831,0.990989,0.988242,0.990153,0.001762,9,0.993282,0.993461,0.992434,0.993085,0.992530,0.992958,0.000408,11,0.983302,0.983754,0.981430,0.982857,0.981642,0.982597,0.000914,11,0.989267,0.989554,0.987951,0.988959,0.988099,0.988766,0.000635,11,0.985429,0.986066,0.988130,0.985914,0.987885,0.986685,0.001103,10,4.016221,0.270259,0.161978,0.016970
12,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,13,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 3, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 9, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.958518,0.958717,0.908687,0.953892,0.911228,0.938208,0.023145,12,0.653785,0.658297,0.726805,0.655573,0.728450,0.684582,0.035180,13,0.777353,0.780600,0.807632,0.777086,0.809652,0.790465,0.014907,12,0.919825,0.920786,0.934953,0.920133,0.935351,0.926210,0.007309,13,0.992927,0.992914,0.981740,0.992078,0.982258,0.988383,0.005225,12,0.954979,0.955491,0.957775,0.954752,0.958231,0.956246,0.001462,12,0.866166,0.868045,0.882704,0.865919,0.883941,0.873355,0.008181,12,0.925103,0.925995,0.930751,0.924774,0.931494,0.927623,0.002894,12,0.823356,0.825605,0.854272,0.823825,0.855354,0.836483,0.014989,13,1.873761,0.323244,0.129009,0.031553
9,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,10,random,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 3, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 3, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",0.696354,0.698013,0.692444,0.695631,0.697810,0.696050,0.002011,13,0.909385,0.909810,0.909660,0.911040,0.906635,0.909306,0.001451,12,0.788738,0.789961,0.786327,0.788896,0.788633,0.788511,0.001191,13,0.975472,0.975604,0.975492,0.975893,0.974770,0.975446,0.000370,12,0.900873,0.901603,0.898986,0.900340,0.901839,0.900728,0.001020,13,0.936690,0.937145,0.935678,0.936595,0.936887,0.936599,0.000498,13,0.862714,0.863553,0.861002,0.862745,0.862760,0.862555,0.000838,13,0.902575,0.903244,0.901121,0.902480,0.902798,0.902444,0.000712,13,0.905129,0.905706,0.904323,0.905690,0.904237,0.905017,0.000637,12,2.208620,0.266633,0.162381,0.009991

modelo: random_forest
 origem do treinamento: cicids2017
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: random_forest - cicids2017

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
2,random_forest,randomized_search,cicids2017,235490,12,13,5,1,3,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 171, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.980061,0.978345,0.982016,0.980649,0.976698,0.979554,0.001851,3,0.996709,0.997664,0.997028,0.995223,0.996709,0.996667,0.000802,5,0.988315,0.987910,0.989465,0.987882,0.986602,0.988035,0.000918,1,0.999174,0.999413,0.999254,0.998801,0.999173,0.999163,0.000201,5,0.994931,0.994480,0.995435,0.995090,0.994055,0.994798,0.000482,3,0.997048,0.996940,0.997341,0.996942,0.996607,0.996976,0.000235,1,0.992681,0.992425,0.993403,0.992412,0.991605,0.992505,0.000577,1,0.995286,0.995117,0.995754,0.995117,0.994586,0.995172,0.000374,1,0.995820,0.996072,0.996231,0.995156,0.995382,0.995732,0.000407,5,85.964579,4.615157,0.551148,0.051425
8,random_forest,randomized_search,cicids2017,235490,12,13,5,1,9,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 275, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.978954,0.977140,0.981110,0.979434,0.975605,0.978449,0.001903,6,0.997558,0.998407,0.997983,0.995966,0.997665,0.997516,0.000829,3,0.988168,0.987660,0.989475,0.987631,0.986511,0.987889,0.000960,2,0.999387,0.999600,0.999494,0.998987,0.999413,0.999376,0.000208,3,0.994639,0.994161,0.995196,0.994771,0.993763,0.994506,0.000497,8,0.997007,0.996873,0.997340,0.996875,0.996580,0.996935,0.000246,2,0.992588,0.992266,0.993408,0.992253,0.991546,0.992412,0.000603,2,0.995223,0.995010,0.995754,0.995010,0.994543,0.995108,0.000392,2,0.996099,0.996284,0.996590,0.995369,0.995714,0.996011,0.000428,1,134.294273,3.839044,0.818761,0.061834
12,random_forest,randomized_search,cicids2017,235490,12,13,5,1,13,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 115, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.978854,0.976940,0.980599,0.979839,0.975998,0.978446,0.001732,7,0.997664,0.998514,0.997983,0.995754,0.997134,0.997410,0.000941,4,0.988170,0.987609,0.989214,0.987732,0.986452,0.987836,0.000893,3,0.999413,0.999626,0.999493,0.998934,0.999280,0.999349,0.000236,4,0.994612,0.994108,0.995063,0.994878,0.993869,0.994506,0.000453,7,0.997007,0.996860,0.997274,0.996902,0.996567,0.996922,0.000229,3,0.992588,0.992234,0.993244,0.992317,0.991510,0.992379,0.000561,3,0.995223,0.994989,0.995647,0.995053,0.994522,0.995087,0.000364,3,0.996138,0.996311,0.996523,0.995316,0.995501,0.995958,0.000469,3,50.037855,5.649497,0.342468,0.021715
1,random_forest,randomized_search,cicids2017,235490,12,13,5,1,2,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 237, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.977933,0.975830,0.979990,0.978728,0.975402,0.977576,0.001735,11,0.997452,0.998726,0.998195,0.996391,0.997665,0.997686,0.000784,2,0.987596,0.987145,0.989009,0.987480,0.986408,0.987528,0.000849,4,0.999360,0.999680,0.999547,0.999094,0.999413,0.999418,0.000197,2,0.994374,0.993816,0.994904,0.994586,0.993710,0.994278,0.000454,11,0.996860,0.996739,0.997220,0.996835,0.996553,0.996841,0.000218,4,0.992228,0.991942,0.993114,0.992157,0.991480,0.992185,0.000533,4,0.994989,0.994798,0.995562,0.994947,0.994501,0.994959,0.000347,4,0.995913,0.996271,0.996550,0.995488,0.995687,0.995982,0.000385,2,118.295477,2.760086,0.746704,0.065747
3,random_forest,randomized_search,cicids2017,235490,12,13,5,1,4,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 30, ""classifier__max_features"": 0.5, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 278, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.978039,0.976035,0.979579,0.977810,0.974691,0.977231,0.001696,12,0.997664,0.998832,0.998089,0.996391,0.997558,0.997707,0.000796,1,0.987754,0.987302,0.988748,0.987013,0.985992,0.987362,0.000903,5,0.999413,0.999706,0.999520,0.999093,0.999386,0.999424,0.000200,1,0.994400,0.993869,0.994798,0.994347,0.993524,0.994188,0.000444,12,0.996900,0.996779,0.997153,0.996714,0.996446,0.996799,0.000231,6,0.992327,0.992041,0.992950,0.991864,0.991219,0.992080,0.000567,5,0.995053,0.994862,0.995456,0.994756,0.994331,0.994892,0.000368,6,0.996032,0.996351,0.996444,0.995369,0.995541,0.995947,0.000428,4,248.642362,3.992943,0.773725,0.037572
0,random_forest,randomized_search,cicids2017,235490,12,13,5,1,1,baseline,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 100, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.982036,0.981035,0.984419,0.981596,0.980117,0.981841,0.001440,1,0.992462,0.994055,0.992675,0.990870,0.994268,0.992866,0.001230,11,0.987221,0.987502,0.988530,0.986212,0.987142,0.987321,0.000744,6,0.998111,0.998509,0.998165,0.997712,0.998562,0.998212,0.000307,11,0.995462,0.995196,0.996072,0.995355,0.994957,0.995409,0.000373,1,0.996784,0.996850,0.997117,0.996532,0.996756,0.996808,0.000188,5,0.992003,0.992176,0.992824,0.991372,0.991949,0.992065,0.000466,6,0.994862,0.994968,0.995393,0.994458,0.994819,0.994900,0.000300,5,0.993962,0.994625,0.994374,0.993113,0.994612,0.994137,0.000566,7,56.558279,1.094425,0.375270,0.042656
4,random_forest,randomized_search,cicids2017,235490,12,13,5,1,5,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 168, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.980199,0.979169,0.982059,0.980361,0.978429,0.980043,0.001229,2,0.993311,0.993099,0.993631,0.990977,0.991932,0.992590,0.000990,12,0.986712,0.986085,0.987811,0.985640,0.985134,0.986276,0.000926,7,0.998322,0.998269,0.998403,0.997738,0.997976,0.998142,0.000248,12,0.994984,0.994719,0.995462,0.995037,0.994533,0.994947,0.000316,2,0.996650,0.996490,0.996930,0.996386,0.996251,0.996542,0.000234,7,0.991681,0.991288,0.992370,0.991013,0.990693,0.991409,0.000580,7,0.994649,0.994395,0.995095,0.994225,0.994012,0.994475,0.000374,7,0.994148,0.993909,0.994546,0.993007,0.993232,0.993768,0.000572,11,86.639724,2.963769,0.538135,0.036308
7,random_forest,randomized_search,cicids2017,235490,12,13,5,1,8,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 160, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.979400,0.977659,0.981452,0.979772,0.976414,0.978939,0.001746,4,0.994373,0.994267,0.994268,0.992357,0.993206,0.993694,0.000793,7,0.986830,0.985893,0.987818,0.986024,0.984738,0.986261,0.001026,8,0.998588,0.998561,0.998562,0.998083,0.998294,0.998418,0.000199,7,0.994772,0.994320,0.995302,0.994878,0.994002,0.994655,0.000452,4,0.996676,0.996436,0.996930,0.996478,0.996143,0.996533,0.000262,8,0.991753,0.991165,0.992374,0.991251,0.990441,0.991397,0.000644,8,0.994692,0.994310,0.995095,0.994373,0.993843,0.994463,0.000417,8,0.994572,0.994294,0.994785,0.993617,0.993604,0.994174,0.000486,6,71.036853,2.064432,0.454492,0.012988
10,random_forest,randomized_search,cicids2017,235490,12,13,5,1,11,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced_subsample"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 296, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.979090,0.977147,0.981247,0.979566,0.976111,0.978632,0.001816,5,0.994267,0.994161,0.994268,0.992357,0.993312,0.993673,0.000749,8,0.986620,0.985580,0.987714,0.985920,0.984636,0.986094,0.001032,9,0.998561,0.998534,0.998562,0.998083,0.998321,0.998412,0.000188,8,0.994692,0.994188,0.995249,0.994825,0.993922,0.994575,0.000470,5,0.996623,0.996356,0.996903,0.996451,0.996117,0.996490,0.000263,9,0.991622,0.990968,0.992309,0.991185,0.990376,0.991292,0.000648,9,0.994607,0.994182,0.995053,0.994331,0.993800,0.994395,0.000420,9,0.994479,0.994174,0.994758,0.993591,0.993617,0.994124,0.000463,8,144.401678,1.992405,0.767127,0.074498
9,random_forest,randomized_search,cicids2017,235490,12,13,5,1,10,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced_subsample"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 231, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.978986,0.976836,0.980940,0.979156,0.976106,0.978405,0.001736,8,0.994161,0.993948,0.994374,0.992357,0.993100,0.993588,0.000752,10,0.986515,0.985318,0.987611,0.985712,0.984530,0.985937,0.001054,10,0.998535,0.998481,0.998589,0.998083,0.998267,0.998391,0.000189,10,0.994665,0.994108,0.995170,0.994718,0.993922,0.994517,0.000449,6,0.996596,0.996290,0.996876,0.996398,0.996090,0.996450,0.000269,10,0.991556,0.990804,0.992244,0.991055,0.990310,0.991194,0.000661,10,0.994565,0.994076,0.995010,0.994246,0.993758,0.994331,0.000428,10,0.994413,0.994028,0.994772,0.993538,0.993511,0.994052,0.000491,10,115.544665,1.344343,0.610721,0.019682
6,random_forest,randomized_search,cicids2017,235490,12,13,5,1,7,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 163, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.978783,0.976839,0.980942,0.978951,0.976007,0.978304,0.001734,9,0.994267,0.994055,0.994480,0.992357,0.993206,0.993673,0.000787,9,0.986464,0.985372,0.987665,0.985608,0.984531,0.985928,0.001065,11,0.998561,0.998507,0.998615,0.998083,0.998294,0.998412,0.000198,9,0.994612,0.994108,0.995170,0.994665,0.993896,0.994490,0.000449,9,0.996583,0.996303,0.996889,0.996371,0.996090,0.996447,0.000271,11,0.991524,0.990837,0.992277,0.990990,0.990311,0.991188,0.000668,11,0.994543,0.994097,0.995032,0.994204,0.993758,0.994327,0.000433,11,0.994440,0.994081,0.994825,0.993511,0.993551,0.994082,0.000507,9,71.410899,0.898032,0.446467,0.005695
11,random_forest,randomized_search,cicids2017,235490,12,13,5,1,12,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": 1.0, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 180, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.979243,0.976521,0.979169,0.977386,0.976575,0.977779,0.001205,10,0.986729,0.984712,0.988004,0.981847,0.982484,0.984755,0.002369,13,0.982972,0.980599,0.983567,0.979611,0.979521,0.981254,0.001699,12,0.996676,0.996170,0.996994,0.995456,0.995614,0.996182,0.000592,13,0.994772,0.994082,0.994745,0.994320,0.994108,0.994405,0.000300,10,0.995723,0.995125,0.995868,0.994888,0.994860,0.995293,0.000423,12,0.989347,0.987862,0.989717,0.987250,0.987191,0.988273,0.001061,12,0.993163,0.992208,0.993397,0.991826,0.991783,0.992475,0.000678,12,0.990750,0.989397,0.991375,0.988084,0.988296,0.989580,0.001305,13,235.536635,5.835629,0.339840,0.036610
5,random_forest,randomized_search,cicids2017,235490,12,13,5,1,6,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": 1.0, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 186, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.962583,0.965138,0.966070,0.966742,0.967162,0.965539,0.001629,13,0.996921,0.996390,0.997452,0.993631,0.994268,0.995732,0.001508,6,0.979451,0.980515,0.981510,0.980002,0.980528,0.980401,0.000681,13,0.999223,0.999090,0.999358,0.998396,0.998557,0.998925,0.000379,6,0.990313,0.991003,0.991242,0.991454,0.991560,0.991114,0.000444,13,0.994748,0.995030,0.995283,0.994913,0.995046,0.995004,0.000176,13,0.987100,0.987773,0.988397,0.987458,0.987787,0.987703,0.000428,13,0.991634,0.992080,0.992484,0.991889,0.992102,0.992038,0.000279,13,0.993617,0.993697,0.994347,0.992542,0.992914,0.993423,0.000633,12,323.804675,7.915171,0.476866,0.003941

modelo: random_forest
 origem do treinamento: unsw_nb15
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: random_forest - unsw_nb15

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
2,random_forest,randomized_search,unsw_nb15,235490,12,13,5,1,3,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 171, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.944579,0.945905,0.942582,0.942871,0.941990,0.943585,0.001444,2,0.997027,0.996921,0.996815,0.996921,0.998089,0.997155,0.000472,11,0.970095,0.970743,0.968940,0.969143,0.969228,0.969630,0.000682,1,0.999246,0.999220,0.999192,0.999219,0.999515,0.999279,0.000120,11,0.985376,0.985748,0.984819,0.984898,0.984633,0.985095,0.000408,2,0.992263,0.992438,0.991953,0.992007,0.992018,0.992136,0.000185,1,0.981179,0.981591,0.980447,0.980575,0.980623,0.980883,0.000434,1,0.987706,0.987983,0.987218,0.987303,0.987324,0.987507,0.000291,1,0.991202,0.991335,0.990817,0.990910,0.991361,0.991125,0.000222,11,80.992971,2.012031,0.647045,0.033243
4,random_forest,randomized_search,unsw_nb15,235490,12,13,5,1,5,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 168, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.944059,0.945120,0.940859,0.940970,0.941200,0.942442,0.001789,3,0.997983,0.998301,0.998089,0.998408,0.999151,0.998386,0.000411,10,0.970273,0.970983,0.968629,0.968839,0.969310,0.969607,0.000891,2,0.999488,0.999569,0.999515,0.999596,0.999784,0.999591,0.000104,10,0.985217,0.985509,0.984314,0.984341,0.984394,0.984755,0.000506,3,0.992302,0.992489,0.991856,0.991910,0.992030,0.992117,0.000241,2,0.981287,0.981736,0.980243,0.980374,0.980670,0.980862,0.000566,2,0.987770,0.988067,0.987070,0.987154,0.987346,0.987481,0.000380,2,0.991600,0.991905,0.991202,0.991374,0.991772,0.991571,0.000256,6,82.191420,1.288445,0.525131,0.026464
12,random_forest,randomized_search,unsw_nb15,235490,12,13,5,1,13,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 115, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.942886,0.944127,0.940348,0.940430,0.940184,0.941595,0.001611,6,0.999044,0.999257,0.999045,0.998832,0.999469,0.999129,0.000217,2,0.970153,0.970910,0.968808,0.968752,0.968920,0.969509,0.000870,3,0.999758,0.999811,0.999757,0.999703,0.999865,0.999779,0.000055,2,0.984872,0.985217,0.984155,0.984182,0.984102,0.984506,0.000454,6,0.992259,0.992461,0.991895,0.991882,0.991921,0.992084,0.000235,3,0.981206,0.981685,0.980351,0.980317,0.980421,0.980796,0.000553,3,0.987706,0.988025,0.987133,0.987112,0.987176,0.987430,0.000370,3,0.991958,0.992237,0.991600,0.991507,0.991786,0.991818,0.000261,1,48.723423,4.511895,0.382920,0.048048
8,random_forest,randomized_search,unsw_nb15,235490,12,13,5,1,9,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 275, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.943158,0.943542,0.940154,0.939960,0.940172,0.941397,0.001601,7,0.998832,0.998938,0.998938,0.998832,0.999257,0.998960,0.000156,8,0.970197,0.970450,0.968655,0.968502,0.968814,0.969324,0.000826,4,0.999704,0.999731,0.999730,0.999703,0.999811,0.999736,0.000040,8,0.984952,0.985058,0.984102,0.984049,0.984102,0.984453,0.000453,7,0.992273,0.992340,0.991855,0.991814,0.991894,0.992035,0.000224,4,0.981235,0.981395,0.980255,0.980158,0.980354,0.980680,0.000525,4,0.987728,0.987834,0.987070,0.987006,0.987133,0.987354,0.000352,4,0.991892,0.991998,0.991520,0.991441,0.991680,0.991706,0.000212,3,126.885208,4.930762,0.901655,0.042390
5,random_forest,randomized_search,unsw_nb15,235490,12,13,5,1,6,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": 1.0, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 186, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.943408,0.944088,0.940324,0.939942,0.940782,0.941709,0.001700,5,0.998195,0.998514,0.998620,0.998514,0.998408,0.998450,0.000144,9,0.970028,0.970538,0.968596,0.968343,0.968739,0.969249,0.000869,5,0.999542,0.999623,0.999650,0.999623,0.999596,0.999607,0.000036,9,0.985031,0.985217,0.984155,0.984049,0.984288,0.984548,0.000480,5,0.992234,0.992368,0.991842,0.991775,0.991883,0.992020,0.000236,5,0.981131,0.981453,0.980219,0.980059,0.980311,0.980634,0.000552,5,0.987664,0.987876,0.987048,0.986942,0.987112,0.987329,0.000371,5,0.991613,0.991865,0.991388,0.991281,0.991348,0.991499,0.000214,8,330.042970,6.999118,0.552596,0.025212
7,random_forest,randomized_search,unsw_nb15,235490,12,13,5,1,8,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 160, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.942508,0.942891,0.939415,0.939684,0.939527,0.940805,0.001554,8,0.999044,0.999151,0.999151,0.998938,0.999469,0.999151,0.000178,1,0.969953,0.970206,0.968363,0.968406,0.968572,0.969100,0.000807,6,0.999758,0.999784,0.999784,0.999730,0.999865,0.999784,0.000045,1,0.984766,0.984872,0.983890,0.983969,0.983916,0.984283,0.000440,8,0.992205,0.992272,0.991773,0.991787,0.991827,0.991973,0.000219,6,0.981079,0.981239,0.980068,0.980097,0.980199,0.980536,0.000513,6,0.987622,0.987728,0.986942,0.986963,0.987027,0.987256,0.000344,6,0.991905,0.992011,0.991520,0.991454,0.991693,0.991717,0.000215,2,69.214529,1.323090,0.474843,0.041874
11,random_forest,randomized_search,unsw_nb15,235490,12,13,5,1,12,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": 1.0, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 180, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.944271,0.944383,0.940411,0.940587,0.941194,0.942169,0.001781,4,0.996603,0.996921,0.996815,0.996603,0.997346,0.996858,0.000274,12,0.969731,0.969941,0.967792,0.967785,0.968457,0.968741,0.000929,7,0.999139,0.999219,0.999192,0.999138,0.999326,0.999203,0.000069,12,0.985297,0.985323,0.984208,0.984261,0.984421,0.984702,0.000501,4,0.992170,0.992223,0.991643,0.991644,0.991818,0.991899,0.000251,7,0.980950,0.981082,0.979718,0.979714,0.980137,0.980320,0.000590,7,0.987558,0.987643,0.986730,0.986730,0.987006,0.987133,0.000395,7,0.990950,0.991122,0.990512,0.990432,0.990883,0.990780,0.000264,12,237.625738,12.707817,0.355204,0.033424
3,random_forest,randomized_search,unsw_nb15,235490,12,13,5,1,4,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 30, ""classifier__max_features"": 0.5, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 278, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.942337,0.942502,0.937911,0.939397,0.938578,0.940145,0.001916,9,0.999363,0.998938,0.999045,0.998832,0.999257,0.999087,0.000197,5,0.970012,0.969900,0.967513,0.968203,0.967968,0.968719,0.001035,8,0.999838,0.999731,0.999757,0.999703,0.999811,0.999768,0.000050,5,0.984713,0.984766,0.983465,0.983890,0.983651,0.984097,0.000542,9,0.992218,0.992192,0.991544,0.991734,0.991665,0.991871,0.000280,8,0.981115,0.981046,0.979529,0.979968,0.979816,0.980295,0.000657,8,0.987643,0.987600,0.986581,0.986878,0.986772,0.987095,0.000441,8,0.992038,0.991852,0.991255,0.991361,0.991454,0.991592,0.000301,4,234.020165,4.674581,0.852861,0.052601
10,random_forest,randomized_search,unsw_nb15,235490,12,13,5,1,11,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced_subsample"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 296, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.941942,0.942325,0.938485,0.938741,0.938491,0.939997,0.001751,10,0.999044,0.999151,0.999257,0.998832,0.999363,0.999129,0.000183,3,0.969653,0.969906,0.967918,0.967855,0.967971,0.968661,0.000918,9,0.999757,0.999784,0.999811,0.999703,0.999838,0.999779,0.000046,3,0.984607,0.984713,0.983624,0.983704,0.983624,0.984055,0.000496,10,0.992124,0.992191,0.991652,0.991639,0.991665,0.991854,0.000249,9,0.980889,0.981049,0.979785,0.979747,0.979818,0.980257,0.000583,9,0.987494,0.987600,0.986751,0.986730,0.986772,0.987070,0.000392,9,0.991826,0.991932,0.991441,0.991268,0.991494,0.991592,0.000248,5,138.489251,1.786143,0.722499,0.031613
1,random_forest,randomized_search,unsw_nb15,235490,12,13,5,1,2,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 237, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.942225,0.942419,0.936990,0.939022,0.938110,0.939753,0.002195,11,0.999044,0.999151,0.999257,0.998832,0.999257,0.999108,0.000159,4,0.969803,0.969956,0.967122,0.968004,0.967719,0.968521,0.001146,10,0.999757,0.999784,0.999811,0.999703,0.999811,0.999773,0.000040,4,0.984686,0.984740,0.983200,0.983784,0.983518,0.983986,0.000622,11,0.992165,0.992205,0.991436,0.991680,0.991598,0.991817,0.000311,10,0.980984,0.981081,0.979279,0.979842,0.979658,0.980169,0.000729,10,0.987558,0.987622,0.986411,0.986793,0.986666,0.987010,0.000489,10,0.991865,0.991945,0.991228,0.991308,0.991388,0.991547,0.000298,7,110.212231,2.572811,0.743044,0.035721
9,random_forest,randomized_search,unsw_nb15,235490,12,13,5,1,10,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced_subsample"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 231, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.941282,0.941288,0.936412,0.938086,0.937369,0.938887,0.002029,13,0.999044,0.999151,0.998938,0.998832,0.999363,0.999066,0.000183,6,0.969304,0.969357,0.966665,0.967506,0.967374,0.968041,0.001091,11,0.999757,0.999784,0.999730,0.999703,0.999838,0.999763,0.000046,6,0.984421,0.984421,0.983041,0.983518,0.983306,0.983741,0.000575,13,0.992030,0.992043,0.991315,0.991545,0.991503,0.991687,0.000296,11,0.980667,0.980700,0.978990,0.979526,0.979439,0.979864,0.000693,11,0.987346,0.987367,0.986220,0.986581,0.986517,0.986806,0.000465,11,0.991733,0.991786,0.990989,0.991175,0.991334,0.991404,0.000311,9,107.391972,1.814946,0.626816,0.045997
6,random_forest,randomized_search,unsw_nb15,235490,12,13,5,1,7,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 163, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.941471,0.941471,0.936132,0.938273,0.937263,0.938922,0.002188,12,0.999044,0.999044,0.998938,0.998832,0.999151,0.999002,0.000108,7,0.969404,0.969404,0.966516,0.967606,0.967218,0.968029,0.001175,12,0.999757,0.999757,0.999730,0.999703,0.999784,0.999746,0.000028,7,0.984474,0.984474,0.982961,0.983571,0.983279,0.983752,0.000620,12,0.992057,0.992057,0.991275,0.991572,0.991463,0.991685,0.000318,12,0.980730,0.980730,0.978895,0.979589,0.979341,0.979857,0.000747,12,0.987388,0.987388,0.986157,0.986624,0.986454,0.986802,0.000501,12,0.991759,0.991759,0.990950,0.991202,0.991215,0.991377,0.000326,10,70.260382,1.562734,0.487325,0.037056
0,random_forest,randomized_search,unsw_nb15,235490,12,13,5,1,1,baseline,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 100, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.948645,0.949964,0.947315,0.946161,0.946505,0.947718,0.001412,1,0.988428,0.985667,0.986837,0.985032,0.986093,0.986411,0.001167,13,0.968128,0.967486,0.966672,0.965205,0.965894,0.966677,0.001053,13,0.997076,0.996383,0.996674,0.996219,0.996486,0.996568,0.000294,13,0.986624,0.987022,0.986278,0.985987,0.986066,0.986395,0.000383,1,0.991823,0.991680,0.991449,0.991076,0.991249,0.991455,0.000273,13,0.979975,0.979583,0.979060,0.978141,0.978571,0.979066,0.000663,13,0.986985,0.986751,0.986390,0.985796,0.986072,0.986399,0.000433,13,0.987526,0.986345,0.986557,0.985509,0.986080,0.986403,0.000662,13,51.928019,1.072577,0.397204,0.006173

modelo: random_forest
 origem do treinamento: iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: random_forest - iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
4,random_forest,randomized_search,iot23,235490,12,13,5,1,5,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 168, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.999573,0.999893,0.999679,1.000000,0.999893,0.999808,0.000157,1,0.993948,0.992037,0.992463,0.994586,0.993737,0.993354,0.000953,12,0.996753,0.995950,0.996058,0.997286,0.996805,0.996570,0.000500,1,0.998489,0.998013,0.998119,0.998648,0.998437,0.998341,0.000238,12,0.999894,0.999973,0.999920,1.000000,0.999973,0.999952,0.000039,1,0.999191,0.998992,0.999019,0.999324,0.999204,0.999146,0.000124,1,0.997972,0.997471,0.997538,0.998305,0.998005,0.997858,0.000312,1,0.998705,0.998386,0.998429,0.998917,0.998726,0.998633,0.000199,1,0.996921,0.996005,0.996192,0.997293,0.996855,0.996653,0.000481,12,54.759309,2.190026,0.485483,0.022149
11,random_forest,randomized_search,iot23,235490,12,13,5,1,12,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": 1.0, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 180, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.999680,0.999679,0.999465,0.999787,0.999786,0.999679,0.000117,2,0.993948,0.991931,0.992251,0.994268,0.993524,0.993184,0.000929,13,0.996806,0.995790,0.995845,0.997019,0.996646,0.996421,0.000507,2,0.998489,0.997987,0.998066,0.998569,0.998384,0.998299,0.000231,13,0.999920,0.999920,0.999867,0.999947,0.999947,0.999920,0.000029,2,0.999204,0.998953,0.998966,0.999257,0.999165,0.999109,0.000126,2,0.998005,0.997371,0.997405,0.998138,0.997905,0.997765,0.000317,2,0.998726,0.998323,0.998344,0.998811,0.998662,0.998573,0.000202,2,0.996934,0.995926,0.996059,0.997107,0.996736,0.996552,0.000474,13,101.862454,3.683951,0.333204,0.027949
0,random_forest,randomized_search,iot23,235490,12,13,5,1,1,baseline,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 100, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.998827,0.999358,0.999359,0.999254,0.998933,0.999146,0.000223,3,0.994161,0.992250,0.992675,0.994904,0.994161,0.993630,0.001001,11,0.996488,0.995791,0.996006,0.997074,0.996542,0.996380,0.000449,3,0.998542,0.998066,0.998172,0.998727,0.998542,0.998410,0.000249,11,0.999708,0.999841,0.999841,0.999814,0.999735,0.999788,0.000056,3,0.999125,0.998953,0.999006,0.999271,0.999138,0.999098,0.000111,3,0.997806,0.997372,0.997506,0.998172,0.997840,0.997739,0.000280,3,0.998599,0.998323,0.998408,0.998832,0.998620,0.998556,0.000178,3,0.996934,0.996045,0.996258,0.997359,0.996948,0.996709,0.000485,11,35.495490,2.902541,0.346623,0.011645
12,random_forest,randomized_search,iot23,235490,12,13,5,1,13,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 115, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.989064,0.987702,0.989465,0.988749,0.986888,0.988374,0.000945,4,0.998620,0.997664,0.997028,0.998195,0.998726,0.998047,0.000632,7,0.993819,0.992658,0.993232,0.993450,0.992772,0.993186,0.000430,4,0.999654,0.999415,0.999255,0.999548,0.999681,0.999511,0.000158,6,0.997240,0.996895,0.997346,0.997160,0.996682,0.997065,0.000242,4,0.998446,0.998153,0.998300,0.998353,0.998179,0.998286,0.000109,4,0.996132,0.995406,0.995766,0.995901,0.995475,0.995736,0.000269,4,0.997516,0.997049,0.997282,0.997367,0.997091,0.997261,0.000174,4,0.997930,0.997280,0.997187,0.997678,0.997704,0.997556,0.000279,1,34.831465,2.415810,0.340936,0.030970
2,random_forest,randomized_search,iot23,235490,12,13,5,1,3,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 171, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.988958,0.987391,0.989880,0.988749,0.986783,0.988352,0.001118,5,0.998407,0.997664,0.996815,0.998195,0.998620,0.997940,0.000646,9,0.993660,0.992501,0.993335,0.993450,0.992666,0.993122,0.000455,5,0.999601,0.999415,0.999202,0.999548,0.999654,0.999484,0.000162,9,0.997213,0.996815,0.997452,0.997160,0.996656,0.997059,0.000287,5,0.998406,0.998113,0.998326,0.998353,0.998153,0.998270,0.000116,5,0.996033,0.995307,0.995831,0.995901,0.995409,0.995696,0.000285,5,0.997452,0.996985,0.997325,0.997367,0.997049,0.997236,0.000184,5,0.997810,0.997240,0.997134,0.997678,0.997638,0.997500,0.000264,7,55.761783,2.876716,0.507790,0.021924
8,random_forest,randomized_search,iot23,235490,12,13,5,1,9,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 275, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.988856,0.987704,0.989778,0.988541,0.986265,0.988229,0.001185,6,0.998620,0.997770,0.997028,0.998195,0.998620,0.998047,0.000599,6,0.993714,0.992712,0.993389,0.993345,0.992404,0.993113,0.000481,6,0.999654,0.999441,0.999255,0.999548,0.999654,0.999510,0.000150,7,0.997187,0.996895,0.997426,0.997107,0.996523,0.997027,0.000304,7,0.998419,0.998166,0.998340,0.998326,0.998086,0.998267,0.000122,6,0.996066,0.995439,0.995865,0.995835,0.995245,0.995690,0.000301,6,0.997473,0.997070,0.997346,0.997325,0.996943,0.997231,0.000195,6,0.997903,0.997333,0.997227,0.997651,0.997572,0.997537,0.000239,2,87.432947,2.086154,0.752229,0.047145
7,random_forest,randomized_search,iot23,235490,12,13,5,1,8,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 160, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.988959,0.987287,0.989567,0.988750,0.986576,0.988228,0.001115,7,0.998514,0.997664,0.996815,0.998301,0.998620,0.997983,0.000671,8,0.993713,0.992449,0.993178,0.993503,0.992561,0.993081,0.000501,7,0.999628,0.999415,0.999202,0.999574,0.999654,0.999495,0.000168,8,0.997213,0.996789,0.997372,0.997160,0.996603,0.997027,0.000286,6,0.998419,0.998100,0.998287,0.998366,0.998126,0.998259,0.000127,7,0.996066,0.995274,0.995732,0.995934,0.995344,0.995670,0.000314,7,0.997473,0.996964,0.997261,0.997388,0.997006,0.997219,0.000203,7,0.997863,0.997226,0.997094,0.997731,0.997611,0.997505,0.000296,5,47.845441,1.094722,0.476247,0.026576
5,random_forest,randomized_search,iot23,235490,12,13,5,1,6,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": 1.0, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 186, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.988541,0.987286,0.989566,0.988851,0.986678,0.988184,0.001054,8,0.998301,0.997558,0.996709,0.998089,0.998514,0.997834,0.000646,10,0.993397,0.992395,0.993125,0.993449,0.992561,0.992985,0.000432,8,0.999574,0.999388,0.999176,0.999521,0.999627,0.999457,0.000162,10,0.997107,0.996789,0.997372,0.997187,0.996629,0.997017,0.000270,8,0.998339,0.998087,0.998273,0.998353,0.998126,0.998236,0.000110,8,0.995868,0.995241,0.995699,0.995901,0.995343,0.995610,0.000271,8,0.997346,0.996943,0.997240,0.997367,0.997006,0.997180,0.000175,8,0.997704,0.997173,0.997041,0.997638,0.997572,0.997426,0.000267,10,124.900504,3.880966,0.506708,0.026334
10,random_forest,randomized_search,iot23,235490,12,13,5,1,11,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced_subsample"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 296, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.988234,0.987496,0.989464,0.988335,0.985955,0.987897,0.001157,9,0.998726,0.997770,0.996921,0.998408,0.998620,0.998089,0.000671,4,0.993452,0.992607,0.993179,0.993346,0.992247,0.992966,0.000463,9,0.999681,0.999441,0.999229,0.999601,0.999654,0.999521,0.000168,4,0.997028,0.996842,0.997346,0.997054,0.996444,0.996943,0.000297,9,0.998352,0.998140,0.998287,0.998326,0.998046,0.998230,0.000118,9,0.995902,0.995373,0.995733,0.995836,0.995147,0.995598,0.000290,9,0.997367,0.997027,0.997261,0.997325,0.996879,0.997172,0.000188,9,0.997877,0.997306,0.997134,0.997731,0.997532,0.997516,0.000271,4,96.644311,2.952577,0.660208,0.048605
3,random_forest,randomized_search,iot23,235490,12,13,5,1,4,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 30, ""classifier__max_features"": 0.5, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 278, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.987508,0.987185,0.989256,0.988127,0.985542,0.987524,0.001217,10,0.998726,0.997770,0.997028,0.998301,0.998620,0.998089,0.000626,4,0.993085,0.992449,0.993127,0.993188,0.992038,0.992777,0.000456,10,0.999681,0.999441,0.999255,0.999574,0.999654,0.999521,0.000157,5,0.996842,0.996762,0.997293,0.997001,0.996337,0.996847,0.000313,10,0.998259,0.998100,0.998273,0.998286,0.997993,0.998182,0.000116,10,0.995672,0.995275,0.995700,0.995737,0.995015,0.995480,0.000286,10,0.997219,0.996964,0.997240,0.997261,0.996794,0.997095,0.000185,10,0.997784,0.997266,0.997160,0.997651,0.997479,0.997468,0.000232,9,121.307293,1.243187,0.746791,0.034265
1,random_forest,randomized_search,iot23,235490,12,13,5,1,2,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 237, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.987509,0.987087,0.988946,0.987816,0.985437,0.987359,0.001142,13,0.998832,0.998195,0.997240,0.998408,0.998514,0.998238,0.000540,1,0.993138,0.992610,0.993076,0.993084,0.991933,0.992768,0.000459,11,0.999707,0.999548,0.999308,0.999601,0.999627,0.999558,0.000135,1,0.996842,0.996736,0.997213,0.996921,0.996311,0.996805,0.000293,13,0.998272,0.998140,0.998260,0.998259,0.997966,0.998179,0.000117,11,0.995705,0.995375,0.995668,0.995672,0.994949,0.995474,0.000288,11,0.997240,0.997027,0.997219,0.997219,0.996751,0.997091,0.000187,11,0.997837,0.997465,0.997227,0.997664,0.997412,0.997521,0.000211,3,75.518778,3.234995,0.644407,0.036808
9,random_forest,randomized_search,iot23,235490,12,13,5,1,10,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced_subsample"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 231, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.987509,0.986983,0.988842,0.988128,0.985434,0.987379,0.001154,12,0.998832,0.998195,0.997240,0.998408,0.998301,0.998195,0.000524,2,0.993138,0.992557,0.993023,0.993241,0.991826,0.992757,0.000521,12,0.999707,0.999548,0.999308,0.999601,0.999574,0.999548,0.000131,2,0.996842,0.996709,0.997187,0.997001,0.996311,0.996810,0.000296,12,0.998272,0.998126,0.998246,0.998299,0.997940,0.998177,0.000132,13,0.995705,0.995342,0.995635,0.995770,0.994883,0.995467,0.000327,12,0.997240,0.997006,0.997197,0.997282,0.996709,0.997087,0.000211,13,0.997837,0.997452,0.997213,0.997704,0.997306,0.997503,0.000235,6,76.660016,2.437979,0.600075,0.022822
6,random_forest,randomized_search,iot23,235490,12,13,5,1,7,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 163, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.987613,0.987087,0.989152,0.987713,0.985436,0.987400,0.001197,11,0.998832,0.998195,0.997028,0.998408,0.998408,0.998174,0.000609,3,0.993191,0.992610,0.993074,0.993031,0.991879,0.992757,0.000481,13,0.999707,0.999548,0.999255,0.999601,0.999601,0.999542,0.000153,3,0.996868,0.996736,0.997266,0.996895,0.996311,0.996815,0.000308,11,0.998286,0.998140,0.998260,0.998246,0.997953,0.998177,0.000122,12,0.995738,0.995375,0.995667,0.995639,0.994916,0.995467,0.000302,13,0.997261,0.997027,0.997219,0.997197,0.996730,0.997087,0.000195,12,0.997850,0.997465,0.997147,0.997651,0.997359,0.997495,0.000241,8,46.255019,0.740651,0.445098,0.011265

modelo: random_forest
 origem do treinamento: cicids2017_unsw_nb15
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: random_forest - cicids2017_unsw_nb15

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
2,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,3,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 171, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.959283,0.960817,0.963743,0.961454,0.958710,0.960801,0.001775,2,0.994267,0.995806,0.996072,0.995594,0.995807,0.995509,0.000639,5,0.976462,0.977999,0.979641,0.978226,0.976906,0.977847,0.001113,1,0.998554,0.998942,0.999010,0.998889,0.998941,0.998867,0.000161,5,0.989450,0.989848,0.990631,0.990021,0.989278,0.989846,0.000475,2,0.993981,0.994374,0.994803,0.994435,0.994086,0.994336,0.000289,1,0.985221,0.986187,0.987222,0.986331,0.985496,0.986091,0.000701,1,0.990414,0.991040,0.991719,0.991136,0.990583,0.990978,0.000459,1,0.991859,0.992827,0.993352,0.992808,0.992542,0.992677,0.000486,5,221.196921,4.737212,1.395986,0.074239
12,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,13,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 115, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.957751,0.959359,0.962030,0.959969,0.956832,0.959188,0.001808,4,0.996390,0.997452,0.997877,0.996656,0.997665,0.997208,0.000581,2,0.976689,0.978035,0.979626,0.977969,0.976822,0.977828,0.001059,2,0.999088,0.999357,0.999464,0.999156,0.999410,0.999295,0.000147,2,0.989012,0.989437,0.990153,0.989609,0.988747,0.989392,0.000488,4,0.994025,0.994372,0.994787,0.994360,0.994050,0.994319,0.000277,2,0.985357,0.986203,0.987206,0.986164,0.985436,0.986073,0.000668,2,0.990488,0.991040,0.991698,0.991019,0.990530,0.990955,0.000439,2,0.992701,0.993445,0.994015,0.993133,0.993206,0.993300,0.000431,1,131.174705,16.065824,0.803045,0.083145
8,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,9,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 275, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.957751,0.959408,0.962072,0.959734,0.956922,0.959177,0.001781,5,0.996390,0.997452,0.997665,0.996921,0.997505,0.997187,0.000470,4,0.976689,0.978060,0.979545,0.977974,0.976793,0.977812,0.001039,3,0.999088,0.999357,0.999411,0.999223,0.999370,0.999290,0.000119,4,0.989012,0.989450,0.990167,0.989543,0.988773,0.989389,0.000480,5,0.994025,0.994379,0.994767,0.994359,0.994043,0.994315,0.000271,3,0.985357,0.986219,0.987156,0.986167,0.985418,0.986063,0.000655,3,0.990488,0.991051,0.991666,0.991019,0.990520,0.990949,0.000430,3,0.992701,0.993451,0.993916,0.993232,0.993139,0.993288,0.000397,2,355.606744,6.985136,2.071268,0.100395
3,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,4,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 30, ""classifier__max_features"": 0.5, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 278, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.956311,0.957904,0.960556,0.958225,0.955814,0.957762,0.001670,9,0.996974,0.997770,0.997877,0.997134,0.997771,0.997505,0.000374,1,0.976220,0.977431,0.978861,0.977292,0.976342,0.977229,0.000950,4,0.999235,0.999437,0.999464,0.999276,0.999436,0.999370,0.000094,1,0.988614,0.989039,0.989755,0.989132,0.988468,0.989002,0.000452,9,0.993897,0.994211,0.994586,0.994178,0.993922,0.994159,0.000249,4,0.985058,0.985821,0.986723,0.985735,0.985132,0.985694,0.000600,4,0.990286,0.990785,0.991380,0.990732,0.990329,0.990702,0.000395,4,0.992794,0.993405,0.993816,0.993133,0.993119,0.993253,0.000341,3,642.926861,3.873772,1.907889,0.012549
1,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,2,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 237, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.955906,0.958180,0.960693,0.958506,0.955856,0.957828,0.001810,8,0.996603,0.997346,0.997611,0.996815,0.997611,0.997197,0.000416,3,0.975830,0.977371,0.978804,0.977285,0.976288,0.977116,0.001028,5,0.999142,0.999330,0.999397,0.999196,0.999396,0.999292,0.000105,3,0.988508,0.989119,0.989795,0.989211,0.988481,0.989023,0.000490,8,0.993796,0.994198,0.994573,0.994178,0.993909,0.994131,0.000270,5,0.984813,0.985784,0.986689,0.985732,0.985098,0.985623,0.000649,5,0.990127,0.990764,0.991358,0.990732,0.990307,0.990658,0.000427,5,0.992555,0.993232,0.993703,0.993013,0.993046,0.993110,0.000371,4,292.938000,5.739411,1.640352,0.047015
4,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,5,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 168, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.958872,0.960697,0.963235,0.960643,0.958863,0.960462,0.001604,3,0.992568,0.992621,0.994321,0.992410,0.993471,0.993078,0.000723,6,0.975429,0.976398,0.978531,0.976268,0.975860,0.976497,0.001072,6,0.998126,0.998140,0.998569,0.998087,0.998353,0.998255,0.000182,6,0.989357,0.989848,0.990512,0.989835,0.989344,0.989779,0.000427,3,0.993722,0.993977,0.994524,0.993944,0.993828,0.993999,0.000277,6,0.984576,0.985188,0.986527,0.985106,0.984844,0.985248,0.000675,6,0.990000,0.990403,0.991274,0.990350,0.990169,0.990439,0.000441,6,0.990963,0.991235,0.992416,0.991122,0.991408,0.991429,0.000515,6,219.023786,4.833807,1.185199,0.035309
0,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,1,baseline,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 100, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.962769,0.964817,0.967365,0.965440,0.962261,0.964530,0.001854,1,0.986994,0.988428,0.988057,0.987527,0.989331,0.988067,0.000796,12,0.974731,0.976480,0.977602,0.976359,0.975608,0.976156,0.000955,7,0.996728,0.997089,0.996998,0.996864,0.997314,0.996999,0.000199,12,0.990459,0.990990,0.991666,0.991162,0.990299,0.990915,0.000494,1,0.993584,0.994030,0.994325,0.994005,0.993794,0.993948,0.000248,7,0.984158,0.985255,0.985963,0.985182,0.984701,0.985052,0.000602,7,0.989766,0.990477,0.990944,0.990435,0.990106,0.990346,0.000394,7,0.988727,0.989709,0.989862,0.989344,0.989815,0.989491,0.000423,11,132.837835,1.624668,0.880006,0.027349
7,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,8,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 160, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.956017,0.958278,0.960418,0.958515,0.956042,0.957854,0.001664,6,0.992303,0.992462,0.994268,0.992144,0.992781,0.992792,0.000767,10,0.973822,0.975070,0.977050,0.975040,0.974065,0.975009,0.001138,8,0.998057,0.998099,0.998554,0.998019,0.998178,0.998181,0.000194,10,0.988588,0.989198,0.989755,0.989264,0.988588,0.989079,0.000445,7,0.993300,0.993629,0.994135,0.993622,0.993359,0.993609,0.000295,8,0.983561,0.984349,0.985593,0.984331,0.983712,0.984309,0.000716,8,0.989331,0.989851,0.990658,0.989840,0.989426,0.989821,0.000469,8,0.990445,0.990830,0.992011,0.990704,0.990684,0.990935,0.000552,8,174.174190,4.092602,1.009297,0.080953
10,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,11,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced_subsample"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 296, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.955347,0.957657,0.960226,0.958165,0.955769,0.957433,0.001761,10,0.992621,0.992887,0.994374,0.991985,0.993259,0.993025,0.000792,7,0.973627,0.974954,0.977001,0.974782,0.974153,0.974903,0.001150,9,0.998137,0.998205,0.998581,0.997978,0.998298,0.998240,0.000200,7,0.988402,0.989026,0.989702,0.989171,0.988508,0.988962,0.000472,10,0.993246,0.993594,0.994122,0.993555,0.993379,0.993579,0.000299,9,0.983437,0.984274,0.985561,0.984168,0.983766,0.984241,0.000724,9,0.989246,0.989798,0.990637,0.989734,0.989458,0.989775,0.000474,9,0.990512,0.990956,0.992038,0.990578,0.990883,0.990994,0.000549,7,350.109981,3.517276,1.620993,0.020941
9,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,10,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced_subsample"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 231, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.954991,0.957243,0.959588,0.957921,0.955075,0.956964,0.001752,11,0.992303,0.992356,0.994427,0.992038,0.992994,0.992823,0.000861,9,0.973290,0.974483,0.976697,0.974681,0.973665,0.974563,0.001183,10,0.998057,0.998071,0.998594,0.997992,0.998231,0.998189,0.000217,8,0.988309,0.988920,0.989530,0.989105,0.988322,0.988837,0.000470,11,0.993159,0.993474,0.994041,0.993528,0.993252,0.993491,0.000307,10,0.983224,0.983979,0.985369,0.984105,0.983458,0.984027,0.000745,10,0.989108,0.989607,0.990509,0.989692,0.989256,0.989634,0.000488,10,0.990306,0.990638,0.991978,0.990572,0.990658,0.990830,0.000588,9,268.778218,5.862060,1.396708,0.066947
6,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,7,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 163, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.954845,0.957198,0.959639,0.958019,0.955019,0.956944,0.001822,12,0.992303,0.992462,0.994480,0.992038,0.992834,0.992823,0.000867,8,0.973214,0.974511,0.976749,0.974732,0.973560,0.974553,0.001236,11,0.998057,0.998098,0.998607,0.997992,0.998191,0.998189,0.000219,9,0.988269,0.988906,0.989543,0.989132,0.988309,0.988832,0.000488,12,0.993139,0.993481,0.994054,0.993542,0.993225,0.993488,0.000321,11,0.983176,0.983996,0.985402,0.984137,0.983392,0.984021,0.000778,11,0.989076,0.989617,0.990530,0.989713,0.989214,0.989630,0.000509,11,0.990286,0.990684,0.992011,0.990585,0.990572,0.990828,0.000607,10,173.641611,3.472154,0.959920,0.012466
11,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,12,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": 1.0, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 180, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.956222,0.958288,0.960279,0.958183,0.956244,0.957843,0.001512,7,0.985561,0.985402,0.986783,0.985138,0.984820,0.985541,0.000670,13,0.970670,0.971656,0.973351,0.971473,0.970321,0.971494,0.001052,12,0.996363,0.996325,0.996673,0.996258,0.996176,0.996359,0.000169,13,0.988721,0.989278,0.989795,0.989251,0.988733,0.989156,0.000400,6,0.992527,0.992789,0.993222,0.992742,0.992441,0.992744,0.000272,12,0.981598,0.982222,0.983286,0.982108,0.981381,0.982119,0.000662,12,0.988089,0.988503,0.989193,0.988428,0.987951,0.988433,0.000432,12,0.987141,0.987340,0.988289,0.987195,0.986777,0.987348,0.000506,13,562.664335,12.092950,0.762805,0.055405

modelo: random_forest
 origem do treinamento: cicids2017_iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: random_forest - cicids2017_iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
0,random_forest,randomized_search,cicids2017_iot23,470980,12,13,5,1,1,baseline,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 100, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.989428,0.989426,0.991259,0.989625,0.988378,0.989623,0.000928,1,0.993630,0.993471,0.993206,0.992357,0.993047,0.993142,0.000442,11,0.991525,0.991444,0.992232,0.990989,0.990707,0.991379,0.000521,1,0.998406,0.998366,0.998301,0.998088,0.998260,0.998284,0.000110,11,0.997346,0.997346,0.997810,0.997399,0.997081,0.997396,0.000235,1,0.997876,0.997856,0.998055,0.997743,0.997670,0.997840,0.000131,1,0.994700,0.994650,0.995144,0.994366,0.994188,0.994610,0.000326,1,0.996603,0.996571,0.996889,0.996391,0.996274,0.996546,0.000210,1,0.995488,0.995408,0.995508,0.994878,0.995064,0.995269,0.000253,7,121.606984,2.665830,0.774025,0.038989
4,random_forest,randomized_search,cicids2017_iot23,470980,12,13,5,1,5,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 168, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.988952,0.988424,0.990211,0.988787,0.988051,0.988885,0.000732,2,0.993152,0.992621,0.993259,0.992304,0.991932,0.992654,0.000502,12,0.991048,0.990518,0.991732,0.990542,0.989988,0.990766,0.000588,2,0.998286,0.998154,0.998313,0.998074,0.997981,0.998162,0.000126,12,0.997227,0.997094,0.997545,0.997187,0.997001,0.997211,0.000185,2,0.997756,0.997623,0.997929,0.997630,0.997491,0.997686,0.000148,2,0.994402,0.994071,0.994831,0.994086,0.993739,0.994226,0.000368,2,0.996412,0.996199,0.996688,0.996210,0.995987,0.996299,0.000236,2,0.995189,0.994858,0.995402,0.994745,0.994466,0.994932,0.000330,11,192.833376,2.180078,1.097328,0.053442
2,random_forest,randomized_search,cicids2017_iot23,470980,12,13,5,1,3,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 171, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.983765,0.982689,0.984388,0.983035,0.981406,0.983057,0.001013,4,0.997133,0.997452,0.997346,0.996497,0.997346,0.997155,0.000345,5,0.990404,0.990016,0.990825,0.989720,0.989312,0.990055,0.000525,3,0.999281,0.999361,0.999334,0.999121,0.999334,0.999286,0.000086,5,0.995886,0.995608,0.996045,0.995700,0.995276,0.995703,0.000262,4,0.997581,0.997481,0.997687,0.997408,0.997301,0.997491,0.000134,3,0.993992,0.993748,0.994256,0.993564,0.993306,0.993773,0.000330,3,0.996136,0.995976,0.996306,0.995860,0.995690,0.995993,0.000214,3,0.996510,0.996530,0.996696,0.996099,0.996311,0.996429,0.000205,5,188.811260,2.182126,1.231482,0.045596
12,random_forest,randomized_search,cicids2017_iot23,470980,12,13,5,1,13,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 115, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.983000,0.982129,0.983879,0.982014,0.981003,0.982405,0.000972,5,0.997611,0.997717,0.997718,0.996921,0.997718,0.997537,0.000311,4,0.990252,0.989862,0.990750,0.989412,0.989290,0.989913,0.000540,4,0.999401,0.999427,0.999427,0.999227,0.999427,0.999382,0.000078,4,0.995687,0.995462,0.995913,0.995435,0.995170,0.995533,0.000251,5,0.997540,0.997440,0.997667,0.997328,0.997294,0.997454,0.000138,4,0.993896,0.993651,0.994208,0.993370,0.993292,0.993683,0.000339,4,0.996072,0.995913,0.996274,0.995732,0.995679,0.995934,0.000219,4,0.996649,0.996590,0.996815,0.996178,0.996444,0.996535,0.000215,1,120.749733,7.740956,0.754915,0.080325
8,random_forest,randomized_search,cicids2017_iot23,470980,12,13,5,1,9,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 275, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.982951,0.981672,0.983931,0.982164,0.980643,0.982272,0.001117,7,0.997717,0.997983,0.997771,0.996709,0.997611,0.997558,0.000441,3,0.990279,0.989760,0.990802,0.989383,0.989054,0.989856,0.000625,5,0.999427,0.999494,0.999441,0.999174,0.999400,0.999387,0.000111,3,0.995674,0.995342,0.995926,0.995475,0.995077,0.995499,0.000289,7,0.997547,0.997414,0.997680,0.997321,0.997234,0.997439,0.000159,5,0.993913,0.993587,0.994241,0.993352,0.993144,0.993648,0.000392,5,0.996083,0.995870,0.996295,0.995722,0.995584,0.995911,0.000254,5,0.996696,0.996663,0.996848,0.996092,0.996344,0.996529,0.000273,2,313.516357,5.461070,1.820809,0.066039
1,random_forest,randomized_search,cicids2017_iot23,470980,12,13,5,1,2,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 237, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.981875,0.980752,0.982749,0.981353,0.979623,0.981270,0.001053,11,0.997877,0.998089,0.997824,0.997240,0.997718,0.997749,0.000282,1,0.989811,0.989345,0.990229,0.989233,0.988587,0.989441,0.000555,6,0.999467,0.999520,0.999454,0.999307,0.999427,0.999435,0.000071,1,0.995395,0.995103,0.995621,0.995262,0.994811,0.995239,0.000273,11,0.997427,0.997307,0.997534,0.997281,0.997114,0.997332,0.000142,6,0.993619,0.993326,0.993881,0.993257,0.992851,0.993387,0.000348,6,0.995892,0.995700,0.996061,0.995658,0.995393,0.995741,0.000226,6,0.996636,0.996596,0.996722,0.996251,0.996264,0.996494,0.000197,3,261.006330,4.078244,1.528854,0.077989
3,random_forest,randomized_search,cicids2017_iot23,470980,12,13,5,1,4,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 30, ""classifier__max_features"": 0.5, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 278, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.982028,0.980853,0.982546,0.980841,0.979673,0.981188,0.001008,12,0.997824,0.997983,0.997983,0.997240,0.997665,0.997739,0.000276,2,0.989863,0.989344,0.990204,0.988972,0.988587,0.989394,0.000585,7,0.999454,0.999494,0.999494,0.999307,0.999413,0.999432,0.000069,2,0.995435,0.995130,0.995568,0.995130,0.994825,0.995217,0.000261,12,0.997440,0.997307,0.997527,0.997214,0.997114,0.997320,0.000149,7,0.993652,0.993325,0.993866,0.993093,0.992850,0.993357,0.000367,7,0.995913,0.995700,0.996051,0.995552,0.995393,0.995722,0.000238,7,0.996629,0.996556,0.996775,0.996185,0.996245,0.996478,0.000227,4,520.796540,7.695003,1.768246,0.080315
10,random_forest,randomized_search,cicids2017_iot23,470980,12,13,5,1,11,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced_subsample"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 296, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.982711,0.981520,0.983589,0.982181,0.980437,0.982088,0.001067,8,0.995700,0.995276,0.995701,0.994745,0.994904,0.995265,0.000395,7,0.989163,0.988350,0.989608,0.988423,0.987618,0.988632,0.000691,8,0.998922,0.998815,0.998922,0.998682,0.998721,0.998812,0.000099,7,0.995621,0.995316,0.995846,0.995488,0.995037,0.995462,0.000274,8,0.997269,0.997062,0.997382,0.997082,0.996876,0.997134,0.000175,8,0.993216,0.992706,0.993495,0.992753,0.992247,0.992883,0.000433,8,0.995637,0.995308,0.995817,0.995340,0.995010,0.995422,0.000280,8,0.995661,0.995296,0.995774,0.995117,0.994971,0.995363,0.000309,6,296.079667,8.831327,1.444841,0.069361
7,random_forest,randomized_search,cicids2017_iot23,470980,12,13,5,1,8,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 160, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.982911,0.981711,0.983897,0.982225,0.980688,0.982287,0.001084,6,0.995382,0.994479,0.995648,0.994321,0.994586,0.994883,0.000529,9,0.989107,0.988054,0.989738,0.988236,0.987588,0.988545,0.000773,9,0.998842,0.998615,0.998909,0.998576,0.998642,0.998717,0.000133,9,0.995674,0.995369,0.995926,0.995501,0.995103,0.995515,0.000278,6,0.997255,0.996989,0.997415,0.997036,0.996869,0.997113,0.000196,9,0.993181,0.992522,0.993576,0.992636,0.992229,0.992829,0.000485,9,0.995616,0.995191,0.995870,0.995265,0.995000,0.995388,0.000313,9,0.995528,0.994924,0.995787,0.994911,0.994845,0.995199,0.000384,8,144.450866,3.336966,0.916222,0.040084
9,random_forest,randomized_search,cicids2017_iot23,470980,12,13,5,1,10,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced_subsample"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 231, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.982553,0.981261,0.983426,0.981652,0.980283,0.981835,0.001079,9,0.995488,0.995169,0.995223,0.993949,0.994904,0.994947,0.000532,8,0.988978,0.988166,0.989289,0.987762,0.987540,0.988347,0.000680,10,0.998868,0.998788,0.998802,0.998482,0.998721,0.998732,0.000133,8,0.995581,0.995249,0.995807,0.995355,0.994997,0.995398,0.000278,10,0.997222,0.997016,0.997302,0.996916,0.996856,0.997062,0.000173,10,0.993100,0.992591,0.993296,0.992339,0.992198,0.992705,0.000426,10,0.995562,0.995233,0.995690,0.995074,0.994979,0.995308,0.000275,10,0.995534,0.995209,0.995515,0.994652,0.994951,0.995172,0.000337,9,231.266716,5.832798,1.247808,0.047467
6,random_forest,randomized_search,cicids2017_iot23,470980,12,13,5,1,7,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 163, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.982494,0.981261,0.983432,0.981498,0.980482,0.981834,0.001025,10,0.995063,0.995169,0.995594,0.993949,0.994586,0.994872,0.000562,10,0.988739,0.988166,0.989476,0.987684,0.987484,0.988310,0.000726,11,0.998762,0.998788,0.998895,0.998482,0.998642,0.998714,0.000141,10,0.995568,0.995249,0.995807,0.995316,0.995050,0.995398,0.000263,9,0.997162,0.997016,0.997348,0.996896,0.996843,0.997053,0.000184,11,0.992950,0.992591,0.993412,0.992290,0.992163,0.992681,0.000455,11,0.995467,0.995233,0.995764,0.995042,0.994957,0.995293,0.000294,11,0.995315,0.995209,0.995701,0.994632,0.994818,0.995135,0.000377,10,148.103265,3.375610,0.932067,0.052026
11,random_forest,randomized_search,cicids2017_iot23,470980,12,13,5,1,12,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": 1.0, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 180, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.988288,0.987691,0.989082,0.987667,0.987470,0.988040,0.000589,3,0.985455,0.983969,0.985775,0.981900,0.983015,0.984023,0.001459,13,0.986869,0.985826,0.987426,0.984775,0.985237,0.986027,0.000990,12,0.996367,0.995996,0.996447,0.995481,0.995758,0.996010,0.000364,13,0.997081,0.996935,0.997280,0.996935,0.996881,0.997022,0.000145,3,0.996723,0.996465,0.996863,0.996207,0.996320,0.996516,0.000245,12,0.991796,0.991146,0.992144,0.990491,0.990778,0.991271,0.000617,12,0.994756,0.994342,0.994979,0.993928,0.994108,0.994422,0.000393,12,0.991268,0.990452,0.991527,0.989417,0.989948,0.990522,0.000790,13,419.240042,11.313371,0.651743,0.060237

modelo: random_forest
 origem do treinamento: unsw_nb15_iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: random_forest - unsw_nb15_iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
4,random_forest,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,5,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 168, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.971081,0.971501,0.970067,0.969163,0.969467,0.970256,0.000904,2,0.994638,0.995276,0.995966,0.995913,0.996019,0.995562,0.000535,11,0.982718,0.983245,0.982846,0.982356,0.982564,0.982746,0.000298,1,0.998652,0.998812,0.998985,0.998971,0.998998,0.998883,0.000134,11,0.992595,0.992702,0.992316,0.992078,0.992157,0.992370,0.000243,2,0.995614,0.995747,0.995639,0.995512,0.995566,0.995616,0.000079,1,0.989166,0.989496,0.989243,0.988934,0.989065,0.989181,0.000188,1,0.993004,0.993216,0.993046,0.992845,0.992930,0.993008,0.000125,1,0.993617,0.993989,0.994141,0.993995,0.994088,0.993966,0.000184,11,163.605585,2.645615,1.068659,0.033753
0,random_forest,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,1,baseline,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 100, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.972873,0.973720,0.972487,0.972157,0.972209,0.972689,0.000575,1,0.989967,0.989330,0.990605,0.989650,0.989703,0.989851,0.000428,13,0.981346,0.981463,0.981462,0.980825,0.980878,0.981195,0.000284,2,0.997481,0.997322,0.997640,0.997401,0.997414,0.997452,0.000107,13,0.993100,0.993325,0.992993,0.992914,0.992927,0.993052,0.000152,1,0.995285,0.995320,0.995311,0.995152,0.995165,0.995247,0.000073,2,0.988315,0.988391,0.988387,0.987989,0.988022,0.988221,0.000178,2,0.992473,0.992526,0.992516,0.992261,0.992282,0.992412,0.000116,2,0.991533,0.991328,0.991799,0.991282,0.991315,0.991451,0.000195,13,106.162437,2.666458,0.798962,0.020932
11,random_forest,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,12,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": 1.0, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 180, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.970558,0.970634,0.969267,0.968701,0.968916,0.969615,0.000821,3,0.992197,0.993099,0.994374,0.990605,0.994374,0.992930,0.001424,12,0.981258,0.981738,0.981660,0.979531,0.981480,0.981133,0.000818,3,0.998038,0.998265,0.998584,0.997638,0.998584,0.998222,0.000358,12,0.992476,0.992489,0.992117,0.991998,0.992025,0.992221,0.000217,3,0.995249,0.995369,0.995340,0.994810,0.995293,0.995212,0.000205,3,0.988254,0.988553,0.988500,0.987170,0.988387,0.988173,0.000512,3,0.992420,0.992611,0.992569,0.991719,0.992494,0.992363,0.000328,3,0.992336,0.992794,0.993246,0.991302,0.993199,0.992575,0.000716,12,403.651637,3.712604,0.712001,0.033133
2,random_forest,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,3,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 171, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.966246,0.966500,0.965312,0.964037,0.964211,0.965261,0.001011,4,0.996868,0.997027,0.997028,0.997399,0.998142,0.997293,0.000459,10,0.981318,0.981526,0.980913,0.980434,0.980883,0.981015,0.000379,4,0.999211,0.999251,0.999251,0.999344,0.999531,0.999318,0.000116,10,0.991295,0.991361,0.991043,0.990697,0.990737,0.991027,0.000274,4,0.995237,0.995290,0.995130,0.995002,0.995115,0.995155,0.000101,4,0.988278,0.988408,0.988022,0.987718,0.987999,0.988085,0.000240,4,0.992409,0.992494,0.992240,0.992038,0.992218,0.992280,0.000159,4,0.994081,0.994194,0.994035,0.994048,0.994440,0.994160,0.000151,7,166.190295,3.851696,1.228557,0.057250
12,random_forest,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,13,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 115, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.965200,0.965546,0.963923,0.962603,0.963156,0.964086,0.001137,5,0.998248,0.998195,0.998408,0.998726,0.999045,0.998524,0.000319,7,0.981446,0.981599,0.980862,0.980332,0.980772,0.981002,0.000464,5,0.999558,0.999545,0.999598,0.999678,0.999759,0.999628,0.000080,7,0.991003,0.991096,0.990658,0.990299,0.990445,0.990700,0.000308,5,0.995262,0.995302,0.995108,0.994967,0.995080,0.995144,0.000123,5,0.988354,0.988451,0.987985,0.987649,0.987926,0.988073,0.000293,5,0.992452,0.992516,0.992208,0.991985,0.992165,0.992265,0.000195,5,0.994626,0.994645,0.994533,0.994513,0.994745,0.994612,0.000084,1,100.057919,10.084606,0.735170,0.071378
8,random_forest,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,9,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 275, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.965197,0.965096,0.963633,0.961757,0.962855,0.963707,0.001318,6,0.998142,0.998089,0.998567,0.998461,0.998885,0.998429,0.000292,8,0.981393,0.981315,0.980789,0.979765,0.980539,0.980760,0.000591,6,0.999532,0.999518,0.999638,0.999611,0.999719,0.999604,0.000073,8,0.991003,0.990976,0.990578,0.990074,0.990366,0.990599,0.000357,6,0.995249,0.995229,0.995088,0.994820,0.995020,0.995081,0.000156,6,0.988321,0.988272,0.987938,0.987292,0.987780,0.987921,0.000374,6,0.992431,0.992399,0.992176,0.991751,0.992070,0.992165,0.000247,6,0.994572,0.994533,0.994572,0.994267,0.994626,0.994514,0.000127,2,268.544849,4.311612,1.859545,0.063959
3,random_forest,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,4,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 30, ""classifier__max_features"": 0.5, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 278, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.964407,0.964062,0.962117,0.961171,0.961871,0.962725,0.001275,7,0.998195,0.998248,0.998885,0.998567,0.998885,0.998556,0.000297,6,0.981010,0.980858,0.980156,0.979512,0.980029,0.980313,0.000553,7,0.999545,0.999558,0.999719,0.999638,0.999719,0.999636,0.000075,6,0.990791,0.990698,0.990167,0.989915,0.990100,0.990334,0.000346,7,0.995148,0.995108,0.994920,0.994753,0.994886,0.994963,0.000147,7,0.988079,0.987983,0.987538,0.987132,0.987457,0.987638,0.000350,7,0.992271,0.992208,0.991910,0.991645,0.991857,0.991978,0.000232,7,0.994493,0.994473,0.994526,0.994241,0.994493,0.994445,0.000104,3,429.674400,7.008535,1.767754,0.072039
1,random_forest,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,2,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 237, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.963380,0.963274,0.961424,0.960973,0.961093,0.962029,0.001071,9,0.998514,0.998301,0.998779,0.998514,0.999098,0.998641,0.000274,1,0.980632,0.980475,0.979746,0.979384,0.979727,0.979993,0.000478,8,0.999625,0.999571,0.999692,0.999625,0.999772,0.999657,0.000069,1,0.990512,0.990485,0.989981,0.989861,0.989888,0.990146,0.000291,9,0.995048,0.995008,0.994813,0.994719,0.994806,0.994879,0.000127,8,0.987840,0.987741,0.987279,0.987051,0.987266,0.987436,0.000303,8,0.992112,0.992048,0.991741,0.991592,0.991730,0.991845,0.000200,8,0.994513,0.994393,0.994380,0.994188,0.994493,0.994393,0.000115,4,222.249820,6.902638,1.496728,0.029995
5,random_forest,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,6,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": 1.0, ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 186, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.964033,0.963250,0.962237,0.961727,0.961517,0.962553,0.000952,8,0.997399,0.997611,0.998142,0.997665,0.998620,0.997887,0.000440,9,0.980432,0.980129,0.979861,0.979366,0.979717,0.979901,0.000362,9,0.999344,0.999397,0.999531,0.999411,0.999652,0.999467,0.000111,9,0.990698,0.990485,0.990206,0.990074,0.990007,0.990294,0.000260,8,0.995002,0.994921,0.994847,0.994720,0.994806,0.994859,0.000097,9,0.987717,0.987525,0.987354,0.987043,0.987262,0.987380,0.000229,9,0.992038,0.991910,0.991794,0.991592,0.991730,0.991813,0.000152,9,0.994048,0.994048,0.994174,0.993869,0.994314,0.994091,0.000148,9,514.132153,5.368298,1.044093,0.057819
7,random_forest,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,8,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 160, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.962146,0.961845,0.960837,0.960192,0.960694,0.961143,0.000735,10,0.998461,0.998301,0.998832,0.998620,0.998938,0.998631,0.000234,2,0.979967,0.979734,0.979466,0.979029,0.979443,0.979528,0.000315,10,0.999612,0.999571,0.999705,0.999651,0.999732,0.999654,0.000059,2,0.990180,0.990101,0.989822,0.989649,0.989782,0.989907,0.000201,10,0.994874,0.994813,0.994739,0.994625,0.994732,0.994757,0.000084,10,0.987420,0.987274,0.987103,0.986827,0.987088,0.987142,0.000199,10,0.991836,0.991741,0.991624,0.991443,0.991613,0.991651,0.000132,10,0.994320,0.994201,0.994327,0.994135,0.994360,0.994269,0.000086,5,135.765100,1.966850,0.899041,0.012098
10,random_forest,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,11,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced_subsample"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 296, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.962184,0.961694,0.960400,0.959406,0.959572,0.960651,0.001115,11,0.998142,0.998195,0.998938,0.998567,0.999045,0.998577,0.000370,5,0.979833,0.979605,0.979290,0.978595,0.978910,0.979247,0.000450,11,0.999531,0.999544,0.999732,0.999638,0.999759,0.999641,0.000093,5,0.990193,0.990061,0.989702,0.989437,0.989477,0.989774,0.000305,11,0.994840,0.994780,0.994692,0.994511,0.994591,0.994683,0.000120,11,0.987337,0.987192,0.986991,0.986553,0.986751,0.986965,0.000285,11,0.991783,0.991688,0.991550,0.991263,0.991390,0.991535,0.000190,11,0.994168,0.994128,0.994320,0.994002,0.994261,0.994176,0.000110,6,280.213138,4.680334,1.498931,0.104991
9,random_forest,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,10,random,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced_subsample"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 231, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",0.961546,0.961354,0.959908,0.958773,0.959134,0.960143,0.001130,12,0.998195,0.998301,0.998885,0.998620,0.999098,0.998620,0.000341,4,0.979528,0.979479,0.979009,0.978291,0.978708,0.979003,0.000468,12,0.999544,0.999571,0.999718,0.999651,0.999772,0.999652,0.000086,4,0.990021,0.989968,0.989570,0.989264,0.989357,0.989636,0.000309,12,0.994760,0.994746,0.994618,0.994431,0.994537,0.994618,0.000125,12,0.987144,0.987113,0.986814,0.986361,0.986623,0.986811,0.000297,12,0.991656,0.991634,0.991433,0.991136,0.991305,0.991433,0.000197,12,0.994108,0.994135,0.994227,0.993942,0.994227,0.994128,0.000105,8,221.155840,1.869459,1.302660,0.059613

modelo: xgboost
 origem do treinamento: cicids2017
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: xgboost - cicids2017

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
7,xgboost,randomized_search,cicids2017,235490,12,13,5,1,8,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.717772960390469, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 6, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 298, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.9873668590451505, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.980532,0.980411,0.982891,0.981481,0.979570,0.980977,0.001133,1,0.994585,0.993630,0.994055,0.990234,0.992569,0.993015,0.001540,3,0.987509,0.986976,0.988441,0.985838,0.986027,0.986958,0.000962,1,0.998642,0.998402,0.998509,0.997553,0.998136,0.998248,0.000385,3,0.995064,0.995037,0.995674,0.995329,0.994825,0.995186,0.000292,1,0.996849,0.996717,0.997090,0.996440,0.996478,0.996715,0.000241,1,0.992179,0.991846,0.992766,0.991139,0.991252,0.991836,0.000601,1,0.994968,0.994756,0.995350,0.994310,0.994373,0.994751,0.000386,1,0.994824,0.994333,0.994865,0.992781,0.993697,0.994100,0.000783,3,9.818352,0.114014,0.436219,0.015581
4,xgboost,randomized_search,cicids2017,235490,12,13,5,1,5,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7688731641189476, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.10269165750001427, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 7, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 196, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.93351677090096, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.980940,0.979506,0.982265,0.981696,0.978962,0.980674,0.001260,5,0.994479,0.994585,0.993631,0.990658,0.992887,0.993248,0.001434,2,0.987663,0.986988,0.987915,0.986157,0.985875,0.986920,0.000803,2,0.998615,0.998641,0.998403,0.997659,0.998215,0.998307,0.000359,2,0.995170,0.994798,0.995515,0.995382,0.994665,0.995106,0.000327,5,0.996889,0.996716,0.996957,0.996519,0.996437,0.996704,0.000202,2,0.992276,0.991852,0.992436,0.991338,0.991156,0.991812,0.000502,2,0.995032,0.994756,0.995138,0.994437,0.994310,0.994734,0.000323,2,0.994824,0.994692,0.994573,0.993020,0.993776,0.994177,0.000684,2,8.333705,0.390043,0.423602,0.040832
5,xgboost,randomized_search,cicids2017,235490,12,13,5,1,6,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9147911547905092, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.19049288475798723, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 122, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.8554457646825666, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.980626,0.979891,0.983388,0.981398,0.979466,0.980954,0.001384,2,0.994161,0.993311,0.992887,0.991295,0.992463,0.992824,0.000948,8,0.987347,0.986556,0.988115,0.986322,0.985921,0.986852,0.000784,3,0.998535,0.998322,0.998217,0.997818,0.998109,0.998200,0.000237,8,0.995090,0.994904,0.995807,0.995302,0.994798,0.995180,0.000357,2,0.996810,0.996610,0.997011,0.996559,0.996451,0.996688,0.000199,3,0.992078,0.991583,0.992563,0.991440,0.991186,0.991770,0.000492,3,0.994904,0.994586,0.995223,0.994501,0.994331,0.994709,0.000317,3,0.994625,0.994108,0.994347,0.993299,0.993630,0.994002,0.000480,6,5.679604,0.261346,0.289306,0.018909
2,xgboost,randomized_search,cicids2017,235490,12,13,5,1,3,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7277015784306393, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.046066102129245355, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 234, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.9806617212418095, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.980622,0.979402,0.982180,0.980781,0.978550,0.980307,0.001244,9,0.993948,0.994479,0.994692,0.991401,0.992781,0.993460,0.001224,1,0.987240,0.986883,0.988397,0.986063,0.985614,0.986839,0.000969,4,0.998482,0.998615,0.998669,0.997844,0.998189,0.998360,0.000307,1,0.995090,0.994772,0.995488,0.995143,0.994559,0.995010,0.000320,9,0.996783,0.996689,0.997076,0.996492,0.996371,0.996682,0.000244,4,0.992012,0.991786,0.992736,0.991277,0.990992,0.991761,0.000607,4,0.994862,0.994713,0.995329,0.994395,0.994204,0.994700,0.000390,4,0.994519,0.994625,0.995090,0.993272,0.993670,0.994235,0.000665,1,10.362145,0.241244,0.529749,0.034273
0,xgboost,randomized_search,cicids2017,235490,12,13,5,1,1,baseline,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 1.0, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.3, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 6, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 100, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 1.0, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.980936,0.980203,0.982265,0.981690,0.978759,0.980771,0.001223,3,0.994267,0.993524,0.993631,0.990340,0.992994,0.992951,0.001367,5,0.987557,0.986819,0.987915,0.985996,0.985825,0.986822,0.000826,5,0.998562,0.998376,0.998403,0.997579,0.998242,0.998232,0.000342,5,0.995170,0.994984,0.995515,0.995382,0.994612,0.995132,0.000317,3,0.996863,0.996677,0.996957,0.996479,0.996424,0.996680,0.000208,5,0.992210,0.991748,0.992436,0.991238,0.991124,0.991751,0.000517,5,0.994989,0.994692,0.995138,0.994373,0.994289,0.994696,0.000332,5,0.994718,0.994254,0.994573,0.992861,0.993803,0.994042,0.000669,4,3.731795,0.236750,0.233972,0.008154
3,xgboost,randomized_search,cicids2017,235490,12,13,5,1,4,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9538932750058051, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.061715573864800456, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 7, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 239, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.833035868133867, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.980727,0.980205,0.982460,0.981184,0.978861,0.980687,0.001179,4,0.994055,0.993630,0.992994,0.990870,0.992994,0.992908,0.001096,6,0.987346,0.986872,0.987699,0.986003,0.985877,0.986759,0.000720,6,0.998509,0.998402,0.998244,0.997712,0.998242,0.998222,0.000274,6,0.995117,0.994984,0.995568,0.995249,0.994639,0.995111,0.000306,4,0.996810,0.996690,0.996904,0.996479,0.996437,0.996664,0.000182,6,0.992078,0.991781,0.992301,0.991241,0.991157,0.991712,0.000451,6,0.994904,0.994713,0.995053,0.994373,0.994310,0.994671,0.000290,6,0.994586,0.994307,0.994281,0.993060,0.993816,0.994010,0.000535,5,10.260197,0.250352,0.437131,0.026947
1,xgboost,randomized_search,cicids2017,235490,12,13,5,1,2,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.8251066014107722, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.1575599187428391, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 4, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 233, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.7440267672451338, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.980421,0.979983,0.982884,0.980876,0.978441,0.980521,0.001438,6,0.994161,0.992781,0.993631,0.990977,0.992463,0.992802,0.001094,9,0.987243,0.986340,0.988228,0.985901,0.985402,0.986623,0.001005,7,0.998535,0.998189,0.998403,0.997738,0.998109,0.998195,0.000274,9,0.995037,0.994931,0.995674,0.995170,0.994533,0.995069,0.000370,6,0.996783,0.996557,0.997037,0.996452,0.996318,0.996629,0.000254,7,0.992013,0.991449,0.992632,0.991176,0.990860,0.991626,0.000630,7,0.994862,0.994501,0.995265,0.994331,0.994119,0.994615,0.000406,7,0.994599,0.993856,0.994652,0.993073,0.993498,0.993936,0.000616,9,8.183731,0.302692,0.290564,0.014008
11,xgboost,randomized_search,cicids2017,235490,12,13,5,1,12,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9725786509279286, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 200, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.8574398130611336, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.980824,0.980090,0.981956,0.980678,0.978548,0.980419,0.001114,8,0.993736,0.992993,0.993631,0.991401,0.992675,0.992887,0.000841,7,0.987238,0.986499,0.987759,0.986011,0.985561,0.986613,0.000798,8,0.998429,0.998243,0.998403,0.997844,0.998162,0.998216,0.000211,7,0.995143,0.994957,0.995435,0.995117,0.994559,0.995042,0.000287,8,0.996783,0.996597,0.996917,0.996479,0.996357,0.996627,0.000202,8,0.992011,0.991548,0.992338,0.991245,0.990959,0.991620,0.000500,8,0.994862,0.994565,0.995074,0.994373,0.994182,0.994611,0.000322,8,0.994440,0.993975,0.994533,0.993259,0.993617,0.993965,0.000483,7,8.678103,0.125782,0.334670,0.037059

modelo: xgboost
 origem do treinamento: unsw_nb15
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: xgboost - unsw_nb15

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
11,xgboost,randomized_search,unsw_nb15,235490,12,13,5,1,12,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9725786509279286, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 200, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.8574398130611336, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.944796,0.945070,0.943001,0.942184,0.941736,0.943358,0.001352,5,0.997558,0.997346,0.997558,0.998195,0.998620,0.997856,0.000477,5,0.970461,0.970505,0.969513,0.969381,0.969344,0.969841,0.000527,1,0.999381,0.999327,0.999381,0.999542,0.999650,0.999456,0.000121,4,0.985430,0.985509,0.984925,0.984686,0.984553,0.985021,0.000386,5,0.992356,0.992370,0.992100,0.992058,0.992044,0.992186,0.000146,2,0.981408,0.981437,0.980806,0.980720,0.980694,0.981013,0.000337,1,0.987855,0.987876,0.987452,0.987388,0.987367,0.987588,0.000229,2,0.991494,0.991427,0.991242,0.991441,0.991587,0.991438,0.000113,4,9.330047,0.168968,0.347241,0.022416
7,xgboost,randomized_search,unsw_nb15,235490,12,13,5,1,8,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.717772960390469, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 6, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 298, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.9873668590451505, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.944948,0.946609,0.943992,0.943506,0.943267,0.944464,0.001217,2,0.996815,0.995753,0.996603,0.996391,0.997240,0.996560,0.000492,10,0.970189,0.970559,0.969584,0.969228,0.969503,0.969813,0.000488,2,0.999193,0.998924,0.999139,0.999085,0.999300,0.999128,0.000124,10,0.985483,0.985960,0.985217,0.985084,0.985005,0.985350,0.000346,2,0.992290,0.992400,0.992129,0.992035,0.992101,0.992191,0.000134,1,0.981239,0.981480,0.980857,0.980631,0.980802,0.981002,0.000311,2,0.987749,0.987919,0.987494,0.987346,0.987452,0.987592,0.000210,1,0.991149,0.990857,0.990910,0.990737,0.991122,0.990955,0.000158,10,10.536906,0.178627,0.470440,0.042910
2,xgboost,randomized_search,unsw_nb15,235490,12,13,5,1,3,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7277015784306393, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.046066102129245355, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 234, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.9806617212418095, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.944160,0.945025,0.942350,0.941624,0.941547,0.942941,0.001404,7,0.998089,0.998301,0.997771,0.998301,0.998620,0.998216,0.000280,2,0.970376,0.970933,0.969269,0.969135,0.969244,0.969791,0.000728,3,0.999515,0.999569,0.999434,0.999569,0.999650,0.999548,0.000071,2,0.985244,0.985483,0.984739,0.984527,0.984500,0.984899,0.000396,7,0.992328,0.992476,0.992032,0.991991,0.992017,0.992169,0.000197,3,0.981352,0.981704,0.980651,0.980563,0.980631,0.980980,0.000462,3,0.987813,0.988046,0.987346,0.987282,0.987324,0.987562,0.000310,3,0.991666,0.991892,0.991255,0.991414,0.991560,0.991557,0.000217,2,11.472835,0.147631,0.571023,0.049026
1,xgboost,randomized_search,unsw_nb15,235490,12,13,5,1,2,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.8251066014107722, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.1575599187428391, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 4, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 233, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.7440267672451338, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.944612,0.945489,0.941612,0.941224,0.941359,0.942859,0.001815,8,0.997664,0.998089,0.998089,0.997877,0.998620,0.998068,0.000318,3,0.970414,0.971077,0.969029,0.968723,0.969144,0.969677,0.000908,4,0.999408,0.999516,0.999515,0.999461,0.999650,0.999510,0.000080,3,0.985376,0.985615,0.984527,0.984421,0.984447,0.984877,0.000512,8,0.992343,0.992517,0.991964,0.991884,0.991990,0.992140,0.000246,5,0.981378,0.981797,0.980496,0.980303,0.980567,0.980908,0.000577,4,0.987834,0.988110,0.987239,0.987112,0.987282,0.987515,0.000387,5,0.991520,0.991852,0.991308,0.991149,0.991534,0.991473,0.000238,3,9.043024,0.601782,0.305928,0.023180
4,xgboost,randomized_search,unsw_nb15,235490,12,13,5,1,5,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7688731641189476, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.10269165750001427, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 7, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 196, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.93351677090096, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.944601,0.946000,0.942877,0.942209,0.941990,0.943536,0.001536,4,0.997452,0.996921,0.997028,0.996921,0.998089,0.997282,0.000448,9,0.970307,0.970793,0.969197,0.968794,0.969228,0.969664,0.000756,5,0.999354,0.999220,0.999246,0.999219,0.999515,0.999311,0.000114,9,0.985376,0.985775,0.984898,0.984713,0.984633,0.985079,0.000433,4,0.992316,0.992452,0.992020,0.991913,0.992018,0.992144,0.000204,4,0.981312,0.981623,0.980608,0.980353,0.980623,0.980904,0.000480,5,0.987791,0.988004,0.987324,0.987154,0.987324,0.987520,0.000322,4,0.991414,0.991348,0.990963,0.990817,0.991361,0.991181,0.000243,9,8.663122,0.253917,0.422147,0.046594
3,xgboost,randomized_search,unsw_nb15,235490,12,13,5,1,4,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9538932750058051, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.061715573864800456, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 7, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 239, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.833035868133867, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.944439,0.945244,0.942173,0.941506,0.942078,0.943088,0.001472,6,0.997983,0.997027,0.997983,0.997877,0.997983,0.997771,0.000374,6,0.970473,0.970445,0.969275,0.968872,0.969225,0.969658,0.000669,6,0.999488,0.999247,0.999488,0.999461,0.999488,0.999434,0.000095,6,0.985323,0.985562,0.984686,0.984500,0.984659,0.984946,0.000417,6,0.992355,0.992357,0.992032,0.991924,0.992018,0.992137,0.000183,7,0.981414,0.981401,0.980654,0.980398,0.980622,0.980898,0.000426,6,0.987855,0.987855,0.987346,0.987176,0.987324,0.987511,0.000287,6,0.991653,0.991295,0.991335,0.991189,0.991321,0.991358,0.000156,5,10.896497,0.289262,0.430802,0.017582
0,xgboost,randomized_search,unsw_nb15,235490,12,13,5,1,1,baseline,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 1.0, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.3, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 6, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 100, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 1.0, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.945233,0.946200,0.943986,0.943205,0.942427,0.944210,0.001360,3,0.996815,0.995222,0.996497,0.996072,0.997452,0.996412,0.000746,11,0.970339,0.970092,0.969531,0.968918,0.969159,0.969608,0.000539,7,0.999193,0.998790,0.999112,0.999004,0.999354,0.999090,0.000189,11,0.985562,0.985854,0.985217,0.985005,0.984766,0.985281,0.000388,3,0.992331,0.992280,0.992116,0.991955,0.992006,0.992137,0.000147,6,0.981335,0.981186,0.980823,0.980436,0.980583,0.980873,0.000343,7,0.987813,0.987728,0.987473,0.987218,0.987303,0.987507,0.000232,7,0.991189,0.990538,0.990857,0.990538,0.991109,0.990846,0.000274,11,4.053674,0.298702,0.251515,0.026830
10,xgboost,randomized_search,unsw_nb15,235490,12,13,5,1,11,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7895485884259134, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.08380226576125108, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 5, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 253, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.8343680578527715, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.943742,0.944651,0.940870,0.940394,0.941459,0.942223,0.001671,11,0.999151,0.998407,0.998301,0.998195,0.998726,0.998556,0.000346,1,0.970656,0.970786,0.968736,0.968433,0.969247,0.969572,0.000975,8,0.999785,0.999596,0.999569,0.999542,0.999677,0.999634,0.000088,1,0.985111,0.985376,0.984314,0.984182,0.984474,0.984691,0.000468,11,0.992394,0.992435,0.991883,0.991802,0.992017,0.992106,0.000261,8,0.981525,0.981610,0.980309,0.980118,0.980632,0.980839,0.000618,8,0.987919,0.987983,0.987112,0.986985,0.987324,0.987464,0.000412,8,0.992131,0.991892,0.991308,0.991189,0.991600,0.991624,0.000352,1,9.300183,0.199127,0.349229,0.012331

modelo: xgboost
 origem do treinamento: iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: xgboost - iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
10,xgboost,randomized_search,iot23,235490,12,13,5,1,11,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7895485884259134, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.08380226576125108, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 5, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 253, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.8343680578527715, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.999573,0.999679,0.999679,0.999787,0.999786,0.999701,0.000080,2,0.993948,0.992144,0.992463,0.994374,0.993843,0.993354,0.000882,3,0.996753,0.995897,0.996058,0.997073,0.996806,0.996517,0.000457,1,0.998489,0.998040,0.998119,0.998595,0.998463,0.998341,0.000220,1,0.999894,0.999920,0.999920,0.999947,0.999947,0.999926,0.000020,2,0.999191,0.998979,0.999019,0.999271,0.999204,0.999133,0.000113,1,0.997972,0.997438,0.997538,0.998172,0.998005,0.997825,0.000285,1,0.998705,0.998365,0.998429,0.998832,0.998726,0.998611,0.000181,1,0.996921,0.996032,0.996192,0.997160,0.996895,0.996640,0.000444,1,8.045913,0.095391,0.285617,0.015646
7,xgboost,randomized_search,iot23,235490,12,13,5,1,8,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.717772960390469, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 6, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 298, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.9873668590451505, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.999573,0.999572,0.999572,0.999893,0.999786,0.999679,0.000135,8,0.993948,0.992144,0.992463,0.994480,0.993737,0.993354,0.000897,2,0.996753,0.995844,0.996005,0.997179,0.996752,0.996507,0.000503,2,0.998489,0.998040,0.998119,0.998622,0.998436,0.998341,0.000224,2,0.999894,0.999894,0.999894,0.999973,0.999947,0.999920,0.000034,5,0.999191,0.998966,0.999006,0.999297,0.999191,0.999130,0.000125,3,0.997972,0.997405,0.997505,0.998238,0.997972,0.997818,0.000314,2,0.998705,0.998344,0.998408,0.998875,0.998705,0.998607,0.000200,2,0.996921,0.996019,0.996178,0.997227,0.996842,0.996637,0.000461,2,9.058163,0.174809,0.427148,0.021204
4,xgboost,randomized_search,iot23,235490,12,13,5,1,5,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7688731641189476, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.10269165750001427, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 7, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 196, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.93351677090096, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.999573,0.999679,0.999572,0.999893,0.999786,0.999701,0.000125,3,0.993842,0.992144,0.992463,0.994374,0.993843,0.993333,0.000869,7,0.996699,0.995897,0.996005,0.997126,0.996806,0.996507,0.000476,3,0.998463,0.998040,0.998119,0.998595,0.998463,0.998336,0.000216,5,0.999894,0.999920,0.999894,0.999973,0.999947,0.999926,0.000031,4,0.999178,0.998979,0.999006,0.999284,0.999204,0.999130,0.000118,2,0.997939,0.997438,0.997505,0.998205,0.998005,0.997818,0.000297,3,0.998684,0.998365,0.998408,0.998853,0.998726,0.998607,0.000189,3,0.996868,0.996032,0.996178,0.997174,0.996895,0.996629,0.000444,5,7.347049,0.104091,0.364793,0.015664
12,xgboost,randomized_search,iot23,235490,12,13,5,1,13,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7250869013641078, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.24773227404307951, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 3, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 262, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.7896790336629148, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.999573,0.999786,0.999572,0.999680,0.999786,0.999679,0.000096,5,0.993948,0.992250,0.992357,0.994374,0.993737,0.993333,0.000866,5,0.996753,0.996004,0.995951,0.997020,0.996752,0.996496,0.000435,4,0.998489,0.998066,0.998093,0.998595,0.998436,0.998336,0.000216,6,0.999894,0.999947,0.999894,0.999920,0.999947,0.999920,0.000024,8,0.999191,0.999006,0.998992,0.999257,0.999191,0.999128,0.000108,5,0.997972,0.997505,0.997472,0.998139,0.997972,0.997812,0.000271,4,0.998705,0.998408,0.998386,0.998811,0.998705,0.998603,0.000173,5,0.996921,0.996098,0.996125,0.997147,0.996842,0.996627,0.000432,6,5.617649,0.759171,0.163129,0.023659
2,xgboost,randomized_search,iot23,235490,12,13,5,1,3,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7277015784306393, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.046066102129245355, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 234, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.9806617212418095, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.999573,0.999679,0.999572,1.000000,0.999680,0.999701,0.000157,4,0.993842,0.992144,0.992357,0.994374,0.993843,0.993312,0.000891,8,0.996699,0.995897,0.995951,0.997179,0.996753,0.996496,0.000496,5,0.998463,0.998040,0.998093,0.998595,0.998463,0.998331,0.000222,8,0.999894,0.999920,0.999894,1.000000,0.999920,0.999926,0.000039,2,0.999178,0.998979,0.998992,0.999297,0.999191,0.999128,0.000123,4,0.997939,0.997438,0.997472,0.998238,0.997972,0.997812,0.000309,5,0.998684,0.998365,0.998386,0.998875,0.998705,0.998603,0.000197,4,0.996868,0.996032,0.996125,0.997187,0.996882,0.996619,0.000456,8,8.426506,0.615131,0.392096,0.018431
6,xgboost,randomized_search,iot23,235490,12,13,5,1,7,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9595060755936949, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.20242687100180323, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 3, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 241, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.7819149922650241, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.999573,0.999786,0.999572,0.999680,0.999573,0.999637,0.000085,11,0.993948,0.992144,0.992569,0.994374,0.993737,0.993354,0.000851,3,0.996753,0.995950,0.996058,0.997020,0.996646,0.996485,0.000413,6,0.998489,0.998040,0.998145,0.998595,0.998436,0.998341,0.000212,3,0.999894,0.999947,0.999894,0.999920,0.999894,0.999910,0.000021,11,0.999191,0.998992,0.999019,0.999257,0.999165,0.999125,0.000102,8,0.997972,0.997471,0.997539,0.998139,0.997905,0.997805,0.000257,6,0.998705,0.998386,0.998429,0.998811,0.998662,0.998599,0.000164,6,0.996921,0.996045,0.996231,0.997147,0.996815,0.996632,0.000421,3,6.447961,0.054483,0.262904,0.013039
8,xgboost,randomized_search,iot23,235490,12,13,5,1,9,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.859949585491905, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.14757009901255264, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 4, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 143, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.905950278304475, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.999680,0.999786,0.999359,0.999573,0.999893,0.999658,0.000184,9,0.993948,0.992144,0.992357,0.994374,0.993843,0.993333,0.000904,6,0.996806,0.995950,0.995845,0.996967,0.996859,0.996485,0.000484,7,0.998489,0.998040,0.998092,0.998595,0.998463,0.998336,0.000225,7,0.999920,0.999947,0.999841,0.999894,0.999973,0.999915,0.000046,10,0.999204,0.998992,0.998966,0.999244,0.999218,0.999125,0.000120,7,0.998005,0.997471,0.997406,0.998105,0.998038,0.997805,0.000302,7,0.998726,0.998386,0.998344,0.998790,0.998747,0.998599,0.000192,6,0.996934,0.996045,0.996099,0.997134,0.996908,0.996624,0.000458,7,4.324259,0.164831,0.231453,0.016525
3,xgboost,randomized_search,iot23,235490,12,13,5,1,4,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9538932750058051, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.061715573864800456, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 7, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 239, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.833035868133867, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.999573,0.999679,0.999572,0.999787,0.999786,0.999679,0.000096,6,0.993842,0.992037,0.992463,0.994374,0.993843,0.993312,0.000898,9,0.996699,0.995844,0.996005,0.997073,0.996806,0.996485,0.000477,8,0.998463,0.998013,0.998119,0.998595,0.998463,0.998331,0.000224,9,0.999894,0.999920,0.999894,0.999947,0.999947,0.999920,0.000024,6,0.999178,0.998966,0.999006,0.999271,0.999204,0.999125,0.000118,6,0.997939,0.997405,0.997505,0.998172,0.998005,0.997805,0.000297,8,0.998684,0.998344,0.998408,0.998832,0.998726,0.998599,0.000189,6,0.996868,0.995979,0.996178,0.997160,0.996895,0.996616,0.000455,9,8.587328,0.056291,0.412338,0.037999

modelo: xgboost
 origem do treinamento: cicids2017_unsw_nb15
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: xgboost - cicids2017_unsw_nb15

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
7,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,8,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.717772960390469, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 6, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 298, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.9873668590451505, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.959647,0.961202,0.963805,0.961404,0.959574,0.961126,0.001540,2,0.993524,0.992940,0.995011,0.992941,0.994055,0.993694,0.000778,5,0.976292,0.976813,0.979159,0.976918,0.976510,0.977138,0.001034,1,0.998367,0.998220,0.998742,0.998220,0.998500,0.998410,0.000196,5,0.989557,0.989981,0.990658,0.990034,0.989530,0.989952,0.000410,2,0.993942,0.994084,0.994684,0.994110,0.993995,0.994163,0.000267,1,0.985117,0.985449,0.986921,0.985514,0.985252,0.985651,0.000651,1,0.990350,0.990573,0.991528,0.990615,0.990435,0.990700,0.000425,1,0.991540,0.991460,0.992834,0.991487,0.991792,0.991823,0.000519,4,23.044710,0.433955,0.902750,0.044492
4,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,5,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7688731641189476, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.10269165750001427, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 7, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 196, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.93351677090096, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.959016,0.960828,0.962822,0.960816,0.959005,0.960497,0.001417,4,0.993736,0.993471,0.995223,0.993047,0.994586,0.994012,0.000787,3,0.976068,0.976877,0.978755,0.976665,0.976472,0.976967,0.000933,2,0.998420,0.998354,0.998796,0.998247,0.998634,0.998490,0.000198,3,0.989384,0.989875,0.990392,0.989875,0.989370,0.989779,0.000379,4,0.993881,0.994096,0.994576,0.994043,0.993981,0.994116,0.000241,2,0.984974,0.985486,0.986665,0.985354,0.985226,0.985541,0.000587,2,0.990254,0.990594,0.991358,0.990509,0.990414,0.990626,0.000383,2,0.991560,0.991673,0.992808,0.991461,0.991978,0.991896,0.000488,2,18.709841,0.456009,0.773873,0.056161
5,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,6,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9147911547905092, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.19049288475798723, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 122, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.8554457646825666, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.960247,0.961738,0.964648,0.961552,0.960117,0.961660,0.001633,1,0.992462,0.992727,0.993577,0.991614,0.992834,0.992643,0.000634,7,0.976089,0.976987,0.978899,0.976352,0.976202,0.976906,0.001044,3,0.998100,0.998167,0.998382,0.997887,0.998193,0.998146,0.000160,7,0.989729,0.990127,0.990897,0.990087,0.989689,0.990106,0.000434,1,0.993897,0.994131,0.994625,0.993972,0.993923,0.994109,0.000270,3,0.984993,0.985559,0.986762,0.985162,0.985062,0.985508,0.000657,3,0.990276,0.990647,0.991433,0.990392,0.990318,0.990613,0.000430,3,0.991096,0.991427,0.992237,0.990850,0.991262,0.991374,0.000472,7,12.892065,0.236437,0.608815,0.014982
11,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,12,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9725786509279286, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 200, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.8574398130611336, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.958643,0.960359,0.962955,0.960254,0.958257,0.960094,0.001659,5,0.994214,0.994108,0.994798,0.993843,0.994268,0.994246,0.000312,1,0.976104,0.976942,0.978618,0.976760,0.975930,0.976871,0.000953,4,0.998540,0.998514,0.998689,0.998447,0.998553,0.998549,0.000079,1,0.989278,0.989742,0.990432,0.989715,0.989171,0.989668,0.000445,6,0.993887,0.994109,0.994543,0.994062,0.993840,0.994088,0.000249,5,0.984996,0.985525,0.986581,0.985411,0.984885,0.985480,0.000601,4,0.990265,0.990615,0.991305,0.990541,0.990191,0.990583,0.000395,5,0.991746,0.991925,0.992615,0.991779,0.991719,0.991957,0.000337,1,20.376918,0.154927,0.589895,0.026355
0,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,1,baseline,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 1.0, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.3, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 6, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 100, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 1.0, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.959254,0.961060,0.963148,0.961159,0.958634,0.960651,0.001592,3,0.993524,0.993099,0.994639,0.992994,0.993896,0.993630,0.000598,6,0.976088,0.976817,0.978640,0.976817,0.975947,0.976862,0.000959,5,0.998366,0.998260,0.998649,0.998234,0.998460,0.998394,0.000151,6,0.989450,0.989941,0.990485,0.989968,0.989278,0.989824,0.000427,3,0.993888,0.994083,0.994550,0.994083,0.993847,0.994091,0.000250,4,0.984988,0.985450,0.986595,0.985450,0.984897,0.985476,0.000604,5,0.990265,0.990573,0.991316,0.990573,0.990201,0.990586,0.000396,4,0.991487,0.991520,0.992562,0.991481,0.991587,0.991727,0.000419,6,8.267123,0.619222,0.476853,0.046744
2,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,3,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7277015784306393, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.046066102129245355, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 234, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.9806617212418095, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.958429,0.960378,0.962617,0.960051,0.958465,0.959988,0.001537,7,0.993789,0.993311,0.995011,0.993684,0.994586,0.994076,0.000625,2,0.975789,0.976567,0.978546,0.976578,0.976192,0.976734,0.000951,6,0.998433,0.998314,0.998742,0.998407,0.998634,0.998506,0.000158,2,0.989225,0.989756,0.990339,0.989662,0.989224,0.989641,0.000412,7,0.993808,0.994016,0.994523,0.994015,0.993907,0.994054,0.000247,6,0.984798,0.985292,0.986534,0.985297,0.985049,0.985394,0.000599,6,0.990138,0.990467,0.991274,0.990467,0.990297,0.990528,0.000392,6,0.991507,0.991533,0.992675,0.991673,0.991905,0.991859,0.000432,3,25.977550,0.764643,1.049878,0.044462
3,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,4,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9538932750058051, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.061715573864800456, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 7, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 239, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.833035868133867, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.958481,0.960333,0.962904,0.960417,0.958261,0.960079,0.001674,6,0.993842,0.993418,0.994745,0.992941,0.994374,0.993864,0.000646,4,0.975841,0.976595,0.978566,0.976408,0.975983,0.976679,0.000982,7,0.998446,0.998340,0.998675,0.998220,0.998580,0.998452,0.000163,4,0.989238,0.989742,0.990419,0.989769,0.989171,0.989668,0.000450,5,0.993821,0.994023,0.994530,0.993976,0.993853,0.994041,0.000256,7,0.984831,0.985309,0.986548,0.985192,0.984918,0.985360,0.000619,7,0.990159,0.990477,0.991284,0.990403,0.990212,0.990507,0.000406,7,0.991540,0.991580,0.992582,0.991355,0.991773,0.991766,0.000429,5,23.822099,0.625966,0.934197,0.060879
1,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,2,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.8251066014107722, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.1575599187428391, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 4, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 233, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.7440267672451338, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.957641,0.960162,0.962124,0.960010,0.957889,0.959565,0.001650,9,0.991294,0.991560,0.993684,0.991348,0.992463,0.992070,0.000910,8,0.974177,0.975608,0.977649,0.975428,0.974870,0.975546,0.001164,8,0.997804,0.997873,0.998408,0.997819,0.998098,0.998000,0.000229,8,0.989039,0.989716,0.990220,0.989676,0.989092,0.989548,0.000439,9,0.993402,0.993777,0.994297,0.993731,0.993575,0.993756,0.000301,8,0.983790,0.984693,0.985973,0.984579,0.984222,0.984651,0.000732,8,0.989490,0.990085,0.990913,0.990010,0.989766,0.990053,0.000478,8,0.990167,0.990638,0.991952,0.990512,0.990777,0.990809,0.000606,8,17.266064,0.526249,0.608916,0.055555

modelo: xgboost
 origem do treinamento: cicids2017_iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: xgboost - cicids2017_iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
7,xgboost,randomized_search,cicids2017_iot23,470980,12,13,5,1,8,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.717772960390469, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 6, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 298, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.9873668590451505, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.989159,0.989151,0.990113,0.989409,0.987948,0.989156,0.000698,2,0.992940,0.992144,0.994002,0.991720,0.992038,0.992569,0.000822,4,0.991046,0.990645,0.992054,0.990563,0.989989,0.990859,0.000686,1,0.998233,0.998035,0.998499,0.997929,0.998007,0.998141,0.000205,3,0.997280,0.997280,0.997518,0.997346,0.996974,0.997280,0.000176,2,0.997756,0.997657,0.998008,0.997637,0.997491,0.997710,0.000172,1,0.994401,0.994151,0.995031,0.994100,0.993740,0.994285,0.000429,1,0.996412,0.996252,0.996815,0.996221,0.995987,0.996337,0.000275,1,0.995110,0.994712,0.995760,0.994533,0.994506,0.994924,0.000470,3,20.686754,0.255130,0.880402,0.059595
0,xgboost,randomized_search,cicids2017_iot23,470980,12,13,5,1,1,baseline,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 1.0, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.3, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 6, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 100, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 1.0, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.988952,0.988944,0.989854,0.989098,0.987999,0.988969,0.000590,3,0.993152,0.992356,0.994268,0.992038,0.991932,0.992749,0.000871,1,0.991048,0.990647,0.992056,0.990566,0.989962,0.990856,0.000693,2,0.998286,0.998087,0.998565,0.998008,0.997981,0.998186,0.000218,1,0.997227,0.997227,0.997452,0.997266,0.996988,0.997232,0.000148,3,0.997756,0.997657,0.998008,0.997637,0.997484,0.997708,0.000173,2,0.994402,0.994152,0.995032,0.994102,0.993723,0.994282,0.000433,2,0.996412,0.996252,0.996815,0.996221,0.995976,0.996335,0.000277,2,0.995189,0.994791,0.995860,0.994652,0.994460,0.994990,0.000496,1,7.277387,0.447405,0.471143,0.038628
4,xgboost,randomized_search,cicids2017_iot23,470980,12,13,5,1,5,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7688731641189476, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.10269165750001427, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 7, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 196, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.93351677090096, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.988799,0.988943,0.989745,0.989149,0.987947,0.988916,0.000582,4,0.993471,0.992303,0.993790,0.991879,0.991932,0.992675,0.000800,2,0.991129,0.990620,0.991763,0.990512,0.989935,0.990792,0.000616,3,0.998366,0.998074,0.998446,0.997968,0.997981,0.998167,0.000200,2,0.997187,0.997227,0.997426,0.997280,0.996974,0.997219,0.000146,4,0.997776,0.997650,0.997935,0.997624,0.997477,0.997693,0.000154,3,0.994453,0.994135,0.994849,0.994068,0.993706,0.994242,0.000385,3,0.996444,0.996242,0.996698,0.996199,0.995966,0.996310,0.000247,3,0.995329,0.994765,0.995608,0.994579,0.994453,0.994947,0.000446,2,16.770161,0.288438,0.718909,0.042575
2,xgboost,randomized_search,cicids2017_iot23,470980,12,13,5,1,3,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7277015784306393, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.046066102129245355, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 234, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.9806617212418095, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.989003,0.988789,0.989795,0.988939,0.987734,0.988852,0.000659,5,0.993046,0.992568,0.993631,0.991879,0.991614,0.992547,0.000740,6,0.991021,0.990675,0.991709,0.990407,0.989670,0.990696,0.000674,4,0.998260,0.998140,0.998406,0.997968,0.997901,0.998135,0.000185,5,0.997240,0.997187,0.997439,0.997226,0.996921,0.997203,0.000166,5,0.997750,0.997663,0.997922,0.997597,0.997411,0.997669,0.000169,4,0.994385,0.994169,0.994816,0.994002,0.993540,0.994183,0.000421,4,0.996401,0.996263,0.996677,0.996157,0.995860,0.996272,0.000270,4,0.995143,0.994877,0.995535,0.994553,0.994267,0.994875,0.000443,4,22.758568,1.187219,0.946698,0.056841
11,xgboost,randomized_search,cicids2017_iot23,470980,12,13,5,1,12,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9725786509279286, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 200, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.8574398130611336, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.988899,0.988843,0.989741,0.988887,0.987838,0.988842,0.000603,6,0.993099,0.992727,0.993418,0.991826,0.991614,0.992537,0.000705,7,0.990995,0.990781,0.991576,0.990354,0.989722,0.990686,0.000622,5,0.998273,0.998180,0.998353,0.997955,0.997901,0.998132,0.000176,7,0.997213,0.997200,0.997426,0.997213,0.996948,0.997200,0.000152,6,0.997743,0.997690,0.997889,0.997584,0.997424,0.997666,0.000156,5,0.994369,0.994236,0.994733,0.993969,0.993573,0.994176,0.000389,5,0.996391,0.996306,0.996624,0.996136,0.995881,0.996267,0.000249,5,0.995156,0.994964,0.995422,0.994520,0.994281,0.994868,0.000416,5,18.182859,0.232334,0.588873,0.051847
5,xgboost,randomized_search,cicids2017_iot23,470980,12,13,5,1,6,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9147911547905092, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.19049288475798723, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 122, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.8554457646825666, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.988951,0.989352,0.990157,0.989768,0.988464,0.989339,0.000595,1,0.993046,0.991347,0.993153,0.990977,0.991507,0.992006,0.000910,11,0.990994,0.990348,0.991653,0.990372,0.989984,0.990670,0.000589,6,0.998260,0.997836,0.998287,0.997743,0.997875,0.998000,0.000227,11,0.997227,0.997333,0.997532,0.997439,0.997107,0.997327,0.000150,1,0.997743,0.997584,0.997909,0.997591,0.997491,0.997664,0.000147,6,0.994369,0.993966,0.994781,0.993982,0.993737,0.994167,0.000368,6,0.996391,0.996136,0.996656,0.996146,0.995987,0.996263,0.000235,6,0.995136,0.994340,0.995342,0.994208,0.994307,0.994667,0.000474,9,11.522335,0.275945,0.559305,0.032239
3,xgboost,randomized_search,cicids2017_iot23,470980,12,13,5,1,4,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9538932750058051, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.061715573864800456, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 7, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 239, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.833035868133867, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.988744,0.988632,0.989741,0.988991,0.987788,0.988779,0.000629,7,0.993205,0.992515,0.993418,0.991826,0.991773,0.992547,0.000680,5,0.990970,0.990570,0.991576,0.990407,0.989776,0.990660,0.000598,7,0.998300,0.998127,0.998353,0.997955,0.997941,0.998135,0.000170,6,0.997173,0.997147,0.997426,0.997240,0.996935,0.997184,0.000158,7,0.997736,0.997637,0.997889,0.997597,0.997438,0.997659,0.000150,7,0.994353,0.994103,0.994733,0.994002,0.993607,0.994159,0.000374,7,0.996380,0.996221,0.996624,0.996157,0.995902,0.996257,0.000240,7,0.995189,0.994831,0.995422,0.994533,0.994354,0.994866,0.000397,6,20.730091,0.495300,0.870524,0.057165
1,xgboost,randomized_search,cicids2017_iot23,470980,12,13,5,1,2,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.8251066014107722, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.1575599187428391, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 4, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 233, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.7440267672451338, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.988534,0.988368,0.989534,0.988887,0.987580,0.988581,0.000640,9,0.993152,0.992356,0.993631,0.991879,0.991826,0.992569,0.000713,3,0.990838,0.990358,0.991578,0.990381,0.989698,0.990571,0.000621,8,0.998286,0.998087,0.998406,0.997968,0.997954,0.998140,0.000178,4,0.997120,0.997081,0.997372,0.997213,0.996881,0.997134,0.000161,9,0.997703,0.997584,0.997889,0.997591,0.997418,0.997637,0.000156,8,0.994270,0.993971,0.994733,0.993986,0.993558,0.994104,0.000388,8,0.996327,0.996136,0.996624,0.996146,0.995870,0.996221,0.000249,8,0.995136,0.994718,0.995502,0.994546,0.994354,0.994851,0.000415,7,15.695513,0.273698,0.589242,0.028654

modelo: xgboost
 origem do treinamento: unsw_nb15_iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: xgboost - unsw_nb15_iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
4,xgboost,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,5,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7688731641189476, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.10269165750001427, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 7, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 196, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.93351677090096, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.970980,0.971599,0.970193,0.969904,0.969515,0.970438,0.000753,4,0.994638,0.995169,0.995117,0.995541,0.995966,0.995286,0.000445,3,0.982667,0.983243,0.982497,0.982555,0.982563,0.982705,0.000275,1,0.998652,0.998785,0.998771,0.998878,0.998985,0.998814,0.000112,3,0.992569,0.992728,0.992356,0.992277,0.992170,0.992420,0.000202,4,0.995601,0.995747,0.995553,0.995566,0.995566,0.995607,0.000072,1,0.989134,0.989495,0.989025,0.989061,0.989064,0.989156,0.000173,1,0.992983,0.993216,0.992908,0.992930,0.992930,0.992993,0.000114,1,0.993604,0.993949,0.993737,0.993909,0.994068,0.993853,0.000164,3,17.153015,0.483498,0.799981,0.086945
7,xgboost,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,8,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.717772960390469, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 6, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 298, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.9873668590451505, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.971369,0.971881,0.970840,0.970043,0.969799,0.970786,0.000783,2,0.994161,0.994426,0.994904,0.995170,0.995382,0.994809,0.000455,8,0.982633,0.983024,0.982725,0.982446,0.982424,0.982650,0.000218,2,0.998532,0.998599,0.998718,0.998785,0.998838,0.998694,0.000114,8,0.992675,0.992808,0.992529,0.992316,0.992250,0.992516,0.000210,2,0.995595,0.995695,0.995614,0.995540,0.995533,0.995595,0.000059,2,0.989114,0.989359,0.989169,0.988993,0.988979,0.989123,0.000138,2,0.992972,0.993131,0.993004,0.992887,0.992877,0.992974,0.000092,2,0.993418,0.993617,0.993717,0.993743,0.993816,0.993662,0.000138,7,21.007737,0.268913,0.942678,0.094938
0,xgboost,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,1,baseline,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 1.0, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.3, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 6, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 100, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 1.0, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.971325,0.972033,0.970448,0.969841,0.969645,0.970659,0.000903,3,0.994373,0.994479,0.995276,0.995117,0.995276,0.994904,0.000396,6,0.982714,0.983128,0.982705,0.982316,0.982293,0.982631,0.000307,3,0.998585,0.998612,0.998811,0.998771,0.998811,0.998718,0.000099,6,0.992662,0.992847,0.992423,0.992263,0.992210,0.992481,0.000241,3,0.995615,0.995721,0.995607,0.995507,0.995500,0.995590,0.000082,3,0.989164,0.989425,0.989156,0.988912,0.988897,0.989111,0.000194,3,0.993004,0.993174,0.992993,0.992834,0.992823,0.992966,0.000129,3,0.993517,0.993663,0.993849,0.993690,0.993743,0.993693,0.000108,5,7.533144,0.284325,0.511477,0.071547
11,xgboost,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,12,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9725786509279286, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 200, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.8574398130611336, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.970741,0.971498,0.970001,0.969207,0.969356,0.970160,0.000861,7,0.995063,0.995169,0.995435,0.995701,0.995648,0.995403,0.000253,2,0.982751,0.983191,0.982554,0.982275,0.982326,0.982619,0.000333,4,0.998758,0.998785,0.998851,0.998918,0.998904,0.998843,0.000063,2,0.992502,0.992702,0.992303,0.992091,0.992131,0.992346,0.000230,7,0.995620,0.995734,0.995566,0.995493,0.995506,0.995584,0.000088,4,0.989186,0.989463,0.989060,0.988884,0.988916,0.989102,0.000210,4,0.993015,0.993195,0.992930,0.992813,0.992834,0.992957,0.000139,4,0.993783,0.993935,0.993869,0.993896,0.993889,0.993874,0.000051,2,18.043468,0.258166,0.586112,0.069861
2,xgboost,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,3,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7277015784306393, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.046066102129245355, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 234, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.9806617212418095, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.970588,0.971355,0.969949,0.969456,0.969255,0.970121,0.000770,8,0.995010,0.995435,0.995382,0.995648,0.995648,0.995424,0.000234,1,0.982647,0.983247,0.982501,0.982377,0.982274,0.982609,0.000342,5,0.998745,0.998852,0.998838,0.998904,0.998904,0.998849,0.000059,1,0.992463,0.992662,0.992290,0.992157,0.992104,0.992335,0.000205,8,0.995594,0.995747,0.995553,0.995519,0.995493,0.995581,0.000090,5,0.989121,0.989497,0.989027,0.988948,0.988883,0.989095,0.000216,5,0.992972,0.993216,0.992908,0.992855,0.992813,0.992953,0.000142,5,0.993736,0.994048,0.993836,0.993902,0.993876,0.993880,0.000101,1,21.590058,0.859910,0.901000,0.017962
3,xgboost,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,4,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9538932750058051, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.061715573864800456, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 7, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 239, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.833035868133867, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.970829,0.971544,0.970050,0.969254,0.969656,0.970267,0.000824,5,0.994638,0.995010,0.995382,0.995594,0.995648,0.995255,0.000381,4,0.982590,0.983137,0.982553,0.982248,0.982480,0.982601,0.000293,6,0.998651,0.998745,0.998838,0.998891,0.998904,0.998806,0.000095,4,0.992529,0.992715,0.992316,0.992104,0.992210,0.992375,0.000220,5,0.995581,0.995721,0.995567,0.995486,0.995546,0.995580,0.000077,6,0.989085,0.989429,0.989060,0.988867,0.989013,0.989091,0.000185,6,0.992951,0.993174,0.992930,0.992802,0.992898,0.992951,0.000123,6,0.993584,0.993862,0.993849,0.993849,0.993929,0.993815,0.000119,4,20.607557,0.519685,0.959578,0.088530
5,xgboost,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,6,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9147911547905092, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.19049288475798723, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 122, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.8554457646825666, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.972003,0.972455,0.971064,0.970969,0.970281,0.971354,0.000777,1,0.993364,0.993258,0.993949,0.994161,0.994692,0.993885,0.000528,11,0.982568,0.982746,0.982373,0.982429,0.982335,0.982490,0.000151,7,0.998332,0.998306,0.998478,0.998531,0.998665,0.998462,0.000132,11,0.992847,0.992967,0.992595,0.992569,0.992383,0.992672,0.000209,1,0.995582,0.995629,0.995528,0.995541,0.995514,0.995559,0.000042,7,0.989075,0.989188,0.988951,0.988985,0.988924,0.989024,0.000096,7,0.992951,0.993025,0.992866,0.992887,0.992845,0.992915,0.000066,7,0.993106,0.993113,0.993272,0.993365,0.993537,0.993279,0.000162,11,11.471280,0.287019,0.553618,0.014481
10,xgboost,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,11,random,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7895485884259134, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.08380226576125108, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 5, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 253, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.8343680578527715, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",0.970774,0.971294,0.969796,0.969039,0.969496,0.970080,0.000832,9,0.994479,0.995063,0.995276,0.995117,0.995329,0.995053,0.000303,5,0.982484,0.983035,0.982371,0.981905,0.982243,0.982407,0.000369,8,0.998611,0.998758,0.998811,0.998771,0.998824,0.998755,0.000076,5,0.992516,0.992648,0.992250,0.992051,0.992170,0.992327,0.000222,9,0.995554,0.995694,0.995520,0.995400,0.995486,0.995531,0.000096,8,0.989019,0.989364,0.988945,0.988652,0.988865,0.988969,0.000233,8,0.992908,0.993131,0.992855,0.992664,0.992802,0.992872,0.000153,8,0.993497,0.993856,0.993763,0.993584,0.993750,0.993690,0.000130,6,17.841832,0.222006,0.689530,0.042606

modelo: linear_svm
 origem do treinamento: cicids2017
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: linear_svm - cicids2017

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
2,linear_svm,randomized_search,cicids2017,235490,12,13,5,1,3,random,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.758667,0.766255,0.761348,0.757855,0.758205,0.760466,0.003145,7,0.964221,0.967194,0.961465,0.960191,0.961359,0.962886,0.002528,1,0.849182,0.855078,0.849784,0.847108,0.847781,0.849787,0.002813,1,0.990406,0.991224,0.989688,0.989335,0.989646,0.990060,0.000680,1,0.923326,0.926245,0.924651,0.923297,0.923350,0.924174,0.001156,7,0.955690,0.957634,0.956065,0.955176,0.955349,0.955983,0.000880,1,0.902436,0.906356,0.902924,0.901142,0.901565,0.902885,0.001845,1,0.931505,0.934435,0.932014,0.930676,0.930952,0.931916,0.001341,1,0.943774,0.946720,0.943058,0.941744,0.942355,0.943530,0.001734,1,17.760707,4.246103,0.108587,0.008907
11,linear_svm,randomized_search,cicids2017,235490,12,13,5,1,12,random,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.740859,0.746078,0.742448,0.740906,0.736150,0.741288,0.003194,8,0.957320,0.959231,0.957537,0.953503,0.956369,0.956792,0.001886,2,0.835294,0.839333,0.836386,0.833867,0.831933,0.835363,0.002483,2,0.988490,0.989025,0.988555,0.987477,0.988210,0.988351,0.000510,2,0.916293,0.918390,0.916954,0.916636,0.914300,0.916514,0.001317,8,0.951023,0.952399,0.951409,0.950738,0.949819,0.951078,0.000844,2,0.893159,0.895866,0.893897,0.892303,0.890876,0.893220,0.001661,2,0.924498,0.926557,0.925071,0.924010,0.922714,0.924570,0.001262,2,0.936807,0.938810,0.937246,0.935069,0.935335,0.936653,0.001362,2,12.124601,2.367762,0.068341,0.016280
6,linear_svm,randomized_search,cicids2017,235490,12,13,5,1,7,random,"{""classifier__C"": 2.23218499287176, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.740713,0.746078,0.742042,0.740906,0.736003,0.741148,0.003219,9,0.956896,0.959231,0.957643,0.953503,0.955945,0.956644,0.001903,3,0.835040,0.839333,0.836168,0.833867,0.831679,0.835217,0.002539,3,0.988377,0.989025,0.988581,0.987477,0.988096,0.988311,0.000515,3,0.916266,0.918390,0.916768,0.916636,0.914274,0.916467,0.001317,9,0.950956,0.952399,0.951321,0.950738,0.949753,0.951034,0.000858,3,0.892998,0.895866,0.893745,0.892303,0.890716,0.893125,0.001697,3,0.924392,0.926557,0.924944,0.924010,0.922608,0.924502,0.001285,3,0.936581,0.938810,0.937206,0.935069,0.935109,0.936555,0.001401,3,15.159143,5.281355,0.106687,0.007082
12,linear_svm,randomized_search,cicids2017,235490,12,13,5,1,13,random,"{""classifier__C"": 0.1932075262142986, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.737542,0.740348,0.738089,0.736760,0.730626,0.736673,0.003251,10,0.953817,0.956896,0.955520,0.951062,0.954777,0.954414,0.001955,5,0.831852,0.834808,0.832848,0.830306,0.827796,0.831522,0.002368,4,0.987542,0.988375,0.987995,0.986805,0.987754,0.987694,0.000524,5,0.915152,0.916107,0.915229,0.915043,0.911991,0.914704,0.001409,10,0.949970,0.950870,0.950221,0.949570,0.948362,0.949799,0.000833,4,0.890911,0.892839,0.891534,0.889938,0.888079,0.890660,0.001597,4,0.922884,0.924264,0.923288,0.922247,0.920549,0.922646,0.001237,4,0.934484,0.936501,0.935375,0.933052,0.933384,0.934559,0.001272,4,7.853948,2.013198,0.080077,0.010929
3,linear_svm,randomized_search,cicids2017,235490,12,13,5,1,4,random,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.737080,0.739016,0.737161,0.736968,0.729892,0.736023,0.003158,11,0.953923,0.955409,0.955414,0.951486,0.954671,0.954181,0.001456,7,0.831598,0.833395,0.832216,0.830600,0.827285,0.831019,0.002075,5,0.987567,0.987973,0.987962,0.986919,0.987722,0.987629,0.000386,7,0.914939,0.915656,0.914831,0.915096,0.911673,0.914439,0.001412,11,0.949867,0.950441,0.949991,0.949652,0.948175,0.949625,0.000770,5,0.890733,0.891918,0.891104,0.890126,0.887730,0.890322,0.001420,5,0.922736,0.923606,0.922948,0.922375,0.920273,0.922387,0.001131,5,0.934431,0.935533,0.935122,0.933291,0.933172,0.934310,0.000949,6,9.034394,4.295320,0.104441,0.004925
5,linear_svm,randomized_search,cicids2017,235490,12,13,5,1,6,random,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.736343,0.738756,0.736782,0.736423,0.729633,0.735587,0.003104,13,0.955940,0.955622,0.955626,0.951486,0.954565,0.954648,0.001648,4,0.831894,0.833310,0.832055,0.830253,0.827079,0.830918,0.002152,6,0.988099,0.988028,0.988016,0.986916,0.987692,0.987750,0.000440,4,0.914435,0.915523,0.914645,0.914857,0.911566,0.914205,0.001369,13,0.949841,0.950395,0.949916,0.949521,0.948104,0.949555,0.000778,6,0.890867,0.891852,0.890985,0.889887,0.887591,0.890237,0.001462,6,0.922736,0.923542,0.922842,0.922184,0.920166,0.922294,0.001148,6,0.935188,0.935572,0.935136,0.933172,0.933066,0.934427,0.001079,5,3.921847,0.270961,0.107866,0.009291
4,linear_svm,randomized_search,cicids2017,235490,12,13,5,1,5,random,"{""classifier__C"": 0.015151125123102896, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.736393,0.738652,0.737083,0.736544,0.729914,0.735717,0.003010,12,0.953817,0.955409,0.955626,0.951486,0.954777,0.954223,0.001506,6,0.831121,0.833164,0.832247,0.830330,0.827339,0.830840,0.001999,7,0.987535,0.987971,0.988018,0.986916,0.987750,0.987638,0.000400,6,0.914647,0.915497,0.914778,0.914911,0.911673,0.914301,0.001346,12,0.949695,0.950354,0.949988,0.949550,0.948188,0.949555,0.000737,7,0.890408,0.891759,0.891118,0.889940,0.887763,0.890198,0.001365,7,0.922481,0.923479,0.922948,0.922226,0.920294,0.922285,0.001084,7,0.934232,0.935453,0.935202,0.933198,0.933225,0.934262,0.000950,7,5.483501,1.942161,0.105844,0.010759
0,linear_svm,randomized_search,cicids2017,235490,12,13,5,1,1,baseline,"{""classifier__C"": 1.0, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.828180,0.836279,0.827217,0.831544,0.822268,0.829097,0.004660,1,0.551651,0.552606,0.557537,0.550743,0.549575,0.552423,0.002746,8,0.662206,0.665473,0.666117,0.662622,0.658819,0.663048,0.002611,8,0.896556,0.896903,0.897715,0.896424,0.896010,0.896722,0.000573,8,0.971390,0.972956,0.970885,0.972106,0.970301,0.971527,0.000929,1,0.932474,0.933383,0.932868,0.932732,0.931677,0.932627,0.000560,8,0.797340,0.799428,0.799492,0.797677,0.795248,0.797837,0.001565,8,0.887447,0.888891,0.888212,0.887830,0.886152,0.887706,0.000912,8,0.761520,0.762781,0.764211,0.761424,0.759938,0.761975,0.001436,8,12.820214,3.705969,0.107819,0.003563
7,linear_svm,randomized_search,cicids2017,235490,12,13,5,1,8,random,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.827674,0.834349,0.825212,0.830479,0.820879,0.827719,0.004575,2,0.551226,0.552394,0.557325,0.550743,0.549257,0.552189,0.002758,9,0.661738,0.664708,0.665315,0.662284,0.658144,0.662438,0.002545,9,0.896461,0.896823,0.897634,0.896404,0.895919,0.896648,0.000571,9,0.971310,0.972584,0.970487,0.971893,0.970036,0.971262,0.000922,2,0.932386,0.933169,0.932640,0.932624,0.931505,0.932465,0.000544,9,0.797062,0.798938,0.798977,0.797454,0.794825,0.797451,0.001523,9,0.887299,0.888552,0.887851,0.887660,0.885876,0.887447,0.000885,9,0.761268,0.762489,0.763906,0.761318,0.759646,0.761726,0.001417,9,12.945567,5.689945,0.106010,0.016260
1,linear_svm,randomized_search,cicids2017,235490,12,13,5,1,2,random,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.826482,0.834805,0.824603,0.828987,0.820273,0.827030,0.004819,3,0.550695,0.552076,0.556476,0.550106,0.548938,0.551658,0.002612,10,0.660975,0.664622,0.664512,0.661349,0.657721,0.661836,0.002563,10,0.896330,0.896768,0.897450,0.896247,0.895843,0.896527,0.000547,10,0.971098,0.972690,0.970407,0.971628,0.969929,0.971151,0.000964,3,0.932217,0.933187,0.932504,0.932416,0.931415,0.932348,0.000569,10,0.796596,0.798905,0.798508,0.796883,0.794568,0.797092,0.001546,10,0.887023,0.888573,0.887617,0.887320,0.885728,0.887252,0.000923,10,0.760897,0.762383,0.763441,0.760867,0.759434,0.761404,0.001381,10,8.740010,2.977819,0.124310,0.025349
10,linear_svm,randomized_search,cicids2017,235490,12,13,5,1,11,random,"{""classifier__C"": 0.014056787147388339, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.826059,0.833976,0.823059,0.828590,0.820244,0.826386,0.004719,6,0.550589,0.551439,0.557006,0.550106,0.548832,0.551595,0.002834,11,0.660763,0.663897,0.664387,0.661222,0.657635,0.661581,0.002433,11,0.896301,0.896623,0.897527,0.896239,0.895821,0.896502,0.000573,11,0.971018,0.972558,0.970062,0.971548,0.969929,0.971023,0.000975,6,0.932165,0.933048,0.932386,0.932376,0.931403,0.932276,0.000528,11,0.796464,0.798473,0.798387,0.796799,0.794519,0.796928,0.001452,11,0.886938,0.888339,0.887447,0.887256,0.885706,0.887137,0.000853,11,0.760804,0.761998,0.763534,0.760827,0.759381,0.761309,0.001388,11,3.998958,0.260060,0.104253,0.005776
9,linear_svm,randomized_search,cicids2017,235490,12,13,5,1,10,random,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.825900,0.834029,0.823520,0.828430,0.820086,0.826393,0.004706,5,0.550483,0.551651,0.556794,0.550000,0.548726,0.551531,0.002794,12,0.660636,0.664068,0.664387,0.661095,0.657508,0.661539,0.002521,12,0.896276,0.896667,0.897493,0.896215,0.895796,0.896490,0.000573,12,0.970992,0.972558,0.970168,0.971522,0.969903,0.971028,0.000958,5,0.932139,0.933072,0.932417,0.932350,0.931378,0.932271,0.000545,13,0.796388,0.798570,0.798402,0.796722,0.794443,0.796905,0.001508,12,0.886895,0.888382,0.887490,0.887214,0.885664,0.887129,0.000884,13,0.760737,0.762104,0.763481,0.760761,0.759314,0.761280,0.001411,12,3.733084,0.133850,0.110752,0.005112
8,linear_svm,randomized_search,cicids2017,235490,12,13,5,1,9,random,"{""classifier__C"": 0.03684406880492199, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.826191,0.834431,0.822662,0.829120,0.819927,0.826466,0.005055,4,0.550589,0.551651,0.556476,0.550106,0.548620,0.551488,0.002678,13,0.660805,0.664195,0.663880,0.661391,0.657381,0.661531,0.002465,13,0.896303,0.896675,0.897412,0.896250,0.895772,0.896482,0.000546,13,0.971045,0.972637,0.970009,0.971655,0.969876,0.971044,0.001034,4,0.932178,0.933113,0.932299,0.932430,0.931352,0.932275,0.000563,12,0.796492,0.798654,0.798090,0.796911,0.794367,0.796903,0.001488,13,0.886959,0.888445,0.887299,0.887341,0.885621,0.887133,0.000906,12,0.760817,0.762144,0.763242,0.760880,0.759248,0.761266,0.001349,13,4.648156,0.420303,0.103608,0.004603

modelo: linear_svm
 origem do treinamento: unsw_nb15
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: linear_svm - unsw_nb15

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
0,linear_svm,randomized_search,unsw_nb15,235490,12,13,5,1,1,baseline,"{""classifier__C"": 1.0, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.938367,0.938825,0.936461,0.937901,0.936837,0.937678,0.000898,1,0.825990,0.827689,0.837049,0.836943,0.825053,0.830545,0.005335,8,0.878600,0.879761,0.883969,0.884551,0.877399,0.880856,0.002884,1,0.957765,0.958164,0.960313,0.960302,0.957528,0.958814,0.001236,8,0.986438,0.986518,0.985801,0.986146,0.986093,0.986199,0.000257,3,0.971890,0.972134,0.972890,0.973052,0.971600,0.972313,0.000565,1,0.925245,0.925947,0.928429,0.928801,0.924500,0.926585,0.001724,1,0.954351,0.954754,0.956049,0.956304,0.953883,0.955068,0.000949,1,0.906214,0.907103,0.911425,0.911544,0.905573,0.908372,0.002588,5,19.481396,14.295596,0.105736,0.010332
7,linear_svm,randomized_search,unsw_nb15,235490,12,13,5,1,8,random,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.938383,0.938623,0.935919,0.938254,0.936646,0.937565,0.001079,2,0.824610,0.826415,0.832590,0.833970,0.822399,0.827997,0.004519,9,0.877825,0.878952,0.881236,0.883044,0.875813,0.879374,0.002538,2,0.957446,0.957866,0.959270,0.959613,0.956911,0.958221,0.001047,9,0.986465,0.986491,0.985748,0.986278,0.986093,0.986215,0.000274,2,0.971739,0.971968,0.972328,0.972763,0.971283,0.972016,0.000504,2,0.924782,0.925460,0.926782,0.927903,0.923548,0.925695,0.001520,2,0.954096,0.954478,0.955115,0.955816,0.953353,0.954571,0.000844,2,0.905537,0.906453,0.909169,0.910124,0.904246,0.907106,0.002211,6,12.527931,3.053868,0.102885,0.006176
2,linear_svm,randomized_search,unsw_nb15,235490,12,13,5,1,3,random,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.856917,0.855124,0.936190,0.937248,0.856011,0.888298,0.039541,6,0.862193,0.861026,0.867516,0.862527,0.860191,0.862691,0.002553,3,0.859547,0.858065,0.900545,0.898336,0.858096,0.874918,0.020042,3,0.965498,0.965199,0.967474,0.966301,0.965003,0.965895,0.000905,1,0.964012,0.963534,0.985217,0.985562,0.963825,0.972430,0.010583,7,0.964754,0.964366,0.976265,0.975837,0.964414,0.969127,0.005656,4,0.912151,0.911215,0.938405,0.937086,0.911255,0.922022,0.012849,3,0.943649,0.943034,0.961676,0.960954,0.943097,0.950482,0.008850,4,0.913103,0.912280,0.926366,0.924044,0.912008,0.917560,0.006296,1,9.283636,1.325120,0.112890,0.007601
1,linear_svm,randomized_search,unsw_nb15,235490,12,13,5,1,2,random,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.937269,0.937738,0.934542,0.937151,0.935146,0.936369,0.001275,3,0.809003,0.810702,0.815393,0.819958,0.806688,0.812349,0.004756,10,0.868426,0.869605,0.870911,0.874646,0.866180,0.869954,0.002815,4,0.953834,0.954229,0.955271,0.956352,0.953274,0.954592,0.001096,10,0.986465,0.986544,0.985721,0.986252,0.986013,0.986199,0.000302,4,0.969875,0.970118,0.970257,0.971072,0.969367,0.970138,0.000557,3,0.919150,0.919861,0.920584,0.922859,0.917774,0.920046,0.001685,4,0.950975,0.951378,0.951654,0.952992,0.950147,0.951429,0.000932,3,0.897734,0.898623,0.900557,0.903105,0.896350,0.899274,0.002352,9,15.154101,5.734889,0.105267,0.004334
6,linear_svm,randomized_search,unsw_nb15,235490,12,13,5,1,7,random,"{""classifier__C"": 2.23218499287176, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.856390,0.854674,0.858779,0.937248,0.855649,0.872548,0.032378,8,0.862300,0.861026,0.867622,0.862527,0.860191,0.862733,0.002589,1,0.859334,0.857838,0.863178,0.898336,0.857914,0.867320,0.015629,5,0.965518,0.965195,0.966818,0.966301,0.964999,0.965766,0.000688,2,0.963853,0.963401,0.964329,0.985562,0.963719,0.968173,0.008700,8,0.964685,0.964297,0.965572,0.975837,0.964359,0.966950,0.004467,6,0.912010,0.911068,0.914375,0.937086,0.911136,0.917135,0.010047,5,0.943543,0.942928,0.944987,0.960954,0.943012,0.947085,0.006974,5,0.913076,0.912213,0.915976,0.924044,0.911955,0.915453,0.004527,2,10.076294,2.888695,0.106931,0.007632
11,linear_svm,randomized_search,unsw_nb15,235490,12,13,5,1,12,random,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.856570,0.854584,0.856798,0.937248,0.855649,0.872170,0.032548,9,0.862300,0.861026,0.867622,0.862527,0.860191,0.862733,0.002589,1,0.859425,0.857793,0.862176,0.898336,0.857914,0.867129,0.015683,6,0.965520,0.965194,0.966799,0.966301,0.964999,0.965763,0.000683,3,0.963906,0.963375,0.963745,0.985562,0.963719,0.968061,0.008752,9,0.964712,0.964283,0.965270,0.975837,0.964359,0.966892,0.004486,7,0.912069,0.911038,0.913723,0.937086,0.911136,0.917011,0.010084,6,0.943586,0.942906,0.944520,0.960954,0.943012,0.946996,0.007002,6,0.913103,0.912200,0.915684,0.924044,0.911955,0.915397,0.004521,3,9.339623,1.621156,0.079591,0.009919
8,linear_svm,randomized_search,unsw_nb15,235490,12,13,5,1,9,random,"{""classifier__C"": 0.03684406880492199, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.935488,0.935939,0.933367,0.935347,0.933503,0.934729,0.001075,4,0.783629,0.787982,0.788110,0.795541,0.780892,0.787231,0.004971,11,0.852851,0.855611,0.854610,0.859798,0.850405,0.854655,0.003120,7,0.948021,0.949015,0.949009,0.950724,0.947371,0.948828,0.001135,11,0.986491,0.986518,0.985933,0.986252,0.986093,0.986257,0.000226,1,0.966873,0.967403,0.967119,0.968162,0.966344,0.967180,0.000602,5,0.909862,0.911507,0.910865,0.913980,0.908374,0.910918,0.001861,7,0.945921,0.946813,0.946367,0.948108,0.945051,0.946452,0.001012,7,0.885060,0.887250,0.887022,0.890897,0.883492,0.886744,0.002489,11,9.787471,2.543971,0.102065,0.003970
12,linear_svm,randomized_search,unsw_nb15,235490,12,13,5,1,13,random,"{""classifier__C"": 0.1932075262142986, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.821859,0.821965,0.818127,0.933663,0.820820,0.843287,0.045209,10,0.860601,0.859752,0.866242,0.862102,0.858811,0.861501,0.002606,4,0.840784,0.840434,0.841497,0.896457,0.839386,0.851712,0.022383,8,0.964737,0.964533,0.966060,0.966172,0.964288,0.965158,0.000796,4,0.953369,0.953449,0.951855,0.984686,0.953129,0.959298,0.012707,10,0.959020,0.958959,0.958905,0.975341,0.958676,0.962180,0.006582,8,0.899902,0.899696,0.900201,0.935899,0.899031,0.906946,0.014482,8,0.934817,0.934711,0.934732,0.960168,0.934265,0.939738,0.010217,8,0.906985,0.906600,0.909049,0.923394,0.905970,0.910400,0.006579,4,8.468008,1.361726,0.063047,0.020445
3,linear_svm,randomized_search,unsw_nb15,235490,12,13,5,1,4,random,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.819990,0.820620,0.816768,0.818292,0.818879,0.818910,0.001346,11,0.853594,0.850940,0.858386,0.857643,0.850000,0.854113,0.003405,5,0.836454,0.835505,0.837060,0.837506,0.834149,0.836135,0.001198,9,0.963023,0.962391,0.964138,0.963976,0.962138,0.963133,0.000809,5,0.953157,0.953502,0.951855,0.952386,0.952996,0.952779,0.000587,11,0.958064,0.957926,0.957957,0.958146,0.957546,0.957928,0.000206,11,0.897259,0.896715,0.897509,0.897826,0.895847,0.897031,0.000695,9,0.933246,0.932991,0.933161,0.933437,0.932396,0.933046,0.000355,10,0.903375,0.902221,0.905121,0.905015,0.901498,0.903446,0.001454,7,8.712817,2.741451,0.107106,0.008757
4,linear_svm,randomized_search,unsw_nb15,235490,12,13,5,1,5,random,"{""classifier__C"": 0.015151125123102896, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.818191,0.819444,0.815605,0.816538,0.817295,0.817415,0.001325,12,0.848073,0.845631,0.852229,0.853291,0.844798,0.848805,0.003421,6,0.832864,0.832332,0.833515,0.834510,0.830819,0.832808,0.001231,10,0.961671,0.961100,0.962636,0.962903,0.960868,0.961836,0.000810,6,0.952892,0.953422,0.951829,0.952068,0.952784,0.952599,0.000579,12,0.957261,0.957246,0.957202,0.957455,0.956809,0.957195,0.000211,12,0.895063,0.894789,0.895358,0.895982,0.893814,0.895001,0.000714,10,0.931929,0.931865,0.931908,0.932311,0.931186,0.931840,0.000364,11,0.900482,0.899527,0.902029,0.902679,0.898791,0.900702,0.001466,8,6.775178,3.133931,0.105388,0.003713
5,linear_svm,randomized_search,unsw_nb15,235490,12,13,5,1,6,random,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.817034,0.818829,0.814143,0.814943,0.816179,0.816226,0.001638,13,0.845313,0.843083,0.848195,0.847558,0.841826,0.845195,0.002466,7,0.830933,0.830779,0.830820,0.830931,0.828804,0.830454,0.000827,11,0.960994,0.960481,0.961646,0.961502,0.960141,0.960953,0.000577,7,0.952679,0.953369,0.951590,0.951882,0.952598,0.952424,0.000629,13,0.956818,0.956912,0.956591,0.956668,0.956355,0.956669,0.000193,13,0.893876,0.893845,0.893706,0.893799,0.892580,0.893561,0.000494,11,0.931207,0.931313,0.930910,0.931016,0.930443,0.930978,0.000302,13,0.898996,0.898226,0.899893,0.899720,0.897212,0.898809,0.000993,10,5.279154,0.880309,0.113209,0.013678
10,linear_svm,randomized_search,unsw_nb15,235490,12,13,5,1,11,random,"{""classifier__C"": 0.014056787147388339, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.889055,0.891553,0.885426,0.890002,0.886062,0.888419,0.002334,5,0.759741,0.761970,0.762951,0.773036,0.757856,0.763111,0.005269,12,0.819327,0.821684,0.819638,0.827406,0.816959,0.821003,0.003535,12,0.942047,0.942583,0.942716,0.945061,0.941574,0.942796,0.001203,12,0.976300,0.976831,0.975317,0.976113,0.975636,0.976039,0.000526,5,0.958868,0.959402,0.958739,0.960336,0.958302,0.959129,0.000698,9,0.889097,0.890543,0.889189,0.893871,0.887631,0.890066,0.002114,12,0.932991,0.933861,0.932842,0.935496,0.932078,0.933454,0.001168,9,0.868020,0.869401,0.869134,0.874575,0.866746,0.869575,0.002670,12,5.848757,0.487663,0.123683,0.022502
9,linear_svm,randomized_search,unsw_nb15,235490,12,13,5,1,10,random,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.887941,0.889972,0.884213,0.888218,0.883234,0.886716,0.002559,7,0.751247,0.755707,0.753928,0.765074,0.751592,0.755510,0.005050,13,0.813895,0.817362,0.813890,0.822060,0.812113,0.815864,0.003535,13,0.940121,0.941151,0.940665,0.943233,0.940126,0.941059,0.001152,13,0.976300,0.976645,0.975317,0.975928,0.975158,0.975869,0.000566,6,0.957869,0.958569,0.957677,0.959302,0.957322,0.958148,0.000706,10,0.885882,0.887966,0.885783,0.890681,0.884717,0.887006,0.002118,13,0.931292,0.932460,0.931037,0.933755,0.930443,0.931798,0.001178,12,0.863774,0.866176,0.864622,0.870501,0.863375,0.865690,0.002590,13,5.186654,0.354464,0.112680,0.009221

modelo: linear_svm
 origem do treinamento: iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: linear_svm - iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
0,linear_svm,randomized_search,iot23,235490,12,13,5,1,1,baseline,"{""classifier__C"": 1.0, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.995101,0.995302,0.995407,0.996267,0.995737,0.995563,0.000408,1,0.992037,0.989702,0.989384,0.991507,0.991826,0.990891,0.001118,11,0.993567,0.992494,0.992387,0.993881,0.993778,0.993221,0.000647,1,0.998011,0.997429,0.997350,0.997879,0.997958,0.997726,0.000279,10,0.998779,0.998832,0.998859,0.999071,0.998938,0.998896,0.000102,1,0.998395,0.998130,0.998104,0.998475,0.998448,0.998310,0.000160,1,0.995981,0.995312,0.995245,0.996178,0.996113,0.995766,0.000403,1,0.997431,0.997006,0.996964,0.997558,0.997516,0.997295,0.000257,1,0.995408,0.994267,0.994122,0.995289,0.995382,0.994894,0.000574,1,7.865280,3.307988,0.112066,0.008781
7,linear_svm,randomized_search,iot23,235490,12,13,5,1,8,random,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.995419,0.993605,0.995407,0.996479,0.995737,0.995329,0.000946,2,0.992037,0.989702,0.989384,0.991401,0.991826,0.990870,0.001107,12,0.993725,0.991649,0.992387,0.993934,0.993778,0.993095,0.000912,2,0.998011,0.997428,0.997350,0.997853,0.997958,0.997720,0.000276,12,0.998859,0.998408,0.998859,0.999124,0.998938,0.998838,0.000236,2,0.998435,0.997918,0.998104,0.998488,0.998448,0.998278,0.000227,2,0.996080,0.994784,0.995245,0.996211,0.996113,0.995687,0.000570,2,0.997495,0.996667,0.996964,0.997580,0.997516,0.997244,0.000364,2,0.995448,0.994055,0.994122,0.995263,0.995382,0.994854,0.000628,2,7.377490,2.726519,0.108757,0.009114
1,linear_svm,randomized_search,iot23,235490,12,13,5,1,2,random,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.996056,0.993604,0.995195,0.996904,0.994465,0.995245,0.001159,3,0.992037,0.989595,0.989384,0.991295,0.991826,0.990828,0.001121,13,0.994043,0.991596,0.992281,0.994092,0.993144,0.993031,0.000978,3,0.998012,0.997402,0.997350,0.997827,0.997958,0.997709,0.000280,13,0.999018,0.998408,0.998806,0.999230,0.998620,0.998816,0.000289,3,0.998515,0.997904,0.998077,0.998528,0.998289,0.998263,0.000244,3,0.996279,0.994750,0.995179,0.996310,0.995716,0.995647,0.000611,3,0.997622,0.996645,0.996921,0.997643,0.997261,0.997219,0.000390,3,0.995528,0.994002,0.994095,0.995263,0.995223,0.994822,0.000641,4,6.863280,1.031082,0.202990,0.124391
8,linear_svm,randomized_search,iot23,235490,12,13,5,1,9,random,"{""classifier__C"": 0.03684406880492199, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.996693,0.993605,0.993075,0.995310,0.995313,0.994799,0.001305,4,0.992037,0.989808,0.989490,0.991295,0.991826,0.990891,0.001048,10,0.994360,0.991703,0.991279,0.993299,0.993566,0.992841,0.001164,4,0.998012,0.997455,0.997375,0.997826,0.997958,0.997725,0.000262,11,0.999177,0.998408,0.998275,0.998832,0.998832,0.998705,0.000325,4,0.998594,0.997931,0.997825,0.998329,0.998395,0.998215,0.000291,4,0.996477,0.994817,0.994552,0.995814,0.995981,0.995528,0.000727,4,0.997749,0.996688,0.996518,0.997325,0.997431,0.997142,0.000465,4,0.995607,0.994108,0.993883,0.995064,0.995329,0.994798,0.000681,5,4.947173,0.652203,0.118611,0.012956
10,linear_svm,randomized_search,iot23,235490,12,13,5,1,11,random,"{""classifier__C"": 0.014056787147388339, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.996162,0.994136,0.993500,0.994463,0.994571,0.994566,0.000881,5,0.992144,0.989914,0.989809,0.991401,0.991826,0.991019,0.000974,9,0.994149,0.992020,0.991651,0.992930,0.993197,0.992789,0.000886,5,0.998038,0.997481,0.997454,0.997852,0.997958,0.997757,0.000243,9,0.999045,0.998540,0.998381,0.998620,0.998646,0.998646,0.000220,5,0.998541,0.998011,0.997918,0.998236,0.998302,0.998201,0.000221,5,0.996345,0.995015,0.994784,0.995583,0.995749,0.995495,0.000553,5,0.997664,0.996815,0.996667,0.997176,0.997282,0.997121,0.000353,5,0.995594,0.994227,0.994095,0.995011,0.995236,0.994833,0.000581,3,4.676376,0.534652,0.114385,0.008987
9,linear_svm,randomized_search,iot23,235490,12,13,5,1,10,random,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.994043,0.993818,0.993184,0.994145,0.994466,0.993931,0.000428,6,0.992144,0.989914,0.989915,0.991401,0.991932,0.991061,0.000967,8,0.993092,0.991862,0.991547,0.992771,0.993197,0.992494,0.000667,6,0.998037,0.997481,0.997481,0.997852,0.997984,0.997767,0.000241,8,0.998514,0.998461,0.998301,0.998540,0.998620,0.998487,0.000106,6,0.998275,0.997971,0.997891,0.998196,0.998302,0.998127,0.000166,6,0.995684,0.994916,0.994719,0.995484,0.995750,0.995310,0.000417,6,0.997240,0.996751,0.996624,0.997112,0.997282,0.997002,0.000266,6,0.995329,0.994187,0.994108,0.994971,0.995276,0.994774,0.000526,6,4.191146,0.331854,0.117349,0.014403
6,linear_svm,randomized_search,iot23,235490,12,13,5,1,7,random,"{""classifier__C"": 2.23218499287176, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.988477,0.990025,0.992339,0.992563,0.991407,0.990962,0.001531,7,0.992674,0.990551,0.990021,0.991826,0.992038,0.991422,0.000983,6,0.990571,0.990288,0.991179,0.992195,0.991722,0.991191,0.000706,7,0.998167,0.997638,0.997507,0.997957,0.998009,0.997855,0.000245,6,0.997107,0.997505,0.998089,0.998142,0.997850,0.997739,0.000388,7,0.997637,0.997571,0.997798,0.998049,0.997930,0.997797,0.000178,7,0.994104,0.993930,0.994488,0.995122,0.994826,0.994494,0.000442,7,0.996221,0.996114,0.996475,0.996879,0.996688,0.996475,0.000284,7,0.994891,0.994028,0.994055,0.994984,0.994944,0.994580,0.000441,8,11.374285,5.312035,0.103413,0.010896
2,linear_svm,randomized_search,iot23,235490,12,13,5,1,3,random,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.988477,0.990236,0.992023,0.992458,0.991302,0.990899,0.001426,9,0.992674,0.990551,0.990127,0.991826,0.992038,0.991443,0.000953,4,0.990571,0.990393,0.991074,0.992142,0.991670,0.991170,0.000658,8,0.998167,0.997638,0.997533,0.997957,0.998009,0.997861,0.000238,4,0.997107,0.997558,0.998009,0.998116,0.997824,0.997723,0.000361,9,0.997637,0.997598,0.997771,0.998036,0.997916,0.997792,0.000166,9,0.994104,0.993996,0.994423,0.995089,0.994793,0.994481,0.000412,8,0.996221,0.996157,0.996433,0.996858,0.996667,0.996467,0.000265,8,0.994891,0.994055,0.994068,0.994971,0.994931,0.994583,0.000427,7,14.684927,3.611193,0.113199,0.014641
11,linear_svm,randomized_search,iot23,235490,12,13,5,1,12,random,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.988477,0.990236,0.992233,0.992247,0.991407,0.990920,0.001426,8,0.992674,0.990551,0.990021,0.991826,0.992038,0.991422,0.000983,6,0.990571,0.990393,0.991126,0.992037,0.991722,0.991170,0.000636,9,0.998167,0.997638,0.997507,0.997957,0.998009,0.997855,0.000245,7,0.997107,0.997558,0.998063,0.998063,0.997850,0.997728,0.000361,8,0.997637,0.997598,0.997784,0.998010,0.997930,0.997792,0.000160,8,0.994104,0.993996,0.994455,0.995023,0.994826,0.994481,0.000398,9,0.996221,0.996157,0.996454,0.996815,0.996688,0.996467,0.000256,8,0.994891,0.994055,0.994042,0.994944,0.994944,0.994575,0.000431,9,8.029718,1.756821,0.071049,0.023405
12,linear_svm,randomized_search,iot23,235490,12,13,5,1,13,random,"{""classifier__C"": 0.1932075262142986, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.988163,0.989710,0.989812,0.991722,0.991406,0.990163,0.001288,10,0.992674,0.990551,0.990127,0.991932,0.991932,0.991443,0.000951,5,0.990414,0.990131,0.989970,0.991827,0.991669,0.990802,0.000787,10,0.998167,0.997637,0.997532,0.997983,0.997983,0.997860,0.000237,5,0.997028,0.997426,0.997452,0.997930,0.997850,0.997537,0.000326,10,0.997597,0.997532,0.997492,0.997956,0.997916,0.997699,0.000197,10,0.994005,0.993831,0.993731,0.994892,0.994793,0.994250,0.000492,10,0.996157,0.996051,0.995987,0.996730,0.996667,0.996318,0.000316,10,0.994851,0.993988,0.993790,0.994931,0.994891,0.994490,0.000496,10,5.983516,0.971155,0.073492,0.014551
5,linear_svm,randomized_search,iot23,235490,12,13,5,1,6,random,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.989104,0.989081,0.988448,0.990569,0.989415,0.989323,0.000697,11,0.992674,0.990551,0.990127,0.992357,0.992251,0.991592,0.001041,1,0.990886,0.989815,0.989287,0.991462,0.990831,0.990456,0.000789,11,0.998167,0.997637,0.997531,0.998088,0.998061,0.997897,0.000260,1,0.997266,0.997266,0.997107,0.997638,0.997346,0.997325,0.000175,11,0.997717,0.997452,0.997319,0.997863,0.997703,0.997611,0.000197,11,0.994301,0.993634,0.993303,0.994663,0.994267,0.994033,0.000493,11,0.996348,0.995923,0.995711,0.996582,0.996327,0.996178,0.000315,11,0.994970,0.993909,0.993617,0.994997,0.994798,0.994458,0.000579,11,4.407492,0.797130,0.118813,0.009358
3,linear_svm,randomized_search,iot23,235490,12,13,5,1,4,random,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.987850,0.989186,0.989497,0.989832,0.989099,0.989093,0.000673,12,0.992674,0.990551,0.990127,0.992038,0.992144,0.991507,0.000987,3,0.990256,0.989868,0.989812,0.990934,0.990620,0.990298,0.000431,12,0.998167,0.997637,0.997531,0.998008,0.998034,0.997876,0.000246,3,0.996948,0.997293,0.997372,0.997452,0.997266,0.997266,0.000172,12,0.997557,0.997465,0.997452,0.997730,0.997650,0.997571,0.000107,12,0.993907,0.993666,0.993632,0.994332,0.994135,0.993934,0.000269,12,0.996093,0.995945,0.995923,0.996369,0.996242,0.996114,0.000171,12,0.994811,0.993922,0.993750,0.994745,0.994705,0.994387,0.000454,13,6.126533,1.713602,0.112159,0.012169
4,linear_svm,randomized_search,iot23,235490,12,13,5,1,5,random,"{""classifier__C"": 0.015151125123102896, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.987746,0.989081,0.988345,0.990673,0.988995,0.988968,0.000980,13,0.992674,0.990551,0.990234,0.992251,0.992144,0.991571,0.000984,2,0.990204,0.989815,0.989288,0.991461,0.990567,0.990267,0.000732,13,0.998166,0.997637,0.997557,0.998062,0.998034,0.997891,0.000246,2,0.996921,0.997266,0.997081,0.997664,0.997240,0.997234,0.000248,13,0.997544,0.997452,0.997319,0.997863,0.997637,0.997563,0.000183,13,0.993874,0.993634,0.993304,0.994662,0.994102,0.993915,0.000458,13,0.996072,0.995923,0.995711,0.996582,0.996221,0.996102,0.000293,13,0.994798,0.993909,0.993657,0.994957,0.994692,0.994403,0.000519,12,5.579012,1.139400,0.115596,0.005863

modelo: linear_svm
 origem do treinamento: cicids2017_unsw_nb15
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: linear_svm - cicids2017_unsw_nb15

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
2,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,3,random,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.681496,0.693933,0.653643,0.682544,0.681982,0.678720,0.013366,7,0.868457,0.890753,0.879087,0.864809,0.865074,0.873636,0.010007,1,0.763701,0.780120,0.749785,0.762942,0.762694,0.763848,0.009641,1,0.964696,0.970606,0.966917,0.963782,0.963840,0.965968,0.002582,1,0.898538,0.901789,0.883539,0.899437,0.899145,0.896490,0.006568,7,0.930442,0.934933,0.923350,0.930499,0.930369,0.929919,0.003718,3,0.847072,0.857527,0.836567,0.846720,0.846531,0.846883,0.006631,1,0.892522,0.899582,0.882649,0.892511,0.892331,0.891919,0.005395,3,0.883498,0.896271,0.881313,0.882123,0.882110,0.885063,0.005648,1,34.724214,7.875248,0.183222,0.014613
6,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,7,random,"{""classifier__C"": 2.23218499287176, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.681326,0.691300,0.651655,0.674661,0.681535,0.676096,0.013323,8,0.868457,0.876951,0.878662,0.864490,0.864544,0.870621,0.006065,2,0.763594,0.773137,0.748322,0.757870,0.762208,0.761026,0.008075,2,0.964693,0.967027,0.966770,0.963557,0.963697,0.965149,0.001483,2,0.898458,0.902107,0.882571,0.895775,0.898999,0.895582,0.006810,8,0.930398,0.933440,0.922754,0.928430,0.930225,0.929049,0.003535,4,0.846996,0.853288,0.835538,0.843150,0.846216,0.845038,0.005781,2,0.892458,0.897076,0.881789,0.889518,0.892108,0.890590,0.005029,4,0.883458,0.889529,0.880617,0.880133,0.881771,0.883101,0.003412,2,33.985355,8.800433,0.176366,0.010999
11,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,12,random,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.681042,0.691361,0.650525,0.674857,0.681647,0.675886,0.013737,9,0.868457,0.876845,0.878450,0.864490,0.864650,0.870578,0.005966,3,0.763416,0.773134,0.747499,0.757993,0.762319,0.760872,0.008319,3,0.964688,0.967000,0.966693,0.963561,0.963726,0.965134,0.001454,3,0.898325,0.902147,0.882013,0.895868,0.899039,0.895479,0.007024,9,0.930325,0.933449,0.922414,0.928482,0.930259,0.928986,0.003654,5,0.846870,0.853291,0.834956,0.843238,0.846289,0.844929,0.005964,3,0.892352,0.897087,0.881301,0.889592,0.892161,0.890499,0.005197,5,0.883391,0.889496,0.880232,0.880179,0.881844,0.883028,0.003444,3,29.690395,4.665815,0.133004,0.018396
12,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,13,random,"{""classifier__C"": 0.1932075262142986, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.615535,0.687879,0.616611,0.614834,0.617705,0.630513,0.028699,10,0.867396,0.867608,0.876380,0.861943,0.862951,0.867256,0.005102,4,0.720078,0.767360,0.723897,0.717714,0.720018,0.729813,0.018878,4,0.963075,0.964592,0.965455,0.961628,0.961960,0.963342,0.001480,4,0.864566,0.901590,0.863767,0.865001,0.866474,0.872279,0.014682,10,0.911166,0.932027,0.911784,0.910759,0.911724,0.915492,0.008276,10,0.815622,0.849694,0.817841,0.814236,0.815871,0.822653,0.013569,4,0.865132,0.894794,0.866289,0.864389,0.865769,0.871275,0.011777,10,0.865981,0.884599,0.870073,0.863472,0.864712,0.869768,0.007741,4,22.746835,7.153376,0.129189,0.033048
0,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,1,baseline,"{""classifier__C"": 1.0, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.805672,0.812321,0.811528,0.808939,0.805936,0.808879,0.002750,1,0.619758,0.616679,0.615021,0.614862,0.612580,0.615780,0.002379,8,0.700591,0.701107,0.699740,0.698673,0.696080,0.699238,0.001782,8,0.910131,0.909619,0.909244,0.909159,0.908621,0.909355,0.000502,8,0.962632,0.964383,0.964290,0.963692,0.963122,0.963624,0.000672,1,0.935646,0.936201,0.935958,0.935632,0.935078,0.935703,0.000377,1,0.818118,0.818654,0.817849,0.817152,0.815579,0.817471,0.001062,5,0.894061,0.894847,0.894433,0.893923,0.893010,0.894055,0.000613,1,0.791195,0.790531,0.789655,0.789277,0.787851,0.789702,0.001142,8,38.600078,12.783674,0.188380,0.008714
7,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,8,random,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.800700,0.810903,0.811125,0.799199,0.805618,0.805509,0.004972,2,0.619546,0.615087,0.614544,0.614544,0.611996,0.615143,0.002450,9,0.698569,0.699550,0.699281,0.694812,0.695584,0.697559,0.001970,9,0.909985,0.909257,0.909136,0.908894,0.908492,0.909153,0.000491,9,0.961451,0.964144,0.964223,0.961397,0.963082,0.962859,0.001240,2,0.935010,0.935897,0.935870,0.934408,0.934991,0.935235,0.000572,2,0.816790,0.817723,0.817576,0.814610,0.815287,0.816397,0.001243,6,0.893074,0.894337,0.894284,0.892023,0.892862,0.893316,0.000885,2,0.790498,0.789616,0.789383,0.787970,0.787539,0.789001,0.001092,9,29.852586,9.082665,0.184878,0.015817
3,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,4,random,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.610357,0.613445,0.615356,0.612753,0.610234,0.612429,0.001940,11,0.865962,0.862724,0.875053,0.861465,0.861518,0.865345,0.005122,7,0.716032,0.717037,0.722579,0.716129,0.714424,0.717240,0.002799,5,0.962575,0.961804,0.965077,0.961453,0.961404,0.962463,0.001373,7,0.861806,0.864102,0.863249,0.863886,0.862426,0.863094,0.000869,11,0.909408,0.910339,0.911327,0.910062,0.909230,0.910073,0.000748,11,0.812720,0.813688,0.816953,0.813096,0.811827,0.813657,0.001755,7,0.862637,0.863826,0.865610,0.863402,0.862245,0.863544,0.001173,11,0.863884,0.863413,0.869151,0.862676,0.861972,0.864219,0.002550,5,15.440869,3.339898,0.192335,0.013393
4,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,5,random,"{""classifier__C"": 0.015151125123102896, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.609960,0.612468,0.615132,0.611605,0.609757,0.611785,0.001957,12,0.866016,0.862618,0.875584,0.861571,0.861783,0.865514,0.005282,6,0.715777,0.716332,0.722606,0.715381,0.714188,0.716857,0.002959,6,0.962580,0.961752,0.965212,0.961452,0.961462,0.962491,0.001421,6,0.861567,0.863558,0.863037,0.863209,0.862108,0.862696,0.000741,12,0.909277,0.910014,0.911269,0.909686,0.909078,0.909865,0.000773,12,0.812527,0.813173,0.816937,0.812534,0.811633,0.813361,0.001854,8,0.862457,0.863370,0.865546,0.862882,0.862043,0.863260,0.001225,12,0.863791,0.863088,0.869310,0.862390,0.861946,0.864105,0.002677,7,14.002952,2.093446,0.176037,0.002994
5,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,6,random,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.609805,0.611481,0.614774,0.611366,0.609689,0.611423,0.001836,13,0.866281,0.862884,0.875955,0.862208,0.862367,0.865939,0.005224,5,0.715761,0.715748,0.722485,0.715437,0.714342,0.716755,0.002912,7,0.962646,0.961797,0.965302,0.961612,0.961612,0.962594,0.001407,5,0.861435,0.862948,0.862771,0.862970,0.861975,0.862420,0.000612,13,0.909232,0.909695,0.911161,0.909625,0.909072,0.909757,0.000740,13,0.812497,0.812722,0.816823,0.812531,0.811707,0.813256,0.001817,9,0.862404,0.862935,0.865408,0.862818,0.862054,0.863124,0.001184,13,0.863858,0.862916,0.869363,0.862589,0.862171,0.864179,0.002651,6,17.477610,2.528563,0.183553,0.027342
1,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,2,random,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.730412,0.775896,0.739200,0.738252,0.772496,0.751251,0.019011,3,0.618590,0.612751,0.613057,0.612898,0.611518,0.613763,0.002474,10,0.669867,0.684740,0.670245,0.669760,0.682645,0.675451,0.006763,10,0.908170,0.908030,0.907218,0.907161,0.907684,0.907652,0.000410,10,0.942926,0.955758,0.945923,0.945671,0.954974,0.949050,0.005268,3,0.925221,0.931283,0.926166,0.926016,0.930729,0.927883,0.002576,6,0.797544,0.808011,0.798206,0.797888,0.806687,0.801667,0.004663,10,0.878063,0.887161,0.879347,0.879114,0.886280,0.881993,0.003894,6,0.780758,0.784254,0.779490,0.779285,0.783246,0.781407,0.002004,10,34.842022,18.371070,0.190325,0.021896
8,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,9,random,"{""classifier__C"": 0.03684406880492199, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.722612,0.727887,0.729572,0.730222,0.724957,0.727050,0.002871,4,0.618006,0.611583,0.612314,0.612898,0.610403,0.613041,0.002619,11,0.666228,0.664686,0.665820,0.666436,0.662767,0.665187,0.001353,11,0.907844,0.906633,0.906818,0.906957,0.906297,0.906910,0.000517,11,0.940696,0.942846,0.943256,0.943389,0.942101,0.942458,0.000988,4,0.923978,0.924385,0.924678,0.924814,0.923853,0.924342,0.000377,7,0.795103,0.794535,0.795249,0.795625,0.793310,0.794764,0.000807,11,0.876162,0.876598,0.877065,0.877288,0.875759,0.876574,0.000563,7,0.779351,0.777215,0.777785,0.778143,0.776252,0.777749,0.001025,11,31.011906,18.123233,0.170862,0.015267
10,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,11,random,"{""classifier__C"": 0.014056787147388339, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.720855,0.725266,0.727187,0.728456,0.721618,0.724677,0.002996,5,0.617422,0.610574,0.611624,0.611996,0.609660,0.612255,0.002710,12,0.665142,0.662997,0.664418,0.665167,0.660932,0.663731,0.001606,12,0.907675,0.906353,0.906611,0.906722,0.906054,0.906683,0.000547,12,0.940232,0.942183,0.942632,0.942964,0.941199,0.941842,0.001001,5,0.923667,0.923921,0.924271,0.924488,0.923292,0.923928,0.000425,8,0.794404,0.793459,0.794344,0.794827,0.792112,0.793829,0.000967,12,0.875674,0.875865,0.876428,0.876768,0.874889,0.875925,0.000649,8,0.778827,0.776379,0.777128,0.777480,0.775430,0.777049,0.001134,12,15.592839,3.482760,0.193766,0.018820
9,linear_svm,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,10,random,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.720652,0.724956,0.726682,0.727962,0.721294,0.724309,0.002893,6,0.617210,0.610044,0.611200,0.611465,0.609501,0.611884,0.002760,13,0.664932,0.662554,0.663957,0.664647,0.660702,0.663358,0.001562,13,0.907625,0.906234,0.906509,0.906598,0.906012,0.906596,0.000555,13,0.940192,0.942143,0.942526,0.942871,0.941119,0.941770,0.000983,6,0.923621,0.923840,0.924167,0.924379,0.923232,0.923848,0.000404,9,0.794277,0.793197,0.794062,0.794513,0.791967,0.793603,0.000931,13,0.875600,0.875727,0.876258,0.876587,0.874793,0.875793,0.000615,9,0.778701,0.776093,0.776863,0.777168,0.775310,0.776827,0.001137,13,18.628148,8.575904,0.174714,0.003862

modelo: linear_svm
 origem do treinamento: cicids2017_iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: linear_svm - cicids2017_iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
0,linear_svm,randomized_search,cicids2017_iot23,470980,12,13,5,1,1,baseline,"{""classifier__C"": 1.0, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.888889,0.896034,0.889194,0.888900,0.888280,0.890259,0.002902,1,0.948296,0.949782,0.946868,0.948301,0.946603,0.947970,0.001147,8,0.917632,0.922125,0.917125,0.917640,0.916515,0.918208,0.002002,1,0.986855,0.987255,0.986497,0.986855,0.986427,0.986778,0.000297,8,0.970368,0.972451,0.970500,0.970367,0.970235,0.970784,0.000838,1,0.978542,0.979798,0.978433,0.978542,0.978264,0.978716,0.000550,1,0.948087,0.950962,0.947779,0.948091,0.947389,0.948462,0.001276,1,0.965954,0.967918,0.965773,0.965954,0.965508,0.966221,0.000864,1,0.959332,0.961117,0.958684,0.959334,0.958419,0.959377,0.000941,4,43.835675,14.405321,0.174477,0.017115
7,linear_svm,randomized_search,cicids2017_iot23,470980,12,13,5,1,8,random,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.885444,0.893629,0.886412,0.886356,0.885538,0.887476,0.003103,2,0.947394,0.948561,0.945648,0.947187,0.946125,0.946983,0.001022,9,0.915372,0.920276,0.915072,0.915762,0.914830,0.916262,0.002031,2,0.986615,0.986941,0.986180,0.986565,0.986296,0.986520,0.000266,9,0.969360,0.971775,0.969704,0.969637,0.969425,0.969980,0.000906,2,0.977911,0.979299,0.977873,0.978028,0.977788,0.978180,0.000565,2,0.946641,0.949788,0.946472,0.946895,0.946309,0.947221,0.001298,2,0.964967,0.967132,0.964892,0.965147,0.964765,0.965381,0.000885,2,0.958377,0.960168,0.957676,0.958412,0.957775,0.958482,0.000895,5,44.507940,12.138522,0.185112,0.023690
1,linear_svm,randomized_search,cicids2017_iot23,470980,12,13,5,1,2,random,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.882536,0.890464,0.884615,0.884703,0.883197,0.885103,0.002806,3,0.946438,0.947234,0.944904,0.946125,0.944374,0.945815,0.001040,10,0.913371,0.917972,0.913767,0.914384,0.912761,0.914451,0.001838,3,0.986364,0.986596,0.985987,0.986293,0.985848,0.986217,0.000268,10,0.968510,0.970872,0.969186,0.969173,0.968775,0.969303,0.000825,3,0.977356,0.978671,0.977514,0.977658,0.977237,0.977687,0.000512,3,0.945363,0.948322,0.945640,0.946021,0.944999,0.946069,0.001175,3,0.964096,0.966145,0.964330,0.964563,0.963894,0.964606,0.000802,3,0.957474,0.959053,0.957045,0.957649,0.956574,0.957559,0.000834,6,27.382137,11.378033,0.190768,0.029954
8,linear_svm,randomized_search,cicids2017_iot23,470980,12,13,5,1,9,random,"{""classifier__C"": 0.03684406880492199, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.882196,0.889293,0.884098,0.884060,0.882654,0.884460,0.002531,4,0.946120,0.947075,0.944586,0.945860,0.944214,0.945571,0.001045,11,0.913040,0.917275,0.913341,0.913916,0.912397,0.913994,0.001712,4,0.986282,0.986551,0.985905,0.986223,0.985805,0.986153,0.000269,11,0.968417,0.970527,0.969040,0.968987,0.968616,0.969118,0.000742,4,0.977268,0.978474,0.977400,0.977529,0.977135,0.977561,0.000475,4,0.945154,0.947874,0.945371,0.945723,0.944766,0.945778,0.001093,4,0.963958,0.965837,0.964149,0.964362,0.963735,0.964408,0.000744,4,0.957268,0.958801,0.956813,0.957424,0.956415,0.957344,0.000810,7,16.755646,8.942787,0.176610,0.011877
10,linear_svm,randomized_search,cicids2017_iot23,470980,12,13,5,1,11,random,"{""classifier__C"": 0.014056787147388339, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.881910,0.888795,0.883861,0.884054,0.882373,0.884199,0.002442,6,0.945907,0.946969,0.944427,0.945807,0.944055,0.945433,0.001062,12,0.912788,0.916960,0.913141,0.913889,0.912173,0.913790,0.001679,5,0.986228,0.986523,0.985864,0.986210,0.985764,0.986118,0.000274,12,0.968338,0.970381,0.968974,0.968987,0.968536,0.969043,0.000715,6,0.977201,0.978386,0.977346,0.977523,0.977074,0.977506,0.000465,6,0.944995,0.947673,0.945243,0.945706,0.944623,0.945648,0.001072,5,0.963852,0.965699,0.964064,0.964351,0.963640,0.964321,0.000728,5,0.957123,0.958675,0.956700,0.957397,0.956296,0.957238,0.000810,8,8.149492,0.619101,0.176216,0.010209
9,linear_svm,randomized_search,cicids2017_iot23,470980,12,13,5,1,10,random,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.882009,0.888800,0.883893,0.884005,0.882324,0.884206,0.002434,5,0.946013,0.947022,0.944321,0.945754,0.944002,0.945422,0.001118,13,0.912891,0.916988,0.913108,0.913837,0.912121,0.913789,0.001690,6,0.986255,0.986536,0.985837,0.986197,0.985751,0.986115,0.000288,13,0.968364,0.970381,0.968987,0.968974,0.968523,0.969046,0.000711,5,0.977228,0.978392,0.977340,0.977509,0.977061,0.977506,0.000467,5,0.945059,0.947690,0.945224,0.945673,0.944591,0.945648,0.001078,6,0.963894,0.965710,0.964054,0.964330,0.963618,0.964321,0.000732,5,0.957189,0.958702,0.956654,0.957364,0.956262,0.957234,0.000831,9,7.612372,1.112182,0.177387,0.010844
2,linear_svm,randomized_search,cicids2017_iot23,470980,12,13,5,1,3,random,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.859037,0.856202,0.859087,0.855126,0.854182,0.856727,0.002011,7,0.973405,0.972874,0.971762,0.970913,0.971338,0.972058,0.000938,1,0.912652,0.910817,0.911957,0.909349,0.909001,0.910755,0.001422,7,0.993123,0.992980,0.992701,0.992473,0.992580,0.992771,0.000244,1,0.960071,0.959155,0.960149,0.958875,0.958543,0.959359,0.000644,7,0.976317,0.975774,0.976154,0.975385,0.975265,0.975779,0.000412,7,0.944484,0.943296,0.944056,0.942367,0.942133,0.943267,0.000917,7,0.962737,0.961899,0.962472,0.961283,0.961102,0.961899,0.000640,7,0.966738,0.966014,0.965956,0.964894,0.964941,0.965708,0.000702,1,39.339440,8.882197,0.180478,0.006660
6,linear_svm,randomized_search,cicids2017_iot23,470980,12,13,5,1,7,random,"{""classifier__C"": 2.23218499287176, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.827596,0.833729,0.826457,0.826587,0.824445,0.827763,0.003153,8,0.971122,0.970485,0.969639,0.969002,0.969904,0.970031,0.000725,2,0.893633,0.896924,0.892341,0.892147,0.891279,0.893265,0.001978,8,0.992454,0.992306,0.992066,0.991901,0.992128,0.992171,0.000192,2,0.949428,0.951618,0.949095,0.949175,0.948365,0.949536,0.001099,8,0.970464,0.971536,0.970105,0.970068,0.969753,0.970385,0.000618,8,0.932048,0.934230,0.931223,0.931107,0.930516,0.931825,0.001298,8,0.953767,0.955391,0.953204,0.953140,0.952673,0.953635,0.000944,8,0.960275,0.961051,0.959367,0.959088,0.959135,0.959783,0.000765,2,31.888142,3.113970,0.170241,0.009647
11,linear_svm,randomized_search,cicids2017_iot23,470980,12,13,5,1,12,random,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.827745,0.833387,0.826494,0.826579,0.824519,0.827745,0.003005,9,0.971122,0.970485,0.969639,0.968949,0.969904,0.970020,0.000740,3,0.893720,0.896726,0.892363,0.892120,0.891322,0.893250,0.001902,9,0.992454,0.992305,0.992066,0.991888,0.992129,0.992168,0.000196,3,0.949481,0.951498,0.949108,0.949175,0.948392,0.949531,0.001047,9,0.970492,0.971473,0.970112,0.970061,0.969767,0.970381,0.000593,9,0.932106,0.934100,0.931237,0.931090,0.930545,0.931816,0.001247,9,0.953809,0.955295,0.953215,0.953130,0.952694,0.953629,0.000906,9,0.960302,0.960992,0.959374,0.959062,0.959148,0.959775,0.000751,3,29.685569,4.586398,0.108865,0.027032
12,linear_svm,randomized_search,cicids2017_iot23,470980,12,13,5,1,13,random,"{""classifier__C"": 0.1932075262142986, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.812372,0.814686,0.811482,0.811843,0.807580,0.811593,0.002296,10,0.969689,0.969424,0.967834,0.967834,0.968153,0.968587,0.000804,4,0.884087,0.885344,0.882789,0.883002,0.880606,0.883166,0.001569,10,0.992037,0.991975,0.991551,0.991552,0.991621,0.991748,0.000214,4,0.944014,0.944876,0.943787,0.943920,0.942327,0.943785,0.000823,10,0.967430,0.967853,0.967080,0.967150,0.966346,0.967172,0.000494,10,0.925758,0.926599,0.924934,0.925076,0.923476,0.925169,0.001032,10,0.949149,0.949786,0.948597,0.948703,0.947492,0.948745,0.000753,10,0.956851,0.957150,0.955811,0.955877,0.955240,0.956186,0.000708,10,18.785775,5.248854,0.128938,0.028236
3,linear_svm,randomized_search,cicids2017_iot23,470980,12,13,5,1,4,random,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.810505,0.811414,0.809746,0.809306,0.804793,0.809153,0.002294,11,0.969052,0.969105,0.967569,0.967516,0.967887,0.968226,0.000708,5,0.882716,0.883276,0.881650,0.881367,0.878838,0.881569,0.001532,11,0.991866,0.991883,0.991476,0.991461,0.991543,0.991646,0.000189,5,0.943364,0.943695,0.943163,0.943004,0.941305,0.942906,0.000833,11,0.967007,0.967189,0.966717,0.966626,0.965771,0.966662,0.000489,11,0.924861,0.925233,0.924183,0.923997,0.922304,0.924116,0.001010,11,0.948501,0.948777,0.948045,0.947906,0.946622,0.947970,0.000743,11,0.956208,0.956400,0.955366,0.955260,0.954596,0.955566,0.000661,11,15.618554,5.691588,0.184687,0.025761
4,linear_svm,randomized_search,cicids2017_iot23,470980,12,13,5,1,5,random,"{""classifier__C"": 0.015151125123102896, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.810217,0.810640,0.809386,0.808759,0.804385,0.808678,0.002243,12,0.969052,0.968999,0.967569,0.967463,0.967781,0.968173,0.000704,7,0.882545,0.882774,0.881437,0.881021,0.878551,0.881265,0.001508,12,0.991865,0.991852,0.991475,0.991446,0.991514,0.991630,0.000188,6,0.943258,0.943417,0.943030,0.942805,0.941159,0.942734,0.000814,12,0.966951,0.967028,0.966646,0.966514,0.965681,0.966564,0.000481,12,0.924748,0.924901,0.924042,0.923767,0.922116,0.923915,0.000994,12,0.948416,0.948533,0.947938,0.947737,0.946484,0.947822,0.000731,12,0.956155,0.956208,0.955300,0.955134,0.954470,0.955453,0.000656,12,9.773764,3.285867,0.178844,0.008377
5,linear_svm,randomized_search,cicids2017_iot23,470980,12,13,5,1,6,random,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.810082,0.810209,0.809154,0.808417,0.804306,0.808433,0.002165,13,0.969105,0.968999,0.967463,0.967569,0.967728,0.968173,0.000724,6,0.882487,0.882518,0.881255,0.880862,0.878481,0.881121,0.001474,13,0.991878,0.991851,0.991447,0.991472,0.991500,0.991630,0.000193,7,0.943204,0.943258,0.942951,0.942672,0.941133,0.942644,0.000783,13,0.966929,0.966944,0.966591,0.966456,0.965660,0.966516,0.000468,13,0.924708,0.924731,0.923923,0.923659,0.922071,0.923818,0.000971,13,0.948384,0.948405,0.947853,0.947652,0.946452,0.947749,0.000712,13,0.956155,0.956128,0.955207,0.955121,0.954430,0.955408,0.000656,13,9.803664,4.517057,0.180941,0.012979

modelo: linear_svm
 origem do treinamento: unsw_nb15_iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: linear_svm - unsw_nb15_iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
2,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,3,random,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.935572,0.917381,0.939179,0.944462,0.907830,0.928885,0.013921,5,0.925788,0.925417,0.929459,0.926115,0.924310,0.926218,0.001731,1,0.930654,0.921382,0.934294,0.935199,0.915996,0.927505,0.007552,1,0.981497,0.981315,0.982409,0.981617,0.980990,0.981566,0.000472,1,0.984063,0.979166,0.984951,0.986385,0.976538,0.982221,0.003737,6,0.982778,0.980239,0.983679,0.983995,0.978759,0.981890,0.002047,1,0.956716,0.950810,0.958986,0.959597,0.947378,0.954697,0.004799,1,0.972409,0.968417,0.973852,0.974330,0.966092,0.971020,0.003224,1,0.954926,0.952291,0.957205,0.956250,0.950424,0.954219,0.002516,1,18.820978,2.530950,0.173487,0.006363
11,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,12,random,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.931023,0.908295,0.938069,0.944408,0.906606,0.925680,0.015484,7,0.925735,0.925364,0.929406,0.926062,0.924363,0.926186,0.001708,2,0.928372,0.916750,0.933717,0.935145,0.915399,0.925877,0.008327,2,0.981462,0.981254,0.982391,0.981604,0.980997,0.981542,0.000471,2,0.982855,0.976645,0.984659,0.986371,0.976193,0.981345,0.004175,7,0.982158,0.978944,0.983524,0.983982,0.978589,0.981439,0.002266,4,0.955265,0.947847,0.958621,0.959563,0.946994,0.953658,0.005296,2,0.971432,0.966389,0.973608,0.974309,0.965827,0.970313,0.003567,4,0.954295,0.951004,0.957033,0.956216,0.950278,0.953765,0.002711,2,17.434067,2.302267,0.138264,0.024130
6,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,7,random,"{""classifier__C"": 2.23218499287176, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.931027,0.906915,0.938170,0.944408,0.906365,0.925377,0.015875,8,0.925788,0.925257,0.929406,0.926062,0.924310,0.926165,0.001727,3,0.928400,0.915994,0.933767,0.935145,0.915250,0.925711,0.008544,3,0.981475,0.981221,0.982392,0.981604,0.980982,0.981535,0.000479,3,0.982855,0.976260,0.984686,0.986371,0.976127,0.981260,0.004284,8,0.982164,0.978734,0.983537,0.983982,0.978548,0.981393,0.002326,5,0.955282,0.947364,0.958652,0.959563,0.946899,0.953552,0.005435,3,0.971443,0.966060,0.973629,0.974309,0.965763,0.970241,0.003661,5,0.954322,0.950759,0.957046,0.956216,0.950218,0.953712,0.002782,3,25.136098,10.667747,0.170105,0.010936
0,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,1,baseline,"{""classifier__C"": 1.0, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.947251,0.948611,0.947249,0.947561,0.947913,0.947717,0.000509,2,0.902750,0.902484,0.906423,0.905414,0.900265,0.903467,0.002203,8,0.924465,0.924973,0.926386,0.926008,0.923475,0.925061,0.001052,4,0.975972,0.975916,0.976854,0.976612,0.975374,0.976146,0.000529,8,0.987433,0.987778,0.987380,0.987473,0.987632,0.987539,0.000146,4,0.981669,0.981811,0.982089,0.982013,0.981465,0.981809,0.000227,2,0.953067,0.953392,0.954237,0.954010,0.952470,0.953435,0.000639,4,0.970498,0.970721,0.971188,0.971060,0.970158,0.970725,0.000374,2,0.945092,0.945131,0.946901,0.946443,0.943949,0.945503,0.001055,6,20.321041,4.208949,0.181427,0.012876
7,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,8,random,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.947234,0.948538,0.947187,0.947972,0.947916,0.947769,0.000506,1,0.902431,0.902113,0.905308,0.904246,0.899363,0.902692,0.002037,9,0.924290,0.924743,0.925774,0.925593,0.923001,0.924680,0.001000,5,0.975895,0.975826,0.976585,0.976333,0.975158,0.975959,0.000489,9,0.987433,0.987765,0.987380,0.987592,0.987645,0.987563,0.000141,3,0.981630,0.981759,0.981953,0.981930,0.981362,0.981727,0.000217,3,0.952960,0.953251,0.953863,0.953762,0.952182,0.953204,0.000609,5,0.970434,0.970636,0.970965,0.970922,0.969988,0.970589,0.000358,3,0.944932,0.944939,0.946344,0.945919,0.943504,0.945128,0.000981,8,20.771831,4.968245,0.170400,0.015758
1,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,2,random,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.947248,0.948350,0.946784,0.947953,0.947759,0.947619,0.000548,3,0.897919,0.898662,0.900902,0.901964,0.895541,0.898998,0.002265,10,0.921924,0.922838,0.923274,0.924387,0.920910,0.922667,0.001183,6,0.974810,0.974995,0.975521,0.975783,0.974239,0.975070,0.000543,10,0.987500,0.987765,0.987340,0.987619,0.987659,0.987576,0.000146,2,0.981114,0.981339,0.981395,0.981665,0.980903,0.981283,0.000259,6,0.951519,0.952088,0.952334,0.953026,0.950907,0.951975,0.000721,6,0.969585,0.969946,0.970052,0.970487,0.969234,0.969861,0.000425,6,0.942709,0.943214,0.944121,0.944791,0.941600,0.943287,0.001109,10,18.084658,2.543247,0.183976,0.019296
8,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,9,random,"{""classifier__C"": 0.03684406880492199, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.947682,0.948287,0.946992,0.946841,0.947458,0.947452,0.000517,4,0.887515,0.888736,0.892304,0.892463,0.884395,0.889082,0.003045,11,0.916612,0.917546,0.918835,0.918848,0.914841,0.917336,0.001505,7,0.972320,0.972616,0.973458,0.973495,0.971570,0.972692,0.000726,11,0.987752,0.987884,0.987513,0.987473,0.987738,0.987672,0.000156,1,0.979975,0.980191,0.980435,0.980434,0.979588,0.980124,0.000318,7,0.948294,0.948868,0.949635,0.949641,0.947214,0.948730,0.000912,7,0.967706,0.968056,0.968470,0.968470,0.967069,0.967954,0.000527,7,0.937633,0.938310,0.939908,0.939968,0.936067,0.938377,0.001468,11,17.533306,2.038984,0.166966,0.007954
12,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,13,random,"{""classifier__C"": 0.1932075262142986, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.887813,0.888861,0.886296,0.939712,0.888316,0.898200,0.020774,10,0.925045,0.924674,0.929246,0.925796,0.923726,0.925697,0.001895,4,0.906047,0.906413,0.907263,0.932702,0.905675,0.911620,0.010554,8,0.981064,0.980978,0.982094,0.981516,0.980739,0.981278,0.000479,4,0.970779,0.971098,0.970195,0.985150,0.970964,0.973637,0.005765,10,0.975895,0.976013,0.976108,0.983330,0.975827,0.977435,0.002949,8,0.940971,0.941213,0.941685,0.958016,0.940751,0.944527,0.006752,8,0.961633,0.961814,0.962005,0.973279,0.961516,0.964049,0.004618,8,0.947912,0.947886,0.949721,0.955473,0.947345,0.949667,0.003012,4,13.535797,2.403072,0.110749,0.026058
3,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,4,random,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.887504,0.888417,0.886003,0.887348,0.887625,0.887379,0.000781,11,0.922179,0.920958,0.925318,0.923567,0.919851,0.922375,0.001924,5,0.904509,0.904395,0.905234,0.905095,0.903451,0.904537,0.000632,9,0.980354,0.980058,0.981119,0.980694,0.979778,0.980401,0.000471,5,0.970779,0.971085,0.970235,0.970686,0.970885,0.970734,0.000283,12,0.975543,0.975551,0.975647,0.975664,0.975311,0.975543,0.000126,10,0.940026,0.939973,0.940440,0.940380,0.939381,0.940040,0.000378,9,0.961060,0.961060,0.961251,0.961262,0.960678,0.961062,0.000211,10,0.946479,0.946021,0.947777,0.947126,0.945368,0.946554,0.000839,5,17.103702,2.361381,0.189335,0.012429
4,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,5,random,"{""classifier__C"": 0.015151125123102896, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.886840,0.888375,0.885503,0.887152,0.887428,0.887060,0.000932,13,0.918994,0.918463,0.922399,0.921762,0.917197,0.919763,0.001991,6,0.902630,0.903169,0.903575,0.904126,0.902067,0.903113,0.000717,10,0.979565,0.979443,0.980395,0.980247,0.979123,0.979755,0.000487,6,0.970687,0.971151,0.970182,0.970686,0.970911,0.970723,0.000321,13,0.975105,0.975280,0.975261,0.975443,0.975000,0.975218,0.000153,11,0.938868,0.939224,0.939418,0.939784,0.938534,0.939166,0.000433,10,0.960349,0.960614,0.960625,0.960901,0.960168,0.960531,0.000252,11,0.944840,0.944807,0.946290,0.946224,0.944054,0.945243,0.000875,7,16.417356,3.976225,0.177537,0.012136
5,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,6,random,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.887343,0.888969,0.885755,0.886706,0.887568,0.887268,0.001058,12,0.917773,0.917189,0.920170,0.919745,0.915552,0.918086,0.001698,7,0.902302,0.902858,0.902635,0.902923,0.901343,0.902412,0.000577,11,0.979267,0.979133,0.979846,0.979747,0.978719,0.979342,0.000413,7,0.970872,0.971363,0.970328,0.970619,0.971004,0.970837,0.000350,11,0.975052,0.975233,0.975063,0.975162,0.974846,0.975071,0.000131,12,0.938677,0.939046,0.938849,0.939042,0.938095,0.938742,0.000351,11,0.960253,0.960529,0.960296,0.960444,0.959913,0.960287,0.000212,12,0.944322,0.944276,0.945249,0.945182,0.943278,0.944462,0.000720,9,12.711648,2.650432,0.175740,0.014781
10,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,11,random,"{""classifier__C"": 0.014056787147388339, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.922513,0.921383,0.921651,0.944482,0.920922,0.926190,0.009161,6,0.875305,0.875358,0.878503,0.882219,0.874045,0.877086,0.002958,12,0.898289,0.897781,0.899560,0.912289,0.896871,0.900958,0.005732,12,0.969223,0.969226,0.969976,0.971031,0.968905,0.969672,0.000765,12,0.981621,0.981329,0.981329,0.987035,0.981236,0.982510,0.002266,5,0.975382,0.975240,0.975619,0.978967,0.975031,0.976048,0.001472,9,0.936836,0.936511,0.937589,0.945628,0.935951,0.938503,0.003602,12,0.960359,0.960136,0.960763,0.966071,0.959797,0.961425,0.002344,9,0.928463,0.928344,0.929916,0.934627,0.927640,0.929798,0.002525,12,15.140030,3.599473,0.169474,0.021416
9,linear_svm,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,10,random,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": true, ""classifier__intercept_scaling"": 1, ""classifier__loss"": ""squared_hinge"", ""classifier__max_iter"": 1000, ""classifier__multi_class"": ""ovr"", ""classifier__penalty"": ""l2"", ""classifier__random_state"": 1, ""classifier__tol"": 0.0001, ""classifier__verbose"": 0}",0.920545,0.919606,0.919178,0.922173,0.918957,0.920092,0.001174,9,0.871483,0.871961,0.874098,0.879246,0.869692,0.873296,0.003290,13,0.895342,0.895150,0.896071,0.900198,0.893646,0.896082,0.002204,13,0.968296,0.968402,0.968904,0.970157,0.967852,0.968722,0.000792,13,0.981196,0.980944,0.980785,0.981448,0.980824,0.981040,0.000250,9,0.974703,0.974633,0.974808,0.975770,0.974295,0.974842,0.000495,13,0.935023,0.934891,0.935440,0.937984,0.933971,0.935462,0.001349,13,0.959255,0.959149,0.959446,0.961007,0.958597,0.959491,0.000809,13,0.926340,0.926453,0.927441,0.930347,0.925258,0.927168,0.001734,13,14.705837,4.094565,0.172031,0.007899

modelo: mlp
 origem do treinamento: cicids2017
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: mlp - cicids2017

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
11,mlp,randomized_search,cicids2017,235490,12,13,5,1,12,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 1.9726066891840947e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.008237189558335287, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.979889,0.975417,0.979707,0.974167,0.977211,0.977278,0.002275,8,0.993205,0.994161,0.994268,0.992781,0.992357,0.993354,0.000752,1,0.986502,0.984700,0.986934,0.983386,0.984726,0.985249,0.001300,1,0.998296,0.998533,0.998561,0.998187,0.998082,0.998332,0.000189,1,0.994904,0.993737,0.994851,0.993418,0.994214,0.994225,0.000591,8,0.996597,0.996129,0.996703,0.995797,0.996144,0.996274,0.000333,1,0.991550,0.990414,0.991818,0.989591,0.990435,0.990762,0.000817,1,0.994565,0.993821,0.994734,0.993291,0.993843,0.994051,0.000530,1,0.994055,0.993949,0.994559,0.993100,0.993285,0.993790,0.000533,1,47.244975,8.098544,0.099604,0.016834
10,mlp,randomized_search,cicids2017,235490,12,13,5,1,11,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 1.3096774493777596e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.005705385668376793, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.978368,0.977513,0.979914,0.976895,0.974183,0.977374,0.001891,7,0.993948,0.992250,0.994374,0.991932,0.993418,0.993184,0.000948,2,0.986096,0.984826,0.987091,0.984356,0.983707,0.985215,0.001222,2,0.998481,0.998055,0.998588,0.997975,0.998346,0.998289,0.000238,2,0.994506,0.994294,0.994904,0.994135,0.993418,0.994251,0.000490,7,0.996490,0.996171,0.996743,0.996051,0.995876,0.996266,0.000311,2,0.991293,0.990499,0.991917,0.990204,0.989791,0.990741,0.000766,2,0.994395,0.993885,0.994798,0.993694,0.993418,0.994038,0.000496,2,0.994227,0.993272,0.994639,0.993033,0.993418,0.993718,0.000611,2,56.818434,10.225845,0.091948,0.019093
6,mlp,randomized_search,cicids2017,235490,12,13,5,1,7,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.001026603003516424, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0013103269001464436, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.977560,0.977901,0.978975,0.976574,0.976121,0.977426,0.001007,5,0.994373,0.991294,0.993524,0.991295,0.993737,0.992845,0.001296,3,0.985895,0.984552,0.986196,0.983879,0.984850,0.985074,0.000858,3,0.998587,0.997816,0.998375,0.997815,0.998427,0.998204,0.000325,3,0.994294,0.994400,0.994665,0.994055,0.993922,0.994267,0.000261,6,0.996436,0.996105,0.996517,0.995932,0.996169,0.996232,0.000216,3,0.991165,0.990329,0.991356,0.989906,0.990510,0.990653,0.000537,3,0.994310,0.993779,0.994437,0.993503,0.993885,0.993983,0.000345,3,0.994333,0.992847,0.994095,0.992675,0.993829,0.993556,0.000671,3,78.048342,20.476447,0.148913,0.007932
7,mlp,randomized_search,cicids2017,235490,12,13,5,1,8,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 2.6373077790924614e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.003994745694560914, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.978842,0.976859,0.977532,0.977801,0.976096,0.977426,0.000922,6,0.992144,0.990445,0.992994,0.991295,0.992675,0.991910,0.000932,4,0.985448,0.983605,0.985202,0.984502,0.984316,0.984614,0.000657,4,0.998029,0.997603,0.998241,0.997816,0.998161,0.997970,0.000233,4,0.994639,0.994135,0.994294,0.994373,0.993922,0.994273,0.000239,5,0.996331,0.995866,0.996264,0.996092,0.996037,0.996118,0.000166,4,0.990889,0.989735,0.990733,0.990297,0.990176,0.990366,0.000412,4,0.994140,0.993397,0.994034,0.993758,0.993673,0.993800,0.000265,4,0.993391,0.992290,0.993644,0.992834,0.993299,0.993092,0.000479,4,24.938260,8.530639,0.134849,0.006950
4,mlp,randomized_search,cicids2017,235490,12,13,5,1,5,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0004134759007834719, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.002346599645859086, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.979002,0.977282,0.979327,0.977843,0.975702,0.977831,0.001299,4,0.985030,0.991082,0.985669,0.988535,0.984713,0.987006,0.002445,5,0.982007,0.984134,0.982488,0.983160,0.980187,0.982395,0.001315,5,0.996252,0.997763,0.996411,0.997126,0.996169,0.996744,0.000611,5,0.994719,0.994241,0.994798,0.994400,0.993869,0.994405,0.000337,4,0.995485,0.995999,0.995604,0.995761,0.995018,0.995573,0.000327,5,0.988746,0.990066,0.989046,0.989460,0.987602,0.988984,0.000821,5,0.992781,0.993609,0.992972,0.993227,0.992038,0.992925,0.000523,5,0.989874,0.992661,0.990233,0.991467,0.989291,0.990706,0.001210,5,26.640262,5.314657,0.121859,0.011216
0,mlp,randomized_search,cicids2017,235490,12,13,5,1,1,baseline,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0001, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.001, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.978735,0.980524,0.979943,0.977031,0.973350,0.977916,0.002577,3,0.991931,0.978129,0.985456,0.984395,0.992569,0.986496,0.005328,6,0.985289,0.979325,0.982692,0.980699,0.982866,0.982174,0.002037,6,0.997976,0.994536,0.996359,0.996091,0.998133,0.996619,0.001328,6,0.994612,0.995143,0.994957,0.994214,0.993206,0.994427,0.000688,3,0.996291,0.994840,0.995658,0.995152,0.995663,0.995521,0.000497,6,0.990790,0.987082,0.989175,0.987925,0.989264,0.988847,0.001267,6,0.994076,0.991741,0.993057,0.992250,0.993078,0.992840,0.000799,6,0.993272,0.986636,0.990207,0.989305,0.992887,0.990461,0.002442,6,77.419439,6.608548,0.115711,0.006750
3,mlp,randomized_search,cicids2017,235490,12,13,5,1,4,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 3.620600725744737e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0006216342697722397, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.979695,0.976938,0.979700,0.978726,0.976286,0.978269,0.001414,2,0.983544,0.984924,0.983652,0.981635,0.983333,0.983418,0.001051,7,0.981616,0.980915,0.981672,0.980178,0.979797,0.980835,0.000752,7,0.995882,0.996224,0.995909,0.995405,0.995826,0.995849,0.000262,7,0.994904,0.994188,0.994904,0.994665,0.994028,0.994538,0.000365,2,0.995393,0.995205,0.995406,0.995035,0.994926,0.995193,0.000191,7,0.988504,0.988060,0.988539,0.987607,0.987362,0.988014,0.000471,7,0.992632,0.992335,0.992654,0.992059,0.991889,0.992314,0.000304,7,0.989224,0.989556,0.989278,0.988150,0.988681,0.988978,0.000502,7,59.465513,7.898876,0.101073,0.005394
8,mlp,randomized_search,cicids2017,235490,12,13,5,1,9,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.008031279258119075, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0024246286430387822, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.978201,0.978238,0.980207,0.978848,0.976715,0.978442,0.001128,1,0.986198,0.983119,0.983121,0.977601,0.979618,0.981931,0.003005,8,0.982183,0.980672,0.981662,0.978224,0.978164,0.980181,0.001694,8,0.996543,0.995775,0.995777,0.994402,0.994900,0.995479,0.000749,8,0.994506,0.994533,0.995037,0.994718,0.994161,0.994591,0.000287,1,0.995523,0.995153,0.995407,0.994560,0.994531,0.995035,0.000417,8,0.988853,0.987913,0.988534,0.986392,0.986347,0.987608,0.001055,8,0.992845,0.992250,0.992654,0.991295,0.991252,0.992059,0.000670,8,0.990352,0.988826,0.989079,0.986160,0.986889,0.988261,0.001527,8,46.744548,3.037284,0.123433,0.007896
2,mlp,randomized_search,cicids2017,235490,12,13,5,1,3,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 8.072307884499753e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0001529949829431265, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.977015,0.975729,0.978025,0.976932,0.974288,0.976398,0.001282,9,0.979297,0.977386,0.978025,0.975584,0.977495,0.977557,0.001198,11,0.978155,0.976557,0.978025,0.976258,0.975889,0.976977,0.000934,9,0.994822,0.994345,0.994506,0.993898,0.994369,0.994388,0.000298,11,0.994241,0.993922,0.994506,0.994241,0.993551,0.994092,0.000328,9,0.994531,0.994133,0.994506,0.994069,0.993960,0.994240,0.000234,9,0.986343,0.985345,0.986266,0.985163,0.984924,0.985608,0.000584,9,0.991252,0.990615,0.991210,0.990509,0.990339,0.990785,0.000375,9,0.986769,0.985654,0.986266,0.984912,0.985523,0.985825,0.000639,11,45.122414,4.591545,0.101121,0.014410
12,mlp,randomized_search,cicids2017,235490,12,13,5,1,13,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0003976453011700043, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0004275936647080326, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.976017,0.974340,0.975455,0.975090,0.973676,0.974916,0.000825,13,0.980784,0.979616,0.978769,0.976539,0.977707,0.978683,0.001472,9,0.978394,0.976971,0.977109,0.975814,0.975687,0.976795,0.000988,10,0.995190,0.994897,0.994687,0.994132,0.994421,0.994666,0.000367,9,0.993975,0.993551,0.993843,0.993763,0.993391,0.993705,0.000209,13,0.994583,0.994224,0.994265,0.993948,0.993906,0.994185,0.000245,10,0.986488,0.985597,0.985687,0.984881,0.984797,0.985490,0.000616,10,0.991337,0.990764,0.990828,0.990318,0.990254,0.990700,0.000393,10,0.987379,0.986583,0.986306,0.985151,0.985549,0.986194,0.000784,9,14.835093,5.458024,0.085517,0.017880
9,mlp,randomized_search,cicids2017,235490,12,13,5,1,10,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.004257625486011381, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.00014794095665996457, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.974551,0.975757,0.976082,0.974997,0.973250,0.974928,0.000998,12,0.979828,0.978554,0.979087,0.976964,0.977176,0.978322,0.001101,10,0.977182,0.977153,0.977582,0.975980,0.975209,0.976621,0.000886,11,0.994951,0.994635,0.994767,0.994238,0.994288,0.994576,0.000275,10,0.993604,0.993922,0.994002,0.993736,0.993285,0.993710,0.000254,12,0.994277,0.994279,0.994384,0.993987,0.993786,0.994143,0.000222,11,0.985730,0.985716,0.985983,0.984983,0.984498,0.985382,0.000554,11,0.990849,0.990849,0.991019,0.990382,0.990063,0.990632,0.000355,11,0.986716,0.986238,0.986544,0.985350,0.985231,0.986016,0.000613,10,27.222783,4.293574,0.118644,0.004685

modelo: mlp
 origem do treinamento: unsw_nb15
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: mlp - unsw_nb15

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
0,mlp,randomized_search,unsw_nb15,235490,12,13,5,1,1,baseline,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0001, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.001, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.941064,0.941141,0.939188,0.938790,0.938649,0.939766,0.001106,1,0.996815,0.996496,0.996815,0.994798,0.997240,0.996433,0.000851,1,0.968138,0.968028,0.967144,0.965983,0.967058,0.967270,0.000780,1,0.999192,0.999111,0.999191,0.998680,0.999299,0.999095,0.000216,1,0.984394,0.984421,0.983863,0.983784,0.983704,0.984033,0.000310,6,0.991738,0.991712,0.991468,0.991176,0.991440,0.991507,0.000205,1,0.979938,0.979870,0.979306,0.978579,0.979249,0.979388,0.000493,1,0.986878,0.986836,0.986454,0.985987,0.986411,0.986513,0.000325,1,0.990605,0.990459,0.990339,0.989291,0.990472,0.990233,0.000479,1,86.330628,5.330978,0.113881,0.012391
6,mlp,randomized_search,unsw_nb15,235490,12,13,5,1,7,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.001026603003516424, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0013103269001464436, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.942312,0.942038,0.938194,0.936130,0.940054,0.939745,0.002342,2,0.995435,0.997346,0.995860,0.997346,0.993843,0.995966,0.001312,3,0.968145,0.968903,0.966167,0.965769,0.966201,0.967037,0.001247,2,0.998842,0.999327,0.998949,0.999325,0.998438,0.998976,0.000332,3,0.984766,0.984660,0.983598,0.982987,0.984155,0.984033,0.000668,7,0.991754,0.991939,0.991214,0.991089,0.991245,0.991448,0.000335,2,0.979950,0.980421,0.978691,0.978429,0.978723,0.979243,0.000791,2,0.986900,0.987197,0.986050,0.985859,0.986093,0.986420,0.000528,2,0.990100,0.991003,0.989729,0.990167,0.988999,0.990000,0.000651,3,61.509222,12.687417,0.153494,0.015015
3,mlp,randomized_search,unsw_nb15,235490,12,13,5,1,4,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 3.620600725744737e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0006216342697722397, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.942963,0.942636,0.938220,0.937775,0.936976,0.939714,0.002553,3,0.995222,0.996178,0.994692,0.995117,0.997452,0.995732,0.000988,4,0.968388,0.968668,0.965631,0.965595,0.966269,0.966910,0.001345,3,0.998789,0.999031,0.998653,0.998760,0.999353,0.998917,0.000250,4,0.984952,0.984846,0.983624,0.983492,0.983226,0.984028,0.000723,8,0.991822,0.991888,0.991082,0.991067,0.991224,0.991416,0.000363,3,0.980105,0.980278,0.978356,0.978331,0.978746,0.979163,0.000854,3,0.987006,0.987112,0.985838,0.985817,0.986072,0.986369,0.000571,3,0.990087,0.990512,0.989158,0.989304,0.990339,0.989880,0.000549,4,95.917158,2.402377,0.109469,0.009232
7,mlp,randomized_search,unsw_nb15,235490,12,13,5,1,8,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 2.6373077790924614e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.003994745694560914, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.941465,0.941265,0.937338,0.937406,0.936625,0.938820,0.002097,6,0.997240,0.997027,0.995648,0.996815,0.994692,0.996284,0.000968,2,0.968550,0.968344,0.965613,0.966198,0.964786,0.966698,0.001498,4,0.999300,0.999246,0.998895,0.999191,0.998652,0.999057,0.000246,2,0.984501,0.984448,0.983359,0.983359,0.983173,0.983768,0.000581,11,0.991845,0.991791,0.991066,0.991212,0.990852,0.991353,0.000397,4,0.980198,0.980068,0.978340,0.978705,0.977819,0.979026,0.000948,4,0.987048,0.986963,0.985817,0.986050,0.985477,0.986271,0.000628,4,0.990870,0.990737,0.989503,0.990087,0.988933,0.990026,0.000734,2,22.966211,6.498265,0.129358,0.009458
8,mlp,randomized_search,unsw_nb15,235490,12,13,5,1,9,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.008031279258119075, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0024246286430387822, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.940357,0.941123,0.937369,0.936026,0.938169,0.938609,0.001886,8,0.995966,0.996178,0.994586,0.994055,0.995435,0.995244,0.000809,6,0.967363,0.967868,0.965130,0.964168,0.965954,0.966097,0.001372,5,0.998976,0.999030,0.998625,0.998490,0.998841,0.998793,0.000206,6,0.984209,0.984421,0.983386,0.983014,0.983598,0.983725,0.000521,12,0.991538,0.991672,0.990947,0.990692,0.991161,0.991202,0.000363,5,0.979450,0.979770,0.978038,0.977430,0.978558,0.978649,0.000868,5,0.986560,0.986772,0.985626,0.985222,0.985965,0.986029,0.000575,5,0.990087,0.990299,0.988986,0.988535,0.989517,0.989485,0.000660,5,74.703325,3.822540,0.117420,0.010852
4,mlp,randomized_search,unsw_nb15,235490,12,13,5,1,5,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0004134759007834719, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.002346599645859086, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.943137,0.941602,0.938213,0.936824,0.938790,0.939713,0.002313,4,0.991400,0.994585,0.994586,0.993312,0.994798,0.993736,0.001281,7,0.966667,0.967369,0.965578,0.964242,0.965983,0.965968,0.001057,6,0.997822,0.998627,0.998626,0.998302,0.998680,0.998411,0.000324,7,0.985058,0.984580,0.983624,0.983253,0.983784,0.984060,0.000661,5,0.991399,0.991554,0.991068,0.990720,0.991176,0.991184,0.000287,6,0.979033,0.979461,0.978323,0.977481,0.978579,0.978576,0.000672,6,0.986326,0.986581,0.985817,0.985265,0.985987,0.985995,0.000451,6,0.988229,0.989583,0.989105,0.988282,0.989291,0.988898,0.000546,7,24.734778,1.793697,0.126456,0.023300
11,mlp,randomized_search,unsw_nb15,235490,12,13,5,1,12,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 1.9726066891840947e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.008237189558335287, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.940958,0.938867,0.935513,0.933021,0.938505,0.937373,0.002784,9,0.996603,0.997877,0.996391,0.995223,0.991507,0.995520,0.002176,5,0.967981,0.967473,0.964993,0.963119,0.964278,0.965569,0.001868,7,0.999138,0.999461,0.999083,0.998785,0.997846,0.998863,0.000552,5,0.984368,0.983758,0.982828,0.982138,0.983757,0.983370,0.000788,13,0.991698,0.991547,0.990889,0.990392,0.990752,0.991055,0.000493,7,0.979840,0.979510,0.977941,0.976755,0.977515,0.978312,0.001180,7,0.986815,0.986581,0.985541,0.984755,0.985307,0.985800,0.000780,7,0.990485,0.990817,0.989609,0.988681,0.987632,0.989445,0.001172,6,30.035092,8.533809,0.102568,0.007355
12,mlp,randomized_search,unsw_nb15,235490,12,13,5,1,13,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0003976453011700043, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0004275936647080326, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.941899,0.940337,0.937099,0.937807,0.936503,0.938729,0.002054,7,0.993099,0.993948,0.991614,0.992463,0.991083,0.992441,0.001023,8,0.966822,0.966400,0.963586,0.964361,0.963020,0.964838,0.001515,8,0.998251,0.998465,0.997872,0.998088,0.997738,0.998083,0.000260,8,0.984686,0.984235,0.983359,0.983545,0.983200,0.983805,0.000565,10,0.991422,0.991299,0.990563,0.990763,0.990415,0.990892,0.000400,8,0.979122,0.978850,0.977074,0.977562,0.976718,0.977865,0.000957,8,0.986369,0.986178,0.985010,0.985328,0.984776,0.985532,0.000633,8,0.988893,0.989092,0.987486,0.988004,0.987141,0.988123,0.000763,8,41.439915,3.827323,0.073686,0.010165
10,mlp,randomized_search,unsw_nb15,235490,12,13,5,1,11,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 1.3096774493777596e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.005705385668376793, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.936976,0.940623,0.937344,0.941279,0.938757,0.938996,0.001716,5,0.997558,0.997346,0.995754,0.862739,0.990977,0.968875,0.053121,9,0.966319,0.968154,0.965666,0.900299,0.964160,0.952920,0.026342,9,0.999380,0.999326,0.998922,0.966384,0.997712,0.992345,0.012994,9,0.983227,0.984262,0.983359,0.986544,0.983837,0.984246,0.001206,4,0.991237,0.991737,0.991079,0.976360,0.990726,0.988228,0.005943,9,0.978778,0.979946,0.978373,0.938330,0.977443,0.970574,0.016142,9,0.986093,0.986878,0.985838,0.961782,0.985265,0.981171,0.009709,9,0.990392,0.990804,0.989556,0.924641,0.987407,0.976560,0.025986,9,25.676539,11.140156,0.119128,0.003319
2,mlp,randomized_search,unsw_nb15,235490,12,13,5,1,3,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 8.072307884499753e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0001529949829431265, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.937069,0.935927,0.933817,0.933008,0.931912,0.934346,0.001893,13,0.909014,0.919631,0.915180,0.912208,0.909554,0.913117,0.003925,10,0.922828,0.927707,0.924405,0.922491,0.920597,0.923606,0.002381,10,0.977424,0.979996,0.978899,0.978173,0.977522,0.978403,0.000956,10,0.984740,0.984262,0.983784,0.983624,0.983386,0.983959,0.000484,9,0.981068,0.982124,0.981335,0.980891,0.980445,0.981173,0.000557,10,0.951948,0.954916,0.952870,0.951691,0.950521,0.952389,0.001469,10,0.969595,0.971336,0.970062,0.969341,0.968619,0.969791,0.000903,10,0.946877,0.951946,0.949482,0.947916,0.946470,0.948538,0.001997,10,96.914022,3.998800,0.099665,0.007211
9,mlp,randomized_search,unsw_nb15,235490,12,13,5,1,10,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.004257625486011381, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.00014794095665996457, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.937175,0.937898,0.934817,0.937263,0.935361,0.936503,0.001193,10,0.861556,0.861026,0.869321,0.864331,0.861783,0.863603,0.003078,11,0.897776,0.897819,0.900880,0.899321,0.897066,0.898572,0.001368,11,0.966076,0.965957,0.967891,0.966728,0.966111,0.966552,0.000721,11,0.985562,0.985748,0.984845,0.985535,0.985111,0.985360,0.000331,1,0.975722,0.975752,0.976294,0.976041,0.975518,0.975866,0.000272,11,0.936749,0.936786,0.938587,0.937681,0.936292,0.937219,0.000819,11,0.960763,0.960805,0.961739,0.961293,0.960444,0.961009,0.000455,11,0.923559,0.923387,0.927083,0.924933,0.923447,0.924482,0.001421,11,42.044676,10.948670,0.125669,0.011539

modelo: mlp
 origem do treinamento: iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: mlp - iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
11,mlp,randomized_search,iot23,235490,12,13,5,1,12,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 1.9726066891840947e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.008237189558335287, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",1.000000,0.999143,0.999358,0.999573,0.999893,0.999593,0.000320,3,0.992568,0.990551,0.991932,0.992887,0.993737,0.992335,0.001065,1,0.996270,0.994829,0.995631,0.996219,0.996805,0.995951,0.000673,1,0.998146,0.997643,0.997987,0.998225,0.998437,0.998087,0.000265,1,1.000000,0.999788,0.999841,0.999894,0.999973,0.999899,0.000079,3,0.999072,0.998714,0.998913,0.999059,0.999204,0.998992,0.000167,1,0.997671,0.996771,0.997272,0.997639,0.998005,0.997472,0.000420,1,0.998514,0.997940,0.998259,0.998493,0.998726,0.998386,0.000268,1,0.996284,0.995169,0.995886,0.996391,0.996855,0.996117,0.000565,1,29.021207,4.261936,0.097874,0.016870
10,mlp,randomized_search,iot23,235490,12,13,5,1,11,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 1.3096774493777596e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.005705385668376793, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.999573,0.999678,0.998078,0.999786,0.999893,0.999402,0.000670,7,0.993311,0.989808,0.992357,0.991295,0.991826,0.991719,0.001165,2,0.996432,0.994719,0.995209,0.995522,0.995843,0.995545,0.000578,2,0.998331,0.997458,0.998092,0.997828,0.997960,0.997934,0.000290,2,0.999894,0.999920,0.999522,0.999947,0.999973,0.999851,0.000167,7,0.999112,0.998688,0.998807,0.998886,0.998966,0.998892,0.000143,2,0.997772,0.996703,0.997008,0.997204,0.997405,0.997218,0.000361,2,0.998577,0.997898,0.998089,0.998216,0.998344,0.998225,0.000230,2,0.996603,0.994864,0.995939,0.995621,0.995900,0.995785,0.000562,2,35.517457,4.078349,0.122263,0.016368
6,mlp,randomized_search,iot23,235490,12,13,5,1,7,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.001026603003516424, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0013103269001464436, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.999466,0.999785,0.999571,0.998827,0.999679,0.999466,0.000337,6,0.994267,0.987791,0.989809,0.994374,0.991826,0.991613,0.002552,3,0.996860,0.993752,0.994666,0.996595,0.995737,0.995522,0.001171,3,0.998569,0.996957,0.997458,0.998595,0.997960,0.997908,0.000635,3,0.999867,0.999947,0.999894,0.999708,0.999920,0.999867,0.000084,6,0.999218,0.998450,0.998675,0.999151,0.998939,0.998886,0.000289,3,0.998039,0.996101,0.996670,0.997873,0.997338,0.997204,0.000730,3,0.998747,0.997516,0.997877,0.998641,0.998301,0.998216,0.000464,3,0.997067,0.993869,0.994851,0.997041,0.995873,0.995740,0.001246,3,54.573810,19.262580,0.141481,0.007996
3,mlp,randomized_search,iot23,235490,12,13,5,1,4,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 3.620600725744737e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0006216342697722397, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.999786,0.999893,0.999357,1.000000,0.999679,0.999743,0.000221,1,0.992887,0.989489,0.989703,0.991932,0.991720,0.991146,0.001327,5,0.996325,0.994664,0.994506,0.995950,0.995683,0.995426,0.000718,4,0.998225,0.997379,0.997432,0.997987,0.997934,0.997791,0.000330,5,0.999947,0.999973,0.999841,1.000000,0.999920,0.999936,0.000055,1,0.999085,0.998675,0.998635,0.998992,0.998926,0.998863,0.000178,4,0.997705,0.996669,0.996571,0.997471,0.997305,0.997144,0.000448,4,0.998535,0.997877,0.997813,0.998386,0.998280,0.998178,0.000285,4,0.996417,0.994731,0.994772,0.995966,0.995820,0.995541,0.000674,5,11.404200,1.930655,0.099392,0.003861
0,mlp,randomized_search,iot23,235490,12,13,5,1,1,baseline,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0001, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.001, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.999573,0.999893,0.999464,1.000000,0.998077,0.999401,0.000691,8,0.992993,0.989808,0.989915,0.992038,0.991826,0.991316,0.001251,4,0.996272,0.994825,0.994667,0.996003,0.994942,0.995342,0.000661,5,0.998251,0.997459,0.997485,0.998013,0.997960,0.997833,0.000311,4,0.999894,0.999973,0.999867,1.000000,0.999522,0.999851,0.000172,8,0.999072,0.998714,0.998675,0.999006,0.998740,0.998841,0.000164,5,0.997672,0.996770,0.996671,0.997504,0.996841,0.997091,0.000413,5,0.998514,0.997940,0.997877,0.998408,0.997983,0.998144,0.000263,5,0.996443,0.994891,0.994891,0.996019,0.995674,0.995584,0.000616,4,19.640934,2.817700,0.111876,0.002086
8,mlp,randomized_search,iot23,235490,12,13,5,1,9,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.008031279258119075, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0024246286430387822, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.999572,1.000000,0.999678,0.999572,0.999572,0.999679,0.000166,2,0.992568,0.989702,0.989172,0.991932,0.991720,0.991019,0.001332,8,0.996058,0.994824,0.994397,0.995737,0.995630,0.995329,0.000618,6,0.998145,0.997432,0.997300,0.997987,0.997934,0.997760,0.000331,8,0.999894,1.000000,0.999920,0.999894,0.999894,0.999920,0.000041,2,0.999019,0.998714,0.998608,0.998939,0.998913,0.998839,0.000153,6,0.997538,0.996769,0.996503,0.997338,0.997272,0.997084,0.000386,6,0.998429,0.997940,0.997771,0.998301,0.998259,0.998140,0.000245,6,0.996231,0.994851,0.994546,0.995913,0.995807,0.995470,0.000652,8,19.700699,3.319231,0.126196,0.009666
4,mlp,randomized_search,iot23,235490,12,13,5,1,5,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0004134759007834719, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.002346599645859086, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.999679,0.999785,0.999250,0.999358,0.999358,0.999486,0.000208,5,0.992568,0.989595,0.989703,0.992038,0.991720,0.991125,0.001236,6,0.996111,0.994664,0.994453,0.995685,0.995524,0.995288,0.000629,7,0.998145,0.997406,0.997432,0.998013,0.997934,0.997786,0.000308,6,0.999920,0.999947,0.999814,0.999841,0.999841,0.999873,0.000051,5,0.999032,0.998675,0.998622,0.998926,0.998886,0.998828,0.000155,7,0.997572,0.996670,0.996537,0.997305,0.997205,0.997058,0.000392,7,0.998450,0.997877,0.997792,0.998280,0.998216,0.998123,0.000249,7,0.996244,0.994771,0.994758,0.995939,0.995780,0.995499,0.000618,6,9.338057,1.312061,0.112519,0.006234
7,mlp,randomized_search,iot23,235490,12,13,5,1,8,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 2.6373077790924614e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.003994745694560914, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.999359,0.999678,0.999571,0.999144,0.999679,0.999486,0.000207,4,0.992887,0.989171,0.989809,0.991826,0.991720,0.991082,0.001378,7,0.996112,0.994397,0.994666,0.995472,0.995683,0.995266,0.000640,8,0.998225,0.997300,0.997458,0.997960,0.997934,0.997775,0.000343,7,0.999841,0.999920,0.999894,0.999788,0.999920,0.999873,0.000051,4,0.999032,0.998608,0.998675,0.998873,0.998926,0.998823,0.000158,8,0.997572,0.996503,0.996670,0.997172,0.997305,0.997044,0.000399,8,0.998450,0.997771,0.997877,0.998195,0.998280,0.998115,0.000254,8,0.996364,0.994546,0.994851,0.995807,0.995820,0.995478,0.000674,7,11.419225,0.832300,0.130515,0.006472
12,mlp,randomized_search,iot23,235490,12,13,5,1,13,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0003976453011700043, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0004275936647080326, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.999679,0.999893,0.999035,0.999144,0.999251,0.999401,0.000329,9,0.992356,0.989595,0.989490,0.991507,0.991720,0.990934,0.001170,10,0.996004,0.994717,0.994240,0.995311,0.995471,0.995149,0.000612,9,0.998093,0.997406,0.997379,0.997881,0.997934,0.997738,0.000291,10,0.999920,0.999973,0.999761,0.999788,0.999814,0.999851,0.000082,9,0.999006,0.998688,0.998569,0.998833,0.998873,0.998794,0.000151,9,0.997505,0.996703,0.996404,0.997072,0.997172,0.996971,0.000382,9,0.998408,0.997898,0.997707,0.998132,0.998195,0.998068,0.000243,9,0.996138,0.994784,0.994626,0.995648,0.995767,0.995393,0.000586,10,9.581503,0.981383,0.081416,0.006624
2,mlp,randomized_search,iot23,235490,12,13,5,1,3,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 8.072307884499753e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0001529949829431265, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.999145,0.999893,0.998821,0.999037,0.998931,0.999165,0.000379,10,0.992674,0.989489,0.989490,0.991614,0.991720,0.990997,0.001285,9,0.995899,0.994664,0.994134,0.995312,0.995312,0.995064,0.000608,10,0.998172,0.997379,0.997379,0.997907,0.997934,0.997754,0.000320,9,0.999788,0.999973,0.999708,0.999761,0.999735,0.999793,0.000094,10,0.998979,0.998675,0.998542,0.998833,0.998833,0.998772,0.000150,10,0.997439,0.996669,0.996338,0.997072,0.997073,0.996918,0.000379,10,0.998365,0.997877,0.997664,0.998132,0.998132,0.998034,0.000241,10,0.996231,0.994731,0.994599,0.995687,0.995727,0.995395,0.000627,9,17.914049,1.538857,0.110114,0.014621
9,mlp,randomized_search,iot23,235490,12,13,5,1,10,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.004257625486011381, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.00014794095665996457, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.999358,0.999678,0.995407,0.999251,0.998397,0.998418,0.001564,11,0.992250,0.989489,0.989384,0.991507,0.991720,0.990870,0.001195,11,0.995791,0.994558,0.992387,0.995364,0.995047,0.994629,0.001192,11,0.998066,0.997379,0.997350,0.997881,0.997933,0.997722,0.000298,11,0.999841,0.999920,0.998859,0.999814,0.999602,0.999607,0.000389,11,0.998953,0.998648,0.998104,0.998847,0.998767,0.998664,0.000297,11,0.997372,0.996603,0.995245,0.997105,0.996907,0.996647,0.000744,11,0.998323,0.997834,0.996964,0.998153,0.998025,0.997860,0.000476,11,0.996045,0.994705,0.994122,0.995661,0.995661,0.995239,0.000713,11,17.883385,3.482948,0.120848,0.006115

modelo: mlp
 origem do treinamento: cicids2017_unsw_nb15
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: mlp - cicids2017_unsw_nb15

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
6,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,7,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.001026603003516424, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0013103269001464436, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.940433,0.956889,0.954601,0.943949,0.945025,0.948180,0.006402,11,0.991453,0.985030,0.988854,0.994904,0.988163,0.989681,0.003318,1,0.965270,0.970756,0.971426,0.968757,0.966113,0.968464,0.002443,1,0.997834,0.996230,0.997188,0.998709,0.997007,0.997393,0.000833,1,0.984302,0.988906,0.988242,0.985230,0.985628,0.986462,0.001790,12,0.991022,0.992555,0.992695,0.991924,0.991285,0.991896,0.000665,1,0.978146,0.981655,0.982060,0.980340,0.978699,0.980180,0.001554,1,0.985732,0.988131,0.988365,0.987165,0.986135,0.987106,0.001046,1,0.987878,0.986968,0.988548,0.990067,0.986896,0.988071,0.001170,1,243.018914,62.308041,0.281958,0.032969
7,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,8,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 2.6373077790924614e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.003994745694560914, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.952743,0.944906,0.953901,0.949202,0.943019,0.948754,0.004250,10,0.985667,0.985083,0.992887,0.987845,0.989119,0.988120,0.002794,2,0.968925,0.964576,0.973004,0.968138,0.965519,0.968032,0.002959,2,0.996386,0.996231,0.998203,0.996930,0.997246,0.996999,0.000705,2,0.987778,0.985642,0.988004,0.986783,0.985058,0.986653,0.001155,10,0.992063,0.990908,0.993077,0.991830,0.991114,0.991799,0.000770,2,0.980494,0.977742,0.983041,0.979984,0.978317,0.979916,0.001865,2,0.987356,0.985530,0.988980,0.986995,0.985870,0.986946,0.001222,2,0.986723,0.985363,0.990446,0.987314,0.987088,0.987387,0.001673,2,55.592604,9.046707,0.247098,0.012667
10,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,11,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 1.3096774493777596e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.005705385668376793, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.949939,0.956980,0.946701,0.954667,0.937600,0.949177,0.006808,9,0.988162,0.969477,0.990870,0.989225,0.993737,0.986294,0.008617,3,0.968674,0.963188,0.968282,0.971639,0.964853,0.967327,0.002986,3,0.997011,0.992345,0.997691,0.997282,0.998410,0.996548,0.002154,3,0.986982,0.989105,0.986053,0.988256,0.983465,0.986772,0.001957,9,0.991971,0.990722,0.991838,0.992748,0.990881,0.991632,0.000747,3,0.980322,0.976955,0.980060,0.982193,0.977867,0.979480,0.001865,3,0.987218,0.985180,0.987016,0.988450,0.985520,0.986677,0.001194,3,0.987572,0.979291,0.988462,0.988740,0.988601,0.986533,0.003644,3,93.854269,14.591789,0.210500,0.028469
0,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,1,baseline,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0001, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.001, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.952488,0.943127,0.953406,0.952719,0.944509,0.949250,0.004467,8,0.988640,0.985933,0.973142,0.990393,0.986571,0.984936,0.006103,5,0.970227,0.964055,0.963173,0.971191,0.965082,0.966746,0.003306,4,0.997133,0.996443,0.993250,0.997574,0.996605,0.996201,0.001529,5,0.987672,0.985138,0.988110,0.987712,0.985509,0.986828,0.001244,8,0.992380,0.990758,0.990673,0.992618,0.991026,0.991491,0.000835,4,0.981304,0.977407,0.976923,0.981905,0.978054,0.979118,0.002070,4,0.987866,0.985297,0.985116,0.988248,0.985721,0.986450,0.001332,4,0.988156,0.985535,0.980626,0.989052,0.986040,0.985882,0.002932,4,220.659481,5.757277,0.196357,0.010487
11,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,12,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 1.9726066891840947e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.008237189558335287, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.951667,0.938319,0.944736,0.943986,0.938212,0.943384,0.004964,13,0.971016,0.991666,0.993577,0.977707,0.992941,0.985381,0.009264,4,0.961244,0.964255,0.968541,0.960551,0.964801,0.963878,0.002855,5,0.992718,0.997887,0.998373,0.994376,0.998209,0.996313,0.002324,4,0.987672,0.983704,0.985469,0.985496,0.983651,0.985198,0.001477,13,0.990188,0.990745,0.991879,0.989916,0.990876,0.990721,0.000678,5,0.975716,0.977500,0.980210,0.975233,0.977838,0.977300,0.001765,5,0.984341,0.985297,0.987091,0.983938,0.985509,0.985235,0.001096,5,0.979344,0.987685,0.989523,0.981601,0.988296,0.985290,0.004041,5,81.117312,14.544687,0.193991,0.019341
4,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,5,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0004134759007834719, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.002346599645859086, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.949902,0.940529,0.946402,0.951740,0.948110,0.947337,0.003841,12,0.979350,0.984765,0.985032,0.982909,0.935881,0.973587,0.018962,6,0.964401,0.962139,0.965331,0.967073,0.941956,0.960180,0.009250,6,0.994798,0.996146,0.996219,0.995692,0.984021,0.993375,0.004704,6,0.987088,0.984434,0.986053,0.987539,0.987194,0.986462,0.001128,11,0.990928,0.990256,0.991110,0.991599,0.985605,0.989899,0.002190,6,0.977665,0.976197,0.978220,0.979336,0.963780,0.975040,0.005720,6,0.985541,0.984500,0.985849,0.986613,0.976931,0.983887,0.003543,6,0.983219,0.984600,0.985542,0.985224,0.961538,0.980025,0.009278,6,43.588439,11.481698,0.206701,0.015109
3,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,4,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 3.620600725744737e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0006216342697722397, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.950203,0.953315,0.957195,0.954560,0.956293,0.954313,0.002457,1,0.979510,0.928973,0.931741,0.967834,0.956953,0.953002,0.019838,7,0.964634,0.940987,0.944297,0.961151,0.956623,0.953538,0.009312,7,0.994838,0.982357,0.983047,0.991930,0.989236,0.988282,0.004893,7,0.987168,0.988628,0.989583,0.988481,0.989065,0.988585,0.000806,6,0.990988,0.985483,0.986304,0.990203,0.989151,0.988426,0.002164,7,0.977811,0.963235,0.965300,0.975677,0.972887,0.970982,0.005738,7,0.985636,0.976698,0.978014,0.984352,0.982643,0.981468,0.003515,7,0.983339,0.958800,0.960662,0.978158,0.973009,0.970794,0.009623,7,195.170338,7.084801,0.186245,0.018024
8,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,9,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.008031279258119075, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0024246286430387822, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.952210,0.952279,0.957536,0.956881,0.949820,0.953745,0.002970,3,0.929717,0.924780,0.929989,0.909342,0.926327,0.924031,0.007608,8,0.940829,0.938328,0.943562,0.932506,0.937927,0.938630,0.003667,8,0.982534,0.981331,0.982621,0.977612,0.981694,0.981159,0.001840,8,0.988336,0.988415,0.989689,0.989755,0.987765,0.988792,0.000792,4,0.985426,0.984861,0.986143,0.983646,0.984720,0.984959,0.000826,8,0.963128,0.961594,0.964852,0.958076,0.961323,0.961795,0.002246,8,0.976613,0.975689,0.977749,0.973672,0.975477,0.975840,0.001349,8,0.959026,0.956597,0.959839,0.949549,0.957046,0.956411,0.003637,8,140.557282,17.314731,0.216172,0.008635
2,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,3,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 8.072307884499753e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0001529949829431265, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.952501,0.956163,0.956994,0.952871,0.952897,0.954285,0.001896,2,0.922922,0.915862,0.921285,0.913270,0.919161,0.918500,0.003523,10,0.937478,0.935578,0.938800,0.932650,0.935725,0.936046,0.002073,10,0.980880,0.979186,0.980502,0.978539,0.979967,0.979815,0.000855,10,0.988495,0.989503,0.989649,0.988707,0.988641,0.988999,0.000479,1,0.984673,0.984318,0.985054,0.983597,0.984284,0.984385,0.000483,9,0.961076,0.959948,0.961927,0.958124,0.960005,0.960216,0.001278,9,0.975381,0.974776,0.975976,0.973619,0.974744,0.974899,0.000784,9,0.955708,0.952682,0.955467,0.950988,0.953901,0.953749,0.001765,10,197.421472,9.281024,0.168820,0.011783
12,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,13,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0003976453011700043, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0004275936647080326, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.953000,0.955281,0.956829,0.951814,0.950943,0.953573,0.002184,4,0.922444,0.915118,0.921125,0.916348,0.920860,0.919179,0.002891,9,0.937473,0.934768,0.938638,0.933744,0.935660,0.936057,0.001779,9,0.980767,0.979002,0.980463,0.979279,0.980369,0.979976,0.000700,9,0.988628,0.989291,0.989609,0.988402,0.988123,0.988811,0.000555,3,0.984681,0.984120,0.985015,0.983819,0.984231,0.984373,0.000424,10,0.961077,0.959444,0.961826,0.958782,0.959945,0.960215,0.001101,10,0.975392,0.974458,0.975912,0.973990,0.974670,0.974884,0.000684,10,0.955536,0.952205,0.955367,0.952375,0.954491,0.953995,0.001438,9,58.918859,7.235300,0.126761,0.018587
5,mlp,randomized_search,cicids2017_unsw_nb15,470980,12,13,5,1,6,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 4.105412016858889e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.00011344234265835253, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.950256,0.954904,0.956495,0.951247,0.950369,0.952654,0.002560,6,0.917720,0.911615,0.906741,0.903079,0.908652,0.909561,0.004931,11,0.933704,0.932758,0.930954,0.926537,0.929042,0.930599,0.002583,11,0.979606,0.978153,0.976983,0.976071,0.977410,0.977645,0.001189,11,0.987991,0.989238,0.989689,0.988428,0.988136,0.988696,0.000658,5,0.983780,0.983664,0.983295,0.982211,0.982744,0.983139,0.000588,11,0.958742,0.958211,0.957124,0.954374,0.955893,0.956869,0.001584,11,0.973937,0.973714,0.973099,0.971358,0.972239,0.972869,0.000958,11,0.952855,0.950426,0.948215,0.945753,0.948394,0.949129,0.002381,11,97.822730,11.749874,0.197424,0.022689

modelo: mlp
 origem do treinamento: cicids2017_iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: mlp - cicids2017_iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
6,mlp,randomized_search,cicids2017_iot23,470980,12,13,5,1,7,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.001026603003516424, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0013103269001464436, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.987610,0.984444,0.988338,0.988370,0.984886,0.986730,0.001713,2,0.990126,0.991029,0.989650,0.987898,0.989225,0.989586,0.001035,1,0.988867,0.987726,0.988994,0.988134,0.987051,0.988154,0.000723,1,0.997530,0.997754,0.997411,0.996975,0.997303,0.997395,0.000258,1,0.996895,0.996085,0.997081,0.997094,0.996205,0.996672,0.000437,2,0.997212,0.996919,0.997246,0.997034,0.996754,0.997033,0.000184,1,0.993039,0.992322,0.993120,0.992584,0.991902,0.992594,0.000453,1,0.995541,0.995074,0.995594,0.995255,0.994809,0.995255,0.000293,1,0.993511,0.993557,0.993365,0.992496,0.992715,0.993129,0.000437,1,192.211556,28.024856,0.279872,0.041263
7,mlp,randomized_search,cicids2017_iot23,470980,12,13,5,1,8,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 2.6373077790924614e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.003994745694560914, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.986262,0.987050,0.987034,0.986019,0.986417,0.986556,0.000416,3,0.990870,0.987207,0.989968,0.988270,0.986783,0.988619,0.001573,2,0.988561,0.987128,0.988499,0.987143,0.986600,0.987586,0.000795,2,0.997715,0.996802,0.997490,0.997066,0.996695,0.997154,0.000392,2,0.996550,0.996762,0.996749,0.996497,0.996603,0.996632,0.000106,3,0.997132,0.996782,0.997119,0.996781,0.996649,0.996893,0.000196,2,0.992846,0.991955,0.992809,0.991962,0.991625,0.992239,0.000496,2,0.995414,0.994851,0.995393,0.994851,0.994639,0.995030,0.000315,2,0.993710,0.991984,0.993358,0.992383,0.991693,0.992626,0.000781,2,48.778090,8.149675,0.227703,0.009805
0,mlp,randomized_search,cicids2017_iot23,470980,12,13,5,1,1,baseline,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0001, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.001, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.988850,0.987905,0.987937,0.989823,0.979212,0.986746,0.003832,1,0.983915,0.984234,0.986783,0.980892,0.992622,0.985689,0.003938,5,0.986376,0.986066,0.987360,0.985337,0.985872,0.986202,0.000670,3,0.995984,0.996062,0.996697,0.995233,0.998149,0.996425,0.000979,5,0.997227,0.996988,0.996988,0.997479,0.994732,0.996682,0.000992,1,0.996605,0.996525,0.996842,0.996355,0.996437,0.996553,0.000167,3,0.991491,0.991295,0.992101,0.990846,0.991155,0.991378,0.000418,3,0.994565,0.994437,0.994947,0.994161,0.994310,0.994484,0.000267,3,0.990571,0.990611,0.991886,0.989185,0.993677,0.991186,0.001510,4,203.779881,30.881144,0.211431,0.008587
10,mlp,randomized_search,cicids2017_iot23,470980,12,13,5,1,11,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 1.3096774493777596e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.005705385668376793, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.983211,0.964869,0.988834,0.986499,0.985441,0.981771,0.008642,5,0.988587,0.987047,0.987102,0.988960,0.988004,0.987940,0.000770,4,0.985892,0.975832,0.987967,0.987728,0.986721,0.984828,0.004558,4,0.997143,0.996743,0.996777,0.997238,0.996999,0.996980,0.000195,4,0.995780,0.991016,0.997213,0.996616,0.996351,0.995395,0.002238,5,0.996461,0.993872,0.996995,0.996927,0.996675,0.996186,0.001173,4,0.991176,0.984852,0.992481,0.992327,0.991698,0.990507,0.002865,4,0.994342,0.990223,0.995191,0.995085,0.994681,0.993904,0.001865,4,0.992184,0.989032,0.992158,0.992788,0.992177,0.991668,0.001339,3,66.827744,21.717452,0.186045,0.046722
4,mlp,randomized_search,cicids2017_iot23,470980,12,13,5,1,5,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0004134759007834719, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.002346599645859086, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.986190,0.985762,0.987592,0.987192,0.984595,0.986266,0.001065,4,0.981845,0.981261,0.980149,0.985934,0.980414,0.981921,0.002096,6,0.984013,0.983506,0.983856,0.986563,0.982500,0.984088,0.001345,5,0.995467,0.995321,0.995046,0.996484,0.995108,0.995485,0.000522,6,0.996563,0.996457,0.996921,0.996802,0.996165,0.996582,0.000266,4,0.996015,0.995889,0.995983,0.996643,0.995636,0.996033,0.000333,5,0.990014,0.989697,0.989920,0.991603,0.989068,0.990060,0.000839,5,0.993620,0.993418,0.993567,0.994628,0.993015,0.993649,0.000533,5,0.989204,0.988859,0.988535,0.991368,0.988289,0.989251,0.001102,6,41.780165,12.014695,0.220347,0.023365
11,mlp,randomized_search,cicids2017_iot23,470980,12,13,5,1,12,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 1.9726066891840947e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.008237189558335287, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.982977,0.965097,0.965956,0.965299,0.985806,0.973027,0.009326,6,0.990073,0.987844,0.987951,0.987792,0.987951,0.988322,0.000878,3,0.986512,0.976338,0.976830,0.976416,0.986877,0.980595,0.004985,6,0.997514,0.996943,0.996970,0.996930,0.996986,0.997069,0.000224,3,0.995714,0.991069,0.991295,0.991122,0.996444,0.993129,0.002421,6,0.996613,0.993998,0.994124,0.994018,0.996715,0.995093,0.001283,6,0.991563,0.985168,0.985477,0.985217,0.991796,0.987844,0.003134,6,0.994586,0.990424,0.990626,0.990456,0.994745,0.992167,0.002041,6,0.992894,0.989457,0.989623,0.989457,0.992197,0.990725,0.001503,5,58.681863,4.858204,0.174104,0.029949
3,mlp,randomized_search,cicids2017_iot23,470980,12,13,5,1,4,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 3.620600725744737e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0006216342697722397, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.964243,0.963616,0.967945,0.966313,0.964096,0.965242,0.001638,7,0.984871,0.984128,0.979299,0.975955,0.980573,0.980965,0.003264,7,0.974448,0.973764,0.973589,0.971110,0.972265,0.973035,0.001194,7,0.996198,0.996011,0.994809,0.993973,0.995122,0.995223,0.000814,7,0.990870,0.990711,0.991892,0.991494,0.990870,0.991167,0.000451,7,0.993527,0.993354,0.993348,0.992732,0.992992,0.993191,0.000288,7,0.983987,0.983559,0.983469,0.981921,0.982628,0.983113,0.000741,7,0.989670,0.989394,0.989373,0.988386,0.988811,0.989127,0.000464,7,0.987871,0.987419,0.985596,0.983725,0.985722,0.986066,0.001477,7,93.378738,18.380456,0.186303,0.019663
8,mlp,randomized_search,cicids2017_iot23,470980,12,13,5,1,9,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.008031279258119075, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0024246286430387822, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.964362,0.963106,0.969425,0.960656,0.963678,0.964245,0.002876,8,0.983969,0.981102,0.969374,0.979777,0.980149,0.978874,0.004972,11,0.974067,0.972021,0.969399,0.970122,0.971844,0.971490,0.001630,8,0.995972,0.995254,0.992343,0.994919,0.995016,0.994701,0.001235,11,0.990910,0.990605,0.992356,0.989968,0.990764,0.990921,0.000787,8,0.993435,0.992924,0.992350,0.992437,0.992885,0.992806,0.000390,8,0.983751,0.982472,0.980875,0.981280,0.982364,0.982148,0.001010,8,0.989522,0.988704,0.987760,0.987929,0.988641,0.988511,0.000629,8,0.987439,0.985853,0.980865,0.984872,0.985456,0.984897,0.002189,11,63.066925,5.684578,0.225446,0.017460
12,mlp,randomized_search,cicids2017_iot23,470980,12,13,5,1,13,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0003976453011700043, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0004275936647080326, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.961774,0.961610,0.963945,0.962534,0.961757,0.962324,0.000872,9,0.981686,0.981314,0.980573,0.979087,0.979777,0.980488,0.000958,8,0.971628,0.971363,0.972188,0.970740,0.970683,0.971320,0.000564,9,0.995398,0.995305,0.995122,0.994749,0.994920,0.995099,0.000240,8,0.990247,0.990207,0.990830,0.990472,0.990260,0.990403,0.000233,9,0.992816,0.992749,0.992971,0.992606,0.992584,0.992745,0.000142,9,0.982222,0.982056,0.982580,0.981673,0.981634,0.982033,0.000353,9,0.988535,0.988428,0.988779,0.988195,0.988163,0.988420,0.000227,9,0.985966,0.985761,0.985702,0.984779,0.985018,0.985445,0.000461,8,27.251511,2.423267,0.148664,0.019621
2,mlp,randomized_search,cicids2017_iot23,470980,12,13,5,1,3,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 8.072307884499753e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0001529949829431265, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.961823,0.961845,0.964002,0.962225,0.961404,0.962260,0.000909,10,0.981633,0.980890,0.979352,0.978875,0.979724,0.980095,0.001017,9,0.971627,0.971274,0.971617,0.970478,0.970478,0.971095,0.000519,10,0.995385,0.995199,0.994817,0.994695,0.994906,0.995001,0.000254,9,0.990260,0.990273,0.990857,0.990392,0.990167,0.990390,0.000244,10,0.992816,0.992730,0.992833,0.992539,0.992531,0.992690,0.000131,10,0.982221,0.982002,0.982225,0.981509,0.981504,0.981892,0.000325,10,0.988535,0.988397,0.988556,0.988089,0.988078,0.988331,0.000209,10,0.985946,0.985581,0.985105,0.984634,0.984945,0.985242,0.000467,9,63.745326,3.659011,0.170025,0.009909
9,mlp,randomized_search,cicids2017_iot23,470980,12,13,5,1,10,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.004257625486011381, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.00014794095665996457, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.961448,0.962340,0.963965,0.961526,0.960885,0.962033,0.001072,11,0.980996,0.980730,0.979724,0.978981,0.979246,0.979935,0.000798,10,0.971124,0.971448,0.971781,0.970175,0.969979,0.970901,0.000707,11,0.995225,0.995160,0.994910,0.994721,0.994786,0.994960,0.000200,10,0.990167,0.990406,0.990843,0.990206,0.990034,0.990331,0.000282,11,0.992690,0.992777,0.992873,0.992459,0.992404,0.992640,0.000181,11,0.981907,0.982113,0.982327,0.981317,0.981192,0.981771,0.000444,11,0.988333,0.988471,0.988619,0.987961,0.987876,0.988252,0.000288,11,0.985581,0.985568,0.985284,0.984594,0.984640,0.985133,0.000435,10,59.558204,2.522850,0.210573,0.020643

modelo: mlp
 origem do treinamento: unsw_nb15_iot23
Fitting 5 folds for each of 13 candidates, totalling 65 fits
resultados dos hiperparâmetros: mlp - unsw_nb15_iot23

,model,search_method,training_source,training_rows,n_random_candidates,n_candidates,n_splits,random_state,candidate_id,candidate_type,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time,mean_score_time,std_score_time
6,mlp,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,7,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.001026603003516424, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0013103269001464436, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.969491,0.970123,0.969890,0.966656,0.967440,0.968720,0.001402,1,0.991878,0.989383,0.986518,0.990977,0.988854,0.989522,0.001852,1,0.980557,0.979658,0.978133,0.978665,0.978030,0.979009,0.000966,1,0.997958,0.997333,0.996615,0.997730,0.997198,0.997367,0.000464,1,0.992197,0.992383,0.992343,0.991454,0.991679,0.992011,0.000375,1,0.995069,0.994852,0.994474,0.994582,0.994431,0.994682,0.000243,1,0.987813,0.987255,0.986304,0.986624,0.986230,0.986845,0.000604,1,0.992133,0.991783,0.991178,0.991358,0.991114,0.991513,0.000388,1,0.992038,0.990883,0.989431,0.991215,0.990266,0.990767,0.000879,1,257.328947,17.226165,0.276711,0.007227
7,mlp,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,8,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 2.6373077790924614e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.003994745694560914, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.967904,0.963555,0.964371,0.963109,0.964286,0.964645,0.001696,3,0.989330,0.988056,0.991295,0.988004,0.990287,0.989394,0.001276,2,0.978500,0.975652,0.977647,0.975398,0.977113,0.976862,0.001181,2,0.997318,0.996995,0.997808,0.996981,0.997555,0.997332,0.000320,2,0.991799,0.990658,0.990843,0.990538,0.990830,0.990934,0.000447,4,0.994551,0.993816,0.994314,0.993749,0.994181,0.994122,0.000302,2,0.986525,0.984734,0.985981,0.984573,0.985647,0.985492,0.000741,2,0.991305,0.990138,0.990934,0.990031,0.990721,0.990626,0.000481,2,0.990565,0.989357,0.991069,0.989271,0.990558,0.990164,0.000719,2,53.641317,11.317247,0.217043,0.004601
10,mlp,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,11,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 1.3096774493777596e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.005705385668376793, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.966855,0.969068,0.963739,0.964369,0.967460,0.966298,0.001980,2,0.989489,0.991188,0.991720,0.991242,0.968949,0.986518,0.008817,3,0.978041,0.980003,0.977529,0.977621,0.968204,0.976280,0.004136,3,0.997357,0.997785,0.997915,0.997795,0.992234,0.996617,0.002200,3,0.991520,0.992091,0.990671,0.990843,0.991852,0.991396,0.000555,2,0.994430,0.994930,0.994280,0.994307,0.992043,0.993998,0.001005,3,0.986236,0.987466,0.985904,0.985964,0.980123,0.985139,0.002571,3,0.991114,0.991910,0.990881,0.990923,0.987271,0.990420,0.001618,3,0.990505,0.991640,0.991195,0.991043,0.980401,0.988957,0.004293,3,92.689828,36.676482,0.178615,0.030959
11,mlp,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,12,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 1.9726066891840947e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.008237189558335287, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.967334,0.965785,0.950046,0.967071,0.959705,0.961988,0.006583,6,0.987207,0.991931,0.990287,0.964915,0.973408,0.981549,0.010575,5,0.977169,0.978683,0.969749,0.965992,0.966508,0.971620,0.005329,4,0.996785,0.997969,0.997546,0.991233,0.993328,0.995372,0.002637,5,0.991666,0.991215,0.986982,0.991786,0.989782,0.990286,0.001799,10,0.994219,0.994581,0.992236,0.991509,0.991552,0.992819,0.001321,4,0.985694,0.986632,0.980992,0.978751,0.979030,0.982220,0.003324,4,0.990775,0.991358,0.987643,0.986411,0.986507,0.988539,0.002117,4,0.989437,0.991573,0.988634,0.978350,0.981595,0.985918,0.005054,5,72.081418,33.036357,0.183568,0.022276
0,mlp,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,1,baseline,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0001, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.001, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.966964,0.952968,0.953557,0.951677,0.954706,0.955974,0.005581,11,0.985083,0.988481,0.981900,0.987845,0.974469,0.983556,0.005105,4,0.975939,0.970400,0.967521,0.969424,0.964486,0.969554,0.003777,5,0.996254,0.997093,0.995441,0.996932,0.993584,0.995861,0.001279,4,0.991587,0.987805,0.988043,0.987460,0.988442,0.988667,0.001494,11,0.993915,0.992427,0.991728,0.992173,0.991006,0.992250,0.000962,5,0.984927,0.981414,0.979625,0.980799,0.977746,0.980902,0.002369,5,0.990286,0.987940,0.986815,0.987537,0.985647,0.987645,0.001533,5,0.988335,0.988143,0.984972,0.987652,0.981455,0.986111,0.002624,4,229.678583,24.988596,0.203048,0.022263
4,mlp,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,5,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0004134759007834719, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.002346599645859086, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.965767,0.966292,0.959437,0.962428,0.962107,0.963206,0.002534,4,0.964434,0.963266,0.969214,0.962633,0.967622,0.965434,0.002555,8,0.965100,0.964777,0.964301,0.962531,0.964857,0.964313,0.000928,6,0.991112,0.990824,0.992284,0.990657,0.991893,0.991354,0.000629,8,0.991454,0.991600,0.989755,0.990605,0.990472,0.990777,0.000679,5,0.991283,0.991212,0.991018,0.990631,0.991182,0.991065,0.000234,6,0.978191,0.977994,0.977659,0.976581,0.978019,0.977689,0.000580,6,0.986050,0.985934,0.985647,0.985010,0.985902,0.985709,0.000373,6,0.977944,0.977433,0.979485,0.976619,0.979047,0.978105,0.001047,7,39.787619,10.286063,0.206298,0.028180
8,mlp,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,9,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.008031279258119075, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0024246286430387822, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.959598,0.964004,0.951218,0.949681,0.950943,0.955089,0.005678,12,0.968309,0.965283,0.969798,0.964703,0.969214,0.967461,0.002079,7,0.963934,0.964643,0.960418,0.957133,0.959992,0.961224,0.002754,7,0.992060,0.991319,0.992412,0.991140,0.992266,0.991839,0.000514,7,0.989809,0.990990,0.987566,0.987221,0.987499,0.988617,0.001507,12,0.990933,0.991154,0.989983,0.989177,0.989877,0.990225,0.000727,7,0.977433,0.977898,0.975201,0.973155,0.974934,0.975724,0.001741,7,0.985509,0.985849,0.984012,0.982717,0.983842,0.984386,0.001151,7,0.979059,0.978136,0.978682,0.975962,0.978357,0.978039,0.001084,8,130.129126,12.554453,0.219697,0.003658
3,mlp,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,4,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 3.620600725744737e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0006216342697722397, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.953783,0.954776,0.949578,0.953269,0.950843,0.952450,0.001933,13,0.971706,0.969424,0.973620,0.965817,0.970223,0.970158,0.002599,6,0.962661,0.962044,0.961449,0.959502,0.960435,0.961218,0.001129,8,0.992894,0.992327,0.993363,0.991426,0.992517,0.992505,0.000646,6,0.988230,0.988521,0.987075,0.988163,0.987460,0.987890,0.000536,13,0.990556,0.990421,0.990209,0.989792,0.989982,0.990192,0.000279,8,0.976609,0.976232,0.975829,0.974647,0.975208,0.975705,0.000704,8,0.984925,0.984702,0.984384,0.983694,0.984012,0.984343,0.000447,8,0.979968,0.978972,0.980347,0.976990,0.978841,0.979024,0.001167,6,185.936461,17.014609,0.174182,0.015490
2,mlp,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,3,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 8.072307884499753e-05, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": false, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0001529949829431265, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.963378,0.963529,0.961976,0.962085,0.962119,0.962617,0.000686,5,0.930035,0.929823,0.933280,0.927972,0.927495,0.929721,0.002039,9,0.946413,0.946376,0.947411,0.944721,0.944489,0.945882,0.001109,9,0.982660,0.982609,0.983443,0.982150,0.982034,0.982579,0.000497,9,0.991162,0.991202,0.990777,0.990857,0.990870,0.990974,0.000174,3,0.986893,0.986887,0.987096,0.986484,0.986432,0.986759,0.000257,9,0.966653,0.966631,0.967254,0.965602,0.965461,0.966320,0.000683,9,0.978938,0.978927,0.979277,0.978279,0.978194,0.978723,0.000417,9,0.960599,0.960512,0.962029,0.959415,0.959182,0.960347,0.001014,9,185.218077,16.959728,0.172147,0.014554
12,mlp,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,13,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0003976453011700043, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.0004275936647080326, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.961773,0.962038,0.960634,0.959437,0.959745,0.960726,0.001044,7,0.928230,0.928230,0.932590,0.926539,0.927601,0.928638,0.002070,10,0.944704,0.944832,0.946405,0.942701,0.943399,0.944408,0.001279,10,0.982214,0.982215,0.983269,0.981790,0.982050,0.982308,0.000505,10,0.990777,0.990844,0.990445,0.990206,0.990273,0.990509,0.000259,6,0.986477,0.986511,0.986844,0.985980,0.986144,0.986391,0.000302,10,0.965591,0.965671,0.966624,0.964341,0.964772,0.965400,0.000791,10,0.978269,0.978322,0.978874,0.977473,0.977738,0.978135,0.000489,10,0.959504,0.959537,0.961518,0.958373,0.958937,0.959574,0.001061,10,38.658976,3.791465,0.140213,0.011649
9,mlp,randomized_search,unsw_nb15_iot23,470980,12,13,5,1,10,random,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.004257625486011381, ""classifier__batch_size"": ""auto"", ""classifier__beta_1"": 0.9, ""classifier__beta_2"": 0.999, ""classifier__early_stopping"": true, ""classifier__epsilon"": 1e-08, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate"": ""constant"", ""classifier__learning_rate_init"": 0.00014794095665996457, ""classifier__max_fun"": 15000, ""classifier__max_iter"": 200, ""classifier__momentum"": 0.9, ""classifier__n_iter_no_change"": 10, ""classifier__nesterovs_momentum"": true, ""classifier__power_t"": 0.5, ""classifier__random_state"": 1, ""classifier__shuffle"": true, ""classifier__solver"": ""adam"", ""classifier__tol"": 0.0001, ""classifier__validation_fraction"": 0.1, ""classifier__verbose"": false, ""classifier__warm_start"": false}",0.961399,0.962675,0.960397,0.959398,0.958345,0.960443,0.001509,8,0.926797,0.926903,0.929352,0.926858,0.919533,0.925889,0.003322,13,0.943781,0.944450,0.944620,0.942847,0.938538,0.942847,0.002243,11,0.981864,0.981895,0.982479,0.981867,0.980084,0.981638,0.000811,13,0.990698,0.991016,0.990419,0.990193,0.990007,0.990467,0.000359,7,0.986261,0.986435,0.986433,0.986013,0.985021,0.986032,0.000529,11,0.965021,0.965443,0.965526,0.964430,0.961779,0.964440,0.001386,11,0.977918,0.978194,0.978205,0.977526,0.975912,0.977551,0.000856,11,0.958747,0.958960,0.959886,0.958525,0.954770,0.958178,0.001766,12,75.637395,17.744393,0.215351,0.014081

,model,search_method,training_source,training_rows,n_random_candidates,n_splits,random_state,n_candidates,best_candidate_type,selection_metric,params,elapsed_seconds,elapsed_minutes,refit_time_seconds,model_size_mb,model_file,precision_attack_mean,precision_attack_std,recall_attack_mean,recall_attack_std,f1_attack_mean,f1_attack_std,precision_benign_mean,precision_benign_std,recall_benign_mean,recall_benign_std,f1_benign_mean,f1_benign_std,f1_macro_mean,f1_macro_std,accuracy_mean,accuracy_std,balanced_accuracy_mean,balanced_accuracy_std
0,decision_tree,randomized_search,cicids2017,235490,12,5,1,13,baseline,f1_macro,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",23.353092,0.389218,1.816012,0.033245,cicids2017.joblib,0.981621,0.001258,0.987579,0.001500,0.984589,0.000582,0.996890,0.000374,0.995377,0.000327,0.996133,0.000145,0.990361,0.000363,0.993817,0.000232,0.991478,0.000652
1,decision_tree,randomized_search,unsw_nb15,235490,12,5,1,13,random,f1_macro,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 10, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",20.746750,0.345779,1.496691,0.013993,unsw_nb15.joblib,0.942730,0.001502,0.994671,0.000767,0.968004,0.000994,0.998649,0.000194,0.984893,0.000417,0.991723,0.000263,0.979864,0.000628,0.986849,0.000416,0.989782,0.000500
2,decision_tree,randomized_search,iot23,235490,12,5,1,13,random,f1_macro,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 8, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 6, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",10.008290,0.166805,0.550976,0.005307,iot23.joblib,0.999530,0.000174,0.993206,0.000961,0.996358,0.000533,0.998304,0.000240,0.999883,0.000043,0.999093,0.000132,0.997725,0.000332,0.998548,0.000212,0.996544,0.000492
3,decision_tree,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,13,random,f1_macro,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",43.113167,0.718553,3.727911,0.037752,cicids2017_unsw_nb15.joblib,0.960413,0.001952,0.986868,0.000512,0.973460,0.001076,0.996694,0.000129,0.989830,0.000520,0.993250,0.000281,0.983355,0.000678,0.989237,0.000445,0.988349,0.000395
4,decision_tree,randomized_search,cicids2017_iot23,470980,12,5,1,13,baseline,f1_macro,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",32.956324,0.549272,2.792350,0.042503,cicids2017_iot23.joblib,0.989187,0.000598,0.990573,0.000469,0.989879,0.000294,0.997642,0.000117,0.997293,0.000152,0.997468,0.000074,0.993673,0.000184,0.995949,0.000118,0.993933,0.000214
5,decision_tree,randomized_search,unsw_nb15_iot23,470980,12,5,1,13,random,f1_macro,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": null, ""classifier__max_leaf_nodes"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 17, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__random_state"": 1, ""classifier__splitter"": ""best""}",29.796993,0.496617,2.619082,0.029032,unsw_nb15_iot23.joblib,0.971112,0.000900,0.992112,0.000550,0.981500,0.000610,0.998017,0.000138,0.992622,0.000236,0.995312,0.000156,0.988406,0.000383,0.992520,0.000248,0.992367,0.000334
6,random_forest,randomized_search,cicids2017,235490,12,5,1,13,random,f1_macro,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 171, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",829.363493,13.822725,35.167629,4.951621,cicids2017.joblib,0.979554,0.001851,0.996667,0.000802,0.988035,0.000918,0.999163,0.000201,0.994798,0.000482,0.996976,0.000235,0.992505,0.000577,0.995172,0.000374,0.995732,0.000407
7,random_forest,randomized_search,unsw_nb15,235490,12,5,1,13,random,f1_macro,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 171, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",822.875393,13.714590,36.225025,12.828723,unsw_nb15.joblib,0.943585,0.001444,0.997155,0.000472,0.969630,0.000682,0.999279,0.000120,0.985095,0.000408,0.992136,0.000185,0.980883,0.000434,0.987507,0.000291,0.991125,0.000222
8,random_forest,randomized_search,iot23,235490,12,5,1,13,random,f1_macro,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 168, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",435.615943,7.260266,17.553909,0.928738,iot23.joblib,0.999808,0.000157,0.993354,0.000953,0.996570,0.000500,0.998341,0.000238,0.999952,0.000039,0.999146,0.000124,0.997858,0.000312,0.998633,0.000199,0.996653,0.000481
9,random_forest,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,13,random,f1_macro,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 171, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",2046.981572,34.116360,100.280946,18.942508,cicids2017_unsw_nb15.joblib,0.960801,0.001775,0.995509,0.000639,0.977847,0.001113,0.998867,0.000161,0.989846,0.000475,0.994336,0.000289,0.986091,0.000701,0.990978,0.000459,0.992677,0.000486
10,random_forest,randomized_search,cicids2017_iot23,470980,12,5,1,13,baseline,f1_macro,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 100, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",1616.655853,26.944264,50.085337,4.030020,cicids2017_iot23.joblib,0.989623,0.000928,0.993142,0.000442,0.991379,0.000521,0.998284,0.000110,0.997396,0.000235,0.997840,0.000131,0.994610,0.000326,0.996546,0.000210,0.995269,0.000253
11,random_forest,randomized_search,unsw_nb15_iot23,470980,12,5,1,13,random,f1_macro,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__max_leaf_nodes"": null, ""classifier__max_samples"": null, ""classifier__min_impurity_decrease"": 0.0, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 2, ""classifier__min_weight_fraction_leaf"": 0.0, ""classifier__monotonic_cst"": null, ""classifier__n_estimators"": 168, ""classifier__n_jobs"": 1, ""classifier__oob_score"": false, ""classifier__random_state"": 1, ""classifier__verbose"": 0, ""classifier__warm_start"": false}",1487.054219,24.784237,68.443604,5.280327,unsw_nb15_iot23.joblib,0.970256,0.000904,0.995562,0.000535,0.982746,0.000298,0.998883,0.000134,0.992370,0.000243,0.995616,0.000079,0.989181,0.000188,0.993008,0.000125,0.993966,0.000184
12,xgboost,randomized_search,cicids2017,235490,12,5,1,13,random,f1_macro,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.717772960390469, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 6, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 298, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.9873668590451505, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",51.374061,0.856234,6.039621,0.256427,cicids2017.joblib,0.980977,0.001133,0.993015,0.001540,0.986958,0.000962,0.998248,0.000385,0.995186,0.000292,0.996715,0.000241,0.991836,0.000601,0.994751,0.000386,0.994100,0.000783
13,xgboost,randomized_search,unsw_nb15,235490,12,5,1,13,random,f1_macro,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.9725786509279286, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 8, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 200, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.8574398130611336, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",53.169139,0.886152,5.343481,0.470984,unsw_nb15.joblib,0.943358,0.001352,0.997856,0.000477,0.969841,0.000527,0.999456,0.000121,0.985021,0.000386,0.992186,0.000146,0.981013,0.000337,0.987588,0.000229,0.991438,0.000113
14,xgboost,randomized_search,iot23,235490,12,5,1,13,random,f1_macro,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.7895485884259134, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.08380226576125108, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 5, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 253, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.8343680578527715, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",46.141024,0.769017,5.164364,0.123423,iot23.joblib,0.999701,0.000080,0.993354,0.000882,0.996517,0.000457,0.998341,0.000220,0.999926,0.000020,0.999133,0.000113,0.997825,0.000285,0.998611,0.000181,0.996640,0.000444
15,xgboost,randomized_search,cicids2017_unsw_nb15,470980,12,5,1,13,random,f1_macro,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_bylevel"": null, ""classifier__colsample_bynode"": null, ""classifier__colsample_bytree"": 0.717772960390469, ""classifier__device"": null, ""classifier__early_stopping_rounds"": null, ""classifier__enable_categorical"": true, ""classifier__eval_metric"": ""logloss"", ""classifier__feature_types"": null, ""classifier__feature_weights"": null, ""classifier__gamma"": null, ""classifier__grow_policy"": null, ""classifier__importance_type"": null, ""classifier__interaction_constraints"": null, ""classifier__learning_rate"": 0.1404912558872892, ""classifier__max_bin"": null, ""classifier__max_cat_threshold"": null, ""classifier__max_cat_to_onehot"": null, ""classifier__max_delta_step"": null, ""classifier__max_depth"": 6, ""classifier__max_leaves"": null, ""classifier__min_child_weight"": null, ""classifier__missing"": NaN, ""classifier__monotone_constraints"": null, ""classifier__multi_strategy"": null, ""classifier__n_estimators"": 298, ""classifier__n_jobs"": 1, ""classifier__num_parallel_tree"": null, ""classifier__objective"": ""binary:logistic"", ""classifier__random_state"": 1, ""classifier__reg_alpha"": null, ""classifier__reg_lambda"": null, ""classifier__sampling_method"": null, ""classifier__scale_pos_weight"": null, ""classifier__subsample"": 0.9873668590451505, ""classifier__tree_method"": ""hist"", ""classifier__validate_parameters"": null, ""classifier__verbosity"": null}",112.075790,1.867930,12.636837,0.334027,cicids2017_unsw_nb15.joblib,0.961126,0.001540,0.993694,0.000778,0.977138,0.001034,0.998410,0.000196,0.989952,0.000410,0.994163,0.000267,0.985651,0.000651,0.990700,0.000425,0.991823,0.000519