In [1]:
from pathlib import Path
from time import perf_counter
import json

import joblib
import optuna
import pandas as pd
from optuna.distributions import (
    CategoricalDistribution,
    FloatDistribution,
    IntDistribution,
)
from optuna.samplers import TPESampler
from optuna_integration.sklearn import OptunaSearchCV

from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, make_scorer, precision_score, recall_score
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier

from src.utils.features import split_features

In [2]:
DATA_DIR = Path("../datasets/final/ml")
SEARCH_METHOD = "optuna"
MODEL_DIR = Path("../models") / SEARCH_METHOD
RESULTS_DIR = Path("../results/model_training") / SEARCH_METHOD

MODEL_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 1
N_SPLITS = 5
N_TRIALS = 30
# trials sequenciais garantem que o TPE use todo o histórico anterior e seja reproduzível.
SEARCH_N_JOBS = 1
#o paralelismo fica dentro dos estimadores que oferecem suporte.
ESTIMATOR_N_JOBS = -1

TRAINING_CONFIGS = {
    "cicids2017": ["cicids2017"],
    "unsw_nb15": ["unsw_nb15"],
    "iot23": ["iot23"],
    "cicids2017_unsw_nb15": ["cicids2017", "unsw_nb15"],
    "cicids2017_iot23": ["cicids2017", "iot23"],
    "unsw_nb15_iot23": ["unsw_nb15", "iot23"],
}

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [3]:
reference_df = pd.read_parquet(DATA_DIR / "cicids2017_train.parquet")
numerical_features, categorical_features = split_features(reference_df)
feature_columns = numerical_features + categorical_features
del reference_df

def build_pipeline(estimator):
    preprocessor = ColumnTransformer(
        transformers=[
            ("numerical", StandardScaler(), numerical_features),
            ("categorical", OneHotEncoder(handle_unknown="ignore"), categorical_features),
        ]
    )
    return Pipeline(steps=[("preprocessor", preprocessor), ("classifier", estimator)])

In [4]:
def categorical(values):
    return CategoricalDistribution(values)


MODEL_CONFIGS = {
    "decision_tree": {
        "estimator": DecisionTreeClassifier(random_state=RANDOM_STATE),
        "param_distributions": {
            "classifier__max_depth": categorical([None, 3, 5, 8, 10, 15, 20, 30]),
            "classifier__min_samples_split": IntDistribution(2, 20),
            "classifier__min_samples_leaf": IntDistribution(1, 10),
            "classifier__class_weight": categorical([None, "balanced"]),
        },
    },
    "random_forest": {
        "estimator": RandomForestClassifier(
            random_state=RANDOM_STATE, n_jobs=ESTIMATOR_N_JOBS
        ),
        "param_distributions": {
            "classifier__n_estimators": IntDistribution(100, 300),
            "classifier__max_depth": categorical([None, 10, 15, 20, 30]),
            "classifier__min_samples_leaf": IntDistribution(1, 10),
            "classifier__max_features": categorical(["sqrt", "log2", 0.5, 1.0]),
            "classifier__class_weight": categorical(
                [None, "balanced", "balanced_subsample"]
            ),
        },
    },
    "xgboost": {
        "estimator": XGBClassifier(
            random_state=RANDOM_STATE,
            n_jobs=ESTIMATOR_N_JOBS,
            eval_metric="logloss",
            tree_method="hist",
        ),
        "param_distributions": {
            "classifier__n_estimators": IntDistribution(100, 300),
            "classifier__max_depth": IntDistribution(3, 8),
            "classifier__learning_rate": FloatDistribution(0.03, 0.3, log=True),
            "classifier__subsample": FloatDistribution(0.7, 1.0),
            "classifier__colsample_bytree": FloatDistribution(0.7, 1.0),
        },
    },
    "linear_svm": {
        "estimator": LinearSVC(random_state=RANDOM_STATE),
        "param_distributions": {
            "classifier__C": FloatDistribution(1e-3, 1e2, log=True),
            "classifier__class_weight": categorical([None, "balanced"]),
        },
    },
    "mlp": {
        "estimator": MLPClassifier(random_state=RANDOM_STATE),
        "param_distributions": {
            "classifier__hidden_layer_sizes": categorical([(50,), (100,), (50, 50), (100, 50)]),
            "classifier__alpha": FloatDistribution(1e-5, 1e-2, log=True),
            "classifier__learning_rate_init": FloatDistribution(1e-4, 1e-2, log=True),
            "classifier__early_stopping": categorical([True, False]),
        },
    },
}

C:\Users\valde\AppData\Local\Temp\ipykernel_18900\2254232033.py:2: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (50,) which is of type tuple.
  return CategoricalDistribution(values)
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\2254232033.py:2: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (100,) which is of type tuple.
  return CategoricalDistribution(values)
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\2254232033.py:2: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (50, 50) which is of type tuple.
  return CategoricalDistribution(values)
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\2254232033.py:2: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (100, 50) which is of type tuple.
  return CategoricalDistribution(values)

In [5]:
#modelos com orçamento de 30 trials.
MODELS_TO_RUN = [
    "decision_tree",
    "random_forest",
    "xgboost",
    "linear_svm",
    "mlp",
]

cross_validation = StratifiedKFold(
    n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE
)

scoring = {
    "precision_attack": make_scorer(precision_score, pos_label=1, zero_division=0),
    "recall_attack": make_scorer(recall_score, pos_label=1, zero_division=0),
    "f1_attack": make_scorer(f1_score, pos_label=1, zero_division=0),
    "precision_benign": make_scorer(precision_score, pos_label=0, zero_division=0),
    "recall_benign": make_scorer(recall_score, pos_label=0, zero_division=0),
    "f1_benign": make_scorer(f1_score, pos_label=0, zero_division=0),
    "f1_macro": make_scorer(
        f1_score, average="macro", labels=[0, 1], zero_division=0
    ),
    "accuracy": "accuracy",
    "balanced_accuracy": "balanced_accuracy",
}

In [6]:
def load_training_data(dataset_names):
    columns = feature_columns + ["label_binary", "dataset_name"]
    dataframes = [
        pd.read_parquet(DATA_DIR / f"{dataset_name}_train.parquet", columns=columns)
        for dataset_name in dataset_names
    ]
    training_df = pd.concat(dataframes, ignore_index=True)
    features = training_df[feature_columns]
    target = training_df["label_binary"].eq("ATTACK").astype("int8")
    stratification_labels = (
        training_df["dataset_name"].astype("string")
        + "__"
        + target.astype("string")
    )
    cv_splits = list(cross_validation.split(features, stratification_labels))
    return features, target, cv_splits


def serialize_params(params):
    return json.dumps(params, sort_keys=True, default=lambda value: value.item())

In [7]:
def train_and_select_model(model_name, training_name, dataset_names):
    features, target, cv_splits = load_training_data(dataset_names)
    model_config = MODEL_CONFIGS[model_name]
    model_dir = MODEL_DIR / model_name
    results_dir = RESULTS_DIR / model_name
    model_dir.mkdir(parents=True, exist_ok=True)
    results_dir.mkdir(parents=True, exist_ok=True)

    study = optuna.create_study(
        direction="maximize",
        sampler=TPESampler(seed=RANDOM_STATE),
        study_name=f"{model_name}_{training_name}",
    )
    search = OptunaSearchCV(
        estimator=build_pipeline(model_config["estimator"]),
        param_distributions=model_config["param_distributions"],
        cv=cv_splits,
        scoring=scoring["f1_macro"],
        n_trials=N_TRIALS,
        study=study,
        refit=True,
        n_jobs=SEARCH_N_JOBS,
        random_state=RANDOM_STATE,
        verbose=1,
        error_score="raise",
        return_train_score=False,
    )

    search_start = perf_counter()
    search.fit(features, target)
    search_elapsed_seconds = perf_counter() - search_start

    candidate_results = pd.DataFrame(search.cv_results_)
    candidate_results = candidate_results.rename(columns={
        **{f"split{fold}_test_score": f"split{fold}_test_f1_macro" for fold in range(N_SPLITS)},
        "mean_test_score": "mean_test_f1_macro",
        "std_test_score": "std_test_f1_macro",
    })
    completed_trials = sorted(
        (trial for trial in study.trials if trial.state.name == "COMPLETE"),
        key=lambda trial: trial.number,
    )
    if len(completed_trials) != len(candidate_results):
        raise RuntimeError("Quantidade de trials concluídos incompatível com cv_results_.")
    candidate_results.insert(0, "trial_number", [trial.number for trial in completed_trials])
    candidate_results.insert(1, "trial_state", [trial.state.name for trial in completed_trials])
    candidate_results.insert(2, "trial_duration_seconds", [
        trial.duration.total_seconds() if trial.duration is not None else None
        for trial in completed_trials
    ])
    candidate_results.insert(3, "params", [
        serialize_params(trial.params) for trial in completed_trials
    ])
    candidate_results["rank_test_f1_macro"] = (
        candidate_results["mean_test_f1_macro"]
        .rank(method="min", ascending=False)
        .astype("int64")
    )
    candidate_results = candidate_results.sort_values("rank_test_f1_macro")
    candidate_results.insert(0, "random_state", RANDOM_STATE)
    candidate_results.insert(0, "n_splits", N_SPLITS)
    candidate_results.insert(0, "n_trials", N_TRIALS)
    candidate_results.insert(0, "training_rows", len(features))
    candidate_results.insert(0, "training_source", training_name)
    candidate_results.insert(0, "search_method", SEARCH_METHOD)
    candidate_results.insert(0, "model", model_name)
    candidate_results.to_csv(results_dir / f"{training_name}_trials.csv", index=False)

    # validação cruzada adicional da configuração vencedora para calcular,
    # em uma única execução, as médias e os desvios-padrão de todas as métricas,
    # pois o OptunaSearchCV aceita apenas uma métrica de scoring por busca.
    winner_cv_n_jobs = (
        1 if model_name in {"random_forest", "xgboost"} else -1
    )
    winner_cv_start = perf_counter()
    winner_cv_results = cross_validate(
        clone(search.best_estimator_),
        features,
        target,
        scoring=scoring,
        cv=cv_splits,
        n_jobs=winner_cv_n_jobs,
        return_train_score=False,
        error_score="raise",
    )
    winner_cv_elapsed_seconds = perf_counter() - winner_cv_start

    fold_results = pd.DataFrame({
        "model": model_name,
        "search_method": SEARCH_METHOD,
        "training_source": training_name,
        "training_rows": len(features),
        "n_trials": N_TRIALS,
        "n_splits": N_SPLITS,
        "random_state": RANDOM_STATE,
        "fold": range(1, N_SPLITS + 1),
        "fit_time_seconds": winner_cv_results["fit_time"],
        "score_time_seconds": winner_cv_results["score_time"],
    })
    for metric in scoring:
        fold_results[metric] = winner_cv_results[f"test_{metric}"]
    fold_results.to_csv(results_dir / f"{training_name}_winner_folds.csv", index=False)

    model_path = model_dir / f"{training_name}.joblib"
    joblib.dump(search.best_estimator_, model_path, compress=3)

    total_elapsed_seconds = search_elapsed_seconds + winner_cv_elapsed_seconds
    result = {
        "model": model_name,
        "search_method": SEARCH_METHOD,
        "training_source": training_name,
        "training_rows": len(features),
        "n_trials": N_TRIALS,
        "n_splits": N_SPLITS,
        "random_state": RANDOM_STATE,
        "selection_metric": "f1_macro",
        "n_completed_trials": len(completed_trials),
        "params": serialize_params(search.best_params_),
        "best_search_f1_macro": search.best_score_,
        "search_elapsed_seconds": search_elapsed_seconds,
        "search_elapsed_minutes": search_elapsed_seconds / 60,
        "refit_time_seconds": search.refit_time_,
        "winner_cv_elapsed_seconds": winner_cv_elapsed_seconds,
        "winner_cv_elapsed_minutes": winner_cv_elapsed_seconds / 60,
        "elapsed_seconds": total_elapsed_seconds,
        "elapsed_minutes": total_elapsed_seconds / 60,
        "fit_time_mean": fold_results["fit_time_seconds"].mean(),
        "fit_time_std": fold_results["fit_time_seconds"].std(ddof=0),
        "score_time_mean": fold_results["score_time_seconds"].mean(),
        "score_time_std": fold_results["score_time_seconds"].std(ddof=0),
        "model_size_mb": model_path.stat().st_size / 1024 ** 2,
        "model_file": model_path.name,
    }
    for metric in scoring:
        result[f"{metric}_mean"] = fold_results[metric].mean()
        result[f"{metric}_std"] = fold_results[metric].std(ddof=0)

    display(candidate_results)
    display(fold_results)
    return result

In [8]:
all_results = []

for model_name in MODELS_TO_RUN:
    model_results = []
    for training_name, dataset_names in TRAINING_CONFIGS.items():
        print(f"Modelo: {model_name} | origem do treinamento: {training_name}")
        result = train_and_select_model(model_name, training_name, dataset_names)
        model_results.append(result)
        all_results.append(result)

    pd.DataFrame(model_results).to_csv(
        RESULTS_DIR / model_name / "summary.csv", index=False
    )

new_results_df = pd.DataFrame(all_results)
summary_path = RESULTS_DIR / "summary.csv"
if summary_path.exists():
    previous_results_df = pd.read_csv(summary_path).reindex(
        columns=new_results_df.columns
    )
    all_results_df = pd.concat(
        [previous_results_df, new_results_df], ignore_index=True
    ).drop_duplicates(subset=["model", "training_source"], keep="last")
else:
    all_results_df = new_results_df
all_results_df.to_csv(summary_path, index=False)
display(all_results_df)

Modelo: decision_tree | origem do treinamento: cicids2017

[I 2026-10-11 21:55:35,762] A new study created in memory with name: decision_tree_cicids2017
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:55:38,056] Trial 0 finished with value: 0.9420724068889916 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 9, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9420724068889916.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:55:40,430] Trial 1 finished with value: 0.9420724068889916 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 17, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9420724068889916.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:55:42,506] Trial 2 finished with value: 0.9479473378300011 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 2 with value: 0.9479473378300011.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:55:47,809] Trial 3 finished with value: 0.9879821724520482 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 3, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9879821724520482.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:55:52,466] Trial 4 finished with value: 0.9824979945470073 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 12, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9879821724520482.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:55:55,456] Trial 5 finished with value: 0.9748105177388157 and parameters: {'classifier__max_depth': 5, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9879821724520482.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:56:00,371] Trial 6 finished with value: 0.9878826333269479 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 18, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9879821724520482.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:56:04,701] Trial 7 finished with value: 0.9848439175241236 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 10, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9879821724520482.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:56:10,514] Trial 8 finished with value: 0.9903061197537151 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 8 with value: 0.9903061197537151.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:56:12,561] Trial 9 finished with value: 0.9479473378300011 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 16, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': None}. Best is trial 8 with value: 0.9903061197537151.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:56:18,864] Trial 10 finished with value: 0.9904160313148933 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 10 with value: 0.9904160313148933.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:56:24,724] Trial 11 finished with value: 0.9902747705446544 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 10 with value: 0.9904160313148933.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:56:30,425] Trial 12 finished with value: 0.9903870052061746 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 14, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': 'balanced'}. Best is trial 10 with value: 0.9904160313148933.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:56:36,160] Trial 13 finished with value: 0.990051733961668 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 12, 'classifier__min_samples_leaf': 9, 'classifier__class_weight': 'balanced'}. Best is trial 10 with value: 0.9904160313148933.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:56:39,321] Trial 14 finished with value: 0.9739075821811973 and parameters: {'classifier__max_depth': 5, 'classifier__min_samples_split': 16, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': 'balanced'}. Best is trial 10 with value: 0.9904160313148933.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:56:44,974] Trial 15 finished with value: 0.9900487646032605 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 15, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': None}. Best is trial 10 with value: 0.9904160313148933.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:56:49,221] Trial 16 finished with value: 0.9849443023341495 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': None}. Best is trial 10 with value: 0.9904160313148933.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:56:54,964] Trial 17 finished with value: 0.9905809511419402 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 12, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': 'balanced'}. Best is trial 17 with value: 0.9905809511419402.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:57:00,664] Trial 18 finished with value: 0.9908611520841571 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 8, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': 'balanced'}. Best is trial 18 with value: 0.9908611520841571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:57:06,439] Trial 19 finished with value: 0.9908258751790969 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 8, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 18 with value: 0.9908611520841571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:57:12,324] Trial 20 finished with value: 0.9906159497138768 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 8, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': 'balanced'}. Best is trial 18 with value: 0.9908611520841571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:57:18,058] Trial 21 finished with value: 0.9908328399782185 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 4, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': 'balanced'}. Best is trial 18 with value: 0.9908611520841571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:57:23,776] Trial 22 finished with value: 0.9907806699114268 and parameters: {'classifier__max_depth': 30, 'classifier__min_samples_split': 7, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': 'balanced'}. Best is trial 18 with value: 0.9908611520841571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:57:29,694] Trial 23 finished with value: 0.9908912406737101 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 5, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 23 with value: 0.9908912406737101.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:57:33,056] Trial 24 finished with value: 0.9739210770290809 and parameters: {'classifier__max_depth': 5, 'classifier__min_samples_split': 6, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': 'balanced'}. Best is trial 23 with value: 0.9908912406737101.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:57:38,870] Trial 25 finished with value: 0.9908955066440954 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 3, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 25 with value: 0.9908955066440954.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:57:44,778] Trial 26 finished with value: 0.989820091973374 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 2, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': 'balanced'}. Best is trial 25 with value: 0.9908955066440954.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:57:47,733] Trial 27 finished with value: 0.9748242468161251 and parameters: {'classifier__max_depth': 5, 'classifier__min_samples_split': 5, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': None}. Best is trial 25 with value: 0.9908955066440954.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:57:53,376] Trial 28 finished with value: 0.9906365898775189 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 4, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': 'balanced'}. Best is trial 25 with value: 0.9908955066440954.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:57:57,893] Trial 29 finished with value: 0.9824918261722283 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 3, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 25 with value: 0.9908955066440954.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
25,decision_tree,optuna,cicids2017,235490,30,5,1,25,COMPLETE,5.813928,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 3}",1.143522,0.035127,0.016790,0.000651,0.991054,0.990759,0.991738,0.990424,0.990502,0.990896,0.000475,1
23,decision_tree,optuna,cicids2017,235490,30,5,1,23,COMPLETE,5.917538,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 5}",1.163238,0.040349,0.017724,0.001634,0.991024,0.990798,0.991672,0.990326,0.990636,0.990891,0.000452,2
18,decision_tree,optuna,cicids2017,235490,30,5,1,18,COMPLETE,5.698785,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 8}",1.120150,0.032854,0.017010,0.000348,0.991060,0.990093,0.992020,0.990839,0.990295,0.990861,0.000677,3
21,decision_tree,optuna,cicids2017,235490,30,5,1,21,COMPLETE,5.733552,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 4}",1.128054,0.032373,0.016334,0.000348,0.991223,0.989826,0.992017,0.990707,0.990391,0.990833,0.000746,4
19,decision_tree,optuna,cicids2017,235490,30,5,1,19,COMPLETE,5.775047,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 8}",1.135848,0.028530,0.016890,0.000351,0.991159,0.990639,0.991715,0.990367,0.990250,0.990826,0.000544,5
22,decision_tree,optuna,cicids2017,235490,30,5,1,22,COMPLETE,5.717615,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 7}",1.124460,0.034325,0.016740,0.000513,0.990764,0.989760,0.992217,0.990576,0.990587,0.990781,0.000798,6
28,decision_tree,optuna,cicids2017,235490,30,5,1,28,COMPLETE,5.642639,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 4}",1.109466,0.030781,0.016708,0.000404,0.991257,0.990414,0.991669,0.990028,0.989816,0.990637,0.000713,7
20,decision_tree,optuna,cicids2017,235490,30,5,1,20,COMPLETE,5.883894,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 8}",1.157569,0.040185,0.016893,0.000542,0.990883,0.990360,0.991843,0.990253,0.989742,0.990616,0.000712,8
17,decision_tree,optuna,cicids2017,235490,30,5,1,17,COMPLETE,5.742822,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 12}",1.129408,0.034785,0.016827,0.000561,0.990544,0.989901,0.991893,0.990684,0.989883,0.990581,0.000733,9
10,decision_tree,optuna,cicids2017,235490,30,5,1,10,COMPLETE,6.302211,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 19}",1.229908,0.071814,0.020060,0.003640,0.990878,0.989576,0.991498,0.990154,0.989974,0.990416,0.000686,10
12,decision_tree,optuna,cicids2017,235490,30,5,1,12,COMPLETE,5.700575,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 14}",1.121367,0.034335,0.016442,0.000369,0.990870,0.990257,0.991245,0.989936,0.989626,0.990387,0.000595,11
8,decision_tree,optuna,cicids2017,235490,30,5,1,8,COMPLETE,5.812556,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 19}",1.143723,0.025200,0.016875,0.000619,0.990823,0.989285,0.990852,0.990522,0.990049,0.990306,0.000586,12
11,decision_tree,optuna,cicids2017,235490,30,5,1,11,COMPLETE,5.859553,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 20}",1.152546,0.059390,0.016657,0.000626,0.990727,0.989189,0.990950,0.990589,0.989919,0.990275,0.000643,13
13,decision_tree,optuna,cicids2017,235490,30,5,1,13,COMPLETE,5.734691,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 9, ""classifier__min_samples_split"": 12}",1.127227,0.056185,0.017292,0.000486,0.990402,0.989324,0.991059,0.989943,0.989531,0.990052,0.000624,14
15,decision_tree,optuna,cicids2017,235490,30,5,1,15,COMPLETE,5.652791,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 15}",1.111338,0.022562,0.016879,0.000353,0.990201,0.990002,0.990686,0.989933,0.989423,0.990049,0.000409,15
26,decision_tree,optuna,cicids2017,235490,30,5,1,26,COMPLETE,5.907760,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 2}",1.162120,0.035816,0.016969,0.000437,0.989376,0.989239,0.991005,0.989247,0.990232,0.989820,0.000698,16
3,decision_tree,optuna,cicids2017,235490,30,5,1,3,COMPLETE,5.302591,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 3}",1.041888,0.122174,0.016741,0.000661,0.987520,0.988365,0.987705,0.988341,0.987981,0.987982,0.000337,17
6,decision_tree,optuna,cicids2017,235490,30,5,1,6,COMPLETE,4.914577,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 18}",0.963852,0.021406,0.017045,0.000088,0.987557,0.988167,0.987737,0.988341,0.987611,0.987883,0.000314,18
16,decision_tree,optuna,cicids2017,235490,30,5,1,16,COMPLETE,4.246320,"{""classifier__class_weight"": null, ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 20}",0.830923,0.010752,0.016065,0.000483,0.984249,0.986070,0.984638,0.984949,0.984816,0.984944,0.000610,19
7,decision_tree,optuna,cicids2017,235490,30,5,1,7,COMPLETE,4.329600,"{""classifier__class_weight"": null, ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 10}",0.847829,0.021266,0.016173,0.000703,0.984184,0.985869,0.984605,0.984680,0.984882,0.984844,0.000561,20
4,decision_tree,optuna,cicids2017,235490,30,5,1,4,COMPLETE,4.656533,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 12}",0.911504,0.024750,0.017594,0.002714,0.984108,0.982661,0.984764,0.980165,0.980792,0.982498,0.001795,21
29,decision_tree,optuna,cicids2017,235490,30,5,1,29,COMPLETE,4.516152,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 3}",0.884658,0.013350,0.016162,0.000416,0.984239,0.982565,0.984732,0.980131,0.980792,0.982492,0.001819,22
27,decision_tree,optuna,cicids2017,235490,30,5,1,27,COMPLETE,2.954072,"{""classifier__class_weight"": null, ""classifier__max_depth"": 5, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 5}",0.572303,0.005767,0.016076,0.000119,0.975360,0.975084,0.975498,0.974753,0.973427,0.974824,0.000744,23
5,decision_tree,optuna,cicids2017,235490,30,5,1,5,COMPLETE,2.989133,"{""classifier__class_weight"": null, ""classifier__max_depth"": 5, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 19}",0.579262,0.010907,0.016429,0.000879,0.975360,0.975084,0.975498,0.974684,0.973427,0.974811,0.000745,24
24,decision_tree,optuna,cicids2017,235490,30,5,1,24,COMPLETE,3.360702,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 5, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 6}",0.652123,0.044458,0.017364,0.001503,0.972307,0.976868,0.972979,0.972009,0.975443,0.973921,0.001905,25
14,decision_tree,optuna,cicids2017,235490,30,5,1,14,COMPLETE,3.160213,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 5, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 16}",0.613363,0.008632,0.016333,0.000308,0.972370,0.976868,0.972879,0.971946,0.975475,0.973908,0.001923,26
9,decision_tree,optuna,cicids2017,235490,30,5,1,9,COMPLETE,2.046350,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 16}",0.391931,0.008000,0.015389,0.000402,0.948007,0.949028,0.948294,0.948290,0.946118,0.947947,0.000975,27
2,decision_tree,optuna,cicids2017,235490,30,5,1,2,COMPLETE,2.075598,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20}",0.397516,0.019161,0.015572,0.000449,0.948007,0.949028,0.948294,0.948290,0.946118,0.947947,0.000975,27
0,decision_tree,optuna,cicids2017,235490,30,5,1,0,COMPLETE,2.291587,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 9}",0.438437,0.022671,0.017013,0.001332,0.942773,0.942970,0.942008,0.941595,0.941016,0.942072,0.000727,29
1,decision_tree,optuna,cicids2017,235490,30,5,1,1,COMPLETE,2.372893,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 17}",0.456953,0.028923,0.015604,0.000391,0.942773,0.942970,0.942008,0.941595,0.941016,0.942072,0.000727,29

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,decision_tree,optuna,cicids2017,235490,30,5,1,1,1.652865,0.058292,0.979154,0.992356,0.985711,0.998083,0.994719,0.996398,0.991054,0.994246,0.993537
1,decision_tree,optuna,cicids2017,235490,30,5,1,2,1.704455,0.050690,0.978432,0.992144,0.985240,0.998029,0.994533,0.996278,0.990759,0.994055,0.993338
2,decision_tree,optuna,cicids2017,235490,30,5,1,3,1.674994,0.052639,0.981820,0.991826,0.986798,0.997951,0.995408,0.996678,0.991738,0.994692,0.993617
3,decision_tree,optuna,cicids2017,235490,30,5,1,4,1.790989,0.046051,0.978612,0.990870,0.984703,0.997710,0.994586,0.996146,0.990424,0.993843,0.992728
4,decision_tree,optuna,cicids2017,235490,30,5,1,5,1.658315,0.062228,0.977116,0.992675,0.984834,0.998161,0.994188,0.996171,0.990502,0.993885,0.993431

Modelo: decision_tree | origem do treinamento: unsw_nb15

[I 2026-10-11 21:58:09,184] A new study created in memory with name: decision_tree_unsw_nb15
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:58:11,648] Trial 0 finished with value: 0.9160376185362888 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 9, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9160376185362888.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:58:13,880] Trial 1 finished with value: 0.9160376185362888 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 17, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9160376185362888.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:58:15,949] Trial 2 finished with value: 0.9300314134853387 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 2 with value: 0.9300314134853387.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:58:21,078] Trial 3 finished with value: 0.9798772173316331 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 3, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9798772173316331.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:58:25,835] Trial 4 finished with value: 0.9795611106762984 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 12, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9798772173316331.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:58:28,949] Trial 5 finished with value: 0.9645668197128167 and parameters: {'classifier__max_depth': 5, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9798772173316331.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:58:34,097] Trial 6 finished with value: 0.9798604223391285 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 18, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9798772173316331.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:58:38,447] Trial 7 finished with value: 0.9777482154978847 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 10, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9798772173316331.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:58:44,348] Trial 8 finished with value: 0.9794237361705846 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9798772173316331.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:58:46,398] Trial 9 finished with value: 0.9300314134853387 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 16, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9798772173316331.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:58:51,491] Trial 10 finished with value: 0.9798337255732488 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 2, 'classifier__min_samples_leaf': 8, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9798772173316331.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:58:54,491] Trial 11 finished with value: 0.9645804986080602 and parameters: {'classifier__max_depth': 5, 'classifier__min_samples_split': 8, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9798772173316331.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:58:59,639] Trial 12 finished with value: 0.9799319085013609 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 16, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9799319085013609.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:59:04,798] Trial 13 finished with value: 0.9799709620258132 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 17, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': None}. Best is trial 13 with value: 0.9799709620258132.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:59:09,963] Trial 14 finished with value: 0.979958304588042 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 18, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': None}. Best is trial 13 with value: 0.9799709620258132.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:59:16,224] Trial 15 finished with value: 0.9757338686385978 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 17, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': None}. Best is trial 13 with value: 0.9799709620258132.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:59:22,508] Trial 16 finished with value: 0.9750363297828478 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 11, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': None}. Best is trial 13 with value: 0.9799709620258132.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:59:27,724] Trial 17 finished with value: 0.9799249392450007 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 12, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': None}. Best is trial 13 with value: 0.9799709620258132.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:59:33,506] Trial 18 finished with value: 0.9800073507348511 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 18 with value: 0.9800073507348511.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:59:39,285] Trial 19 finished with value: 0.9800318847605765 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 18, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': 'balanced'}. Best is trial 19 with value: 0.9800318847605765.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:59:45,129] Trial 20 finished with value: 0.9798208997526932 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 18, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': 'balanced'}. Best is trial 19 with value: 0.9800318847605765.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:59:50,937] Trial 21 finished with value: 0.9796315988717683 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': 'balanced'}. Best is trial 19 with value: 0.9800318847605765.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:59:53,152] Trial 22 finished with value: 0.9160376185362888 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 15, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 19 with value: 0.9800318847605765.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 21:59:57,706] Trial 23 finished with value: 0.9792637903253502 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': 'balanced'}. Best is trial 19 with value: 0.9800318847605765.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:03,815] Trial 24 finished with value: 0.9786407530285871 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 12, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': None}. Best is trial 19 with value: 0.9800318847605765.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:09,611] Trial 25 finished with value: 0.9798251394442022 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 14, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': 'balanced'}. Best is trial 19 with value: 0.9800318847605765.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:14,206] Trial 26 finished with value: 0.9792421674269984 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 14, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': 'balanced'}. Best is trial 19 with value: 0.9800318847605765.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:19,350] Trial 27 finished with value: 0.9799053035419855 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 15, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': None}. Best is trial 19 with value: 0.9800318847605765.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:24,725] Trial 28 finished with value: 0.979913240102172 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': None}. Best is trial 19 with value: 0.9800318847605765.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:30,889] Trial 29 finished with value: 0.9800009950683005 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 15, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 19 with value: 0.9800318847605765.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
19,decision_tree,optuna,unsw_nb15,235490,30,5,1,19,COMPLETE,5.778974,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 18}",1.136425,0.052461,0.017103,0.000271,0.980764,0.980601,0.979494,0.979858,0.979442,0.980032,0.000553,1
18,decision_tree,optuna,unsw_nb15,235490,30,5,1,18,COMPLETE,5.781414,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 19}",1.136835,0.059882,0.017110,0.000541,0.980763,0.980663,0.979423,0.979920,0.979268,0.980007,0.000616,2
29,decision_tree,optuna,unsw_nb15,235490,30,5,1,29,COMPLETE,6.163609,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 15}",1.212771,0.046547,0.017472,0.000434,0.980663,0.980533,0.979928,0.979683,0.979198,0.980001,0.000543,3
13,decision_tree,optuna,unsw_nb15,235490,30,5,1,13,COMPLETE,5.158627,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 17}",1.012224,0.007755,0.017157,0.000468,0.980288,0.980812,0.979599,0.979268,0.979888,0.979971,0.000538,4
14,decision_tree,optuna,unsw_nb15,235490,30,5,1,14,COMPLETE,5.163946,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 18}",1.013603,0.010023,0.016849,0.000428,0.980288,0.980810,0.979568,0.979303,0.979823,0.979958,0.000536,5
12,decision_tree,optuna,unsw_nb15,235490,30,5,1,12,COMPLETE,5.147607,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 16}",1.010451,0.010528,0.016707,0.000483,0.980421,0.980846,0.979568,0.979065,0.979759,0.979932,0.000631,6
17,decision_tree,optuna,unsw_nb15,235490,30,5,1,17,COMPLETE,5.214991,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 12}",1.023729,0.014157,0.016905,0.000314,0.980253,0.980748,0.979669,0.979067,0.979888,0.979925,0.000564,7
28,decision_tree,optuna,unsw_nb15,235490,30,5,1,28,COMPLETE,5.374154,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 20}",1.054811,0.058988,0.017588,0.001046,0.980353,0.980880,0.979571,0.979201,0.979561,0.979913,0.000612,8
27,decision_tree,optuna,unsw_nb15,235490,30,5,1,27,COMPLETE,5.144151,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 15}",1.009610,0.010559,0.016629,0.000179,0.980255,0.980715,0.979568,0.979102,0.979888,0.979905,0.000555,9
3,decision_tree,optuna,unsw_nb15,235490,30,5,1,3,COMPLETE,5.128548,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 3}",1.006887,0.007135,0.016978,0.000384,0.980293,0.980684,0.979775,0.979032,0.979602,0.979877,0.000570,10
6,decision_tree,optuna,unsw_nb15,235490,30,5,1,6,COMPLETE,5.147626,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 18}",1.010951,0.005260,0.016707,0.000550,0.980294,0.980784,0.979420,0.979130,0.979674,0.979860,0.000601,11
10,decision_tree,optuna,unsw_nb15,235490,30,5,1,10,COMPLETE,5.092400,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 2}",0.999416,0.011477,0.016739,0.000296,0.980229,0.980852,0.979316,0.978967,0.979805,0.979834,0.000666,12
25,decision_tree,optuna,unsw_nb15,235490,30,5,1,25,COMPLETE,5.795889,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 14}",1.139915,0.053587,0.016943,0.000269,0.980185,0.980311,0.979747,0.979409,0.979474,0.979825,0.000366,13
20,decision_tree,optuna,unsw_nb15,235490,30,5,1,20,COMPLETE,5.843826,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 18}",1.149367,0.060955,0.017092,0.000347,0.980435,0.980383,0.979337,0.979573,0.979376,0.979821,0.000487,14
21,decision_tree,optuna,unsw_nb15,235490,30,5,1,21,COMPLETE,5.807253,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 19}",1.142141,0.046929,0.017000,0.000671,0.980294,0.980334,0.979124,0.979452,0.978954,0.979632,0.000580,15
4,decision_tree,optuna,unsw_nb15,235490,30,5,1,4,COMPLETE,4.756224,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 12}",0.932368,0.045262,0.016974,0.000480,0.979879,0.980116,0.979376,0.979214,0.979221,0.979561,0.000369,16
8,decision_tree,optuna,unsw_nb15,235490,30,5,1,8,COMPLETE,5.900164,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 19}",1.160847,0.049925,0.017121,0.000512,0.980036,0.980139,0.978782,0.978992,0.979170,0.979424,0.000556,17
23,decision_tree,optuna,unsw_nb15,235490,30,5,1,23,COMPLETE,4.553899,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 20}",0.891929,0.011355,0.016546,0.000255,0.979782,0.979864,0.978682,0.979154,0.978836,0.979264,0.000482,18
26,decision_tree,optuna,unsw_nb15,235490,30,5,1,26,COMPLETE,4.594007,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 14}",0.900187,0.015094,0.016331,0.000216,0.979653,0.979738,0.978928,0.979056,0.978836,0.979242,0.000377,19
24,decision_tree,optuna,unsw_nb15,235490,30,5,1,24,COMPLETE,6.108058,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 12}",1.201610,0.034314,0.017635,0.000390,0.979140,0.979429,0.978736,0.976906,0.978993,0.978641,0.000896,20
7,decision_tree,optuna,unsw_nb15,235490,30,5,1,7,COMPLETE,4.349642,"{""classifier__class_weight"": null, ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 10}",0.851119,0.011896,0.016879,0.000704,0.978268,0.977828,0.978804,0.976851,0.976990,0.977748,0.000745,21
15,decision_tree,optuna,unsw_nb15,235490,30,5,1,15,COMPLETE,6.260183,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 17}",1.232144,0.027528,0.017445,0.000370,0.976622,0.976394,0.975546,0.974340,0.975767,0.975734,0.000801,22
16,decision_tree,optuna,unsw_nb15,235490,30,5,1,16,COMPLETE,6.284154,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 11}",1.236931,0.039228,0.017557,0.000641,0.976163,0.975638,0.974495,0.974167,0.974718,0.975036,0.000746,23
11,decision_tree,optuna,unsw_nb15,235490,30,5,1,11,COMPLETE,2.999616,"{""classifier__class_weight"": null, ""classifier__max_depth"": 5, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 8}",0.581621,0.003367,0.015954,0.000207,0.964175,0.965483,0.963217,0.964928,0.965099,0.964580,0.000804,24
5,decision_tree,optuna,unsw_nb15,235490,30,5,1,5,COMPLETE,3.113029,"{""classifier__class_weight"": null, ""classifier__max_depth"": 5, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 19}",0.604566,0.028329,0.016120,0.000137,0.964175,0.965483,0.963217,0.964928,0.965031,0.964567,0.000795,25
2,decision_tree,optuna,unsw_nb15,235490,30,5,1,2,COMPLETE,2.068797,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20}",0.396124,0.004620,0.015751,0.000163,0.930200,0.930826,0.928867,0.930493,0.929772,0.930031,0.000678,26
9,decision_tree,optuna,unsw_nb15,235490,30,5,1,9,COMPLETE,2.049692,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 16}",0.392279,0.003166,0.015792,0.000184,0.930200,0.930826,0.928867,0.930493,0.929772,0.930031,0.000678,26
1,decision_tree,optuna,unsw_nb15,235490,30,5,1,1,COMPLETE,2.231334,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 17}",0.428085,0.010672,0.016325,0.000739,0.915520,0.917950,0.915161,0.916458,0.915098,0.916038,0.001073,28
0,decision_tree,optuna,unsw_nb15,235490,30,5,1,0,COMPLETE,2.461904,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 9}",0.473419,0.063578,0.017052,0.001734,0.915520,0.917950,0.915161,0.916458,0.915098,0.916038,0.001073,28
22,decision_tree,optuna,unsw_nb15,235490,30,5,1,22,COMPLETE,2.213969,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 15}",0.424651,0.007137,0.015845,0.000266,0.915520,0.917950,0.915161,0.916458,0.915098,0.916038,0.001073,28

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,decision_tree,optuna,unsw_nb15,235490,30,5,1,1,1.897563,0.055031,0.943434,0.996921,0.969440,0.999219,0.985058,0.992088,0.980764,0.987430,0.990990
1,decision_tree,optuna,unsw_nb15,235490,30,5,1,2,1.925426,0.057668,0.943227,0.996603,0.969181,0.999139,0.985005,0.992021,0.980601,0.987324,0.990804
2,decision_tree,optuna,unsw_nb15,235490,30,5,1,3,2.039435,0.046915,0.937992,0.998832,0.967457,0.999703,0.983492,0.991531,0.979494,0.986560,0.991162
3,decision_tree,optuna,unsw_nb15,235490,30,5,1,4,1.636650,0.051534,0.939994,0.997771,0.968021,0.999434,0.984076,0.991695,0.979858,0.986815,0.990923
4,decision_tree,optuna,unsw_nb15,235490,30,5,1,5,1.794684,0.051803,0.939037,0.997452,0.967363,0.999353,0.983810,0.991521,0.979442,0.986539,0.990631

Modelo: decision_tree | origem do treinamento: iot23

[I 2026-10-11 22:00:37,271] A new study created in memory with name: decision_tree_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:38,648] Trial 0 finished with value: 0.9899831590464239 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 9, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9899831590464239.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:39,953] Trial 1 finished with value: 0.9899765229719565 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 17, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9899831590464239.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:41,064] Trial 2 finished with value: 0.9933081515563748 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 2 with value: 0.9933081515563748.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:42,797] Trial 3 finished with value: 0.9976922288757049 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 3, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9976922288757049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:44,759] Trial 4 finished with value: 0.9953422188696145 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 12, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9976922288757049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:46,265] Trial 5 finished with value: 0.996863026426541 and parameters: {'classifier__max_depth': 5, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9976922288757049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:48,039] Trial 6 finished with value: 0.997639142152136 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 18, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9976922288757049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:49,817] Trial 7 finished with value: 0.9976255664395959 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 10, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9976922288757049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:52,184] Trial 8 finished with value: 0.9949874847171666 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9976922288757049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:53,412] Trial 9 finished with value: 0.9933081515563748 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 16, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9976922288757049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:55,437] Trial 10 finished with value: 0.997645864024246 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 2, 'classifier__min_samples_leaf': 8, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9976922288757049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:57,368] Trial 11 finished with value: 0.9976326245505927 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 2, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9976922288757049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:00:59,274] Trial 12 finished with value: 0.9976393170505119 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 2, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9976922288757049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:01,188] Trial 13 finished with value: 0.9975926993776518 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 4, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9976922288757049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:03,205] Trial 14 finished with value: 0.9977320883532448 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 8, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9977320883532448.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:05,257] Trial 15 finished with value: 0.9977455530921571 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 14, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': None}. Best is trial 15 with value: 0.9977455530921571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:07,192] Trial 16 finished with value: 0.9977056283022577 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 15, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': None}. Best is trial 15 with value: 0.9977455530921571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:09,242] Trial 17 finished with value: 0.9977255605990167 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 8, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': None}. Best is trial 15 with value: 0.9977455530921571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:11,329] Trial 18 finished with value: 0.9977522823986531 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 10, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': None}. Best is trial 18 with value: 0.9977522823986531.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:13,411] Trial 19 finished with value: 0.9977655030699861 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 12, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': None}. Best is trial 19 with value: 0.9977655030699861.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:15,350] Trial 20 finished with value: 0.9976323983622937 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 13, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 19 with value: 0.9977655030699861.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:17,289] Trial 21 finished with value: 0.9977058605024111 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 13, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': None}. Best is trial 19 with value: 0.9977655030699861.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:18,436] Trial 22 finished with value: 0.9933213543381824 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 18, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': None}. Best is trial 19 with value: 0.9977655030699861.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:20,272] Trial 23 finished with value: 0.9976792914576145 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 7, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': None}. Best is trial 19 with value: 0.9977655030699861.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:22,545] Trial 24 finished with value: 0.9950533713732577 and parameters: {'classifier__max_depth': 30, 'classifier__min_samples_split': 13, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': 'balanced'}. Best is trial 19 with value: 0.9977655030699861.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:24,501] Trial 25 finished with value: 0.99774562175681 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 9, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': None}. Best is trial 19 with value: 0.9977655030699861.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:26,387] Trial 26 finished with value: 0.9977389164744264 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 7, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': None}. Best is trial 19 with value: 0.9977655030699861.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:28,146] Trial 27 finished with value: 0.9976460143442486 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 7, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': None}. Best is trial 19 with value: 0.9977655030699861.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:30,092] Trial 28 finished with value: 0.9949939833373147 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 16, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': 'balanced'}. Best is trial 19 with value: 0.9977655030699861.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:32,043] Trial 29 finished with value: 0.9950072208279674 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 11, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': 'balanced'}. Best is trial 19 with value: 0.9977655030699861.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
19,decision_tree,optuna,iot23,235490,30,5,1,19,COMPLETE,2.080643,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 12}",0.396180,0.022519,0.017292,0.000327,0.997905,0.997405,0.997372,0.998239,0.997906,0.997766,0.000331,1
18,decision_tree,optuna,iot23,235490,30,5,1,18,COMPLETE,2.087012,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 10}",0.396763,0.047314,0.018161,0.001075,0.997872,0.997306,0.997406,0.998239,0.997939,0.997752,0.000348,2
25,decision_tree,optuna,iot23,235490,30,5,1,25,COMPLETE,1.955245,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 9}",0.370380,0.025579,0.018110,0.000866,0.997872,0.997306,0.997439,0.998205,0.997906,0.997746,0.000329,3
15,decision_tree,optuna,iot23,235490,30,5,1,15,COMPLETE,2.051632,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 14}",0.390940,0.037417,0.016979,0.000545,0.997740,0.997405,0.997439,0.998238,0.997906,0.997746,0.000309,4
26,decision_tree,optuna,iot23,235490,30,5,1,26,COMPLETE,1.885504,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 7}",0.356247,0.033318,0.018438,0.002738,0.997872,0.997306,0.997439,0.998239,0.997839,0.997739,0.000333,5
14,decision_tree,optuna,iot23,235490,30,5,1,14,COMPLETE,2.016064,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 8}",0.383784,0.041660,0.017011,0.000451,0.997806,0.997405,0.997439,0.998172,0.997839,0.997732,0.000284,6
17,decision_tree,optuna,iot23,235490,30,5,1,17,COMPLETE,2.049048,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 8}",0.389925,0.025165,0.017224,0.000299,0.997740,0.997273,0.997505,0.998205,0.997905,0.997726,0.000321,7
21,decision_tree,optuna,iot23,235490,30,5,1,21,COMPLETE,1.938711,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 13}",0.368454,0.023486,0.016867,0.000282,0.997872,0.997273,0.997372,0.998172,0.997839,0.997706,0.000335,8
16,decision_tree,optuna,iot23,235490,30,5,1,16,COMPLETE,1.934338,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 15}",0.367682,0.036408,0.016737,0.000253,0.997839,0.997273,0.997406,0.998205,0.997806,0.997706,0.000333,9
3,decision_tree,optuna,iot23,235490,30,5,1,3,COMPLETE,1.732215,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 3}",0.327724,0.017438,0.016794,0.000714,0.997772,0.997405,0.997339,0.998205,0.997739,0.997692,0.000309,10
23,decision_tree,optuna,iot23,235490,30,5,1,23,COMPLETE,1.835011,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 7}",0.347716,0.013880,0.016818,0.000463,0.997772,0.997373,0.997339,0.998139,0.997773,0.997679,0.000296,11
27,decision_tree,optuna,iot23,235490,30,5,1,27,COMPLETE,1.758684,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 7}",0.332588,0.020552,0.016940,0.000456,0.997772,0.997439,0.997273,0.998072,0.997674,0.997646,0.000276,12
10,decision_tree,optuna,iot23,235490,30,5,1,10,COMPLETE,2.025005,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 2}",0.385768,0.046677,0.016855,0.000572,0.997772,0.997406,0.997306,0.998072,0.997673,0.997646,0.000273,13
12,decision_tree,optuna,iot23,235490,30,5,1,12,COMPLETE,1.905812,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 2}",0.360657,0.029156,0.017895,0.001587,0.997772,0.997339,0.997306,0.998139,0.997640,0.997639,0.000306,14
6,decision_tree,optuna,iot23,235490,30,5,1,6,COMPLETE,1.773973,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 18}",0.336038,0.022624,0.016826,0.000385,0.997806,0.997339,0.997306,0.998072,0.997673,0.997639,0.000289,15
11,decision_tree,optuna,iot23,235490,30,5,1,11,COMPLETE,1.929737,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 2}",0.366490,0.036912,0.017058,0.000411,0.997772,0.997406,0.997273,0.998072,0.997640,0.997633,0.000281,16
20,decision_tree,optuna,iot23,235490,30,5,1,20,COMPLETE,1.938919,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 13}",0.368384,0.014459,0.017001,0.000161,0.997739,0.997305,0.997306,0.998172,0.997640,0.997632,0.000321,17
7,decision_tree,optuna,iot23,235490,30,5,1,7,COMPLETE,1.776797,"{""classifier__class_weight"": null, ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 10}",0.336604,0.014792,0.016863,0.000592,0.997739,0.997272,0.997272,0.998106,0.997739,0.997626,0.000318,18
13,decision_tree,optuna,iot23,235490,30,5,1,13,COMPLETE,1.913887,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 4}",0.362314,0.034416,0.018065,0.002116,0.997739,0.997339,0.997239,0.998039,0.997607,0.997593,0.000287,19
5,decision_tree,optuna,iot23,235490,30,5,1,5,COMPLETE,1.505036,"{""classifier__class_weight"": null, ""classifier__max_depth"": 5, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 19}",0.282721,0.004347,0.016304,0.000420,0.997043,0.996443,0.996510,0.997210,0.997109,0.996863,0.000321,20
4,decision_tree,optuna,iot23,235490,30,5,1,4,COMPLETE,1.961632,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 12}",0.373773,0.023361,0.016580,0.000592,0.995639,0.994947,0.995439,0.995605,0.995081,0.995342,0.000280,21
24,decision_tree,optuna,iot23,235490,30,5,1,24,COMPLETE,2.272757,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 13}",0.433979,0.054866,0.018050,0.000878,0.995671,0.994718,0.995011,0.995376,0.994491,0.995053,0.000428,22
29,decision_tree,optuna,iot23,235490,30,5,1,29,COMPLETE,1.950415,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 11}",0.370971,0.027016,0.016821,0.000443,0.995408,0.994784,0.994944,0.995441,0.994458,0.995007,0.000375,23
28,decision_tree,optuna,iot23,235490,30,5,1,28,COMPLETE,1.944716,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 16}",0.369660,0.025560,0.016951,0.000346,0.995539,0.994488,0.995076,0.995343,0.994524,0.994994,0.000425,24
8,decision_tree,optuna,iot23,235490,30,5,1,8,COMPLETE,2.366705,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 19}",0.454080,0.019179,0.017317,0.000447,0.995539,0.994586,0.995174,0.995408,0.994230,0.994987,0.000500,25
22,decision_tree,optuna,iot23,235490,30,5,1,22,COMPLETE,1.146567,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 18}",0.211118,0.007140,0.015672,0.000146,0.993252,0.992917,0.992698,0.993491,0.994250,0.993321,0.000538,26
9,decision_tree,optuna,iot23,235490,30,5,1,9,COMPLETE,1.227568,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 16}",0.227461,0.004800,0.016060,0.000256,0.993252,0.992917,0.992698,0.993491,0.994184,0.993308,0.000515,27
2,decision_tree,optuna,iot23,235490,30,5,1,2,COMPLETE,1.111047,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20}",0.204364,0.006760,0.015780,0.000275,0.993252,0.992917,0.992698,0.993491,0.994184,0.993308,0.000515,27
0,decision_tree,optuna,iot23,235490,30,5,1,0,COMPLETE,1.374574,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 9}",0.256657,0.016729,0.016267,0.000793,0.990744,0.990998,0.990576,0.988795,0.988801,0.989983,0.000977,29
1,decision_tree,optuna,iot23,235490,30,5,1,1,COMPLETE,1.303998,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 17}",0.243304,0.010966,0.015560,0.000230,0.990744,0.990998,0.990576,0.988795,0.988768,0.989977,0.000985,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,decision_tree,optuna,iot23,235490,30,5,1,1,0.405194,0.047655,0.999573,0.993736,0.996646,0.998436,0.999894,0.999165,0.997905,0.998662,0.996815
1,decision_tree,optuna,iot23,235490,30,5,1,2,0.442160,0.046773,0.999358,0.992356,0.995845,0.998092,0.999841,0.998966,0.997405,0.998344,0.996098
2,decision_tree,optuna,iot23,235490,30,5,1,3,0.560365,0.064892,0.999252,0.992357,0.995792,0.998092,0.999814,0.998953,0.997372,0.998323,0.996085
3,decision_tree,optuna,iot23,235490,30,5,1,4,0.603988,0.051433,0.999467,0.994904,0.997180,0.998727,0.999867,0.999297,0.998239,0.998875,0.997386
4,decision_tree,optuna,iot23,235490,30,5,1,5,0.513073,0.065454,0.999360,0.993949,0.996647,0.998489,0.999841,0.999165,0.997906,0.998662,0.996895

Modelo: decision_tree | origem do treinamento: cicids2017_unsw_nb15

[I 2026-10-11 22:01:35,564] A new study created in memory with name: decision_tree_cicids2017_unsw_nb15
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:40,742] Trial 0 finished with value: 0.7909169950851065 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 9, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.7909169950851065.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:45,711] Trial 1 finished with value: 0.7909169950851065 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 17, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.7909169950851065.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:01:50,361] Trial 2 finished with value: 0.7587234484059989 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 0 with value: 0.7909169950851065.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:02:01,376] Trial 3 finished with value: 0.9811424653597965 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 3, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9811424653597965.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:02:11,447] Trial 4 finished with value: 0.9765436277272681 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 12, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9811424653597965.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:02:18,073] Trial 5 finished with value: 0.9426214796711122 and parameters: {'classifier__max_depth': 5, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9811424653597965.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:02:29,205] Trial 6 finished with value: 0.9811266469319472 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 18, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9811424653597965.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:02:39,190] Trial 7 finished with value: 0.9783003942670334 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 10, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9811424653597965.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:02:53,734] Trial 8 finished with value: 0.983368845272266 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 8 with value: 0.983368845272266.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:02:58,350] Trial 9 finished with value: 0.7587234484059989 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 16, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': None}. Best is trial 8 with value: 0.983368845272266.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:03:13,867] Trial 10 finished with value: 0.9832704572252258 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 8 with value: 0.983368845272266.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:03:28,754] Trial 11 finished with value: 0.9833452160471927 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 8 with value: 0.983368845272266.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:03:43,457] Trial 12 finished with value: 0.9834040940626062 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 15, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9834040940626062.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:03:57,959] Trial 13 finished with value: 0.9831158293992341 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 13, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9834040940626062.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:04:11,674] Trial 14 finished with value: 0.9825919032486775 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 11, 'classifier__min_samples_leaf': 8, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9834040940626062.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:04:26,122] Trial 15 finished with value: 0.983334811936156 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 14, 'classifier__min_samples_leaf': 8, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9834040940626062.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:04:39,940] Trial 16 finished with value: 0.9825956733378041 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 17, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9834040940626062.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:04:54,660] Trial 17 finished with value: 0.983241148518341 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 13, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9834040940626062.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:05:06,591] Trial 18 finished with value: 0.980256631876218 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 7, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9834040940626062.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:05:16,637] Trial 19 finished with value: 0.9762907245174226 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 15, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9834040940626062.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:05:23,887] Trial 20 finished with value: 0.916568037983468 and parameters: {'classifier__max_depth': 5, 'classifier__min_samples_split': 17, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9834040940626062.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:05:38,479] Trial 21 finished with value: 0.9826857390274537 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 8, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9834040940626062.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:05:48,672] Trial 22 finished with value: 0.9762171619306563 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9834040940626062.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:06:03,295] Trial 23 finished with value: 0.9833452160471927 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9834040940626062.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:06:17,666] Trial 24 finished with value: 0.9816367085294864 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 16, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9834040940626062.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:06:32,307] Trial 25 finished with value: 0.9833574680437158 and parameters: {'classifier__max_depth': 30, 'classifier__min_samples_split': 8, 'classifier__min_samples_leaf': 8, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9834040940626062.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:06:47,036] Trial 26 finished with value: 0.9834581373714235 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 7, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 26 with value: 0.9834581373714235.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:07:01,486] Trial 27 finished with value: 0.9834581373714235 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 6, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 26 with value: 0.9834581373714235.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:07:16,043] Trial 28 finished with value: 0.9834581373714235 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 2, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 26 with value: 0.9834581373714235.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:07:30,897] Trial 29 finished with value: 0.9834581373714235 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 4, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 26 with value: 0.9834581373714235.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
27,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,27,COMPLETE,14.449082,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 6}",2.855275,0.040449,0.031135,0.000596,0.982578,0.983111,0.984851,0.983923,0.982828,0.983458,0.000830,1
26,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,26,COMPLETE,14.729087,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 7}",2.911058,0.061715,0.031342,0.000911,0.982578,0.983111,0.984851,0.983923,0.982828,0.983458,0.000830,1
29,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,29,COMPLETE,14.853053,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 4}",2.936255,0.134495,0.030902,0.000351,0.982578,0.983111,0.984851,0.983923,0.982828,0.983458,0.000830,1
28,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,28,COMPLETE,14.556876,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 2}",2.877234,0.045076,0.030716,0.000092,0.982578,0.983111,0.984851,0.983923,0.982828,0.983458,0.000830,1
12,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,12,COMPLETE,14.703303,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 15}",2.905668,0.079322,0.031519,0.000331,0.982477,0.983099,0.984815,0.983975,0.982655,0.983404,0.000875,5
8,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,8,COMPLETE,14.543360,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 19}",2.874818,0.064486,0.030963,0.000119,0.982605,0.983165,0.984599,0.983786,0.982689,0.983369,0.000745,6
25,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,25,COMPLETE,14.640530,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 8}",2.893711,0.081939,0.030883,0.000213,0.982526,0.983108,0.984527,0.984097,0.982530,0.983357,0.000819,7
11,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,11,COMPLETE,14.886049,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 20}",2.941777,0.129342,0.032055,0.002621,0.982593,0.983134,0.984550,0.983823,0.982626,0.983345,0.000749,8
23,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,23,COMPLETE,14.622345,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 20}",2.890280,0.062392,0.030775,0.000118,0.982593,0.983134,0.984550,0.983823,0.982626,0.983345,0.000749,8
15,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,15,COMPLETE,14.447892,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 14}",2.855161,0.071096,0.031125,0.000259,0.982412,0.983077,0.984559,0.984065,0.982562,0.983335,0.000842,10
10,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,10,COMPLETE,15.516108,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 19}",3.068692,0.093602,0.031086,0.000215,0.982601,0.983200,0.984764,0.983671,0.982116,0.983270,0.000914,11
17,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,17,COMPLETE,14.719311,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 13}",2.908942,0.039903,0.031437,0.000407,0.982560,0.983112,0.984715,0.983393,0.982426,0.983241,0.000817,12
13,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,13,COMPLETE,14.500902,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 13}",2.865795,0.040561,0.031154,0.000550,0.982559,0.983487,0.984144,0.983339,0.982050,0.983116,0.000733,13
21,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,21,COMPLETE,14.591964,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 20}",2.883634,0.138530,0.031387,0.000753,0.981578,0.982560,0.983747,0.983490,0.982053,0.982686,0.000826,14
16,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,16,COMPLETE,13.816999,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 17}",2.729437,0.038118,0.030683,0.000363,0.981761,0.982685,0.983473,0.983057,0.982003,0.982596,0.000639,15
14,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,14,COMPLETE,13.714334,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 11}",2.708800,0.052527,0.030655,0.000448,0.981521,0.982240,0.983541,0.983505,0.982152,0.982592,0.000800,16
24,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,24,COMPLETE,14.369467,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 16}",2.839158,0.055204,0.031121,0.000126,0.980520,0.981577,0.982900,0.982222,0.980965,0.981637,0.000853,17
3,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,3,COMPLETE,11.014060,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 3}",2.170455,0.021230,0.029679,0.000204,0.980613,0.981516,0.981590,0.981243,0.980751,0.981142,0.000396,18
6,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,6,COMPLETE,11.131243,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 18}",2.192016,0.014349,0.031276,0.001699,0.980589,0.981348,0.981638,0.981193,0.980864,0.981127,0.000367,19
18,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,18,COMPLETE,11.931364,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 7}",2.353428,0.020275,0.029498,0.000183,0.977752,0.980622,0.981063,0.981585,0.980261,0.980257,0.001328,20
7,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,7,COMPLETE,9.984698,"{""classifier__class_weight"": null, ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 10}",1.964508,0.170901,0.029532,0.000462,0.977935,0.978324,0.978966,0.978465,0.977812,0.978300,0.000411,21
4,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,4,COMPLETE,10.070768,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 12}",1.982392,0.013676,0.028978,0.000270,0.973567,0.976391,0.978028,0.978359,0.976373,0.976544,0.001698,22
19,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,19,COMPLETE,10.044793,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 15}",1.976400,0.022991,0.029181,0.000455,0.973332,0.976329,0.977675,0.978138,0.975979,0.976291,0.001684,23
22,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,22,COMPLETE,10.192525,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 20}",2.005210,0.027972,0.029377,0.000500,0.973187,0.976362,0.977533,0.978137,0.975867,0.976217,0.001717,24
5,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,5,COMPLETE,6.625608,"{""classifier__class_weight"": null, ""classifier__max_depth"": 5, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 19}",1.293774,0.011084,0.028547,0.000317,0.941692,0.943260,0.943465,0.943584,0.941106,0.942621,0.001020,25
20,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,20,COMPLETE,7.249618,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 5, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 17}",1.417831,0.035515,0.028681,0.000308,0.912135,0.920619,0.915733,0.915659,0.918694,0.916568,0.002902,26
1,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,1,COMPLETE,4.967919,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 17}",0.962570,0.020918,0.028342,0.000427,0.790075,0.792010,0.791652,0.790628,0.790221,0.790917,0.000776,27
0,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,0,COMPLETE,5.175483,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 9}",1.003707,0.041629,0.028602,0.000297,0.790075,0.792010,0.791652,0.790628,0.790221,0.790917,0.000776,27
9,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,9,COMPLETE,4.615672,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 16}",0.892182,0.011347,0.028134,0.000408,0.759308,0.760504,0.758410,0.758168,0.757227,0.758723,0.001110,29
2,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,2,COMPLETE,4.650044,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20}",0.899628,0.010655,0.027672,0.000146,0.759308,0.760504,0.758410,0.758168,0.757227,0.758723,0.001110,29

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,1,3.703747,0.095525,0.952303,0.993099,0.972273,0.998256,0.987566,0.992882,0.982578,0.988673,0.990333
1,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,2,4.010554,0.084282,0.953582,0.993471,0.973118,0.998351,0.987911,0.993103,0.983111,0.989023,0.990691
2,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,3,3.996091,0.085293,0.956988,0.995541,0.975884,0.998874,0.988813,0.993818,0.984851,0.990159,0.992177
3,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,4,4.282763,0.076529,0.955278,0.994321,0.974408,0.998565,0.988362,0.993437,0.983923,0.989554,0.991341
4,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,5,4.042099,0.099310,0.951241,0.995117,0.972684,0.998765,0.987247,0.992973,0.982828,0.988821,0.991182

Modelo: decision_tree | origem do treinamento: cicids2017_iot23

[I 2026-10-11 22:07:46,588] A new study created in memory with name: decision_tree_cicids2017_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:07:50,438] Trial 0 finished with value: 0.9601719899785482 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 9, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9601719899785482.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:07:54,324] Trial 1 finished with value: 0.9601719899785482 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 17, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9601719899785482.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:07:57,859] Trial 2 finished with value: 0.9372210879040457 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9601719899785482.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:08:06,128] Trial 3 finished with value: 0.9910947918934812 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 3, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9910947918934812.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:08:13,332] Trial 4 finished with value: 0.9879041558953692 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 12, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9910947918934812.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:08:18,351] Trial 5 finished with value: 0.9813287702439413 and parameters: {'classifier__max_depth': 5, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9910947918934812.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:08:26,802] Trial 6 finished with value: 0.9909716903475954 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 18, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9910947918934812.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:08:33,877] Trial 7 finished with value: 0.9893764870842263 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 10, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9910947918934812.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:08:44,350] Trial 8 finished with value: 0.9921970680878168 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 8 with value: 0.9921970680878168.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:08:47,876] Trial 9 finished with value: 0.9372210879040457 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 16, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': None}. Best is trial 8 with value: 0.9921970680878168.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:08:58,447] Trial 10 finished with value: 0.9921881723754978 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 8 with value: 0.9921970680878168.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:09:08,860] Trial 11 finished with value: 0.9922168845748592 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9922168845748592.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:09:19,406] Trial 12 finished with value: 0.9923239821106155 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 15, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9923239821106155.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:09:29,932] Trial 13 finished with value: 0.9921862821110242 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 13, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9923239821106155.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:09:35,244] Trial 14 finished with value: 0.9655389168290416 and parameters: {'classifier__max_depth': 5, 'classifier__min_samples_split': 11, 'classifier__min_samples_leaf': 8, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9923239821106155.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:09:45,828] Trial 15 finished with value: 0.9922800402377252 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 14, 'classifier__min_samples_leaf': 8, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9923239821106155.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:09:56,283] Trial 16 finished with value: 0.9922767808449038 and parameters: {'classifier__max_depth': 30, 'classifier__min_samples_split': 15, 'classifier__min_samples_leaf': 8, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9923239821106155.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:10:06,833] Trial 17 finished with value: 0.9922847413057962 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 8, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9923239821106155.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:10:17,318] Trial 18 finished with value: 0.9922800402377252 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 4, 'classifier__min_samples_leaf': 8, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9923239821106155.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:10:28,101] Trial 19 finished with value: 0.9934418271428644 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 7, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': None}. Best is trial 19 with value: 0.9934418271428644.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:10:38,973] Trial 20 finished with value: 0.9936002099222441 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 8, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': None}. Best is trial 20 with value: 0.9936002099222441.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:10:49,713] Trial 21 finished with value: 0.9936031908516911 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 7, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': None}. Best is trial 21 with value: 0.9936031908516911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:11:00,409] Trial 22 finished with value: 0.9925998153656774 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 8, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 21 with value: 0.9936031908516911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:11:11,038] Trial 23 finished with value: 0.993488430650593 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 5, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': None}. Best is trial 21 with value: 0.9936031908516911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:11:21,819] Trial 24 finished with value: 0.9935745189437142 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 7, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': None}. Best is trial 21 with value: 0.9936031908516911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:11:32,370] Trial 25 finished with value: 0.9935984579031363 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 10, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': None}. Best is trial 21 with value: 0.9936031908516911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:11:43,005] Trial 26 finished with value: 0.9935984579031363 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 10, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': None}. Best is trial 21 with value: 0.9936031908516911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:11:53,660] Trial 27 finished with value: 0.9935007092767222 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 10, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': None}. Best is trial 21 with value: 0.9936031908516911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:11:57,158] Trial 28 finished with value: 0.9372210879040457 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 13, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': None}. Best is trial 21 with value: 0.9936031908516911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:12:07,801] Trial 29 finished with value: 0.9935935938094834 and parameters: {'classifier__max_depth': 20, 'classifier__min_samples_split': 13, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': None}. Best is trial 21 with value: 0.9936031908516911.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
21,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,21,COMPLETE,10.739020,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 7}",2.114410,0.023398,0.030179,0.000406,0.993800,0.993601,0.993762,0.993400,0.993453,0.993603,0.000160,1
20,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,20,COMPLETE,10.871735,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 8}",2.140699,0.030732,0.030394,0.000885,0.993716,0.993635,0.993813,0.993500,0.993336,0.993600,0.000167,2
25,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,25,COMPLETE,10.550718,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10}",2.076663,0.027104,0.030153,0.000443,0.993566,0.993570,0.993984,0.993435,0.993438,0.993598,0.000202,3
26,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,26,COMPLETE,10.634085,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 10}",2.092977,0.034958,0.030530,0.000404,0.993566,0.993570,0.993984,0.993435,0.993438,0.993598,0.000202,3
29,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,29,COMPLETE,10.642570,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 13}",2.094902,0.026312,0.030303,0.000206,0.993502,0.993587,0.993951,0.993653,0.993274,0.993594,0.000220,5
24,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,24,COMPLETE,10.780969,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 7}",2.122757,0.028301,0.030005,0.000373,0.993778,0.993534,0.993728,0.993298,0.993535,0.993575,0.000170,6
27,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,27,COMPLETE,10.654759,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 10}",2.096783,0.023955,0.030903,0.000846,0.993517,0.993453,0.993899,0.993165,0.993470,0.993501,0.000235,7
23,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,23,COMPLETE,10.628182,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 5}",2.092235,0.034329,0.030059,0.000303,0.993666,0.993500,0.993796,0.993165,0.993315,0.993488,0.000228,8
19,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,19,COMPLETE,10.782881,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 7}",2.122594,0.040762,0.030630,0.000764,0.993816,0.993187,0.993781,0.993085,0.993340,0.993442,0.000303,9
22,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,22,COMPLETE,10.695514,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 8}",2.105225,0.052119,0.030633,0.000216,0.992854,0.992627,0.993150,0.992332,0.992036,0.992600,0.000390,10
12,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,12,COMPLETE,10.544902,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 15}",2.075436,0.054174,0.030265,0.000261,0.992564,0.992112,0.992964,0.992210,0.991771,0.992324,0.000408,11
17,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,17,COMPLETE,10.549344,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 8}",2.076533,0.054983,0.030112,0.000352,0.992548,0.992112,0.992799,0.992211,0.991754,0.992285,0.000361,12
18,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,18,COMPLETE,10.483651,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 4}",2.062949,0.050967,0.030474,0.000628,0.992402,0.991885,0.992753,0.992457,0.991904,0.992280,0.000337,13
15,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,15,COMPLETE,10.583663,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 14}",2.082854,0.057003,0.030657,0.000755,0.992402,0.991885,0.992753,0.992457,0.991904,0.992280,0.000337,13
16,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,16,COMPLETE,10.454860,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 15}",2.057387,0.059728,0.030283,0.000235,0.992402,0.991885,0.992753,0.992457,0.991887,0.992277,0.000340,15
11,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,11,COMPLETE,10.412601,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 20}",2.049078,0.055073,0.030241,0.000299,0.992533,0.991883,0.992817,0.992162,0.991690,0.992217,0.000413,16
8,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,8,COMPLETE,10.473028,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 19}",2.061109,0.061441,0.030728,0.000537,0.992597,0.991883,0.992670,0.992162,0.991673,0.992197,0.000389,17
10,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,10,COMPLETE,10.570012,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 19}",2.080403,0.035808,0.030365,0.000533,0.992528,0.991799,0.992661,0.992172,0.991781,0.992188,0.000363,18
13,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,13,COMPLETE,10.526112,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 13}",2.071596,0.040308,0.030276,0.000165,0.992667,0.991983,0.992590,0.991999,0.991693,0.992186,0.000378,19
3,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,3,COMPLETE,8.268466,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 3}",1.622061,0.026129,0.028740,0.000494,0.991662,0.990743,0.992012,0.990476,0.990581,0.991095,0.000622,20
6,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,6,COMPLETE,8.449752,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 18}",1.658029,0.098089,0.029086,0.000881,0.991545,0.990660,0.991830,0.990460,0.990363,0.990972,0.000599,21
7,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,7,COMPLETE,7.074227,"{""classifier__class_weight"": null, ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 10}",1.383563,0.038877,0.028486,0.000294,0.990102,0.988976,0.990144,0.988656,0.989004,0.989376,0.000622,22
4,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,4,COMPLETE,7.204080,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 12}",1.409420,0.013010,0.028682,0.000424,0.987646,0.987514,0.988272,0.989174,0.986915,0.987904,0.000768,23
5,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,5,COMPLETE,5.018692,"{""classifier__class_weight"": null, ""classifier__max_depth"": 5, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 19}",0.973102,0.026282,0.027899,0.000182,0.981695,0.981625,0.981902,0.980893,0.980530,0.981329,0.000525,24
14,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,14,COMPLETE,5.311065,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 5, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 11}",1.030783,0.022271,0.028151,0.000352,0.964744,0.965929,0.967008,0.964778,0.965235,0.965539,0.000850,25
0,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,0,COMPLETE,3.848250,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 9}",0.738812,0.015003,0.027957,0.000308,0.960185,0.960497,0.961344,0.959455,0.959378,0.960172,0.000725,26
1,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,1,COMPLETE,3.885189,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 17}",0.744633,0.011999,0.029704,0.002926,0.960185,0.960497,0.961344,0.959455,0.959378,0.960172,0.000725,26
2,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,2,COMPLETE,3.534203,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20}",0.676187,0.005740,0.027856,0.000293,0.937721,0.936781,0.938958,0.935753,0.936892,0.937221,0.001070,28
9,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,9,COMPLETE,3.525813,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 16}",0.674741,0.008537,0.027675,0.000230,0.937721,0.936781,0.938958,0.935753,0.936892,0.937221,0.001070,28
28,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,28,COMPLETE,3.497267,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 13}",0.668008,0.005314,0.028016,0.000396,0.937721,0.936781,0.938958,0.935753,0.936892,0.937221,0.001070,28

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,1,3.275585,0.078003,0.989294,0.990870,0.990081,0.997717,0.997319,0.997518,0.993800,0.996030,0.994094
1,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,2,3.053035,0.089943,0.988924,0.990604,0.989763,0.997650,0.997227,0.997438,0.993601,0.995902,0.993915
2,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,3,3.314113,0.080008,0.990281,0.989756,0.990019,0.997439,0.997572,0.997505,0.993762,0.996008,0.993664
3,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,4,3.436006,0.076638,0.989074,0.989809,0.989441,0.997452,0.997266,0.997359,0.993400,0.995775,0.993538
4,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,5,3.078758,0.080891,0.988454,0.990605,0.989528,0.997650,0.997107,0.997378,0.993453,0.995807,0.993856

Modelo: decision_tree | origem do treinamento: unsw_nb15_iot23

[I 2026-10-11 22:12:16,692] A new study created in memory with name: decision_tree_unsw_nb15_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:12:20,671] Trial 0 finished with value: 0.8625549726761591 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 9, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.8625549726761591.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:12:24,630] Trial 1 finished with value: 0.8625549726761591 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 17, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.8625549726761591.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:12:28,269] Trial 2 finished with value: 0.8733550679997295 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 20, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 2 with value: 0.8733550679997295.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:12:37,014] Trial 3 finished with value: 0.9873663867133595 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 3, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9873663867133595.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:12:44,164] Trial 4 finished with value: 0.985281661181095 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 12, 'classifier__min_samples_leaf': 2, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9873663867133595.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:12:49,481] Trial 5 finished with value: 0.9278848663117817 and parameters: {'classifier__max_depth': 5, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9873663867133595.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:12:57,589] Trial 6 finished with value: 0.9873591792792942 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 18, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9873663867133595.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:13:04,603] Trial 7 finished with value: 0.9825969771469033 and parameters: {'classifier__max_depth': 8, 'classifier__min_samples_split': 10, 'classifier__min_samples_leaf': 6, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9873663867133595.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:13:13,710] Trial 8 finished with value: 0.9870471066060803 and parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 19, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9873663867133595.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:13:17,373] Trial 9 finished with value: 0.8733550679997295 and parameters: {'classifier__max_depth': 3, 'classifier__min_samples_split': 16, 'classifier__min_samples_leaf': 10, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9873663867133595.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:13:25,710] Trial 10 finished with value: 0.987325800311263 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 2, 'classifier__min_samples_leaf': 8, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9873663867133595.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:13:31,125] Trial 11 finished with value: 0.9278813231830885 and parameters: {'classifier__max_depth': 5, 'classifier__min_samples_split': 8, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9873663867133595.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:13:39,282] Trial 12 finished with value: 0.987403939676302 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 16, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': None}. Best is trial 12 with value: 0.987403939676302.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:13:47,525] Trial 13 finished with value: 0.9873545322802524 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 17, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': None}. Best is trial 12 with value: 0.987403939676302.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:13:55,627] Trial 14 finished with value: 0.987371939258854 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 9, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': None}. Best is trial 12 with value: 0.987403939676302.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:14:03,489] Trial 15 finished with value: 0.9868134299014935 and parameters: {'classifier__max_depth': 10, 'classifier__min_samples_split': 13, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.987403939676302.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:14:12,595] Trial 16 finished with value: 0.9884235212299977 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 13, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': None}. Best is trial 16 with value: 0.9884235212299977.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:14:21,709] Trial 17 finished with value: 0.9883340922090937 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 14, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': None}. Best is trial 16 with value: 0.9884235212299977.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:14:31,154] Trial 18 finished with value: 0.9849695181144498 and parameters: {'classifier__max_depth': 30, 'classifier__min_samples_split': 13, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': None}. Best is trial 16 with value: 0.9884235212299977.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:14:39,964] Trial 19 finished with value: 0.9872287244764795 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 18, 'classifier__min_samples_leaf': 3, 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.9884235212299977.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:14:49,114] Trial 20 finished with value: 0.9883582658091219 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 9, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': None}. Best is trial 16 with value: 0.9884235212299977.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:14:58,229] Trial 21 finished with value: 0.9882501882947281 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 6, 'classifier__min_samples_leaf': 1, 'classifier__class_weight': None}. Best is trial 16 with value: 0.9884235212299977.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:15:07,367] Trial 22 finished with value: 0.988392790925649 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 12, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': None}. Best is trial 16 with value: 0.9884235212299977.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:15:16,515] Trial 23 finished with value: 0.9884486616129255 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 7, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': None}. Best is trial 23 with value: 0.9884486616129255.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:15:25,570] Trial 24 finished with value: 0.9884383868069009 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 12, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': None}. Best is trial 23 with value: 0.9884486616129255.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:15:34,741] Trial 25 finished with value: 0.9884611356525008 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 6, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': None}. Best is trial 25 with value: 0.9884611356525008.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:15:43,916] Trial 26 finished with value: 0.9883005146829884 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 7, 'classifier__min_samples_leaf': 8, 'classifier__class_weight': None}. Best is trial 25 with value: 0.9884611356525008.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:15:53,048] Trial 27 finished with value: 0.9884486616129255 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 4, 'classifier__min_samples_leaf': 5, 'classifier__class_weight': None}. Best is trial 25 with value: 0.9884611356525008.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:16:02,199] Trial 28 finished with value: 0.9882965739938283 and parameters: {'classifier__max_depth': 15, 'classifier__min_samples_split': 5, 'classifier__min_samples_leaf': 4, 'classifier__class_weight': None}. Best is trial 25 with value: 0.9884611356525008.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:16:11,555] Trial 29 finished with value: 0.9863249882898015 and parameters: {'classifier__max_depth': 30, 'classifier__min_samples_split': 10, 'classifier__min_samples_leaf': 7, 'classifier__class_weight': None}. Best is trial 25 with value: 0.9884611356525008.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
25,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,25,COMPLETE,9.170003,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 6}",1.800923,0.048578,0.029827,0.000257,0.988414,0.989138,0.988370,0.988255,0.988128,0.988461,0.000353,1
23,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,23,COMPLETE,9.147178,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 7}",1.796001,0.032651,0.030137,0.000554,0.988614,0.988993,0.988223,0.988319,0.988094,0.988449,0.000322,2
27,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,27,COMPLETE,9.131372,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 4}",1.793190,0.043885,0.029835,0.000250,0.988614,0.988993,0.988223,0.988319,0.988094,0.988449,0.000322,2
24,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,24,COMPLETE,9.054814,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 12}",1.777945,0.033193,0.029776,0.000257,0.988548,0.988942,0.988173,0.988370,0.988159,0.988438,0.000290,4
16,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,16,COMPLETE,9.105295,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 13}",1.787749,0.039669,0.030007,0.000266,0.988563,0.989121,0.988173,0.988238,0.988023,0.988424,0.000391,5
22,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,22,COMPLETE,9.137550,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 12}",1.794470,0.038348,0.029761,0.000330,0.988347,0.989052,0.988172,0.988321,0.988073,0.988393,0.000344,6
20,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,20,COMPLETE,9.150077,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 9}",1.796823,0.045304,0.029944,0.000385,0.988331,0.988921,0.988324,0.988258,0.987957,0.988358,0.000313,7
17,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,17,COMPLETE,9.113302,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 14}",1.789155,0.031741,0.030152,0.000380,0.988265,0.989003,0.988141,0.988240,0.988021,0.988334,0.000345,8
26,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,26,COMPLETE,9.174671,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 7}",1.798520,0.046191,0.033139,0.005888,0.988212,0.988772,0.988072,0.988322,0.988124,0.988301,0.000251,9
28,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,28,COMPLETE,9.150604,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 5}",1.796930,0.020700,0.029987,0.000250,0.988213,0.988836,0.988286,0.988287,0.987860,0.988297,0.000313,10
21,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,21,COMPLETE,9.114619,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 6}",1.789874,0.034224,0.029852,0.000152,0.988250,0.988722,0.988158,0.988277,0.987844,0.988250,0.000282,11
12,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,12,COMPLETE,8.156231,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 16}",1.598849,0.009239,0.029151,0.000425,0.987268,0.987113,0.987809,0.986895,0.987935,0.987404,0.000402,12
14,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,14,COMPLETE,8.101180,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 9}",1.588057,0.022011,0.028996,0.000199,0.987220,0.987163,0.987810,0.986829,0.987837,0.987372,0.000392,13
3,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,3,COMPLETE,8.744048,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 3}",1.715179,0.092848,0.030744,0.001834,0.987336,0.987082,0.987795,0.986830,0.987788,0.987366,0.000382,14
6,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,6,COMPLETE,8.107894,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 18}",1.589688,0.029103,0.029164,0.000348,0.987254,0.987129,0.987776,0.986813,0.987824,0.987359,0.000388,15
13,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,13,COMPLETE,8.242601,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 17}",1.616209,0.021575,0.029074,0.000159,0.987138,0.987145,0.987761,0.986844,0.987885,0.987355,0.000399,16
10,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,10,COMPLETE,8.336077,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 8, ""classifier__min_samples_split"": 2}",1.632803,0.077404,0.030835,0.003710,0.987221,0.987162,0.987728,0.986730,0.987789,0.987326,0.000392,17
19,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,19,COMPLETE,8.809161,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 18}",1.728976,0.078257,0.029685,0.000252,0.987458,0.987751,0.987144,0.986951,0.986840,0.987229,0.000335,18
8,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,8,COMPLETE,9.106041,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 19}",1.788732,0.078508,0.029668,0.000198,0.987454,0.987561,0.986994,0.986694,0.986533,0.987047,0.000405,19
15,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,15,COMPLETE,7.861277,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__min_samples_leaf"": 5, ""classifier__min_samples_split"": 13}",1.539732,0.012555,0.029164,0.000362,0.986894,0.987449,0.986760,0.986365,0.986599,0.986813,0.000364,20
29,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,29,COMPLETE,9.354811,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 10}",1.837132,0.029698,0.030367,0.000325,0.986493,0.986642,0.986796,0.985338,0.986356,0.986325,0.000515,21
4,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,4,COMPLETE,7.149652,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 12}",1.397025,0.030789,0.030112,0.002501,0.986207,0.985411,0.984908,0.985245,0.984637,0.985282,0.000535,22
18,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,18,COMPLETE,9.444783,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__min_samples_leaf"": 1, ""classifier__min_samples_split"": 13}",1.855430,0.046184,0.030233,0.000352,0.984809,0.985419,0.985141,0.984455,0.985024,0.984970,0.000324,23
7,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,7,COMPLETE,7.013733,"{""classifier__class_weight"": null, ""classifier__max_depth"": 8, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 10}",1.371459,0.026174,0.028479,0.000405,0.983403,0.983786,0.981298,0.982841,0.981658,0.982597,0.000969,24
5,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,5,COMPLETE,5.315853,"{""classifier__class_weight"": null, ""classifier__max_depth"": 5, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 19}",1.030993,0.039050,0.029368,0.002719,0.947547,0.947537,0.897851,0.947713,0.898777,0.927885,0.024146,25
11,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,11,COMPLETE,5.415103,"{""classifier__class_weight"": null, ""classifier__max_depth"": 5, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 8}",1.050917,0.037840,0.028701,0.000388,0.947529,0.947537,0.897851,0.947713,0.898777,0.927881,0.024144,26
9,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,9,COMPLETE,3.662578,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 16}",0.701943,0.007834,0.027806,0.000150,0.866166,0.868045,0.882704,0.865919,0.883941,0.873355,0.008181,27
2,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,2,COMPLETE,3.638396,"{""classifier__class_weight"": null, ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 20}",0.696324,0.014858,0.028623,0.001845,0.866166,0.868045,0.882704,0.865919,0.883941,0.873355,0.008181,27
0,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,0,COMPLETE,3.976304,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 6, ""classifier__min_samples_split"": 9}",0.764654,0.023486,0.027857,0.000583,0.862714,0.863553,0.861002,0.862745,0.862760,0.862555,0.000838,29
1,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,1,COMPLETE,3.959324,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 3, ""classifier__min_samples_leaf"": 10, ""classifier__min_samples_split"": 17}",0.761512,0.016866,0.027633,0.000107,0.862714,0.863553,0.861002,0.862745,0.862760,0.862555,0.000838,29

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,1,2.078005,0.078860,0.971307,0.991931,0.981511,0.997972,0.992675,0.995317,0.988414,0.992526,0.992303
1,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,2,2.483548,0.075068,0.972401,0.993152,0.982667,0.998279,0.992954,0.995609,0.989138,0.992993,0.993053
2,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,3,2.356278,0.082580,0.970669,0.992463,0.981445,0.998105,0.992502,0.995296,0.988370,0.992494,0.992483
3,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,4,2.375290,0.082208,0.970463,0.992304,0.981262,0.998065,0.992449,0.995249,0.988255,0.992420,0.992376
4,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,5,2.379763,0.083265,0.969816,0.992569,0.981061,0.998131,0.992277,0.995195,0.988128,0.992335,0.992423

Modelo: random_forest | origem do treinamento: cicids2017

[I 2026-10-11 22:16:20,065] A new study created in memory with name: random_forest_cicids2017
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:17:29,578] Trial 0 finished with value: 0.9925225904819499 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:17:50,944] Trial 1 finished with value: 0.991477995794282 and parameters: {'classifier__n_estimators': 105, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 9, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:18:34,981] Trial 2 finished with value: 0.9922235030573161 and parameters: {'classifier__n_estimators': 134, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 7, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:19:26,423] Trial 3 finished with value: 0.9923181998937751 and parameters: {'classifier__n_estimators': 156, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:21:46,825] Trial 4 finished with value: 0.9912691558731639 and parameters: {'classifier__n_estimators': 215, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 7, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:24:48,917] Trial 5 finished with value: 0.9909953529744902 and parameters: {'classifier__n_estimators': 281, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 10, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:25:17,736] Trial 6 finished with value: 0.991816225033342 and parameters: {'classifier__n_estimators': 154, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:25:55,692] Trial 7 finished with value: 0.9913772236427386 and parameters: {'classifier__n_estimators': 100, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 10, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:26:48,352] Trial 8 finished with value: 0.9922762087353629 and parameters: {'classifier__n_estimators': 287, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 8, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:29:07,489] Trial 9 finished with value: 0.9920653819061762 and parameters: {'classifier__n_estimators': 211, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:30:38,313] Trial 10 finished with value: 0.9923258740860688 and parameters: {'classifier__n_estimators': 261, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:32:06,613] Trial 11 finished with value: 0.9922942601367677 and parameters: {'classifier__n_estimators': 254, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:32:57,429] Trial 12 finished with value: 0.9918823404738563 and parameters: {'classifier__n_estimators': 142, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:34:14,015] Trial 13 finished with value: 0.9920739236737178 and parameters: {'classifier__n_estimators': 214, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:35:45,589] Trial 14 finished with value: 0.9921310013236646 and parameters: {'classifier__n_estimators': 260, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:36:34,795] Trial 15 finished with value: 0.992194204335384 and parameters: {'classifier__n_estimators': 132, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:37:19,150] Trial 16 finished with value: 0.992449944672642 and parameters: {'classifier__n_estimators': 206, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.9925225904819499.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:38:02,755] Trial 17 finished with value: 0.9925710174345552 and parameters: {'classifier__n_estimators': 199, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 17 with value: 0.9925710174345552.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:39:58,401] Trial 18 finished with value: 0.99184539672484 and parameters: {'classifier__n_estimators': 167, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 17 with value: 0.9925710174345552.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:40:35,282] Trial 19 finished with value: 0.9912058089548094 and parameters: {'classifier__n_estimators': 177, 'classifier__max_depth': 10, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 'log2', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 17 with value: 0.9925710174345552.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:41:22,004] Trial 20 finished with value: 0.9904918902016595 and parameters: {'classifier__n_estimators': 264, 'classifier__max_depth': 10, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 17 with value: 0.9925710174345552.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:41:54,102] Trial 21 finished with value: 0.9924564363782657 and parameters: {'classifier__n_estimators': 145, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 17 with value: 0.9925710174345552.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:43:00,463] Trial 22 finished with value: 0.9923447291837014 and parameters: {'classifier__n_estimators': 188, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 17 with value: 0.9925710174345552.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:43:24,178] Trial 23 finished with value: 0.9925574405821257 and parameters: {'classifier__n_estimators': 106, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 17 with value: 0.9925710174345552.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:43:51,110] Trial 24 finished with value: 0.992405742303176 and parameters: {'classifier__n_estimators': 119, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 17 with value: 0.9925710174345552.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:44:29,636] Trial 25 finished with value: 0.9920180440715128 and parameters: {'classifier__n_estimators': 108, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 17 with value: 0.9925710174345552.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:45:16,089] Trial 26 finished with value: 0.9922798248022421 and parameters: {'classifier__n_estimators': 257, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 17 with value: 0.9925710174345552.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:45:45,035] Trial 27 finished with value: 0.9925510213353317 and parameters: {'classifier__n_estimators': 132, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'log2', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 17 with value: 0.9925710174345552.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:46:13,371] Trial 28 finished with value: 0.992531160649702 and parameters: {'classifier__n_estimators': 129, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'log2', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 17 with value: 0.9925710174345552.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:46:32,684] Trial 29 finished with value: 0.9922797722001058 and parameters: {'classifier__n_estimators': 103, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 'log2', 'classifier__class_weight': 'balanced'}. Best is trial 17 with value: 0.9925710174345552.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
17,random_forest,optuna,cicids2017,235490,30,5,1,17,COMPLETE,43.603964,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 199}",8.644114,0.106861,0.073384,0.000632,0.992747,0.992557,0.993534,0.992413,0.991604,0.992571,0.000620,1
23,random_forest,optuna,cicids2017,235490,30,5,1,23,COMPLETE,23.714276,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 106}",4.688479,0.068673,0.051434,0.000424,0.992615,0.992557,0.993568,0.992411,0.991636,0.992557,0.000615,2
27,random_forest,optuna,cicids2017,235490,30,5,1,27,COMPLETE,28.945030,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 30, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 132}",5.728647,0.037470,0.057092,0.006802,0.992713,0.992524,0.993601,0.992346,0.991570,0.992551,0.000653,3
28,random_forest,optuna,cicids2017,235490,30,5,1,28,COMPLETE,28.335312,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 30, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 129}",5.610923,0.099053,0.053492,0.004244,0.992681,0.992557,0.993535,0.992313,0.991570,0.992531,0.000633,4
0,random_forest,optuna,cicids2017,235490,30,5,1,0,COMPLETE,69.510702,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 183}",13.818679,0.589642,0.079522,0.005426,0.992648,0.992487,0.993499,0.992247,0.991731,0.992523,0.000579,5
21,random_forest,optuna,cicids2017,235490,30,5,1,21,COMPLETE,32.097711,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 145}",6.354255,0.139620,0.062621,0.000701,0.992554,0.992429,0.993440,0.992283,0.991576,0.992456,0.000597,6
16,random_forest,optuna,cicids2017,235490,30,5,1,16,COMPLETE,44.354566,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 206}",8.794445,0.254359,0.073247,0.000421,0.992521,0.992429,0.993407,0.992382,0.991510,0.992450,0.000602,7
24,random_forest,optuna,cicids2017,235490,30,5,1,24,COMPLETE,26.931519,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 119}",5.329447,0.132141,0.054280,0.004133,0.992555,0.992234,0.993441,0.992287,0.991512,0.992406,0.000622,8
22,random_forest,optuna,cicids2017,235490,30,5,1,22,COMPLETE,66.360428,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 188}",13.197545,0.191072,0.071197,0.006597,0.992521,0.992363,0.993341,0.991988,0.991511,0.992345,0.000608,9
10,random_forest,optuna,cicids2017,235490,30,5,1,10,COMPLETE,90.822629,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 261}",18.070584,0.213358,0.089227,0.005599,0.992455,0.992462,0.993178,0.992088,0.991447,0.992326,0.000564,10
3,random_forest,optuna,cicids2017,235490,30,5,1,3,COMPLETE,51.441518,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 156}",10.221986,0.145337,0.063296,0.000723,0.992586,0.992297,0.993210,0.991988,0.991510,0.992318,0.000571,11
11,random_forest,optuna,cicids2017,235490,30,5,1,11,COMPLETE,88.299785,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 254}",17.568008,0.126172,0.087150,0.002975,0.992456,0.992266,0.993243,0.992024,0.991482,0.992294,0.000576,12
26,random_forest,optuna,cicids2017,235490,30,5,1,26,COMPLETE,46.452856,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 257}",9.199483,0.145727,0.087003,0.002302,0.992438,0.992114,0.993223,0.991739,0.991885,0.992280,0.000527,13
29,random_forest,optuna,cicids2017,235490,30,5,1,29,COMPLETE,19.312985,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 103}",3.807847,0.086325,0.052078,0.000340,0.992473,0.992047,0.993223,0.991737,0.991919,0.992280,0.000530,14
8,random_forest,optuna,cicids2017,235490,30,5,1,8,COMPLETE,52.659409,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 8, ""classifier__n_estimators"": 287}",10.430089,0.291360,0.097929,0.008729,0.992425,0.992138,0.993212,0.992092,0.991513,0.992276,0.000554,15
2,random_forest,optuna,cicids2017,235490,30,5,1,2,COMPLETE,44.035738,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 134}",8.745354,0.102189,0.058981,0.008347,0.992393,0.992235,0.993015,0.992092,0.991382,0.992224,0.000526,16
15,random_forest,optuna,cicids2017,235490,30,5,1,15,COMPLETE,49.205603,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 132}",9.780688,0.107235,0.056832,0.005781,0.992239,0.992279,0.993058,0.991574,0.991820,0.992194,0.000506,17
14,random_forest,optuna,cicids2017,235490,30,5,1,14,COMPLETE,91.573364,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 260}",18.216676,0.218259,0.092272,0.008281,0.992436,0.992112,0.993023,0.991337,0.991748,0.992131,0.000577,18
13,random_forest,optuna,cicids2017,235490,30,5,1,13,COMPLETE,76.585607,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 30, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 214}",15.234429,0.335442,0.077819,0.004811,0.992173,0.992213,0.992791,0.991507,0.991685,0.992074,0.000451,19
9,random_forest,optuna,cicids2017,235490,30,5,1,9,COMPLETE,139.136450,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 211}",27.750376,0.452165,0.073638,0.000647,0.992198,0.992168,0.992751,0.991795,0.991415,0.992065,0.000446,20
25,random_forest,optuna,cicids2017,235490,30,5,1,25,COMPLETE,38.525493,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 108}",7.645194,0.045486,0.056844,0.003841,0.992037,0.991944,0.992923,0.991371,0.991814,0.992018,0.000507,21
12,random_forest,optuna,cicids2017,235490,30,5,1,12,COMPLETE,50.815132,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 15, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 142}",10.100010,0.152047,0.059676,0.005969,0.991641,0.991518,0.993015,0.991891,0.991348,0.991882,0.000593,22
18,random_forest,optuna,cicids2017,235490,30,5,1,18,COMPLETE,115.645493,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 167}",23.057304,0.559731,0.068602,0.005943,0.991873,0.992143,0.992458,0.991206,0.991547,0.991845,0.000439,23
6,random_forest,optuna,cicids2017,235490,30,5,1,6,COMPLETE,28.817577,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 154}",5.695832,0.068916,0.064592,0.002470,0.991641,0.991321,0.992884,0.992052,0.991183,0.991816,0.000612,24
1,random_forest,optuna,cicids2017,235490,30,5,1,1,COMPLETE,21.366219,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 105}",4.216832,0.121566,0.053692,0.001994,0.991681,0.991125,0.992804,0.991080,0.990699,0.991478,0.000733,25
7,random_forest,optuna,cicids2017,235490,30,5,1,7,COMPLETE,37.956334,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 100}",7.536759,0.131683,0.052059,0.000471,0.991680,0.991024,0.992338,0.991181,0.990663,0.991377,0.000581,26
4,random_forest,optuna,cicids2017,235490,30,5,1,4,COMPLETE,140.401808,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 215}",28.004157,0.674840,0.073215,0.000712,0.990797,0.990769,0.992258,0.991499,0.991022,0.991269,0.000560,27
19,random_forest,optuna,cicids2017,235490,30,5,1,19,COMPLETE,36.880195,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 177}",7.311664,0.226515,0.061778,0.000333,0.991488,0.990835,0.992243,0.991153,0.990310,0.991206,0.000648,28
5,random_forest,optuna,cicids2017,235490,30,5,1,5,COMPLETE,182.091793,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 281}",36.324090,0.632944,0.091008,0.006251,0.990665,0.990410,0.992030,0.991273,0.990599,0.990995,0.000593,29
20,random_forest,optuna,cicids2017,235490,30,5,1,20,COMPLETE,46.721642,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 264}",9.255751,0.080221,0.085478,0.002667,0.990975,0.990152,0.991667,0.989909,0.989757,0.990492,0.000723,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,random_forest,optuna,cicids2017,235490,30,5,1,1,8.588256,0.101570,0.980165,0.996815,0.988420,0.999200,0.994957,0.997074,0.992747,0.995329,0.995886
1,random_forest,optuna,cicids2017,235490,30,5,1,2,8.432170,0.101120,0.978553,0.997877,0.988120,0.999467,0.994533,0.996994,0.992557,0.995201,0.996205
2,random_forest,optuna,cicids2017,235490,30,5,1,3,8.606156,0.099557,0.982326,0.997134,0.989674,0.999281,0.995515,0.997394,0.993534,0.995838,0.996324
3,random_forest,optuna,cicids2017,235490,30,5,1,4,8.582196,0.101186,0.980548,0.995329,0.987883,0.998828,0.995063,0.996942,0.992413,0.995117,0.995196
4,random_forest,optuna,cicids2017,235490,30,5,1,5,8.608072,0.101598,0.976797,0.996603,0.986601,0.999146,0.994081,0.996607,0.991604,0.994586,0.995342

Modelo: random_forest | origem do treinamento: unsw_nb15

[I 2026-10-11 22:47:27,930] A new study created in memory with name: random_forest_unsw_nb15
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:48:32,775] Trial 0 finished with value: 0.9806425288526774 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.9806425288526774.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:48:53,457] Trial 1 finished with value: 0.9804995837970267 and parameters: {'classifier__n_estimators': 105, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 9, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 0 with value: 0.9806425288526774.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:49:36,150] Trial 2 finished with value: 0.9805274846118419 and parameters: {'classifier__n_estimators': 134, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 7, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9806425288526774.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:50:25,907] Trial 3 finished with value: 0.980955708615911 and parameters: {'classifier__n_estimators': 156, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.980955708615911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:52:53,719] Trial 4 finished with value: 0.980127784562495 and parameters: {'classifier__n_estimators': 215, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 7, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.980955708615911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:56:05,102] Trial 5 finished with value: 0.9798106390403551 and parameters: {'classifier__n_estimators': 281, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 10, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.980955708615911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:56:32,572] Trial 6 finished with value: 0.9807966270876648 and parameters: {'classifier__n_estimators': 154, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.980955708615911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:57:06,507] Trial 7 finished with value: 0.9803783527651604 and parameters: {'classifier__n_estimators': 100, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 10, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 3 with value: 0.980955708615911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 22:57:56,993] Trial 8 finished with value: 0.9802319295041075 and parameters: {'classifier__n_estimators': 287, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 8, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.980955708615911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:00:23,620] Trial 9 finished with value: 0.9804198276401955 and parameters: {'classifier__n_estimators': 211, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.980955708615911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:01:29,529] Trial 10 finished with value: 0.9808547226092793 and parameters: {'classifier__n_estimators': 207, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.980955708615911.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:02:41,999] Trial 11 finished with value: 0.9810017884223697 and parameters: {'classifier__n_estimators': 226, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:03:25,161] Trial 12 finished with value: 0.9809623285048147 and parameters: {'classifier__n_estimators': 132, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:04:07,640] Trial 13 finished with value: 0.9806825308141214 and parameters: {'classifier__n_estimators': 240, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 'log2', 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:05:34,002] Trial 14 finished with value: 0.9809638009958889 and parameters: {'classifier__n_estimators': 275, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:07:04,013] Trial 15 finished with value: 0.9809156758563198 and parameters: {'classifier__n_estimators': 287, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:07:45,634] Trial 16 finished with value: 0.9807905785975146 and parameters: {'classifier__n_estimators': 237, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:09:04,960] Trial 17 finished with value: 0.9806788926368087 and parameters: {'classifier__n_estimators': 260, 'classifier__max_depth': 10, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:10:32,533] Trial 18 finished with value: 0.9806170120061157 and parameters: {'classifier__n_estimators': 256, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:12:06,570] Trial 19 finished with value: 0.9807997568329305 and parameters: {'classifier__n_estimators': 298, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:13:20,765] Trial 20 finished with value: 0.9809056822502233 and parameters: {'classifier__n_estimators': 229, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:13:57,292] Trial 21 finished with value: 0.9806974619612208 and parameters: {'classifier__n_estimators': 104, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:14:43,645] Trial 22 finished with value: 0.9805617996182221 and parameters: {'classifier__n_estimators': 268, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:16:12,788] Trial 23 finished with value: 0.9809872135420236 and parameters: {'classifier__n_estimators': 259, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:17:27,730] Trial 24 finished with value: 0.9808297435613393 and parameters: {'classifier__n_estimators': 220, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:19:01,396] Trial 25 finished with value: 0.9808650457791164 and parameters: {'classifier__n_estimators': 271, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 11 with value: 0.9810017884223697.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:19:56,334] Trial 26 finished with value: 0.981040409154686 and parameters: {'classifier__n_estimators': 296, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 'log2', 'classifier__class_weight': None}. Best is trial 26 with value: 0.981040409154686.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:20:50,145] Trial 27 finished with value: 0.9810470523809197 and parameters: {'classifier__n_estimators': 290, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 'log2', 'classifier__class_weight': None}. Best is trial 27 with value: 0.9810470523809197.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:21:45,558] Trial 28 finished with value: 0.9810145157838436 and parameters: {'classifier__n_estimators': 300, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'log2', 'classifier__class_weight': None}. Best is trial 27 with value: 0.9810470523809197.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:22:39,922] Trial 29 finished with value: 0.9810470525467453 and parameters: {'classifier__n_estimators': 291, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 'log2', 'classifier__class_weight': None}. Best is trial 29 with value: 0.9810470525467453.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
29,random_forest,optuna,unsw_nb15,235490,30,5,1,29,COMPLETE,54.363942,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 291}",10.770463,0.189791,0.098843,0.006635,0.981381,0.981862,0.980518,0.980593,0.980881,0.981047,0.000508,1
27,random_forest,optuna,unsw_nb15,235490,30,5,1,27,COMPLETE,53.809802,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 290}",10.658944,0.151244,0.099603,0.005986,0.981381,0.981862,0.980549,0.980593,0.980850,0.981047,0.000504,2
26,random_forest,optuna,unsw_nb15,235490,30,5,1,26,COMPLETE,54.937469,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 296}",10.885835,0.104020,0.098262,0.006095,0.981381,0.981862,0.980516,0.980593,0.980850,0.981040,0.000510,3
28,random_forest,optuna,unsw_nb15,235490,30,5,1,28,COMPLETE,55.412637,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 300}",10.975816,0.133364,0.102610,0.007679,0.981414,0.981836,0.980493,0.980564,0.980765,0.981015,0.000524,4
11,random_forest,optuna,unsw_nb15,235490,30,5,1,11,COMPLETE,72.469553,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 226}",14.405170,0.234598,0.084437,0.001380,0.981418,0.981704,0.980693,0.980465,0.980729,0.981002,0.000475,5
23,random_forest,optuna,unsw_nb15,235490,30,5,1,23,COMPLETE,89.142274,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 259}",17.737944,0.093288,0.086596,0.004455,0.981436,0.981728,0.980477,0.980546,0.980749,0.980987,0.000502,6
14,random_forest,optuna,unsw_nb15,235490,30,5,1,14,COMPLETE,86.361388,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 275}",17.185384,0.170540,0.084067,0.000927,0.981459,0.981776,0.980572,0.980407,0.980605,0.980964,0.000547,7
12,random_forest,optuna,unsw_nb15,235490,30,5,1,12,COMPLETE,43.161180,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 132}",8.567738,0.236869,0.061519,0.008492,0.981652,0.981514,0.980570,0.980502,0.980573,0.980962,0.000509,8
3,random_forest,optuna,unsw_nb15,235490,30,5,1,3,COMPLETE,49.756098,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 156}",9.884447,0.124390,0.064610,0.003162,0.981618,0.981547,0.980570,0.980438,0.980606,0.980956,0.000515,9
15,random_forest,optuna,unsw_nb15,235490,30,5,1,15,COMPLETE,90.010366,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 287}",17.902435,0.255854,0.095998,0.005619,0.981428,0.981716,0.980576,0.980284,0.980575,0.980916,0.000554,10
20,random_forest,optuna,unsw_nb15,235490,30,5,1,20,COMPLETE,74.194083,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 229}",14.744425,0.263977,0.089509,0.006228,0.981281,0.981699,0.980587,0.980429,0.980533,0.980906,0.000498,11
25,random_forest,optuna,unsw_nb15,235490,30,5,1,25,COMPLETE,93.666130,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 271}",18.633483,0.215316,0.096151,0.006354,0.981244,0.981664,0.980219,0.980483,0.980716,0.980865,0.000523,12
10,random_forest,optuna,unsw_nb15,235490,30,5,1,10,COMPLETE,65.908598,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 207}",13.103333,0.190972,0.074752,0.001614,0.981379,0.981299,0.980651,0.980549,0.980395,0.980855,0.000405,13
24,random_forest,optuna,unsw_nb15,235490,30,5,1,24,COMPLETE,74.941199,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 220}",14.904180,0.115495,0.081241,0.006884,0.981342,0.981696,0.980288,0.980172,0.980651,0.980830,0.000595,14
19,random_forest,optuna,unsw_nb15,235490,30,5,1,19,COMPLETE,94.037054,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 298}",18.704055,0.166030,0.098457,0.006113,0.981493,0.981457,0.980445,0.980220,0.980383,0.980800,0.000557,15
6,random_forest,optuna,unsw_nb15,235490,30,5,1,6,COMPLETE,27.469603,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 154}",5.428666,0.031967,0.062824,0.000159,0.981143,0.981652,0.980226,0.980413,0.980549,0.980797,0.000526,16
16,random_forest,optuna,unsw_nb15,235490,30,5,1,16,COMPLETE,41.621440,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 237}",8.233434,0.139840,0.088042,0.002242,0.981111,0.981685,0.980226,0.980382,0.980549,0.980791,0.000538,17
21,random_forest,optuna,unsw_nb15,235490,30,5,1,21,COMPLETE,36.527220,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 104}",7.249034,0.128482,0.053365,0.003017,0.981363,0.981457,0.980160,0.980122,0.980385,0.980697,0.000590,18
13,random_forest,optuna,unsw_nb15,235490,30,5,1,13,COMPLETE,42.478508,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 240}",8.396737,0.132287,0.094632,0.005960,0.981208,0.981493,0.980258,0.980160,0.980294,0.980683,0.000554,19
17,random_forest,optuna,unsw_nb15,235490,30,5,1,17,COMPLETE,79.325081,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 10, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 260}",15.763754,0.268663,0.097655,0.009398,0.981206,0.981297,0.980252,0.980157,0.980483,0.980679,0.000480,20
0,random_forest,optuna,unsw_nb15,235490,30,5,1,0,COMPLETE,64.842293,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 183}",12.885866,0.271347,0.078861,0.005180,0.980900,0.981409,0.980483,0.980107,0.980314,0.980643,0.000463,21
18,random_forest,optuna,unsw_nb15,235490,30,5,1,18,COMPLETE,87.571773,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 256}",17.420431,0.123294,0.089733,0.007238,0.981177,0.981308,0.980320,0.979813,0.980467,0.980617,0.000556,22
22,random_forest,optuna,unsw_nb15,235490,30,5,1,22,COMPLETE,46.351938,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 268}",9.181746,0.082976,0.085573,0.001527,0.981176,0.981336,0.980133,0.980095,0.980069,0.980562,0.000569,23
2,random_forest,optuna,unsw_nb15,235490,30,5,1,2,COMPLETE,42.693039,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 134}",8.473497,0.171046,0.063069,0.001123,0.981238,0.981268,0.979873,0.980030,0.980228,0.980527,0.000603,24
1,random_forest,optuna,unsw_nb15,235490,30,5,1,1,COMPLETE,20.681299,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 105}",4.078558,0.139967,0.055401,0.004778,0.981062,0.981180,0.979678,0.980047,0.980531,0.980500,0.000576,25
9,random_forest,optuna,unsw_nb15,235490,30,5,1,9,COMPLETE,146.625901,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 211}",29.245591,0.729100,0.076454,0.006792,0.980961,0.981068,0.979991,0.980087,0.979992,0.980420,0.000488,26
7,random_forest,optuna,unsw_nb15,235490,30,5,1,7,COMPLETE,33.934065,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 100}",6.733138,0.068603,0.051716,0.000504,0.981092,0.980704,0.980105,0.979694,0.980296,0.980378,0.000483,27
8,random_forest,optuna,unsw_nb15,235490,30,5,1,8,COMPLETE,50.485638,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 8, ""classifier__n_estimators"": 287}",9.985080,0.169806,0.107787,0.006504,0.980984,0.981049,0.979372,0.979873,0.979881,0.980232,0.000667,28
4,random_forest,optuna,unsw_nb15,235490,30,5,1,4,COMPLETE,147.811595,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 215}",29.483841,0.606506,0.075959,0.004774,0.980845,0.980850,0.979587,0.979739,0.979617,0.980128,0.000590,29
5,random_forest,optuna,unsw_nb15,235490,30,5,1,5,COMPLETE,191.382438,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 281}",38.186109,0.782106,0.088152,0.006176,0.980685,0.980502,0.979205,0.979296,0.979364,0.979811,0.000644,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,random_forest,optuna,unsw_nb15,235490,30,5,1,1,10.954273,0.141018,0.944433,0.997877,0.970420,0.999462,0.985323,0.992342,0.981381,0.987834,0.991600
1,random_forest,optuna,unsw_nb15,235490,30,5,1,2,10.667069,0.126459,0.945590,0.998195,0.971181,0.999542,0.985642,0.992543,0.981862,0.988152,0.991919
2,random_forest,optuna,unsw_nb15,235490,30,5,1,3,10.833181,0.158242,0.942327,0.997346,0.969056,0.999327,0.984739,0.991979,0.980518,0.987261,0.991043
3,random_forest,optuna,unsw_nb15,235490,30,5,1,4,11.065267,0.164246,0.941807,0.998195,0.969182,0.999542,0.984580,0.992004,0.980593,0.987303,0.991388
4,random_forest,optuna,unsw_nb15,235490,30,5,1,5,10.887353,0.144804,0.942479,0.998408,0.969638,0.999596,0.984766,0.992125,0.980881,0.987494,0.991587

Modelo: random_forest | origem do treinamento: iot23

[I 2026-10-11 23:23:50,702] A new study created in memory with name: random_forest_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:24:25,317] Trial 0 finished with value: 0.9957095525644787 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.9957095525644787.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:24:37,517] Trial 1 finished with value: 0.9977447075724835 and parameters: {'classifier__n_estimators': 105, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 9, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 1 with value: 0.9977447075724835.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:24:57,369] Trial 2 finished with value: 0.9955587613854531 and parameters: {'classifier__n_estimators': 134, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 7, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9977447075724835.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:25:20,173] Trial 3 finished with value: 0.9956766002704086 and parameters: {'classifier__n_estimators': 156, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9977447075724835.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:26:06,850] Trial 4 finished with value: 0.995538421750647 and parameters: {'classifier__n_estimators': 215, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 7, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9977447075724835.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:27:07,116] Trial 5 finished with value: 0.9955383576804918 and parameters: {'classifier__n_estimators': 281, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 10, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9977447075724835.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:27:24,930] Trial 6 finished with value: 0.9956895712479863 and parameters: {'classifier__n_estimators': 154, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9977447075724835.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:27:41,247] Trial 7 finished with value: 0.9977381272475508 and parameters: {'classifier__n_estimators': 100, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 10, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 1 with value: 0.9977447075724835.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:28:13,203] Trial 8 finished with value: 0.9954601890887467 and parameters: {'classifier__n_estimators': 287, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 8, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9977447075724835.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:29:00,440] Trial 9 finished with value: 0.9955976137209952 and parameters: {'classifier__n_estimators': 211, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9977447075724835.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:29:13,478] Trial 10 finished with value: 0.9977525579956807 and parameters: {'classifier__n_estimators': 104, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 10 with value: 0.9977525579956807.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:29:28,921] Trial 11 finished with value: 0.9977581731374487 and parameters: {'classifier__n_estimators': 128, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 7, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 11 with value: 0.9977581731374487.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:29:42,303] Trial 12 finished with value: 0.9978115078042806 and parameters: {'classifier__n_estimators': 108, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 12 with value: 0.9978115078042806.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:30:00,463] Trial 13 finished with value: 0.9978181088773169 and parameters: {'classifier__n_estimators': 148, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 13 with value: 0.9978181088773169.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:30:35,621] Trial 14 finished with value: 0.9978053109000488 and parameters: {'classifier__n_estimators': 151, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 1.0, 'classifier__class_weight': None}. Best is trial 13 with value: 0.9978181088773169.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:30:51,338] Trial 15 finished with value: 0.997811545051474 and parameters: {'classifier__n_estimators': 134, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 13 with value: 0.9978181088773169.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:31:11,919] Trial 16 finished with value: 0.9977915349230049 and parameters: {'classifier__n_estimators': 180, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 13 with value: 0.9978181088773169.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:31:29,804] Trial 17 finished with value: 0.9977314086525224 and parameters: {'classifier__n_estimators': 168, 'classifier__max_depth': 10, 'classifier__min_samples_leaf': 9, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 13 with value: 0.9978181088773169.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:31:49,182] Trial 18 finished with value: 0.9957491681632089 and parameters: {'classifier__n_estimators': 119, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 13 with value: 0.9978181088773169.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:32:13,627] Trial 19 finished with value: 0.9977914928756318 and parameters: {'classifier__n_estimators': 215, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 13 with value: 0.9978181088773169.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:32:51,182] Trial 20 finished with value: 0.9977385174630978 and parameters: {'classifier__n_estimators': 161, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 1.0, 'classifier__class_weight': None}. Best is trial 13 with value: 0.9978181088773169.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:33:03,175] Trial 21 finished with value: 0.9978114391831788 and parameters: {'classifier__n_estimators': 108, 'classifier__max_depth': 10, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 13 with value: 0.9978181088773169.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:33:18,649] Trial 22 finished with value: 0.9977981679032808 and parameters: {'classifier__n_estimators': 133, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 13 with value: 0.9978181088773169.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:33:32,887] Trial 23 finished with value: 0.9978514987258003 and parameters: {'classifier__n_estimators': 127, 'classifier__max_depth': 10, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 23 with value: 0.9978514987258003.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:33:48,329] Trial 24 finished with value: 0.9978382396631782 and parameters: {'classifier__n_estimators': 139, 'classifier__max_depth': 10, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 23 with value: 0.9978514987258003.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:34:09,823] Trial 25 finished with value: 0.9978516917492165 and parameters: {'classifier__n_estimators': 185, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 25 with value: 0.9978516917492165.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:34:31,179] Trial 26 finished with value: 0.99786483538834 and parameters: {'classifier__n_estimators': 186, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 26 with value: 0.99786483538834.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:34:52,201] Trial 27 finished with value: 0.9978581726393971 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 26 with value: 0.99786483538834.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:35:18,981] Trial 28 finished with value: 0.9978582992425487 and parameters: {'classifier__n_estimators': 232, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 26 with value: 0.99786483538834.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:35:55,826] Trial 29 finished with value: 0.9957294303618351 and parameters: {'classifier__n_estimators': 227, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 26 with value: 0.99786483538834.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
26,random_forest,optuna,iot23,235490,30,5,1,26,COMPLETE,21.354950,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 186}",4.202018,0.151925,0.066306,0.005665,0.998005,0.997471,0.997572,0.998271,0.998005,0.997865,0.000299,1
28,random_forest,optuna,iot23,235490,30,5,1,28,COMPLETE,26.779210,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 232}",5.277049,0.130116,0.075582,0.001858,0.997972,0.997471,0.997572,0.998338,0.997939,0.997858,0.000310,2
27,random_forest,optuna,iot23,235490,30,5,1,27,COMPLETE,21.022216,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 183}",4.137719,0.116262,0.064077,0.001474,0.998005,0.997471,0.997572,0.998238,0.998005,0.997858,0.000290,3
25,random_forest,optuna,iot23,235490,30,5,1,25,COMPLETE,21.493079,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 185}",4.227900,0.106726,0.068078,0.006012,0.998005,0.997471,0.997572,0.998305,0.997905,0.997852,0.000302,4
23,random_forest,optuna,iot23,235490,30,5,1,23,COMPLETE,14.237932,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 127}",2.789257,0.106772,0.055457,0.001538,0.998005,0.997471,0.997538,0.998305,0.997938,0.997851,0.000310,5
24,random_forest,optuna,iot23,235490,30,5,1,24,COMPLETE,15.441393,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 139}",3.032613,0.120978,0.052894,0.001311,0.997939,0.997471,0.997572,0.998205,0.998005,0.997838,0.000275,6
13,random_forest,optuna,iot23,235490,30,5,1,13,COMPLETE,18.158941,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 148}",3.564430,0.167154,0.064664,0.001501,0.997972,0.997471,0.997538,0.998171,0.997938,0.997818,0.000269,7
15,random_forest,optuna,iot23,235490,30,5,1,15,COMPLETE,15.716371,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 134}",3.085413,0.096334,0.054824,0.005441,0.997872,0.997471,0.997572,0.998205,0.997938,0.997812,0.000264,8
12,random_forest,optuna,iot23,235490,30,5,1,12,COMPLETE,13.381157,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 108}",2.617958,0.114226,0.055437,0.003440,0.997939,0.997471,0.997538,0.998171,0.997938,0.997812,0.000265,9
21,random_forest,optuna,iot23,235490,30,5,1,21,COMPLETE,11.992245,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 108}",2.340683,0.077274,0.055120,0.002622,0.997938,0.997438,0.997572,0.998171,0.997938,0.997811,0.000268,10
14,random_forest,optuna,iot23,235490,30,5,1,14,COMPLETE,35.157251,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 151}",6.964576,0.302663,0.064080,0.005045,0.997939,0.997372,0.997472,0.998305,0.997939,0.997805,0.000342,11
22,random_forest,optuna,iot23,235490,30,5,1,22,COMPLETE,15.473723,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 133}",3.037913,0.063135,0.054006,0.002774,0.997905,0.997471,0.997505,0.998171,0.997938,0.997798,0.000270,12
16,random_forest,optuna,iot23,235490,30,5,1,16,COMPLETE,20.580591,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 180}",4.048473,0.133094,0.064617,0.002633,0.997872,0.997471,0.997505,0.998171,0.997938,0.997792,0.000267,13
19,random_forest,optuna,iot23,235490,30,5,1,19,COMPLETE,24.444889,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 215}",4.810273,0.160873,0.076113,0.002889,0.997938,0.997471,0.997471,0.998138,0.997938,0.997791,0.000271,14
11,random_forest,optuna,iot23,235490,30,5,1,11,COMPLETE,15.442711,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 128}",3.026074,0.060037,0.059687,0.005628,0.997839,0.997404,0.997471,0.998138,0.997938,0.997758,0.000280,15
10,random_forest,optuna,iot23,235490,30,5,1,10,COMPLETE,13.037350,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 104}",2.548487,0.100493,0.056233,0.001426,0.997840,0.997372,0.997506,0.998172,0.997873,0.997753,0.000284,16
1,random_forest,optuna,iot23,235490,30,5,1,1,COMPLETE,12.199864,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 105}",2.384933,0.052097,0.052927,0.001768,0.997905,0.997338,0.997405,0.998138,0.997938,0.997745,0.000316,17
20,random_forest,optuna,iot23,235490,30,5,1,20,COMPLETE,37.554535,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 161}",7.443076,0.202674,0.065147,0.002628,0.998072,0.997338,0.997405,0.998072,0.997805,0.997739,0.000316,18
7,random_forest,optuna,iot23,235490,30,5,1,7,COMPLETE,16.315814,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 100}",3.205410,0.111984,0.055603,0.002494,0.997872,0.997304,0.997371,0.998171,0.997972,0.997738,0.000341,19
17,random_forest,optuna,iot23,235490,30,5,1,17,COMPLETE,17.883914,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 168}",3.508426,0.111406,0.065728,0.001464,0.997905,0.997338,0.997405,0.998105,0.997905,0.997731,0.000304,20
18,random_forest,optuna,iot23,235490,30,5,1,18,COMPLETE,19.377464,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 119}",3.822051,0.101563,0.050714,0.000277,0.996066,0.995439,0.995865,0.995934,0.995443,0.995749,0.000260,21
29,random_forest,optuna,iot23,235490,30,5,1,29,COMPLETE,36.844596,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 227}",7.293247,0.152687,0.072532,0.000500,0.996033,0.995472,0.995832,0.995901,0.995410,0.995729,0.000245,22
0,random_forest,optuna,iot23,235490,30,5,1,0,COMPLETE,34.611779,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 183}",6.858622,0.058737,0.061663,0.000388,0.996033,0.995308,0.995765,0.995967,0.995475,0.995710,0.000280,23
6,random_forest,optuna,iot23,235490,30,5,1,6,COMPLETE,17.813748,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 154}",3.495710,0.081942,0.064964,0.001494,0.996033,0.995307,0.995798,0.995901,0.995409,0.995690,0.000282,24
3,random_forest,optuna,iot23,235490,30,5,1,3,COMPLETE,22.803515,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 156}",4.494395,0.073418,0.064313,0.001698,0.995967,0.995308,0.995733,0.995934,0.995442,0.995677,0.000263,25
9,random_forest,optuna,iot23,235490,30,5,1,9,COMPLETE,47.236192,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 211}",9.367812,0.173199,0.077315,0.002039,0.995934,0.995374,0.995633,0.995736,0.995311,0.995598,0.000231,26
2,random_forest,optuna,iot23,235490,30,5,1,2,COMPLETE,19.851522,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 134}",3.914068,0.045537,0.054153,0.002711,0.995869,0.995406,0.995569,0.995835,0.995115,0.995559,0.000281,27
4,random_forest,optuna,iot23,235490,30,5,1,4,COMPLETE,46.675687,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 215}",9.254620,0.181332,0.078296,0.006012,0.995836,0.995340,0.995502,0.995769,0.995245,0.995538,0.000232,28
5,random_forest,optuna,iot23,235490,30,5,1,5,COMPLETE,60.265523,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 281}",11.966544,0.256686,0.084360,0.001025,0.995704,0.995439,0.995600,0.995736,0.995212,0.995538,0.000193,29
8,random_forest,optuna,iot23,235490,30,5,1,8,COMPLETE,31.955958,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 8, ""classifier__n_estimators"": 287}",6.301953,0.295041,0.086931,0.004763,0.995738,0.995309,0.995700,0.995605,0.994949,0.995460,0.000297,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,random_forest,optuna,iot23,235490,30,5,1,1,4.334840,0.091749,0.999573,0.994055,0.996806,0.998516,0.999894,0.999204,0.998005,0.998726,0.996974
1,random_forest,optuna,iot23,235490,30,5,1,2,4.313454,0.095465,0.999893,0.992037,0.995950,0.998013,0.999973,0.998992,0.997471,0.998386,0.996005
2,random_forest,optuna,iot23,235490,30,5,1,3,4.051754,0.090772,0.999786,0.992463,0.996111,0.998119,0.999947,0.999032,0.997572,0.998450,0.996205
3,random_forest,optuna,iot23,235490,30,5,1,4,4.147138,0.094510,1.000000,0.994480,0.997232,0.998622,1.000000,0.999310,0.998271,0.998896,0.997240
4,random_forest,optuna,iot23,235490,30,5,1,5,4.279947,0.090703,0.999893,0.993737,0.996805,0.998437,0.999973,0.999204,0.998005,0.998726,0.996855

Modelo: random_forest | origem do treinamento: cicids2017_unsw_nb15

[I 2026-10-11 23:36:24,161] A new study created in memory with name: random_forest_cicids2017_unsw_nb15
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:39:18,035] Trial 0 finished with value: 0.985961237094098 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.985961237094098.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:40:10,800] Trial 1 finished with value: 0.9850567773386842 and parameters: {'classifier__n_estimators': 105, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 9, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 0 with value: 0.985961237094098.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:42:04,318] Trial 2 finished with value: 0.9859246374265336 and parameters: {'classifier__n_estimators': 134, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 7, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.985961237094098.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:44:19,044] Trial 3 finished with value: 0.9861201853173049 and parameters: {'classifier__n_estimators': 156, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9861201853173049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:50:09,781] Trial 4 finished with value: 0.9845233635885968 and parameters: {'classifier__n_estimators': 215, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 7, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9861201853173049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:57:44,461] Trial 5 finished with value: 0.9840379126555178 and parameters: {'classifier__n_estimators': 281, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 10, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9861201853173049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-11 23:59:00,234] Trial 6 finished with value: 0.9855582905625205 and parameters: {'classifier__n_estimators': 154, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9861201853173049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:00:32,987] Trial 7 finished with value: 0.98510490833734 and parameters: {'classifier__n_estimators': 100, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 10, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 3 with value: 0.9861201853173049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:02:47,993] Trial 8 finished with value: 0.9857433047374965 and parameters: {'classifier__n_estimators': 287, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 8, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9861201853173049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:08:41,161] Trial 9 finished with value: 0.9851374304839939 and parameters: {'classifier__n_estimators': 211, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.9861201853173049.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:11:39,740] Trial 10 finished with value: 0.9861863116909733 and parameters: {'classifier__n_estimators': 207, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 10 with value: 0.9861863116909733.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:14:54,162] Trial 11 finished with value: 0.9862410886694768 and parameters: {'classifier__n_estimators': 226, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9862410886694768.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:22:22,923] Trial 12 finished with value: 0.9855596474883257 and parameters: {'classifier__n_estimators': 260, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9862410886694768.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:24:11,064] Trial 13 finished with value: 0.9860390809104078 and parameters: {'classifier__n_estimators': 227, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 'log2', 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9862410886694768.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:27:46,338] Trial 14 finished with value: 0.9859298642853617 and parameters: {'classifier__n_estimators': 259, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9862410886694768.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:31:03,926] Trial 15 finished with value: 0.9854990895260913 and parameters: {'classifier__n_estimators': 223, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 11 with value: 0.9862410886694768.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:34:49,365] Trial 16 finished with value: 0.9862575181782374 and parameters: {'classifier__n_estimators': 248, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 16 with value: 0.9862575181782374.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:38:50,018] Trial 17 finished with value: 0.9861639639051851 and parameters: {'classifier__n_estimators': 266, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 16 with value: 0.9862575181782374.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:45:59,169] Trial 18 finished with value: 0.9815600248094721 and parameters: {'classifier__n_estimators': 287, 'classifier__max_depth': 10, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 16 with value: 0.9862575181782374.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:47:59,645] Trial 19 finished with value: 0.9860859152740528 and parameters: {'classifier__n_estimators': 222, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 16 with value: 0.9862575181782374.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:52:19,343] Trial 20 finished with value: 0.9860144424445755 and parameters: {'classifier__n_estimators': 293, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 16 with value: 0.9862575181782374.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:55:10,382] Trial 21 finished with value: 0.9861733170655548 and parameters: {'classifier__n_estimators': 198, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.9862575181782374.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 00:57:28,254] Trial 22 finished with value: 0.9859427344526137 and parameters: {'classifier__n_estimators': 255, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 16 with value: 0.9862575181782374.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:01:07,280] Trial 23 finished with value: 0.9861959400488083 and parameters: {'classifier__n_estimators': 238, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 16 with value: 0.9862575181782374.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:04:36,925] Trial 24 finished with value: 0.9861992537523644 and parameters: {'classifier__n_estimators': 228, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 16 with value: 0.9862575181782374.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:08:19,010] Trial 25 finished with value: 0.986013958354237 and parameters: {'classifier__n_estimators': 265, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.9862575181782374.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:10:36,373] Trial 26 finished with value: 0.986160726321003 and parameters: {'classifier__n_estimators': 287, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 'log2', 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.9862575181782374.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:13:40,267] Trial 27 finished with value: 0.9860746169973897 and parameters: {'classifier__n_estimators': 203, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 16 with value: 0.9862575181782374.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:15:20,223] Trial 28 finished with value: 0.9861969352915555 and parameters: {'classifier__n_estimators': 181, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'log2', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 16 with value: 0.9862575181782374.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:18:03,245] Trial 29 finished with value: 0.9861513519206204 and parameters: {'classifier__n_estimators': 298, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 16 with value: 0.9862575181782374.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
16,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,16,COMPLETE,225.438598,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 248}",44.899957,0.246212,0.181899,0.006591,0.985531,0.986378,0.987382,0.986275,0.985723,0.986258,0.000647,1
11,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,11,COMPLETE,194.421737,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 226}",38.707103,0.195835,0.172603,0.010100,0.985614,0.986294,0.987350,0.986258,0.985689,0.986241,0.000622,2
24,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,24,COMPLETE,209.643522,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 228}",41.744718,0.326943,0.177995,0.010324,0.985544,0.986289,0.987374,0.986091,0.985699,0.986199,0.000645,3
28,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,28,COMPLETE,99.954884,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 181}",19.844820,0.455117,0.142102,0.003644,0.985582,0.986184,0.987367,0.986209,0.985643,0.986197,0.000641,4
23,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,23,COMPLETE,219.025162,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 238}",43.619610,0.435535,0.180201,0.009700,0.985544,0.986338,0.987357,0.986075,0.985666,0.986196,0.000646,5
10,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,10,COMPLETE,178.577656,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 207}",35.555872,0.296296,0.155139,0.004910,0.985593,0.986306,0.987277,0.985976,0.985780,0.986186,0.000594,6
21,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,21,COMPLETE,171.038542,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 198}",34.047067,0.164257,0.156080,0.007663,0.985543,0.986290,0.987261,0.985993,0.985781,0.986173,0.000597,7
17,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,17,COMPLETE,240.652013,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 266}",47.936461,0.652285,0.188821,0.006707,0.985552,0.986284,0.987271,0.986245,0.985468,0.986164,0.000649,8
26,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,26,COMPLETE,137.362776,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 287}",27.248795,0.272637,0.217066,0.006569,0.985528,0.986224,0.987360,0.986074,0.985618,0.986161,0.000655,9
29,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,29,COMPLETE,163.021653,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 298}",32.386116,0.605136,0.211232,0.012877,0.985560,0.986224,0.987295,0.986025,0.985652,0.986151,0.000621,10
3,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,3,COMPLETE,134.725560,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 156}",26.811796,0.142359,0.130010,0.005244,0.985370,0.986284,0.987238,0.986177,0.985532,0.986120,0.000661,11
19,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,19,COMPLETE,120.476121,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 222}",23.925105,0.356480,0.164743,0.004812,0.985340,0.986219,0.987239,0.986164,0.985468,0.986086,0.000677,12
27,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,27,COMPLETE,183.893683,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 203}",36.620556,0.517403,0.153333,0.010055,0.985358,0.986287,0.987110,0.986116,0.985501,0.986075,0.000626,13
13,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,13,COMPLETE,108.140076,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 227}",21.445534,0.385258,0.178067,0.009995,0.985245,0.986238,0.987109,0.986134,0.985469,0.986039,0.000656,14
20,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,20,COMPLETE,259.697658,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 293}",51.734617,0.597845,0.200370,0.009472,0.985296,0.986158,0.987045,0.986151,0.985422,0.986014,0.000628,15
25,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,25,COMPLETE,222.084793,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 265}",44.231530,0.483543,0.180927,0.004183,0.985295,0.986222,0.986948,0.986135,0.985471,0.986014,0.000590,16
0,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,0,COMPLETE,173.870518,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 183}",34.611260,0.655199,0.155274,0.006942,0.985113,0.985966,0.987131,0.986076,0.985521,0.985961,0.000678,17
22,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,22,COMPLETE,137.871486,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 255}",27.383461,0.576210,0.185596,0.007146,0.985214,0.986044,0.986980,0.986070,0.985405,0.985943,0.000620,18
14,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,14,COMPLETE,215.273673,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 259}",42.865479,0.408401,0.184503,0.008004,0.985144,0.985763,0.987221,0.985915,0.985607,0.985930,0.000695,19
2,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,2,COMPLETE,113.516819,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 134}",22.582512,0.284866,0.117657,0.007970,0.985215,0.986061,0.986933,0.986057,0.985358,0.985925,0.000613,20
8,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,8,COMPLETE,135.005417,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 8, ""classifier__n_estimators"": 287}",26.783661,0.437568,0.212301,0.007730,0.985039,0.985897,0.986787,0.985830,0.985163,0.985743,0.000625,21
12,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,12,COMPLETE,448.760585,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 260}",89.559982,1.072856,0.186257,0.007077,0.984717,0.985821,0.986811,0.985497,0.984952,0.985560,0.000737,22
6,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,6,COMPLETE,75.771737,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 154}",15.018998,0.357723,0.131934,0.004108,0.984743,0.985395,0.986497,0.985835,0.985321,0.985558,0.000584,23
15,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,15,COMPLETE,197.587602,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 223}",39.347326,0.349991,0.165682,0.007867,0.984576,0.985506,0.986946,0.985391,0.985077,0.985499,0.000792,24
9,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,9,COMPLETE,353.167566,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 211}",70.468559,0.734138,0.159849,0.004480,0.984434,0.985260,0.986167,0.985334,0.984492,0.985137,0.000637,25
7,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,7,COMPLETE,92.752971,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 100}",18.451400,0.348501,0.095819,0.004761,0.984373,0.984995,0.986589,0.984915,0.984652,0.985105,0.000773,26
1,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,1,COMPLETE,52.765016,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 105}",10.451852,0.151255,0.098097,0.001364,0.984294,0.984949,0.986544,0.985020,0.984477,0.985057,0.000793,27
4,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,4,COMPLETE,350.736261,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 215}",69.995084,0.497352,0.148813,0.004804,0.983803,0.984221,0.985520,0.984860,0.984213,0.984523,0.000602,28
5,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,5,COMPLETE,454.680106,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 281}",90.748011,0.591786,0.184568,0.010390,0.983178,0.983921,0.985150,0.984269,0.983671,0.984038,0.000660,29
18,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,18,COMPLETE,429.150567,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 10, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 287}",85.667544,0.402884,0.158727,0.001604,0.979867,0.982014,0.982361,0.982305,0.981253,0.981560,0.000934,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,1,45.098387,0.218933,0.958523,0.996125,0.976962,0.999022,0.989225,0.994099,0.985531,0.990605,0.992675
1,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,2,44.471061,0.234324,0.960133,0.997187,0.978309,0.999290,0.989649,0.994446,0.986378,0.991157,0.993418
2,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,3,44.155072,0.255840,0.962762,0.997665,0.979903,0.999411,0.990352,0.994861,0.987382,0.991815,0.994009
3,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,4,45.306342,0.224341,0.960501,0.996444,0.978143,0.999102,0.989755,0.994407,0.986275,0.991093,0.993100
4,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,5,46.175637,0.241847,0.957849,0.997505,0.977275,0.999370,0.989025,0.994171,0.985723,0.990721,0.993265

Modelo: random_forest | origem do treinamento: cicids2017_iot23

[I 2026-10-12 01:22:50,972] A new study created in memory with name: random_forest_cicids2017_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:25:08,089] Trial 0 finished with value: 0.9937451896022157 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.9937451896022157.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:25:55,679] Trial 1 finished with value: 0.9942134951922803 and parameters: {'classifier__n_estimators': 105, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 9, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 1 with value: 0.9942134951922803.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:27:29,469] Trial 2 finished with value: 0.993471259364069 and parameters: {'classifier__n_estimators': 134, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 7, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9942134951922803.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:29:19,202] Trial 3 finished with value: 0.9936692765876106 and parameters: {'classifier__n_estimators': 156, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9942134951922803.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:33:44,776] Trial 4 finished with value: 0.9931710173757906 and parameters: {'classifier__n_estimators': 215, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 7, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9942134951922803.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:39:26,891] Trial 5 finished with value: 0.9928218952617851 and parameters: {'classifier__n_estimators': 281, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 10, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9942134951922803.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:40:29,430] Trial 6 finished with value: 0.9934281793211698 and parameters: {'classifier__n_estimators': 154, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9942134951922803.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:41:49,955] Trial 7 finished with value: 0.9942331882524262 and parameters: {'classifier__n_estimators': 100, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 10, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 7 with value: 0.9942331882524262.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:43:47,105] Trial 8 finished with value: 0.993481635428657 and parameters: {'classifier__n_estimators': 287, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 8, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.9942331882524262.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:48:21,866] Trial 9 finished with value: 0.9933029867842318 and parameters: {'classifier__n_estimators': 211, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.9942331882524262.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:51:00,732] Trial 10 finished with value: 0.9942165863248477 and parameters: {'classifier__n_estimators': 198, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 10, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 7 with value: 0.9942331882524262.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:54:23,310] Trial 11 finished with value: 0.9942264031299167 and parameters: {'classifier__n_estimators': 254, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 9, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 7 with value: 0.9942331882524262.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 01:57:40,829] Trial 12 finished with value: 0.99448918332179 and parameters: {'classifier__n_estimators': 246, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 8, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 12 with value: 0.99448918332179.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:00:28,762] Trial 13 finished with value: 0.9945455476570293 and parameters: {'classifier__n_estimators': 206, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 13 with value: 0.9945455476570293.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:03:01,667] Trial 14 finished with value: 0.9945655055132647 and parameters: {'classifier__n_estimators': 186, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9945655055132647.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:06:19,702] Trial 15 finished with value: 0.9946415971747576 and parameters: {'classifier__n_estimators': 239, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 15 with value: 0.9946415971747576.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:08:37,490] Trial 16 finished with value: 0.9945689224803846 and parameters: {'classifier__n_estimators': 168, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 15 with value: 0.9946415971747576.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:12:14,877] Trial 17 finished with value: 0.9946665663723042 and parameters: {'classifier__n_estimators': 267, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 17 with value: 0.9946665663723042.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:15:40,590] Trial 18 finished with value: 0.9937215715686302 and parameters: {'classifier__n_estimators': 274, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 17 with value: 0.9946665663723042.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:19:03,649] Trial 19 finished with value: 0.9943818082506926 and parameters: {'classifier__n_estimators': 251, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 17 with value: 0.9946665663723042.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:23:02,062] Trial 20 finished with value: 0.994588681911603 and parameters: {'classifier__n_estimators': 295, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 17 with value: 0.9946665663723042.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:27:02,557] Trial 21 finished with value: 0.9945885999223056 and parameters: {'classifier__n_estimators': 297, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 17 with value: 0.9946665663723042.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:30:07,447] Trial 22 finished with value: 0.9946694348628566 and parameters: {'classifier__n_estimators': 225, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 22 with value: 0.9946694348628566.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:33:13,295] Trial 23 finished with value: 0.9946566166090733 and parameters: {'classifier__n_estimators': 227, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 22 with value: 0.9946694348628566.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:38:57,623] Trial 24 finished with value: 0.9944970771333825 and parameters: {'classifier__n_estimators': 241, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 1.0, 'classifier__class_weight': None}. Best is trial 22 with value: 0.9946694348628566.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:42:35,028] Trial 25 finished with value: 0.9946658707252698 and parameters: {'classifier__n_estimators': 268, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 22 with value: 0.9946694348628566.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:44:51,657] Trial 26 finished with value: 0.9946896598836892 and parameters: {'classifier__n_estimators': 297, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 'log2', 'classifier__class_weight': None}. Best is trial 26 with value: 0.9946896598836892.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:46:58,480] Trial 27 finished with value: 0.9946877741970439 and parameters: {'classifier__n_estimators': 284, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 'log2', 'classifier__class_weight': None}. Best is trial 26 with value: 0.9946896598836892.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:48:46,374] Trial 28 finished with value: 0.9925596905920742 and parameters: {'classifier__n_estimators': 300, 'classifier__max_depth': 10, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'log2', 'classifier__class_weight': None}. Best is trial 26 with value: 0.9946896598836892.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:50:41,959] Trial 29 finished with value: 0.9941462241187662 and parameters: {'classifier__n_estimators': 270, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 'log2', 'classifier__class_weight': None}. Best is trial 26 with value: 0.9946896598836892.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
26,random_forest,optuna,cicids2017_iot23,470980,30,5,1,26,COMPLETE,136.627672,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 297}",27.119721,0.342886,0.201629,0.009540,0.994750,0.994734,0.995194,0.994417,0.994354,0.994690,0.000299,1
27,random_forest,optuna,cicids2017_iot23,470980,30,5,1,27,COMPLETE,126.822822,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 284}",25.167443,0.349793,0.191980,0.007245,0.994601,0.994653,0.995345,0.994568,0.994272,0.994688,0.000354,2
22,random_forest,optuna,cicids2017_iot23,470980,30,5,1,22,COMPLETE,184.889233,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 225}",36.816773,0.338788,0.156576,0.005927,0.994618,0.994750,0.995210,0.994367,0.994403,0.994669,0.000305,3
17,random_forest,optuna,cicids2017_iot23,470980,30,5,1,17,COMPLETE,217.385886,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 267}",43.295444,0.505828,0.177762,0.009548,0.994551,0.994619,0.995393,0.994450,0.994321,0.994667,0.000377,4
25,random_forest,optuna,cicids2017_iot23,470980,30,5,1,25,COMPLETE,217.404795,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 268}",43.298533,0.371022,0.177774,0.003539,0.994650,0.994767,0.995177,0.994300,0.994436,0.994666,0.000303,5
23,random_forest,optuna,cicids2017_iot23,470980,30,5,1,23,COMPLETE,185.847178,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 227}",37.010840,0.494137,0.154717,0.005865,0.994501,0.994569,0.995426,0.994416,0.994371,0.994657,0.000391,6
15,random_forest,optuna,cicids2017_iot23,470980,30,5,1,15,COMPLETE,198.034325,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 239}",39.429274,1.215846,0.173370,0.008066,0.994568,0.994504,0.995230,0.994534,0.994372,0.994642,0.000301,7
20,random_forest,optuna,cicids2017_iot23,470980,30,5,1,20,COMPLETE,238.412321,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 295}",47.483766,0.464719,0.193222,0.007027,0.994552,0.994438,0.995131,0.994468,0.994356,0.994589,0.000278,8
21,random_forest,optuna,cicids2017_iot23,470980,30,5,1,21,COMPLETE,240.494410,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 297}",47.905326,0.374240,0.189181,0.005625,0.994552,0.994421,0.995147,0.994484,0.994339,0.994589,0.000288,9
16,random_forest,optuna,cicids2017_iot23,470980,30,5,1,16,COMPLETE,137.787602,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 168}",27.427900,0.217714,0.125865,0.007329,0.994519,0.994421,0.995231,0.994385,0.994289,0.994569,0.000339,10
14,random_forest,optuna,cicids2017_iot23,470980,30,5,1,14,COMPLETE,152.905172,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 186}",30.434561,0.274997,0.142625,0.004401,0.994519,0.994404,0.995197,0.994401,0.994306,0.994566,0.000323,11
13,random_forest,optuna,cicids2017_iot23,470980,30,5,1,13,COMPLETE,167.932248,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 206}",33.437290,0.417526,0.145376,0.006421,0.994552,0.994404,0.995148,0.994335,0.994289,0.994546,0.000314,12
24,random_forest,optuna,cicids2017_iot23,470980,30,5,1,24,COMPLETE,344.327815,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 241}",68.704364,1.027288,0.157294,0.006668,0.994335,0.994518,0.994945,0.994350,0.994338,0.994497,0.000234,13
12,random_forest,optuna,cicids2017_iot23,470980,30,5,1,12,COMPLETE,197.517859,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 8, ""classifier__n_estimators"": 246}",39.331920,0.510199,0.167215,0.006414,0.994469,0.994504,0.995147,0.994318,0.994007,0.994489,0.000373,14
19,random_forest,optuna,cicids2017_iot23,470980,30,5,1,19,COMPLETE,203.058815,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 251}",40.443483,0.421990,0.164351,0.005126,0.994517,0.994254,0.994980,0.994251,0.993907,0.994382,0.000357,15
7,random_forest,optuna,cicids2017_iot23,470980,30,5,1,7,COMPLETE,80.524459,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 100}",16.016089,0.259783,0.085768,0.000873,0.994320,0.994105,0.994964,0.994019,0.993757,0.994233,0.000408,16
11,random_forest,optuna,cicids2017_iot23,470980,30,5,1,11,COMPLETE,202.578026,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 254}",40.334432,0.414964,0.177566,0.008483,0.994303,0.994089,0.994848,0.994086,0.993807,0.994226,0.000348,17
10,random_forest,optuna,cicids2017_iot23,470980,30,5,1,10,COMPLETE,158.865425,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 198}",31.631540,0.409147,0.137785,0.002231,0.994203,0.994122,0.994864,0.994119,0.993774,0.994217,0.000356,18
1,random_forest,optuna,cicids2017_iot23,470980,30,5,1,1,COMPLETE,47.588936,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 105}",9.421657,0.115326,0.093145,0.004899,0.994286,0.993989,0.994998,0.994020,0.993775,0.994213,0.000425,19
29,random_forest,optuna,cicids2017_iot23,470980,30,5,1,29,COMPLETE,115.585110,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 270}",22.941345,0.379282,0.171401,0.006520,0.994336,0.994021,0.994715,0.993970,0.993690,0.994146,0.000351,20
0,random_forest,optuna,cicids2017_iot23,470980,30,5,1,0,COMPLETE,137.115112,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 183}",27.286037,0.091267,0.133775,0.007812,0.993942,0.993664,0.994222,0.993529,0.993369,0.993745,0.000304,21
18,random_forest,optuna,cicids2017_iot23,470980,30,5,1,18,COMPLETE,205.712876,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 274}",40.954983,0.636595,0.182839,0.007314,0.993830,0.993667,0.994240,0.993516,0.993356,0.993722,0.000303,22
3,random_forest,optuna,cicids2017_iot23,470980,30,5,1,3,COMPLETE,109.732196,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 156}",21.821605,0.379173,0.121586,0.008500,0.993796,0.993651,0.994175,0.993401,0.993324,0.993669,0.000304,23
8,random_forest,optuna,cicids2017_iot23,470980,30,5,1,8,COMPLETE,117.149648,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 8, ""classifier__n_estimators"": 287}",23.235720,0.346074,0.191110,0.007337,0.993733,0.993374,0.994062,0.993290,0.992949,0.993482,0.000383,24
2,random_forest,optuna,cicids2017_iot23,470980,30,5,1,2,COMPLETE,93.789500,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 134}",18.647591,0.370798,0.106607,0.004659,0.993667,0.993406,0.993931,0.993289,0.993063,0.993471,0.000301,25
6,random_forest,optuna,cicids2017_iot23,470980,30,5,1,6,COMPLETE,62.539069,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 154}",12.378991,0.228600,0.125778,0.008065,0.993520,0.993129,0.994045,0.993352,0.993094,0.993428,0.000345,26
9,random_forest,optuna,cicids2017_iot23,470980,30,5,1,9,COMPLETE,274.759992,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 211}",54.807197,0.649970,0.141617,0.006475,0.993535,0.993159,0.993929,0.993043,0.992849,0.993303,0.000385,27
4,random_forest,optuna,cicids2017_iot23,470980,30,5,1,4,COMPLETE,265.573748,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 215}",52.969760,0.881919,0.141521,0.006946,0.993469,0.992993,0.993681,0.992995,0.992717,0.993171,0.000351,28
5,random_forest,optuna,cicids2017_iot23,470980,30,5,1,5,COMPLETE,342.114087,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 281}",68.256620,0.909428,0.162505,0.006178,0.993175,0.992602,0.993437,0.992651,0.992245,0.992822,0.000427,29
28,random_forest,optuna,cicids2017_iot23,470980,30,5,1,28,COMPLETE,107.893151,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 300}",21.403777,0.646942,0.171110,0.011115,0.992964,0.992164,0.993411,0.992262,0.991998,0.992560,0.000538,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,random_forest,optuna,cicids2017_iot23,470980,30,5,1,1,26.835974,0.255701,0.989378,0.993842,0.991605,0.998459,0.997333,0.997896,0.994750,0.996635,0.995587
1,random_forest,optuna,cicids2017_iot23,470980,30,5,1,2,27.114510,0.250088,0.989377,0.993789,0.991578,0.998446,0.997333,0.997889,0.994734,0.996624,0.995561
2,random_forest,optuna,cicids2017_iot23,470980,30,5,1,3,26.465926,0.250673,0.991209,0.993418,0.992312,0.998354,0.997797,0.998075,0.995194,0.996921,0.995608
3,random_forest,optuna,cicids2017_iot23,470980,30,5,1,4,26.913750,0.241297,0.989420,0.992728,0.991071,0.998180,0.997346,0.997763,0.994417,0.996422,0.995037
4,random_forest,optuna,cicids2017_iot23,470980,30,5,1,5,27.256114,0.252145,0.988693,0.993259,0.990971,0.998313,0.997160,0.997736,0.994354,0.996380,0.995210

Modelo: random_forest | origem do treinamento: unsw_nb15_iot23

[I 2026-10-12 02:53:35,479] A new study created in memory with name: random_forest_unsw_nb15_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:55:33,646] Trial 0 finished with value: 0.9879970238181677 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.9879970238181677.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:56:13,781] Trial 1 finished with value: 0.9889181785467571 and parameters: {'classifier__n_estimators': 105, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 9, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 1 with value: 0.9889181785467571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:57:31,246] Trial 2 finished with value: 0.9877855009761017 and parameters: {'classifier__n_estimators': 134, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 7, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9889181785467571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 02:59:02,549] Trial 3 finished with value: 0.9881132666070362 and parameters: {'classifier__n_estimators': 156, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 0.5, 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9889181785467571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:03:00,213] Trial 4 finished with value: 0.9876190639058138 and parameters: {'classifier__n_estimators': 215, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 7, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9889181785467571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:08:08,503] Trial 5 finished with value: 0.9873733667381994 and parameters: {'classifier__n_estimators': 281, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 10, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9889181785467571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:09:04,046] Trial 6 finished with value: 0.988011256326925 and parameters: {'classifier__n_estimators': 154, 'classifier__max_depth': 15, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9889181785467571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:10:06,465] Trial 7 finished with value: 0.9889070306499468 and parameters: {'classifier__n_estimators': 100, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 10, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 1 with value: 0.9889181785467571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:11:47,829] Trial 8 finished with value: 0.9875228818183966 and parameters: {'classifier__n_estimators': 287, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 8, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9889181785467571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:15:42,100] Trial 9 finished with value: 0.9877043112497951 and parameters: {'classifier__n_estimators': 211, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 1.0, 'classifier__class_weight': 'balanced'}. Best is trial 1 with value: 0.9889181785467571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:16:23,495] Trial 10 finished with value: 0.9882408698762349 and parameters: {'classifier__n_estimators': 104, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 1 with value: 0.9889181785467571.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:17:07,952] Trial 11 finished with value: 0.9889310522559956 and parameters: {'classifier__n_estimators': 117, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 9, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 11 with value: 0.9889310522559956.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:17:49,589] Trial 12 finished with value: 0.9889998652204849 and parameters: {'classifier__n_estimators': 106, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 7, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 12 with value: 0.9889998652204849.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:18:40,630] Trial 13 finished with value: 0.989041202399844 and parameters: {'classifier__n_estimators': 133, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 13 with value: 0.989041202399844.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:19:43,580] Trial 14 finished with value: 0.989094824656337 and parameters: {'classifier__n_estimators': 164, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 14 with value: 0.989094824656337.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:20:33,578] Trial 15 finished with value: 0.989127342164819 and parameters: {'classifier__n_estimators': 129, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 15 with value: 0.989127342164819.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:21:59,927] Trial 16 finished with value: 0.9890948253912981 and parameters: {'classifier__n_estimators': 228, 'classifier__max_depth': None, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 15 with value: 0.989127342164819.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:23:47,540] Trial 17 finished with value: 0.9890926995776919 and parameters: {'classifier__n_estimators': 284, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 6, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 15 with value: 0.989127342164819.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:25:18,475] Trial 18 finished with value: 0.9891183971251166 and parameters: {'classifier__n_estimators': 240, 'classifier__max_depth': 30, 'classifier__min_samples_leaf': 5, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 15 with value: 0.989127342164819.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:29:47,877] Trial 19 finished with value: 0.9888722573749499 and parameters: {'classifier__n_estimators': 225, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 1.0, 'classifier__class_weight': None}. Best is trial 15 with value: 0.989127342164819.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:30:43,195] Trial 20 finished with value: 0.989173573231445 and parameters: {'classifier__n_estimators': 143, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 20 with value: 0.989173573231445.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:31:45,383] Trial 21 finished with value: 0.9891933022705348 and parameters: {'classifier__n_estimators': 161, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 21 with value: 0.9891933022705348.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:32:43,812] Trial 22 finished with value: 0.9891868237993465 and parameters: {'classifier__n_estimators': 150, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 21 with value: 0.9891933022705348.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:34:00,673] Trial 23 finished with value: 0.9890390383181991 and parameters: {'classifier__n_estimators': 196, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 21 with value: 0.9891933022705348.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:34:50,886] Trial 24 finished with value: 0.9887474411668904 and parameters: {'classifier__n_estimators': 147, 'classifier__max_depth': 10, 'classifier__min_samples_leaf': 2, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 21 with value: 0.9891933022705348.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:35:55,482] Trial 25 finished with value: 0.9891565428604647 and parameters: {'classifier__n_estimators': 168, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 21 with value: 0.9891933022705348.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:36:41,274] Trial 26 finished with value: 0.9881787649509688 and parameters: {'classifier__n_estimators': 124, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced'}. Best is trial 21 with value: 0.9891933022705348.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:38:15,044] Trial 27 finished with value: 0.9889209649537112 and parameters: {'classifier__n_estimators': 146, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 0.5, 'classifier__class_weight': None}. Best is trial 21 with value: 0.9891933022705348.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:38:51,732] Trial 28 finished with value: 0.9886488059029069 and parameters: {'classifier__n_estimators': 106, 'classifier__max_depth': 10, 'classifier__min_samples_leaf': 4, 'classifier__max_features': 'sqrt', 'classifier__class_weight': None}. Best is trial 21 with value: 0.9891933022705348.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:40:12,655] Trial 29 finished with value: 0.9880335880715172 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': 20, 'classifier__min_samples_leaf': 3, 'classifier__max_features': 'sqrt', 'classifier__class_weight': 'balanced_subsample'}. Best is trial 21 with value: 0.9891933022705348.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
21,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,21,COMPLETE,62.187912,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 161}",12.304963,0.276612,0.128906,0.010603,0.989227,0.989605,0.989182,0.988892,0.989060,0.989193,0.000236,1
22,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,22,COMPLETE,58.428510,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 150}",11.563599,0.398657,0.118215,0.003704,0.989210,0.989654,0.989150,0.988860,0.989060,0.989187,0.000262,2
20,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,20,COMPLETE,55.317420,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 143}",10.941498,0.228808,0.117279,0.006978,0.989211,0.989588,0.989117,0.988893,0.989060,0.989174,0.000232,3
25,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,25,COMPLETE,64.595148,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 168}",12.787090,0.201064,0.128136,0.003896,0.989197,0.989475,0.989072,0.988847,0.989192,0.989157,0.000204,4
15,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,15,COMPLETE,49.997298,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 129}",9.887442,0.194009,0.107463,0.005475,0.989198,0.989476,0.989022,0.988748,0.989192,0.989127,0.000239,5
18,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,18,COMPLETE,90.933982,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 240}",18.010084,0.274442,0.171740,0.008533,0.989129,0.989439,0.989170,0.988779,0.989075,0.989118,0.000211,6
16,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,16,COMPLETE,86.348106,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 228}",17.107253,0.272509,0.158398,0.005689,0.989112,0.989422,0.989087,0.988778,0.989075,0.989095,0.000204,7
14,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,14,COMPLETE,62.948865,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 5, ""classifier__n_estimators"": 164}",12.462002,0.256507,0.123923,0.005489,0.989112,0.989423,0.989120,0.988745,0.989075,0.989095,0.000215,8
17,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,17,COMPLETE,107.612940,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 284}",21.330301,0.452116,0.188257,0.007486,0.989199,0.989411,0.989008,0.988767,0.989078,0.989093,0.000213,9
13,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,13,COMPLETE,51.040503,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 133}",10.095797,0.271314,0.108567,0.002717,0.989166,0.989412,0.989024,0.988525,0.989079,0.989041,0.000290,10
23,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,23,COMPLETE,76.860544,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 196}",15.222894,0.277810,0.145164,0.007358,0.989011,0.989438,0.989166,0.988691,0.988890,0.989039,0.000253,11
12,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,12,COMPLETE,41.636402,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 106}",8.226736,0.183416,0.096822,0.007625,0.989099,0.989411,0.989057,0.988373,0.989059,0.989000,0.000340,12
11,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,11,COMPLETE,44.456450,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 117}",8.786913,0.169208,0.100823,0.006844,0.989035,0.989413,0.988881,0.988444,0.988882,0.988931,0.000311,13
27,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,27,COMPLETE,93.769378,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 146}",18.635680,0.174746,0.114354,0.008952,0.988858,0.989316,0.988961,0.988681,0.988788,0.988921,0.000218,14
1,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,1,COMPLETE,40.134495,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 9, ""classifier__n_estimators"": 105}",7.928136,0.159427,0.095661,0.006168,0.989035,0.989380,0.988897,0.988445,0.988834,0.988918,0.000303,15
7,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,7,COMPLETE,62.418243,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 100}",12.395677,0.207394,0.084577,0.000618,0.988959,0.989176,0.988957,0.988628,0.988815,0.988907,0.000181,16
19,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,19,COMPLETE,269.401541,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 225}",53.727547,0.697063,0.148873,0.005603,0.988662,0.989384,0.988961,0.988651,0.988704,0.988872,0.000280,17
24,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,24,COMPLETE,50.212304,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 147}",9.933034,0.230168,0.105755,0.011230,0.988821,0.989218,0.988751,0.988178,0.988769,0.988747,0.000332,18
28,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,28,COMPLETE,36.688271,"{""classifier__class_weight"": null, ""classifier__max_depth"": 10, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 4, ""classifier__n_estimators"": 106}",7.247165,0.172422,0.086846,0.003974,0.988738,0.989168,0.988490,0.988128,0.988719,0.988649,0.000340,19
10,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,10,COMPLETE,41.395103,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 104}",8.171920,0.194366,0.102114,0.008167,0.988333,0.988524,0.988437,0.987873,0.988038,0.988241,0.000246,20
26,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,26,COMPLETE,45.791097,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 124}",9.047112,0.211612,0.107162,0.006250,0.988397,0.988643,0.988013,0.987968,0.987873,0.988179,0.000293,21
3,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,3,COMPLETE,91.302046,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 156}",18.138716,0.434179,0.118217,0.006512,0.988402,0.988481,0.988048,0.987696,0.987940,0.988113,0.000292,22
29,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,29,COMPLETE,80.922618,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 183}",16.052397,0.700229,0.128185,0.001642,0.988303,0.988435,0.987954,0.987599,0.987877,0.988034,0.000301,23
6,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,6,COMPLETE,55.542837,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 154}",10.983904,0.311293,0.121433,0.004209,0.988385,0.988451,0.987955,0.987324,0.987941,0.988011,0.000403,24
0,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,0,COMPLETE,118.164676,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 183}",23.497884,0.356008,0.130759,0.005075,0.988256,0.988352,0.987802,0.987662,0.987913,0.987997,0.000265,25
2,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,2,COMPLETE,77.465012,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 134}",15.381716,0.194185,0.107990,0.009962,0.988143,0.988079,0.987680,0.987454,0.987571,0.987786,0.000276,26
9,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,9,COMPLETE,234.270017,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 6, ""classifier__n_estimators"": 211}",46.708957,0.918907,0.141703,0.006852,0.987846,0.988154,0.987679,0.987436,0.987406,0.987704,0.000277,27
4,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,4,COMPLETE,237.663850,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 7, ""classifier__n_estimators"": 215}",47.396646,0.706115,0.131922,0.005884,0.987849,0.988059,0.987568,0.987373,0.987246,0.987619,0.000300,28
8,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,8,COMPLETE,101.363558,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 8, ""classifier__n_estimators"": 287}",20.082835,0.464648,0.186606,0.001978,0.988017,0.987822,0.987442,0.987084,0.987250,0.987523,0.000349,29
5,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,5,COMPLETE,308.289194,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__max_features"": 1.0, ""classifier__min_samples_leaf"": 10, ""classifier__n_estimators"": 281}",61.494533,0.938274,0.160078,0.001916,0.987637,0.987478,0.987358,0.987292,0.987102,0.987373,0.000180,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,1,12.019520,0.165711,0.971771,0.994108,0.982812,0.998519,0.992781,0.995642,0.989227,0.993046,0.993444
1,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,2,12.497442,0.165767,0.972441,0.994638,0.983415,0.998652,0.992954,0.995795,0.989605,0.993291,0.993796
2,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,3,12.073140,0.180650,0.971280,0.994480,0.982743,0.998612,0.992648,0.995621,0.989182,0.993015,0.993564
3,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,4,12.103709,0.163761,0.970131,0.994745,0.982284,0.998678,0.992343,0.995500,0.988892,0.992823,0.993544
4,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,5,12.677971,0.179673,0.969952,0.995488,0.982554,0.998865,0.992290,0.995566,0.989060,0.992930,0.993889

Modelo: xgboost | origem do treinamento: cicids2017

[I 2026-10-12 03:41:31,933] A new study created in memory with name: xgboost_cicids2017
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:41:38,023] Trial 0 finished with value: 0.9913423758771067 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.03000790177293386, 'classifier__subsample': 0.7906997717895519, 'classifier__colsample_bytree': 0.7440267672451338}. Best is trial 0 with value: 0.9913423758771067.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:41:41,341] Trial 1 finished with value: 0.9895671650438622 and parameters: {'classifier__n_estimators': 118, 'classifier__max_depth': 4, 'classifier__learning_rate': 0.06647861789041172, 'classifier__subsample': 0.819030242269201, 'classifier__colsample_bytree': 0.8616450202010071}. Best is trial 0 with value: 0.9913423758771067.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:41:46,453] Trial 2 finished with value: 0.9915409239121808 and parameters: {'classifier__n_estimators': 184, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.0480367375659992, 'classifier__subsample': 0.9634352309172836, 'classifier__colsample_bytree': 0.7082162779593778}. Best is trial 2 with value: 0.9915409239121808.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:41:52,550] Trial 3 finished with value: 0.9916000992652858 and parameters: {'classifier__n_estimators': 234, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.10859531344085706, 'classifier__subsample': 0.7421160815785701, 'classifier__colsample_bytree': 0.7594304467254636}. Best is trial 3 with value: 0.9916000992652858.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:41:59,714] Trial 4 finished with value: 0.9917706461343988 and parameters: {'classifier__n_estimators': 260, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06173698734681893, 'classifier__subsample': 0.9076967847007942, 'classifier__colsample_bytree': 0.9629167456888115}. Best is trial 4 with value: 0.9917706461343988.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:42:05,725] Trial 5 finished with value: 0.9874193681715534 and parameters: {'classifier__n_estimators': 279, 'classifier__max_depth': 3, 'classifier__learning_rate': 0.032822831099235304, 'classifier__subsample': 0.7509491258693707, 'classifier__colsample_bytree': 0.9634427510288239}. Best is trial 4 with value: 0.9917706461343988.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:42:09,365] Trial 6 finished with value: 0.991657764978321 and parameters: {'classifier__n_estimators': 119, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.27227689219802986, 'classifier__subsample': 0.859949585491905, 'classifier__colsample_bytree': 0.907563134185142}. Best is trial 4 with value: 0.9917706461343988.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:42:14,420] Trial 7 finished with value: 0.9915205920943926 and parameters: {'classifier__n_estimators': 163, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.20499672676341157, 'classifier__subsample': 0.7054864832032575, 'classifier__colsample_bytree': 0.9250432944834902}. Best is trial 4 with value: 0.9917706461343988.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:42:21,968] Trial 8 finished with value: 0.9918119920780665 and parameters: {'classifier__n_estimators': 298, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.05722229168328298, 'classifier__subsample': 0.9367837985354466, 'classifier__colsample_bytree': 0.7309678019732926}. Best is trial 8 with value: 0.9918119920780665.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:42:27,959] Trial 9 finished with value: 0.9918990493905431 and parameters: {'classifier__n_estimators': 190, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.05898416056128349, 'classifier__subsample': 0.7863326015759046, 'classifier__colsample_bytree': 0.7390085716354833}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:42:33,842] Trial 10 finished with value: 0.9913819810697522 and parameters: {'classifier__n_estimators': 171, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.03374094527095239, 'classifier__subsample': 0.9390633079309185, 'classifier__colsample_bytree': 0.8114686242883993}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:42:41,962] Trial 11 finished with value: 0.99183604658962 and parameters: {'classifier__n_estimators': 290, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.0675693609485163, 'classifier__subsample': 0.8656127913905788, 'classifier__colsample_bytree': 0.733728951824139}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:42:48,083] Trial 12 finished with value: 0.9918373599567392 and parameters: {'classifier__n_estimators': 228, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.11173366728075725, 'classifier__subsample': 0.8430917576976493, 'classifier__colsample_bytree': 0.7292092968714783}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:42:53,626] Trial 13 finished with value: 0.9916099442815414 and parameters: {'classifier__n_estimators': 209, 'classifier__max_depth': 6, 'classifier__learning_rate': 0.19568000346960662, 'classifier__subsample': 0.8375463555846466, 'classifier__colsample_bytree': 0.7500779718114516}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:42:58,152] Trial 14 finished with value: 0.9915416357007125 and parameters: {'classifier__n_estimators': 138, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.043778217352987175, 'classifier__subsample': 0.825169088270381, 'classifier__colsample_bytree': 0.7264072230985587}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:43:03,850] Trial 15 finished with value: 0.9917399968312697 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06020444052797918, 'classifier__subsample': 0.7860516143714918, 'classifier__colsample_bytree': 0.8025076810805891}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:43:08,637] Trial 16 finished with value: 0.9914687289034921 and parameters: {'classifier__n_estimators': 161, 'classifier__max_depth': 6, 'classifier__learning_rate': 0.07807955333289543, 'classifier__subsample': 0.7874765304579947, 'classifier__colsample_bytree': 0.7040668702126329}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:43:15,165] Trial 17 finished with value: 0.9914349229940479 and parameters: {'classifier__n_estimators': 217, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.15923872741980838, 'classifier__subsample': 0.7814914087880903, 'classifier__colsample_bytree': 0.8274196839395644}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:43:22,358] Trial 18 finished with value: 0.991856802225404 and parameters: {'classifier__n_estimators': 247, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06260183849962903, 'classifier__subsample': 0.8510629978508164, 'classifier__colsample_bytree': 0.7214003228333933}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:43:28,119] Trial 19 finished with value: 0.9917729607591481 and parameters: {'classifier__n_estimators': 166, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.08230658240473691, 'classifier__subsample': 0.924169654878658, 'classifier__colsample_bytree': 0.7669125248140473}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:43:36,616] Trial 20 finished with value: 0.9918837327014899 and parameters: {'classifier__n_estimators': 284, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06419947264585936, 'classifier__subsample': 0.7647509599188942, 'classifier__colsample_bytree': 0.8539187318137799}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:43:44,881] Trial 21 finished with value: 0.9916633926452674 and parameters: {'classifier__n_estimators': 279, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.07174949440694982, 'classifier__subsample': 0.73578794294661, 'classifier__colsample_bytree': 0.8430014019307733}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:43:52,063] Trial 22 finished with value: 0.9915861408371022 and parameters: {'classifier__n_estimators': 260, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.04119765632743507, 'classifier__subsample': 0.7716557233015587, 'classifier__colsample_bytree': 0.8338003540350899}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:43:59,464] Trial 23 finished with value: 0.9918318810663678 and parameters: {'classifier__n_estimators': 249, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.059091273400699314, 'classifier__subsample': 0.7198211444824247, 'classifier__colsample_bytree': 0.7775785428208108}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:44:06,426] Trial 24 finished with value: 0.9917204950392762 and parameters: {'classifier__n_estimators': 238, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.042238465333893936, 'classifier__subsample': 0.797546404946494, 'classifier__colsample_bytree': 0.7689218792766438}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:44:13,647] Trial 25 finished with value: 0.9917305656925064 and parameters: {'classifier__n_estimators': 247, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.08684192690013923, 'classifier__subsample': 0.839977464664921, 'classifier__colsample_bytree': 0.8023965911625831}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:44:21,527] Trial 26 finished with value: 0.9918183248112793 and parameters: {'classifier__n_estimators': 291, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.05181216902672782, 'classifier__subsample': 0.7569635952564551, 'classifier__colsample_bytree': 0.875275855141271}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:44:29,017] Trial 27 finished with value: 0.9917850036269389 and parameters: {'classifier__n_estimators': 270, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.047247883202550946, 'classifier__subsample': 0.8269872197207402, 'classifier__colsample_bytree': 0.7177801111553842}. Best is trial 9 with value: 0.9918990493905431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:44:37,172] Trial 28 finished with value: 0.991827160169841 and parameters: {'classifier__n_estimators': 287, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.038799558642045505, 'classifier__subsample': 0.7792413826130057, 'classifier__colsample_bytree': 0.7894137702726823}. Best is trial 9 with value: 0.9918990493905431.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
9,xgboost,optuna,cicids2017,235490,30,5,1,9,COMPLETE,5.990426,"{""classifier__colsample_bytree"": 0.7390085716354833, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 190, ""classifier__subsample"": 0.7863326015759046}",1.152035,0.062117,0.042842,0.003203,0.992209,0.991885,0.992770,0.991375,0.991256,0.991899,0.000555,1
20,xgboost,optuna,cicids2017,235490,30,5,1,20,COMPLETE,8.496427,"{""classifier__colsample_bytree"": 0.8539187318137799, ""classifier__learning_rate"": 0.06419947264585936, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 284, ""classifier__subsample"": 0.7647509599188942}",1.642378,0.130388,0.052492,0.002870,0.992276,0.991716,0.992699,0.991508,0.991219,0.991884,0.000535,2
18,xgboost,optuna,cicids2017,235490,30,5,1,18,COMPLETE,7.192721,"{""classifier__colsample_bytree"": 0.7214003228333933, ""classifier__learning_rate"": 0.06260183849962903, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 247, ""classifier__subsample"": 0.8510629978508164}",1.377111,0.081957,0.056535,0.010540,0.992344,0.991913,0.992701,0.991270,0.991056,0.991857,0.000622,3
12,xgboost,optuna,cicids2017,235490,30,5,1,12,COMPLETE,6.120263,"{""classifier__colsample_bytree"": 0.7292092968714783, ""classifier__learning_rate"": 0.11173366728075725, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 228, ""classifier__subsample"": 0.8430917576976493}",1.174193,0.074046,0.045804,0.003002,0.992244,0.991948,0.992435,0.991441,0.991118,0.991837,0.000492,4
11,xgboost,optuna,cicids2017,235490,30,5,1,11,COMPLETE,8.119457,"{""classifier__colsample_bytree"": 0.733728951824139, ""classifier__learning_rate"": 0.0675693609485163, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 290, ""classifier__subsample"": 0.8656127913905788}",1.557565,0.087129,0.061642,0.013765,0.992377,0.991610,0.992469,0.991507,0.991217,0.991836,0.000497,5
23,xgboost,optuna,cicids2017,235490,30,5,1,23,COMPLETE,7.400574,"{""classifier__colsample_bytree"": 0.7775785428208108, ""classifier__learning_rate"": 0.059091273400699314, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 249, ""classifier__subsample"": 0.7198211444824247}",1.425070,0.064091,0.050398,0.003241,0.992112,0.991818,0.992569,0.991408,0.991253,0.991832,0.000477,6
28,xgboost,optuna,cicids2017,235490,30,5,1,28,COMPLETE,8.154966,"{""classifier__colsample_bytree"": 0.7894137702726823, ""classifier__learning_rate"": 0.038799558642045505, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 287, ""classifier__subsample"": 0.7792413826130057}",1.572305,0.064968,0.053975,0.003730,0.992110,0.991752,0.992636,0.991545,0.991092,0.991827,0.000521,7
26,xgboost,optuna,cicids2017,235490,30,5,1,26,COMPLETE,7.879179,"{""classifier__colsample_bytree"": 0.875275855141271, ""classifier__learning_rate"": 0.05181216902672782, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 291, ""classifier__subsample"": 0.7569635952564551}",1.519653,0.074408,0.051655,0.003320,0.992210,0.991751,0.992498,0.991441,0.991192,0.991818,0.000481,8
8,xgboost,optuna,cicids2017,235490,30,5,1,8,COMPLETE,7.547425,"{""classifier__colsample_bytree"": 0.7309678019732926, ""classifier__learning_rate"": 0.05722229168328298, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9367837985354466}",1.453774,0.111812,0.052393,0.005218,0.992277,0.991946,0.992401,0.991341,0.991095,0.991812,0.000513,9
29,xgboost,optuna,cicids2017,235490,30,5,1,29,COMPLETE,6.194206,"{""classifier__colsample_bytree"": 0.7560746527807743, ""classifier__learning_rate"": 0.06816439477038028, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 202, ""classifier__subsample"": 0.7754727611883925}",1.188806,0.078408,0.045713,0.007523,0.992077,0.991951,0.992332,0.991405,0.991222,0.991798,0.000418,10
27,xgboost,optuna,cicids2017,235490,30,5,1,27,COMPLETE,7.489378,"{""classifier__colsample_bytree"": 0.7177801111553842, ""classifier__learning_rate"": 0.047247883202550946, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 270, ""classifier__subsample"": 0.8269872197207402}",1.441863,0.060402,0.051629,0.003189,0.992213,0.991678,0.992635,0.991440,0.990959,0.991785,0.000586,11
19,xgboost,optuna,cicids2017,235490,30,5,1,19,COMPLETE,5.760537,"{""classifier__colsample_bytree"": 0.7669125248140473, ""classifier__learning_rate"": 0.08230658240473691, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 166, ""classifier__subsample"": 0.924169654878658}",1.098786,0.125142,0.048750,0.006468,0.992145,0.991951,0.992372,0.991307,0.991089,0.991773,0.000493,12
4,xgboost,optuna,cicids2017,235490,30,5,1,4,COMPLETE,7.163397,"{""classifier__colsample_bytree"": 0.9629167456888115, ""classifier__learning_rate"": 0.06173698734681893, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 260, ""classifier__subsample"": 0.9076967847007942}",1.379072,0.075593,0.050300,0.003384,0.992177,0.991646,0.992537,0.991339,0.991154,0.991771,0.000517,13
15,xgboost,optuna,cicids2017,235490,30,5,1,15,COMPLETE,5.696993,"{""classifier__colsample_bytree"": 0.8025076810805891, ""classifier__learning_rate"": 0.06020444052797918, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 183, ""classifier__subsample"": 0.7860516143714918}",1.092670,0.083172,0.042765,0.003479,0.992212,0.991785,0.992469,0.991244,0.990991,0.991740,0.000559,14
25,xgboost,optuna,cicids2017,235490,30,5,1,25,COMPLETE,7.220440,"{""classifier__colsample_bytree"": 0.8023965911625831, ""classifier__learning_rate"": 0.08684192690013923, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 247, ""classifier__subsample"": 0.839977464664921}",1.390104,0.060308,0.049750,0.003191,0.992176,0.991586,0.992533,0.991271,0.991087,0.991731,0.000546,15
24,xgboost,optuna,cicids2017,235490,30,5,1,24,COMPLETE,6.960805,"{""classifier__colsample_bytree"": 0.7689218792766438, ""classifier__learning_rate"": 0.042238465333893936, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 238, ""classifier__subsample"": 0.797546404946494}",1.337700,0.120503,0.050355,0.004520,0.991914,0.991752,0.992438,0.991341,0.991158,0.991720,0.000450,16
21,xgboost,optuna,cicids2017,235490,30,5,1,21,COMPLETE,8.264372,"{""classifier__colsample_bytree"": 0.8430014019307733, ""classifier__learning_rate"": 0.07174949440694982, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 279, ""classifier__subsample"": 0.73578794294661}",1.597151,0.117171,0.051344,0.001267,0.992244,0.991516,0.992103,0.991368,0.991086,0.991663,0.000441,17
6,xgboost,optuna,cicids2017,235490,30,5,1,6,COMPLETE,3.638957,"{""classifier__colsample_bytree"": 0.907563134185142, ""classifier__learning_rate"": 0.27227689219802986, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 119, ""classifier__subsample"": 0.859949585491905}",0.693407,0.068968,0.031281,0.003598,0.992012,0.991615,0.992403,0.991140,0.991119,0.991658,0.000498,18
13,xgboost,optuna,cicids2017,235490,30,5,1,13,COMPLETE,5.542686,"{""classifier__colsample_bytree"": 0.7500779718114516, ""classifier__learning_rate"": 0.19568000346960662, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 209, ""classifier__subsample"": 0.8375463555846466}",1.064322,0.076575,0.040047,0.002733,0.991914,0.991480,0.992200,0.991206,0.991251,0.991610,0.000387,19
3,xgboost,optuna,cicids2017,235490,30,5,1,3,COMPLETE,6.096023,"{""classifier__colsample_bytree"": 0.7594304467254636, ""classifier__learning_rate"": 0.10859531344085706, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 234, ""classifier__subsample"": 0.7421160815785701}",1.171974,0.105553,0.043978,0.005751,0.991844,0.991452,0.992570,0.991208,0.990926,0.991600,0.000571,20
22,xgboost,optuna,cicids2017,235490,30,5,1,22,COMPLETE,7.181271,"{""classifier__colsample_bytree"": 0.8338003540350899, ""classifier__learning_rate"": 0.04119765632743507, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 260, ""classifier__subsample"": 0.7716557233015587}",1.384975,0.105198,0.046918,0.002890,0.991878,0.991482,0.992337,0.991342,0.990892,0.991586,0.000490,21
14,xgboost,optuna,cicids2017,235490,30,5,1,14,COMPLETE,4.525250,"{""classifier__colsample_bytree"": 0.7264072230985587, ""classifier__learning_rate"": 0.043778217352987175, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 138, ""classifier__subsample"": 0.825169088270381}",0.865372,0.073072,0.035695,0.001206,0.991946,0.991319,0.992504,0.991013,0.990926,0.991542,0.000600,22
2,xgboost,optuna,cicids2017,235490,30,5,1,2,COMPLETE,5.111030,"{""classifier__colsample_bytree"": 0.7082162779593778, ""classifier__learning_rate"": 0.0480367375659992, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 184, ""classifier__subsample"": 0.9634352309172836}",0.978038,0.083377,0.040943,0.003219,0.991846,0.991517,0.992402,0.991112,0.990827,0.991541,0.000553,23
7,xgboost,optuna,cicids2017,235490,30,5,1,7,COMPLETE,5.054465,"{""classifier__colsample_bytree"": 0.9250432944834902, ""classifier__learning_rate"": 0.20499672676341157, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 163, ""classifier__subsample"": 0.7054864832032575}",0.969879,0.071179,0.037761,0.001955,0.992042,0.991279,0.991994,0.991238,0.991050,0.991521,0.000414,24
16,xgboost,optuna,cicids2017,235490,30,5,1,16,COMPLETE,4.786426,"{""classifier__colsample_bytree"": 0.7040668702126329, ""classifier__learning_rate"": 0.07807955333289543, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 161, ""classifier__subsample"": 0.7874765304579947}",0.916042,0.072389,0.036576,0.002734,0.991747,0.991387,0.992304,0.990982,0.990924,0.991469,0.000513,25
17,xgboost,optuna,cicids2017,235490,30,5,1,17,COMPLETE,6.527152,"{""classifier__colsample_bytree"": 0.8274196839395644, ""classifier__learning_rate"": 0.15923872741980838, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 217, ""classifier__subsample"": 0.7814914087880903}",1.251334,0.074363,0.049869,0.007508,0.992143,0.991281,0.991862,0.991034,0.990855,0.991435,0.000491,26
10,xgboost,optuna,cicids2017,235490,30,5,1,10,COMPLETE,5.882285,"{""classifier__colsample_bytree"": 0.8114686242883993, ""classifier__learning_rate"": 0.03374094527095239, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 171, ""classifier__subsample"": 0.9390633079309185}",1.124872,0.097249,0.046015,0.006258,0.991814,0.991253,0.992303,0.990815,0.990725,0.991382,0.000601,27
0,xgboost,optuna,cicids2017,235490,30,5,1,0,COMPLETE,6.088391,"{""classifier__colsample_bytree"": 0.7440267672451338, ""classifier__learning_rate"": 0.03000790177293386, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 183, ""classifier__subsample"": 0.7906997717895519}",1.167006,0.141326,0.047531,0.008820,0.991879,0.991220,0.992270,0.990779,0.990563,0.991342,0.000646,28
1,xgboost,optuna,cicids2017,235490,30,5,1,1,COMPLETE,3.317579,"{""classifier__colsample_bytree"": 0.8616450202010071, ""classifier__learning_rate"": 0.06647861789041172, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 118, ""classifier__subsample"": 0.819030242269201}",0.631182,0.073680,0.029250,0.002724,0.990058,0.989102,0.990619,0.989386,0.988670,0.989567,0.000693,29
5,xgboost,optuna,cicids2017,235490,30,5,1,5,COMPLETE,6.010499,"{""classifier__colsample_bytree"": 0.9634427510288239, ""classifier__learning_rate"": 0.032822831099235304, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 279, ""classifier__subsample"": 0.7509491258693707}",1.162647,0.074598,0.036238,0.002181,0.987928,0.987192,0.988658,0.986417,0.986902,0.987419,0.000789,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,xgboost,optuna,cicids2017,235490,30,5,1,1,1.054496,0.086788,0.981138,0.994055,0.987554,0.998509,0.995223,0.996863,0.992209,0.994989,0.994639
1,xgboost,optuna,cicids2017,235490,30,5,1,2,1.056201,0.085181,0.979509,0.994692,0.987042,0.998668,0.994798,0.996729,0.991885,0.994777,0.994745
2,xgboost,optuna,cicids2017,235490,30,5,1,3,1.159712,0.086482,0.982081,0.994904,0.988451,0.998722,0.995462,0.997089,0.992770,0.995350,0.995183
3,xgboost,optuna,cicids2017,235490,30,5,1,4,1.051118,0.089128,0.981192,0.991295,0.986217,0.997818,0.995249,0.996532,0.991375,0.994458,0.993272
4,xgboost,optuna,cicids2017,235490,30,5,1,5,1.076604,0.085384,0.978968,0.993206,0.986036,0.998295,0.994665,0.996477,0.991256,0.994373,0.993936

Modelo: xgboost | origem do treinamento: unsw_nb15

[I 2026-10-12 03:44:51,002] A new study created in memory with name: xgboost_unsw_nb15
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:44:57,361] Trial 0 finished with value: 0.9805973956627607 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.03000790177293386, 'classifier__subsample': 0.7906997717895519, 'classifier__colsample_bytree': 0.7440267672451338}. Best is trial 0 with value: 0.9805973956627607.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:45:00,723] Trial 1 finished with value: 0.9782584590487113 and parameters: {'classifier__n_estimators': 118, 'classifier__max_depth': 4, 'classifier__learning_rate': 0.06647861789041172, 'classifier__subsample': 0.819030242269201, 'classifier__colsample_bytree': 0.8616450202010071}. Best is trial 0 with value: 0.9805973956627607.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:45:06,138] Trial 2 finished with value: 0.9808004529293013 and parameters: {'classifier__n_estimators': 184, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.0480367375659992, 'classifier__subsample': 0.9634352309172836, 'classifier__colsample_bytree': 0.7082162779593778}. Best is trial 2 with value: 0.9808004529293013.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:45:12,348] Trial 3 finished with value: 0.9808771950792243 and parameters: {'classifier__n_estimators': 234, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.10859531344085706, 'classifier__subsample': 0.7421160815785701, 'classifier__colsample_bytree': 0.7594304467254636}. Best is trial 3 with value: 0.9808771950792243.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:45:20,190] Trial 4 finished with value: 0.981001547653573 and parameters: {'classifier__n_estimators': 260, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06173698734681893, 'classifier__subsample': 0.9076967847007942, 'classifier__colsample_bytree': 0.9629167456888115}. Best is trial 4 with value: 0.981001547653573.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:45:26,352] Trial 5 finished with value: 0.974587589138225 and parameters: {'classifier__n_estimators': 279, 'classifier__max_depth': 3, 'classifier__learning_rate': 0.032822831099235304, 'classifier__subsample': 0.7509491258693707, 'classifier__colsample_bytree': 0.9634427510288239}. Best is trial 4 with value: 0.981001547653573.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:45:29,971] Trial 6 finished with value: 0.9808412484550454 and parameters: {'classifier__n_estimators': 119, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.27227689219802986, 'classifier__subsample': 0.859949585491905, 'classifier__colsample_bytree': 0.907563134185142}. Best is trial 4 with value: 0.981001547653573.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:45:35,208] Trial 7 finished with value: 0.9800343368203798 and parameters: {'classifier__n_estimators': 163, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.20499672676341157, 'classifier__subsample': 0.7054864832032575, 'classifier__colsample_bytree': 0.9250432944834902}. Best is trial 4 with value: 0.981001547653573.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:45:43,376] Trial 8 finished with value: 0.9810479265310219 and parameters: {'classifier__n_estimators': 298, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.05722229168328298, 'classifier__subsample': 0.9367837985354466, 'classifier__colsample_bytree': 0.7309678019732926}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:45:49,596] Trial 9 finished with value: 0.9809662163715223 and parameters: {'classifier__n_estimators': 190, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.05898416056128349, 'classifier__subsample': 0.7863326015759046, 'classifier__colsample_bytree': 0.7390085716354833}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:45:57,261] Trial 10 finished with value: 0.9809437892730049 and parameters: {'classifier__n_estimators': 281, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.08367410349214705, 'classifier__subsample': 0.8801886955254052, 'classifier__colsample_bytree': 0.7257453039000061}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:46:05,556] Trial 11 finished with value: 0.9809717464801789 and parameters: {'classifier__n_estimators': 283, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.03940199291211741, 'classifier__subsample': 0.9611378713211751, 'classifier__colsample_bytree': 0.9808429072490431}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:46:13,701] Trial 12 finished with value: 0.9809797210456243 and parameters: {'classifier__n_estimators': 294, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.0619997317115452, 'classifier__subsample': 0.9398786864192985, 'classifier__colsample_bytree': 0.876305918407855}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:46:20,920] Trial 13 finished with value: 0.9810259845727746 and parameters: {'classifier__n_estimators': 249, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.04432015010883705, 'classifier__subsample': 0.9735203573166348, 'classifier__colsample_bytree': 0.7077917006949705}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:46:28,061] Trial 14 finished with value: 0.9807784977032243 and parameters: {'classifier__n_estimators': 267, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.038712010477318114, 'classifier__subsample': 0.9854841197791762, 'classifier__colsample_bytree': 0.8004090043140765}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:46:34,170] Trial 15 finished with value: 0.9808509526141126 and parameters: {'classifier__n_estimators': 209, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.047925476599974766, 'classifier__subsample': 0.9280716042557959, 'classifier__colsample_bytree': 0.8010478203937744}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:46:41,602] Trial 16 finished with value: 0.981015884203269 and parameters: {'classifier__n_estimators': 294, 'classifier__max_depth': 6, 'classifier__learning_rate': 0.08612245894715416, 'classifier__subsample': 0.9946696974172923, 'classifier__colsample_bytree': 0.7449804923309825}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:46:49,812] Trial 17 finished with value: 0.9809897232432554 and parameters: {'classifier__n_estimators': 282, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.03220420286357773, 'classifier__subsample': 0.9492233253830737, 'classifier__colsample_bytree': 0.712793854941364}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:46:56,585] Trial 18 finished with value: 0.9808814974920461 and parameters: {'classifier__n_estimators': 219, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.03610858229316408, 'classifier__subsample': 0.9892303765466554, 'classifier__colsample_bytree': 0.7763740916161622}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:47:03,771] Trial 19 finished with value: 0.9807122791716953 and parameters: {'classifier__n_estimators': 251, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.09809740096586565, 'classifier__subsample': 0.9571293095942764, 'classifier__colsample_bytree': 0.742996717233981}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:47:11,670] Trial 20 finished with value: 0.981010894716521 and parameters: {'classifier__n_estimators': 280, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.05224379128902169, 'classifier__subsample': 0.9943604616595795, 'classifier__colsample_bytree': 0.7652777262287889}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:47:18,873] Trial 21 finished with value: 0.9809870886546515 and parameters: {'classifier__n_estimators': 290, 'classifier__max_depth': 6, 'classifier__learning_rate': 0.0708299483692095, 'classifier__subsample': 0.9970020864251439, 'classifier__colsample_bytree': 0.7432091760633582}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:47:25,864] Trial 22 finished with value: 0.981038318735093 and parameters: {'classifier__n_estimators': 247, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.057242627804528164, 'classifier__subsample': 0.9916350907755249, 'classifier__colsample_bytree': 0.7092145227782262}. Best is trial 8 with value: 0.9810479265310219.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:47:34,115] Trial 23 finished with value: 0.9810527910318193 and parameters: {'classifier__n_estimators': 244, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.055587807154804283, 'classifier__subsample': 0.9594797691884895, 'classifier__colsample_bytree': 0.709652207359822}. Best is trial 23 with value: 0.9810527910318193.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:47:40,381] Trial 24 finished with value: 0.9810092352379487 and parameters: {'classifier__n_estimators': 226, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.07570843638813116, 'classifier__subsample': 0.9777068360075115, 'classifier__colsample_bytree': 0.7124891613471462}. Best is trial 23 with value: 0.9810527910318193.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:47:47,237] Trial 25 finished with value: 0.9808907845462741 and parameters: {'classifier__n_estimators': 261, 'classifier__max_depth': 6, 'classifier__learning_rate': 0.05790391145840442, 'classifier__subsample': 0.9603590855163122, 'classifier__colsample_bytree': 0.7467986050860286}. Best is trial 23 with value: 0.9810527910318193.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:47:55,003] Trial 26 finished with value: 0.980996635998219 and parameters: {'classifier__n_estimators': 286, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.046220867327535844, 'classifier__subsample': 0.9230306543759397, 'classifier__colsample_bytree': 0.7494035215036511}. Best is trial 23 with value: 0.9810527910318193.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:48:01,773] Trial 27 finished with value: 0.9809623063698091 and parameters: {'classifier__n_estimators': 228, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.07288225136576428, 'classifier__subsample': 0.9099517298440379, 'classifier__colsample_bytree': 0.71305484504681}. Best is trial 23 with value: 0.9810527910318193.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:48:08,716] Trial 28 finished with value: 0.9807142267165009 and parameters: {'classifier__n_estimators': 249, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.030863006099374642, 'classifier__subsample': 0.9198956758183118, 'classifier__colsample_bytree': 0.7571501319673374}. Best is trial 23 with value: 0.9810527910318193.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
23,xgboost,optuna,unsw_nb15,235490,30,5,1,23,COMPLETE,8.250624,"{""classifier__colsample_bytree"": 0.709652207359822, ""classifier__learning_rate"": 0.055587807154804283, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 244, ""classifier__subsample"": 0.9594797691884895}",1.590275,0.129527,0.055373,0.008352,0.981509,0.981501,0.980844,0.980656,0.980753,0.981053,0.000374,1
8,xgboost,optuna,unsw_nb15,235490,30,5,1,8,COMPLETE,8.166695,"{""classifier__colsample_bytree"": 0.7309678019732926, ""classifier__learning_rate"": 0.05722229168328298, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9367837985354466}",1.572504,0.059670,0.057434,0.009477,0.981316,0.981762,0.980750,0.980687,0.980724,0.981048,0.000426,2
22,xgboost,optuna,unsw_nb15,235490,30,5,1,22,COMPLETE,6.990468,"{""classifier__colsample_bytree"": 0.7092145227782262, ""classifier__learning_rate"": 0.057242627804528164, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 247, ""classifier__subsample"": 0.9916350907755249}",1.344875,0.094882,0.048824,0.002746,0.981444,0.981501,0.980775,0.980688,0.980783,0.981038,0.000357,3
13,xgboost,optuna,unsw_nb15,235490,30,5,1,13,COMPLETE,7.218326,"{""classifier__colsample_bytree"": 0.7077917006949705, ""classifier__learning_rate"": 0.04432015010883705, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 249, ""classifier__subsample"": 0.9735203573166348}",1.390075,0.127035,0.049396,0.002921,0.981317,0.981671,0.980752,0.980694,0.980696,0.981026,0.000399,4
16,xgboost,optuna,unsw_nb15,235490,30,5,1,16,COMPLETE,7.432022,"{""classifier__colsample_bytree"": 0.7449804923309825, ""classifier__learning_rate"": 0.08612245894715416, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 294, ""classifier__subsample"": 0.9946696974172923}",1.432844,0.096154,0.049240,0.005676,0.981579,0.981601,0.980617,0.980593,0.980690,0.981016,0.000470,5
20,xgboost,optuna,unsw_nb15,235490,30,5,1,20,COMPLETE,7.898376,"{""classifier__colsample_bytree"": 0.7652777262287889, ""classifier__learning_rate"": 0.05224379128902169, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 280, ""classifier__subsample"": 0.9943604616595795}",1.522052,0.076262,0.053185,0.003819,0.981313,0.981463,0.980841,0.980812,0.980625,0.981011,0.000321,6
24,xgboost,optuna,unsw_nb15,235490,30,5,1,24,COMPLETE,6.265246,"{""classifier__colsample_bytree"": 0.7124891613471462, ""classifier__learning_rate"": 0.07570843638813116, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 226, ""classifier__subsample"": 0.9777068360075115}",1.202961,0.079943,0.045824,0.002597,0.981284,0.981631,0.980783,0.980656,0.980691,0.981009,0.000384,7
4,xgboost,optuna,unsw_nb15,235490,30,5,1,4,COMPLETE,7.840873,"{""classifier__colsample_bytree"": 0.9629167456888115, ""classifier__learning_rate"": 0.06173698734681893, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 260, ""classifier__subsample"": 0.9076967847007942}",1.514484,0.084694,0.050385,0.001507,0.981370,0.981429,0.980828,0.980733,0.980649,0.981002,0.000330,8
26,xgboost,optuna,unsw_nb15,235490,30,5,1,26,COMPLETE,7.765361,"{""classifier__colsample_bytree"": 0.7494035215036511, ""classifier__learning_rate"": 0.046220867327535844, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 286, ""classifier__subsample"": 0.9230306543759397}",1.497826,0.094508,0.050919,0.005134,0.981521,0.981635,0.980597,0.980566,0.980664,0.980997,0.000477,9
17,xgboost,optuna,unsw_nb15,235490,30,5,1,17,COMPLETE,8.208949,"{""classifier__colsample_bytree"": 0.712793854941364, ""classifier__learning_rate"": 0.03220420286357773, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 282, ""classifier__subsample"": 0.9492233253830737}",1.584058,0.069372,0.053402,0.003125,0.981514,0.981674,0.980721,0.980438,0.980602,0.980990,0.000504,10
29,xgboost,optuna,unsw_nb15,235490,30,5,1,29,COMPLETE,7.119882,"{""classifier__colsample_bytree"": 0.7360747773025502, ""classifier__learning_rate"": 0.043783361587648215, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 237, ""classifier__subsample"": 0.8872786545440627}",1.366910,0.089457,0.052712,0.008431,0.981287,0.981736,0.980721,0.980596,0.980597,0.980988,0.000453,11
21,xgboost,optuna,unsw_nb15,235490,30,5,1,21,COMPLETE,7.201594,"{""classifier__colsample_bytree"": 0.7432091760633582, ""classifier__learning_rate"": 0.0708299483692095, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 290, ""classifier__subsample"": 0.9970020864251439}",1.387982,0.115099,0.048146,0.003078,0.981515,0.981635,0.980659,0.980495,0.980631,0.980987,0.000485,12
12,xgboost,optuna,unsw_nb15,235490,30,5,1,12,COMPLETE,8.143750,"{""classifier__colsample_bytree"": 0.876305918407855, ""classifier__learning_rate"": 0.0619997317115452, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 294, ""classifier__subsample"": 0.9398786864192985}",1.572739,0.077979,0.051771,0.001947,0.981247,0.981567,0.980812,0.980682,0.980590,0.980980,0.000370,13
11,xgboost,optuna,unsw_nb15,235490,30,5,1,11,COMPLETE,8.294190,"{""classifier__colsample_bytree"": 0.9808429072490431, ""classifier__learning_rate"": 0.03940199291211741, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 283, ""classifier__subsample"": 0.9611378713211751}",1.601739,0.075381,0.052820,0.003005,0.981414,0.981671,0.980844,0.980398,0.980531,0.980972,0.000495,14
9,xgboost,optuna,unsw_nb15,235490,30,5,1,9,COMPLETE,6.220135,"{""classifier__colsample_bytree"": 0.7390085716354833, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 190, ""classifier__subsample"": 0.7863326015759046}",1.190794,0.053653,0.049945,0.008546,0.981351,0.981639,0.980589,0.980525,0.980727,0.980966,0.000446,15
27,xgboost,optuna,unsw_nb15,235490,30,5,1,27,COMPLETE,6.769602,"{""classifier__colsample_bytree"": 0.71305484504681, ""classifier__learning_rate"": 0.07288225136576428, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 228, ""classifier__subsample"": 0.9099517298440379}",1.303449,0.074118,0.046023,0.001384,0.981141,0.981519,0.980698,0.980772,0.980682,0.980962,0.000324,16
10,xgboost,optuna,unsw_nb15,235490,30,5,1,10,COMPLETE,7.664492,"{""classifier__colsample_bytree"": 0.7257453039000061, ""classifier__learning_rate"": 0.08367410349214705, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 281, ""classifier__subsample"": 0.8801886955254052}",1.475694,0.085262,0.052942,0.002801,0.981469,0.981445,0.980719,0.980538,0.980548,0.980944,0.000424,17
25,xgboost,optuna,unsw_nb15,235490,30,5,1,25,COMPLETE,6.855231,"{""classifier__colsample_bytree"": 0.7467986050860286, ""classifier__learning_rate"": 0.05790391145840442, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 261, ""classifier__subsample"": 0.9603590855163122}",1.316483,0.141404,0.050245,0.006128,0.981363,0.981642,0.980471,0.980279,0.980699,0.980891,0.000525,18
18,xgboost,optuna,unsw_nb15,235490,30,5,1,18,COMPLETE,6.772441,"{""classifier__colsample_bytree"": 0.7763740916161622, ""classifier__learning_rate"": 0.03610858229316408, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 219, ""classifier__subsample"": 0.9892303765466554}",1.296735,0.119052,0.053536,0.008412,0.981355,0.981547,0.980724,0.980243,0.980539,0.980881,0.000493,19
3,xgboost,optuna,unsw_nb15,235490,30,5,1,3,COMPLETE,6.210106,"{""classifier__colsample_bytree"": 0.7594304467254636, ""classifier__learning_rate"": 0.10859531344085706, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 234, ""classifier__subsample"": 0.7421160815785701}",1.197357,0.088582,0.040887,0.005755,0.981481,0.981605,0.980495,0.980306,0.980499,0.980877,0.000549,20
15,xgboost,optuna,unsw_nb15,235490,30,5,1,15,COMPLETE,6.107539,"{""classifier__colsample_bytree"": 0.8010478203937744, ""classifier__learning_rate"": 0.047925476599974766, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 209, ""classifier__subsample"": 0.9280716042557959}",1.170469,0.116430,0.046916,0.006816,0.981327,0.981645,0.980664,0.980146,0.980472,0.980851,0.000554,21
6,xgboost,optuna,unsw_nb15,235490,30,5,1,6,COMPLETE,3.618181,"{""classifier__colsample_bytree"": 0.907563134185142, ""classifier__learning_rate"": 0.27227689219802986, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 119, ""classifier__subsample"": 0.859949585491905}",0.689937,0.081468,0.030561,0.001949,0.981341,0.981498,0.980244,0.980473,0.980651,0.980841,0.000492,22
2,xgboost,optuna,unsw_nb15,235490,30,5,1,2,COMPLETE,5.413700,"{""classifier__colsample_bytree"": 0.7082162779593778, ""classifier__learning_rate"": 0.0480367375659992, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 184, ""classifier__subsample"": 0.9634352309172836}",1.034370,0.074731,0.045103,0.005269,0.981296,0.981551,0.980440,0.980275,0.980440,0.980800,0.000519,23
14,xgboost,optuna,unsw_nb15,235490,30,5,1,14,COMPLETE,7.141327,"{""classifier__colsample_bytree"": 0.8004090043140765, ""classifier__learning_rate"": 0.038712010477318114, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 267, ""classifier__subsample"": 0.9854841197791762}",1.374698,0.088812,0.049347,0.002137,0.981264,0.981512,0.980438,0.980208,0.980471,0.980778,0.000512,24
28,xgboost,optuna,unsw_nb15,235490,30,5,1,28,COMPLETE,6.942428,"{""classifier__colsample_bytree"": 0.7571501319673374, ""classifier__learning_rate"": 0.030863006099374642, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 249, ""classifier__subsample"": 0.9198956758183118}",1.337038,0.118958,0.047203,0.003022,0.981260,0.981515,0.980181,0.980241,0.980374,0.980714,0.000559,25
19,xgboost,optuna,unsw_nb15,235490,30,5,1,19,COMPLETE,7.185865,"{""classifier__colsample_bytree"": 0.742996717233981, ""classifier__learning_rate"": 0.09809740096586565, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 251, ""classifier__subsample"": 0.9571293095942764}",1.380813,0.080847,0.051987,0.002975,0.980934,0.980912,0.980846,0.980462,0.980406,0.980712,0.000230,26
0,xgboost,optuna,unsw_nb15,235490,30,5,1,0,COMPLETE,6.357767,"{""classifier__colsample_bytree"": 0.7440267672451338, ""classifier__learning_rate"": 0.03000790177293386, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 183, ""classifier__subsample"": 0.7906997717895519}",1.218740,0.119466,0.049625,0.007480,0.981226,0.981352,0.980118,0.979949,0.980342,0.980597,0.000580,27
7,xgboost,optuna,unsw_nb15,235490,30,5,1,7,COMPLETE,5.236824,"{""classifier__colsample_bytree"": 0.9250432944834902, ""classifier__learning_rate"": 0.20499672676341157, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 163, ""classifier__subsample"": 0.7054864832032575}",1.006259,0.080598,0.037733,0.001583,0.980444,0.980186,0.979962,0.980056,0.979522,0.980034,0.000303,28
1,xgboost,optuna,unsw_nb15,235490,30,5,1,1,COMPLETE,3.361248,"{""classifier__colsample_bytree"": 0.8616450202010071, ""classifier__learning_rate"": 0.06647861789041172, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 118, ""classifier__subsample"": 0.819030242269201}",0.639019,0.083431,0.030165,0.002283,0.978634,0.979077,0.977803,0.977758,0.978020,0.978258,0.000515,29
5,xgboost,optuna,unsw_nb15,235490,30,5,1,5,COMPLETE,6.161526,"{""classifier__colsample_bytree"": 0.9634427510288239, ""classifier__learning_rate"": 0.032822831099235304, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 279, ""classifier__subsample"": 0.7509491258693707}",1.192883,0.087419,0.036193,0.002101,0.975359,0.975510,0.974659,0.973471,0.973939,0.974588,0.000790,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,xgboost,optuna,unsw_nb15,235490,30,5,1,1,1.321773,0.094824,0.944724,0.997983,0.970623,0.999489,0.985403,0.992396,0.981509,0.987919,0.991693
1,xgboost,optuna,unsw_nb15,235490,30,5,1,2,1.314898,0.096240,0.945261,0.997346,0.970605,0.999327,0.985562,0.992397,0.981501,0.987919,0.991454
2,xgboost,optuna,unsw_nb15,235490,30,5,1,3,1.288765,0.091502,0.942740,0.997983,0.969575,0.999488,0.984845,0.992113,0.980844,0.987473,0.991414
3,xgboost,optuna,unsw_nb15,235490,30,5,1,4,1.391982,0.090994,0.941996,0.998195,0.969282,0.999542,0.984633,0.992031,0.980656,0.987346,0.991414
4,xgboost,optuna,unsw_nb15,235490,30,5,1,5,1.425283,0.092293,0.942190,0.998301,0.969435,0.999569,0.984686,0.992072,0.980753,0.987409,0.991494

Modelo: xgboost | origem do treinamento: iot23

[I 2026-10-12 03:48:25,223] A new study created in memory with name: xgboost_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:48:30,907] Trial 0 finished with value: 0.9978049998720208 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.03000790177293386, 'classifier__subsample': 0.7906997717895519, 'classifier__colsample_bytree': 0.7440267672451338}. Best is trial 0 with value: 0.9978049998720208.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:48:34,234] Trial 1 finished with value: 0.9977649110429972 and parameters: {'classifier__n_estimators': 118, 'classifier__max_depth': 4, 'classifier__learning_rate': 0.06647861789041172, 'classifier__subsample': 0.819030242269201, 'classifier__colsample_bytree': 0.8616450202010071}. Best is trial 0 with value: 0.9978049998720208.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:48:39,002] Trial 2 finished with value: 0.9978183392668104 and parameters: {'classifier__n_estimators': 184, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.0480367375659992, 'classifier__subsample': 0.9634352309172836, 'classifier__colsample_bytree': 0.7082162779593778}. Best is trial 2 with value: 0.9978183392668104.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:48:45,147] Trial 3 finished with value: 0.9978117434952702 and parameters: {'classifier__n_estimators': 234, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.10859531344085706, 'classifier__subsample': 0.7421160815785701, 'classifier__colsample_bytree': 0.7594304467254636}. Best is trial 2 with value: 0.9978183392668104.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:48:51,817] Trial 4 finished with value: 0.9978050307364592 and parameters: {'classifier__n_estimators': 260, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06173698734681893, 'classifier__subsample': 0.9076967847007942, 'classifier__colsample_bytree': 0.9629167456888115}. Best is trial 2 with value: 0.9978183392668104.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:48:58,009] Trial 5 finished with value: 0.9977515204777401 and parameters: {'classifier__n_estimators': 279, 'classifier__max_depth': 3, 'classifier__learning_rate': 0.032822831099235304, 'classifier__subsample': 0.7509491258693707, 'classifier__colsample_bytree': 0.9634427510288239}. Best is trial 2 with value: 0.9978183392668104.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:49:01,326] Trial 6 finished with value: 0.9978118175339261 and parameters: {'classifier__n_estimators': 119, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.27227689219802986, 'classifier__subsample': 0.859949585491905, 'classifier__colsample_bytree': 0.907563134185142}. Best is trial 2 with value: 0.9978183392668104.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:49:05,951] Trial 7 finished with value: 0.997798485671446 and parameters: {'classifier__n_estimators': 163, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.20499672676341157, 'classifier__subsample': 0.7054864832032575, 'classifier__colsample_bytree': 0.9250432944834902}. Best is trial 2 with value: 0.9978183392668104.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:49:12,990] Trial 8 finished with value: 0.9978117770272442 and parameters: {'classifier__n_estimators': 298, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.05722229168328298, 'classifier__subsample': 0.9367837985354466, 'classifier__colsample_bytree': 0.7309678019732926}. Best is trial 2 with value: 0.9978183392668104.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:49:18,148] Trial 9 finished with value: 0.9978051110730675 and parameters: {'classifier__n_estimators': 190, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.05898416056128349, 'classifier__subsample': 0.7863326015759046, 'classifier__colsample_bytree': 0.7390085716354833}. Best is trial 2 with value: 0.9978183392668104.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:49:22,434] Trial 10 finished with value: 0.9978249738595382 and parameters: {'classifier__n_estimators': 164, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.04636584084816155, 'classifier__subsample': 0.9632313474826545, 'classifier__colsample_bytree': 0.7438843062136022}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:49:27,442] Trial 11 finished with value: 0.9978183786481829 and parameters: {'classifier__n_estimators': 194, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.05498518482345156, 'classifier__subsample': 0.9730251987149728, 'classifier__colsample_bytree': 0.7102171875504907}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:49:32,245] Trial 12 finished with value: 0.997818307896343 and parameters: {'classifier__n_estimators': 196, 'classifier__max_depth': 6, 'classifier__learning_rate': 0.04584865465814916, 'classifier__subsample': 0.9668828581490665, 'classifier__colsample_bytree': 0.8127282584801958}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:49:36,918] Trial 13 finished with value: 0.997805111658365 and parameters: {'classifier__n_estimators': 180, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.1077291769642233, 'classifier__subsample': 0.9330792948477349, 'classifier__colsample_bytree': 0.7427874488507247}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:49:40,326] Trial 14 finished with value: 0.9978182695903666 and parameters: {'classifier__n_estimators': 123, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.03916400459846598, 'classifier__subsample': 0.9541054335996062, 'classifier__colsample_bytree': 0.7278227210578906}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:49:44,402] Trial 15 finished with value: 0.997798408432439 and parameters: {'classifier__n_estimators': 138, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.05455282270317269, 'classifier__subsample': 0.8689202773979461, 'classifier__colsample_bytree': 0.7455036520237539}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:49:49,620] Trial 16 finished with value: 0.997811744597658 and parameters: {'classifier__n_estimators': 229, 'classifier__max_depth': 6, 'classifier__learning_rate': 0.07344056773663223, 'classifier__subsample': 0.9963109732862966, 'classifier__colsample_bytree': 0.7504646482259039}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:49:55,775] Trial 17 finished with value: 0.9978183392686493 and parameters: {'classifier__n_estimators': 250, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.03334041476631435, 'classifier__subsample': 0.9490145445956589, 'classifier__colsample_bytree': 0.7131105272115245}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:50:00,241] Trial 18 finished with value: 0.9978117126888424 and parameters: {'classifier__n_estimators': 164, 'classifier__max_depth': 6, 'classifier__learning_rate': 0.049912260077503066, 'classifier__subsample': 0.850339477716455, 'classifier__colsample_bytree': 0.7209788625255835}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:50:04,694] Trial 19 finished with value: 0.9978183105774925 and parameters: {'classifier__n_estimators': 179, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.03033965257812245, 'classifier__subsample': 0.9941285016083087, 'classifier__colsample_bytree': 0.7093686615088576}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:50:10,117] Trial 20 finished with value: 0.997811744597658 and parameters: {'classifier__n_estimators': 210, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06425470779842692, 'classifier__subsample': 0.9492508993621507, 'classifier__colsample_bytree': 0.7701010097671769}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:50:17,107] Trial 21 finished with value: 0.9978050717111465 and parameters: {'classifier__n_estimators': 284, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.0354951287157322, 'classifier__subsample': 0.9480087792071914, 'classifier__colsample_bytree': 0.727916934574306}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:50:23,314] Trial 22 finished with value: 0.9978249738595382 and parameters: {'classifier__n_estimators': 251, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.04396258151641167, 'classifier__subsample': 0.929756034587087, 'classifier__colsample_bytree': 0.7715965245573347}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:50:27,264] Trial 23 finished with value: 0.9977984781016126 and parameters: {'classifier__n_estimators': 140, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.07334082815188657, 'classifier__subsample': 0.9845840031527653, 'classifier__colsample_bytree': 0.7631355548973815}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:50:31,840] Trial 24 finished with value: 0.9978249328724124 and parameters: {'classifier__n_estimators': 173, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.03928031207247796, 'classifier__subsample': 0.9357988532807273, 'classifier__colsample_bytree': 0.8161960749151348}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:50:37,552] Trial 25 finished with value: 0.9978183105774925 and parameters: {'classifier__n_estimators': 228, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.038556032866999476, 'classifier__subsample': 0.907883340985071, 'classifier__colsample_bytree': 0.7773618162605717}. Best is trial 10 with value: 0.9978249738595382.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:50:41,338] Trial 26 finished with value: 0.9978316175039594 and parameters: {'classifier__n_estimators': 137, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.04579747054926139, 'classifier__subsample': 0.9923740090265242, 'classifier__colsample_bytree': 0.7826494405879115}. Best is trial 26 with value: 0.9978316175039594.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:50:44,913] Trial 27 finished with value: 0.9978115940262512 and parameters: {'classifier__n_estimators': 133, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.035211434571631714, 'classifier__subsample': 0.9796728610251201, 'classifier__colsample_bytree': 0.7679916002145453}. Best is trial 26 with value: 0.9978316175039594.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:50:48,392] Trial 28 finished with value: 0.9978183488816301 and parameters: {'classifier__n_estimators': 123, 'classifier__max_depth': 6, 'classifier__learning_rate': 0.05544349110657431, 'classifier__subsample': 0.9262056453860433, 'classifier__colsample_bytree': 0.7729397404535612}. Best is trial 26 with value: 0.9978316175039594.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
26,xgboost,optuna,iot23,235490,30,5,1,26,COMPLETE,3.784764,"{""classifier__colsample_bytree"": 0.7826494405879115, ""classifier__learning_rate"": 0.04579747054926139, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 137, ""classifier__subsample"": 0.9923740090265242}",0.715949,0.082081,0.036631,0.004919,0.998005,0.997438,0.997505,0.998205,0.998005,0.997832,0.000304,1
10,xgboost,optuna,iot23,235490,30,5,1,10,COMPLETE,4.285581,"{""classifier__colsample_bytree"": 0.7438843062136022, ""classifier__learning_rate"": 0.04636584084816155, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 164, ""classifier__subsample"": 0.9632313474826545}",0.815265,0.104748,0.037970,0.003042,0.997972,0.997438,0.997472,0.998238,0.998005,0.997825,0.000316,2
22,xgboost,optuna,iot23,235490,30,5,1,22,COMPLETE,6.205705,"{""classifier__colsample_bytree"": 0.7715965245573347, ""classifier__learning_rate"": 0.04396258151641167, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 251, ""classifier__subsample"": 0.929756034587087}",1.192364,0.089399,0.044581,0.002425,0.997972,0.997438,0.997472,0.998238,0.998005,0.997825,0.000316,2
24,xgboost,optuna,iot23,235490,30,5,1,24,COMPLETE,4.575968,"{""classifier__colsample_bytree"": 0.8161960749151348, ""classifier__learning_rate"": 0.03928031207247796, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 173, ""classifier__subsample"": 0.9357988532807273}",0.872813,0.099185,0.038259,0.003169,0.998005,0.997405,0.997472,0.998238,0.998005,0.997825,0.000328,4
11,xgboost,optuna,iot23,235490,30,5,1,11,COMPLETE,5.006816,"{""classifier__colsample_bytree"": 0.7102171875504907, ""classifier__learning_rate"": 0.05498518482345156, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 194, ""classifier__subsample"": 0.9730251987149728}",0.952693,0.104254,0.044630,0.004845,0.997972,0.997438,0.997505,0.998205,0.997972,0.997818,0.000296,5
28,xgboost,optuna,iot23,235490,30,5,1,28,COMPLETE,3.478697,"{""classifier__colsample_bytree"": 0.7729397404535612, ""classifier__learning_rate"": 0.05544349110657431, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 123, ""classifier__subsample"": 0.9262056453860433}",0.655584,0.082667,0.035972,0.004519,0.997972,0.997438,0.997505,0.998172,0.998005,0.997818,0.000292,6
17,xgboost,optuna,iot23,235490,30,5,1,17,COMPLETE,6.154541,"{""classifier__colsample_bytree"": 0.7131105272115245, ""classifier__learning_rate"": 0.03334041476631435, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 250, ""classifier__subsample"": 0.9490145445956589}",1.183654,0.096087,0.042895,0.000743,0.997972,0.997438,0.997472,0.998172,0.998038,0.997818,0.000304,7
2,xgboost,optuna,iot23,235490,30,5,1,2,COMPLETE,4.767790,"{""classifier__colsample_bytree"": 0.7082162779593778, ""classifier__learning_rate"": 0.0480367375659992, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 184, ""classifier__subsample"": 0.9634352309172836}",0.909831,0.096248,0.040567,0.003669,0.998005,0.997438,0.997472,0.998172,0.998005,0.997818,0.000303,8
25,xgboost,optuna,iot23,235490,30,5,1,25,COMPLETE,5.711385,"{""classifier__colsample_bytree"": 0.7773618162605717, ""classifier__learning_rate"": 0.038556032866999476, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 228, ""classifier__subsample"": 0.907883340985071}",1.093291,0.098663,0.044796,0.005928,0.997972,0.997438,0.997472,0.998205,0.998005,0.997818,0.000307,9
19,xgboost,optuna,iot23,235490,30,5,1,19,COMPLETE,4.452549,"{""classifier__colsample_bytree"": 0.7093686615088576, ""classifier__learning_rate"": 0.03033965257812245, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 179, ""classifier__subsample"": 0.9941285016083087}",0.850172,0.098667,0.035834,0.000606,0.997972,0.997438,0.997472,0.998205,0.998005,0.997818,0.000307,9
12,xgboost,optuna,iot23,235490,30,5,1,12,COMPLETE,4.802397,"{""classifier__colsample_bytree"": 0.8127282584801958, ""classifier__learning_rate"": 0.04584865465814916, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 196, ""classifier__subsample"": 0.9668828581490665}",0.917911,0.099232,0.038551,0.003098,0.997972,0.997405,0.997505,0.998172,0.998038,0.997818,0.000305,11
29,xgboost,optuna,iot23,235490,30,5,1,29,COMPLETE,3.830642,"{""classifier__colsample_bytree"": 0.7772681101310915, ""classifier__learning_rate"": 0.039323148339371415, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 143, ""classifier__subsample"": 0.9096391133976436}",0.727214,0.091409,0.034767,0.003059,0.998005,0.997405,0.997472,0.998205,0.998005,0.997818,0.000319,12
14,xgboost,optuna,iot23,235490,30,5,1,14,COMPLETE,3.407869,"{""classifier__colsample_bytree"": 0.7278227210578906, ""classifier__learning_rate"": 0.03916400459846598, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 123, ""classifier__subsample"": 0.9541054335996062}",0.643713,0.074560,0.033829,0.004653,0.998005,0.997405,0.997472,0.998205,0.998005,0.997818,0.000319,12
6,xgboost,optuna,iot23,235490,30,5,1,6,COMPLETE,3.316231,"{""classifier__colsample_bytree"": 0.907563134185142, ""classifier__learning_rate"": 0.27227689219802986, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 119, ""classifier__subsample"": 0.859949585491905}",0.628575,0.078955,0.031545,0.003545,0.997939,0.997372,0.997539,0.998205,0.998005,0.997812,0.000309,14
8,xgboost,optuna,iot23,235490,30,5,1,8,COMPLETE,7.038416,"{""classifier__colsample_bytree"": 0.7309678019732926, ""classifier__learning_rate"": 0.05722229168328298, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9367837985354466}",1.350835,0.132462,0.053495,0.008636,0.997972,0.997438,0.997505,0.998172,0.997972,0.997812,0.000288,15
16,xgboost,optuna,iot23,235490,30,5,1,16,COMPLETE,5.217581,"{""classifier__colsample_bytree"": 0.7504646482259039, ""classifier__learning_rate"": 0.07344056773663223, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 229, ""classifier__subsample"": 0.9963109732862966}",1.000349,0.087591,0.038928,0.000568,0.997939,0.997438,0.997505,0.998172,0.998005,0.997812,0.000289,16
20,xgboost,optuna,iot23,235490,30,5,1,20,COMPLETE,5.421792,"{""classifier__colsample_bytree"": 0.7701010097671769, ""classifier__learning_rate"": 0.06425470779842692, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 210, ""classifier__subsample"": 0.9492508993621507}",1.035467,0.097520,0.044661,0.006729,0.997939,0.997438,0.997505,0.998172,0.998005,0.997812,0.000289,16
3,xgboost,optuna,iot23,235490,30,5,1,3,COMPLETE,6.144283,"{""classifier__colsample_bytree"": 0.7594304467254636, ""classifier__learning_rate"": 0.10859531344085706, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 234, ""classifier__subsample"": 0.7421160815785701}",1.182319,0.057570,0.043214,0.004441,0.997939,0.997438,0.997505,0.998172,0.998005,0.997812,0.000289,18
18,xgboost,optuna,iot23,235490,30,5,1,18,COMPLETE,4.465228,"{""classifier__colsample_bytree"": 0.7209788625255835, ""classifier__learning_rate"": 0.049912260077503066, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 164, ""classifier__subsample"": 0.850339477716455}",0.853172,0.085885,0.035766,0.002448,0.997972,0.997405,0.997539,0.998172,0.997972,0.997812,0.000290,19
27,xgboost,optuna,iot23,235490,30,5,1,27,COMPLETE,3.574514,"{""classifier__colsample_bytree"": 0.7679916002145453, ""classifier__learning_rate"": 0.035211434571631714, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 133, ""classifier__subsample"": 0.9796728610251201}",0.675892,0.083530,0.034738,0.004865,0.998005,0.997371,0.997472,0.998205,0.998005,0.997812,0.000328,20
13,xgboost,optuna,iot23,235490,30,5,1,13,COMPLETE,4.672024,"{""classifier__colsample_bytree"": 0.7427874488507247, ""classifier__learning_rate"": 0.1077291769642233, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 180, ""classifier__subsample"": 0.9330792948477349}",0.887881,0.098728,0.041776,0.005664,0.997939,0.997405,0.997505,0.998205,0.997972,0.997805,0.000302,21
9,xgboost,optuna,iot23,235490,30,5,1,9,COMPLETE,5.158004,"{""classifier__colsample_bytree"": 0.7390085716354833, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 190, ""classifier__subsample"": 0.7863326015759046}",0.990482,0.095893,0.037964,0.000132,0.997972,0.997438,0.997505,0.998139,0.997972,0.997805,0.000280,22
21,xgboost,optuna,iot23,235490,30,5,1,21,COMPLETE,6.989867,"{""classifier__colsample_bytree"": 0.727916934574306, ""classifier__learning_rate"": 0.0354951287157322, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 284, ""classifier__subsample"": 0.9480087792071914}",1.342115,0.104815,0.051524,0.008461,0.997972,0.997438,0.997472,0.998172,0.997972,0.997805,0.000295,23
4,xgboost,optuna,iot23,235490,30,5,1,4,COMPLETE,6.669577,"{""classifier__colsample_bytree"": 0.9629167456888115, ""classifier__learning_rate"": 0.06173698734681893, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 260, ""classifier__subsample"": 0.9076967847007942}",1.284281,0.116729,0.046226,0.001902,0.997939,0.997405,0.997472,0.998205,0.998005,0.997805,0.000313,24
0,xgboost,optuna,iot23,235490,30,5,1,0,COMPLETE,5.681069,"{""classifier__colsample_bytree"": 0.7440267672451338, ""classifier__learning_rate"": 0.03000790177293386, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 183, ""classifier__subsample"": 0.7906997717895519}",1.087762,0.127376,0.045174,0.007636,0.997972,0.997405,0.997505,0.998138,0.998005,0.997805,0.000293,25
7,xgboost,optuna,iot23,235490,30,5,1,7,COMPLETE,4.623853,"{""classifier__colsample_bytree"": 0.9250432944834902, ""classifier__learning_rate"": 0.20499672676341157, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 163, ""classifier__subsample"": 0.7054864832032575}",0.885354,0.102057,0.036220,0.001948,0.997905,0.997339,0.997539,0.998172,0.998038,0.997798,0.000312,26
23,xgboost,optuna,iot23,235490,30,5,1,23,COMPLETE,3.949280,"{""classifier__colsample_bytree"": 0.7631355548973815, ""classifier__learning_rate"": 0.07334082815188657, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 140, ""classifier__subsample"": 0.9845840031527653}",0.752493,0.091882,0.033236,0.000613,0.997905,0.997438,0.997505,0.998172,0.997972,0.997798,0.000282,27
15,xgboost,optuna,iot23,235490,30,5,1,15,COMPLETE,4.075245,"{""classifier__colsample_bytree"": 0.7455036520237539, ""classifier__learning_rate"": 0.05455282270317269, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 138, ""classifier__subsample"": 0.8689202773979461}",0.774653,0.084336,0.036391,0.002516,0.997972,0.997438,0.997472,0.998138,0.997972,0.997798,0.000287,28
1,xgboost,optuna,iot23,235490,30,5,1,1,COMPLETE,3.326287,"{""classifier__colsample_bytree"": 0.8616450202010071, ""classifier__learning_rate"": 0.06647861789041172, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 118, ""classifier__subsample"": 0.819030242269201}",0.629859,0.072718,0.032319,0.005405,0.997872,0.997371,0.997405,0.998172,0.998005,0.997765,0.000322,29
5,xgboost,optuna,iot23,235490,30,5,1,5,COMPLETE,6.191264,"{""classifier__colsample_bytree"": 0.9634427510288239, ""classifier__learning_rate"": 0.032822831099235304, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 279, ""classifier__subsample"": 0.7509491258693707}",1.200029,0.094773,0.035076,0.001065,0.997872,0.997305,0.997438,0.998138,0.998005,0.997752,0.000324,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,xgboost,optuna,iot23,235490,30,5,1,1,0.666862,0.079990,0.999786,0.993842,0.996805,0.998463,0.999947,0.999204,0.998005,0.998726,0.996895
1,xgboost,optuna,iot23,235490,30,5,1,2,0.670874,0.076748,0.999679,0.992144,0.995897,0.998040,0.999920,0.998979,0.997438,0.998365,0.996032
2,xgboost,optuna,iot23,235490,30,5,1,3,0.637846,0.080469,0.999572,0.992463,0.996005,0.998119,0.999894,0.999006,0.997505,0.998408,0.996178
3,xgboost,optuna,iot23,235490,30,5,1,4,0.626813,0.079029,1.000000,0.994268,0.997126,0.998569,1.000000,0.999284,0.998205,0.998853,0.997134
4,xgboost,optuna,iot23,235490,30,5,1,5,0.652888,0.076067,0.999786,0.993843,0.996806,0.998463,0.999947,0.999204,0.998005,0.998726,0.996895

Modelo: xgboost | origem do treinamento: cicids2017_unsw_nb15

[I 2026-10-12 03:50:57,552] A new study created in memory with name: xgboost_cicids2017_unsw_nb15
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:51:08,640] Trial 0 finished with value: 0.984207021225283 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.03000790177293386, 'classifier__subsample': 0.7906997717895519, 'classifier__colsample_bytree': 0.7440267672451338}. Best is trial 0 with value: 0.984207021225283.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:51:14,685] Trial 1 finished with value: 0.9776141441469435 and parameters: {'classifier__n_estimators': 118, 'classifier__max_depth': 4, 'classifier__learning_rate': 0.06647861789041172, 'classifier__subsample': 0.819030242269201, 'classifier__colsample_bytree': 0.8616450202010071}. Best is trial 0 with value: 0.984207021225283.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:51:24,661] Trial 2 finished with value: 0.9849578490556121 and parameters: {'classifier__n_estimators': 184, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.0480367375659992, 'classifier__subsample': 0.9634352309172836, 'classifier__colsample_bytree': 0.7082162779593778}. Best is trial 2 with value: 0.9849578490556121.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:51:35,612] Trial 3 finished with value: 0.9849404124396918 and parameters: {'classifier__n_estimators': 234, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.10859531344085706, 'classifier__subsample': 0.7421160815785701, 'classifier__colsample_bytree': 0.7594304467254636}. Best is trial 2 with value: 0.9849578490556121.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:51:49,704] Trial 4 finished with value: 0.9856472406043452 and parameters: {'classifier__n_estimators': 260, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06173698734681893, 'classifier__subsample': 0.9076967847007942, 'classifier__colsample_bytree': 0.9629167456888115}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:52:01,128] Trial 5 finished with value: 0.9754557431447278 and parameters: {'classifier__n_estimators': 279, 'classifier__max_depth': 3, 'classifier__learning_rate': 0.032822831099235304, 'classifier__subsample': 0.7509491258693707, 'classifier__colsample_bytree': 0.9634427510288239}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:52:07,504] Trial 6 finished with value: 0.9850742572835911 and parameters: {'classifier__n_estimators': 119, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.27227689219802986, 'classifier__subsample': 0.859949585491905, 'classifier__colsample_bytree': 0.907563134185142}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:52:16,757] Trial 7 finished with value: 0.98552435821631 and parameters: {'classifier__n_estimators': 163, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.20499672676341157, 'classifier__subsample': 0.7054864832032575, 'classifier__colsample_bytree': 0.9250432944834902}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:52:31,942] Trial 8 finished with value: 0.9854931077700139 and parameters: {'classifier__n_estimators': 298, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.05722229168328298, 'classifier__subsample': 0.9367837985354466, 'classifier__colsample_bytree': 0.7309678019732926}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:52:43,436] Trial 9 finished with value: 0.9855114501962688 and parameters: {'classifier__n_estimators': 190, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.05898416056128349, 'classifier__subsample': 0.7863326015759046, 'classifier__colsample_bytree': 0.7390085716354833}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:52:58,033] Trial 10 finished with value: 0.9850164755932909 and parameters: {'classifier__n_estimators': 288, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.03355271522020396, 'classifier__subsample': 0.9457462284934223, 'classifier__colsample_bytree': 0.997055611642783}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:53:13,504] Trial 11 finished with value: 0.98540394590513 and parameters: {'classifier__n_estimators': 284, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.14526259033330963, 'classifier__subsample': 0.8138000696610828, 'classifier__colsample_bytree': 0.9424215786432294}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:53:22,216] Trial 12 finished with value: 0.9855780979751365 and parameters: {'classifier__n_estimators': 146, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.17862359149072526, 'classifier__subsample': 0.8362899548808053, 'classifier__colsample_bytree': 0.9332070667471085}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:53:33,396] Trial 13 finished with value: 0.9856005527481788 and parameters: {'classifier__n_estimators': 175, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.08882600147722249, 'classifier__subsample': 0.8874458993333433, 'classifier__colsample_bytree': 0.98139392662449}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:53:44,860] Trial 14 finished with value: 0.9856080820432785 and parameters: {'classifier__n_estimators': 214, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.09588757749499387, 'classifier__subsample': 0.8619767757110919, 'classifier__colsample_bytree': 0.9563639325251423}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:53:58,340] Trial 15 finished with value: 0.9856125840647953 and parameters: {'classifier__n_estimators': 239, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06095459173995253, 'classifier__subsample': 0.8853554419721588, 'classifier__colsample_bytree': 0.9617345244866197}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:54:11,810] Trial 16 finished with value: 0.9855744322608878 and parameters: {'classifier__n_estimators': 246, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.05614401815182934, 'classifier__subsample': 0.8692704402778306, 'classifier__colsample_bytree': 0.9402492388524982}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:54:25,151] Trial 17 finished with value: 0.9854897511704884 and parameters: {'classifier__n_estimators': 242, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.050441578445405214, 'classifier__subsample': 0.9259467402035013, 'classifier__colsample_bytree': 0.9930842488188111}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:54:40,010] Trial 18 finished with value: 0.9856438666858554 and parameters: {'classifier__n_estimators': 286, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06324408793416796, 'classifier__subsample': 0.946087053997854, 'classifier__colsample_bytree': 0.8687206072008071}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:54:54,579] Trial 19 finished with value: 0.9856125155444966 and parameters: {'classifier__n_estimators': 285, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.0787975359386056, 'classifier__subsample': 0.9923561970390533, 'classifier__colsample_bytree': 0.9061034301603393}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:55:06,934] Trial 20 finished with value: 0.9854559649064836 and parameters: {'classifier__n_estimators': 223, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.050064112620704156, 'classifier__subsample': 0.9010772045482742, 'classifier__colsample_bytree': 0.8719491051387778}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:55:22,849] Trial 21 finished with value: 0.9854602486524486 and parameters: {'classifier__n_estimators': 293, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.03716910895494346, 'classifier__subsample': 0.8836734334116035, 'classifier__colsample_bytree': 0.8883367103380616}. Best is trial 4 with value: 0.9856472406043452.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:55:35,030] Trial 22 finished with value: 0.9857208772165065 and parameters: {'classifier__n_estimators': 227, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.08764086364133913, 'classifier__subsample': 0.9249996971958904, 'classifier__colsample_bytree': 0.9899866166981167}. Best is trial 22 with value: 0.9857208772165065.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:55:47,136] Trial 23 finished with value: 0.9857071985022248 and parameters: {'classifier__n_estimators': 226, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.09380402383184405, 'classifier__subsample': 0.9628863575423227, 'classifier__colsample_bytree': 0.9230561514310412}. Best is trial 22 with value: 0.9857208772165065.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:55:58,820] Trial 24 finished with value: 0.9856435042083763 and parameters: {'classifier__n_estimators': 215, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.0852871789929276, 'classifier__subsample': 0.9281508760025046, 'classifier__colsample_bytree': 0.9551203568223886}. Best is trial 22 with value: 0.9857208772165065.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:56:09,851] Trial 25 finished with value: 0.9856776646010121 and parameters: {'classifier__n_estimators': 225, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.1199753855055712, 'classifier__subsample': 0.967729131704429, 'classifier__colsample_bytree': 0.9253950379612328}. Best is trial 22 with value: 0.9857208772165065.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:56:22,047] Trial 26 finished with value: 0.9857165799901709 and parameters: {'classifier__n_estimators': 233, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.11236744307961766, 'classifier__subsample': 0.985928897550576, 'classifier__colsample_bytree': 0.9325167930946302}. Best is trial 22 with value: 0.9857208772165065.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:56:35,813] Trial 27 finished with value: 0.9856094398229999 and parameters: {'classifier__n_estimators': 270, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.1204106730019636, 'classifier__subsample': 0.9273154087169277, 'classifier__colsample_bytree': 0.9628731075026138}. Best is trial 22 with value: 0.9857208772165065.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:56:47,122] Trial 28 finished with value: 0.985707676291834 and parameters: {'classifier__n_estimators': 209, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.13530900300011928, 'classifier__subsample': 0.9035362815760095, 'classifier__colsample_bytree': 0.9690070118646403}. Best is trial 22 with value: 0.9857208772165065.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
22,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,22,COMPLETE,12.180709,"{""classifier__colsample_bytree"": 0.9899866166981167, ""classifier__learning_rate"": 0.08764086364133913, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 227, ""classifier__subsample"": 0.9249996971958904}",2.343821,0.107624,0.086774,0.002874,0.985086,0.985629,0.987004,0.985467,0.985418,0.985721,0.000665,1
26,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,26,COMPLETE,12.194708,"{""classifier__colsample_bytree"": 0.9325167930946302, ""classifier__learning_rate"": 0.11236744307961766, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 233, ""classifier__subsample"": 0.985928897550576}",2.342829,0.074716,0.090568,0.004172,0.985165,0.985710,0.986948,0.985362,0.985399,0.985717,0.000640,2
28,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,28,COMPLETE,11.308090,"{""classifier__colsample_bytree"": 0.9690070118646403, ""classifier__learning_rate"": 0.13530900300011928, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 209, ""classifier__subsample"": 0.9035362815760095}",2.175665,0.096623,0.080040,0.001237,0.985257,0.985657,0.986911,0.985456,0.985258,0.985708,0.000619,3
23,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,23,COMPLETE,12.105522,"{""classifier__colsample_bytree"": 0.9230561514310412, ""classifier__learning_rate"": 0.09380402383184405, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 226, ""classifier__subsample"": 0.9628863575423227}",2.330158,0.085358,0.085590,0.002509,0.985153,0.985697,0.986884,0.985531,0.985271,0.985707,0.000619,4
25,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,25,COMPLETE,11.031258,"{""classifier__colsample_bytree"": 0.9253950379612328, ""classifier__learning_rate"": 0.1199753855055712, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 225, ""classifier__subsample"": 0.967729131704429}",2.122050,0.101409,0.078787,0.001611,0.985281,0.985616,0.986773,0.985447,0.985273,0.985678,0.000562,5
4,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,4,COMPLETE,14.090745,"{""classifier__colsample_bytree"": 0.9629167456888115, ""classifier__learning_rate"": 0.06173698734681893, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 260, ""classifier__subsample"": 0.9076967847007942}",2.722255,0.123453,0.091375,0.001595,0.985096,0.985652,0.986776,0.985505,0.985207,0.985647,0.000598,6
18,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,18,COMPLETE,14.858527,"{""classifier__colsample_bytree"": 0.8687206072008071, ""classifier__learning_rate"": 0.06324408793416796, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 286, ""classifier__subsample"": 0.946087053997854}",2.859675,0.086578,0.106422,0.009981,0.985122,0.985764,0.986674,0.985418,0.985241,0.985644,0.000559,7
24,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,24,COMPLETE,11.682707,"{""classifier__colsample_bytree"": 0.9551203568223886, ""classifier__learning_rate"": 0.0852871789929276, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 215, ""classifier__subsample"": 0.9281508760025046}",2.247660,0.094534,0.083438,0.004384,0.985187,0.985647,0.986741,0.985487,0.985155,0.985644,0.000579,8
15,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,15,COMPLETE,13.480010,"{""classifier__colsample_bytree"": 0.9617345244866197, ""classifier__learning_rate"": 0.06095459173995253, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 239, ""classifier__subsample"": 0.8853554419721588}",2.601684,0.121582,0.088808,0.001605,0.985062,0.985555,0.986680,0.985638,0.985128,0.985613,0.000580,9
19,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,19,COMPLETE,14.568246,"{""classifier__colsample_bytree"": 0.9061034301603393, ""classifier__learning_rate"": 0.0787975359386056, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 285, ""classifier__subsample"": 0.9923561970390533}",2.807917,0.070136,0.100187,0.002286,0.985185,0.985632,0.986740,0.985431,0.985074,0.985613,0.000596,10
27,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,27,COMPLETE,13.765563,"{""classifier__colsample_bytree"": 0.9628731075026138, ""classifier__learning_rate"": 0.1204106730019636, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 270, ""classifier__subsample"": 0.9273154087169277}",2.650960,0.093148,0.096487,0.001856,0.985203,0.985705,0.986807,0.985173,0.985159,0.985609,0.000633,11
14,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,14,COMPLETE,11.462860,"{""classifier__colsample_bytree"": 0.9563639325251423, ""classifier__learning_rate"": 0.09588757749499387, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 214, ""classifier__subsample"": 0.8619767757110919}",2.204375,0.063861,0.082752,0.010888,0.985155,0.985714,0.986710,0.985319,0.985143,0.985608,0.000588,12
13,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,13,COMPLETE,11.180150,"{""classifier__colsample_bytree"": 0.98139392662449, ""classifier__learning_rate"": 0.08882600147722249, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 175, ""classifier__subsample"": 0.8874458993333433}",2.151456,0.191200,0.079203,0.012550,0.985058,0.985603,0.986777,0.985423,0.985142,0.985601,0.000620,13
12,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,12,COMPLETE,8.711224,"{""classifier__colsample_bytree"": 0.9332070667471085, ""classifier__learning_rate"": 0.17862359149072526, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 146, ""classifier__subsample"": 0.8362899548808053}",1.668082,0.094020,0.068923,0.003812,0.985174,0.985558,0.986612,0.985388,0.985159,0.985578,0.000537,14
16,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,16,COMPLETE,13.468809,"{""classifier__colsample_bytree"": 0.9402492388524982, ""classifier__learning_rate"": 0.05614401815182934, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 246, ""classifier__subsample"": 0.8692704402778306}",2.591395,0.121495,0.096804,0.010008,0.985079,0.985556,0.986713,0.985425,0.985099,0.985574,0.000598,15
7,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,7,COMPLETE,9.252250,"{""classifier__colsample_bytree"": 0.9250432944834902, ""classifier__learning_rate"": 0.20499672676341157, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 163, ""classifier__subsample"": 0.7054864832032575}",1.774828,0.091500,0.071221,0.010421,0.985265,0.985306,0.986463,0.985352,0.985235,0.985524,0.000471,16
9,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,9,COMPLETE,11.493844,"{""classifier__colsample_bytree"": 0.7390085716354833, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 190, ""classifier__subsample"": 0.7863326015759046}",2.209530,0.285438,0.084763,0.011063,0.984976,0.985409,0.986763,0.985359,0.985050,0.985511,0.000648,17
8,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,8,COMPLETE,15.184621,"{""classifier__colsample_bytree"": 0.7309678019732926, ""classifier__learning_rate"": 0.05722229168328298, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9367837985354466}",2.933477,0.281255,0.098694,0.003659,0.984894,0.985471,0.986664,0.985422,0.985014,0.985493,0.000627,18
29,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,29,COMPLETE,11.369515,"{""classifier__colsample_bytree"": 0.9879767464660101, ""classifier__learning_rate"": 0.17921154249720816, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 205, ""classifier__subsample"": 0.8969060968144698}",2.180525,0.098534,0.087797,0.010469,0.984933,0.985502,0.986572,0.985312,0.985135,0.985491,0.000573,19
17,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,17,COMPLETE,13.340509,"{""classifier__colsample_bytree"": 0.9930842488188111, ""classifier__learning_rate"": 0.050441578445405214, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 242, ""classifier__subsample"": 0.9259467402035013}",2.566313,0.096688,0.096231,0.009421,0.984884,0.985394,0.986632,0.985476,0.985063,0.985490,0.000610,20
21,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,21,COMPLETE,15.913988,"{""classifier__colsample_bytree"": 0.8883367103380616, ""classifier__learning_rate"": 0.03716910895494346, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 293, ""classifier__subsample"": 0.8836734334116035}",3.069499,0.096817,0.107825,0.010238,0.984868,0.985375,0.986564,0.985445,0.985048,0.985460,0.000591,21
20,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,20,COMPLETE,12.354565,"{""classifier__colsample_bytree"": 0.8719491051387778, ""classifier__learning_rate"": 0.050064112620704156, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 223, ""classifier__subsample"": 0.9010772045482742}",2.375420,0.089805,0.089991,0.010098,0.984896,0.985507,0.986467,0.985378,0.985033,0.985456,0.000552,22
11,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,11,COMPLETE,15.470212,"{""classifier__colsample_bytree"": 0.9424215786432294, ""classifier__learning_rate"": 0.14526259033330963, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 284, ""classifier__subsample"": 0.8138000696610828}",2.986106,0.144736,0.102401,0.000756,0.984956,0.985145,0.986418,0.985307,0.985193,0.985404,0.000519,23
6,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,6,COMPLETE,6.374886,"{""classifier__colsample_bytree"": 0.907563134185142, ""classifier__learning_rate"": 0.27227689219802986, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 119, ""classifier__subsample"": 0.859949585491905}",1.216110,0.095100,0.054583,0.005296,0.984512,0.985008,0.986367,0.984978,0.984507,0.985074,0.000682,24
10,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,10,COMPLETE,14.595730,"{""classifier__colsample_bytree"": 0.997055611642783, ""classifier__learning_rate"": 0.03355271522020396, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 288, ""classifier__subsample"": 0.9457462284934223}",2.815926,0.060380,0.097828,0.009800,0.984482,0.984716,0.986201,0.985061,0.984623,0.985016,0.000622,25
2,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,2,COMPLETE,9.976037,"{""classifier__colsample_bytree"": 0.7082162779593778, ""classifier__learning_rate"": 0.0480367375659992, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 184, ""classifier__subsample"": 0.9634352309172836}",1.918879,0.145781,0.071872,0.002568,0.984449,0.984727,0.986199,0.984975,0.984439,0.984958,0.000652,26
3,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,3,COMPLETE,10.950178,"{""classifier__colsample_bytree"": 0.7594304467254636, ""classifier__learning_rate"": 0.10859531344085706, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 234, ""classifier__subsample"": 0.7421160815785701}",2.118043,0.115065,0.067392,0.002534,0.984366,0.984874,0.986267,0.984793,0.984403,0.984940,0.000694,27
0,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,0,COMPLETE,11.085339,"{""classifier__colsample_bytree"": 0.7440267672451338, ""classifier__learning_rate"": 0.03000790177293386, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 183, ""classifier__subsample"": 0.7906997717895519}",2.126873,0.264984,0.086013,0.011527,0.983685,0.984076,0.985571,0.984062,0.983641,0.984207,0.000706,28
1,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,1,COMPLETE,6.044412,"{""classifier__colsample_bytree"": 0.8616450202010071, ""classifier__learning_rate"": 0.06647861789041172, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 118, ""classifier__subsample"": 0.819030242269201}",1.152920,0.094193,0.051648,0.004456,0.976244,0.977911,0.978753,0.977938,0.977225,0.977614,0.000839,29
5,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,5,COMPLETE,11.423974,"{""classifier__colsample_bytree"": 0.9634427510288239, ""classifier__learning_rate"": 0.032822831099235304, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 279, ""classifier__subsample"": 0.7509491258693707}",2.211587,0.125483,0.068798,0.008075,0.973603,0.975898,0.978065,0.974672,0.975041,0.975456,0.001498,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,1,2.251095,0.161793,0.959408,0.993683,0.976244,0.998407,0.989490,0.993928,0.985086,0.990329,0.991587
1,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,2,2.216924,0.165105,0.961461,0.993258,0.977101,0.998301,0.990048,0.994157,0.985629,0.990690,0.991653
2,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,3,2.238858,0.158849,0.963909,0.995170,0.979290,0.998783,0.990684,0.994717,0.987004,0.991581,0.992927
3,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,4,2.219487,0.165725,0.961161,0.993047,0.976844,0.998247,0.989968,0.994090,0.985467,0.990583,0.991507
4,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,5,2.352530,0.166614,0.959641,0.994533,0.976776,0.998621,0.989543,0.994061,0.985418,0.990541,0.992038

Modelo: xgboost | origem do treinamento: cicids2017_iot23

[I 2026-10-12 03:57:14,375] A new study created in memory with name: xgboost_cicids2017_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:57:25,111] Trial 0 finished with value: 0.9938370129033223 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.03000790177293386, 'classifier__subsample': 0.7906997717895519, 'classifier__colsample_bytree': 0.7440267672451338}. Best is trial 0 with value: 0.9938370129033223.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:57:31,814] Trial 1 finished with value: 0.9911422253099195 and parameters: {'classifier__n_estimators': 118, 'classifier__max_depth': 4, 'classifier__learning_rate': 0.06647861789041172, 'classifier__subsample': 0.819030242269201, 'classifier__colsample_bytree': 0.8616450202010071}. Best is trial 0 with value: 0.9938370129033223.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:57:41,107] Trial 2 finished with value: 0.9940262707215639 and parameters: {'classifier__n_estimators': 184, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.0480367375659992, 'classifier__subsample': 0.9634352309172836, 'classifier__colsample_bytree': 0.7082162779593778}. Best is trial 2 with value: 0.9940262707215639.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:57:51,841] Trial 3 finished with value: 0.9941232471964995 and parameters: {'classifier__n_estimators': 234, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.10859531344085706, 'classifier__subsample': 0.7421160815785701, 'classifier__colsample_bytree': 0.7594304467254636}. Best is trial 3 with value: 0.9941232471964995.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:58:04,915] Trial 4 finished with value: 0.9942322432144831 and parameters: {'classifier__n_estimators': 260, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06173698734681893, 'classifier__subsample': 0.9076967847007942, 'classifier__colsample_bytree': 0.9629167456888115}. Best is trial 4 with value: 0.9942322432144831.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:58:16,279] Trial 5 finished with value: 0.9896341639813965 and parameters: {'classifier__n_estimators': 279, 'classifier__max_depth': 3, 'classifier__learning_rate': 0.032822831099235304, 'classifier__subsample': 0.7509491258693707, 'classifier__colsample_bytree': 0.9634427510288239}. Best is trial 4 with value: 0.9942322432144831.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:58:22,360] Trial 6 finished with value: 0.9941791722745684 and parameters: {'classifier__n_estimators': 119, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.27227689219802986, 'classifier__subsample': 0.859949585491905, 'classifier__colsample_bytree': 0.907563134185142}. Best is trial 4 with value: 0.9942322432144831.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:58:31,937] Trial 7 finished with value: 0.9941393742120441 and parameters: {'classifier__n_estimators': 163, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.20499672676341157, 'classifier__subsample': 0.7054864832032575, 'classifier__colsample_bytree': 0.9250432944834902}. Best is trial 4 with value: 0.9942322432144831.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:58:45,496] Trial 8 finished with value: 0.9942326098870982 and parameters: {'classifier__n_estimators': 298, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.05722229168328298, 'classifier__subsample': 0.9367837985354466, 'classifier__colsample_bytree': 0.7309678019732926}. Best is trial 8 with value: 0.9942326098870982.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:58:55,679] Trial 9 finished with value: 0.9942158478727071 and parameters: {'classifier__n_estimators': 190, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.05898416056128349, 'classifier__subsample': 0.7863326015759046, 'classifier__colsample_bytree': 0.7390085716354833}. Best is trial 8 with value: 0.9942326098870982.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:59:08,857] Trial 10 finished with value: 0.994257985320426 and parameters: {'classifier__n_estimators': 281, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.08367410349214705, 'classifier__subsample': 0.8801886955254052, 'classifier__colsample_bytree': 0.7257453039000061}. Best is trial 10 with value: 0.994257985320426.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:59:23,442] Trial 11 finished with value: 0.9943307844167826 and parameters: {'classifier__n_estimators': 295, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.0675693609485163, 'classifier__subsample': 0.9068296839507027, 'classifier__colsample_bytree': 0.733728951824139}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:59:35,638] Trial 12 finished with value: 0.9942476439948701 and parameters: {'classifier__n_estimators': 262, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.11173366728075725, 'classifier__subsample': 0.8788065906496572, 'classifier__colsample_bytree': 0.7292092968714783}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 03:59:47,938] Trial 13 finished with value: 0.9942321824593607 and parameters: {'classifier__n_estimators': 281, 'classifier__max_depth': 6, 'classifier__learning_rate': 0.10188676841297015, 'classifier__subsample': 0.9069507413871317, 'classifier__colsample_bytree': 0.8142584014246752}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:00:00,115] Trial 14 finished with value: 0.9940803756270375 and parameters: {'classifier__n_estimators': 280, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.07366987723268603, 'classifier__subsample': 0.8211586541640608, 'classifier__colsample_bytree': 0.715512294919408}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:00:12,877] Trial 15 finished with value: 0.9942177285132289 and parameters: {'classifier__n_estimators': 252, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.07765320028758296, 'classifier__subsample': 0.8629526508799245, 'classifier__colsample_bytree': 0.7943211703611323}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:00:27,321] Trial 16 finished with value: 0.9942615787106461 and parameters: {'classifier__n_estimators': 292, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.07163341656406279, 'classifier__subsample': 0.7753747151737316, 'classifier__colsample_bytree': 0.775464874455185}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:00:38,572] Trial 17 finished with value: 0.9939506984822077 and parameters: {'classifier__n_estimators': 248, 'classifier__max_depth': 6, 'classifier__learning_rate': 0.04151631179829661, 'classifier__subsample': 0.922339048476879, 'classifier__colsample_bytree': 0.8104646642201216}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:00:53,433] Trial 18 finished with value: 0.994153486168915 and parameters: {'classifier__n_estimators': 295, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.08449614790644853, 'classifier__subsample': 0.7886991755799742, 'classifier__colsample_bytree': 0.8653994583105493}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:01:06,480] Trial 19 finished with value: 0.9942183930348094 and parameters: {'classifier__n_estimators': 259, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.07833808757158632, 'classifier__subsample': 0.765632961998103, 'classifier__colsample_bytree': 0.7906582796318218}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:01:20,000] Trial 20 finished with value: 0.9942913375372282 and parameters: {'classifier__n_estimators': 290, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.0731867178774419, 'classifier__subsample': 0.9656743006024917, 'classifier__colsample_bytree': 0.8051923728103373}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:01:32,898] Trial 21 finished with value: 0.9942155726272638 and parameters: {'classifier__n_estimators': 266, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.05376210356508267, 'classifier__subsample': 0.9917721056194725, 'classifier__colsample_bytree': 0.7519954011264963}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:01:46,195] Trial 22 finished with value: 0.9941303502128507 and parameters: {'classifier__n_estimators': 295, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.12195489909180829, 'classifier__subsample': 0.9817628589467864, 'classifier__colsample_bytree': 0.7208761362088312}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:01:59,183] Trial 23 finished with value: 0.9942125800488745 and parameters: {'classifier__n_estimators': 257, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.04915836764454548, 'classifier__subsample': 0.9934361027834819, 'classifier__colsample_bytree': 0.8221116943281451}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:02:12,954] Trial 24 finished with value: 0.9942123557581791 and parameters: {'classifier__n_estimators': 275, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.0499645871704915, 'classifier__subsample': 0.8630580169326147, 'classifier__colsample_bytree': 0.8086380154693131}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:02:25,517] Trial 25 finished with value: 0.9942714157639087 and parameters: {'classifier__n_estimators': 258, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06889511887397343, 'classifier__subsample': 0.9127369014198069, 'classifier__colsample_bytree': 0.757554314096737}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:02:40,605] Trial 26 finished with value: 0.9942578857467304 and parameters: {'classifier__n_estimators': 295, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.07497992461880537, 'classifier__subsample': 0.9622170656839338, 'classifier__colsample_bytree': 0.7976472923192888}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:02:52,688] Trial 27 finished with value: 0.9941560550737248 and parameters: {'classifier__n_estimators': 237, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.04347392775667993, 'classifier__subsample': 0.9443440353599775, 'classifier__colsample_bytree': 0.7513166066268374}. Best is trial 11 with value: 0.9943307844167826.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:03:07,802] Trial 28 finished with value: 0.9941995307438438 and parameters: {'classifier__n_estimators': 299, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.042187937583994285, 'classifier__subsample': 0.8881901587416006, 'classifier__colsample_bytree': 0.7542843201054525}. Best is trial 11 with value: 0.9943307844167826.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
11,xgboost,optuna,cicids2017_iot23,470980,30,5,1,11,COMPLETE,14.584537,"{""classifier__colsample_bytree"": 0.733728951824139, ""classifier__learning_rate"": 0.0675693609485163, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 295, ""classifier__subsample"": 0.9068296839507027}",2.806821,0.090250,0.104762,0.008745,0.994667,0.994201,0.994882,0.994116,0.993788,0.994331,0.000393,1
20,xgboost,optuna,cicids2017_iot23,470980,30,5,1,20,COMPLETE,13.519910,"{""classifier__colsample_bytree"": 0.8051923728103373, ""classifier__learning_rate"": 0.0731867178774419, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 290, ""classifier__subsample"": 0.9656743006024917}",2.601654,0.103294,0.096931,0.002153,0.994484,0.994218,0.994932,0.994067,0.993755,0.994291,0.000398,2
25,xgboost,optuna,cicids2017_iot23,470980,30,5,1,25,COMPLETE,12.562158,"{""classifier__colsample_bytree"": 0.757554314096737, ""classifier__learning_rate"": 0.06889511887397343, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 258, ""classifier__subsample"": 0.9127369014198069}",2.416687,0.147889,0.090275,0.002923,0.994552,0.994152,0.994848,0.994017,0.993788,0.994271,0.000380,3
29,xgboost,optuna,cicids2017_iot23,470980,30,5,1,29,COMPLETE,14.402642,"{""classifier__colsample_bytree"": 0.8089658873377489, ""classifier__learning_rate"": 0.05157471688505652, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 300, ""classifier__subsample"": 0.9777009002259874}",2.769121,0.127591,0.105846,0.010479,0.994419,0.994135,0.994949,0.994019,0.993788,0.994262,0.000399,4
16,xgboost,optuna,cicids2017_iot23,470980,30,5,1,16,COMPLETE,14.444101,"{""classifier__colsample_bytree"": 0.775464874455185, ""classifier__learning_rate"": 0.07163341656406279, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 292, ""classifier__subsample"": 0.7753747151737316}",2.791330,0.208508,0.091938,0.002459,0.994435,0.994152,0.994931,0.994051,0.993740,0.994262,0.000402,5
10,xgboost,optuna,cicids2017_iot23,470980,30,5,1,10,COMPLETE,13.176567,"{""classifier__colsample_bytree"": 0.7257453039000061, ""classifier__learning_rate"": 0.08367410349214705, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 281, ""classifier__subsample"": 0.8801886955254052}",2.538277,0.123452,0.091732,0.003425,0.994435,0.994235,0.994931,0.994033,0.993656,0.994258,0.000424,6
26,xgboost,optuna,cicids2017_iot23,470980,30,5,1,26,COMPLETE,15.087661,"{""classifier__colsample_bytree"": 0.7976472923192888, ""classifier__learning_rate"": 0.07497992461880537, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 295, ""classifier__subsample"": 0.9622170656839338}",2.905803,0.321891,0.106178,0.010778,0.994501,0.994218,0.994849,0.994017,0.993705,0.994258,0.000393,7
12,xgboost,optuna,cicids2017_iot23,470980,30,5,1,12,COMPLETE,12.195710,"{""classifier__colsample_bytree"": 0.7292092968714783, ""classifier__learning_rate"": 0.11173366728075725, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 262, ""classifier__subsample"": 0.8788065906496572}",2.343432,0.101538,0.090286,0.011224,0.994386,0.994200,0.994914,0.993983,0.993754,0.994248,0.000395,8
8,xgboost,optuna,cicids2017_iot23,470980,30,5,1,8,COMPLETE,13.557968,"{""classifier__colsample_bytree"": 0.7309678019732926, ""classifier__learning_rate"": 0.05722229168328298, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9367837985354466}",2.615272,0.098953,0.091793,0.002402,0.994436,0.994202,0.994866,0.994019,0.993641,0.994233,0.000410,9
4,xgboost,optuna,cicids2017_iot23,470980,30,5,1,4,COMPLETE,13.073892,"{""classifier__colsample_bytree"": 0.9629167456888115, ""classifier__learning_rate"": 0.06173698734681893, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 260, ""classifier__subsample"": 0.9076967847007942}",2.519087,0.119556,0.091159,0.000734,0.994336,0.994202,0.994849,0.994051,0.993724,0.994232,0.000370,10
13,xgboost,optuna,cicids2017_iot23,470980,30,5,1,13,COMPLETE,12.298736,"{""classifier__colsample_bytree"": 0.8142584014246752, ""classifier__learning_rate"": 0.10188676841297015, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 281, ""classifier__subsample"": 0.9069507413871317}",2.371915,0.093741,0.082274,0.001172,0.994385,0.994169,0.994899,0.994018,0.993690,0.994232,0.000403,11
19,xgboost,optuna,cicids2017_iot23,470980,30,5,1,19,COMPLETE,13.046217,"{""classifier__colsample_bytree"": 0.7906582796318218, ""classifier__learning_rate"": 0.07833808757158632, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 259, ""classifier__subsample"": 0.765632961998103}",2.512049,0.169454,0.091367,0.009782,0.994352,0.994102,0.994849,0.994001,0.993788,0.994218,0.000364,12
15,xgboost,optuna,cicids2017_iot23,470980,30,5,1,15,COMPLETE,12.761160,"{""classifier__colsample_bytree"": 0.7943211703611323, ""classifier__learning_rate"": 0.07765320028758296, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 252, ""classifier__subsample"": 0.8629526508799245}",2.447301,0.103603,0.099149,0.014767,0.994434,0.994067,0.994848,0.994017,0.993722,0.994218,0.000388,13
9,xgboost,optuna,cicids2017_iot23,470980,30,5,1,9,COMPLETE,10.182975,"{""classifier__colsample_bytree"": 0.7390085716354833, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 190, ""classifier__subsample"": 0.7863326015759046}",1.957814,0.115159,0.074163,0.000499,0.994436,0.994169,0.994832,0.994035,0.993608,0.994216,0.000408,14
21,xgboost,optuna,cicids2017_iot23,470980,30,5,1,21,COMPLETE,12.896850,"{""classifier__colsample_bytree"": 0.7519954011264963, ""classifier__learning_rate"": 0.05376210356508267, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 266, ""classifier__subsample"": 0.9917721056194725}",2.480746,0.143719,0.093238,0.001346,0.994386,0.994152,0.994849,0.994019,0.993672,0.994216,0.000392,15
23,xgboost,optuna,cicids2017_iot23,470980,30,5,1,23,COMPLETE,12.987455,"{""classifier__colsample_bytree"": 0.8221116943281451, ""classifier__learning_rate"": 0.04915836764454548, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 257, ""classifier__subsample"": 0.9934361027834819}",2.498256,0.083913,0.093753,0.009323,0.994435,0.994203,0.994750,0.994052,0.993623,0.994213,0.000377,16
24,xgboost,optuna,cicids2017_iot23,470980,30,5,1,24,COMPLETE,13.769873,"{""classifier__colsample_bytree"": 0.8086380154693131, ""classifier__learning_rate"": 0.0499645871704915, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 275, ""classifier__subsample"": 0.8630580169326147}",2.649436,0.092508,0.099057,0.008857,0.994402,0.994153,0.994799,0.994018,0.993690,0.994212,0.000373,17
28,xgboost,optuna,cicids2017_iot23,470980,30,5,1,28,COMPLETE,15.112876,"{""classifier__colsample_bytree"": 0.7542843201054525, ""classifier__learning_rate"": 0.042187937583994285, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 299, ""classifier__subsample"": 0.8881901587416006}",2.914759,0.135728,0.101109,0.001511,0.994336,0.994203,0.994749,0.994002,0.993707,0.994200,0.000347,18
6,xgboost,optuna,cicids2017_iot23,470980,30,5,1,6,COMPLETE,6.080529,"{""classifier__colsample_bytree"": 0.907563134185142, ""classifier__learning_rate"": 0.27227689219802986, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 119, ""classifier__subsample"": 0.859949585491905}",1.158583,0.131050,0.053237,0.002644,0.994519,0.994085,0.994683,0.993952,0.993657,0.994179,0.000375,19
27,xgboost,optuna,cicids2017_iot23,470980,30,5,1,27,COMPLETE,12.083011,"{""classifier__colsample_bytree"": 0.7513166066268374, ""classifier__learning_rate"": 0.04347392775667993, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 237, ""classifier__subsample"": 0.9443440353599775}",2.321793,0.104053,0.089315,0.004351,0.994302,0.994186,0.994733,0.994002,0.993557,0.994156,0.000384,20
18,xgboost,optuna,cicids2017_iot23,470980,30,5,1,18,COMPLETE,14.860135,"{""classifier__colsample_bytree"": 0.8653994583105493, ""classifier__learning_rate"": 0.08449614790644853, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 295, ""classifier__subsample"": 0.7886991755799742}",2.857515,0.140404,0.109098,0.009311,0.994269,0.994051,0.994830,0.993948,0.993670,0.994153,0.000389,21
7,xgboost,optuna,cicids2017_iot23,470980,30,5,1,7,COMPLETE,9.576782,"{""classifier__colsample_bytree"": 0.9250432944834902, ""classifier__learning_rate"": 0.20499672676341157, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 163, ""classifier__subsample"": 0.7054864832032575}",1.836008,0.127145,0.074923,0.010714,0.994333,0.993900,0.994713,0.994031,0.993720,0.994139,0.000350,22
22,xgboost,optuna,cicids2017_iot23,470980,30,5,1,22,COMPLETE,13.296497,"{""classifier__colsample_bytree"": 0.7208761362088312, ""classifier__learning_rate"": 0.12195489909180829, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 295, ""classifier__subsample"": 0.9817628589467864}",2.554568,0.101249,0.099149,0.002041,0.994286,0.993999,0.994897,0.993882,0.993587,0.994130,0.000444,23
3,xgboost,optuna,cicids2017_iot23,470980,30,5,1,3,COMPLETE,10.733616,"{""classifier__colsample_bytree"": 0.7594304467254636, ""classifier__learning_rate"": 0.10859531344085706, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 234, ""classifier__subsample"": 0.7421160815785701}",2.071138,0.115026,0.071174,0.005739,0.994286,0.993971,0.994734,0.994068,0.993557,0.994123,0.000386,24
14,xgboost,optuna,cicids2017_iot23,470980,30,5,1,14,COMPLETE,12.176683,"{""classifier__colsample_bytree"": 0.715512294919408, ""classifier__learning_rate"": 0.07366987723268603, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 280, ""classifier__subsample"": 0.8211586541640608}",2.354171,0.119253,0.075641,0.004138,0.994270,0.993987,0.994700,0.993986,0.993459,0.994080,0.000406,25
2,xgboost,optuna,cicids2017_iot23,470980,30,5,1,2,COMPLETE,9.291400,"{""classifier__colsample_bytree"": 0.7082162779593778, ""classifier__learning_rate"": 0.0480367375659992, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 184, ""classifier__subsample"": 0.9634352309172836}",1.782635,0.184671,0.071229,0.002882,0.994170,0.993953,0.994633,0.993952,0.993424,0.994026,0.000390,26
17,xgboost,optuna,cicids2017_iot23,470980,30,5,1,17,COMPLETE,11.250184,"{""classifier__colsample_bytree"": 0.8104646642201216, ""classifier__learning_rate"": 0.04151631179829661, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 248, ""classifier__subsample"": 0.922339048476879}",2.165902,0.131126,0.078747,0.003048,0.994005,0.993921,0.994600,0.993885,0.993343,0.993951,0.000400,27
0,xgboost,optuna,cicids2017_iot23,470980,30,5,1,0,COMPLETE,10.733449,"{""classifier__colsample_bytree"": 0.7440267672451338, ""classifier__learning_rate"": 0.03000790177293386, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 183, ""classifier__subsample"": 0.7906997717895519}",2.059964,0.214523,0.081711,0.012719,0.994004,0.993804,0.994467,0.993769,0.993142,0.993837,0.000427,28
1,xgboost,optuna,cicids2017_iot23,470980,30,5,1,1,COMPLETE,6.703085,"{""classifier__colsample_bytree"": 0.8616450202010071, ""classifier__learning_rate"": 0.06647861789041172, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 118, ""classifier__subsample"": 0.819030242269201}",1.286580,0.147618,0.049675,0.002515,0.991520,0.991030,0.992165,0.990545,0.990451,0.991142,0.000638,29
5,xgboost,optuna,cicids2017_iot23,470980,30,5,1,5,COMPLETE,11.362465,"{""classifier__colsample_bytree"": 0.9634427510288239, ""classifier__learning_rate"": 0.032822831099235304, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 279, ""classifier__subsample"": 0.7509491258693707}",2.204709,0.113895,0.063366,0.003526,0.990517,0.989925,0.989678,0.989223,0.988828,0.989634,0.000580,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,xgboost,optuna,cicids2017_iot23,470980,30,5,1,1,3.145051,0.176816,0.989479,0.993471,0.991471,0.998366,0.997359,0.997862,0.994667,0.996582,0.995415
1,xgboost,optuna,cicids2017_iot23,470980,30,5,1,2,2.896903,0.172957,0.989049,0.992409,0.990726,0.998101,0.997253,0.997677,0.994201,0.996284,0.994831
2,xgboost,optuna,cicids2017_iot23,470980,30,5,1,3,2.651372,0.171708,0.990005,0.993631,0.991814,0.998406,0.997492,0.997949,0.994882,0.996720,0.995561
3,xgboost,optuna,cicids2017_iot23,470980,30,5,1,4,2.615977,0.175179,0.989513,0.991667,0.990589,0.997915,0.997372,0.997644,0.994116,0.996231,0.994520
4,xgboost,optuna,cicids2017_iot23,470980,30,5,1,5,2.863141,0.176955,0.988311,0.991826,0.990065,0.997955,0.997067,0.997511,0.993788,0.996019,0.994447

Modelo: xgboost | origem do treinamento: unsw_nb15_iot23

[I 2026-10-12 04:03:41,994] A new study created in memory with name: xgboost_unsw_nb15_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:03:52,529] Trial 0 finished with value: 0.9885374993895735 and parameters: {'classifier__n_estimators': 183, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.03000790177293386, 'classifier__subsample': 0.7906997717895519, 'classifier__colsample_bytree': 0.7440267672451338}. Best is trial 0 with value: 0.9885374993895735.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:03:58,521] Trial 1 finished with value: 0.9852529867934944 and parameters: {'classifier__n_estimators': 118, 'classifier__max_depth': 4, 'classifier__learning_rate': 0.06647861789041172, 'classifier__subsample': 0.819030242269201, 'classifier__colsample_bytree': 0.8616450202010071}. Best is trial 0 with value: 0.9885374993895735.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:04:07,999] Trial 2 finished with value: 0.9887914554841132 and parameters: {'classifier__n_estimators': 184, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.0480367375659992, 'classifier__subsample': 0.9634352309172836, 'classifier__colsample_bytree': 0.7082162779593778}. Best is trial 2 with value: 0.9887914554841132.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:04:19,004] Trial 3 finished with value: 0.9890190188752539 and parameters: {'classifier__n_estimators': 234, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.10859531344085706, 'classifier__subsample': 0.7421160815785701, 'classifier__colsample_bytree': 0.7594304467254636}. Best is trial 3 with value: 0.9890190188752539.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:04:32,175] Trial 4 finished with value: 0.9891945056605701 and parameters: {'classifier__n_estimators': 260, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06173698734681893, 'classifier__subsample': 0.9076967847007942, 'classifier__colsample_bytree': 0.9629167456888115}. Best is trial 4 with value: 0.9891945056605701.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:04:43,537] Trial 5 finished with value: 0.9837464284699626 and parameters: {'classifier__n_estimators': 279, 'classifier__max_depth': 3, 'classifier__learning_rate': 0.032822831099235304, 'classifier__subsample': 0.7509491258693707, 'classifier__colsample_bytree': 0.9634427510288239}. Best is trial 4 with value: 0.9891945056605701.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:04:49,743] Trial 6 finished with value: 0.98902667483339 and parameters: {'classifier__n_estimators': 119, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.27227689219802986, 'classifier__subsample': 0.859949585491905, 'classifier__colsample_bytree': 0.907563134185142}. Best is trial 4 with value: 0.9891945056605701.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:04:58,741] Trial 7 finished with value: 0.9888713090265913 and parameters: {'classifier__n_estimators': 163, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.20499672676341157, 'classifier__subsample': 0.7054864832032575, 'classifier__colsample_bytree': 0.9250432944834902}. Best is trial 4 with value: 0.9891945056605701.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:05:12,687] Trial 8 finished with value: 0.989172586437647 and parameters: {'classifier__n_estimators': 298, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.05722229168328298, 'classifier__subsample': 0.9367837985354466, 'classifier__colsample_bytree': 0.7309678019732926}. Best is trial 4 with value: 0.9891945056605701.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:05:22,993] Trial 9 finished with value: 0.9891055581452346 and parameters: {'classifier__n_estimators': 190, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.05898416056128349, 'classifier__subsample': 0.7863326015759046, 'classifier__colsample_bytree': 0.7390085716354833}. Best is trial 4 with value: 0.9891945056605701.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:05:36,643] Trial 10 finished with value: 0.9887772494618439 and parameters: {'classifier__n_estimators': 288, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.03355271522020396, 'classifier__subsample': 0.9457462284934223, 'classifier__colsample_bytree': 0.997055611642783}. Best is trial 4 with value: 0.9891945056605701.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:05:50,012] Trial 11 finished with value: 0.9892398282550856 and parameters: {'classifier__n_estimators': 280, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06328141991837156, 'classifier__subsample': 0.9641036110609162, 'classifier__colsample_bytree': 0.716575355191113}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:06:04,752] Trial 12 finished with value: 0.9891533544114528 and parameters: {'classifier__n_estimators': 295, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.04843125896474501, 'classifier__subsample': 0.8906347761980276, 'classifier__colsample_bytree': 0.880987039892758}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:06:16,590] Trial 13 finished with value: 0.989203605560195 and parameters: {'classifier__n_estimators': 246, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.1210981030393243, 'classifier__subsample': 0.9284684265293066, 'classifier__colsample_bytree': 0.8011175380795007}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:06:30,077] Trial 14 finished with value: 0.9888463084827428 and parameters: {'classifier__n_estimators': 275, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.1505296778163139, 'classifier__subsample': 0.9506432005245602, 'classifier__colsample_bytree': 0.7249059588401392}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:06:42,813] Trial 15 finished with value: 0.9891882619502512 and parameters: {'classifier__n_estimators': 251, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.06331081225921806, 'classifier__subsample': 0.9232239634712497, 'classifier__colsample_bytree': 0.7991370230895036}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:06:55,099] Trial 16 finished with value: 0.9891560075516244 and parameters: {'classifier__n_estimators': 291, 'classifier__max_depth': 6, 'classifier__learning_rate': 0.0990594409052359, 'classifier__subsample': 0.996352158393604, 'classifier__colsample_bytree': 0.7440052640765176}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:07:06,991] Trial 17 finished with value: 0.9891077579392256 and parameters: {'classifier__n_estimators': 254, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.12991019494452638, 'classifier__subsample': 0.9705410675720415, 'classifier__colsample_bytree': 0.7963123353901238}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:07:19,117] Trial 18 finished with value: 0.9890810560698787 and parameters: {'classifier__n_estimators': 277, 'classifier__max_depth': 6, 'classifier__learning_rate': 0.07151034415104235, 'classifier__subsample': 0.9565576462760065, 'classifier__colsample_bytree': 0.8383327154517631}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:07:31,059] Trial 19 finished with value: 0.9889699543460603 and parameters: {'classifier__n_estimators': 223, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.03217988945543679, 'classifier__subsample': 0.9893428687373984, 'classifier__colsample_bytree': 0.7282130389484783}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:07:43,714] Trial 20 finished with value: 0.9891540683467511 and parameters: {'classifier__n_estimators': 253, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.1158496498952307, 'classifier__subsample': 0.8461142971531366, 'classifier__colsample_bytree': 0.8189010104222241}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:07:54,913] Trial 21 finished with value: 0.9891723329520667 and parameters: {'classifier__n_estimators': 238, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.07413860503757783, 'classifier__subsample': 0.9843149354140229, 'classifier__colsample_bytree': 0.7440792342503498}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:08:08,301] Trial 22 finished with value: 0.9890215121236935 and parameters: {'classifier__n_estimators': 265, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.10120068626192824, 'classifier__subsample': 0.9086526132712857, 'classifier__colsample_bytree': 0.9369151322177399}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:08:19,971] Trial 23 finished with value: 0.9891340069556241 and parameters: {'classifier__n_estimators': 232, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.0543158663912385, 'classifier__subsample': 0.8800799328947276, 'classifier__colsample_bytree': 0.9664170921841151}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:08:32,446] Trial 24 finished with value: 0.9888899742162032 and parameters: {'classifier__n_estimators': 245, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.04034468303056137, 'classifier__subsample': 0.9202079855760704, 'classifier__colsample_bytree': 0.7295397459825814}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:08:45,214] Trial 25 finished with value: 0.9888073250781518 and parameters: {'classifier__n_estimators': 273, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.032374291423179276, 'classifier__subsample': 0.9529140202968732, 'classifier__colsample_bytree': 0.7552892506245754}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:08:58,146] Trial 26 finished with value: 0.9891818077623693 and parameters: {'classifier__n_estimators': 271, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.087606096998529, 'classifier__subsample': 0.9861826527770483, 'classifier__colsample_bytree': 0.7827511074618926}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:09:12,218] Trial 27 finished with value: 0.9889615542301622 and parameters: {'classifier__n_estimators': 284, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.1007408466806844, 'classifier__subsample': 0.900093961358576, 'classifier__colsample_bytree': 0.744759525548886}. Best is trial 11 with value: 0.9892398282550856.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:09:23,852] Trial 28 finished with value: 0.9892491406850308 and parameters: {'classifier__n_estimators': 230, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.07927649874783331, 'classifier__subsample': 0.9189551670409017, 'classifier__colsample_bytree': 0.8635520750631398}. Best is trial 28 with value: 0.9892491406850308.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
28,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,28,COMPLETE,11.633640,"{""classifier__colsample_bytree"": 0.8635520750631398, ""classifier__learning_rate"": 0.07927649874783331, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 230, ""classifier__subsample"": 0.9189551670409017}",2.230919,0.116692,0.090326,0.010923,0.989297,0.989476,0.989188,0.989159,0.989126,0.989249,0.000127,1
11,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,11,COMPLETE,13.367659,"{""classifier__colsample_bytree"": 0.716575355191113, ""classifier__learning_rate"": 0.06328141991837156, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 280, ""classifier__subsample"": 0.9641036110609162}",2.573428,0.133335,0.094716,0.003022,0.989164,0.989526,0.989271,0.989176,0.989063,0.989240,0.000158,2
13,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,13,COMPLETE,11.837620,"{""classifier__colsample_bytree"": 0.8011175380795007, ""classifier__learning_rate"": 0.1210981030393243, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 246, ""classifier__subsample"": 0.9284684265293066}",2.276720,0.091932,0.085445,0.005733,0.989211,0.989454,0.989220,0.989123,0.989010,0.989204,0.000146,3
4,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,4,COMPLETE,13.170302,"{""classifier__colsample_bytree"": 0.9629167456888115, ""classifier__learning_rate"": 0.06173698734681893, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 260, ""classifier__subsample"": 0.9076967847007942}",2.532902,0.132305,0.096628,0.009483,0.989183,0.989493,0.989155,0.989193,0.988948,0.989195,0.000174,4
15,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,15,COMPLETE,12.735781,"{""classifier__colsample_bytree"": 0.7991370230895036, ""classifier__learning_rate"": 0.06331081225921806, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 251, ""classifier__subsample"": 0.9232239634712497}",2.447788,0.111596,0.093896,0.009396,0.989166,0.989427,0.989256,0.989046,0.989046,0.989188,0.000143,5
26,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,26,COMPLETE,12.931132,"{""classifier__colsample_bytree"": 0.7827511074618926, ""classifier__learning_rate"": 0.087606096998529, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 271, ""classifier__subsample"": 0.9861826527770483}",2.485860,0.102370,0.094779,0.002128,0.989112,0.989541,0.989170,0.989125,0.988961,0.989182,0.000193,6
8,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,8,COMPLETE,13.945127,"{""classifier__colsample_bytree"": 0.7309678019732926, ""classifier__learning_rate"": 0.05722229168328298, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 298, ""classifier__subsample"": 0.9367837985354466}",2.690521,0.100561,0.093941,0.002113,0.989186,0.989542,0.989060,0.989062,0.989014,0.989173,0.000193,7
21,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,21,COMPLETE,11.198047,"{""classifier__colsample_bytree"": 0.7440792342503498, ""classifier__learning_rate"": 0.07413860503757783, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 238, ""classifier__subsample"": 0.9843149354140229}",2.153977,0.140729,0.080146,0.002142,0.989218,0.989576,0.989107,0.988931,0.989030,0.989172,0.000223,8
16,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,16,COMPLETE,12.285726,"{""classifier__colsample_bytree"": 0.7440052640765176, ""classifier__learning_rate"": 0.0990594409052359, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 291, ""classifier__subsample"": 0.996352158393604}",2.366291,0.126634,0.085326,0.001790,0.989133,0.989494,0.989092,0.988996,0.989064,0.989156,0.000175,9
20,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,20,COMPLETE,12.654394,"{""classifier__colsample_bytree"": 0.8189010104222241, ""classifier__learning_rate"": 0.1158496498952307, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 253, ""classifier__subsample"": 0.8461142971531366}",2.438039,0.245635,0.087448,0.003378,0.989262,0.989357,0.989136,0.989055,0.988960,0.989154,0.000142,10
12,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,12,COMPLETE,14.739691,"{""classifier__colsample_bytree"": 0.880987039892758, ""classifier__learning_rate"": 0.04843125896474501, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 295, ""classifier__subsample"": 0.8906347761980276}",2.844055,0.156934,0.098437,0.002996,0.989118,0.989496,0.989174,0.988964,0.989015,0.989153,0.000186,11
23,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,23,COMPLETE,11.669333,"{""classifier__colsample_bytree"": 0.9664170921841151, ""classifier__learning_rate"": 0.0543158663912385, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 232, ""classifier__subsample"": 0.8800799328947276}",2.242815,0.124451,0.085502,0.004793,0.989251,0.989462,0.989159,0.988866,0.988932,0.989134,0.000217,12
17,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,17,COMPLETE,11.890870,"{""classifier__colsample_bytree"": 0.7963123353901238, ""classifier__learning_rate"": 0.12991019494452638, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 254, ""classifier__subsample"": 0.9705410675720415}",2.287352,0.117324,0.085333,0.002811,0.989146,0.989226,0.989120,0.989154,0.988893,0.989108,0.000113,13
9,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,9,COMPLETE,10.305797,"{""classifier__colsample_bytree"": 0.7390085716354833, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 190, ""classifier__subsample"": 0.7863326015759046}",1.980232,0.119756,0.076426,0.002655,0.989054,0.989481,0.989176,0.988883,0.988934,0.989106,0.000213,14
18,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,18,COMPLETE,12.125428,"{""classifier__colsample_bytree"": 0.8383327154517631, ""classifier__learning_rate"": 0.07151034415104235, ""classifier__max_depth"": 6, ""classifier__n_estimators"": 277, ""classifier__subsample"": 0.9565576462760065}",2.336394,0.129710,0.083177,0.002607,0.989001,0.989446,0.989060,0.988916,0.988982,0.989081,0.000188,15
6,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,6,COMPLETE,6.205110,"{""classifier__colsample_bytree"": 0.907563134185142, ""classifier__learning_rate"": 0.27227689219802986, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 119, ""classifier__subsample"": 0.859949585491905}",1.182185,0.119400,0.054558,0.006166,0.988967,0.989396,0.988942,0.988982,0.988847,0.989027,0.000190,16
22,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,22,COMPLETE,13.387975,"{""classifier__colsample_bytree"": 0.9369151322177399, ""classifier__learning_rate"": 0.10120068626192824, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 265, ""classifier__subsample"": 0.9086526132712857}",2.577129,0.146559,0.095104,0.001610,0.989091,0.989171,0.989166,0.988937,0.988742,0.989022,0.000163,17
3,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,3,COMPLETE,11.004752,"{""classifier__colsample_bytree"": 0.7594304467254636, ""classifier__learning_rate"": 0.10859531344085706, ""classifier__max_depth"": 5, ""classifier__n_estimators"": 234, ""classifier__subsample"": 0.7421160815785701}",2.129533,0.185694,0.066947,0.003045,0.989052,0.989332,0.989028,0.988735,0.988948,0.989019,0.000192,18
29,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,29,COMPLETE,12.331228,"{""classifier__colsample_bytree"": 0.7169716667065978, ""classifier__learning_rate"": 0.04522160003175496, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 265, ""classifier__subsample"": 0.9761077551645695}",2.373706,0.126769,0.087060,0.001987,0.989086,0.989232,0.988944,0.988734,0.988947,0.988989,0.000166,19
19,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,19,COMPLETE,11.941573,"{""classifier__colsample_bytree"": 0.7282130389484783, ""classifier__learning_rate"": 0.03217988945543679, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 223, ""classifier__subsample"": 0.9893428687373984}",2.298108,0.282611,0.084755,0.004311,0.989004,0.989332,0.988912,0.988719,0.988883,0.988970,0.000203,20
27,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,27,COMPLETE,14.071655,"{""classifier__colsample_bytree"": 0.744759525548886, ""classifier__learning_rate"": 0.1007408466806844, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 284, ""classifier__subsample"": 0.900093961358576}",2.711545,0.133022,0.097294,0.002433,0.989105,0.989154,0.988866,0.988904,0.988778,0.988962,0.000144,21
24,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,24,COMPLETE,12.474377,"{""classifier__colsample_bytree"": 0.7295397459825814, ""classifier__learning_rate"": 0.04034468303056137, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 245, ""classifier__subsample"": 0.9202079855760704}",2.409383,0.137248,0.080065,0.001057,0.988937,0.989265,0.988796,0.988520,0.988931,0.988890,0.000241,22
7,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,7,COMPLETE,8.997556,"{""classifier__colsample_bytree"": 0.9250432944834902, ""classifier__learning_rate"": 0.20499672676341157, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 163, ""classifier__subsample"": 0.7054864832032575}",1.729783,0.114420,0.065313,0.001024,0.988888,0.989036,0.989076,0.988784,0.988573,0.988871,0.000182,23
14,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,14,COMPLETE,13.485798,"{""classifier__colsample_bytree"": 0.7249059588401392, ""classifier__learning_rate"": 0.1505296778163139, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 275, ""classifier__subsample"": 0.9506432005245602}",2.589868,0.122604,0.101783,0.011210,0.988937,0.989000,0.988942,0.988732,0.988621,0.988846,0.000145,24
25,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,25,COMPLETE,12.767041,"{""classifier__colsample_bytree"": 0.7552892506245754, ""classifier__learning_rate"": 0.032374291423179276, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 273, ""classifier__subsample"": 0.9529140202968732}",2.460907,0.113097,0.087083,0.005114,0.988788,0.989150,0.988763,0.988537,0.988799,0.988807,0.000196,25
2,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,2,COMPLETE,9.477746,"{""classifier__colsample_bytree"": 0.7082162779593778, ""classifier__learning_rate"": 0.0480367375659992, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 184, ""classifier__subsample"": 0.9634352309172836}",1.817167,0.130142,0.073912,0.011077,0.988756,0.989168,0.988714,0.988504,0.988816,0.988791,0.000215,26
10,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,10,COMPLETE,13.649633,"{""classifier__colsample_bytree"": 0.997055611642783, ""classifier__learning_rate"": 0.03355271522020396, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 288, ""classifier__subsample"": 0.9457462284934223}",2.634310,0.118751,0.090257,0.000597,0.988671,0.989099,0.988781,0.988536,0.988799,0.988777,0.000186,27
0,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,0,COMPLETE,10.532020,"{""classifier__colsample_bytree"": 0.7440267672451338, ""classifier__learning_rate"": 0.03000790177293386, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 183, ""classifier__subsample"": 0.7906997717895519}",2.016787,0.236480,0.085352,0.013037,0.988589,0.988937,0.988435,0.988124,0.988602,0.988537,0.000264,28
1,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,1,COMPLETE,5.991372,"{""classifier__colsample_bytree"": 0.8616450202010071, ""classifier__learning_rate"": 0.06647861789041172, ""classifier__max_depth"": 4, ""classifier__n_estimators"": 118, ""classifier__subsample"": 0.819030242269201}",1.142192,0.112878,0.051755,0.003537,0.985507,0.985530,0.985429,0.984714,0.985085,0.985253,0.000313,29
5,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,5,COMPLETE,11.360923,"{""classifier__colsample_bytree"": 0.9634427510288239, ""classifier__learning_rate"": 0.032822831099235304, ""classifier__max_depth"": 3, ""classifier__n_estimators"": 279, ""classifier__subsample"": 0.7509491258693707}",2.203173,0.137326,0.064640,0.002851,0.983605,0.984296,0.984230,0.983276,0.983325,0.983746,0.000437,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,1,2.104001,0.163528,0.971386,0.994745,0.982926,0.998678,0.992675,0.995668,0.989297,0.993089,0.993710
1,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,2,2.123200,0.158916,0.971842,0.994851,0.983212,0.998705,0.992794,0.995741,0.989476,0.993206,0.993823
2,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,3,2.204861,0.157021,0.970646,0.995170,0.982755,0.998785,0.992476,0.995620,0.989188,0.993015,0.993823
3,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,4,2.124734,0.161898,0.970156,0.995594,0.982711,0.998891,0.992343,0.995606,0.989159,0.992993,0.993969
4,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,5,2.102679,0.164348,0.970056,0.995594,0.982659,0.998891,0.992316,0.995593,0.989126,0.992972,0.993955

Modelo: linear_svm | origem do treinamento: cicids2017

[I 2026-10-12 04:09:51,158] A new study created in memory with name: linear_svm_cicids2017
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:10:01,603] Trial 0 finished with value: 0.7970917642574233 and parameters: {'classifier__C': 0.12164941464151847, 'classifier__class_weight': None}. Best is trial 0 with value: 0.7970917642574233.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:10:07,740] Trial 1 finished with value: 0.7968996257721814 and parameters: {'classifier__C': 0.0324835034508668, 'classifier__class_weight': None}. Best is trial 0 with value: 0.7970917642574233.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:10:12,750] Trial 2 finished with value: 0.8902366900120953 and parameters: {'classifier__C': 0.008536916958038761, 'classifier__class_weight': 'balanced'}. Best is trial 2 with value: 0.8902366900120953.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:10:26,382] Trial 3 finished with value: 0.8914576368785354 and parameters: {'classifier__C': 0.4944059287398678, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.8914576368785354.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:10:31,395] Trial 4 finished with value: 0.7969049066762882 and parameters: {'classifier__C': 0.01052594868979971, 'classifier__class_weight': None}. Best is trial 3 with value: 0.8914576368785354.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:10:51,587] Trial 5 finished with value: 0.8932202320698168 and parameters: {'classifier__C': 2.25080333975975, 'classifier__class_weight': 'balanced'}. Best is trial 5 with value: 0.8932202320698168.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:10:56,229] Trial 6 finished with value: 0.8900972126579433 and parameters: {'classifier__C': 0.005034249005866117, 'classifier__class_weight': 'balanced'}. Best is trial 5 with value: 0.8932202320698168.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:11:19,594] Trial 7 finished with value: 0.9039079839184578 and parameters: {'classifier__C': 69.3917561414594, 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.9039079839184578.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:11:38,941] Trial 8 finished with value: 0.8024819994017826 and parameters: {'classifier__C': 24.096044772653222, 'classifier__class_weight': None}. Best is trial 7 with value: 0.9039079839184578.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:11:43,128] Trial 9 finished with value: 0.8898583270792029 and parameters: {'classifier__C': 0.0015677395556368667, 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.9039079839184578.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:12:04,082] Trial 10 finished with value: 0.902396749643278 and parameters: {'classifier__C': 38.40450841639351, 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.9039079839184578.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:12:30,123] Trial 11 finished with value: 0.9041627438295127 and parameters: {'classifier__C': 86.5093058278553, 'classifier__class_weight': 'balanced'}. Best is trial 11 with value: 0.9041627438295127.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:12:52,932] Trial 12 finished with value: 0.9044064204639761 and parameters: {'classifier__C': 82.94461752105981, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:13:11,104] Trial 13 finished with value: 0.8945483229545033 and parameters: {'classifier__C': 5.989707983993218, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:13:33,196] Trial 14 finished with value: 0.8948347814027526 and parameters: {'classifier__C': 9.08542191189212, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:13:52,574] Trial 15 finished with value: 0.7999920294655121 and parameters: {'classifier__C': 6.192208110388674, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:14:15,402] Trial 16 finished with value: 0.9037909085559246 and parameters: {'classifier__C': 78.9038175930485, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:14:29,667] Trial 17 finished with value: 0.7980281431227805 and parameters: {'classifier__C': 1.5669579715678401, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:14:50,337] Trial 18 finished with value: 0.8989864683200371 and parameters: {'classifier__C': 15.620311628199916, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:15:08,774] Trial 19 finished with value: 0.8922157382773157 and parameters: {'classifier__C': 1.1158061548390923, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:15:19,598] Trial 20 finished with value: 0.8904325205172071 and parameters: {'classifier__C': 0.06516496425754421, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:15:44,882] Trial 21 finished with value: 0.9042057247206827 and parameters: {'classifier__C': 95.94783900983505, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:16:08,876] Trial 22 finished with value: 0.8526881300014267 and parameters: {'classifier__C': 78.84696969254713, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:16:30,966] Trial 23 finished with value: 0.9015018507706642 and parameters: {'classifier__C': 26.80787261688018, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:16:50,684] Trial 24 finished with value: 0.9036060551554599 and parameters: {'classifier__C': 68.80939396391068, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:17:10,013] Trial 25 finished with value: 0.8945913585610976 and parameters: {'classifier__C': 5.244142974305016, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:17:32,562] Trial 26 finished with value: 0.8995958899199581 and parameters: {'classifier__C': 21.45618942985188, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:17:56,281] Trial 27 finished with value: 0.9041678613391095 and parameters: {'classifier__C': 94.85356521349148, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:18:17,206] Trial 28 finished with value: 0.9020707445946605 and parameters: {'classifier__C': 34.72116075021814, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9044064204639761.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:18:21,204] Trial 29 finished with value: 0.7963478929722974 and parameters: {'classifier__C': 0.001599085778185112, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9044064204639761.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
12,linear_svm,optuna,cicids2017,235490,30,5,1,12,COMPLETE,22.808344,"{""classifier__C"": 82.94461752105981, ""classifier__class_weight"": ""balanced""}",4.544699,1.376817,0.014729,0.000490,0.904600,0.907028,0.905632,0.901331,0.903440,0.904406,0.001939,1
21,linear_svm,optuna,cicids2017,235490,30,5,1,21,COMPLETE,25.283626,"{""classifier__C"": 95.94783900983505, ""classifier__class_weight"": ""balanced""}",5.040098,0.987389,0.014545,0.000394,0.905726,0.907267,0.906110,0.901244,0.900682,0.904206,0.002702,2
27,linear_svm,optuna,cicids2017,235490,30,5,1,27,COMPLETE,23.717587,"{""classifier__C"": 94.85356521349148, ""classifier__class_weight"": ""balanced""}",4.726833,1.353150,0.014580,0.000331,0.904778,0.907240,0.905634,0.901244,0.901944,0.904168,0.002256,3
11,linear_svm,optuna,cicids2017,235490,30,5,1,11,COMPLETE,26.039772,"{""classifier__C"": 86.5093058278553, ""classifier__class_weight"": ""balanced""}",5.190759,1.054596,0.015069,0.001272,0.904052,0.907397,0.905061,0.901960,0.902343,0.904163,0.001972,4
7,linear_svm,optuna,cicids2017,235490,30,5,1,7,COMPLETE,23.365032,"{""classifier__C"": 69.3917561414594, ""classifier__class_weight"": ""balanced""}",4.655476,1.282800,0.015579,0.002410,0.903260,0.906907,0.905611,0.901770,0.901991,0.903908,0.002028,5
16,linear_svm,optuna,cicids2017,235490,30,5,1,16,COMPLETE,22.827426,"{""classifier__C"": 78.9038175930485, ""classifier__class_weight"": ""balanced""}",4.549051,0.862025,0.014344,0.000154,0.903617,0.906513,0.905272,0.901338,0.902214,0.903791,0.001905,6
24,linear_svm,optuna,cicids2017,235490,30,5,1,24,COMPLETE,19.717307,"{""classifier__C"": 68.80939396391068, ""classifier__class_weight"": ""balanced""}",3.926682,0.900553,0.014658,0.000384,0.903565,0.906540,0.905197,0.901575,0.901154,0.903606,0.002063,7
10,linear_svm,optuna,cicids2017,235490,30,5,1,10,COMPLETE,20.954372,"{""classifier__C"": 38.40450841639351, ""classifier__class_weight"": ""balanced""}",4.174183,0.750750,0.014576,0.000092,0.902382,0.905914,0.902039,0.900899,0.900749,0.902397,0.001869,8
28,linear_svm,optuna,cicids2017,235490,30,5,1,28,COMPLETE,20.925103,"{""classifier__C"": 34.72116075021814, ""classifier__class_weight"": ""balanced""}",4.168371,0.959521,0.014545,0.000349,0.902274,0.905229,0.902629,0.900758,0.899464,0.902071,0.001941,9
23,linear_svm,optuna,cicids2017,235490,30,5,1,23,COMPLETE,22.089689,"{""classifier__C"": 26.80787261688018, ""classifier__class_weight"": ""balanced""}",4.401340,0.884324,0.014561,0.000276,0.901377,0.904843,0.901667,0.900482,0.899141,0.901502,0.001888,10
26,linear_svm,optuna,cicids2017,235490,30,5,1,26,COMPLETE,22.548767,"{""classifier__C"": 21.45618942985188, ""classifier__class_weight"": ""balanced""}",4.492843,0.812700,0.014788,0.000104,0.901269,0.903112,0.901060,0.899431,0.893107,0.899596,0.003448,11
18,linear_svm,optuna,cicids2017,235490,30,5,1,18,COMPLETE,20.670077,"{""classifier__C"": 15.620311628199916, ""classifier__class_weight"": ""balanced""}",4.117413,1.165680,0.014543,0.000301,0.900092,0.902215,0.896429,0.898504,0.897692,0.898986,0.002005,12
14,linear_svm,optuna,cicids2017,235490,30,5,1,14,COMPLETE,22.091633,"{""classifier__C"": 9.08542191189212, ""classifier__class_weight"": ""balanced""}",4.401651,1.473925,0.014577,0.000238,0.894717,0.897657,0.896423,0.893176,0.892202,0.894835,0.002009,13
25,linear_svm,optuna,cicids2017,235490,30,5,1,25,COMPLETE,19.328509,"{""classifier__C"": 5.244142974305016, ""classifier__class_weight"": ""balanced""}",3.849144,0.709830,0.014482,0.000237,0.894190,0.897457,0.895892,0.892842,0.892576,0.894591,0.001854,14
13,linear_svm,optuna,cicids2017,235490,30,5,1,13,COMPLETE,18.171932,"{""classifier__C"": 5.989707983993218, ""classifier__class_weight"": ""balanced""}",3.617842,0.660994,0.014450,0.000348,0.894374,0.897510,0.896098,0.892630,0.892130,0.894548,0.002036,15
5,linear_svm,optuna,cicids2017,235490,30,5,1,5,COMPLETE,20.191155,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced""}",4.021896,1.126052,0.014523,0.000145,0.893159,0.895866,0.893897,0.892303,0.890876,0.893220,0.001661,16
19,linear_svm,optuna,cicids2017,235490,30,5,1,19,COMPLETE,18.436114,"{""classifier__C"": 1.1158061548390923, ""classifier__class_weight"": ""balanced""}",3.670771,1.271224,0.014337,0.000185,0.892679,0.894733,0.892966,0.891108,0.889592,0.892216,0.001745,17
3,linear_svm,optuna,cicids2017,235490,30,5,1,3,COMPLETE,13.631340,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": ""balanced""}",2.710127,0.864671,0.014307,0.000111,0.892128,0.893840,0.891912,0.890520,0.888888,0.891458,0.001662,18
20,linear_svm,optuna,cicids2017,235490,30,5,1,20,COMPLETE,10.823566,"{""classifier__C"": 0.06516496425754421, ""classifier__class_weight"": ""balanced""}",2.148211,0.509826,0.014430,0.000182,0.890778,0.892157,0.891289,0.890051,0.887888,0.890433,0.001446,19
2,linear_svm,optuna,cicids2017,235490,30,5,1,2,COMPLETE,5.009681,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced""}",0.985617,0.078449,0.014493,0.000387,0.890867,0.891852,0.890985,0.889887,0.887591,0.890237,0.001462,20
6,linear_svm,optuna,cicids2017,235490,30,5,1,6,COMPLETE,4.641260,"{""classifier__C"": 0.005034249005866117, ""classifier__class_weight"": ""balanced""}",0.911814,0.110164,0.014638,0.000320,0.890583,0.891806,0.890973,0.889637,0.887486,0.890097,0.001480,21
9,linear_svm,optuna,cicids2017,235490,30,5,1,9,COMPLETE,4.185842,"{""classifier__C"": 0.0015677395556368667, ""classifier__class_weight"": ""balanced""}",0.820282,0.023950,0.015044,0.000604,0.889673,0.891888,0.890582,0.889838,0.887310,0.889858,0.001495,22
22,linear_svm,optuna,cicids2017,235490,30,5,1,22,COMPLETE,23.993598,"{""classifier__C"": 78.84696969254713, ""classifier__class_weight"": null}",4.782106,1.262419,0.014548,0.000404,0.790365,0.928846,0.878376,0.790378,0.875475,0.852688,0.054306,23
8,linear_svm,optuna,cicids2017,235490,30,5,1,8,COMPLETE,19.346029,"{""classifier__C"": 24.096044772653222, ""classifier__class_weight"": null}",3.852616,0.703391,0.014613,0.000293,0.802294,0.802896,0.804716,0.801723,0.800780,0.802482,0.001317,24
15,linear_svm,optuna,cicids2017,235490,30,5,1,15,COMPLETE,19.377767,"{""classifier__C"": 6.192208110388674, ""classifier__class_weight"": null}",3.858923,1.459735,0.014559,0.000187,0.799673,0.801761,0.801430,0.799125,0.797971,0.799992,0.001424,25
17,linear_svm,optuna,cicids2017,235490,30,5,1,17,COMPLETE,14.263892,"{""classifier__C"": 1.5669579715678401, ""classifier__class_weight"": null}",2.836345,0.477296,0.014393,0.000132,0.797396,0.799750,0.799604,0.797740,0.795651,0.798028,0.001522,26
0,linear_svm,optuna,cicids2017,235490,30,5,1,0,COMPLETE,10.442971,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null}",2.070856,0.883098,0.015904,0.002849,0.796596,0.798905,0.798508,0.796883,0.794568,0.797092,0.001546,27
4,linear_svm,optuna,cicids2017,235490,30,5,1,4,COMPLETE,5.013258,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null}",0.986094,0.048275,0.014760,0.000170,0.796388,0.798570,0.798402,0.796722,0.794443,0.796905,0.001508,28
1,linear_svm,optuna,cicids2017,235490,30,5,1,1,COMPLETE,6.136454,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": null}",1.210940,0.053795,0.014557,0.000349,0.796492,0.798626,0.798110,0.796903,0.794367,0.796900,0.001485,29
29,linear_svm,optuna,cicids2017,235490,30,5,1,29,COMPLETE,3.996747,"{""classifier__C"": 0.001599085778185112, ""classifier__class_weight"": null}",0.782770,0.021586,0.014479,0.000390,0.795456,0.798027,0.798099,0.796305,0.793851,0.796348,0.001607,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,linear_svm,optuna,cicids2017,235490,30,5,1,1,9.568226,0.042671,0.762523,0.966451,0.852461,0.991013,0.924759,0.956740,0.904600,0.933097,0.945605
1,linear_svm,optuna,cicids2017,235490,30,5,1,2,5.126449,0.051809,0.767669,0.967512,0.856083,0.991313,0.926803,0.957973,0.907028,0.934944,0.947158
2,linear_svm,optuna,cicids2017,235490,30,5,1,3,7.151357,0.049069,0.765796,0.964968,0.853922,0.990632,0.926217,0.957342,0.905632,0.933967,0.945593
3,linear_svm,optuna,cicids2017,235490,30,5,1,4,7.994989,0.045494,0.758300,0.960191,0.847386,0.989338,0.923483,0.955277,0.901331,0.930825,0.941837
4,linear_svm,optuna,cicids2017,235490,30,5,1,5,6.244826,0.049039,0.761561,0.963270,0.850621,0.990166,0.924598,0.956259,0.903440,0.932333,0.943934

Modelo: linear_svm | origem do treinamento: unsw_nb15

[I 2026-10-12 04:18:44,880] A new study created in memory with name: linear_svm_unsw_nb15
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:19:03,297] Trial 0 finished with value: 0.9200456861054492 and parameters: {'classifier__C': 0.12164941464151847, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9200456861054492.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:19:11,621] Trial 1 finished with value: 0.9099650706976726 and parameters: {'classifier__C': 0.0324835034508668, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9200456861054492.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:19:18,303] Trial 2 finished with value: 0.8935612203286445 and parameters: {'classifier__C': 0.008536916958038761, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9200456861054492.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:19:35,129] Trial 3 finished with value: 0.9139606307391693 and parameters: {'classifier__C': 0.4944059287398678, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9200456861054492.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:19:41,811] Trial 4 finished with value: 0.887005861811373 and parameters: {'classifier__C': 0.01052594868979971, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9200456861054492.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:19:56,062] Trial 5 finished with value: 0.9170105156485853 and parameters: {'classifier__C': 2.25080333975975, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9200456861054492.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:20:02,544] Trial 6 finished with value: 0.8924780718090124 and parameters: {'classifier__C': 0.005034249005866117, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9200456861054492.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:20:15,690] Trial 7 finished with value: 0.9220106278127306 and parameters: {'classifier__C': 69.3917561414594, 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.9220106278127306.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:20:32,485] Trial 8 finished with value: 0.9275212183468667 and parameters: {'classifier__C': 24.096044772653222, 'classifier__class_weight': None}. Best is trial 8 with value: 0.9275212183468667.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:20:37,001] Trial 9 finished with value: 0.8316607793492802 and parameters: {'classifier__C': 0.0015677395556368667, 'classifier__class_weight': 'balanced'}. Best is trial 8 with value: 0.9275212183468667.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:21:03,795] Trial 10 finished with value: 0.9275439581918459 and parameters: {'classifier__C': 50.46246112561027, 'classifier__class_weight': None}. Best is trial 10 with value: 0.9275439581918459.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:21:30,334] Trial 11 finished with value: 0.9275136540702661 and parameters: {'classifier__C': 48.29670773314647, 'classifier__class_weight': None}. Best is trial 10 with value: 0.9275439581918459.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:21:46,636] Trial 12 finished with value: 0.9274683544935728 and parameters: {'classifier__C': 10.148737057476696, 'classifier__class_weight': None}. Best is trial 10 with value: 0.9275439581918459.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:22:01,906] Trial 13 finished with value: 0.9269705904906071 and parameters: {'classifier__C': 1.6207550343863824, 'classifier__class_weight': None}. Best is trial 10 with value: 0.9275439581918459.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:22:16,514] Trial 14 finished with value: 0.9275515394691961 and parameters: {'classifier__C': 88.78015547689247, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:22:35,336] Trial 15 finished with value: 0.9274004302523281 and parameters: {'classifier__C': 6.155406925808113, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:22:53,528] Trial 16 finished with value: 0.9275439581918459 and parameters: {'classifier__C': 75.9200749709584, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:23:09,226] Trial 17 finished with value: 0.9267889764610459 and parameters: {'classifier__C': 1.1982235198424767, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:23:22,366] Trial 18 finished with value: 0.9220106278127306 and parameters: {'classifier__C': 17.260806779881086, 'classifier__class_weight': 'balanced'}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:23:38,934] Trial 19 finished with value: 0.9273549730819797 and parameters: {'classifier__C': 4.839689477666346, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:23:55,134] Trial 20 finished with value: 0.9275439581918459 and parameters: {'classifier__C': 93.68144606294365, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:24:10,216] Trial 21 finished with value: 0.9275288107579124 and parameters: {'classifier__C': 27.80473222664567, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:24:25,805] Trial 22 finished with value: 0.92753625593494 and parameters: {'classifier__C': 88.18081209805024, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:24:41,660] Trial 23 finished with value: 0.927506145888611 and parameters: {'classifier__C': 16.905554732198585, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:24:58,007] Trial 24 finished with value: 0.9275363848132585 and parameters: {'classifier__C': 42.633931910874466, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:25:11,991] Trial 25 finished with value: 0.9220061172521902 and parameters: {'classifier__C': 8.222303503164403, 'classifier__class_weight': 'balanced'}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:25:28,802] Trial 26 finished with value: 0.9272893444857422 and parameters: {'classifier__C': 3.369467841991787, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:25:43,419] Trial 27 finished with value: 0.9274986290508913 and parameters: {'classifier__C': 15.381661733545434, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:25:59,074] Trial 28 finished with value: 0.9275363657808005 and parameters: {'classifier__C': 92.72080740375651, 'classifier__class_weight': None}. Best is trial 14 with value: 0.9275515394691961.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:26:11,535] Trial 29 finished with value: 0.922022456479685 and parameters: {'classifier__C': 33.265899652104075, 'classifier__class_weight': 'balanced'}. Best is trial 14 with value: 0.9275515394691961.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
14,linear_svm,optuna,unsw_nb15,235490,30,5,1,14,COMPLETE,14.607532,"{""classifier__C"": 88.78015547689247, ""classifier__class_weight"": null}",2.904812,0.554105,0.014631,0.000185,0.926460,0.927009,0.929670,0.929283,0.925336,0.927552,0.001666,1
10,linear_svm,optuna,unsw_nb15,235490,30,5,1,10,COMPLETE,26.792882,"{""classifier__C"": 50.46246112561027, ""classifier__class_weight"": null}",5.341878,4.069247,0.014632,0.000330,0.926422,0.927009,0.929670,0.929283,0.925336,0.927544,0.001671,2
20,linear_svm,optuna,unsw_nb15,235490,30,5,1,20,COMPLETE,16.200342,"{""classifier__C"": 93.68144606294365, ""classifier__class_weight"": null}",3.223157,0.876574,0.014786,0.000238,0.926422,0.927009,0.929670,0.929283,0.925336,0.927544,0.001671,2
16,linear_svm,optuna,unsw_nb15,235490,30,5,1,16,COMPLETE,18.191253,"{""classifier__C"": 75.9200749709584, ""classifier__class_weight"": null}",3.621529,1.820309,0.014629,0.000193,0.926422,0.927009,0.929670,0.929283,0.925336,0.927544,0.001671,2
24,linear_svm,optuna,unsw_nb15,235490,30,5,1,24,COMPLETE,16.347028,"{""classifier__C"": 42.633931910874466, ""classifier__class_weight"": null}",3.252265,0.834776,0.014970,0.000682,0.926422,0.926971,0.929670,0.929283,0.925336,0.927536,0.001674,5
28,linear_svm,optuna,unsw_nb15,235490,30,5,1,28,COMPLETE,15.654870,"{""classifier__C"": 92.72080740375651, ""classifier__class_weight"": null}",3.114307,0.770456,0.014551,0.000215,0.926422,0.927009,0.929670,0.929283,0.925298,0.927536,0.001681,6
22,linear_svm,optuna,unsw_nb15,235490,30,5,1,22,COMPLETE,15.587708,"{""classifier__C"": 88.18081209805024, ""classifier__class_weight"": null}",3.100769,0.715105,0.014698,0.000336,0.926384,0.926933,0.929708,0.929321,0.925336,0.927536,0.001699,7
21,linear_svm,optuna,unsw_nb15,235490,30,5,1,21,COMPLETE,15.081349,"{""classifier__C"": 27.80473222664567, ""classifier__class_weight"": null}",2.999610,0.557790,0.014591,0.000097,0.926422,0.926933,0.929670,0.929283,0.925336,0.927529,0.001677,8
8,linear_svm,optuna,unsw_nb15,235490,30,5,1,8,COMPLETE,16.794418,"{""classifier__C"": 24.096044772653222, ""classifier__class_weight"": null}",3.342519,1.283697,0.014541,0.000133,0.926422,0.926933,0.929670,0.929283,0.925298,0.927521,0.001687,9
11,linear_svm,optuna,unsw_nb15,235490,30,5,1,11,COMPLETE,26.538741,"{""classifier__C"": 48.29670773314647, ""classifier__class_weight"": null}",5.291009,4.506744,0.014674,0.000227,0.926384,0.926895,0.929670,0.929283,0.925336,0.927514,0.001684,10
23,linear_svm,optuna,unsw_nb15,235490,30,5,1,23,COMPLETE,15.854339,"{""classifier__C"": 16.905554732198585, ""classifier__class_weight"": null}",3.154139,0.705029,0.014578,0.000298,0.926422,0.926895,0.929595,0.929321,0.925298,0.927506,0.001678,11
27,linear_svm,optuna,unsw_nb15,235490,30,5,1,27,COMPLETE,14.616538,"{""classifier__C"": 15.381661733545434, ""classifier__class_weight"": null}",2.906763,0.445523,0.014471,0.000208,0.926384,0.926933,0.929557,0.929321,0.925298,0.927499,0.001671,12
12,linear_svm,optuna,unsw_nb15,235490,30,5,1,12,COMPLETE,16.301124,"{""classifier__C"": 10.148737057476696, ""classifier__class_weight"": null}",3.243454,0.955652,0.014730,0.000096,0.926422,0.926857,0.929557,0.929283,0.925222,0.927468,0.001684,13
15,linear_svm,optuna,unsw_nb15,235490,30,5,1,15,COMPLETE,18.822017,"{""classifier__C"": 6.155406925808113, ""classifier__class_weight"": null}",3.747688,1.302827,0.014633,0.000208,0.926384,0.926782,0.929520,0.929133,0.925184,0.927400,0.001663,14
19,linear_svm,optuna,unsw_nb15,235490,30,5,1,19,COMPLETE,16.566821,"{""classifier__C"": 4.839689477666346, ""classifier__class_weight"": null}",3.296462,0.707149,0.014774,0.000346,0.926308,0.926744,0.929520,0.929095,0.925108,0.927355,0.001687,15
26,linear_svm,optuna,unsw_nb15,235490,30,5,1,26,COMPLETE,16.810372,"{""classifier__C"": 3.369467841991787, ""classifier__class_weight"": null}",3.345424,0.798189,0.014580,0.000057,0.926080,0.926592,0.929445,0.929222,0.925108,0.927289,0.001737,16
13,linear_svm,optuna,unsw_nb15,235490,30,5,1,13,COMPLETE,15.269571,"{""classifier__C"": 1.6207550343863824, ""classifier__class_weight"": null}",3.037425,0.806754,0.014440,0.000341,0.925663,0.926403,0.928881,0.929103,0.924804,0.926971,0.001728,17
17,linear_svm,optuna,unsw_nb15,235490,30,5,1,17,COMPLETE,15.697437,"{""classifier__C"": 1.1982235198424767, ""classifier__class_weight"": null}",3.122993,0.764385,0.014440,0.000314,0.925397,0.926137,0.928655,0.928990,0.924766,0.926789,0.001719,18
29,linear_svm,optuna,unsw_nb15,235490,30,5,1,29,COMPLETE,12.460727,"{""classifier__C"": 33.265899652104075, ""classifier__class_weight"": ""balanced""}",2.475209,0.608474,0.014783,0.000238,0.912151,0.911215,0.938405,0.937086,0.911255,0.922022,0.012849,19
7,linear_svm,optuna,unsw_nb15,235490,30,5,1,7,COMPLETE,13.146310,"{""classifier__C"": 69.3917561414594, ""classifier__class_weight"": ""balanced""}",2.612839,0.627382,0.014609,0.000419,0.912151,0.911156,0.938405,0.937086,0.911255,0.922011,0.012859,20
18,linear_svm,optuna,unsw_nb15,235490,30,5,1,18,COMPLETE,13.139785,"{""classifier__C"": 17.260806779881086, ""classifier__class_weight"": ""balanced""}",2.610898,0.590014,0.014978,0.000407,0.912151,0.911156,0.938405,0.937086,0.911255,0.922011,0.012859,20
25,linear_svm,optuna,unsw_nb15,235490,30,5,1,25,COMPLETE,13.983177,"{""classifier__C"": 8.222303503164403, ""classifier__class_weight"": ""balanced""}",2.779606,0.778303,0.014908,0.000298,0.912187,0.911097,0.938405,0.937086,0.911255,0.922006,0.012863,22
0,linear_svm,optuna,unsw_nb15,235490,30,5,1,0,COMPLETE,18.415351,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null}",3.666412,1.731818,0.014826,0.000135,0.919150,0.919861,0.920584,0.922859,0.917774,0.920046,0.001685,23
5,linear_svm,optuna,unsw_nb15,235490,30,5,1,5,COMPLETE,14.250803,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced""}",2.833533,0.666856,0.014790,0.000427,0.912069,0.911038,0.913723,0.937086,0.911136,0.917011,0.010084,24
3,linear_svm,optuna,unsw_nb15,235490,30,5,1,3,COMPLETE,16.825269,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": ""balanced""}",3.348375,1.744273,0.014868,0.000176,0.909835,0.910611,0.912204,0.936981,0.900172,0.913961,0.012259,25
1,linear_svm,optuna,unsw_nb15,235490,30,5,1,1,COMPLETE,8.323405,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": null}",1.648303,0.100722,0.014575,0.000194,0.908647,0.910406,0.910079,0.913309,0.907386,0.909965,0.001989,26
2,linear_svm,optuna,unsw_nb15,235490,30,5,1,2,COMPLETE,6.681947,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced""}",1.319906,0.207457,0.014662,0.000324,0.893876,0.893845,0.893706,0.893799,0.892580,0.893561,0.000494,27
6,linear_svm,optuna,unsw_nb15,235490,30,5,1,6,COMPLETE,6.480640,"{""classifier__C"": 0.005034249005866117, ""classifier__class_weight"": ""balanced""}",1.279597,0.168844,0.014713,0.000229,0.892716,0.892811,0.892545,0.892597,0.891722,0.892478,0.000389,28
4,linear_svm,optuna,unsw_nb15,235490,30,5,1,4,COMPLETE,6.681786,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null}",1.319980,0.033199,0.014567,0.000098,0.885882,0.887966,0.885783,0.890681,0.884717,0.887006,0.002118,29
9,linear_svm,optuna,unsw_nb15,235490,30,5,1,9,COMPLETE,4.515661,"{""classifier__C"": 0.0015677395556368667, ""classifier__class_weight"": ""balanced""}",0.886518,0.069866,0.014758,0.000615,0.825872,0.844468,0.825462,0.841388,0.821115,0.831661,0.009400,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,linear_svm,optuna,unsw_nb15,235490,30,5,1,1,2.842476,0.058883,0.938604,0.829387,0.880622,0.958556,0.986438,0.972297,0.926460,0.955030,0.907913
1,linear_svm,optuna,unsw_nb15,235490,30,5,1,2,4.306510,0.055186,0.939030,0.830661,0.881528,0.958856,0.986518,0.972490,0.927009,0.955348,0.908590
2,linear_svm,optuna,unsw_nb15,235490,30,5,1,3,4.572229,0.046106,0.936709,0.840552,0.886029,0.961133,0.985801,0.973311,0.929670,0.956750,0.913176
3,linear_svm,optuna,unsw_nb15,235490,30,5,1,4,5.074414,0.042942,0.937470,0.838747,0.885365,0.960719,0.986013,0.973202,0.929283,0.956559,0.912380
4,linear_svm,optuna,unsw_nb15,235490,30,5,1,5,3.160048,0.048904,0.937004,0.827389,0.878791,0.958071,0.986093,0.971880,0.925336,0.954351,0.906741

Modelo: linear_svm | origem do treinamento: iot23

[I 2026-10-12 04:26:26,514] A new study created in memory with name: linear_svm_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:26:34,046] Trial 0 finished with value: 0.9956467632946164 and parameters: {'classifier__C': 0.12164941464151847, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9956467632946164.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:26:40,015] Trial 1 finished with value: 0.995528039383399 and parameters: {'classifier__C': 0.0324835034508668, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9956467632946164.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:26:45,024] Trial 2 finished with value: 0.9940334650765028 and parameters: {'classifier__C': 0.008536916958038761, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9956467632946164.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:26:55,717] Trial 3 finished with value: 0.9944611099707468 and parameters: {'classifier__C': 0.4944059287398678, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9956467632946164.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:27:00,664] Trial 4 finished with value: 0.9953104485742443 and parameters: {'classifier__C': 0.01052594868979971, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9956467632946164.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:27:12,361] Trial 5 finished with value: 0.9944807632053626 and parameters: {'classifier__C': 2.25080333975975, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9956467632946164.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:27:17,014] Trial 6 finished with value: 0.9941453536371215 and parameters: {'classifier__C': 0.005034249005866117, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9956467632946164.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:27:30,200] Trial 7 finished with value: 0.9945071509837105 and parameters: {'classifier__C': 69.3917561414594, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9956467632946164.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:27:39,362] Trial 8 finished with value: 0.9957460052197431 and parameters: {'classifier__C': 24.096044772653222, 'classifier__class_weight': None}. Best is trial 8 with value: 0.9957460052197431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:27:43,341] Trial 9 finished with value: 0.993783971001063 and parameters: {'classifier__C': 0.0015677395556368667, 'classifier__class_weight': 'balanced'}. Best is trial 8 with value: 0.9957460052197431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:27:51,908] Trial 10 finished with value: 0.9957460030394358 and parameters: {'classifier__C': 50.46246112561027, 'classifier__class_weight': None}. Best is trial 8 with value: 0.9957460052197431.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:28:00,749] Trial 11 finished with value: 0.9957592302441893 and parameters: {'classifier__C': 48.29670773314647, 'classifier__class_weight': None}. Best is trial 11 with value: 0.9957592302441893.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:28:09,097] Trial 12 finished with value: 0.9957592324243215 and parameters: {'classifier__C': 9.950384075581109, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9957592324243215.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:28:19,628] Trial 13 finished with value: 0.9957393907908993 and parameters: {'classifier__C': 2.489265072954432, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9957592324243215.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:28:28,227] Trial 14 finished with value: 0.9957393907908993 and parameters: {'classifier__C': 6.483958415124679, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9957592324243215.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:28:37,381] Trial 15 finished with value: 0.9957393907908993 and parameters: {'classifier__C': 9.956547936614156, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9957592324243215.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:28:45,213] Trial 16 finished with value: 0.9956799064246106 and parameters: {'classifier__C': 0.6039256971924426, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9957592324243215.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:28:57,593] Trial 17 finished with value: 0.9944808632833853 and parameters: {'classifier__C': 21.825328025495757, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9957592324243215.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:29:06,233] Trial 18 finished with value: 0.9957658516698285 and parameters: {'classifier__C': 65.72187409908494, 'classifier__class_weight': None}. Best is trial 18 with value: 0.9957658516698285.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:29:13,994] Trial 19 finished with value: 0.9957658516698285 and parameters: {'classifier__C': 1.013842090310565, 'classifier__class_weight': None}. Best is trial 18 with value: 0.9957658516698285.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:29:22,885] Trial 20 finished with value: 0.994072453805307 and parameters: {'classifier__C': 0.06516496425754421, 'classifier__class_weight': 'balanced'}. Best is trial 18 with value: 0.9957658516698285.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:29:30,902] Trial 21 finished with value: 0.9956667344224857 and parameters: {'classifier__C': 0.7257591827442454, 'classifier__class_weight': None}. Best is trial 18 with value: 0.9957658516698285.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:29:39,329] Trial 22 finished with value: 0.9957592270978755 and parameters: {'classifier__C': 2.8431496924581094, 'classifier__class_weight': None}. Best is trial 18 with value: 0.9957658516698285.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:29:47,492] Trial 23 finished with value: 0.9957526158153456 and parameters: {'classifier__C': 8.453981055410763, 'classifier__class_weight': None}. Best is trial 18 with value: 0.9957658516698285.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:29:56,521] Trial 24 finished with value: 0.9957658452002314 and parameters: {'classifier__C': 20.182489738515677, 'classifier__class_weight': None}. Best is trial 18 with value: 0.9957658516698285.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:30:06,372] Trial 25 finished with value: 0.9957658452002314 and parameters: {'classifier__C': 90.77581717329434, 'classifier__class_weight': None}. Best is trial 18 with value: 0.9957658516698285.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:30:14,242] Trial 26 finished with value: 0.9957592356591164 and parameters: {'classifier__C': 1.2511899477973074, 'classifier__class_weight': None}. Best is trial 18 with value: 0.9957658516698285.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:30:21,448] Trial 27 finished with value: 0.9957393769325409 and parameters: {'classifier__C': 0.16892419661801938, 'classifier__class_weight': None}. Best is trial 18 with value: 0.9957658516698285.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:30:25,295] Trial 28 finished with value: 0.9939676040760329 and parameters: {'classifier__C': 0.0015701491614882478, 'classifier__class_weight': None}. Best is trial 18 with value: 0.9957658516698285.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:30:32,305] Trial 29 finished with value: 0.9957327657472694 and parameters: {'classifier__C': 0.15972846913490713, 'classifier__class_weight': None}. Best is trial 18 with value: 0.9957658516698285.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
18,linear_svm,optuna,iot23,235490,30,5,1,18,COMPLETE,8.639523,"{""classifier__C"": 65.72187409908494, ""classifier__class_weight"": null}",1.711302,0.604326,0.014481,0.000345,0.995981,0.995312,0.995245,0.996178,0.996113,0.995766,0.000403,1
19,linear_svm,optuna,iot23,235490,30,5,1,19,COMPLETE,7.759626,"{""classifier__C"": 1.013842090310565, ""classifier__class_weight"": null}",1.535487,0.279545,0.014327,0.000268,0.995981,0.995312,0.995245,0.996178,0.996113,0.995766,0.000403,1
24,linear_svm,optuna,iot23,235490,30,5,1,24,COMPLETE,9.027926,"{""classifier__C"": 20.182489738515677, ""classifier__class_weight"": null}",1.788819,0.235376,0.014709,0.000287,0.995981,0.995378,0.995245,0.996112,0.996113,0.995766,0.000376,3
25,linear_svm,optuna,iot23,235490,30,5,1,25,COMPLETE,9.850775,"{""classifier__C"": 90.77581717329434, ""classifier__class_weight"": null}",1.953466,0.527042,0.014581,0.000182,0.995981,0.995378,0.995245,0.996112,0.996113,0.995766,0.000376,3
26,linear_svm,optuna,iot23,235490,30,5,1,26,COMPLETE,7.869213,"{""classifier__C"": 1.2511899477973074, ""classifier__class_weight"": null}",1.557376,0.334067,0.014392,0.000437,0.995981,0.995312,0.995245,0.996145,0.996113,0.995759,0.000397,5
12,linear_svm,optuna,iot23,235490,30,5,1,12,COMPLETE,8.347407,"{""classifier__C"": 9.950384075581109, ""classifier__class_weight"": null}",1.652958,0.345526,0.014469,0.000274,0.995981,0.995345,0.995245,0.996112,0.996113,0.995759,0.000383,6
11,linear_svm,optuna,iot23,235490,30,5,1,11,COMPLETE,8.840188,"{""classifier__C"": 48.29670773314647, ""classifier__class_weight"": null}",1.751572,0.280858,0.014405,0.000260,0.995981,0.995378,0.995245,0.996079,0.996113,0.995759,0.000370,7
22,linear_svm,optuna,iot23,235490,30,5,1,22,COMPLETE,8.426547,"{""classifier__C"": 2.8431496924581094, ""classifier__class_weight"": null}",1.669102,0.678511,0.014148,0.000124,0.996014,0.995378,0.995245,0.996046,0.996113,0.995759,0.000369,8
23,linear_svm,optuna,iot23,235490,30,5,1,23,COMPLETE,8.162636,"{""classifier__C"": 8.453981055410763, ""classifier__class_weight"": null}",1.615960,0.399025,0.014385,0.000385,0.995981,0.995378,0.995245,0.996046,0.996113,0.995753,0.000365,9
8,linear_svm,optuna,iot23,235490,30,5,1,8,COMPLETE,9.160743,"{""classifier__C"": 24.096044772653222, ""classifier__class_weight"": null}",1.815786,0.251000,0.014514,0.000182,0.995981,0.995312,0.995245,0.996079,0.996113,0.995746,0.000385,10
10,linear_svm,optuna,iot23,235490,30,5,1,10,COMPLETE,8.566926,"{""classifier__C"": 50.46246112561027, ""classifier__class_weight"": null}",1.696798,0.515686,0.014521,0.000227,0.995981,0.995345,0.995245,0.996046,0.996113,0.995746,0.000372,11
13,linear_svm,optuna,iot23,235490,30,5,1,13,COMPLETE,10.531146,"{""classifier__C"": 2.489265072954432, ""classifier__class_weight"": null}",2.089483,1.299205,0.014622,0.000200,0.995981,0.995312,0.995245,0.996046,0.996113,0.995739,0.000379,12
14,linear_svm,optuna,iot23,235490,30,5,1,14,COMPLETE,8.598127,"{""classifier__C"": 6.483958415124679, ""classifier__class_weight"": null}",1.703376,0.407338,0.014207,0.000070,0.995981,0.995312,0.995245,0.996046,0.996113,0.995739,0.000379,12
15,linear_svm,optuna,iot23,235490,30,5,1,15,COMPLETE,9.153248,"{""classifier__C"": 9.956547936614156, ""classifier__class_weight"": null}",1.814042,0.380292,0.014503,0.000253,0.995981,0.995312,0.995245,0.996046,0.996113,0.995739,0.000379,12
27,linear_svm,optuna,iot23,235490,30,5,1,27,COMPLETE,7.206172,"{""classifier__C"": 0.16892419661801938, ""classifier__class_weight"": null}",1.424439,0.115662,0.014695,0.000305,0.996245,0.994750,0.995212,0.996343,0.996146,0.995739,0.000639,15
29,linear_svm,optuna,iot23,235490,30,5,1,29,COMPLETE,7.009358,"{""classifier__C"": 0.15972846913490713, ""classifier__class_weight"": null}",1.385192,0.083799,0.014604,0.000317,0.996245,0.994750,0.995179,0.996343,0.996146,0.995733,0.000645,16
16,linear_svm,optuna,iot23,235490,30,5,1,16,COMPLETE,7.832184,"{""classifier__C"": 0.6039256971924426, ""classifier__class_weight"": null}",1.550021,0.421270,0.014320,0.000400,0.996047,0.994784,0.995245,0.996211,0.996113,0.995680,0.000565,17
21,linear_svm,optuna,iot23,235490,30,5,1,21,COMPLETE,8.016702,"{""classifier__C"": 0.7257591827442454, ""classifier__class_weight"": null}",1.586953,0.238706,0.014324,0.000286,0.996047,0.994784,0.995245,0.996145,0.996113,0.995667,0.000553,18
0,linear_svm,optuna,iot23,235490,30,5,1,0,COMPLETE,7.530445,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null}",1.489502,0.247863,0.014709,0.000367,0.996279,0.994750,0.995179,0.996310,0.995716,0.995647,0.000611,19
1,linear_svm,optuna,iot23,235490,30,5,1,1,COMPLETE,5.968098,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": null}",1.177364,0.101847,0.014459,0.000343,0.996444,0.994784,0.994618,0.995781,0.996014,0.995528,0.000710,20
4,linear_svm,optuna,iot23,235490,30,5,1,4,COMPLETE,4.946353,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null}",0.973023,0.106252,0.014440,0.000348,0.995684,0.994916,0.994719,0.995484,0.995750,0.995310,0.000417,21
7,linear_svm,optuna,iot23,235490,30,5,1,7,COMPLETE,13.186264,"{""classifier__C"": 69.3917561414594, ""classifier__class_weight"": ""balanced""}",2.620769,0.982184,0.014650,0.000385,0.994104,0.993996,0.994488,0.995122,0.994826,0.994507,0.000425,22
17,linear_svm,optuna,iot23,235490,30,5,1,17,COMPLETE,12.379413,"{""classifier__C"": 21.825328025495757, ""classifier__class_weight"": ""balanced""}",2.459326,0.957074,0.014465,0.000279,0.994104,0.993963,0.994423,0.995089,0.994826,0.994481,0.000425,23
5,linear_svm,optuna,iot23,235490,30,5,1,5,COMPLETE,11.695780,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced""}",2.322963,0.836952,0.014355,0.000167,0.994104,0.993996,0.994455,0.995023,0.994826,0.994481,0.000398,24
3,linear_svm,optuna,iot23,235490,30,5,1,3,COMPLETE,10.692959,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": ""balanced""}",2.122460,0.542421,0.014339,0.000240,0.994038,0.993963,0.994456,0.995023,0.994826,0.994461,0.000419,25
6,linear_svm,optuna,iot23,235490,30,5,1,6,COMPLETE,4.652489,"{""classifier__C"": 0.005034249005866117, ""classifier__class_weight"": ""balanced""}",0.914115,0.087076,0.014535,0.000367,0.994301,0.993732,0.993533,0.994663,0.994497,0.994145,0.000438,26
20,linear_svm,optuna,iot23,235490,30,5,1,20,COMPLETE,8.890784,"{""classifier__C"": 0.06516496425754421, ""classifier__class_weight"": ""balanced""}",1.761551,0.541984,0.014531,0.000620,0.993907,0.993963,0.993698,0.994529,0.994266,0.994072,0.000292,27
2,linear_svm,optuna,iot23,235490,30,5,1,2,COMPLETE,5.008933,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced""}",0.985438,0.172056,0.014498,0.000384,0.994301,0.993634,0.993303,0.994663,0.994267,0.994033,0.000493,28
28,linear_svm,optuna,iot23,235490,30,5,1,28,COMPLETE,3.846005,"{""classifier__C"": 0.0015701491614882478, ""classifier__class_weight"": null}",0.752290,0.036511,0.014811,0.000946,0.994625,0.993492,0.993299,0.994260,0.994162,0.993968,0.000496,29
9,linear_svm,optuna,iot23,235490,30,5,1,9,COMPLETE,3.978514,"{""classifier__C"": 0.0015677395556368667, ""classifier__class_weight"": ""balanced""}",0.779233,0.098117,0.014641,0.000516,0.994071,0.993403,0.993076,0.994201,0.994168,0.993784,0.000458,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,linear_svm,optuna,iot23,235490,30,5,1,1,2.326202,0.058949,0.995101,0.992037,0.993567,0.998011,0.998779,0.998395,0.995981,0.997431,0.995408
1,linear_svm,optuna,iot23,235490,30,5,1,2,2.327717,0.051381,0.995302,0.989702,0.992494,0.997429,0.998832,0.998130,0.995312,0.997006,0.994267
2,linear_svm,optuna,iot23,235490,30,5,1,3,3.226781,0.045422,0.995407,0.989384,0.992387,0.997350,0.998859,0.998104,0.995245,0.996964,0.994122
3,linear_svm,optuna,iot23,235490,30,5,1,4,4.000912,0.042529,0.996267,0.991507,0.993881,0.997879,0.999071,0.998475,0.996178,0.997558,0.995289
4,linear_svm,optuna,iot23,235490,30,5,1,5,2.347950,0.057539,0.995737,0.991826,0.993778,0.997958,0.998938,0.998448,0.996113,0.997516,0.995382

Modelo: linear_svm | origem do treinamento: cicids2017_unsw_nb15

[I 2026-10-12 04:30:41,376] A new study created in memory with name: linear_svm_cicids2017_unsw_nb15
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:31:25,072] Trial 0 finished with value: 0.8016671206624905 and parameters: {'classifier__C': 0.12164941464151847, 'classifier__class_weight': None}. Best is trial 0 with value: 0.8016671206624905.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:31:56,810] Trial 1 finished with value: 0.7945413965427324 and parameters: {'classifier__C': 0.0324835034508668, 'classifier__class_weight': None}. Best is trial 0 with value: 0.8016671206624905.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:32:17,883] Trial 2 finished with value: 0.8132559084415242 and parameters: {'classifier__C': 0.008536916958038761, 'classifier__class_weight': 'balanced'}. Best is trial 2 with value: 0.8132559084415242.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:32:50,346] Trial 3 finished with value: 0.8343900757854131 and parameters: {'classifier__C': 0.4944059287398678, 'classifier__class_weight': 'balanced'}. Best is trial 3 with value: 0.8343900757854131.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:33:14,893] Trial 4 finished with value: 0.7936030986153417 and parameters: {'classifier__C': 0.01052594868979971, 'classifier__class_weight': None}. Best is trial 3 with value: 0.8343900757854131.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:33:59,225] Trial 5 finished with value: 0.8449289438538473 and parameters: {'classifier__C': 2.25080333975975, 'classifier__class_weight': 'balanced'}. Best is trial 5 with value: 0.8449289438538473.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:34:14,202] Trial 6 finished with value: 0.8132733210174388 and parameters: {'classifier__C': 0.005034249005866117, 'classifier__class_weight': 'balanced'}. Best is trial 5 with value: 0.8449289438538473.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:34:43,648] Trial 7 finished with value: 0.8470116951450593 and parameters: {'classifier__C': 69.3917561414594, 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.8470116951450593.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:35:18,235] Trial 8 finished with value: 0.8183510115710284 and parameters: {'classifier__C': 24.096044772653222, 'classifier__class_weight': None}. Best is trial 7 with value: 0.8470116951450593.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:35:31,594] Trial 9 finished with value: 0.8137955317077313 and parameters: {'classifier__C': 0.0015677395556368667, 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.8470116951450593.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:36:14,168] Trial 10 finished with value: 0.847185446469495 and parameters: {'classifier__C': 38.40450841639351, 'classifier__class_weight': 'balanced'}. Best is trial 10 with value: 0.847185446469495.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:36:43,445] Trial 11 finished with value: 0.8471704125517245 and parameters: {'classifier__C': 86.5093058278553, 'classifier__class_weight': 'balanced'}. Best is trial 10 with value: 0.847185446469495.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:37:18,838] Trial 12 finished with value: 0.8470898076568998 and parameters: {'classifier__C': 12.729975807923264, 'classifier__class_weight': 'balanced'}. Best is trial 10 with value: 0.847185446469495.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:37:55,979] Trial 13 finished with value: 0.8471034230241313 and parameters: {'classifier__C': 9.356185217636972, 'classifier__class_weight': 'balanced'}. Best is trial 10 with value: 0.847185446469495.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:39:02,445] Trial 14 finished with value: 0.8179304003532295 and parameters: {'classifier__C': 3.0410650617777244, 'classifier__class_weight': None}. Best is trial 10 with value: 0.847185446469495.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:39:41,697] Trial 15 finished with value: 0.8471649476408973 and parameters: {'classifier__C': 55.98628381282539, 'classifier__class_weight': 'balanced'}. Best is trial 10 with value: 0.847185446469495.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:40:18,490] Trial 16 finished with value: 0.8458615821040849 and parameters: {'classifier__C': 3.281379454479388, 'classifier__class_weight': 'balanced'}. Best is trial 10 with value: 0.847185446469495.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:41:19,438] Trial 17 finished with value: 0.8183984700415273 and parameters: {'classifier__C': 48.83593030938401, 'classifier__class_weight': None}. Best is trial 10 with value: 0.847185446469495.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:41:49,923] Trial 18 finished with value: 0.847243427348797 and parameters: {'classifier__C': 28.99831460488399, 'classifier__class_weight': 'balanced'}. Best is trial 18 with value: 0.847243427348797.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:42:20,594] Trial 19 finished with value: 0.8355441280422017 and parameters: {'classifier__C': 0.5902742948215418, 'classifier__class_weight': 'balanced'}. Best is trial 18 with value: 0.847243427348797.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:42:43,749] Trial 20 finished with value: 0.8168976062026857 and parameters: {'classifier__C': 0.06516496425754421, 'classifier__class_weight': 'balanced'}. Best is trial 18 with value: 0.847243427348797.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:43:16,228] Trial 21 finished with value: 0.8470983154296701 and parameters: {'classifier__C': 20.951537230791352, 'classifier__class_weight': 'balanced'}. Best is trial 18 with value: 0.847243427348797.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:43:50,662] Trial 22 finished with value: 0.8471020475276688 and parameters: {'classifier__C': 86.93326104937702, 'classifier__class_weight': 'balanced'}. Best is trial 18 with value: 0.847243427348797.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:44:25,717] Trial 23 finished with value: 0.8469772497106653 and parameters: {'classifier__C': 5.811701183398581, 'classifier__class_weight': 'balanced'}. Best is trial 18 with value: 0.847243427348797.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:44:55,851] Trial 24 finished with value: 0.8483047453846492 and parameters: {'classifier__C': 31.808217066869858, 'classifier__class_weight': 'balanced'}. Best is trial 24 with value: 0.8483047453846492.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:45:32,648] Trial 25 finished with value: 0.8471859302800053 and parameters: {'classifier__C': 28.574123483328165, 'classifier__class_weight': 'balanced'}. Best is trial 24 with value: 0.8483047453846492.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:46:25,655] Trial 26 finished with value: 0.8182083295233802 and parameters: {'classifier__C': 10.214824589867378, 'classifier__class_weight': None}. Best is trial 24 with value: 0.8483047453846492.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:47:00,892] Trial 27 finished with value: 0.8175067477028011 and parameters: {'classifier__C': 1.1300964864630034, 'classifier__class_weight': None}. Best is trial 24 with value: 0.8483047453846492.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:47:32,617] Trial 28 finished with value: 0.8470375752422648 and parameters: {'classifier__C': 23.62085074004599, 'classifier__class_weight': 'balanced'}. Best is trial 24 with value: 0.8483047453846492.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:47:43,363] Trial 29 finished with value: 0.7919070267168165 and parameters: {'classifier__C': 0.001599085778185112, 'classifier__class_weight': None}. Best is trial 24 with value: 0.8483047453846492.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
24,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,24,COMPLETE,30.134133,"{""classifier__C"": 31.808217066869858, ""classifier__class_weight"": ""balanced""}",5.999167,1.162796,0.024552,0.000251,0.847129,0.857492,0.842432,0.847884,0.846587,0.848305,0.004968,1
18,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,18,COMPLETE,30.483999,"{""classifier__C"": 28.99831460488399, ""classifier__class_weight"": ""balanced""}",6.069433,1.445802,0.024305,0.000294,0.847124,0.857527,0.836557,0.848339,0.846670,0.847243,0.006656,2
25,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,25,COMPLETE,36.795784,"{""classifier__C"": 28.574123483328165, ""classifier__class_weight"": ""balanced""}",7.331641,2.220417,0.024461,0.000367,0.847129,0.857539,0.836697,0.847965,0.846599,0.847186,0.006606,3
10,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,10,COMPLETE,42.573665,"{""classifier__C"": 38.40450841639351, ""classifier__class_weight"": ""balanced""}",8.486411,2.380639,0.025240,0.000802,0.847129,0.857539,0.836550,0.848164,0.846544,0.847185,0.006659,4
11,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,11,COMPLETE,29.276811,"{""classifier__C"": 86.5093058278553, ""classifier__class_weight"": ""balanced""}",5.828056,1.254268,0.024246,0.000324,0.847112,0.857565,0.836611,0.848002,0.846562,0.847170,0.006642,5
15,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,15,COMPLETE,39.252374,"{""classifier__C"": 55.98628381282539, ""classifier__class_weight"": ""balanced""}",7.822974,1.927988,0.024393,0.000236,0.847129,0.857539,0.836435,0.848164,0.846557,0.847165,0.006695,6
13,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,13,COMPLETE,37.140528,"{""classifier__C"": 9.356185217636972, ""classifier__class_weight"": ""balanced""}",7.398632,1.951738,0.026321,0.003649,0.846860,0.857286,0.836901,0.847927,0.846544,0.847103,0.006463,7
22,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,22,COMPLETE,34.433402,"{""classifier__C"": 86.93326104937702, ""classifier__class_weight"": ""balanced""}",6.858965,1.431089,0.024631,0.000420,0.846996,0.857492,0.836564,0.847914,0.846544,0.847102,0.006633,8
21,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,21,COMPLETE,32.478629,"{""classifier__C"": 20.951537230791352, ""classifier__class_weight"": ""balanced""}",6.468396,1.221777,0.024287,0.000169,0.847109,0.857509,0.836660,0.847626,0.846587,0.847098,0.006601,9
12,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,12,COMPLETE,35.392185,"{""classifier__C"": 12.729975807923264, ""classifier__class_weight"": ""balanced""}",7.051067,0.833558,0.024322,0.000256,0.847034,0.857373,0.836817,0.847651,0.846574,0.847090,0.006509,10
28,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,28,COMPLETE,31.724751,"{""classifier__C"": 23.62085074004599, ""classifier__class_weight"": ""balanced""}",6.317714,1.243075,0.024158,0.000286,0.847134,0.857368,0.836296,0.847876,0.846514,0.847038,0.006680,11
7,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,7,COMPLETE,29.445046,"{""classifier__C"": 69.3917561414594, ""classifier__class_weight"": ""balanced""}",5.861555,0.773972,0.024644,0.000790,0.847009,0.857398,0.836964,0.847326,0.846362,0.847012,0.006471,12
23,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,23,COMPLETE,35.054645,"{""classifier__C"": 5.811701183398581, ""classifier__class_weight"": ""balanced""}",6.983210,2.234822,0.024652,0.000297,0.847072,0.857298,0.836076,0.847965,0.846476,0.846977,0.006732,13
16,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,16,COMPLETE,36.792301,"{""classifier__C"": 3.281379454479388, ""classifier__class_weight"": ""balanced""}",7.331308,1.939099,0.024076,0.000264,0.846903,0.853447,0.835651,0.847023,0.846284,0.845862,0.005734,14
5,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,5,COMPLETE,44.331866,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced""}",8.838137,2.335192,0.025353,0.001675,0.846870,0.853291,0.834956,0.843238,0.846289,0.844929,0.005964,15
19,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,19,COMPLETE,30.671201,"{""classifier__C"": 0.5902742948215418, ""classifier__class_weight"": ""balanced""}",6.107027,1.939127,0.024180,0.000248,0.842264,0.852043,0.820212,0.817780,0.845421,0.835544,0.013896,16
3,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,3,COMPLETE,32.462142,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": ""balanced""}",6.465260,1.909171,0.024369,0.000277,0.838362,0.851527,0.820306,0.817721,0.844035,0.834390,0.013257,17
17,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,17,COMPLETE,60.947345,"{""classifier__C"": 48.83593030938401, ""classifier__class_weight"": null}",12.162005,7.564874,0.024395,0.000433,0.818402,0.821958,0.818138,0.817542,0.815952,0.818398,0.001973,18
8,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,8,COMPLETE,34.586511,"{""classifier__C"": 24.096044772653222, ""classifier__class_weight"": null}",6.890313,0.567272,0.024211,0.000204,0.818380,0.821737,0.818251,0.817435,0.815952,0.818351,0.001901,19
26,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,26,COMPLETE,53.006259,"{""classifier__C"": 10.214824589867378, ""classifier__class_weight"": null}",10.573826,5.016875,0.024363,0.000499,0.818402,0.821007,0.818184,0.817421,0.816028,0.818208,0.001627,20
14,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,14,COMPLETE,66.465168,"{""classifier__C"": 3.0410650617777244, ""classifier__class_weight"": null}",13.265818,5.270792,0.024163,0.000269,0.818245,0.820069,0.818158,0.817302,0.815879,0.817930,0.001366,21
27,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,27,COMPLETE,35.236843,"{""classifier__C"": 1.1300964864630034, ""classifier__class_weight"": null}",7.019815,1.550503,0.024483,0.000376,0.818186,0.818544,0.817931,0.817198,0.815675,0.817507,0.001017,22
20,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,20,COMPLETE,23.153793,"{""classifier__C"": 0.06516496425754421, ""classifier__class_weight"": ""balanced""}",4.601819,0.875629,0.025902,0.001724,0.813052,0.828563,0.817239,0.813342,0.812292,0.816898,0.006080,23
9,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,9,COMPLETE,13.358077,"{""classifier__C"": 0.0015677395556368667, ""classifier__class_weight"": ""balanced""}",2.644235,0.761572,0.024530,0.000597,0.813195,0.813435,0.816753,0.813044,0.812550,0.813796,0.001507,24
6,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,6,COMPLETE,14.976588,"{""classifier__C"": 0.005034249005866117, ""classifier__class_weight"": ""balanced""}",2.968175,0.978265,0.024356,0.000295,0.812685,0.812596,0.816886,0.812587,0.811613,0.813273,0.001848,25
2,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,2,COMPLETE,21.072425,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced""}",4.187204,0.613451,0.024501,0.000473,0.812497,0.812722,0.816823,0.812531,0.811707,0.813256,0.001817,26
0,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,0,COMPLETE,43.693513,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null}",8.710746,4.720791,0.025128,0.000840,0.797544,0.808011,0.798206,0.797888,0.806687,0.801667,0.004663,27
1,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,1,COMPLETE,31.737887,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": null}",6.320478,5.076593,0.024338,0.000323,0.795003,0.794321,0.795053,0.795388,0.792943,0.794541,0.000871,28
4,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,4,COMPLETE,24.546678,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null}",4.882266,2.192896,0.024269,0.000291,0.794277,0.793197,0.794062,0.794513,0.791967,0.793603,0.000931,29
29,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,29,COMPLETE,10.744981,"{""classifier__C"": 0.001599085778185112, ""classifier__class_weight"": null}",2.120831,0.195810,0.025065,0.001071,0.792372,0.791562,0.792588,0.792966,0.790047,0.791907,0.001037,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,1,11.829663,0.089308,0.681653,0.868404,0.763779,0.964685,0.898617,0.930480,0.847129,0.892575,0.883511
1,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,2,9.805408,0.084966,0.693908,0.890647,0.780064,0.970579,0.901789,0.934920,0.857492,0.899560,0.896218
2,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,3,11.521020,0.071464,0.666130,0.879193,0.757974,0.967171,0.889830,0.926890,0.842432,0.887702,0.884511
3,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,4,8.387626,0.110358,0.685109,0.864968,0.764604,0.963869,0.900605,0.931164,0.847884,0.893477,0.882787
4,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,5,10.069869,0.080729,0.682081,0.865127,0.762776,0.963855,0.899185,0.930398,0.846587,0.892373,0.882156

Modelo: linear_svm | origem do treinamento: cicids2017_iot23

[I 2026-10-12 04:48:10,482] A new study created in memory with name: linear_svm_cicids2017_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:48:46,860] Trial 0 finished with value: 0.9460690122112085 and parameters: {'classifier__C': 0.12164941464151847, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9460690122112085.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:49:09,583] Trial 1 finished with value: 0.9457615587988023 and parameters: {'classifier__C': 0.0324835034508668, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9460690122112085.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:49:22,142] Trial 2 finished with value: 0.9238183710980286 and parameters: {'classifier__C': 0.008536916958038761, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9460690122112085.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:49:58,407] Trial 3 finished with value: 0.9265780662693235 and parameters: {'classifier__C': 0.4944059287398678, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9460690122112085.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:50:08,687] Trial 4 finished with value: 0.945647557275857 and parameters: {'classifier__C': 0.01052594868979971, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9460690122112085.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:50:57,807] Trial 5 finished with value: 0.9318156368193147 and parameters: {'classifier__C': 2.25080333975975, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9460690122112085.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:51:07,325] Trial 6 finished with value: 0.9237576668705113 and parameters: {'classifier__C': 0.005034249005866117, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9460690122112085.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:51:56,463] Trial 7 finished with value: 0.9435866730550027 and parameters: {'classifier__C': 69.3917561414594, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9460690122112085.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:53:15,841] Trial 8 finished with value: 0.9566108858943407 and parameters: {'classifier__C': 24.096044772653222, 'classifier__class_weight': None}. Best is trial 8 with value: 0.9566108858943407.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:53:25,403] Trial 9 finished with value: 0.923772320062705 and parameters: {'classifier__C': 0.0015677395556368667, 'classifier__class_weight': 'balanced'}. Best is trial 8 with value: 0.9566108858943407.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:54:24,537] Trial 10 finished with value: 0.9570617569018218 and parameters: {'classifier__C': 50.46246112561027, 'classifier__class_weight': None}. Best is trial 10 with value: 0.9570617569018218.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:55:55,154] Trial 11 finished with value: 0.9571528838683317 and parameters: {'classifier__C': 48.29670773314647, 'classifier__class_weight': None}. Best is trial 11 with value: 0.9571528838683317.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:57:17,760] Trial 12 finished with value: 0.9573703094311403 and parameters: {'classifier__C': 80.19985870613085, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9573703094311403.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:58:42,178] Trial 13 finished with value: 0.952018029530838 and parameters: {'classifier__C': 3.738251062600857, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9573703094311403.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 04:59:52,856] Trial 14 finished with value: 0.9540927013895159 and parameters: {'classifier__C': 6.483958415124679, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9573703094311403.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:00:44,762] Trial 15 finished with value: 0.9483764243197479 and parameters: {'classifier__C': 0.9494815930822887, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9573703094311403.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:01:34,024] Trial 16 finished with value: 0.9409540374997292 and parameters: {'classifier__C': 14.2871774062585, 'classifier__class_weight': 'balanced'}. Best is trial 12 with value: 0.9573703094311403.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:03:01,141] Trial 17 finished with value: 0.9569306915188864 and parameters: {'classifier__C': 48.185028416094525, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9573703094311403.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:04:08,483] Trial 18 finished with value: 0.9557758021290615 and parameters: {'classifier__C': 12.403995786585147, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9573703094311403.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:04:47,357] Trial 19 finished with value: 0.9486878688579248 and parameters: {'classifier__C': 1.1463308082891923, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9573703094311403.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:06:11,608] Trial 20 finished with value: 0.9573299344000128 and parameters: {'classifier__C': 93.50472965761261, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9573703094311403.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:07:51,744] Trial 21 finished with value: 0.9572241900545764 and parameters: {'classifier__C': 96.11165745966535, 'classifier__class_weight': None}. Best is trial 12 with value: 0.9573703094311403.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:09:38,792] Trial 22 finished with value: 0.9574267746130479 and parameters: {'classifier__C': 89.93277588459073, 'classifier__class_weight': None}. Best is trial 22 with value: 0.9574267746130479.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:10:46,425] Trial 23 finished with value: 0.9563037502366732 and parameters: {'classifier__C': 18.13038696963024, 'classifier__class_weight': None}. Best is trial 22 with value: 0.9574267746130479.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:12:16,192] Trial 24 finished with value: 0.9554390141197663 and parameters: {'classifier__C': 10.805618595409454, 'classifier__class_weight': None}. Best is trial 22 with value: 0.9574267746130479.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:13:36,770] Trial 25 finished with value: 0.957141657735772 and parameters: {'classifier__C': 91.38512639584005, 'classifier__class_weight': None}. Best is trial 22 with value: 0.9574267746130479.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:14:31,363] Trial 26 finished with value: 0.9426059284228275 and parameters: {'classifier__C': 30.656350373044013, 'classifier__class_weight': 'balanced'}. Best is trial 22 with value: 0.9574267746130479.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:16:01,282] Trial 27 finished with value: 0.9567885170447405 and parameters: {'classifier__C': 28.432941770302218, 'classifier__class_weight': None}. Best is trial 22 with value: 0.9574267746130479.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:17:10,344] Trial 28 finished with value: 0.953860728177054 and parameters: {'classifier__C': 6.088067276086894, 'classifier__class_weight': None}. Best is trial 22 with value: 0.9574267746130479.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:17:19,950] Trial 29 finished with value: 0.9456472903903842 and parameters: {'classifier__C': 0.001599085778185112, 'classifier__class_weight': None}. Best is trial 22 with value: 0.9574267746130479.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
22,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,22,COMPLETE,107.047529,"{""classifier__C"": 89.93277588459073, ""classifier__class_weight"": null}",21.382249,6.012340,0.024176,0.000385,0.956886,0.957818,0.957964,0.957266,0.957200,0.957427,0.000403,1
12,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,12,COMPLETE,82.604992,"{""classifier__C"": 80.19985870613085, ""classifier__class_weight"": null}",16.493239,5.870471,0.024674,0.000879,0.956919,0.957413,0.958040,0.957174,0.957305,0.957370,0.000373,2
20,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,20,COMPLETE,84.250346,"{""classifier__C"": 93.50472965761261, ""classifier__class_weight"": null}",16.822623,4.510094,0.024358,0.000537,0.956867,0.957545,0.957742,0.957271,0.957224,0.957330,0.000298,3
21,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,21,COMPLETE,100.135954,"{""classifier__C"": 96.11165745966535, ""classifier__class_weight"": null}",19.999646,3.803473,0.024455,0.000501,0.956901,0.957207,0.957980,0.956695,0.957338,0.957224,0.000440,4
11,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,11,COMPLETE,90.616531,"{""classifier__C"": 48.29670773314647, ""classifier__class_weight"": null}",18.096148,10.926635,0.024113,0.000290,0.956640,0.957530,0.957694,0.956843,0.957057,0.957153,0.000401,5
25,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,25,COMPLETE,80.578230,"{""classifier__C"": 91.38512639584005, ""classifier__class_weight"": null}",16.088389,4.667598,0.024181,0.000572,0.956886,0.957578,0.956928,0.957190,0.957127,0.957142,0.000247,6
10,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,10,COMPLETE,59.133026,"{""classifier__C"": 50.46246112561027, ""classifier__class_weight"": null}",11.799199,3.025944,0.024074,0.000462,0.956810,0.957071,0.957725,0.956891,0.956812,0.957062,0.000345,7
17,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,17,COMPLETE,87.116204,"{""classifier__C"": 48.185028416094525, ""classifier__class_weight"": null}",17.395978,4.326426,0.024181,0.000315,0.956156,0.957269,0.957146,0.957018,0.957065,0.956931,0.000397,8
27,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,27,COMPLETE,89.918845,"{""classifier__C"": 28.432941770302218, ""classifier__class_weight"": null}",17.956503,7.502296,0.024201,0.000491,0.956267,0.957191,0.957179,0.956678,0.956628,0.956789,0.000353,9
8,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,8,COMPLETE,79.377340,"{""classifier__C"": 24.096044772653222, ""classifier__class_weight"": null}",15.848476,5.159723,0.024104,0.000250,0.956041,0.957084,0.956978,0.956584,0.956368,0.956611,0.000386,10
23,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,23,COMPLETE,67.631784,"{""classifier__C"": 18.13038696963024, ""classifier__class_weight"": null}",13.498892,2.863429,0.024399,0.000377,0.955677,0.956996,0.956615,0.956147,0.956083,0.956304,0.000457,11
18,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,18,COMPLETE,67.341539,"{""classifier__C"": 12.403995786585147, ""classifier__class_weight"": null}",13.440853,4.863492,0.024350,0.000709,0.955314,0.956637,0.956237,0.955183,0.955508,0.955776,0.000564,12
24,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,24,COMPLETE,89.766443,"{""classifier__C"": 10.805618595409454, ""classifier__class_weight"": null}",17.925634,11.533268,0.024552,0.000673,0.954899,0.956591,0.955688,0.954714,0.955303,0.955439,0.000667,13
14,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,14,COMPLETE,70.677477,"{""classifier__C"": 6.483958415124679, ""classifier__class_weight"": null}",14.108583,2.579274,0.023875,0.000201,0.953704,0.955960,0.954063,0.953033,0.953704,0.954093,0.000992,14
28,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,28,COMPLETE,69.061114,"{""classifier__C"": 6.088067276086894, ""classifier__class_weight"": null}",13.785127,3.495735,0.024027,0.000439,0.953367,0.955791,0.953810,0.952927,0.953410,0.953861,0.001005,15
13,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,13,COMPLETE,84.417193,"{""classifier__C"": 3.738251062600857, ""classifier__class_weight"": null}",16.856172,6.741024,0.024196,0.000191,0.951290,0.954567,0.951325,0.951422,0.951486,0.952018,0.001276,16
19,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,19,COMPLETE,38.873647,"{""classifier__C"": 1.1463308082891923, ""classifier__class_weight"": null}",7.747585,1.926334,0.024079,0.000157,0.948213,0.951191,0.948116,0.948228,0.947692,0.948688,0.001267,17
15,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,15,COMPLETE,51.905773,"{""classifier__C"": 0.9494815930822887, ""classifier__class_weight"": null}",10.353743,3.656866,0.024375,0.000384,0.948044,0.950887,0.947671,0.948028,0.947253,0.948376,0.001288,18
0,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,0,COMPLETE,36.375779,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null}",7.247802,2.774620,0.024281,0.000646,0.945363,0.948322,0.945640,0.946021,0.944999,0.946069,0.001175,19
1,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,1,COMPLETE,22.722468,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": null}",4.517433,3.305780,0.024283,0.000269,0.945154,0.947814,0.945353,0.945740,0.944747,0.945762,0.001075,20
4,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,4,COMPLETE,10.279278,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null}",2.028355,0.259744,0.024618,0.000533,0.945059,0.947690,0.945224,0.945673,0.944591,0.945648,0.001078,21
29,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,29,COMPLETE,9.605939,"{""classifier__C"": 0.001599085778185112, ""classifier__class_weight"": null}",1.893697,0.147977,0.024432,0.000708,0.945284,0.947502,0.945125,0.945700,0.944626,0.945647,0.000989,22
7,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,7,COMPLETE,49.136967,"{""classifier__C"": 69.3917561414594, ""classifier__class_weight"": ""balanced""}",9.800817,1.823457,0.023805,0.000115,0.944861,0.943420,0.944358,0.942455,0.942839,0.943587,0.000904,23
26,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,26,COMPLETE,54.591584,"{""classifier__C"": 30.656350373044013, ""classifier__class_weight"": ""balanced""}",10.891093,1.976914,0.024157,0.000439,0.943620,0.943365,0.943273,0.941007,0.941764,0.942606,0.001031,24
16,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,16,COMPLETE,49.261761,"{""classifier__C"": 14.2871774062585, ""classifier__class_weight"": ""balanced""}",9.825088,3.355293,0.024122,0.000187,0.941592,0.942994,0.941001,0.939544,0.939640,0.940954,0.001287,25
5,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,5,COMPLETE,49.119344,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced""}",9.796823,3.644121,0.024255,0.000278,0.932106,0.934100,0.931237,0.931090,0.930545,0.931816,0.001247,26
3,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,3,COMPLETE,36.264632,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": ""balanced""}",7.225783,1.932613,0.024307,0.000513,0.927303,0.928151,0.926154,0.926278,0.925005,0.926578,0.001072,27
2,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,2,COMPLETE,12.557972,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced""}",2.484783,1.248501,0.024008,0.000234,0.924708,0.924731,0.923923,0.923659,0.922071,0.923818,0.000971,28
9,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,9,COMPLETE,9.561998,"{""classifier__C"": 0.0015677395556368667, ""classifier__class_weight"": ""balanced""}",1.883979,0.113432,0.025444,0.002509,0.924720,0.924494,0.924042,0.923568,0.922037,0.923772,0.000953,29
6,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,6,COMPLETE,9.518118,"{""classifier__C"": 0.005034249005866117, ""classifier__class_weight"": ""balanced""}",1.876596,0.109542,0.024231,0.000307,0.924594,0.924640,0.923990,0.923662,0.921902,0.923758,0.000998,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,1,23.078974,0.111590,0.910723,0.953074,0.931417,0.988131,0.976645,0.982355,0.956886,0.971931,0.964859
1,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,2,24.399146,0.082043,0.913887,0.952649,0.932865,0.988036,0.977560,0.982770,0.957818,0.972578,0.965105
2,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,3,42.044444,0.069494,0.914230,0.952760,0.933098,0.988064,0.977653,0.982831,0.957964,0.972674,0.965206
3,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,4,34.901021,0.085615,0.911717,0.953238,0.932015,0.988174,0.976923,0.982516,0.957266,0.972186,0.965080
4,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,5,35.624103,0.073887,0.912504,0.952123,0.931893,0.987899,0.977175,0.982508,0.957200,0.972164,0.964649

Modelo: linear_svm | origem do treinamento: unsw_nb15_iot23

[I 2026-10-12 05:18:18,948] A new study created in memory with name: linear_svm_unsw_nb15_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:18:42,516] Trial 0 finished with value: 0.9519747862440774 and parameters: {'classifier__C': 0.12164941464151847, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9519747862440774.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:19:02,851] Trial 1 finished with value: 0.9480334133754196 and parameters: {'classifier__C': 0.0324835034508668, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9519747862440774.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:19:19,091] Trial 2 finished with value: 0.9387416585327705 and parameters: {'classifier__C': 0.008536916958038761, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9519747862440774.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:19:55,342] Trial 3 finished with value: 0.9501087223803509 and parameters: {'classifier__C': 0.4944059287398678, 'classifier__class_weight': 'balanced'}. Best is trial 0 with value: 0.9519747862440774.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:20:15,026] Trial 4 finished with value: 0.9354617539366142 and parameters: {'classifier__C': 0.01052594868979971, 'classifier__class_weight': None}. Best is trial 0 with value: 0.9519747862440774.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:20:40,652] Trial 5 finished with value: 0.9536579323828983 and parameters: {'classifier__C': 2.25080333975975, 'classifier__class_weight': 'balanced'}. Best is trial 5 with value: 0.9536579323828983.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:20:53,696] Trial 6 finished with value: 0.9382540876963313 and parameters: {'classifier__C': 0.005034249005866117, 'classifier__class_weight': 'balanced'}. Best is trial 5 with value: 0.9536579323828983.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:21:19,307] Trial 7 finished with value: 0.9547004166377135 and parameters: {'classifier__C': 69.3917561414594, 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.9547004166377135.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:21:43,200] Trial 8 finished with value: 0.9537304195366143 and parameters: {'classifier__C': 24.096044772653222, 'classifier__class_weight': None}. Best is trial 7 with value: 0.9547004166377135.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:21:54,917] Trial 9 finished with value: 0.9364582250584503 and parameters: {'classifier__C': 0.0015677395556368667, 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.9547004166377135.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:22:20,753] Trial 10 finished with value: 0.9545817806565677 and parameters: {'classifier__C': 38.40450841639351, 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.9547004166377135.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:22:51,035] Trial 11 finished with value: 0.9544935965147981 and parameters: {'classifier__C': 86.5093058278553, 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.9547004166377135.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:23:21,702] Trial 12 finished with value: 0.954386786195714 and parameters: {'classifier__C': 8.945813535680552, 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.9547004166377135.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:23:49,223] Trial 13 finished with value: 0.9546276284305005 and parameters: {'classifier__C': 68.19098538564086, 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.9547004166377135.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:24:17,865] Trial 14 finished with value: 0.9536593897895713 and parameters: {'classifier__C': 3.0410650617777244, 'classifier__class_weight': None}. Best is trial 7 with value: 0.9547004166377135.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:24:45,897] Trial 15 finished with value: 0.9544011014684433 and parameters: {'classifier__C': 9.762274350036803, 'classifier__class_weight': 'balanced'}. Best is trial 7 with value: 0.9547004166377135.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:25:11,196] Trial 16 finished with value: 0.954712898762752 and parameters: {'classifier__C': 77.75026881948125, 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.954712898762752.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:25:39,978] Trial 17 finished with value: 0.9543683280095723 and parameters: {'classifier__C': 13.618768833449131, 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.954712898762752.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:26:10,450] Trial 18 finished with value: 0.9536925460380127 and parameters: {'classifier__C': 2.374768161029034, 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.954712898762752.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:26:35,478] Trial 19 finished with value: 0.9536665332295229 and parameters: {'classifier__C': 3.953964967975712, 'classifier__class_weight': None}. Best is trial 16 with value: 0.954712898762752.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:27:05,422] Trial 20 finished with value: 0.940678368953589 and parameters: {'classifier__C': 0.06516496425754421, 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.954712898762752.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:27:28,941] Trial 21 finished with value: 0.954546515808438 and parameters: {'classifier__C': 95.85498280276488, 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.954712898762752.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:27:55,004] Trial 22 finished with value: 0.9537474791616802 and parameters: {'classifier__C': 78.84696969254713, 'classifier__class_weight': None}. Best is trial 16 with value: 0.954712898762752.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:28:20,955] Trial 23 finished with value: 0.9544862328731952 and parameters: {'classifier__C': 33.454766074916364, 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.954712898762752.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:28:47,484] Trial 24 finished with value: 0.954634355588811 and parameters: {'classifier__C': 28.896729879528554, 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.954712898762752.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:29:10,908] Trial 25 finished with value: 0.9541172797108022 and parameters: {'classifier__C': 4.7050175407147545, 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.954712898762752.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:29:41,979] Trial 26 finished with value: 0.9542893149778655 and parameters: {'classifier__C': 19.682353885216415, 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.954712898762752.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:30:09,116] Trial 27 finished with value: 0.9535023468606395 and parameters: {'classifier__C': 1.1300964864630034, 'classifier__class_weight': None}. Best is trial 16 with value: 0.954712898762752.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:30:40,157] Trial 28 finished with value: 0.9500067511155189 and parameters: {'classifier__C': 0.47824346061974404, 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.954712898762752.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:31:06,705] Trial 29 finished with value: 0.9542087961465194 and parameters: {'classifier__C': 31.952651849390534, 'classifier__class_weight': 'balanced'}. Best is trial 16 with value: 0.954712898762752.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
16,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,16,COMPLETE,25.299108,"{""classifier__C"": 77.75026881948125, ""classifier__class_weight"": ""balanced""}",5.031832,1.364874,0.024925,0.000606,0.956716,0.950810,0.958986,0.959597,0.947455,0.954713,0.004776,1
7,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,7,COMPLETE,25.611255,"{""classifier__C"": 69.3917561414594, ""classifier__class_weight"": ""balanced""}",5.095005,0.967475,0.024474,0.000328,0.956608,0.950810,0.958986,0.959597,0.947501,0.954700,0.004753,2
24,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,24,COMPLETE,26.529008,"{""classifier__C"": 28.896729879528554, ""classifier__class_weight"": ""balanced""}",5.277549,0.749127,0.025021,0.001830,0.956653,0.950764,0.958763,0.959614,0.947378,0.954634,0.004766,3
13,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,13,COMPLETE,27.519572,"{""classifier__C"": 68.19098538564086, ""classifier__class_weight"": ""balanced""}",5.476529,1.549074,0.024332,0.000428,0.956716,0.950764,0.958986,0.959614,0.947058,0.954628,0.004908,4
10,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,10,COMPLETE,25.835881,"{""classifier__C"": 38.40450841639351, ""classifier__class_weight"": ""balanced""}",5.139717,1.507300,0.024393,0.000309,0.956606,0.950484,0.958874,0.959614,0.947331,0.954582,0.004842,5
21,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,21,COMPLETE,23.518201,"{""classifier__C"": 95.85498280276488, ""classifier__class_weight"": ""balanced""}",4.675396,0.844672,0.025128,0.001012,0.956716,0.950206,0.958986,0.959597,0.947227,0.954547,0.004946,6
11,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,11,COMPLETE,30.281493,"{""classifier__C"": 86.5093058278553, ""classifier__class_weight"": ""balanced""}",6.028772,2.199707,0.024421,0.000363,0.955847,0.950810,0.958986,0.959597,0.947227,0.954494,0.004784,7
23,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,23,COMPLETE,25.949963,"{""classifier__C"": 33.454766074916364, ""classifier__class_weight"": ""balanced""}",5.162479,1.040417,0.024460,0.000328,0.956622,0.949895,0.958986,0.959597,0.947331,0.954486,0.004964,8
15,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,15,COMPLETE,28.030958,"{""classifier__C"": 9.762274350036803, ""classifier__class_weight"": ""balanced""}",5.578953,1.087622,0.024187,0.000242,0.956227,0.950188,0.958891,0.959597,0.947102,0.954401,0.004930,9
12,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,12,COMPLETE,30.666799,"{""classifier__C"": 8.945813535680552, ""classifier__class_weight"": ""balanced""}",6.106085,1.926295,0.024158,0.000205,0.956432,0.949880,0.958939,0.959597,0.947086,0.954387,0.005013,10
17,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,17,COMPLETE,28.780886,"{""classifier__C"": 13.618768833449131, ""classifier__class_weight"": ""balanced""}",5.728608,1.195017,0.024472,0.000538,0.956464,0.949600,0.958986,0.959597,0.947194,0.954368,0.005045,11
26,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,26,COMPLETE,31.070458,"{""classifier__C"": 19.682353885216415, ""classifier__class_weight"": ""balanced""}",6.185588,1.594063,0.024199,0.000352,0.956622,0.949102,0.958795,0.959597,0.947331,0.954289,0.005084,12
29,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,29,COMPLETE,26.546987,"{""classifier__C"": 31.952651849390534, ""classifier__class_weight"": ""balanced""}",5.282055,1.715210,0.024245,0.000309,0.956164,0.949133,0.958986,0.959597,0.947163,0.954209,0.005120,13
25,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,25,COMPLETE,23.423852,"{""classifier__C"": 4.7050175407147545, ""classifier__class_weight"": ""balanced""}",4.657491,0.739752,0.024207,0.000142,0.956007,0.949133,0.958779,0.959597,0.947071,0.954117,0.005095,14
22,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,22,COMPLETE,26.062716,"{""classifier__C"": 78.84696969254713, ""classifier__class_weight"": null}",5.185175,0.472230,0.024187,0.000443,0.953399,0.953694,0.954540,0.954175,0.952931,0.953747,0.000566,15
8,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,8,COMPLETE,23.891722,"{""classifier__C"": 24.096044772653222, ""classifier__class_weight"": null}",4.751402,0.169511,0.024135,0.000330,0.953383,0.953678,0.954486,0.954192,0.952913,0.953730,0.000562,16
18,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,18,COMPLETE,30.472415,"{""classifier__C"": 2.374768161029034, ""classifier__class_weight"": ""balanced""}",6.066856,1.478317,0.024438,0.000329,0.955186,0.948019,0.958621,0.959597,0.947040,0.953693,0.005250,17
19,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,19,COMPLETE,25.026607,"{""classifier__C"": 3.953964967975712, ""classifier__class_weight"": null}",4.977789,0.366376,0.024460,0.000288,0.953347,0.953624,0.954451,0.954175,0.952736,0.953667,0.000607,18
14,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,14,COMPLETE,28.642015,"{""classifier__C"": 3.0410650617777244, ""classifier__class_weight"": null}",5.701297,1.143226,0.023993,0.000376,0.953329,0.953642,0.954486,0.954121,0.952718,0.953659,0.000615,19
5,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,5,COMPLETE,25.625508,"{""classifier__C"": 2.25080333975975, ""classifier__class_weight"": ""balanced""}",5.097988,1.233640,0.024264,0.000424,0.955265,0.947847,0.958621,0.959563,0.946994,0.953658,0.005296,20
27,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,27,COMPLETE,27.136133,"{""classifier__C"": 1.1300964864630034, ""classifier__class_weight"": null}",5.399550,1.094085,0.024607,0.001028,0.953153,0.953428,0.954362,0.954064,0.952506,0.953502,0.000660,21
0,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,0,COMPLETE,23.564598,"{""classifier__C"": 0.12164941464151847, ""classifier__class_weight"": null}",4.685534,0.270013,0.024504,0.000484,0.951519,0.952088,0.952334,0.953026,0.950907,0.951975,0.000721,22
3,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,3,COMPLETE,36.250451,"{""classifier__C"": 0.4944059287398678, ""classifier__class_weight"": ""balanced""}",7.222809,3.667009,0.024489,0.000351,0.947084,0.946942,0.956047,0.959387,0.941084,0.950109,0.006663,23
28,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,28,COMPLETE,31.040852,"{""classifier__C"": 0.47824346061974404, ""classifier__class_weight"": ""balanced""}",6.180743,1.267089,0.024334,0.000360,0.947149,0.946942,0.955639,0.959387,0.940917,0.950007,0.006632,24
1,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,1,COMPLETE,20.334120,"{""classifier__C"": 0.0324835034508668, ""classifier__class_weight"": null}",4.039978,0.252470,0.024048,0.000430,0.947721,0.948122,0.948650,0.949015,0.946659,0.948033,0.000817,25
20,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,20,COMPLETE,29.944121,"{""classifier__C"": 0.06516496425754421, ""classifier__class_weight"": ""balanced""}",5.961437,1.836205,0.024333,0.000296,0.940717,0.940699,0.941370,0.940608,0.939998,0.940678,0.000435,26
2,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,2,COMPLETE,16.239196,"{""classifier__C"": 0.008536916958038761, ""classifier__class_weight"": ""balanced""}",3.220668,0.624866,0.024341,0.000338,0.938677,0.939046,0.938849,0.939042,0.938095,0.938742,0.000351,27
6,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,6,COMPLETE,13.043329,"{""classifier__C"": 0.005034249005866117, ""classifier__class_weight"": ""balanced""}",2.581704,0.171211,0.024184,0.000220,0.938174,0.938595,0.938366,0.938446,0.937690,0.938254,0.000313,28
9,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,9,COMPLETE,11.716377,"{""classifier__C"": 0.0015677395556368667, ""classifier__class_weight"": ""balanced""}",2.315782,0.074768,0.024665,0.000445,0.936217,0.936788,0.936437,0.936514,0.936334,0.936458,0.000193,29
4,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,4,COMPLETE,19.683664,"{""classifier__C"": 0.01052594868979971, ""classifier__class_weight"": null}",3.909497,1.010996,0.024457,0.000817,0.935023,0.934891,0.935440,0.937984,0.933971,0.935462,0.001349,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,1,6.184706,0.088947,0.935572,0.925788,0.930654,0.981497,0.984063,0.982778,0.956716,0.972409,0.954926
1,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,2,6.567419,0.081832,0.917381,0.925417,0.921382,0.981315,0.979166,0.980239,0.950810,0.968417,0.952291
2,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,3,6.863712,0.096658,0.939179,0.929459,0.934294,0.982409,0.984951,0.983679,0.958986,0.973852,0.957205
3,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,4,10.400081,0.069321,0.944462,0.926115,0.935199,0.981617,0.986385,0.983995,0.959597,0.974330,0.956250
4,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,5,7.223200,0.074255,0.908067,0.924310,0.916116,0.980991,0.976604,0.978793,0.947455,0.966145,0.950457

Modelo: mlp | origem do treinamento: cicids2017

[I 2026-10-12 05:31:28,999] A new study created in memory with name: mlp_cicids2017
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:34:18,335] Trial 0 finished with value: 0.986352838995308 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 2.7559267640273738e-05, 'classifier__learning_rate_init': 0.0001529949829431265, 'classifier__early_stopping': False}. Best is trial 0 with value: 0.986352838995308.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:37:40,871] Trial 1 finished with value: 0.9907340051489587 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 4.105412016858889e-05, 'classifier__learning_rate_init': 0.005704727088203684, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9907340051489587.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:39:15,325] Trial 2 finished with value: 0.9865206890216323 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 0.0025248390936171007, 'classifier__learning_rate_init': 0.008640187187029892, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9907340051489587.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:41:25,198] Trial 3 finished with value: 0.9894968276379965 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 3.232148147351273e-05, 'classifier__learning_rate_init': 0.005705385668376793, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9907340051489587.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:43:26,831] Trial 4 finished with value: 0.9888445254392885 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 0.001146839870575158, 'classifier__learning_rate_init': 0.004669295331523649, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9907340051489587.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:44:05,035] Trial 5 finished with value: 0.9857406513678842 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 2.0402247877617882e-05, 'classifier__learning_rate_init': 0.0007866599720665551, 'classifier__early_stopping': True}. Best is trial 1 with value: 0.9907340051489587.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:46:25,097] Trial 6 finished with value: 0.9900916749674143 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 4.314041792135614e-05, 'classifier__learning_rate_init': 0.0003396982571910356, 'classifier__early_stopping': True}. Best is trial 1 with value: 0.9907340051489587.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:48:03,436] Trial 7 finished with value: 0.990181778158871 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 2.027698063881496e-05, 'classifier__learning_rate_init': 0.0006731501945399556, 'classifier__early_stopping': True}. Best is trial 1 with value: 0.9907340051489587.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:49:29,062] Trial 8 finished with value: 0.9900764198935279 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 0.006819998324673501, 'classifier__learning_rate_init': 0.0014897386352200294, 'classifier__early_stopping': True}. Best is trial 1 with value: 0.9907340051489587.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:50:25,850] Trial 9 finished with value: 0.9861844550010035 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 0.006060741222490684, 'classifier__learning_rate_init': 0.0004960571565137328, 'classifier__early_stopping': True}. Best is trial 1 with value: 0.9907340051489587.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:56:19,160] Trial 10 finished with value: 0.989824502775884 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.001212494718830438, 'classifier__learning_rate_init': 0.00011090722889650909, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9907340051489587.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:58:09,515] Trial 11 finished with value: 0.9905649110236316 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 3.113226289948056e-05, 'classifier__learning_rate_init': 0.0036710511871714062, 'classifier__early_stopping': True}. Best is trial 1 with value: 0.9907340051489587.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 05:59:22,225] Trial 12 finished with value: 0.9900077954932378 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 2.104688149615943e-05, 'classifier__learning_rate_init': 0.00851203095001293, 'classifier__early_stopping': True}. Best is trial 1 with value: 0.9907340051489587.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:03:14,779] Trial 13 finished with value: 0.9910647328628205 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.0145206295623886e-05, 'classifier__learning_rate_init': 0.002017977223065986, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:07:20,005] Trial 14 finished with value: 0.9909207439254096 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0001811765232830859, 'classifier__learning_rate_init': 0.0020630586056145403, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:11:46,489] Trial 15 finished with value: 0.991026119534294 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00022190557855364008, 'classifier__learning_rate_init': 0.00160986162881342, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:15:29,527] Trial 16 finished with value: 0.9901668262238953 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 0.0003450097441838016, 'classifier__learning_rate_init': 0.0007272237082808107, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:20:08,810] Trial 17 finished with value: 0.9904170360485128 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.001444507861577274, 'classifier__learning_rate_init': 0.00033351344012071533, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:24:24,214] Trial 18 finished with value: 0.9906655711697929 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.2785930801295058e-05, 'classifier__learning_rate_init': 0.0019383168771295528, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:25:08,775] Trial 19 finished with value: 0.987223485930232 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 0.00032714665991783696, 'classifier__learning_rate_init': 0.0019500008020454666, 'classifier__early_stopping': True}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:30:29,834] Trial 20 finished with value: 0.9904272180927716 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00013707306277129026, 'classifier__learning_rate_init': 0.000372233107477956, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:34:40,855] Trial 21 finished with value: 0.9907100996110657 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.000197890995486617, 'classifier__learning_rate_init': 0.0018295578663031099, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:38:07,449] Trial 22 finished with value: 0.9909419876015034 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00012594954716338742, 'classifier__learning_rate_init': 0.003961549324438345, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:41:28,400] Trial 23 finished with value: 0.9906734704982381 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0009025252238024254, 'classifier__learning_rate_init': 0.002929331541017319, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:44:07,930] Trial 24 finished with value: 0.9907775980239322 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.2462986577710301e-05, 'classifier__learning_rate_init': 0.006463073287965047, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:47:41,065] Trial 25 finished with value: 0.9904536199085697 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00037501217180797093, 'classifier__learning_rate_init': 0.006289134547942787, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:51:14,616] Trial 26 finished with value: 0.9906478552350635 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 6.736265062691812e-05, 'classifier__learning_rate_init': 0.003004475585486129, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:55:02,117] Trial 27 finished with value: 0.9905200153863378 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 4.5052287240014755e-05, 'classifier__learning_rate_init': 0.0007504182447764458, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 06:59:51,963] Trial 28 finished with value: 0.9907892110250941 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 6.462294653216163e-05, 'classifier__learning_rate_init': 0.0012656219921384861, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:04:08,221] Trial 29 finished with value: 0.9908038302171507 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.3000809277666598e-05, 'classifier__learning_rate_init': 0.001095481320910975, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9910647328628205.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
13,mlp,optuna,cicids2017,235490,30,5,1,13,COMPLETE,232.553643,"{""classifier__alpha"": 1.0145206295623886e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.002017977223065986}",46.470478,6.840018,0.037954,0.000394,0.991650,0.990801,0.991848,0.990255,0.990770,0.991065,0.000595,1
15,mlp,optuna,cicids2017,235490,30,5,1,15,COMPLETE,266.483177,"{""classifier__alpha"": 0.00022190557855364008, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00160986162881342}",53.256019,7.736395,0.038328,0.000960,0.991884,0.990365,0.991714,0.990671,0.990497,0.991026,0.000641,2
22,mlp,optuna,cicids2017,235490,30,5,1,22,COMPLETE,206.593061,"{""classifier__alpha"": 0.00012594954716338742, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.003961549324438345}",41.277043,4.558732,0.039312,0.002425,0.991755,0.990273,0.991814,0.990335,0.990532,0.990942,0.000694,3
14,mlp,optuna,cicids2017,235490,30,5,1,14,COMPLETE,245.225653,"{""classifier__alpha"": 0.0001811765232830859, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0020630586056145403}",49.005026,8.119181,0.037845,0.000533,0.991293,0.990595,0.991618,0.990659,0.990438,0.990921,0.000454,4
29,mlp,optuna,cicids2017,235490,30,5,1,29,COMPLETE,256.257512,"{""classifier__alpha"": 1.3000809277666598e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.001095481320910975}",51.211358,9.098089,0.037871,0.000513,0.991614,0.990694,0.991788,0.989975,0.989948,0.990804,0.000782,5
28,mlp,optuna,cicids2017,235490,30,5,1,28,COMPLETE,289.845208,"{""classifier__alpha"": 6.462294653216163e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0012656219921384861}",57.928648,13.601296,0.038119,0.000361,0.991033,0.990221,0.992141,0.990019,0.990532,0.990789,0.000757,6
24,mlp,optuna,cicids2017,235490,30,5,1,24,COMPLETE,159.530097,"{""classifier__alpha"": 1.2462986577710301e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.006463073287965047}",31.866077,5.513171,0.037689,0.000525,0.991132,0.990408,0.991484,0.990194,0.990669,0.990778,0.000472,7
1,mlp,optuna,cicids2017,235490,30,5,1,1,COMPLETE,202.535813,"{""classifier__alpha"": 4.105412016858889e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.005704727088203684}",40.467409,6.571383,0.037790,0.000668,0.991258,0.990533,0.991521,0.990007,0.990350,0.990734,0.000567,8
21,mlp,optuna,cicids2017,235490,30,5,1,21,COMPLETE,251.020825,"{""classifier__alpha"": 0.000197890995486617, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0018295578663031099}",50.164206,6.999859,0.037684,0.000632,0.991512,0.990359,0.991457,0.989789,0.990433,0.990710,0.000671,9
23,mlp,optuna,cicids2017,235490,30,5,1,23,COMPLETE,200.950189,"{""classifier__alpha"": 0.0009025252238024254, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.002929331541017319}",40.149925,2.706007,0.037840,0.000335,0.991522,0.990090,0.991618,0.990003,0.990135,0.990673,0.000734,10
18,mlp,optuna,cicids2017,235490,30,5,1,18,COMPLETE,255.402978,"{""classifier__alpha"": 1.2785930801295058e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0019383168771295528}",51.040852,11.108712,0.037478,0.000147,0.991024,0.990927,0.991453,0.990089,0.989836,0.990666,0.000606,11
26,mlp,optuna,cicids2017,235490,30,5,1,26,COMPLETE,213.549906,"{""classifier__alpha"": 6.736265062691812e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.003004475585486129}",42.669432,5.743502,0.038250,0.001559,0.990997,0.990727,0.991718,0.989821,0.989976,0.990648,0.000694,12
11,mlp,optuna,cicids2017,235490,30,5,1,11,COMPLETE,110.354756,"{""classifier__alpha"": 3.113226289948056e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0036710511871714062}",22.031370,7.392374,0.037331,0.000280,0.991126,0.990006,0.991580,0.989541,0.990571,0.990565,0.000735,13
27,mlp,optuna,cicids2017,235490,30,5,1,27,COMPLETE,227.500946,"{""classifier__alpha"": 4.5052287240014755e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0007504182447764458}",45.460033,7.582163,0.037897,0.000534,0.990935,0.989959,0.991492,0.990100,0.990114,0.990520,0.000596,14
25,mlp,optuna,cicids2017,235490,30,5,1,25,COMPLETE,213.134376,"{""classifier__alpha"": 0.00037501217180797093, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.006289134547942787}",42.586960,4.690077,0.037630,0.000386,0.990011,0.990240,0.991782,0.990037,0.990197,0.990454,0.000670,15
20,mlp,optuna,cicids2017,235490,30,5,1,20,COMPLETE,321.058093,"{""classifier__alpha"": 0.00013707306277129026, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.000372233107477956}",64.171245,12.274896,0.038086,0.000669,0.990495,0.990264,0.991544,0.990561,0.989272,0.990427,0.000726,16
17,mlp,optuna,cicids2017,235490,30,5,1,17,COMPLETE,279.282855,"{""classifier__alpha"": 0.001444507861577274, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00033351344012071533}",55.816641,6.251656,0.037684,0.000414,0.991352,0.989934,0.991524,0.990101,0.989175,0.990417,0.000892,17
7,mlp,optuna,cicids2017,235490,30,5,1,7,COMPLETE,98.338878,"{""classifier__alpha"": 2.027698063881496e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0006731501945399556}",19.627884,1.529211,0.037919,0.000498,0.990794,0.989764,0.991114,0.989465,0.989772,0.990182,0.000648,18
16,mlp,optuna,cicids2017,235490,30,5,1,16,COMPLETE,223.037434,"{""classifier__alpha"": 0.0003450097441838016, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0007272237082808107}",44.574890,7.105605,0.030315,0.000495,0.990920,0.990334,0.991416,0.987994,0.990170,0.990167,0.001173,19
6,mlp,optuna,cicids2017,235490,30,5,1,6,COMPLETE,140.060363,"{""classifier__alpha"": 4.314041792135614e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0003396982571910356}",27.972669,2.201535,0.037458,0.000633,0.990628,0.989505,0.991178,0.989696,0.989452,0.990092,0.000689,20
8,mlp,optuna,cicids2017,235490,30,5,1,8,COMPLETE,85.625732,"{""classifier__alpha"": 0.006819998324673501, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0014897386352200294}",17.093351,2.570459,0.029767,0.000269,0.990326,0.989896,0.991195,0.988826,0.990139,0.990076,0.000763,21
12,mlp,optuna,cicids2017,235490,30,5,1,12,COMPLETE,72.709178,"{""classifier__alpha"": 2.104688149615943e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00851203095001293}",14.500655,3.064349,0.038903,0.001849,0.990591,0.989644,0.991258,0.989743,0.988803,0.990008,0.000843,22
10,mlp,optuna,cicids2017,235490,30,5,1,10,COMPLETE,353.309322,"{""classifier__alpha"": 0.001212494718830438, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00011090722889650909}",70.620614,9.509806,0.038963,0.001871,0.990719,0.988289,0.991111,0.989630,0.989374,0.989825,0.001005,23
3,mlp,optuna,cicids2017,235490,30,5,1,3,COMPLETE,129.872081,"{""classifier__alpha"": 3.232148147351273e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.005705385668376793}",25.943523,5.977293,0.028983,0.000724,0.988908,0.990366,0.988591,0.989803,0.989817,0.989497,0.000651,24
4,mlp,optuna,cicids2017,235490,30,5,1,4,COMPLETE,121.632655,"{""classifier__alpha"": 0.001146839870575158, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.004669295331523649}",24.301763,4.682678,0.022830,0.000175,0.990488,0.987370,0.991019,0.988456,0.986890,0.988845,0.001648,25
19,mlp,optuna,cicids2017,235490,30,5,1,19,COMPLETE,44.561325,"{""classifier__alpha"": 0.00032714665991783696, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0019500008020454666}",8.886893,2.990308,0.023134,0.001290,0.988824,0.987866,0.988682,0.985447,0.985297,0.987223,0.001547,26
2,mlp,optuna,cicids2017,235490,30,5,1,2,COMPLETE,94.453750,"{""classifier__alpha"": 0.0025248390936171007, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.008640187187029892}",18.859986,3.975109,0.028838,0.000153,0.988387,0.988052,0.986763,0.980423,0.988979,0.986521,0.003134,27
0,mlp,optuna,cicids2017,235490,30,5,1,0,COMPLETE,169.334053,"{""classifier__alpha"": 2.7559267640273738e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0001529949829431265}",33.836052,2.533895,0.028831,0.000561,0.986785,0.986683,0.987202,0.985304,0.985790,0.986353,0.000697,28
9,mlp,optuna,cicids2017,235490,30,5,1,9,COMPLETE,56.786948,"{""classifier__alpha"": 0.006060741222490684, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0004960571565137328}",11.326840,2.155720,0.028604,0.000535,0.986787,0.986749,0.986612,0.985115,0.985659,0.986184,0.000676,29
5,mlp,optuna,cicids2017,235490,30,5,1,5,COMPLETE,38.203894,"{""classifier__alpha"": 2.0402247877617882e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0007866599720665551}",7.616162,1.980743,0.022589,0.000326,0.986318,0.986259,0.986086,0.985414,0.984627,0.985741,0.000643,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,mlp,optuna,cicids2017,235490,30,5,1,1,58.008039,0.082586,0.977465,0.994692,0.986003,0.998667,0.994267,0.996462,0.991233,0.994352,0.994479
1,mlp,optuna,cicids2017,235490,30,5,1,2,59.917186,0.080243,0.978043,0.993099,0.985513,0.998268,0.994427,0.996344,0.990929,0.994161,0.993763
2,mlp,optuna,cicids2017,235490,30,5,1,3,56.694990,0.081787,0.981027,0.993524,0.987236,0.998376,0.995196,0.996783,0.992010,0.994862,0.994360
3,mlp,optuna,cicids2017,235490,30,5,1,4,46.685103,0.083504,0.978536,0.992144,0.985293,0.998029,0.994559,0.996291,0.990792,0.994076,0.993352
4,mlp,optuna,cicids2017,235490,30,5,1,5,60.877782,0.078973,0.977121,0.992887,0.984941,0.998215,0.994188,0.996197,0.990569,0.993928,0.993538

Modelo: mlp | origem do treinamento: unsw_nb15

[I 2026-10-12 07:06:30,611] A new study created in memory with name: mlp_unsw_nb15
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:12:07,590] Trial 0 finished with value: 0.9782068949784056 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 2.7559267640273738e-05, 'classifier__learning_rate_init': 0.0001529949829431265, 'classifier__early_stopping': False}. Best is trial 0 with value: 0.9782068949784056.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:14:32,063] Trial 1 finished with value: 0.9771251336281166 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 4.105412016858889e-05, 'classifier__learning_rate_init': 0.005704727088203684, 'classifier__early_stopping': False}. Best is trial 0 with value: 0.9782068949784056.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:16:38,214] Trial 2 finished with value: 0.9782528845248081 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 0.0025248390936171007, 'classifier__learning_rate_init': 0.008640187187029892, 'classifier__early_stopping': False}. Best is trial 2 with value: 0.9782528845248081.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:19:00,290] Trial 3 finished with value: 0.9790453274568 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 3.232148147351273e-05, 'classifier__learning_rate_init': 0.005705385668376793, 'classifier__early_stopping': False}. Best is trial 3 with value: 0.9790453274568.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:21:07,256] Trial 4 finished with value: 0.9788135109473263 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 0.001146839870575158, 'classifier__learning_rate_init': 0.004669295331523649, 'classifier__early_stopping': False}. Best is trial 3 with value: 0.9790453274568.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:22:44,557] Trial 5 finished with value: 0.9783875894026357 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 2.0402247877617882e-05, 'classifier__learning_rate_init': 0.0007866599720665551, 'classifier__early_stopping': True}. Best is trial 3 with value: 0.9790453274568.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:25:08,933] Trial 6 finished with value: 0.9792252535256857 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 4.314041792135614e-05, 'classifier__learning_rate_init': 0.0003396982571910356, 'classifier__early_stopping': True}. Best is trial 6 with value: 0.9792252535256857.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:26:58,457] Trial 7 finished with value: 0.979186890498702 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 2.027698063881496e-05, 'classifier__learning_rate_init': 0.0006731501945399556, 'classifier__early_stopping': True}. Best is trial 6 with value: 0.9792252535256857.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:28:06,145] Trial 8 finished with value: 0.979163334561064 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 0.006819998324673501, 'classifier__learning_rate_init': 0.0014897386352200294, 'classifier__early_stopping': True}. Best is trial 6 with value: 0.9792252535256857.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:29:56,475] Trial 9 finished with value: 0.9716470733391354 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 0.006060741222490684, 'classifier__learning_rate_init': 0.0004960571565137328, 'classifier__early_stopping': True}. Best is trial 6 with value: 0.9792252535256857.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:31:57,071] Trial 10 finished with value: 0.9780537997292486 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00014007753529570927, 'classifier__learning_rate_init': 0.0002073795587005078, 'classifier__early_stopping': True}. Best is trial 6 with value: 0.9792252535256857.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:33:37,562] Trial 11 finished with value: 0.97944897126738 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 3.113226289948056e-05, 'classifier__learning_rate_init': 0.0021585454565860055, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:35:07,919] Trial 12 finished with value: 0.9790776273898949 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.7472428046879254e-05, 'classifier__learning_rate_init': 0.0038830128806495254, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:36:16,485] Trial 13 finished with value: 0.9790577668439578 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 0.000395555142387354, 'classifier__learning_rate_init': 0.003205419729242539, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:37:48,540] Trial 14 finished with value: 0.9792367819164174 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00013713038633857472, 'classifier__learning_rate_init': 0.0016168403857357077, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:41:03,462] Trial 15 finished with value: 0.9791820177168059 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00013138517730208995, 'classifier__learning_rate_init': 0.0016987402644247811, 'classifier__early_stopping': False}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:42:31,337] Trial 16 finished with value: 0.9791540910203679 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 6.69451671737246e-05, 'classifier__learning_rate_init': 0.002534206491180696, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:44:11,114] Trial 17 finished with value: 0.9791501752277287 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0001577870773319174, 'classifier__learning_rate_init': 0.0009079639175648353, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:45:22,633] Trial 18 finished with value: 0.9784757761389408 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 1.8235548708515244e-05, 'classifier__learning_rate_init': 0.0015603026018076024, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:46:41,953] Trial 19 finished with value: 0.978929969440018 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00023415913471651787, 'classifier__learning_rate_init': 0.005305170569420419, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:47:55,490] Trial 20 finished with value: 0.9789853673147715 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0005499731279461089, 'classifier__learning_rate_init': 0.001969142735083541, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:49:57,839] Trial 21 finished with value: 0.9558147413124406 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 5.9628366901784513e-05, 'classifier__learning_rate_init': 0.00028682163257282044, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:52:49,865] Trial 22 finished with value: 0.9785567942598211 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.3126896815404588e-05, 'classifier__learning_rate_init': 0.0001395933450467029, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:55:21,648] Trial 23 finished with value: 0.9788688751826715 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 3.338579184079967e-05, 'classifier__learning_rate_init': 0.00021026636166940254, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:56:35,370] Trial 24 finished with value: 0.9791104858803733 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 4.847759254039833e-05, 'classifier__learning_rate_init': 0.0012588481283504053, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:58:20,194] Trial 25 finished with value: 0.9793750350771104 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.0568447573678146e-05, 'classifier__learning_rate_init': 0.0017319826119671288, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 07:59:15,062] Trial 26 finished with value: 0.9786270688149443 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 1.3921199961241151e-05, 'classifier__learning_rate_init': 0.006787045806667581, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:00:58,923] Trial 27 finished with value: 0.9791526523162657 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00047526393348488647, 'classifier__learning_rate_init': 0.0007789167906835796, 'classifier__early_stopping': True}. Best is trial 11 with value: 0.97944897126738.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
11,mlp,optuna,unsw_nb15,235490,30,5,1,11,COMPLETE,100.490093,"{""classifier__alpha"": 3.113226289948056e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0021585454565860055}",20.057236,7.201215,0.038491,0.001774,0.980252,0.980259,0.978716,0.978468,0.979549,0.979449,0.000750,1
29,mlp,optuna,unsw_nb15,235490,30,5,1,29,COMPLETE,104.083642,"{""classifier__alpha"": 1.1940920303115686e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0016341803125843341}",20.774989,2.331725,0.039409,0.001031,0.980330,0.980356,0.978622,0.978482,0.979159,0.979390,0.000811,2
25,mlp,optuna,unsw_nb15,235490,30,5,1,25,COMPLETE,104.822976,"{""classifier__alpha"": 1.0568447573678146e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0017319826119671288}",20.923577,3.210605,0.038767,0.000563,0.980246,0.979956,0.979105,0.978674,0.978895,0.979375,0.000615,3
28,mlp,optuna,unsw_nb15,235490,30,5,1,28,COMPLETE,105.984621,"{""classifier__alpha"": 1.088812620201685e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0017613068895268977}",21.155297,7.350442,0.039354,0.000722,0.980542,0.980343,0.977904,0.978699,0.979181,0.979334,0.000995,4
14,mlp,optuna,unsw_nb15,235490,30,5,1,14,COMPLETE,92.054007,"{""classifier__alpha"": 0.00013713038633857472, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0016168403857357077}",18.370511,4.942979,0.038002,0.000670,0.980195,0.979758,0.978250,0.978429,0.979553,0.979237,0.000763,5
6,mlp,optuna,unsw_nb15,235490,30,5,1,6,COMPLETE,144.375556,"{""classifier__alpha"": 4.314041792135614e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0003396982571910356}",28.835528,2.917531,0.037631,0.000702,0.980195,0.980169,0.978446,0.978316,0.979001,0.979225,0.000814,6
7,mlp,optuna,unsw_nb15,235490,30,5,1,7,COMPLETE,109.522734,"{""classifier__alpha"": 2.027698063881496e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0006731501945399556}",21.865027,5.310509,0.037558,0.000584,0.980649,0.980038,0.978030,0.978190,0.979028,0.979187,0.001022,7
15,mlp,optuna,unsw_nb15,235490,30,5,1,15,COMPLETE,194.921414,"{""classifier__alpha"": 0.00013138517730208995, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0016987402644247811}",38.944304,22.422439,0.037699,0.000656,0.979646,0.980353,0.979249,0.979132,0.977529,0.979182,0.000930,8
8,mlp,optuna,unsw_nb15,235490,30,5,1,8,COMPLETE,67.687476,"{""classifier__alpha"": 0.006819998324673501, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0014897386352200294}",13.505448,1.991298,0.030084,0.000540,0.979820,0.980158,0.978376,0.978403,0.979059,0.979163,0.000725,9
16,mlp,optuna,unsw_nb15,235490,30,5,1,16,COMPLETE,87.874896,"{""classifier__alpha"": 6.69451671737246e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.002534206491180696}",17.534572,3.304886,0.038141,0.000831,0.980045,0.979871,0.978587,0.978004,0.979263,0.979154,0.000770,10
27,mlp,optuna,unsw_nb15,235490,30,5,1,27,COMPLETE,103.860135,"{""classifier__alpha"": 0.00047526393348488647, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0007789167906835796}",20.730740,3.140360,0.038966,0.000627,0.979950,0.979878,0.978334,0.978486,0.979116,0.979153,0.000675,11
17,mlp,optuna,unsw_nb15,235490,30,5,1,17,COMPLETE,99.776291,"{""classifier__alpha"": 0.0001577870773319174, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0009079639175648353}",19.914009,5.602418,0.038938,0.000870,0.979970,0.979968,0.978391,0.978667,0.978755,0.979150,0.000679,12
24,mlp,optuna,unsw_nb15,235490,30,5,1,24,COMPLETE,73.722469,"{""classifier__alpha"": 4.847759254039833e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0012588481283504053}",14.711725,3.135885,0.030522,0.000607,0.979692,0.980102,0.978394,0.978331,0.979032,0.979110,0.000700,13
12,mlp,optuna,unsw_nb15,235490,30,5,1,12,COMPLETE,90.356176,"{""classifier__alpha"": 1.7472428046879254e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0038830128806495254}",18.031262,3.262809,0.037738,0.000585,0.979770,0.979855,0.978752,0.977999,0.979012,0.979078,0.000687,14
13,mlp,optuna,unsw_nb15,235490,30,5,1,13,COMPLETE,68.565823,"{""classifier__alpha"": 0.000395555142387354, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.003205419729242539}",13.679941,1.885464,0.030913,0.000425,0.980232,0.979521,0.978379,0.978639,0.978517,0.979058,0.000710,15
3,mlp,optuna,unsw_nb15,235490,30,5,1,3,COMPLETE,142.075742,"{""classifier__alpha"": 3.232148147351273e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.005705385668376793}",28.384526,4.940745,0.028709,0.000372,0.980113,0.979895,0.979097,0.977030,0.979091,0.979045,0.001089,16
20,mlp,optuna,unsw_nb15,235490,30,5,1,20,COMPLETE,73.536090,"{""classifier__alpha"": 0.0005499731279461089, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.001969142735083541}",14.666276,2.695197,0.038702,0.000536,0.980158,0.979713,0.977385,0.978413,0.979259,0.978985,0.000987,17
19,mlp,optuna,unsw_nb15,235490,30,5,1,19,COMPLETE,79.319782,"{""classifier__alpha"": 0.00023415913471651787, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.005305170569420419}",15.823396,4.397605,0.038290,0.000335,0.979710,0.979298,0.978835,0.978562,0.978245,0.978930,0.000521,18
23,mlp,optuna,unsw_nb15,235490,30,5,1,23,COMPLETE,151.782306,"{""classifier__alpha"": 3.338579184079967e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00021026636166940254}",30.315472,4.639572,0.038640,0.000451,0.979800,0.979870,0.978160,0.978127,0.978388,0.978869,0.000794,19
4,mlp,optuna,unsw_nb15,235490,30,5,1,4,COMPLETE,126.964935,"{""classifier__alpha"": 0.001146839870575158, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.004669295331523649}",25.368040,3.644752,0.022954,0.000179,0.980317,0.979601,0.978476,0.977621,0.978053,0.978814,0.000999,20
26,mlp,optuna,unsw_nb15,235490,30,5,1,26,COMPLETE,54.867652,"{""classifier__alpha"": 1.3921199961241151e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.006787045806667581}",10.941722,2.864551,0.029475,0.000718,0.980024,0.979799,0.978549,0.977734,0.977030,0.978627,0.001156,21
22,mlp,optuna,unsw_nb15,235490,30,5,1,22,COMPLETE,172.025670,"{""classifier__alpha"": 1.3126896815404588e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0001395933450467029}",34.363974,8.403809,0.038870,0.000606,0.979571,0.979327,0.977547,0.978441,0.977899,0.978557,0.000786,22
18,mlp,optuna,unsw_nb15,235490,30,5,1,18,COMPLETE,71.518711,"{""classifier__alpha"": 1.8235548708515244e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0015603026018076024}",14.272008,1.558981,0.029476,0.000408,0.979355,0.979564,0.977604,0.978015,0.977840,0.978476,0.000817,23
5,mlp,optuna,unsw_nb15,235490,30,5,1,5,COMPLETE,97.300986,"{""classifier__alpha"": 2.0402247877617882e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0007866599720665551}",19.435367,2.171151,0.022897,0.000428,0.979225,0.979116,0.978015,0.977480,0.978102,0.978388,0.000675,24
2,mlp,optuna,unsw_nb15,235490,30,5,1,2,COMPLETE,126.150997,"{""classifier__alpha"": 0.0025248390936171007, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.008640187187029892}",25.199271,8.129240,0.028971,0.000362,0.979279,0.979281,0.978316,0.976027,0.978361,0.978253,0.001190,25
0,mlp,optuna,unsw_nb15,235490,30,5,1,0,COMPLETE,336.976040,"{""classifier__alpha"": 2.7559267640273738e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0001529949829431265}",67.364484,0.116161,0.028811,0.000316,0.978577,0.978757,0.977792,0.977790,0.978118,0.978207,0.000398,26
10,mlp,optuna,unsw_nb15,235490,30,5,1,10,COMPLETE,120.595587,"{""classifier__alpha"": 0.00014007753529570927, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0002073795587005078}",24.079249,5.735494,0.037580,0.000517,0.976804,0.979692,0.977740,0.978316,0.977717,0.978054,0.000952,27
1,mlp,optuna,unsw_nb15,235490,30,5,1,1,COMPLETE,144.472392,"{""classifier__alpha"": 4.105412016858889e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.005704727088203684}",28.854211,10.451580,0.038268,0.000582,0.979546,0.980075,0.978655,0.978324,0.969025,0.977125,0.004097,28
9,mlp,optuna,unsw_nb15,235490,30,5,1,9,COMPLETE,110.330207,"{""classifier__alpha"": 0.006060741222490684, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0004960571565137328}",22.035383,2.742184,0.028716,0.000112,0.977141,0.978425,0.952150,0.974597,0.975922,0.971647,0.009831,29
21,mlp,optuna,unsw_nb15,235490,30,5,1,21,COMPLETE,122.348070,"{""classifier__alpha"": 5.9628366901784513e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.00028682163257282044}",24.444134,9.671954,0.023197,0.000159,0.937186,0.953273,0.976000,0.975749,0.936865,0.955815,0.017421,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,mlp,optuna,unsw_nb15,235490,30,5,1,1,22.692836,0.097120,0.942607,0.995647,0.968401,0.998896,0.984846,0.991821,0.980111,0.987006,0.990246
1,mlp,optuna,unsw_nb15,235490,30,5,1,2,19.685520,0.088518,0.941897,0.996496,0.968428,0.999111,0.984633,0.991819,0.980124,0.987006,0.990565
2,mlp,optuna,unsw_nb15,235490,30,5,1,3,20.226581,0.080786,0.936914,0.997983,0.966485,0.999487,0.983200,0.991277,0.978881,0.986157,0.990591
3,mlp,optuna,unsw_nb15,235490,30,5,1,4,19.849839,0.081986,0.938081,0.995541,0.965958,0.998868,0.983571,0.991161,0.978559,0.985965,0.989556
4,mlp,optuna,unsw_nb15,235490,30,5,1,5,29.584872,0.079291,0.937831,0.997665,0.966823,0.999407,0.983465,0.991372,0.979097,0.986305,0.990565

Modelo: mlp | origem do treinamento: iot23

[I 2026-10-12 08:05:20,621] A new study created in memory with name: mlp_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:06:12,125] Trial 0 finished with value: 0.9969581623317489 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 2.7559267640273738e-05, 'classifier__learning_rate_init': 0.0001529949829431265, 'classifier__early_stopping': False}. Best is trial 0 with value: 0.9969581623317489.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:08:03,283] Trial 1 finished with value: 0.9972646681732604 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 4.105412016858889e-05, 'classifier__learning_rate_init': 0.005704727088203684, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9972646681732604.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:08:47,796] Trial 2 finished with value: 0.9968718286501964 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 0.0025248390936171007, 'classifier__learning_rate_init': 0.008640187187029892, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9972646681732604.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:10:05,509] Trial 3 finished with value: 0.9971577545883598 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 3.232148147351273e-05, 'classifier__learning_rate_init': 0.005705385668376793, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9972646681732604.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:10:39,643] Trial 4 finished with value: 0.9970976715497338 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 0.001146839870575158, 'classifier__learning_rate_init': 0.004669295331523649, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9972646681732604.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:11:04,208] Trial 5 finished with value: 0.9970644311266588 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 2.0402247877617882e-05, 'classifier__learning_rate_init': 0.0007866599720665551, 'classifier__early_stopping': True}. Best is trial 1 with value: 0.9972646681732604.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:11:57,065] Trial 6 finished with value: 0.9971440996789391 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 4.314041792135614e-05, 'classifier__learning_rate_init': 0.0003396982571910356, 'classifier__early_stopping': True}. Best is trial 1 with value: 0.9972646681732604.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:12:40,325] Trial 7 finished with value: 0.9971306755148639 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 2.027698063881496e-05, 'classifier__learning_rate_init': 0.0006731501945399556, 'classifier__early_stopping': True}. Best is trial 1 with value: 0.9972646681732604.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:13:14,298] Trial 8 finished with value: 0.9971042841036262 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 0.006819998324673501, 'classifier__learning_rate_init': 0.0014897386352200294, 'classifier__early_stopping': True}. Best is trial 1 with value: 0.9972646681732604.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:13:53,107] Trial 9 finished with value: 0.9969580824205408 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 0.006060741222490684, 'classifier__learning_rate_init': 0.0004960571565137328, 'classifier__early_stopping': True}. Best is trial 1 with value: 0.9972646681732604.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:15:07,694] Trial 10 finished with value: 0.997124062229355 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.001212494718830438, 'classifier__learning_rate_init': 0.00011090722889650909, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9972646681732604.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:16:03,116] Trial 11 finished with value: 0.9970971707893865 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 6.133096251366484e-05, 'classifier__learning_rate_init': 0.008160320573654392, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9972646681732604.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:18:04,762] Trial 12 finished with value: 0.9974911318410904 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 2.7776606537483853e-05, 'classifier__learning_rate_init': 0.0023724370736324927, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9974911318410904.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:20:24,595] Trial 13 finished with value: 0.9975716882540206 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.0145206295623886e-05, 'classifier__learning_rate_init': 0.002017977223065986, 'classifier__early_stopping': False}. Best is trial 13 with value: 0.9975716882540206.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:22:40,473] Trial 14 finished with value: 0.997651339626896 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 5.458181018581338e-05, 'classifier__learning_rate_init': 0.0016903876852460745, 'classifier__early_stopping': False}. Best is trial 14 with value: 0.997651339626896.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:23:16,591] Trial 15 finished with value: 0.9970842092833705 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00024351638261020753, 'classifier__learning_rate_init': 0.002521897059934058, 'classifier__early_stopping': True}. Best is trial 14 with value: 0.997651339626896.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:25:04,512] Trial 16 finished with value: 0.997451430929509 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00011766323084817951, 'classifier__learning_rate_init': 0.002338900809515618, 'classifier__early_stopping': False}. Best is trial 14 with value: 0.997651339626896.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:27:08,393] Trial 17 finished with value: 0.9973110475814749 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0002529435538455632, 'classifier__learning_rate_init': 0.0003470687035022395, 'classifier__early_stopping': False}. Best is trial 14 with value: 0.997651339626896.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:27:50,263] Trial 18 finished with value: 0.9971512332230269 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 1.3793344068282639e-05, 'classifier__learning_rate_init': 0.0016891938155335522, 'classifier__early_stopping': False}. Best is trial 14 with value: 0.997651339626896.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:28:28,056] Trial 19 finished with value: 0.9970641991966855 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.7876260791220345e-05, 'classifier__learning_rate_init': 0.004816854843482243, 'classifier__early_stopping': True}. Best is trial 14 with value: 0.997651339626896.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:30:48,640] Trial 20 finished with value: 0.9974383647745644 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 3.035801584178554e-05, 'classifier__learning_rate_init': 0.001078031851242188, 'classifier__early_stopping': False}. Best is trial 14 with value: 0.997651339626896.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:33:07,685] Trial 21 finished with value: 0.9973918595939345 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.8235063096376947e-05, 'classifier__learning_rate_init': 0.003519174825307502, 'classifier__early_stopping': False}. Best is trial 14 with value: 0.997651339626896.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:35:46,597] Trial 22 finished with value: 0.9976514608686916 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.2135528081866365e-05, 'classifier__learning_rate_init': 0.0006633669118179749, 'classifier__early_stopping': False}. Best is trial 22 with value: 0.9976514608686916.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:38:42,091] Trial 23 finished with value: 0.9975316506886667 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 7.392423337104901e-05, 'classifier__learning_rate_init': 0.0009100873396923754, 'classifier__early_stopping': False}. Best is trial 22 with value: 0.9976514608686916.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:40:40,270] Trial 24 finished with value: 0.9975250774748904 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.0901064988686686e-05, 'classifier__learning_rate_init': 0.0018335222574236496, 'classifier__early_stopping': False}. Best is trial 22 with value: 0.9976514608686916.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:41:27,395] Trial 25 finished with value: 0.997064815623275 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 0.00020640041637785323, 'classifier__learning_rate_init': 0.0007770516211140652, 'classifier__early_stopping': False}. Best is trial 22 with value: 0.9976514608686916.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:43:29,045] Trial 26 finished with value: 0.9973041959774591 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.4411015939522442e-05, 'classifier__learning_rate_init': 0.000290622060610244, 'classifier__early_stopping': False}. Best is trial 22 with value: 0.9976514608686916.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:44:30,328] Trial 27 finished with value: 0.9970581940236606 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 6.55521856607954e-05, 'classifier__learning_rate_init': 0.0016229073644207874, 'classifier__early_stopping': False}. Best is trial 22 with value: 0.9976514608686916.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:45:00,203] Trial 28 finished with value: 0.9970775623297723 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 7.927798117647116e-05, 'classifier__learning_rate_init': 0.003106551633963463, 'classifier__early_stopping': True}. Best is trial 22 with value: 0.9976514608686916.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:45:44,382] Trial 29 finished with value: 0.9971307095680484 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00011456128334247981, 'classifier__learning_rate_init': 0.0006139425402159046, 'classifier__early_stopping': True}. Best is trial 22 with value: 0.9976514608686916.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
22,mlp,optuna,iot23,235490,30,5,1,22,COMPLETE,158.911072,"{""classifier__alpha"": 1.2135528081866365e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0006633669118179749}",31.741409,9.410925,0.038548,0.000301,0.997972,0.997471,0.996670,0.998172,0.997972,0.997651,0.000543,1
14,mlp,optuna,iot23,235490,30,5,1,14,COMPLETE,135.878308,"{""classifier__alpha"": 5.458181018581338e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0016903876852460745}",27.134341,8.362179,0.039065,0.000364,0.998039,0.996603,0.997438,0.998205,0.997972,0.997651,0.000584,2
13,mlp,optuna,iot23,235490,30,5,1,13,COMPLETE,139.832246,"{""classifier__alpha"": 1.0145206295623886e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.002017977223065986}",27.924835,8.630917,0.039360,0.000748,0.997638,0.997471,0.997472,0.997272,0.998005,0.997572,0.000246,3
23,mlp,optuna,iot23,235490,30,5,1,23,COMPLETE,175.494027,"{""classifier__alpha"": 7.392423337104901e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0009100873396923754}",35.057005,1.941165,0.039489,0.000401,0.997873,0.997438,0.996737,0.998172,0.997438,0.997532,0.000485,4
24,mlp,optuna,iot23,235490,30,5,1,24,COMPLETE,118.177806,"{""classifier__alpha"": 1.0901064988686686e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0018335222574236496}",23.594072,6.341056,0.039241,0.000332,0.998039,0.996703,0.997439,0.998072,0.997372,0.997525,0.000504,5
12,mlp,optuna,iot23,235490,30,5,1,12,COMPLETE,121.645742,"{""classifier__alpha"": 2.7776606537483853e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0023724370736324927}",24.288099,8.495122,0.038795,0.000504,0.997972,0.996703,0.996670,0.998106,0.998005,0.997491,0.000658,6
16,mlp,optuna,iot23,235490,30,5,1,16,COMPLETE,107.920862,"{""classifier__alpha"": 0.00011766323084817951, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.002338900809515618}",21.542900,9.116104,0.039012,0.000519,0.997938,0.997438,0.996570,0.997305,0.998005,0.997451,0.000518,7
20,mlp,optuna,iot23,235490,30,5,1,20,COMPLETE,140.584025,"{""classifier__alpha"": 3.035801584178554e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.001078031851242188}",28.075082,7.259969,0.039456,0.000919,0.997773,0.997305,0.996637,0.998106,0.997371,0.997438,0.000494,8
21,mlp,optuna,iot23,235490,30,5,1,21,COMPLETE,139.044343,"{""classifier__alpha"": 1.8235063096376947e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.003519174825307502}",27.767197,4.329715,0.039177,0.000590,0.997506,0.997272,0.996671,0.998106,0.997405,0.997392,0.000460,9
17,mlp,optuna,iot23,235490,30,5,1,17,COMPLETE,123.880118,"{""classifier__alpha"": 0.0002529435538455632, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0003470687035022395}",24.733923,12.515978,0.039806,0.001075,0.997738,0.996670,0.996737,0.998039,0.997371,0.997311,0.000540,10
26,mlp,optuna,iot23,235490,30,5,1,26,COMPLETE,121.650191,"{""classifier__alpha"": 1.4411015939522442e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.000290622060610244}",24.288950,10.829618,0.038788,0.000519,0.997738,0.996670,0.996670,0.997404,0.998038,0.997304,0.000555,11
1,mlp,optuna,iot23,235490,30,5,1,1,COMPLETE,111.157662,"{""classifier__alpha"": 4.105412016858889e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.005704727088203684}",22.189935,6.405154,0.039659,0.000416,0.997972,0.997004,0.996704,0.997239,0.997405,0.997265,0.000425,12
3,mlp,optuna,iot23,235490,30,5,1,3,COMPLETE,77.712083,"{""classifier__alpha"": 3.232148147351273e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.005705385668376793}",15.510667,8.091263,0.029801,0.000330,0.997572,0.996803,0.996704,0.997272,0.997438,0.997158,0.000345,13
18,mlp,optuna,iot23,235490,30,5,1,18,COMPLETE,41.870006,"{""classifier__alpha"": 1.3793344068282639e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0016891938155335522}",8.348598,2.912025,0.023165,0.000117,0.997672,0.996670,0.996637,0.997471,0.997305,0.997151,0.000422,14
6,mlp,optuna,iot23,235490,30,5,1,6,COMPLETE,52.856228,"{""classifier__alpha"": 4.314041792135614e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0003396982571910356}",10.529743,0.741829,0.038870,0.000600,0.997672,0.996669,0.996604,0.997438,0.997338,0.997144,0.000429,15
29,mlp,optuna,iot23,235490,30,5,1,29,COMPLETE,44.178740,"{""classifier__alpha"": 0.00011456128334247981, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0006139425402159046}",8.794124,0.631112,0.039362,0.000892,0.997672,0.996669,0.996670,0.997371,0.997272,0.997131,0.000399,16
7,mlp,optuna,iot23,235490,30,5,1,7,COMPLETE,43.259141,"{""classifier__alpha"": 2.027698063881496e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0006731501945399556}",8.610764,0.585466,0.039095,0.001402,0.997605,0.996669,0.996670,0.997404,0.997305,0.997131,0.000389,17
10,mlp,optuna,iot23,235490,30,5,1,10,COMPLETE,74.586466,"{""classifier__alpha"": 0.001212494718830438, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00011090722889650909}",14.875925,0.581397,0.039144,0.000381,0.997605,0.996636,0.996637,0.997405,0.997338,0.997124,0.000408,18
8,mlp,optuna,iot23,235490,30,5,1,8,COMPLETE,33.973079,"{""classifier__alpha"": 0.006819998324673501, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0014897386352200294}",6.761955,0.765253,0.030727,0.000262,0.997572,0.996669,0.996637,0.997405,0.997239,0.997104,0.000383,19
4,mlp,optuna,iot23,235490,30,5,1,4,COMPLETE,34.134194,"{""classifier__alpha"": 0.001146839870575158, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.004669295331523649}",6.801417,1.016678,0.023504,0.000203,0.997672,0.996536,0.996538,0.997339,0.997404,0.997098,0.000471,20
11,mlp,optuna,iot23,235490,30,5,1,11,COMPLETE,55.421108,"{""classifier__alpha"": 6.133096251366484e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.008160320573654392}",11.052327,1.873704,0.029646,0.000448,0.997738,0.996669,0.996637,0.997037,0.997405,0.997097,0.000425,21
15,mlp,optuna,iot23,235490,30,5,1,15,COMPLETE,36.116917,"{""classifier__alpha"": 0.00024351638261020753, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.002521897059934058}",7.182096,0.183938,0.039032,0.000495,0.997638,0.996537,0.996537,0.997371,0.997338,0.997084,0.000459,22
28,mlp,optuna,iot23,235490,30,5,1,28,COMPLETE,29.874557,"{""classifier__alpha"": 7.927798117647116e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.003106551633963463}",5.941759,0.547391,0.030894,0.000299,0.997672,0.996536,0.996603,0.997239,0.997338,0.997078,0.000439,23
25,mlp,optuna,iot23,235490,30,5,1,25,COMPLETE,47.124377,"{""classifier__alpha"": 0.00020640041637785323, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0007770516211140652}",9.392208,1.480054,0.030373,0.001038,0.997672,0.996736,0.996637,0.997438,0.996841,0.997065,0.000412,24
5,mlp,optuna,iot23,235490,30,5,1,5,COMPLETE,24.564642,"{""classifier__alpha"": 2.0402247877617882e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0007866599720665551}",4.888498,0.513120,0.022483,0.000262,0.997638,0.996703,0.996471,0.997239,0.997272,0.997064,0.000421,25
19,mlp,optuna,iot23,235490,30,5,1,19,COMPLETE,37.791862,"{""classifier__alpha"": 1.7876260791220345e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.004816854843482243}",7.517280,0.529778,0.038762,0.000577,0.997638,0.996570,0.996570,0.997238,0.997305,0.997064,0.000425,26
27,mlp,optuna,iot23,235490,30,5,1,27,COMPLETE,61.282291,"{""classifier__alpha"": 6.55521856607954e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0016229073644207874}",12.224443,2.614902,0.029657,0.000315,0.997738,0.996736,0.996637,0.997338,0.996841,0.997058,0.000417,27
0,mlp,optuna,iot23,235490,30,5,1,0,COMPLETE,51.501103,"{""classifier__alpha"": 2.7559267640273738e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0001529949829431265}",10.268475,0.542851,0.029746,0.000628,0.997372,0.996669,0.996438,0.997272,0.997040,0.996958,0.000355,28
9,mlp,optuna,iot23,235490,30,5,1,9,COMPLETE,38.808067,"{""classifier__alpha"": 0.006060741222490684, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0004960571565137328}",7.730642,1.336923,0.029044,0.000221,0.997638,0.996603,0.996504,0.997105,0.996940,0.996958,0.000404,29
2,mlp,optuna,iot23,235490,30,5,1,2,COMPLETE,44.512132,"{""classifier__alpha"": 0.0025248390936171007, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.008640187187029892}",8.870695,0.442122,0.029814,0.000230,0.997506,0.996469,0.996437,0.997272,0.996675,0.996872,0.000436,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,mlp,optuna,iot23,235490,30,5,1,1,37.435904,0.083939,0.999253,0.994267,0.996754,0.998569,0.999814,0.999191,0.997972,0.998705,0.997041
1,mlp,optuna,iot23,235490,30,5,1,2,37.862546,0.080257,0.999893,0.992037,0.995950,0.998013,0.999973,0.998992,0.997471,0.998386,0.996005
2,mlp,optuna,iot23,235490,30,5,1,3,14.168409,0.105669,0.999678,0.989703,0.994666,0.997432,0.999920,0.998675,0.996670,0.997877,0.994812
3,mlp,optuna,iot23,235490,30,5,1,4,35.626046,0.081889,0.999680,0.994480,0.997073,0.998622,0.999920,0.999271,0.998172,0.998832,0.997200
4,mlp,optuna,iot23,235490,30,5,1,5,39.030467,0.079854,0.999680,0.993843,0.996753,0.998463,0.999920,0.999191,0.997972,0.998705,0.996882

Modelo: mlp | origem do treinamento: cicids2017_unsw_nb15

[I 2026-10-12 08:47:13,204] A new study created in memory with name: mlp_cicids2017_unsw_nb15
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 08:58:39,817] Trial 0 finished with value: 0.9634912112720274 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 2.7559267640273738e-05, 'classifier__learning_rate_init': 0.0001529949829431265, 'classifier__early_stopping': False}. Best is trial 0 with value: 0.9634912112720274.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 09:04:00,693] Trial 1 finished with value: 0.9791080204127969 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 4.105412016858889e-05, 'classifier__learning_rate_init': 0.005704727088203684, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9791080204127969.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 09:08:46,079] Trial 2 finished with value: 0.9726635185927149 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 0.0025248390936171007, 'classifier__learning_rate_init': 0.008640187187029892, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9791080204127969.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 09:14:08,418] Trial 3 finished with value: 0.9795571574823635 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 3.232148147351273e-05, 'classifier__learning_rate_init': 0.005705385668376793, 'classifier__early_stopping': False}. Best is trial 3 with value: 0.9795571574823635.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 09:18:47,025] Trial 4 finished with value: 0.9764886264976752 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 0.001146839870575158, 'classifier__learning_rate_init': 0.004669295331523649, 'classifier__early_stopping': False}. Best is trial 3 with value: 0.9795571574823635.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 09:21:09,675] Trial 5 finished with value: 0.9608872464387727 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 2.0402247877617882e-05, 'classifier__learning_rate_init': 0.0007866599720665551, 'classifier__early_stopping': True}. Best is trial 3 with value: 0.9795571574823635.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 09:25:48,051] Trial 6 finished with value: 0.9795597971817497 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 4.314041792135614e-05, 'classifier__learning_rate_init': 0.0003396982571910356, 'classifier__early_stopping': True}. Best is trial 6 with value: 0.9795597971817497.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 09:29:11,381] Trial 7 finished with value: 0.9795784415059273 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 2.027698063881496e-05, 'classifier__learning_rate_init': 0.0006731501945399556, 'classifier__early_stopping': True}. Best is trial 7 with value: 0.9795784415059273.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 09:31:25,303] Trial 8 finished with value: 0.9783498185287733 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 0.006819998324673501, 'classifier__learning_rate_init': 0.0014897386352200294, 'classifier__early_stopping': True}. Best is trial 7 with value: 0.9795784415059273.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 09:34:56,061] Trial 9 finished with value: 0.9611668468578352 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 0.006060741222490684, 'classifier__learning_rate_init': 0.0004960571565137328, 'classifier__early_stopping': True}. Best is trial 7 with value: 0.9795784415059273.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 09:38:13,488] Trial 10 finished with value: 0.9810820652786534 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0002268369562074097, 'classifier__learning_rate_init': 0.003106652368459398, 'classifier__early_stopping': True}. Best is trial 10 with value: 0.9810820652786534.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 09:40:44,843] Trial 11 finished with value: 0.9791994431322003 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00026354180609780965, 'classifier__learning_rate_init': 0.00558156246838305, 'classifier__early_stopping': True}. Best is trial 10 with value: 0.9810820652786534.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 09:50:14,432] Trial 12 finished with value: 0.9816306997899329 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 2.3938152498123657e-05, 'classifier__learning_rate_init': 0.0015530817719481575, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9816306997899329.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 10:01:05,055] Trial 13 finished with value: 0.980636476576817 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.039138133731021e-05, 'classifier__learning_rate_init': 0.0013087415473890067, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9816306997899329.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 10:04:12,165] Trial 14 finished with value: 0.9797785322350553 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00027612292363419046, 'classifier__learning_rate_init': 0.0020705896396898114, 'classifier__early_stopping': True}. Best is trial 12 with value: 0.9816306997899329.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 10:14:29,014] Trial 15 finished with value: 0.9807211140614964 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 0.0001376665055165609, 'classifier__learning_rate_init': 0.0005043088345218804, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9816306997899329.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 10:22:45,268] Trial 16 finished with value: 0.9766843341327917 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00010394274613257715, 'classifier__learning_rate_init': 0.0021881506089849647, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9816306997899329.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 10:38:43,601] Trial 17 finished with value: 0.9822280465469447 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0004850777386828204, 'classifier__learning_rate_init': 0.0006809764960501163, 'classifier__early_stopping': False}. Best is trial 17 with value: 0.9822280465469447.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 10:51:32,887] Trial 18 finished with value: 0.9807442675858468 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0015492265118513975, 'classifier__learning_rate_init': 0.0005881009450040533, 'classifier__early_stopping': False}. Best is trial 17 with value: 0.9822280465469447.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 11:02:45,983] Trial 19 finished with value: 0.9814116181574264 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.002548805549334603, 'classifier__learning_rate_init': 0.0012112563605998039, 'classifier__early_stopping': False}. Best is trial 17 with value: 0.9822280465469447.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 11:15:59,203] Trial 20 finished with value: 0.9796170069932245 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00019791546840846534, 'classifier__learning_rate_init': 0.00019864791440100564, 'classifier__early_stopping': False}. Best is trial 17 with value: 0.9822280465469447.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 11:28:20,306] Trial 21 finished with value: 0.9797038449634448 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.007484923097934535, 'classifier__learning_rate_init': 0.00037888886800844433, 'classifier__early_stopping': False}. Best is trial 17 with value: 0.9822280465469447.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 11:36:40,465] Trial 22 finished with value: 0.9800557315357346 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0030952694277071244, 'classifier__learning_rate_init': 0.0018536712629932306, 'classifier__early_stopping': False}. Best is trial 17 with value: 0.9822280465469447.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 11:44:46,511] Trial 23 finished with value: 0.9803020439190414 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 0.000621786566623724, 'classifier__learning_rate_init': 0.0009321298913909612, 'classifier__early_stopping': False}. Best is trial 17 with value: 0.9822280465469447.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 11:51:27,918] Trial 24 finished with value: 0.977188883731993 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.3777139047074268e-05, 'classifier__learning_rate_init': 0.005502469400306589, 'classifier__early_stopping': False}. Best is trial 17 with value: 0.9822280465469447.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 12:03:45,197] Trial 25 finished with value: 0.9808237618086434 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0014123734308424082, 'classifier__learning_rate_init': 0.00024159831008551582, 'classifier__early_stopping': False}. Best is trial 17 with value: 0.9822280465469447.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 12:20:43,991] Trial 26 finished with value: 0.9809884956560971 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 8.842763361156066e-05, 'classifier__learning_rate_init': 0.0007148975867052746, 'classifier__early_stopping': False}. Best is trial 17 with value: 0.9822280465469447.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
17,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,17,COMPLETE,958.332418,"{""classifier__alpha"": 0.0004850777386828204, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0006809764960501163}",191.588791,35.559315,0.074408,0.000794,0.983195,0.983251,0.984790,0.979940,0.979964,0.982228,0.001945,1
12,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,12,COMPLETE,569.587723,"{""classifier__alpha"": 2.3938152498123657e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0015530817719481575}",113.839668,17.766478,0.074551,0.002110,0.982986,0.980096,0.984072,0.982764,0.978235,0.981631,0.002143,2
19,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,19,COMPLETE,673.095952,"{""classifier__alpha"": 0.002548805549334603, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0012112563605998039}",134.541968,14.336525,0.073989,0.000592,0.982089,0.981711,0.981574,0.979267,0.982418,0.981412,0.001112,3
10,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,10,COMPLETE,197.426265,"{""classifier__alpha"": 0.0002268369562074097, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.003106652368459398}",39.407837,6.213545,0.074077,0.001378,0.981271,0.981648,0.981968,0.980997,0.979527,0.981082,0.000845,4
26,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,26,COMPLETE,1018.793288,"{""classifier__alpha"": 8.842763361156066e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0007148975867052746}",203.678708,27.621045,0.076392,0.003748,0.980424,0.981296,0.984687,0.980186,0.978349,0.980988,0.002083,5
25,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,25,COMPLETE,737.278581,"{""classifier__alpha"": 0.0014123734308424082, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00024159831008551582}",147.375491,32.508720,0.076641,0.002766,0.981736,0.981407,0.981260,0.980465,0.979250,0.980824,0.000891,6
18,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,18,COMPLETE,769.285398,"{""classifier__alpha"": 0.0015492265118513975, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0005881009450040533}",153.779595,21.607420,0.074191,0.000635,0.981921,0.979786,0.981885,0.980058,0.980072,0.980744,0.000951,7
15,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,15,COMPLETE,616.848072,"{""classifier__alpha"": 0.0001376665055165609, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0005043088345218804}",123.307887,22.129192,0.058459,0.000455,0.978854,0.980844,0.982035,0.982698,0.979174,0.980721,0.001519,8
13,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,13,COMPLETE,650.622282,"{""classifier__alpha"": 1.039138133731021e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0013087415473890067}",130.046257,43.434738,0.074910,0.002206,0.980695,0.978923,0.985080,0.979272,0.979213,0.980636,0.002305,9
29,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,29,COMPLETE,925.915766,"{""classifier__alpha"": 0.0004826779460016026, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00040579396989296444}",185.104241,24.349297,0.075556,0.000460,0.982069,0.976641,0.984641,0.976439,0.982188,0.980396,0.003280,10
23,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,23,COMPLETE,486.045861,"{""classifier__alpha"": 0.000621786566623724, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0009321298913909612}",97.146352,10.039779,0.059561,0.000707,0.978777,0.978784,0.981807,0.982713,0.979429,0.980302,0.001641,11
27,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,27,COMPLETE,439.546158,"{""classifier__alpha"": 0.00037513014982536397, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0015104884589028538}",87.826751,14.606404,0.078946,0.003870,0.979197,0.981940,0.981182,0.979916,0.979193,0.980286,0.001101,12
22,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,22,COMPLETE,500.158515,"{""classifier__alpha"": 0.0030952694277071244, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0018536712629932306}",99.951605,14.912174,0.076757,0.002574,0.978306,0.979266,0.980883,0.982816,0.979007,0.980056,0.001618,13
14,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,14,COMPLETE,187.109763,"{""classifier__alpha"": 0.00027612292363419046, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0020705896396898114}",37.344550,10.254688,0.074178,0.001276,0.980090,0.980171,0.980096,0.977642,0.980894,0.979779,0.001110,14
21,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,21,COMPLETE,741.102682,"{""classifier__alpha"": 0.007484923097934535, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00037888886800844433}",148.143060,17.981973,0.074199,0.000373,0.980629,0.976905,0.980488,0.978880,0.981617,0.979704,0.001652,15
28,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,28,COMPLETE,567.618080,"{""classifier__alpha"": 4.507927092283409e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0011535105453205413}",113.443610,31.053028,0.076206,0.000627,0.979003,0.979455,0.981783,0.975700,0.982406,0.979670,0.002375,16
20,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,20,COMPLETE,793.218798,"{""classifier__alpha"": 0.00019791546840846534, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00019864791440100564}",158.565915,25.687381,0.074540,0.000552,0.976700,0.977512,0.979685,0.981991,0.982197,0.979617,0.002247,17
7,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,7,COMPLETE,203.329304,"{""classifier__alpha"": 2.027698063881496e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0006731501945399556}",40.588547,5.705301,0.074403,0.001000,0.979943,0.980463,0.979459,0.979346,0.978682,0.979578,0.000598,18
6,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,6,COMPLETE,278.375930,"{""classifier__alpha"": 4.314041792135614e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0003396982571910356}",55.598253,12.966904,0.074025,0.000598,0.980947,0.978077,0.978578,0.980257,0.979941,0.979560,0.001069,19
3,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,3,COMPLETE,322.337941,"{""classifier__alpha"": 3.232148147351273e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.005705385668376793}",64.409489,12.308193,0.055196,0.000673,0.980093,0.979297,0.980407,0.980039,0.977949,0.979557,0.000883,20
11,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,11,COMPLETE,151.355416,"{""classifier__alpha"": 0.00026354180609780965, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00558156246838305}",30.193772,4.153412,0.074049,0.000561,0.980583,0.977418,0.980205,0.978393,0.979399,0.979199,0.001165,21
1,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,1,COMPLETE,320.875553,"{""classifier__alpha"": 4.105412016858889e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.005704727088203684}",64.097946,26.819939,0.074241,0.000779,0.980165,0.977849,0.980402,0.978062,0.979063,0.979108,0.001046,22
8,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,8,COMPLETE,133.921669,"{""classifier__alpha"": 0.006819998324673501, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0014897386352200294}",26.722945,7.561778,0.058431,0.000940,0.977613,0.976734,0.979918,0.979381,0.978103,0.978350,0.001161,23
24,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,24,COMPLETE,401.405936,"{""classifier__alpha"": 1.3777139047074268e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.005502469400306589}",80.203621,34.921228,0.074356,0.000793,0.980539,0.981936,0.966272,0.979715,0.977483,0.977189,0.005646,24
16,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,16,COMPLETE,496.253756,"{""classifier__alpha"": 0.00010394274613257715, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0021881506089849647}",99.172943,49.679475,0.074550,0.000936,0.978566,0.980730,0.979619,0.978456,0.966051,0.976684,0.005380,25
4,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,4,COMPLETE,278.606576,"{""classifier__alpha"": 0.001146839870575158, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.004669295331523649}",55.676870,4.861028,0.041556,0.000277,0.975366,0.976293,0.980376,0.974558,0.975851,0.976489,0.002027,26
2,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,2,COMPLETE,285.385684,"{""classifier__alpha"": 0.0025248390936171007, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.008640187187029892}",57.019233,13.290833,0.055012,0.000402,0.961422,0.978939,0.976940,0.971039,0.974978,0.972664,0.006197,27
0,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,0,COMPLETE,686.609944,"{""classifier__alpha"": 2.7559267640273738e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0001529949829431265}",137.264739,0.448726,0.054325,0.000266,0.964106,0.962796,0.965398,0.962521,0.962636,0.963491,0.001111,28
9,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,9,COMPLETE,210.756937,"{""classifier__alpha"": 0.006060741222490684, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0004960571565137328}",42.092007,12.807541,0.056232,0.003468,0.962020,0.960422,0.962728,0.957598,0.963067,0.961167,0.002003,29
5,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,5,COMPLETE,142.649075,"{""classifier__alpha"": 2.0402247877617882e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0007866599720665551}",28.485156,5.616600,0.041757,0.000241,0.961954,0.959904,0.962931,0.959533,0.960114,0.960887,0.001320,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,1,238.617570,0.188965,0.955099,0.990286,0.972374,0.997549,0.988362,0.992934,0.982654,0.988747,0.989324
1,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,2,180.662763,0.178154,0.946555,0.991878,0.968687,0.997945,0.986000,0.991937,0.980312,0.987176,0.988939
2,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,3,222.388085,0.173423,0.949921,0.994745,0.971817,0.998671,0.986889,0.992745,0.982281,0.988460,0.990817
3,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,4,197.590349,0.160653,0.946776,0.991401,0.968575,0.997825,0.986066,0.991911,0.980243,0.987133,0.988734
4,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,5,269.920298,0.147737,0.953349,0.993577,0.973047,0.998377,0.987844,0.993083,0.983065,0.988991,0.990711

Modelo: mlp | origem do treinamento: cicids2017_iot23

[I 2026-10-12 13:00:52,625] A new study created in memory with name: mlp_cicids2017_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 13:04:31,992] Trial 0 finished with value: 0.9823643485109755 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 2.7559267640273738e-05, 'classifier__learning_rate_init': 0.0001529949829431265, 'classifier__early_stopping': False}. Best is trial 0 with value: 0.9823643485109755.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 13:09:50,078] Trial 1 finished with value: 0.9910374289960195 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 4.105412016858889e-05, 'classifier__learning_rate_init': 0.005704727088203684, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9910374289960195.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 13:13:26,262] Trial 2 finished with value: 0.985639418363977 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 0.0025248390936171007, 'classifier__learning_rate_init': 0.008640187187029892, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9910374289960195.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 13:17:34,999] Trial 3 finished with value: 0.9914040791286609 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 3.232148147351273e-05, 'classifier__learning_rate_init': 0.005705385668376793, 'classifier__early_stopping': False}. Best is trial 3 with value: 0.9914040791286609.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 13:21:41,240] Trial 4 finished with value: 0.9877652253955939 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 0.001146839870575158, 'classifier__learning_rate_init': 0.004669295331523649, 'classifier__early_stopping': False}. Best is trial 3 with value: 0.9914040791286609.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 13:23:17,832] Trial 5 finished with value: 0.9826943816095621 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 2.0402247877617882e-05, 'classifier__learning_rate_init': 0.0007866599720665551, 'classifier__early_stopping': True}. Best is trial 3 with value: 0.9914040791286609.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 13:27:05,784] Trial 6 finished with value: 0.9898085267353262 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 4.314041792135614e-05, 'classifier__learning_rate_init': 0.0003396982571910356, 'classifier__early_stopping': True}. Best is trial 3 with value: 0.9914040791286609.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 13:30:29,061] Trial 7 finished with value: 0.9922432088647646 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 2.027698063881496e-05, 'classifier__learning_rate_init': 0.0006731501945399556, 'classifier__early_stopping': True}. Best is trial 7 with value: 0.9922432088647646.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 13:33:20,334] Trial 8 finished with value: 0.9919388327530297 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 0.006819998324673501, 'classifier__learning_rate_init': 0.0014897386352200294, 'classifier__early_stopping': True}. Best is trial 7 with value: 0.9922432088647646.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 13:35:04,244] Trial 9 finished with value: 0.9822522397882363 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 0.006060741222490684, 'classifier__learning_rate_init': 0.0004960571565137328, 'classifier__early_stopping': True}. Best is trial 7 with value: 0.9922432088647646.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 13:37:57,288] Trial 10 finished with value: 0.9921911352220587 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0002268369562074097, 'classifier__learning_rate_init': 0.003106652368459398, 'classifier__early_stopping': True}. Best is trial 7 with value: 0.9922432088647646.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 13:40:36,932] Trial 11 finished with value: 0.9922103630605873 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00026354180609780965, 'classifier__learning_rate_init': 0.00558156246838305, 'classifier__early_stopping': True}. Best is trial 7 with value: 0.9922432088647646.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 13:51:48,327] Trial 12 finished with value: 0.9927592668080537 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.000651771454524825, 'classifier__learning_rate_init': 0.0007903757689608092, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 14:05:17,231] Trial 13 finished with value: 0.9924808116592171 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0002340418770904872, 'classifier__learning_rate_init': 0.00030120104933275714, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 14:15:21,464] Trial 14 finished with value: 0.992307591292483 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0006330921062443028, 'classifier__learning_rate_init': 0.0006693617380881765, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 14:28:57,699] Trial 15 finished with value: 0.9923341735406368 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0002236990033639975, 'classifier__learning_rate_init': 0.0002607361408784249, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 14:38:26,555] Trial 16 finished with value: 0.9924196941024214 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0045595017004489286, 'classifier__learning_rate_init': 0.001485632161019749, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 14:46:04,488] Trial 17 finished with value: 0.9925013188592668 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0003797860334613739, 'classifier__learning_rate_init': 0.002028136139897803, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 14:53:27,480] Trial 18 finished with value: 0.9924869727864067 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0005252826060801501, 'classifier__learning_rate_init': 0.0021729207942837348, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 14:59:49,468] Trial 19 finished with value: 0.9926826631879923 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 8.129414907068952e-05, 'classifier__learning_rate_init': 0.0014947342429858473, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 15:05:52,936] Trial 20 finished with value: 0.9925646597120548 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 0.00012113761572823069, 'classifier__learning_rate_init': 0.002387140331528127, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 15:11:44,918] Trial 21 finished with value: 0.992512285463705 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 0.00010040098461646608, 'classifier__learning_rate_init': 0.001712248397357667, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 15:16:30,190] Trial 22 finished with value: 0.9910165586156469 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 1.1753003168228232e-05, 'classifier__learning_rate_init': 0.005478702079601365, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 15:20:02,803] Trial 23 finished with value: 0.9894684089787251 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 0.00010827609188334919, 'classifier__learning_rate_init': 0.005598788888984887, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 15:27:47,635] Trial 24 finished with value: 0.9925508335865845 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 0.00011239811406289498, 'classifier__learning_rate_init': 0.0009049310301562782, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 15:34:30,207] Trial 25 finished with value: 0.9924835582376895 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 1.1482649790433106e-05, 'classifier__learning_rate_init': 0.0012363228824589195, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 15:38:54,753] Trial 26 finished with value: 0.9926217486082372 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 5.450244620582474e-05, 'classifier__learning_rate_init': 0.0031019001131189724, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 15:51:25,749] Trial 27 finished with value: 0.9919801637750748 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.004511816648454064, 'classifier__learning_rate_init': 0.0003637877565454308, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9927592668080537.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 15:59:07,038] Trial 28 finished with value: 0.9927805613835895 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 3.159100296783887e-05, 'classifier__learning_rate_init': 0.001330341954755882, 'classifier__early_stopping': False}. Best is trial 28 with value: 0.9927805613835895.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 16:12:44,049] Trial 29 finished with value: 0.9928767668770957 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.1319686938423936e-05, 'classifier__learning_rate_init': 0.00040313765778780087, 'classifier__early_stopping': False}. Best is trial 29 with value: 0.9928767668770957.

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
29,mlp,optuna,cicids2017_iot23,470980,30,5,1,29,COMPLETE,817.010718,"{""classifier__alpha"": 1.1319686938423936e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00040313765778780087}",163.320411,13.806411,0.078052,0.000573,0.993485,0.992622,0.993599,0.991906,0.992772,0.992877,0.000618,1
28,mlp,optuna,cicids2017_iot23,470980,30,5,1,28,COMPLETE,461.288515,"{""classifier__alpha"": 3.159100296783887e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.001330341954755882}",92.176181,11.853597,0.077905,0.000548,0.992711,0.992528,0.993651,0.992825,0.992188,0.992781,0.000486,2
12,mlp,optuna,cicids2017_iot23,470980,30,5,1,12,COMPLETE,671.394374,"{""classifier__alpha"": 0.000651771454524825, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0007903757689608092}",134.201067,19.346193,0.074486,0.000402,0.993304,0.992214,0.993514,0.992552,0.992213,0.992759,0.000549,3
19,mlp,optuna,cicids2017_iot23,470980,30,5,1,19,COMPLETE,381.987915,"{""classifier__alpha"": 8.129414907068952e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0014947342429858473}",76.335134,14.922342,0.058834,0.000565,0.992788,0.992405,0.993824,0.992240,0.992155,0.992683,0.000611,4
26,mlp,optuna,cicids2017_iot23,470980,30,5,1,26,COMPLETE,264.545870,"{""classifier__alpha"": 5.450244620582474e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0031019001131189724}",52.844295,24.465242,0.061030,0.000314,0.992787,0.992224,0.993385,0.992284,0.992429,0.992622,0.000429,5
20,mlp,optuna,cicids2017_iot23,470980,30,5,1,20,COMPLETE,363.467522,"{""classifier__alpha"": 0.00012113761572823069, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.002387140331528127}",72.630135,9.745837,0.059987,0.001145,0.993306,0.992281,0.993268,0.992288,0.991681,0.992565,0.000629,6
24,mlp,optuna,cicids2017_iot23,470980,30,5,1,24,COMPLETE,464.831359,"{""classifier__alpha"": 0.00011239811406289498, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0009049310301562782}",92.902155,15.773604,0.060372,0.000143,0.992723,0.992589,0.993158,0.992350,0.991934,0.992551,0.000405,7
21,mlp,optuna,cicids2017_iot23,470980,30,5,1,21,COMPLETE,351.980793,"{""classifier__alpha"": 0.00010040098461646608, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.001712248397357667}",70.331646,12.462757,0.060665,0.000501,0.992595,0.992339,0.993206,0.992142,0.992280,0.992512,0.000377,8
17,mlp,optuna,cicids2017_iot23,470980,30,5,1,17,COMPLETE,457.931838,"{""classifier__alpha"": 0.0003797860334613739, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.002028136139897803}",91.506665,33.395389,0.076174,0.002186,0.992712,0.992426,0.992922,0.992321,0.992127,0.992501,0.000283,9
18,mlp,optuna,cicids2017_iot23,470980,30,5,1,18,COMPLETE,442.991557,"{""classifier__alpha"": 0.0005252826060801501, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0021729207942837348}",88.519377,13.125891,0.075184,0.000624,0.992841,0.992508,0.993321,0.992046,0.991719,0.992487,0.000567,10
25,mlp,optuna,cicids2017_iot23,470980,30,5,1,25,COMPLETE,402.571169,"{""classifier__alpha"": 1.1482649790433106e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0012363228824589195}",80.449503,14.737807,0.061057,0.000349,0.992909,0.992273,0.992704,0.992471,0.992061,0.992484,0.000301,11
13,mlp,optuna,cicids2017_iot23,470980,30,5,1,13,COMPLETE,808.903541,"{""classifier__alpha"": 0.0002340418770904872, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00030120104933275714}",161.699249,14.257219,0.077736,0.003568,0.991308,0.992504,0.993079,0.992722,0.992791,0.992481,0.000614,12
16,mlp,optuna,cicids2017_iot23,470980,30,5,1,16,COMPLETE,568.855969,"{""classifier__alpha"": 0.0045595017004489286, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.001485632161019749}",113.692693,5.416419,0.075077,0.000858,0.992987,0.991972,0.993117,0.992018,0.992006,0.992420,0.000518,13
15,mlp,optuna,cicids2017_iot23,470980,30,5,1,15,COMPLETE,816.234369,"{""classifier__alpha"": 0.0002236990033639975, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0002607361408784249}",163.166985,13.914941,0.076347,0.001572,0.992816,0.992090,0.993500,0.991042,0.992223,0.992334,0.000816,14
14,mlp,optuna,cicids2017_iot23,470980,30,5,1,14,COMPLETE,604.232076,"{""classifier__alpha"": 0.0006330921062443028, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0006693617380881765}",120.765454,28.987397,0.077255,0.001758,0.991420,0.992071,0.993016,0.992970,0.992061,0.992308,0.000607,15
7,mlp,optuna,cicids2017_iot23,470980,30,5,1,7,COMPLETE,203.275929,"{""classifier__alpha"": 2.027698063881496e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0006731501945399556}",40.575784,4.256266,0.076239,0.003198,0.992493,0.991825,0.992870,0.992152,0.991876,0.992243,0.000393,16
11,mlp,optuna,cicids2017_iot23,470980,30,5,1,11,COMPLETE,159.642595,"{""classifier__alpha"": 0.00026354180609780965, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00558156246838305}",31.850469,7.014179,0.074615,0.000589,0.992082,0.992124,0.992984,0.991952,0.991910,0.992210,0.000395,17
10,mlp,optuna,cicids2017_iot23,470980,30,5,1,10,COMPLETE,173.043695,"{""classifier__alpha"": 0.0002268369562074097, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.003106652368459398}",34.523701,7.237544,0.080780,0.004999,0.992528,0.991708,0.992641,0.992252,0.991826,0.992191,0.000371,18
27,mlp,optuna,cicids2017_iot23,470980,30,5,1,27,COMPLETE,750.994882,"{""classifier__alpha"": 0.004511816648454064, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0003637877565454308}",150.117050,13.678408,0.078295,0.000766,0.992317,0.990723,0.993217,0.991371,0.992273,0.991980,0.000858,19
8,mlp,optuna,cicids2017_iot23,470980,30,5,1,8,COMPLETE,171.272016,"{""classifier__alpha"": 0.006819998324673501, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0014897386352200294}",34.192658,8.007229,0.058748,0.000492,0.991686,0.991456,0.992655,0.991892,0.992005,0.991939,0.000404,20
3,mlp,optuna,cicids2017_iot23,470980,30,5,1,3,COMPLETE,248.737035,"{""classifier__alpha"": 3.232148147351273e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.005705385668376793}",49.688461,8.020652,0.055752,0.003655,0.990397,0.991295,0.992045,0.991784,0.991499,0.991404,0.000564,21
1,mlp,optuna,cicids2017_iot23,470980,30,5,1,1,COMPLETE,318.085390,"{""classifier__alpha"": 4.105412016858889e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.005704727088203684}",63.543210,16.945957,0.070786,0.000828,0.992757,0.985209,0.993238,0.992040,0.991943,0.991037,0.002953,22
22,mlp,optuna,cicids2017_iot23,470980,30,5,1,22,COMPLETE,285.271044,"{""classifier__alpha"": 1.1753003168228232e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.005478702079601365}",56.987355,18.998851,0.062627,0.002618,0.985756,0.992003,0.992970,0.992543,0.991811,0.991017,0.002662,23
6,mlp,optuna,cicids2017_iot23,470980,30,5,1,6,COMPLETE,227.952060,"{""classifier__alpha"": 4.314041792135614e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0003396982571910356}",45.511664,12.793362,0.075576,0.001727,0.992739,0.984904,0.989266,0.990377,0.991757,0.989809,0.002722,24
23,mlp,optuna,cicids2017_iot23,470980,30,5,1,23,COMPLETE,212.612495,"{""classifier__alpha"": 0.00010827609188334919, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.005598788888984887}",42.458160,7.583243,0.060606,0.000795,0.992565,0.991923,0.986360,0.984467,0.992027,0.989468,0.003372,25
4,mlp,optuna,cicids2017_iot23,470980,30,5,1,4,COMPLETE,246.240320,"{""classifier__alpha"": 0.001146839870575158, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.004669295331523649}",49.198333,7.237381,0.046507,0.005170,0.991177,0.990051,0.984744,0.983272,0.989582,0.987765,0.003146,26
2,mlp,optuna,cicids2017_iot23,470980,30,5,1,2,COMPLETE,216.183062,"{""classifier__alpha"": 0.0025248390936171007, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.008640187187029892}",43.178017,10.515268,0.055321,0.005369,0.983325,0.982661,0.989791,0.989742,0.982679,0.985639,0.003378,27
5,mlp,optuna,cicids2017_iot23,470980,30,5,1,5,COMPLETE,96.590912,"{""classifier__alpha"": 2.0402247877617882e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0007866599720665551}",19.270318,5.016112,0.044649,0.003531,0.982559,0.982274,0.983716,0.981939,0.982983,0.982694,0.000615,28
0,mlp,optuna,cicids2017_iot23,470980,30,5,1,0,COMPLETE,219.363376,"{""classifier__alpha"": 2.7559267640273738e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0001529949829431265}",43.817682,1.946489,0.052024,0.000400,0.982751,0.982476,0.982264,0.981777,0.982554,0.982364,0.000333,29
9,mlp,optuna,cicids2017_iot23,470980,30,5,1,9,COMPLETE,103.909884,"{""classifier__alpha"": 0.006060741222490684, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0004960571565137328}",20.719395,3.576308,0.059437,0.004365,0.982559,0.982593,0.983029,0.981723,0.981356,0.982252,0.000616,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,mlp,optuna,cicids2017_iot23,470980,30,5,1,1,168.386202,0.209848,0.982884,0.990710,0.986782,0.997673,0.995687,0.996679,0.991730,0.994692,0.993199
1,mlp,optuna,cicids2017_iot23,470980,30,5,1,2,150.746055,0.201867,0.986405,0.989861,0.988130,0.997463,0.996590,0.997026,0.992578,0.995244,0.993225
2,mlp,optuna,cicids2017_iot23,470980,30,5,1,3,177.073004,0.203447,0.988978,0.990658,0.989818,0.997663,0.997240,0.997452,0.993635,0.995923,0.993949
3,mlp,optuna,cicids2017_iot23,470980,30,5,1,4,138.546447,0.212815,0.981449,0.994108,0.987738,0.998522,0.995302,0.996910,0.992324,0.995063,0.994705
4,mlp,optuna,cicids2017_iot23,470980,30,5,1,5,184.681594,0.150847,0.987708,0.989490,0.988598,0.997371,0.996921,0.997146,0.992872,0.995435,0.993206

Modelo: mlp | origem do treinamento: unsw_nb15_iot23

[I 2026-10-12 16:19:00,695] A new study created in memory with name: mlp_unsw_nb15_iot23
C:\Users\valde\AppData\Local\Temp\ipykernel_18900\1500463012.py:14: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  search = OptunaSearchCV(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 16:30:26,647] Trial 0 finished with value: 0.9706027819556949 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 2.7559267640273738e-05, 'classifier__learning_rate_init': 0.0001529949829431265, 'classifier__early_stopping': False}. Best is trial 0 with value: 0.9706027819556949.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 16:39:19,513] Trial 1 finished with value: 0.9826923915890579 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 4.105412016858889e-05, 'classifier__learning_rate_init': 0.005704727088203684, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9826923915890579.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 16:43:19,072] Trial 2 finished with value: 0.9761202043026195 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 0.0025248390936171007, 'classifier__learning_rate_init': 0.008640187187029892, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9826923915890579.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 16:51:01,127] Trial 3 finished with value: 0.9819795044647377 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 3.232148147351273e-05, 'classifier__learning_rate_init': 0.005705385668376793, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9826923915890579.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 16:56:56,577] Trial 4 finished with value: 0.978618297557133 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 0.001146839870575158, 'classifier__learning_rate_init': 0.004669295331523649, 'classifier__early_stopping': False}. Best is trial 1 with value: 0.9826923915890579.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 16:58:38,072] Trial 5 finished with value: 0.9680878509952346 and parameters: {'classifier__hidden_layer_sizes': (50,), 'classifier__alpha': 2.0402247877617882e-05, 'classifier__learning_rate_init': 0.0007866599720665551, 'classifier__early_stopping': True}. Best is trial 1 with value: 0.9826923915890579.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 17:03:26,115] Trial 6 finished with value: 0.982254523373047 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 4.314041792135614e-05, 'classifier__learning_rate_init': 0.0003396982571910356, 'classifier__early_stopping': True}. Best is trial 1 with value: 0.9826923915890579.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 17:08:51,953] Trial 7 finished with value: 0.986268675202458 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 2.027698063881496e-05, 'classifier__learning_rate_init': 0.0006731501945399556, 'classifier__early_stopping': True}. Best is trial 7 with value: 0.986268675202458.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 17:12:02,538] Trial 8 finished with value: 0.9837510959986243 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 0.006819998324673501, 'classifier__learning_rate_init': 0.0014897386352200294, 'classifier__early_stopping': True}. Best is trial 7 with value: 0.986268675202458.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 17:14:05,427] Trial 9 finished with value: 0.9655649186575083 and parameters: {'classifier__hidden_layer_sizes': (100,), 'classifier__alpha': 0.006060741222490684, 'classifier__learning_rate_init': 0.0004960571565137328, 'classifier__early_stopping': True}. Best is trial 7 with value: 0.986268675202458.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 17:17:47,579] Trial 10 finished with value: 0.9861509935984725 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0002268369562074097, 'classifier__learning_rate_init': 0.003106652368459398, 'classifier__early_stopping': True}. Best is trial 7 with value: 0.986268675202458.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 17:22:16,328] Trial 11 finished with value: 0.9860407329572883 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00026354180609780965, 'classifier__learning_rate_init': 0.00558156246838305, 'classifier__early_stopping': True}. Best is trial 7 with value: 0.986268675202458.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 17:34:46,634] Trial 12 finished with value: 0.9871087806790513 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 2.3938152498123657e-05, 'classifier__learning_rate_init': 0.0015530817719481575, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9871087806790513.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 17:51:06,322] Trial 13 finished with value: 0.9866820232312883 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.0093906831204727e-05, 'classifier__learning_rate_init': 0.0003679441801609784, 'classifier__early_stopping': False}. Best is trial 12 with value: 0.9871087806790513.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 18:02:08,845] Trial 14 finished with value: 0.9871413046537574 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 3.256112690445746e-05, 'classifier__learning_rate_init': 0.0018998137387656493, 'classifier__early_stopping': False}. Best is trial 14 with value: 0.9871413046537574.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 18:12:16,246] Trial 15 finished with value: 0.9869677320380028 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 1.4799397827112744e-05, 'classifier__learning_rate_init': 0.002237897978596909, 'classifier__early_stopping': False}. Best is trial 14 with value: 0.9871413046537574.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 18:25:40,637] Trial 16 finished with value: 0.987250541995764 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00014032253527391072, 'classifier__learning_rate_init': 0.0011992765734976515, 'classifier__early_stopping': False}. Best is trial 16 with value: 0.987250541995764.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 18:40:13,293] Trial 17 finished with value: 0.9872047713901061 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0001607937524392821, 'classifier__learning_rate_init': 0.000702265245646305, 'classifier__early_stopping': False}. Best is trial 16 with value: 0.987250541995764.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 18:50:44,893] Trial 18 finished with value: 0.9865968810164528 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0003462497347007463, 'classifier__learning_rate_init': 0.0015359858946811776, 'classifier__early_stopping': False}. Best is trial 16 with value: 0.987250541995764.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 19:05:43,808] Trial 19 finished with value: 0.9865877612743841 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0002532224790291502, 'classifier__learning_rate_init': 0.00046735569122326116, 'classifier__early_stopping': False}. Best is trial 16 with value: 0.987250541995764.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 19:20:08,066] Trial 20 finished with value: 0.9870738991675081 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 5.9657131173950535e-05, 'classifier__learning_rate_init': 0.0005103768944370768, 'classifier__early_stopping': False}. Best is trial 16 with value: 0.987250541995764.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 19:36:53,388] Trial 21 finished with value: 0.9861754722066761 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0012798006892962349, 'classifier__learning_rate_init': 0.000234448270789972, 'classifier__early_stopping': False}. Best is trial 16 with value: 0.987250541995764.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 19:45:23,048] Trial 22 finished with value: 0.9866693851333164 and parameters: {'classifier__hidden_layer_sizes': (50, 50), 'classifier__alpha': 8.966893199547871e-05, 'classifier__learning_rate_init': 0.0008152134431245619, 'classifier__early_stopping': False}. Best is trial 16 with value: 0.987250541995764.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 19:52:10,780] Trial 23 finished with value: 0.9863484002347533 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 9.467844593983901e-05, 'classifier__learning_rate_init': 0.0032842924148969947, 'classifier__early_stopping': False}. Best is trial 16 with value: 0.987250541995764.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 20:08:03,231] Trial 24 finished with value: 0.9863787141281442 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.00021777275250267432, 'classifier__learning_rate_init': 0.00018858298743038365, 'classifier__early_stopping': False}. Best is trial 16 with value: 0.987250541995764.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 20:21:55,088] Trial 25 finished with value: 0.9871053698278255 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 0.0005135178799730877, 'classifier__learning_rate_init': 0.0008568360429358294, 'classifier__early_stopping': False}. Best is trial 16 with value: 0.987250541995764.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)
[I 2026-10-12 20:36:16,987] Trial 26 finished with value: 0.9875580370814188 and parameters: {'classifier__hidden_layer_sizes': (100, 50), 'classifier__alpha': 5.9276550057310775e-05, 'classifier__learning_rate_init': 0.0012247884215016809, 'classifier__early_stopping': False}. Best is trial 26 with value: 0.9875580370814188.
C:\tcc\network-ids-ml-generalization\.venv\Lib\site-packages\optuna_integration\sklearn\sklearn.py:275: FutureWarning: `optuna.terminator` module has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0.
  report_cross_validation_scores(trial, scores_list)

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,trial_number,trial_state,trial_duration_seconds,params,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro
26,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,26,COMPLETE,861.899120,"{""classifier__alpha"": 5.9276550057310775e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0012247884215016809}",172.300361,19.201066,0.076088,0.000422,0.987814,0.988034,0.987164,0.987246,0.987533,0.987558,0.000330,1
16,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,16,COMPLETE,804.390071,"{""classifier__alpha"": 0.00014032253527391072, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0011992765734976515}",160.798715,11.107416,0.075402,0.000595,0.987777,0.988100,0.986393,0.986939,0.987044,0.987251,0.000612,2
17,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,17,COMPLETE,872.655900,"{""classifier__alpha"": 0.0001607937524392821, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.000702265245646305}",174.451331,28.026665,0.076437,0.000742,0.987193,0.988104,0.987181,0.986311,0.987235,0.987205,0.000567,3
14,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,14,COMPLETE,662.522143,"{""classifier__alpha"": 3.256112690445746e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0018998137387656493}",132.425505,19.158467,0.075318,0.007110,0.986761,0.987684,0.987276,0.986740,0.987246,0.987141,0.000355,4
12,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,12,COMPLETE,750.305061,"{""classifier__alpha"": 2.3938152498123657e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0015530817719481575}",149.981978,17.150993,0.075336,0.000997,0.986767,0.987697,0.987004,0.987313,0.986764,0.987109,0.000356,5
25,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,25,COMPLETE,831.855937,"{""classifier__alpha"": 0.0005135178799730877, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0008568360429358294}",166.292122,38.069946,0.075348,0.000501,0.987085,0.987660,0.987535,0.986698,0.986549,0.987105,0.000440,6
20,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,20,COMPLETE,864.256914,"{""classifier__alpha"": 5.9657131173950535e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0005103768944370768}",172.773480,16.704137,0.074111,0.000375,0.987231,0.987637,0.987104,0.986323,0.987074,0.987074,0.000426,7
15,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,15,COMPLETE,607.400635,"{""classifier__alpha"": 1.4799397827112744e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.002237897978596909}",121.401092,28.861659,0.075314,0.002107,0.986784,0.987384,0.986194,0.987206,0.987272,0.986968,0.000437,8
27,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,27,COMPLETE,535.936696,"{""classifier__alpha"": 0.00010381567794947139, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.002097399883265077}",107.119792,2.708780,0.063922,0.007409,0.987632,0.987484,0.986871,0.985993,0.986436,0.986883,0.000619,9
13,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,13,COMPLETE,979.687099,"{""classifier__alpha"": 1.0093906831204727e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0003679441801609784}",195.863861,39.075967,0.070170,0.001014,0.987376,0.987548,0.985514,0.985747,0.987225,0.986682,0.000868,10
22,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,22,COMPLETE,509.659359,"{""classifier__alpha"": 8.966893199547871e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0008152134431245619}",101.869697,18.815284,0.058435,0.000521,0.986185,0.987888,0.986990,0.986824,0.985460,0.986669,0.000813,11
18,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,18,COMPLETE,631.598858,"{""classifier__alpha"": 0.0003462497347007463, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0015359858946811776}",126.239577,16.905575,0.076751,0.000381,0.987014,0.986993,0.987589,0.986353,0.985035,0.986597,0.000873,12
19,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,19,COMPLETE,898.914773,"{""classifier__alpha"": 0.0002532224790291502, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00046735569122326116}",179.703307,44.362796,0.076267,0.000900,0.986400,0.987433,0.985843,0.986185,0.987078,0.986588,0.000584,13
29,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,29,COMPLETE,362.273327,"{""classifier__alpha"": 0.00011456128334247981, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0006139425402159046}",72.374175,6.717627,0.076844,0.000535,0.986518,0.987064,0.986050,0.986679,0.986443,0.986551,0.000329,14
24,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,24,COMPLETE,952.450637,"{""classifier__alpha"": 0.00021777275250267432, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00018858298743038365}",190.410296,13.563501,0.075957,0.002163,0.986455,0.987706,0.985043,0.986184,0.986505,0.986379,0.000849,15
23,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,23,COMPLETE,407.731152,"{""classifier__alpha"": 9.467844593983901e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0032842924148969947}",81.468118,27.974895,0.074604,0.000475,0.987101,0.986883,0.986558,0.985858,0.985342,0.986348,0.000656,16
7,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,7,COMPLETE,325.837479,"{""classifier__alpha"": 2.027698063881496e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0006731501945399556}",65.086836,9.204808,0.077416,0.000623,0.986075,0.987705,0.985898,0.985641,0.986023,0.986269,0.000734,17
21,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,21,COMPLETE,1005.321540,"{""classifier__alpha"": 0.0012798006892962349, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.000234448270789972}",200.987314,38.495605,0.073551,0.000502,0.985997,0.987455,0.984943,0.986500,0.985982,0.986175,0.000816,18
10,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,10,COMPLETE,222.151646,"{""classifier__alpha"": 0.0002268369562074097, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.003106652368459398}",44.349462,8.558454,0.077189,0.000699,0.986361,0.986546,0.985671,0.986431,0.985746,0.986151,0.000367,19
11,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,11,COMPLETE,268.748319,"{""classifier__alpha"": 0.00026354180609780965, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00558156246838305}",53.669731,4.142053,0.076499,0.000935,0.985769,0.986563,0.986099,0.985613,0.986159,0.986041,0.000331,20
8,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,8,COMPLETE,190.583884,"{""classifier__alpha"": 0.006819998324673501, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50, 50], ""classifier__learning_rate_init"": 0.0014897386352200294}",38.050613,13.653423,0.062630,0.002982,0.984885,0.980666,0.985064,0.983761,0.984380,0.983751,0.001608,21
1,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,1,COMPLETE,532.865197,"{""classifier__alpha"": 4.105412016858889e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.005704727088203684}",106.491869,34.225288,0.078034,0.000568,0.987306,0.987346,0.985723,0.970729,0.982358,0.982692,0.006251,22
6,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,6,COMPLETE,288.042928,"{""classifier__alpha"": 4.314041792135614e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0003396982571910356}",57.526107,24.028088,0.079401,0.002353,0.981338,0.977925,0.986103,0.979908,0.985998,0.982255,0.003284,23
3,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,3,COMPLETE,462.054486,"{""classifier__alpha"": 3.232148147351273e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.005705385668376793}",92.349463,23.712666,0.058213,0.000742,0.985062,0.985257,0.985777,0.968707,0.985095,0.981980,0.006641,24
28,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,28,COMPLETE,532.276436,"{""classifier__alpha"": 4.661396974798939e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0012900991126154418}",106.407118,0.563548,0.044565,0.000685,0.979960,0.982584,0.980531,0.978476,0.982621,0.980834,0.001592,25
4,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,4,COMPLETE,355.448902,"{""classifier__alpha"": 0.001146839870575158, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.004669295331523649}",71.041131,14.748880,0.045501,0.002242,0.979906,0.981751,0.977031,0.977537,0.976866,0.978618,0.001909,26
2,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,2,COMPLETE,239.558628,"{""classifier__alpha"": 0.0025248390936171007, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.008640187187029892}",47.850526,5.896176,0.058025,0.000231,0.976216,0.977596,0.977745,0.975055,0.973990,0.976120,0.001449,27
0,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,0,COMPLETE,685.948606,"{""classifier__alpha"": 2.7559267640273738e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0001529949829431265}",137.128358,1.545831,0.058252,0.000735,0.978067,0.966731,0.966888,0.975728,0.965600,0.970603,0.005211,28
5,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,5,COMPLETE,101.494180,"{""classifier__alpha"": 2.0402247877617882e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [50], ""classifier__learning_rate_init"": 0.0007866599720665551}",20.251472,6.334292,0.044210,0.000745,0.965450,0.977660,0.966872,0.965626,0.964831,0.968088,0.004832,29
9,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,9,COMPLETE,122.888880,"{""classifier__alpha"": 0.006060741222490684, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.0004960571565137328}",24.516799,4.849060,0.057789,0.000538,0.966167,0.965605,0.966854,0.964533,0.964667,0.965565,0.000883,30

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,fold,fit_time_seconds,score_time_seconds,precision_attack,recall_attack,f1_attack,precision_benign,recall_benign,f1_benign,f1_macro,accuracy,balanced_accuracy
0,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,1,193.556817,0.168751,0.970647,0.988268,0.979378,0.997054,0.992529,0.994786,0.987082,0.991677,0.990399
1,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,2,150.039937,0.178663,0.969787,0.989967,0.979773,0.997479,0.992290,0.994878,0.987325,0.991826,0.991129
2,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,3,206.301040,0.171448,0.968837,0.991773,0.980171,0.997931,0.992025,0.994969,0.987570,0.991974,0.991899
3,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,4,182.654548,0.186594,0.969269,0.987739,0.978417,0.996920,0.992170,0.994540,0.986478,0.991284,0.989955
4,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,5,212.923010,0.147230,0.968158,0.992516,0.980186,0.998117,0.991839,0.994968,0.987577,0.991974,0.992177

,model,search_method,training_source,training_rows,n_trials,n_splits,random_state,selection_metric,n_completed_trials,params,best_search_f1_macro,search_elapsed_seconds,search_elapsed_minutes,refit_time_seconds,winner_cv_elapsed_seconds,winner_cv_elapsed_minutes,elapsed_seconds,elapsed_minutes,fit_time_mean,fit_time_std,score_time_mean,score_time_std,model_size_mb,model_file,precision_attack_mean,precision_attack_std,recall_attack_mean,recall_attack_std,f1_attack_mean,f1_attack_std,precision_benign_mean,precision_benign_std,recall_benign_mean,recall_benign_std,f1_benign_mean,f1_benign_std,f1_macro_mean,f1_macro_std,accuracy_mean,accuracy_std,balanced_accuracy_mean,balanced_accuracy_std
6,decision_tree,optuna,cicids2017,235490,30,5,1,f1_macro,30,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 2, ""classifier__min_samples_split"": 3}",0.990896,143.680751,2.394679,1.549246,9.368995,0.156150,153.049746,2.550829,1.696324,0.050628,0.053980,0.005694,0.033790,cicids2017.joblib,0.979027,0.001549,0.991974,0.000617,0.985457,0.000757,0.997987,0.000154,0.994687,0.000401,0.996334,0.000194,0.990896,0.000475,0.994144,0.000309,0.993330,0.000316
7,decision_tree,optuna,unsw_nb15,235490,30,5,1,f1_macro,30,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 18}",0.980032,143.332926,2.388882,1.627599,4.417783,0.073630,147.750709,2.462512,1.858751,0.135670,0.052590,0.003624,0.029778,unsw_nb15.joblib,0.940737,0.002212,0.997516,0.000773,0.968292,0.000865,0.999370,0.000196,0.984288,0.000635,0.991771,0.000240,0.980032,0.000553,0.986934,0.000377,0.990902,0.000178
8,decision_tree,optuna,iot23,235490,30,5,1,f1_macro,30,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__min_samples_leaf"": 4, ""classifier__min_samples_split"": 12}",0.997766,55.247233,0.920787,0.475219,2.428261,0.040471,57.675494,0.961258,0.504956,0.073266,0.055242,0.008261,0.009499,iot23.joblib,0.999402,0.000109,0.993460,0.000984,0.996422,0.000530,0.998368,0.000245,0.999851,0.000027,0.999109,0.000132,0.997766,0.000331,0.998573,0.000211,0.996656,0.000500
9,decision_tree,optuna,cicids2017_unsw_nb15,470980,30,5,1,f1_macro,30,"{""classifier__class_weight"": ""balanced"", ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 7}",0.983458,359.276696,5.987945,3.943406,11.108456,0.185141,370.385152,6.173086,4.007051,0.184049,0.088188,0.008211,0.088208,cicids2017_unsw_nb15.joblib,0.953878,0.002057,0.994310,0.000931,0.973673,0.001317,0.998562,0.000235,0.987980,0.000557,0.993243,0.000344,0.983458,0.000830,0.989246,0.000545,0.991145,0.000628
10,decision_tree,optuna,cicids2017_iot23,470980,30,5,1,f1_macro,30,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__min_samples_leaf"": 3, ""classifier__min_samples_split"": 7}",0.993603,263.926728,4.398779,2.712662,5.547860,0.092464,269.474588,4.491243,3.231499,0.145445,0.081097,0.004668,0.035351,cicids2017_iot23.joblib,0.989206,0.000604,0.990329,0.000457,0.989767,0.000255,0.997582,0.000114,0.997298,0.000154,0.997440,0.000064,0.993603,0.000160,0.995904,0.000103,0.993813,0.000195
11,decision_tree,optuna,unsw_nb15_iot23,470980,30,5,1,f1_macro,30,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__min_samples_leaf"": 7, ""classifier__min_samples_split"": 6}",0.988461,237.190942,3.953182,2.327475,5.842801,0.097380,243.033744,4.050562,2.334577,0.135788,0.080396,0.003067,0.029451,unsw_nb15_iot23.joblib,0.970931,0.000876,0.992484,0.000398,0.981589,0.000561,0.998110,0.000100,0.992571,0.000230,0.995333,0.000144,0.988461,0.000353,0.992554,0.000229,0.992528,0.000269
12,random_forest,optuna,cicids2017,235490,30,5,1,f1_macro,30,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": null, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 199}",0.992571,1823.819020,30.396984,11.199216,43.336383,0.722273,1867.155402,31.119257,8.563370,0.066357,0.101006,0.000750,7.145731,cicids2017.joblib,0.979678,0.001875,0.996751,0.000832,0.988140,0.000987,0.999184,0.000209,0.994830,0.000487,0.997002,0.000252,0.992571,0.000620,0.995214,0.000402,0.995791,0.000452
13,random_forest,optuna,unsw_nb15,235490,30,5,1,f1_macro,30,"{""classifier__class_weight"": null, ""classifier__max_depth"": 15, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 291}",0.981047,2126.763202,35.446053,14.770324,55.164504,0.919408,2181.927705,36.365462,10.881429,0.132224,0.146953,0.013314,9.005455,unsw_nb15.joblib,0.943327,0.001440,0.998004,0.000370,0.969895,0.000801,0.999494,0.000094,0.985010,0.000404,0.992199,0.000215,0.981047,0.000508,0.987609,0.000339,0.991507,0.000288
14,random_forest,optuna,iot23,235490,30,5,1,f1_macro,30,"{""classifier__class_weight"": null, ""classifier__max_depth"": 30, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 3, ""classifier__n_estimators"": 186}",0.997865,731.122471,12.185375,5.998689,21.600450,0.360008,752.722921,12.545382,4.225427,0.108613,0.092640,0.001975,1.173029,iot23.joblib,0.999829,0.000145,0.993354,0.000942,0.996581,0.000478,0.998341,0.000235,0.999958,0.000036,0.999149,0.000119,0.997865,0.000299,0.998637,0.000190,0.996656,0.000471
15,random_forest,optuna,cicids2017_unsw_nb15,470980,30,5,1,f1_macro,30,"{""classifier__class_weight"": ""balanced_subsample"", ""classifier__max_depth"": 20, ""classifier__max_features"": 0.5, ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 248}",0.986258,6158.823562,102.647059,59.739311,226.420058,3.773668,6385.243620,106.420727,45.041300,0.702965,0.235057,0.013064,18.766259,cicids2017_unsw_nb15.joblib,0.959954,0.001714,0.996985,0.000601,0.978118,0.001026,0.999239,0.000152,0.989601,0.000461,0.994397,0.000267,0.986258,0.000647,0.991078,0.000424,0.993293,0.000435
16,random_forest,optuna,cicids2017_iot23,470980,30,5,1,f1_macro,30,"{""classifier__class_weight"": null, ""classifier__max_depth"": null, ""classifier__max_features"": ""log2"", ""classifier__min_samples_leaf"": 1, ""classifier__n_estimators"": 297}",0.994690,5307.250047,88.454167,36.262036,135.860875,2.264348,5443.110922,90.718515,26.917255,0.269834,0.249981,0.004760,12.019603,cicids2017_iot23.joblib,0.989615,0.000841,0.993407,0.000405,0.991508,0.000478,0.998350,0.000101,0.997394,0.000213,0.997872,0.000120,0.994690,0.000299,0.996596,0.000192,0.995401,0.000233
17,random_forest,optuna,unsw_nb15_iot23,470980,30,5,1,f1_macro,30,"{""classifier__class_weight"": null, ""classifier__max_depth"": 20, ""classifier__max_features"": ""sqrt"", ""classifier__min_samples_leaf"": 2, ""classifier__n_estimators"": 161}",0.989193,2813.389016,46.889817,16.211540,62.245352,1.037423,2875.634368,47.927239,12.274356,0.263523,0.171113,0.007430,8.810776,unsw_nb15_iot23.joblib,0.971115,0.000952,0.994692,0.000453,0.982762,0.000374,0.998665,0.000114,0.992603,0.000254,0.995625,0.000098,0.989193,0.000236,0.993021,0.000155,0.993648,0.000167
18,xgboost,optuna,cicids2017,235490,30,5,1,f1_macro,30,"{""classifier__colsample_bytree"": 0.7390085716354833, ""classifier__learning_rate"": 0.05898416056128349, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 190, ""classifier__subsample"": 0.7863326015759046}",0.991899,192.842027,3.214034,1.406512,5.846269,0.097438,198.688296,3.311472,1.079626,0.041027,0.086593,0.001409,0.363552,cicids2017.joblib,0.980578,0.001156,0.993630,0.001309,0.987060,0.000888,0.998402,0.000328,0.995079,0.000299,0.996738,0.000223,0.991899,0.000555,0.994790,0.000357,0.994355,0.000673
19,xgboost,optuna,unsw_nb15,235490,30,5,1,f1_macro,30,"{""classifier__colsample_bytree"": 0.709652207359822, ""classifier__learning_rate"": 0.055587807154804283, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 244, ""classifier__subsample"": 0.9594797691884895}",0.981053,206.615071,3.443585,1.778834,7.224076,0.120401,213.839147,3.563986,1.348540,0.051377,0.093170,0.002022,0.573093,unsw_nb15.joblib,0.943382,0.001348,0.997962,0.000332,0.969904,0.000587,0.999483,0.000084,0.985026,0.000383,0.992202,0.000161,0.981053,0.000374,0.987613,0.000253,0.991494,0.000104
20,xgboost,optuna,iot23,235490,30,5,1,f1_macro,30,"{""classifier__colsample_bytree"": 0.7826494405879115, ""classifier__learning_rate"": 0.04579747054926139, ""classifier__max_depth"": 7, ""classifier__n_estimators"": 137, ""classifier__subsample"": 0.9923740090265242}",0.997832,148.012462,2.466874,1.011299,3.662298,0.061038,151.674760,2.527913,0.651057,0.016782,0.078461,0.001752,0.129786,iot23.joblib,0.999765,0.000142,0.993312,0.000844,0.996528,0.000486,0.998331,0.000210,0.999942,0.000035,0.999135,0.000121,0.997832,0.000304,0.998616,0.000193,0.996627,0.000437
21,xgboost,optuna,cicids2017_unsw_nb15,470980,30,5,1,f1_macro,30,"{""classifier__colsample_bytree"": 0.9899866166981167, ""classifier__learning_rate"": 0.08764086364133913, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 227, ""classifier__subsample"": 0.9249996971958904}",0.985721,364.038991,6.067317,3.098010,12.118041,0.201967,376.157032,6.269284,2.255779,0.049992,0.163617,0.002888,0.594414,cicids2017_unsw_nb15.joblib,0.961116,0.001614,0.993938,0.000799,0.977251,0.001057,0.998471,0.000201,0.989946,0.000430,0.994191,0.000273,0.985721,0.000665,0.990745,0.000434,0.991942,0.000525
22,xgboost,optuna,cicids2017_iot23,470980,30,5,1,f1_macro,30,"{""classifier__colsample_bytree"": 0.733728951824139, ""classifier__learning_rate"": 0.0675693609485163, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 295, ""classifier__subsample"": 0.9068296839507027}",0.994331,371.853187,6.197553,4.021609,15.068002,0.251133,386.921189,6.448686,2.834489,0.191021,0.174723,0.002087,0.568448,cicids2017_iot23.joblib,0.989271,0.000568,0.992601,0.000816,0.990933,0.000629,0.998149,0.000204,0.997309,0.000143,0.997729,0.000157,0.994331,0.000393,0.996367,0.000252,0.994955,0.000457
23,xgboost,optuna,unsw_nb15_iot23,470980,30,5,1,f1_macro,30,"{""classifier__colsample_bytree"": 0.8635520750631398, ""classifier__learning_rate"": 0.07927649874783331, ""classifier__max_depth"": 8, ""classifier__n_estimators"": 230, ""classifier__subsample"": 0.9189551670409017}",0.989249,357.298461,5.954974,3.106936,11.486661,0.191444,368.785122,6.146419,2.131895,0.037637,0.161142,0.002774,0.484843,unsw_nb15_iot23.joblib,0.970817,0.000696,0.995191,0.000358,0.982853,0.000201,0.998790,0.000090,0.992521,0.000187,0.995646,0.000054,0.989249,0.000127,0.993055,0.000085,0.993856,0.000096
24,linear_svm,optuna,cicids2017,235490,30,5,1,f1_macro,30,"{""classifier__C"": 82.94461752105981, ""classifier__class_weight"": ""balanced""}",0.904406,515.360828,8.589347,5.314842,18.034038,0.300567,533.394866,8.889914,7.217169,1.513497,0.047616,0.003183,0.001995,cicids2017.joblib,0.763170,0.003282,0.964478,0.002576,0.852094,0.002957,0.990492,0.000694,0.925172,0.001192,0.956718,0.000922,0.904406,0.001939,0.933033,0.001407,0.944825,0.001809
25,linear_svm,optuna,unsw_nb15,235490,30,5,1,f1_macro,30,"{""classifier__C"": 88.78015547689247, ""classifier__class_weight"": null}",0.927552,450.164003,7.502733,3.507961,11.148478,0.185808,461.312481,7.688541,3.991135,0.850970,0.050404,0.005851,0.001998,unsw_nb15.joblib,0.937763,0.000904,0.833347,0.005281,0.882467,0.002789,0.959467,0.001224,0.986172,0.000268,0.972636,0.000545,0.927552,0.001666,0.955607,0.000915,0.909760,0.002547
26,linear_svm,optuna,iot23,235490,30,5,1,f1_macro,30,"{""classifier__C"": 65.72187409908494, ""classifier__class_weight"": null}",0.995766,248.229392,4.137157,2.437704,6.019908,0.100332,254.249300,4.237488,2.845912,0.673153,0.051164,0.006463,0.001986,iot23.joblib,0.995563,0.000408,0.990891,0.001118,0.993221,0.000647,0.997726,0.000279,0.998896,0.000102,0.998310,0.000160,0.995766,0.000403,0.997295,0.000257,0.994894,0.000574
27,linear_svm,optuna,cicids2017_unsw_nb15,470980,30,5,1,f1_macro,30,"{""classifier__C"": 31.808217066869858, ""classifier__class_weight"": ""balanced""}",0.848305,1031.070538,17.184509,9.083054,17.433637,0.290561,1048.504175,17.475070,10.322717,1.247633,0.087365,0.012924,0.002007,cicids2017_unsw_nb15.joblib,0.681776,0.008980,0.873668,0.009951,0.765839,0.007475,0.966032,0.002577,0.898005,0.004235,0.930770,0.002556,0.848305,0.004968,0.893138,0.003790,0.885837,0.005249
28,linear_svm,optuna,cicids2017_iot23,470980,30,5,1,f1_macro,30,"{""classifier__C"": 89.93277588459073, ""classifier__class_weight"": null}",0.957427,1759.064490,29.317742,9.595539,48.781584,0.813026,1807.846075,30.130768,32.009538,7.208302,0.084526,0.014690,0.001996,cicids2017_iot23.joblib,0.912612,0.001313,0.952769,0.000386,0.932258,0.000628,0.988061,0.000095,0.977191,0.000380,0.982596,0.000178,0.957427,0.000403,0.972307,0.000277,0.964980,0.000200
29,linear_svm,optuna,unsw_nb15_iot23,470980,30,5,1,f1_macro,30,"{""classifier__C"": 77.75026881948125, ""classifier__class_weight"": ""balanced""}",0.954713,772.968016,12.882800,5.211036,16.709141,0.278486,789.677157,13.161286,7.447824,1.515127,0.082203,0.009836,0.002005,unsw_nb15_iot23.joblib,0.928932,0.013850,0.926218,0.001731,0.927529,0.007515,0.981566,0.000472,0.982234,0.003716,0.981897,0.002036,0.954713,0.004776,0.971031,0.003208,0.954226,0.002506
30,mlp,optuna,cicids2017,235490,30,5,1,f1_macro,30,"{""classifier__alpha"": 1.0145206295623886e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.002017977223065986}",0.991065,5634.380555,93.906343,75.157806,66.906696,1.115112,5701.287251,95.021454,56.436620,5.088545,0.081419,0.001625,0.199733,cicids2017.joblib,0.978438,0.001382,0.993269,0.000840,0.985797,0.000798,0.998311,0.000211,0.994527,0.000358,0.996416,0.000203,0.991106,0.000500,0.994276,0.000324,0.993898,0.000447
31,mlp,optuna,unsw_nb15,235490,30,5,1,f1_macro,30,"{""classifier__alpha"": 3.113226289948056e-05, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0021585454565860055}",0.979449,3493.979827,58.232997,15.598525,35.686031,0.594767,3529.665858,58.827764,22.407930,3.749754,0.085540,0.006592,0.158453,unsw_nb15.joblib,0.939466,0.002319,0.996666,0.001006,0.967219,0.001014,0.999154,0.000255,0.983943,0.000665,0.991490,0.000278,0.979354,0.000646,0.986488,0.000436,0.990305,0.000395
32,mlp,optuna,iot23,235490,30,5,1,f1_macro,30,"{""classifier__alpha"": 1.2135528081866365e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0006633669118179749}",0.997651,2467.153433,41.119224,43.392285,44.787121,0.746452,2511.940553,41.865676,32.824675,9.392118,0.086322,0.009780,0.207044,iot23.joblib,0.999637,0.000209,0.992866,0.001801,0.996239,0.000870,0.998220,0.000448,0.999910,0.000052,0.999064,0.000215,0.997651,0.000543,0.998501,0.000345,0.996388,0.000890
33,mlp,optuna,cicids2017_unsw_nb15,470980,30,5,1,f1_macro,30,"{""classifier__alpha"": 0.0004850777386828204, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0006809764960501163}",0.982228,14942.236381,249.037273,198.367001,276.389096,4.606485,15218.625477,253.643758,221.835813,31.231755,0.169786,0.014287,0.201133,cicids2017_unsw_nb15.joblib,0.950340,0.003432,0.992378,0.001589,0.970900,0.001894,0.998073,0.000401,0.987032,0.000943,0.992522,0.000500,0.981711,0.001197,0.988101,0.000791,0.989705,0.000886
34,mlp,optuna,cicids2017_iot23,470980,30,5,1,f1_macro,30,"{""classifier__alpha"": 1.1319686938423936e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.00040313765778780087}",0.992877,11692.261077,194.871018,180.835353,194.876001,3.247933,11887.137079,198.118951,163.886660,16.978555,0.195765,0.022816,0.207108,cicids2017_iot23.joblib,0.985485,0.002865,0.990966,0.001639,0.988213,0.001000,0.997739,0.000409,0.996348,0.000737,0.997043,0.000256,0.992628,0.000628,0.995272,0.000408,0.993657,0.000597
35,mlp,optuna,unsw_nb15_iot23,470980,30,5,1,f1_macro,30,"{""classifier__alpha"": 5.9276550057310775e-05, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.0012247884215016809}",0.987558,17018.023862,283.633731,151.242548,219.462234,3.657704,17237.486096,287.291435,189.095070,22.138234,0.170537,0.013199,0.203593,unsw_nb15_iot23.joblib,0.969340,0.000844,0.990053,0.001875,0.979585,0.000655,0.997500,0.000470,0.992171,0.000234,0.994828,0.000159,0.987207,0.000407,0.991747,0.000256,0.991112,0.000849