In [1]:
from pathlib import Path
from time import perf_counter
import json

import joblib
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    f1_score,
    make_scorer,
    precision_score,
    recall_score,
)
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier

from xgboost import XGBClassifier

from src.utils.features import split_features

In [2]:
DATA_DIR = Path("../datasets/final/ml")
MODEL_DIR = Path("../models")
RESULTS_DIR = Path("../results/model_training")

MODEL_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 1
N_SPLITS = 5
N_JOBS = -1
SEARCH_STAGE = "search_01_initial"

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [3]:
#configurações de treinamento / organização / origem dos dados
TRAINING_CONFIGS = {
    "cicids2017": ["cicids2017"],
    "unsw_nb15": ["unsw_nb15"],
    "iot23": ["iot23"],
    "cicids2017_unsw_nb15": ["cicids2017", "unsw_nb15"],
    "cicids2017_iot23": ["cicids2017", "iot23"],
    "unsw_nb15_iot23": ["unsw_nb15", "iot23"],
}

In [4]:
# atributos
reference_df = pd.read_parquet(DATA_DIR / "cicids2017_train.parquet")

numerical_features, categorical_features = split_features(reference_df)
feature_columns = numerical_features + categorical_features

del reference_df

print("features num:", len(numerical_features))
print("features cat:", len(categorical_features))
print("Total de features antes do one-hot:", len(feature_columns))

features num: 14
features cat: 1
Total de features antes do one-hot: 15

In [5]:
#pipeline pré-rocessamento
def build_pipeline(estimator):
    preprocessor = ColumnTransformer(
        transformers=[
            ("numerical", StandardScaler(), numerical_features),
            ("categorical", OneHotEncoder(handle_unknown="ignore"),categorical_features),
        ]
    )

    return Pipeline(
        steps=[ ("preprocessor", preprocessor),
                ("classifier", estimator),
        ]
    )

In [6]:
#modelos e espaços de busca
MODEL_CONFIGS = {
    "decision_tree": {
        "estimator": DecisionTreeClassifier(
            random_state=RANDOM_STATE,
        ),
        "param_grid": {
            "classifier__max_depth": [3, 5, 10, 20, None],
            "classifier__min_samples_leaf": [1, 5, 10],
        },
    },
    "random_forest": {
        "estimator": RandomForestClassifier(
            random_state=RANDOM_STATE,
            n_jobs=1,
        ),
        "param_grid": {
            "classifier__n_estimators": [100, 200],
            "classifier__max_depth": [10, 20, None],
            "classifier__min_samples_leaf": [1, 5],
        },
    },
    "xgboost": {
        "estimator": XGBClassifier(
            random_state=RANDOM_STATE,
            n_jobs=1,
        ),
        "param_grid": [
            {
                "classifier__n_estimators": [100],
                "classifier__max_depth": [3],
                "classifier__learning_rate": [0.05, 0.1, 0.3],
                "classifier__eval_metric": ["logloss"],
                "classifier__tree_method": ["hist"],
            },
            {
                "classifier__n_estimators": [100],
                "classifier__max_depth": [6],
                "classifier__learning_rate": [0.05, 0.1],
                "classifier__eval_metric": ["logloss"],
                "classifier__tree_method": ["hist"],
            },
            {
                "classifier__n_estimators": [200],
                "classifier__max_depth": [3, 6],
                "classifier__learning_rate": [0.05, 0.1, 0.3],
                "classifier__eval_metric": ["logloss"],
                "classifier__tree_method": ["hist"],
            },
            {
                "classifier__n_estimators": [100],
                "classifier__max_depth": [6],
                "classifier__learning_rate": [0.3],
                "classifier__eval_metric": [None],
                "classifier__tree_method": [None],
            },
        ],
    },
    "linear_svm": {
        "estimator": LinearSVC(random_state=RANDOM_STATE),
        "param_grid": [
            {
                "classifier__C": [0.01, 0.1, 10.0, 100.0],
                "classifier__dual": [False],
                "classifier__max_iter": [10000],
            },
            {
                "classifier__C": [1.0],
                "classifier__dual": ["auto"],
                "classifier__max_iter": [1000],
            },
        ],
    },
    "mlp": {
        "estimator": MLPClassifier(random_state=RANDOM_STATE),
        "param_grid": [
            {
                "classifier__hidden_layer_sizes": [
                    (50,),
                    (100, 50),
                ],
                "classifier__alpha": [0.0001, 0.001],
                "classifier__learning_rate_init": [0.0001, 0.001],
                "classifier__max_iter": [300],
                "classifier__early_stopping": [True],
            },
            {
                "classifier__hidden_layer_sizes": [(100,)],
                "classifier__alpha": [0.001],
                "classifier__learning_rate_init": [0.0001, 0.001],
                "classifier__max_iter": [300],
                "classifier__early_stopping": [True],
            },
            {
                "classifier__hidden_layer_sizes": [(100,)],
                "classifier__alpha": [0.0001],
                "classifier__learning_rate_init": [0.0001],
                "classifier__max_iter": [300],
                "classifier__early_stopping": [True],
            },
            {
                "classifier__hidden_layer_sizes": [(100,)],
                "classifier__alpha": [0.0001],
                "classifier__learning_rate_init": [0.001],
                "classifier__max_iter": [200],
                "classifier__early_stopping": [False],
            },
        ],
    },
}

In [7]:
#modelos para rodar
MODELS_TO_RUN = [
    #"decision_tree",
    #"random_forest",
    #"xgboost",
    #"linear_svm",
    "mlp",
]

In [8]:
# kfold estratificado + métricas
# buscar: melhores hiperparâmetros através do f1-score
cross_validation = StratifiedKFold(
    n_splits=N_SPLITS,
    shuffle=True,
    random_state=RANDOM_STATE,
)

scoring = {
    #o make_scorer cria um avaliador que calcula a métrica estabelecida, considerando a classe 1 ataque como positiva
    "precision_attack": make_scorer(
        precision_score,
        pos_label=1,
        zero_division=0,
    ),
    "recall_attack": make_scorer(
        recall_score,
        pos_label=1,
        zero_division=0,
    ),
    "f1_attack": make_scorer(
        f1_score,
        pos_label=1,
        zero_division=0,
    ),
    "precision_benign": make_scorer(
        precision_score,
        pos_label=0,
        zero_division=0,
    ),
    "recall_benign": make_scorer(
        recall_score,
        pos_label=0,
        zero_division=0,
    ),
    "f1_benign": make_scorer(
        f1_score,
        pos_label=0,
        zero_division=0,
    ),
    "f1_macro": make_scorer(
        f1_score,
        average="macro",
        labels=[0, 1],
        zero_division=0,
    ),
    "accuracy": "accuracy",
    "balanced_accuracy": "balanced_accuracy",
}

In [9]:
# carregamento de origem de treinamento
def load_training_data(dataset_names):
    columns = feature_columns + ["label_binary"]

    dataframes = []

    for dataset_name in dataset_names:
        #columns=columns (pandas pega apenas colunas necessárias)
        df = pd.read_parquet( DATA_DIR / f"{dataset_name}_train.parquet", columns=columns)
        dataframes.append(df)

    training_df = pd.concat( dataframes, ignore_index=True)

    features = training_df[feature_columns]
    # training_df["label_binary"].eq("ATTACK").astype("int8") -> 1 se equal, 0 se não, ou seja, 1 ataque, 0 benigno
    target = (training_df["label_binary"].eq("ATTACK").astype("int8"))

    return features, target

In [10]:
##treino, validação e save
def train_and_select_model(model_name, training_name, dataset_names):
    features, target = load_training_data(dataset_names)
    model_config = MODEL_CONFIGS[model_name]
    model_dir = MODEL_DIR / model_name
    results_dir = RESULTS_DIR / model_name

    model_dir.mkdir(parents=True, exist_ok=True)
    results_dir.mkdir(parents=True, exist_ok=True)

    search = GridSearchCV(
        estimator=build_pipeline(model_config["estimator"]),
        param_grid=model_config["param_grid"],
        scoring=scoring,
        # o refit treina novamente o pipeline com todo o conjunto de treino,
        # usando os melhores hiperparâmetros encontrados segundo o f1 de ataque na validação cruzada.
        refit="f1_attack",
        cv=cross_validation,
        n_jobs=N_JOBS,
        verbose=1,
        error_score="raise",
        return_train_score=False,
    )

    start = perf_counter()
    search.fit(features, target)
    elapsed_minutes = (perf_counter() - start) / 60

    cv_results = pd.DataFrame(search.cv_results_)

    #informações da busca
    candidate_columns = ["params"]
    for metric in scoring:
        candidate_columns.extend(
            f"split{fold}_test_{metric}" for fold in range(N_SPLITS)
        )
        candidate_columns.extend([
            f"mean_test_{metric}",
            f"std_test_{metric}",
            f"rank_test_{metric}",
        ])
    candidate_columns.extend(["mean_fit_time", "std_fit_time"])

    candidate_results = (
        cv_results[candidate_columns]
        .sort_values("rank_test_f1_attack")
    )
    candidate_results.insert(0, "random_state", RANDOM_STATE)
    candidate_results.insert(0, "n_splits", N_SPLITS)
    candidate_results.insert(0, "training_rows", len(features))
    candidate_results.insert(0, "training_source", training_name)
    candidate_results.insert(0, "search_stage", SEARCH_STAGE)
    candidate_results.insert(0, "model", model_name)

    print(f"resultados dos hiperparâmetros: {model_name} - {training_name}")

    #todas as colunas de informações definidas
    display(candidate_results)

    candidate_results.to_csv(
        results_dir / f"{training_name}_{SEARCH_STAGE}.csv",
        index=False,
    )

    model_path = model_dir / f"{training_name}.joblib"
    # salva o pipeline da configuração com maior f1 de ataque na validação cruzada
    joblib.dump(
        search.best_estimator_,
        model_path,
        compress=3,
    )

    best_result = cv_results.loc[search.best_index_]

    result = {
        "model": model_name,
        "search_stage": SEARCH_STAGE,
        "training_source": training_name,
        "training_rows": len(features),
        "best_parameters": json.dumps(
            search.best_params_,
            sort_keys=True,
        ),
        "elapsed_minutes": elapsed_minutes,
        "model_size_mb": (
                model_path.stat().st_size / 1024 ** 2
        ),
        "model_file": model_path.name,
    }

    for metric in scoring:
        result[f"{metric}_mean"] = best_result[f"mean_test_{metric}"]
        result[f"{metric}_std"] = best_result[f"std_test_{metric}"]

    return result

In [11]:
# exec
all_results = []

for model_name in MODELS_TO_RUN:
    model_results = []

    for training_name, dataset_names in TRAINING_CONFIGS.items():
        print(f"modelo: {model_name}\n origem do treinamento: {training_name}")

        result = train_and_select_model(
            model_name,
            training_name,
            dataset_names,
        )

        model_results.append(result)
        all_results.append(result)

    results_df = pd.DataFrame(model_results)
    results_df.to_csv(
        RESULTS_DIR / model_name / "summary.csv",
        index=False,
    )

all_results_df = pd.DataFrame(all_results)
display(all_results_df)

modelo: mlp
 origem do treinamento: cicids2017
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: mlp - cicids2017

,model,search_stage,training_source,training_rows,n_splits,random_state,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time
3,mlp,search_01_initial,cicids2017,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.979757,0.977358,0.980260,0.978108,0.975070,0.978111,0.001851,1,0.991719,0.989914,0.991083,0.991295,0.992357,0.991273,0.000807,1,0.985701,0.983596,0.985642,0.984658,0.983638,0.984647,0.000919,1,0.997924,0.997471,0.997764,0.997816,0.998081,0.997811,0.000202,1,0.994878,0.994267,0.995010,0.994453,0.993657,0.994453,0.000482,2,0.996398,0.995866,0.996385,0.996132,0.995864,0.996129,0.000236,1,0.991050,0.989731,0.991014,0.990395,0.989751,0.990388,0.000577,1,0.994246,0.993397,0.994225,0.993821,0.993397,0.993817,0.000375,1,0.993298,0.992091,0.993047,0.992874,0.993007,0.992863,0.000410,1,43.876888,6.255255
7,mlp,search_01_initial,cicids2017,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.978639,0.977563,0.979979,0.976839,0.976467,0.977897,0.001278,4,0.992250,0.989914,0.992463,0.989490,0.991083,0.991040,0.001197,2,0.985397,0.983700,0.986181,0.983124,0.983721,0.984425,0.001161,2,0.998056,0.997471,0.998110,0.997364,0.997762,0.997752,0.000300,2,0.994586,0.994320,0.994931,0.994135,0.994028,0.994400,0.000326,4,0.996318,0.995893,0.996518,0.995747,0.995892,0.996073,0.000293,2,0.990858,0.989797,0.991350,0.989435,0.989806,0.990249,0.000727,2,0.994119,0.993439,0.994437,0.993206,0.993439,0.993728,0.000468,2,0.993418,0.992117,0.993697,0.991812,0.992556,0.992720,0.000729,2,38.489790,6.605717
11,mlp,search_01_initial,cicids2017,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': False, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 200}",0.978735,0.980524,0.979943,0.977031,0.973350,0.977916,0.002577,3,0.991931,0.978129,0.985456,0.984395,0.992569,0.986496,0.005328,3,0.985289,0.979325,0.982692,0.980699,0.982866,0.982174,0.002037,3,0.997976,0.994536,0.996359,0.996091,0.998133,0.996619,0.001328,3,0.994612,0.995143,0.994957,0.994214,0.993206,0.994427,0.000688,3,0.996291,0.994840,0.995658,0.995152,0.995663,0.995521,0.000497,3,0.990790,0.987082,0.989175,0.987925,0.989264,0.988847,0.001267,3,0.994076,0.991741,0.993057,0.992250,0.993078,0.992840,0.000799,3,0.993272,0.986636,0.990207,0.989305,0.992887,0.990461,0.002442,3,53.542830,4.751452
9,mlp,search_01_initial,cicids2017,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.978941,0.977160,0.979303,0.978503,0.975733,0.977928,0.001316,2,0.987047,0.981102,0.984501,0.980892,0.981741,0.983057,0.002377,4,0.982977,0.979127,0.981895,0.979696,0.978728,0.980485,0.001659,4,0.996755,0.995271,0.996120,0.995220,0.995428,0.995759,0.000594,4,0.994692,0.994267,0.994798,0.994612,0.993896,0.994453,0.000331,1,0.995723,0.994769,0.995459,0.994916,0.994661,0.995105,0.000413,4,0.989350,0.986948,0.988677,0.987306,0.986695,0.987795,0.001036,4,0.993163,0.991634,0.992739,0.991868,0.991465,0.992174,0.000661,4,0.990870,0.987685,0.989650,0.987752,0.987818,0.988755,0.001289,4,30.879219,7.428380
1,mlp,search_01_initial,cicids2017,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.978293,0.976213,0.978451,0.976241,0.975130,0.976866,0.001295,6,0.980890,0.984712,0.983333,0.985775,0.978132,0.982568,0.002756,5,0.979590,0.980444,0.980886,0.980985,0.976628,0.979707,0.001616,5,0.995220,0.996170,0.995828,0.996435,0.994528,0.995636,0.000687,5,0.994559,0.994002,0.994586,0.994002,0.993763,0.994182,0.000330,6,0.994889,0.995085,0.995206,0.995217,0.994146,0.994909,0.000399,5,0.987240,0.987764,0.988046,0.988101,0.985387,0.987308,0.001008,5,0.991826,0.992144,0.992335,0.992356,0.990637,0.991860,0.000640,5,0.987724,0.989357,0.988960,0.989888,0.985947,0.988375,0.001408,5,25.087318,7.068439
5,mlp,search_01_initial,cicids2017,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.977578,0.976507,0.978942,0.976236,0.974825,0.976817,0.001378,7,0.981314,0.984075,0.982059,0.985563,0.978344,0.982271,0.002469,6,0.979443,0.980276,0.980498,0.980877,0.976582,0.979535,0.001550,6,0.995324,0.996011,0.995511,0.996382,0.994581,0.995562,0.000616,6,0.994374,0.994082,0.994718,0.994002,0.993683,0.994172,0.000351,7,0.994849,0.995045,0.995115,0.995190,0.994132,0.994866,0.000384,6,0.987146,0.987661,0.987806,0.988034,0.985357,0.987201,0.000967,6,0.991762,0.992080,0.992187,0.992314,0.990615,0.991792,0.000616,6,0.987844,0.989078,0.988389,0.989782,0.986014,0.988221,0.001282,6,24.861969,7.404061
2,mlp,search_01_initial,cicids2017,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.976987,0.975710,0.979138,0.977801,0.975574,0.977042,0.001334,5,0.982588,0.980890,0.981529,0.981953,0.979406,0.981273,0.001086,7,0.979780,0.978293,0.980332,0.979873,0.977486,0.979153,0.001079,7,0.995641,0.995216,0.995379,0.995483,0.994846,0.995313,0.000271,7,0.994214,0.993896,0.994771,0.994426,0.993869,0.994235,0.000339,5,0.994927,0.994556,0.995075,0.994955,0.994357,0.994774,0.000271,7,0.987354,0.986424,0.987704,0.987414,0.985922,0.986963,0.000675,7,0.991889,0.991295,0.992123,0.991932,0.990976,0.991643,0.000434,7,0.988401,0.987393,0.988150,0.988190,0.986637,0.987754,0.000655,7,54.558980,11.477250
6,mlp,search_01_initial,cicids2017,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.977654,0.976442,0.977879,0.977188,0.974630,0.976759,0.001172,8,0.984712,0.981314,0.980786,0.977707,0.978769,0.980657,0.002415,8,0.981170,0.978872,0.979330,0.977448,0.976695,0.978703,0.001557,8,0.996171,0.995323,0.995193,0.994426,0.994686,0.995160,0.000602,8,0.994374,0.994082,0.994453,0.994294,0.993630,0.994166,0.000295,8,0.995272,0.994702,0.994823,0.994360,0.994158,0.994663,0.000386,8,0.988221,0.986787,0.987076,0.985904,0.985426,0.986683,0.000971,8,0.992441,0.991528,0.991719,0.990976,0.990658,0.991465,0.000618,8,0.989543,0.987698,0.987619,0.986000,0.986199,0.987412,0.001275,8,52.070949,13.411577
10,mlp,search_01_initial,cicids2017,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.972913,0.975050,0.975858,0.974682,0.973347,0.974370,0.001090,11,0.980040,0.979191,0.978344,0.976752,0.976964,0.978258,0.001265,9,0.976464,0.977116,0.977099,0.975716,0.975152,0.976309,0.000773,9,0.995001,0.994793,0.994582,0.994185,0.994235,0.994559,0.000315,9,0.993179,0.993737,0.993949,0.993657,0.993312,0.993567,0.000282,11,0.994089,0.994264,0.994265,0.993921,0.993773,0.994063,0.000193,9,0.985277,0.985690,0.985682,0.984818,0.984463,0.985186,0.000483,9,0.990552,0.990828,0.990828,0.990276,0.990042,0.990505,0.000309,9,0.986610,0.986464,0.986146,0.985204,0.985138,0.985912,0.000624,9,28.561638,1.497204
8,mlp,search_01_initial,cicids2017,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.973016,0.975153,0.975754,0.974682,0.973242,0.974369,0.001071,12,0.980040,0.979191,0.978344,0.976752,0.976858,0.978237,0.001287,10,0.976515,0.977168,0.977047,0.975716,0.975046,0.976299,0.000809,10,0.995001,0.994793,0.994582,0.994185,0.994209,0.994554,0.000321,10,0.993206,0.993763,0.993922,0.993657,0.993285,0.993567,0.000277,12,0.994103,0.994278,0.994252,0.993921,0.993747,0.994060,0.000202,10,0.985309,0.985723,0.985650,0.984818,0.984397,0.985179,0.000505,10,0.990573,0.990849,0.990806,0.990276,0.990000,0.990501,0.000323,10,0.986623,0.986477,0.986133,0.985204,0.985071,0.985902,0.000645,10,31.995816,2.791583
4,mlp,search_01_initial,cicids2017,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.975646,0.975013,0.976057,0.975366,0.973333,0.975083,0.000939,10,0.978235,0.977705,0.978025,0.975159,0.976433,0.977112,0.001159,11,0.976939,0.976357,0.977040,0.975263,0.974881,0.976096,0.000876,11,0.994556,0.994423,0.994503,0.993790,0.994103,0.994275,0.000289,11,0.993896,0.993737,0.994002,0.993843,0.993312,0.993758,0.000239,10,0.994226,0.994080,0.994252,0.993816,0.993707,0.994016,0.000219,11,0.985582,0.985218,0.985646,0.984539,0.984294,0.985056,0.000548,11,0.990764,0.990530,0.990806,0.990106,0.989936,0.990428,0.000350,11,0.986066,0.985721,0.986014,0.984501,0.984872,0.985435,0.000633,11,32.299105,2.852044
0,mlp,search_01_initial,cicids2017,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.975636,0.974716,0.976160,0.975475,0.973642,0.975126,0.000874,9,0.977811,0.965920,0.978025,0.975372,0.976433,0.974712,0.004501,12,0.976722,0.970298,0.977092,0.975423,0.975036,0.974914,0.002433,12,0.994450,0.991500,0.994503,0.993843,0.994104,0.993680,0.001116,12,0.993896,0.993737,0.994028,0.993869,0.993391,0.993784,0.000217,9,0.994173,0.992617,0.994266,0.993856,0.993747,0.993732,0.000590,12,0.985447,0.981458,0.985679,0.984640,0.984392,0.984323,0.001511,12,0.990679,0.988174,0.990828,0.990169,0.990000,0.989970,0.000949,12,0.985853,0.979828,0.986027,0.984620,0.984912,0.984248,0.002274,12,28.737104,5.493357

modelo: mlp
 origem do treinamento: unsw_nb15
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: mlp - unsw_nb15

,model,search_stage,training_source,training_rows,n_splits,random_state,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time
11,mlp,search_01_initial,unsw_nb15,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': False, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 200}",0.941064,0.941141,0.939188,0.938790,0.938649,0.939766,0.001106,1,0.996815,0.996496,0.996815,0.994798,0.997240,0.996433,0.000851,3,0.968138,0.968028,0.967144,0.965983,0.967058,0.967270,0.000780,1,0.999192,0.999111,0.999191,0.998680,0.999299,0.999095,0.000216,3,0.984394,0.984421,0.983863,0.983784,0.983704,0.984033,0.000310,5,0.991738,0.991712,0.991468,0.991176,0.991440,0.991507,0.000205,1,0.979938,0.979870,0.979306,0.978579,0.979249,0.979388,0.000493,1,0.986878,0.986836,0.986454,0.985987,0.986411,0.986513,0.000325,1,0.990605,0.990459,0.990339,0.989291,0.990472,0.990233,0.000479,2,64.397633,4.143351
3,mlp,search_01_initial,unsw_nb15,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.941542,0.940764,0.937070,0.936266,0.938849,0.938898,0.002037,4,0.996921,0.996496,0.997452,0.996497,0.997452,0.996964,0.000428,1,0.968441,0.967828,0.966319,0.965443,0.967264,0.967059,0.001068,2,0.999219,0.999111,0.999353,0.999110,0.999353,0.999229,0.000108,1,0.984527,0.984315,0.983253,0.983041,0.983757,0.983778,0.000578,9,0.991819,0.991658,0.991237,0.991010,0.991494,0.991443,0.000290,2,0.980130,0.979743,0.978778,0.978226,0.979379,0.979251,0.000679,2,0.987006,0.986751,0.986093,0.985732,0.986496,0.986416,0.000456,2,0.990724,0.990406,0.990353,0.989769,0.990605,0.990371,0.000330,1,37.817277,6.594763
7,mlp,search_01_initial,unsw_nb15,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.941047,0.941974,0.935404,0.937250,0.938651,0.938865,0.002411,5,0.998195,0.996178,0.997665,0.995754,0.995648,0.996688,0.001043,2,0.968779,0.968318,0.965531,0.965617,0.966309,0.966911,0.001372,3,0.999542,0.999031,0.999406,0.998922,0.998895,0.999159,0.000265,2,0.984368,0.984660,0.982775,0.983332,0.983731,0.983773,0.000683,10,0.991897,0.991793,0.991021,0.991066,0.991255,0.991406,0.000368,3,0.980338,0.980056,0.978276,0.978341,0.978782,0.979159,0.000870,3,0.987133,0.986963,0.985753,0.985817,0.986114,0.986356,0.000581,3,0.991282,0.990419,0.990220,0.989543,0.989689,0.990230,0.000617,3,36.967097,4.508395
9,mlp,search_01_initial,unsw_nb15,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.941934,0.940935,0.936781,0.939607,0.938270,0.939506,0.001838,2,0.993736,0.996178,0.994161,0.990977,0.993949,0.993800,0.001660,7,0.967142,0.967769,0.964619,0.964609,0.965307,0.965889,0.001319,4,0.998412,0.999030,0.998518,0.997713,0.998464,0.998427,0.000420,7,0.984686,0.984368,0.983226,0.984076,0.983651,0.984001,0.000516,6,0.991502,0.991645,0.990813,0.990847,0.991002,0.991162,0.000345,4,0.979322,0.979707,0.977716,0.977728,0.978155,0.978525,0.000832,4,0.986496,0.986730,0.985413,0.985456,0.985711,0.985961,0.000547,4,0.989211,0.990273,0.988694,0.987526,0.988800,0.988901,0.000886,7,34.809166,4.205952
1,mlp,search_01_initial,unsw_nb15,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.941969,0.940475,0.937006,0.936611,0.938108,0.938834,0.002065,6,0.994373,0.996390,0.994798,0.992887,0.992781,0.994246,0.001335,6,0.967462,0.967626,0.965038,0.963929,0.964671,0.965745,0.001512,5,0.998574,0.999084,0.998679,0.998195,0.998169,0.998540,0.000339,6,0.984686,0.984235,0.983279,0.983200,0.983624,0.983805,0.000572,8,0.991581,0.991604,0.990919,0.990640,0.990843,0.991118,0.000398,5,0.979522,0.979615,0.977979,0.977285,0.977757,0.978431,0.000955,5,0.986624,0.986666,0.985583,0.985137,0.985456,0.985893,0.000631,5,0.989530,0.990313,0.989039,0.988044,0.988203,0.989026,0.000843,6,33.587130,3.588544
2,mlp,search_01_initial,unsw_nb15,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.940739,0.940905,0.934523,0.936245,0.937087,0.937900,0.002526,7,0.994373,0.995647,0.995435,0.994586,0.994586,0.994925,0.000513,4,0.966813,0.967502,0.964018,0.964534,0.964981,0.965570,0.001350,6,0.998573,0.998896,0.998840,0.998625,0.998625,0.998712,0.000130,4,0.984341,0.984368,0.982563,0.983067,0.983306,0.983529,0.000716,11,0.991406,0.991579,0.990634,0.990785,0.990906,0.991062,0.000366,6,0.979110,0.979540,0.977326,0.977659,0.977944,0.978316,0.000858,6,0.986348,0.986624,0.985137,0.985371,0.985562,0.985808,0.000576,6,0.989357,0.990008,0.988999,0.988827,0.988946,0.989227,0.000428,4,66.788037,5.478395
6,mlp,search_01_initial,unsw_nb15,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.939281,0.940905,0.935609,0.936630,0.936770,0.937839,0.001952,8,0.993630,0.995647,0.994904,0.993206,0.995541,0.994586,0.000996,5,0.965692,0.967502,0.964346,0.964089,0.965262,0.965378,0.001213,7,0.998384,0.998896,0.998706,0.998275,0.998868,0.998626,0.000253,5,0.983943,0.984368,0.982881,0.983200,0.983200,0.983518,0.000550,12,0.991111,0.991579,0.990730,0.990680,0.990972,0.991014,0.000323,8,0.978401,0.979540,0.977538,0.977385,0.978117,0.978196,0.000768,7,0.985881,0.986624,0.985286,0.985201,0.985668,0.985732,0.000510,7,0.988787,0.990008,0.988893,0.988203,0.989371,0.989052,0.000605,5,72.196113,3.375727
5,mlp,search_01_initial,unsw_nb15,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.942337,0.941259,0.937024,0.937061,0.938993,0.939335,0.002161,3,0.994161,0.991825,0.993524,0.990977,0.993418,0.992781,0.001186,8,0.967555,0.965881,0.964448,0.963265,0.965439,0.965318,0.001436,8,0.998520,0.997929,0.998356,0.997711,0.998330,0.998169,0.000301,8,0.984793,0.984527,0.983306,0.983359,0.983863,0.983970,0.000602,7,0.991609,0.991183,0.990774,0.990483,0.991044,0.991018,0.000380,7,0.979582,0.978532,0.977611,0.976874,0.978241,0.978168,0.000908,8,0.986666,0.985987,0.985350,0.984883,0.985774,0.985732,0.000601,7,0.989477,0.988176,0.988415,0.987168,0.988641,0.988375,0.000746,8,31.566004,6.017772
8,mlp,search_01_initial,unsw_nb15,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.938589,0.938244,0.934861,0.936288,0.934419,0.936480,0.001701,10,0.863255,0.861344,0.879087,0.861146,0.859130,0.864792,0.007266,9,0.899347,0.898151,0.906117,0.897147,0.895194,0.899191,0.003721,9,0.966489,0.966035,0.970214,0.965968,0.965476,0.966836,0.001719,9,0.985881,0.985828,0.984686,0.985350,0.984925,0.985334,0.000475,2,0.976088,0.975831,0.977397,0.975562,0.975103,0.975996,0.000772,9,0.937718,0.936991,0.941757,0.936354,0.935149,0.937594,0.002246,9,0.961357,0.960933,0.963565,0.960508,0.959765,0.961226,0.001283,9,0.924568,0.923586,0.931887,0.923248,0.922027,0.925063,0.003507,9,56.636347,16.726168
10,mlp,search_01_initial,unsw_nb15,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.939520,0.938556,0.935318,0.937017,0.934918,0.937066,0.001784,9,0.864211,0.861132,0.867304,0.862314,0.860085,0.863009,0.002547,10,0.900293,0.898178,0.900028,0.898115,0.895942,0.898511,0.001571,10,0.966722,0.965987,0.967417,0.966249,0.965706,0.966416,0.000602,10,0.986093,0.985907,0.985005,0.985509,0.985031,0.985509,0.000443,1,0.976312,0.975846,0.976131,0.975784,0.975273,0.975869,0.000354,10,0.938302,0.937012,0.938079,0.936949,0.935607,0.937190,0.000962,10,0.961718,0.960954,0.961463,0.960869,0.960041,0.961009,0.000578,10,0.925152,0.923520,0.926154,0.923912,0.922558,0.924259,0.001261,10,45.996667,6.414000
4,mlp,search_01_initial,unsw_nb15,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.937421,0.936987,0.933928,0.935961,0.932454,0.935350,0.001884,11,0.861981,0.860389,0.867304,0.859554,0.855839,0.861013,0.003736,11,0.898119,0.897056,0.899384,0.896132,0.892505,0.896639,0.002334,11,0.966178,0.965799,0.967405,0.965589,0.964683,0.965931,0.000886,11,0.985615,0.985536,0.984659,0.985296,0.984500,0.985121,0.000457,3,0.975800,0.975567,0.975956,0.975343,0.974491,0.975432,0.000514,11,0.936960,0.936312,0.937670,0.935738,0.933498,0.936035,0.001423,11,0.960890,0.960508,0.961187,0.960147,0.958767,0.960300,0.000843,11,0.923798,0.922962,0.925982,0.922425,0.920169,0.923067,0.001889,11,36.256953,7.396790
0,mlp,search_01_initial,unsw_nb15,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.936512,0.936987,0.934035,0.935029,0.932239,0.934960,0.001719,12,0.861344,0.860389,0.867304,0.858599,0.855839,0.860695,0.003799,12,0.897356,0.897056,0.899433,0.895185,0.892406,0.896287,0.002362,12,0.966021,0.965799,0.967406,0.965356,0.964681,0.965853,0.000902,12,0.985403,0.985536,0.984686,0.985084,0.984447,0.985031,0.000414,4,0.975616,0.975567,0.975970,0.975120,0.974464,0.975347,0.000518,12,0.936486,0.936312,0.937701,0.935153,0.933435,0.935817,0.001439,12,0.960593,0.960508,0.961209,0.959786,0.958724,0.960164,0.000850,12,0.923374,0.922962,0.925995,0.921841,0.920143,0.922863,0.001925,12,32.859871,3.923935

modelo: mlp
 origem do treinamento: iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: mlp - iot23

,model,search_stage,training_source,training_rows,n_splits,random_state,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time
3,mlp,search_01_initial,iot23,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.999786,0.999785,0.999678,1.000000,0.999572,0.999764,0.000142,2,0.992887,0.989595,0.989490,0.991932,0.991826,0.991146,0.001361,2,0.996325,0.994664,0.994558,0.995950,0.995684,0.995436,0.000704,1,0.998225,0.997406,0.997379,0.997987,0.997960,0.997791,0.000339,2,0.999947,0.999947,0.999920,1.000000,0.999894,0.999942,0.000035,2,0.999085,0.998675,0.998648,0.998992,0.998926,0.998865,0.000174,2,0.997705,0.996670,0.996603,0.997471,0.997305,0.997151,0.000439,1,0.998535,0.997877,0.997834,0.998386,0.998280,0.998183,0.000279,1,0.996417,0.994771,0.994705,0.995966,0.995860,0.995544,0.000684,2,16.382547,1.432005
7,mlp,search_01_initial,iot23,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.999893,0.999785,0.999678,1.000000,0.999679,0.999807,0.000125,1,0.992887,0.989383,0.989703,0.991826,0.991720,0.991104,0.001342,3,0.996378,0.994557,0.994666,0.995896,0.995683,0.995436,0.000711,2,0.998225,0.997353,0.997432,0.997961,0.997934,0.997781,0.000334,3,0.999973,0.999947,0.999920,1.000000,0.999920,0.999952,0.000031,1,0.999098,0.998648,0.998675,0.998979,0.998926,0.998865,0.000176,1,0.997738,0.996603,0.996670,0.997438,0.997305,0.997151,0.000443,2,0.998556,0.997834,0.997877,0.998365,0.998280,0.998183,0.000282,1,0.996430,0.994665,0.994812,0.995913,0.995820,0.995528,0.000679,3,16.844240,1.766078
11,mlp,search_01_initial,iot23,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': False, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 200}",0.999573,0.999893,0.999464,1.000000,0.998077,0.999401,0.000691,7,0.992993,0.989808,0.989915,0.992038,0.991826,0.991316,0.001251,1,0.996272,0.994825,0.994667,0.996003,0.994942,0.995342,0.000661,3,0.998251,0.997459,0.997485,0.998013,0.997960,0.997833,0.000311,1,0.999894,0.999973,0.999867,1.000000,0.999522,0.999851,0.000172,7,0.999072,0.998714,0.998675,0.999006,0.998740,0.998841,0.000164,3,0.997672,0.996770,0.996671,0.997504,0.996841,0.997091,0.000413,3,0.998514,0.997940,0.997877,0.998408,0.997983,0.998144,0.000263,3,0.996443,0.994891,0.994891,0.996019,0.995674,0.995584,0.000616,1,14.048570,1.448573
6,mlp,search_01_initial,iot23,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.999359,1.000000,0.999464,0.999572,0.999572,0.999593,0.000218,4,0.992993,0.989383,0.989490,0.991614,0.991720,0.991040,0.001396,6,0.996166,0.994663,0.994452,0.995577,0.995630,0.995298,0.000642,4,0.998251,0.997353,0.997379,0.997907,0.997934,0.997765,0.000348,6,0.999841,1.000000,0.999867,0.999894,0.999894,0.999899,0.000054,4,0.999045,0.998675,0.998622,0.998900,0.998913,0.998831,0.000159,5,0.997606,0.996669,0.996537,0.997238,0.997272,0.997064,0.000400,4,0.998471,0.997877,0.997792,0.998238,0.998259,0.998127,0.000254,4,0.996417,0.994692,0.994679,0.995754,0.995807,0.995470,0.000682,6,29.186901,3.580842
2,mlp,search_01_initial,iot23,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.999466,1.000000,0.999571,0.999572,0.999465,0.999615,0.000198,3,0.992781,0.989383,0.989597,0.991614,0.991720,0.991019,0.001315,8,0.996112,0.994663,0.994559,0.995577,0.995577,0.995298,0.000595,5,0.998198,0.997353,0.997405,0.997907,0.997934,0.997760,0.000327,8,0.999867,1.000000,0.999894,0.999894,0.999867,0.999904,0.000049,3,0.999032,0.998675,0.998648,0.998900,0.998900,0.998831,0.000147,4,0.997572,0.996669,0.996603,0.997238,0.997238,0.997064,0.000371,5,0.998450,0.997877,0.997834,0.998238,0.998238,0.998127,0.000235,4,0.996324,0.994692,0.994745,0.995754,0.995794,0.995462,0.000640,7,26.886821,2.532221
9,mlp,search_01_initial,iot23,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.999786,1.000000,0.999143,0.999572,0.999251,0.999550,0.000321,5,0.992568,0.989489,0.989597,0.991932,0.991720,0.991061,0.001271,5,0.996164,0.994717,0.994347,0.995737,0.995471,0.995287,0.000666,6,0.998146,0.997379,0.997405,0.997987,0.997934,0.997770,0.000316,5,0.999947,1.000000,0.999788,0.999894,0.999814,0.999889,0.000079,5,0.999045,0.998688,0.998595,0.998939,0.998873,0.998828,0.000165,6,0.997605,0.996702,0.996471,0.997338,0.997172,0.997058,0.000415,6,0.998471,0.997898,0.997749,0.998301,0.998195,0.998123,0.000264,6,0.996258,0.994745,0.994692,0.995913,0.995767,0.995475,0.000638,4,12.046936,1.697972
1,mlp,search_01_initial,iot23,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.999679,0.999678,0.999250,0.999145,0.999465,0.999443,0.000218,6,0.992568,0.989702,0.989490,0.991932,0.991720,0.991082,0.001247,4,0.996111,0.994665,0.994346,0.995525,0.995577,0.995245,0.000646,7,0.998145,0.997432,0.997379,0.997987,0.997934,0.997775,0.000310,4,0.999920,0.999920,0.999814,0.999788,0.999867,0.999862,0.000054,6,0.999032,0.998675,0.998595,0.998886,0.998900,0.998818,0.000160,7,0.997572,0.996670,0.996471,0.997206,0.997238,0.997031,0.000403,7,0.998450,0.997877,0.997749,0.998216,0.998238,0.998106,0.000256,7,0.996244,0.994811,0.994652,0.995860,0.995794,0.995472,0.000626,5,8.530158,0.662569
5,mlp,search_01_initial,iot23,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.999145,0.999893,0.999250,0.999145,0.999358,0.999358,0.000279,8,0.992462,0.989595,0.989490,0.991932,0.991720,0.991040,0.001246,7,0.995792,0.994717,0.994346,0.995525,0.995524,0.995181,0.000552,8,0.998119,0.997406,0.997379,0.997987,0.997934,0.997765,0.000310,7,0.999788,0.999973,0.999814,0.999788,0.999841,0.999841,0.000069,8,0.998953,0.998688,0.998595,0.998886,0.998886,0.998802,0.000136,8,0.997372,0.996703,0.996471,0.997206,0.997205,0.996991,0.000344,8,0.998323,0.997898,0.997749,0.998216,0.998216,0.998081,0.000218,8,0.996125,0.994784,0.994652,0.995860,0.995780,0.995440,0.000602,8,8.583271,1.111236
10,mlp,search_01_initial,iot23,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.999252,0.997005,0.995939,0.997970,0.996798,0.997393,0.001132,9,0.992462,0.989489,0.989384,0.991401,0.991295,0.990806,0.001191,9,0.995845,0.993233,0.992651,0.994675,0.994039,0.994088,0.001116,9,0.998119,0.997377,0.997350,0.997854,0.997827,0.997705,0.000297,9,0.999814,0.999257,0.998991,0.999496,0.999204,0.999352,0.000281,9,0.998966,0.998316,0.998170,0.998674,0.998515,0.998528,0.000278,9,0.997406,0.995775,0.995411,0.996674,0.996277,0.996308,0.000697,9,0.998344,0.997303,0.997070,0.997877,0.997622,0.997643,0.000445,9,0.996138,0.994373,0.994188,0.995449,0.995249,0.995079,0.000718,9,13.385656,0.885294
8,mlp,search_01_initial,iot23,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.999252,0.997005,0.995833,0.997970,0.996798,0.997371,0.001160,10,0.992462,0.989489,0.989384,0.991401,0.991295,0.990806,0.001191,9,0.995845,0.993233,0.992598,0.994675,0.994039,0.994078,0.001130,10,0.998119,0.997377,0.997350,0.997854,0.997827,0.997705,0.000297,10,0.999814,0.999257,0.998965,0.999496,0.999204,0.999347,0.000288,10,0.998966,0.998316,0.998157,0.998674,0.998515,0.998526,0.000281,10,0.997406,0.995775,0.995378,0.996674,0.996277,0.996302,0.000706,10,0.998344,0.997303,0.997049,0.997877,0.997622,0.997639,0.000450,10,0.996138,0.994373,0.994175,0.995449,0.995249,0.995077,0.000722,10,15.497503,1.256067
0,mlp,search_01_initial,iot23,235490,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.999252,0.996791,0.995620,0.997756,0.997117,0.997307,0.001194,11,0.992568,0.989383,0.989384,0.991401,0.991295,0.990806,0.001245,9,0.995899,0.993073,0.992492,0.994569,0.994197,0.994046,0.001191,11,0.998145,0.997351,0.997350,0.997854,0.997827,0.997705,0.000311,11,0.999814,0.999204,0.998912,0.999443,0.999283,0.999331,0.000297,11,0.998979,0.998277,0.998130,0.998648,0.998555,0.998518,0.000296,11,0.997439,0.995675,0.995311,0.996608,0.996376,0.996282,0.000744,11,0.998365,0.997240,0.997006,0.997834,0.997686,0.997626,0.000475,11,0.996191,0.994293,0.994148,0.995422,0.995289,0.995069,0.000759,11,13.920950,0.842294
4,mlp,search_01_initial,iot23,235490,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.999252,0.996791,0.995514,0.997756,0.997010,0.997265,0.001228,12,0.992568,0.989383,0.989384,0.991401,0.991295,0.990806,0.001245,9,0.995899,0.993073,0.992440,0.994569,0.994145,0.994025,0.001203,12,0.998145,0.997351,0.997350,0.997854,0.997827,0.997705,0.000311,12,0.999814,0.999204,0.998885,0.999443,0.999257,0.999321,0.000305,12,0.998979,0.998277,0.998117,0.998648,0.998541,0.998512,0.000300,12,0.997439,0.995675,0.995278,0.996608,0.996343,0.996269,0.000751,12,0.998365,0.997240,0.996985,0.997834,0.997664,0.997618,0.000480,12,0.996191,0.994293,0.994135,0.995422,0.995276,0.995063,0.000762,12,14.112805,0.861079

modelo: mlp
 origem do treinamento: cicids2017_unsw_nb15
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: mlp - cicids2017_unsw_nb15

,model,search_stage,training_source,training_rows,n_splits,random_state,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time
3,mlp,search_01_initial,cicids2017_unsw_nb15,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.952022,0.953329,0.952271,0.951286,0.954848,0.952751,0.001236,5,0.991135,0.988853,0.987048,0.993046,0.990021,0.990021,0.002030,1,0.971185,0.970766,0.969348,0.971718,0.972117,0.971027,0.000957,1,0.997761,0.997187,0.996732,0.998242,0.997482,0.997481,0.000511,1,0.987513,0.987898,0.987632,0.987287,0.988296,0.987725,0.000347,7,0.992610,0.992521,0.992161,0.992735,0.992868,0.992579,0.000239,1,0.981898,0.981643,0.980755,0.982226,0.982492,0.981803,0.000598,1,0.988237,0.988089,0.987515,0.988439,0.988641,0.988184,0.000383,1,0.989324,0.988375,0.987340,0.990167,0.989158,0.988873,0.000955,1,106.600272,22.695777
7,mlp,search_01_initial,cicids2017_unsw_nb15,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.952447,0.950136,0.951768,0.944017,0.945163,0.948706,0.003463,11,0.989808,0.981103,0.977281,0.989968,0.988960,0.985424,0.005241,2,0.970768,0.965371,0.964356,0.966446,0.966566,0.966701,0.002186,2,0.997427,0.995237,0.994282,0.997461,0.997207,0.996323,0.001315,2,0.987645,0.987128,0.987619,0.985323,0.985655,0.986674,0.000991,11,0.992512,0.991166,0.990939,0.991355,0.991397,0.991474,0.000544,2,0.981640,0.978269,0.977648,0.978901,0.978981,0.979088,0.001364,2,0.988078,0.985923,0.985551,0.986252,0.986316,0.986424,0.000871,2,0.988727,0.984115,0.982450,0.987645,0.987307,0.986049,0.002366,2,73.390388,17.759304
6,mlp,search_01_initial,cicids2017_unsw_nb15,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.945114,0.952290,0.949224,0.952207,0.953361,0.950439,0.002997,10,0.981687,0.982165,0.980413,0.980360,0.980839,0.981093,0.000716,4,0.963054,0.966997,0.964566,0.966078,0.966905,0.965520,0.001510,3,0.995377,0.995506,0.995063,0.995053,0.995175,0.995235,0.000179,4,0.985748,0.987699,0.986889,0.987699,0.988004,0.987208,0.000818,10,0.990539,0.991587,0.990959,0.991362,0.991576,0.991205,0.000403,3,0.976796,0.979292,0.977763,0.978720,0.979240,0.978362,0.000957,3,0.984936,0.986592,0.985594,0.986231,0.986571,0.985985,0.000636,3,0.983717,0.984932,0.983651,0.984029,0.984421,0.984150,0.000476,4,167.064983,25.700227
11,mlp,search_01_initial,cicids2017_unsw_nb15,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': False, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 200}",0.953880,0.943808,0.942754,0.959434,0.959240,0.951823,0.007262,8,0.985880,0.987844,0.988694,0.979245,0.951858,0.978704,0.013826,5,0.969616,0.965324,0.965178,0.969238,0.955535,0.964978,0.005079,4,0.996440,0.996925,0.997139,0.994784,0.987987,0.994655,0.003435,5,0.988083,0.985297,0.984991,0.989649,0.989888,0.987582,0.002087,8,0.992244,0.991077,0.991028,0.992210,0.988937,0.991099,0.001202,4,0.980930,0.978200,0.978103,0.980724,0.972236,0.978039,0.003139,4,0.987643,0.985806,0.985732,0.987568,0.982282,0.985806,0.001945,4,0.986982,0.986571,0.986843,0.984447,0.970873,0.983143,0.006204,5,142.190210,10.662048
2,mlp,search_01_initial,cicids2017_unsw_nb15,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.942160,0.942646,0.949527,0.943361,0.944734,0.944486,0.002666,12,0.983969,0.987579,0.980625,0.983120,0.979936,0.983046,0.002718,3,0.962611,0.964589,0.964826,0.962830,0.962013,0.963374,0.001124,5,0.995947,0.996857,0.995116,0.995735,0.994937,0.995719,0.000682,3,0.984899,0.984978,0.986969,0.985244,0.985668,0.985551,0.000758,12,0.990392,0.990882,0.991026,0.990462,0.990281,0.990608,0.000292,5,0.976502,0.977736,0.977926,0.976646,0.976147,0.976991,0.000707,5,0.984713,0.985498,0.985700,0.984819,0.984522,0.985050,0.000463,5,0.984434,0.986279,0.983797,0.984182,0.982802,0.984299,0.001135,3,147.402547,16.154597
9,mlp,search_01_initial,cicids2017_unsw_nb15,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.941903,0.953156,0.951169,0.953215,0.953946,0.950678,0.004483,9,0.983651,0.938585,0.922289,0.979829,0.979618,0.960794,0.025357,6,0.962324,0.945814,0.936506,0.966339,0.966612,0.955519,0.012183,6,0.995867,0.984705,0.980719,0.994922,0.994870,0.990216,0.006266,6,0.984832,0.988468,0.988163,0.987977,0.988176,0.987523,0.001355,9,0.990319,0.986583,0.984427,0.991437,0.991512,0.988856,0.002851,6,0.976322,0.966199,0.960467,0.978888,0.979062,0.972187,0.007516,6,0.984596,0.978492,0.974988,0.986348,0.986464,0.982178,0.004624,6,0.984242,0.963527,0.955226,0.983903,0.983897,0.974159,0.012353,6,67.872510,19.062420
1,mlp,search_01_initial,cicids2017_unsw_nb15,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.953561,0.954287,0.953548,0.953895,0.953656,0.953790,0.000278,2,0.918839,0.918626,0.920750,0.923616,0.918577,0.920082,0.001942,7,0.935878,0.936117,0.936862,0.938511,0.935788,0.936631,0.001013,7,0.979893,0.979845,0.980357,0.981055,0.979829,0.980196,0.000472,7,0.988813,0.988999,0.988787,0.988840,0.988840,0.988856,0.000074,3,0.984333,0.984401,0.984554,0.984932,0.984314,0.984507,0.000229,7,0.960105,0.960259,0.960708,0.961722,0.960051,0.960569,0.000621,7,0.974818,0.974925,0.975179,0.975795,0.974787,0.975101,0.000374,7,0.953826,0.953813,0.954768,0.956228,0.953709,0.954469,0.000960,7,47.492547,8.485348
5,mlp,search_01_initial,cicids2017_unsw_nb15,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.953811,0.954844,0.951610,0.953823,0.952956,0.953409,0.001080,4,0.920750,0.919263,0.917565,0.923191,0.917144,0.919583,0.002214,8,0.936989,0.936716,0.934277,0.938257,0.934707,0.936189,0.001486,8,0.980358,0.980002,0.979574,0.980951,0.979478,0.980073,0.000540,8,0.988853,0.989132,0.988336,0.988827,0.988680,0.988765,0.000260,4,0.984587,0.984546,0.983935,0.984873,0.984058,0.984400,0.000350,8,0.960788,0.960631,0.959106,0.961565,0.959382,0.960294,0.000918,8,0.975232,0.975158,0.974181,0.975700,0.974373,0.974929,0.000567,8,0.954801,0.954197,0.952950,0.956009,0.952912,0.954174,0.001171,8,42.069774,6.656014
10,mlp,search_01_initial,cicids2017_unsw_nb15,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.952681,0.954881,0.953786,0.954508,0.956618,0.954495,0.001300,1,0.907320,0.913318,0.912575,0.912150,0.912951,0.911663,0.002206,9,0.929447,0.933637,0.932726,0.932848,0.934275,0.932587,0.001667,9,0.977103,0.978563,0.978378,0.978279,0.978482,0.978161,0.000538,9,0.988734,0.989211,0.988946,0.989132,0.989649,0.989134,0.000306,1,0.982884,0.983858,0.983633,0.983675,0.984034,0.983617,0.000393,9,0.956166,0.958748,0.958180,0.958262,0.959154,0.958102,0.001030,9,0.972451,0.974033,0.973672,0.973736,0.974309,0.973640,0.000636,9,0.948027,0.951265,0.950760,0.950641,0.951300,0.950399,0.001215,9,109.214980,10.710462
8,mlp,search_01_initial,cicids2017_unsw_nb15,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.952442,0.954479,0.953361,0.952280,0.955300,0.953572,0.001166,3,0.906789,0.904878,0.904931,0.905674,0.913163,0.907087,0.003116,10,0.929055,0.929017,0.928515,0.928393,0.933757,0.929747,0.002022,10,0.976974,0.976525,0.976531,0.976704,0.978527,0.977052,0.000755,10,0.988681,0.989211,0.988933,0.988654,0.989317,0.988959,0.000270,2,0.982792,0.982827,0.982693,0.982643,0.983892,0.982969,0.000466,10,0.955924,0.955922,0.955604,0.955518,0.958825,0.956358,0.001244,10,0.972302,0.972345,0.972133,0.972058,0.974086,0.972585,0.000758,10,0.947735,0.947045,0.946932,0.947164,0.951240,0.948023,0.001632,10,109.779212,26.133392
0,mlp,search_01_initial,cicids2017_unsw_nb15,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.951906,0.953282,0.950221,0.952879,0.953615,0.952381,0.001223,6,0.907745,0.901162,0.902808,0.918839,0.902442,0.906599,0.006517,11,0.929301,0.926490,0.925908,0.935549,0.927323,0.928914,0.003511,11,0.977201,0.975624,0.976002,0.979890,0.975932,0.976930,0.001574,11,0.988535,0.988959,0.988176,0.988641,0.989025,0.988667,0.000308,5,0.982835,0.982246,0.982051,0.984246,0.982435,0.982763,0.000785,11,0.956068,0.954368,0.953980,0.959897,0.954879,0.955838,0.002148,11,0.972377,0.971400,0.971103,0.974680,0.971708,0.972254,0.001285,11,0.948140,0.945061,0.945492,0.953740,0.945734,0.947633,0.003236,11,95.539879,16.394240
4,mlp,search_01_initial,cicids2017_unsw_nb15,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.952084,0.953628,0.951169,0.948608,0.953853,0.951868,0.001908,7,0.908116,0.900579,0.902649,0.904347,0.904034,0.903945,0.002473,12,0.929581,0.926345,0.926274,0.925949,0.928276,0.927285,0.001410,12,0.977292,0.975486,0.975969,0.976363,0.976316,0.976285,0.000593,12,0.988574,0.989052,0.988415,0.987752,0.989065,0.988572,0.000484,6,0.982901,0.982222,0.982153,0.982024,0.982650,0.982390,0.000331,12,0.956241,0.954283,0.954213,0.953987,0.955463,0.954837,0.000869,12,0.972483,0.971358,0.971262,0.971071,0.972058,0.971646,0.000535,12,0.948345,0.944815,0.945532,0.946050,0.946550,0.946258,0.001191,12,87.844022,16.609212

modelo: mlp
 origem do treinamento: cicids2017_iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: mlp - cicids2017_iot23

,model,search_stage,training_source,training_rows,n_splits,random_state,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time
7,mlp,search_01_initial,cicids2017_iot23,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.988223,0.986265,0.988255,0.987489,0.988740,0.987794,0.000863,1,0.988853,0.987207,0.987048,0.988747,0.988057,0.987983,0.000751,2,0.988538,0.986736,0.987651,0.988117,0.988398,0.987888,0.000651,1,0.997213,0.996801,0.996763,0.997186,0.997015,0.996996,0.000187,2,0.997054,0.996563,0.997067,0.996868,0.997187,0.996948,0.000218,1,0.997133,0.996682,0.996915,0.997027,0.997101,0.996972,0.000163,1,0.992836,0.991709,0.992283,0.992572,0.992750,0.992430,0.000407,1,0.995414,0.994692,0.995063,0.995244,0.995361,0.995155,0.000261,1,0.992953,0.991885,0.992058,0.992807,0.992622,0.992465,0.000420,2,72.185051,7.200296
3,mlp,search_01_initial,cicids2017_iot23,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.987546,0.986536,0.987919,0.987300,0.988005,0.987461,0.000528,2,0.989118,0.987897,0.985350,0.990392,0.988057,0.988163,0.001666,1,0.988331,0.987216,0.986633,0.988844,0.988031,0.987811,0.000791,2,0.997279,0.996973,0.996340,0.997596,0.997014,0.997040,0.000415,1,0.996882,0.996629,0.996988,0.996815,0.997001,0.996863,0.000135,2,0.997080,0.996801,0.996664,0.997206,0.997008,0.996952,0.000195,2,0.992706,0.992009,0.991648,0.993025,0.992519,0.992381,0.000493,2,0.995329,0.994883,0.994660,0.995531,0.995212,0.995123,0.000313,2,0.993000,0.992263,0.991169,0.993604,0.992529,0.992513,0.000812,1,69.906678,9.020776
11,mlp,search_01_initial,cicids2017_iot23,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': False, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 200}",0.984657,0.965116,0.988311,0.982160,0.987687,0.981586,0.008526,3,0.991295,0.985403,0.982855,0.987738,0.987792,0.987016,0.002805,3,0.987965,0.975154,0.985575,0.984941,0.987740,0.984275,0.004711,3,0.997820,0.996331,0.995720,0.996930,0.996948,0.996750,0.000700,3,0.996138,0.991096,0.997094,0.995515,0.996921,0.995353,0.002203,3,0.996978,0.993707,0.996406,0.996222,0.996935,0.996050,0.001208,3,0.992472,0.984430,0.990991,0.990582,0.992337,0.990162,0.002959,3,0.995170,0.989957,0.994246,0.993959,0.995095,0.993686,0.001923,3,0.993717,0.988249,0.989974,0.991626,0.992357,0.991185,0.001901,3,124.243512,21.370663
6,mlp,search_01_initial,cicids2017_iot23,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.965946,0.963988,0.963276,0.964512,0.965354,0.964615,0.000950,4,0.986199,0.981846,0.981581,0.983916,0.984979,0.983704,0.001781,5,0.975967,0.972835,0.972342,0.974118,0.975068,0.974066,0.001350,4,0.996532,0.995440,0.995373,0.995959,0.996225,0.995906,0.000446,5,0.991308,0.990830,0.990645,0.990950,0.991162,0.990979,0.000235,4,0.993913,0.993130,0.993003,0.993448,0.993687,0.993436,0.000338,4,0.984940,0.982983,0.982673,0.983783,0.984377,0.983751,0.000844,4,0.990286,0.989034,0.988832,0.989543,0.989925,0.989524,0.000541,4,0.988753,0.986338,0.986113,0.987433,0.988070,0.987342,0.001005,4,107.451482,20.740869
2,mlp,search_01_initial,cicids2017_iot23,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.965526,0.962880,0.963854,0.963880,0.964154,0.964059,0.000852,6,0.985668,0.983120,0.980891,0.985880,0.983652,0.983842,0.001831,4,0.975493,0.972895,0.972297,0.974756,0.973805,0.973849,0.001170,5,0.996398,0.995758,0.995202,0.996450,0.995892,0.995940,0.000458,4,0.991202,0.990525,0.990804,0.990764,0.990857,0.990830,0.000218,6,0.993793,0.993135,0.992998,0.993599,0.993368,0.993378,0.000292,5,0.984643,0.983015,0.982648,0.984177,0.983587,0.983614,0.000731,5,0.990095,0.989044,0.988821,0.989787,0.989416,0.989433,0.000467,5,0.988435,0.986823,0.985847,0.988322,0.987254,0.987336,0.000966,5,89.721124,10.227720
9,mlp,search_01_initial,cicids2017_iot23,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.965645,0.963204,0.962816,0.964862,0.964210,0.964147,0.001041,5,0.984713,0.982377,0.981368,0.983863,0.983811,0.983226,0.001194,6,0.975085,0.972696,0.972004,0.974270,0.973912,0.973593,0.001106,6,0.996159,0.995572,0.995320,0.995946,0.995932,0.995786,0.000300,6,0.991242,0.990618,0.990525,0.991043,0.990870,0.990859,0.000265,5,0.993694,0.993089,0.992917,0.993488,0.993394,0.993317,0.000279,6,0.984390,0.982892,0.982460,0.983879,0.983653,0.983455,0.000693,6,0.989936,0.988970,0.988694,0.989607,0.989458,0.989333,0.000446,6,0.987977,0.986497,0.985947,0.987453,0.987341,0.987043,0.000725,6,42.848951,5.640703
1,mlp,search_01_initial,cicids2017_iot23,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.962588,0.961364,0.962737,0.964433,0.963620,0.962949,0.001033,8,0.984713,0.980041,0.980572,0.981634,0.982749,0.981942,0.001668,7,0.973525,0.970613,0.971573,0.972957,0.973091,0.972352,0.001088,7,0.996156,0.994986,0.995121,0.995388,0.995666,0.995463,0.000418,7,0.990432,0.990154,0.990512,0.990950,0.990724,0.990554,0.000269,8,0.993286,0.992564,0.992811,0.993164,0.993189,0.993003,0.000272,7,0.983405,0.981588,0.982192,0.983061,0.983140,0.982677,0.000680,7,0.989288,0.988131,0.988524,0.989087,0.989129,0.988832,0.000435,7,0.987572,0.985097,0.985542,0.986292,0.986737,0.986248,0.000874,7,36.207760,13.630551
5,mlp,search_01_initial,cicids2017_iot23,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.965470,0.962033,0.962072,0.964535,0.964384,0.963699,0.001395,7,0.981050,0.981846,0.978874,0.981687,0.981635,0.981018,0.001106,8,0.973198,0.971838,0.970400,0.973036,0.972933,0.972281,0.001055,8,0.995243,0.995438,0.994695,0.995401,0.995388,0.995233,0.000277,8,0.991228,0.990313,0.990353,0.990976,0.990936,0.990761,0.000364,7,0.993232,0.992869,0.992519,0.993184,0.993157,0.992992,0.000268,8,0.983215,0.982354,0.981460,0.983110,0.983045,0.982637,0.000662,8,0.989193,0.988619,0.988057,0.989118,0.989076,0.988813,0.000428,8,0.986139,0.986079,0.984613,0.986332,0.986286,0.985890,0.000645,8,32.838017,10.450908
8,mlp,search_01_initial,cicids2017_iot23,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.963256,0.960625,0.960893,0.963029,0.962565,0.962074,0.001100,9,0.981050,0.979033,0.978184,0.980307,0.979936,0.979702,0.000999,9,0.972072,0.969742,0.969461,0.971591,0.971173,0.970808,0.001029,9,0.995241,0.994733,0.994521,0.995055,0.994961,0.994902,0.000251,9,0.990645,0.989968,0.990047,0.990591,0.990472,0.990345,0.000282,9,0.992937,0.992345,0.992279,0.992818,0.992711,0.992618,0.000261,9,0.982504,0.981043,0.980870,0.982204,0.981942,0.981713,0.000645,9,0.988726,0.987781,0.987675,0.988535,0.988365,0.988216,0.000416,9,0.985847,0.984500,0.984115,0.985449,0.985204,0.985023,0.000631,9,61.792748,5.532763
10,mlp,search_01_initial,cicids2017_iot23,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.962870,0.960529,0.960997,0.962802,0.962629,0.961966,0.000996,10,0.980094,0.979139,0.978290,0.978237,0.980308,0.979214,0.000870,10,0.971406,0.969745,0.969566,0.970458,0.971388,0.970513,0.000781,10,0.995001,0.994759,0.994548,0.994537,0.995054,0.994780,0.000218,10,0.990552,0.989941,0.990074,0.990552,0.990485,0.990321,0.000260,10,0.992772,0.992344,0.992306,0.992540,0.992764,0.992545,0.000198,10,0.982089,0.981045,0.980936,0.981499,0.982076,0.981529,0.000490,10,0.988460,0.987781,0.987717,0.988089,0.988450,0.988099,0.000316,10,0.985323,0.984540,0.984182,0.984394,0.985397,0.984767,0.000498,10,46.569025,4.369213
0,mlp,search_01_initial,cicids2017_iot23,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.962926,0.960388,0.959079,0.961929,0.960957,0.961056,0.001313,11,0.978874,0.976803,0.972875,0.976379,0.974575,0.975901,0.002039,11,0.970834,0.968526,0.965928,0.969100,0.967718,0.968421,0.001613,11,0.994697,0.994176,0.993194,0.994073,0.993621,0.993952,0.000510,11,0.990578,0.989928,0.989623,0.990339,0.990100,0.990114,0.000329,11,0.992633,0.992047,0.991405,0.992202,0.991857,0.992029,0.000403,11,0.981734,0.980287,0.978667,0.980651,0.979788,0.980225,0.001008,11,0.988237,0.987303,0.986273,0.987547,0.986995,0.987271,0.000645,11,0.984726,0.983366,0.981249,0.983359,0.982338,0.983008,0.001161,11,35.591187,10.192048
4,mlp,search_01_initial,cicids2017_iot23,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.962899,0.959347,0.959081,0.961085,0.960904,0.960663,0.001376,12,0.979511,0.973300,0.972928,0.974043,0.974522,0.974861,0.002391,12,0.971134,0.966273,0.965955,0.967521,0.967665,0.967710,0.001839,12,0.994856,0.993301,0.993208,0.993489,0.993608,0.993692,0.000598,12,0.990565,0.989689,0.989623,0.990140,0.990087,0.990021,0.000342,12,0.992706,0.991492,0.991412,0.991812,0.991844,0.991853,0.000459,12,0.981920,0.978882,0.978684,0.979666,0.979755,0.979781,0.001149,12,0.988354,0.986411,0.986284,0.986921,0.986974,0.986989,0.000735,12,0.985038,0.981495,0.981276,0.982092,0.982305,0.982441,0.001352,12,31.131944,11.622992

modelo: mlp
 origem do treinamento: unsw_nb15_iot23
Fitting 5 folds for each of 12 candidates, totalling 60 fits
resultados dos hiperparâmetros: mlp - unsw_nb15_iot23

,model,search_stage,training_source,training_rows,n_splits,random_state,params,split0_test_precision_attack,split1_test_precision_attack,split2_test_precision_attack,split3_test_precision_attack,split4_test_precision_attack,mean_test_precision_attack,std_test_precision_attack,rank_test_precision_attack,split0_test_recall_attack,split1_test_recall_attack,split2_test_recall_attack,split3_test_recall_attack,split4_test_recall_attack,mean_test_recall_attack,std_test_recall_attack,rank_test_recall_attack,split0_test_f1_attack,split1_test_f1_attack,split2_test_f1_attack,split3_test_f1_attack,split4_test_f1_attack,mean_test_f1_attack,std_test_f1_attack,rank_test_f1_attack,split0_test_precision_benign,split1_test_precision_benign,split2_test_precision_benign,split3_test_precision_benign,split4_test_precision_benign,mean_test_precision_benign,std_test_precision_benign,rank_test_precision_benign,split0_test_recall_benign,split1_test_recall_benign,split2_test_recall_benign,split3_test_recall_benign,split4_test_recall_benign,mean_test_recall_benign,std_test_recall_benign,rank_test_recall_benign,split0_test_f1_benign,split1_test_f1_benign,split2_test_f1_benign,split3_test_f1_benign,split4_test_f1_benign,mean_test_f1_benign,std_test_f1_benign,rank_test_f1_benign,split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,mean_fit_time,std_fit_time
7,mlp,search_01_initial,unsw_nb15_iot23,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.967549,0.965125,0.966589,0.966052,0.966943,0.966452,0.000823,1,0.987579,0.991560,0.988959,0.992409,0.990552,0.990212,0.001747,1,0.977461,0.978164,0.977646,0.979053,0.978605,0.978186,0.000591,1,0.996879,0.997875,0.997224,0.998089,0.997623,0.997538,0.000438,1,0.991719,0.991043,0.991454,0.991282,0.991534,0.991406,0.000230,1,0.994292,0.994447,0.994331,0.994674,0.994569,0.994463,0.000143,1,0.985877,0.986306,0.985988,0.986863,0.986587,0.986324,0.000367,1,0.990891,0.991146,0.990955,0.991507,0.991337,0.991167,0.000231,1,0.989649,0.991301,0.990207,0.991845,0.991043,0.990809,0.000785,1,105.362979,9.800482
3,mlp,search_01_initial,unsw_nb15_iot23,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.966700,0.965056,0.966245,0.966005,0.966698,0.966141,0.000605,2,0.987738,0.990976,0.989171,0.992516,0.989172,0.989915,0.001657,2,0.977106,0.977844,0.977574,0.979081,0.977806,0.977882,0.000655,2,0.996918,0.997729,0.997277,0.998116,0.997277,0.997463,0.000416,2,0.991494,0.991029,0.991361,0.991268,0.991480,0.991327,0.000170,2,0.994198,0.994368,0.994310,0.994680,0.994370,0.994385,0.000160,2,0.985652,0.986106,0.985942,0.986881,0.986088,0.986134,0.000407,2,0.990743,0.991019,0.990923,0.991518,0.991019,0.991044,0.000257,2,0.989616,0.991003,0.990266,0.991892,0.990326,0.990621,0.000772,2,96.477137,12.775769
11,mlp,search_01_initial,unsw_nb15_iot23,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': False, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 200}",0.956164,0.957884,0.958027,0.965124,0.970117,0.961463,0.005310,6,0.973725,0.989968,0.969266,0.970964,0.966667,0.974118,0.008251,3,0.964864,0.973662,0.963614,0.968036,0.968389,0.967713,0.003489,3,0.993401,0.997471,0.992294,0.992730,0.991674,0.993514,0.002057,3,0.988840,0.989118,0.989384,0.991228,0.992555,0.990225,0.001434,10,0.991115,0.993277,0.990837,0.991979,0.992114,0.991864,0.000859,3,0.977990,0.983469,0.977225,0.980007,0.980251,0.979789,0.002173,3,0.985817,0.989288,0.985360,0.987176,0.987377,0.987004,0.001378,3,0.981282,0.989543,0.979325,0.981096,0.979611,0.982172,0.003767,3,161.249849,4.715002
6,mlp,search_01_initial,unsw_nb15_iot23,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.965409,0.949405,0.962279,0.961595,0.964742,0.960686,0.005820,7,0.967408,0.987101,0.928924,0.966240,0.965817,0.963098,0.018867,4,0.966408,0.967886,0.945307,0.963912,0.965279,0.961759,0.008329,4,0.991848,0.996743,0.982384,0.991550,0.991452,0.990795,0.004653,4,0.991335,0.986849,0.990897,0.990353,0.991175,0.990122,0.001670,11,0.991591,0.991771,0.986622,0.990951,0.991313,0.990450,0.001934,4,0.978999,0.979829,0.965965,0.977432,0.978296,0.976104,0.005131,4,0.986549,0.986900,0.978502,0.985530,0.986103,0.984717,0.003141,4,0.979371,0.986975,0.959910,0.978296,0.978496,0.976610,0.008948,4,116.307939,26.250016
2,mlp,search_01_initial,unsw_nb15_iot23,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100, 50), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.961847,0.962114,0.963079,0.963446,0.963871,0.962871,0.000774,3,0.930039,0.982695,0.966453,0.965338,0.930361,0.954977,0.021143,5,0.945675,0.972296,0.964763,0.964391,0.946820,0.958789,0.010628,5,0.982653,0.995651,0.991606,0.991330,0.982739,0.988796,0.005210,5,0.990777,0.990326,0.990737,0.990844,0.991281,0.990793,0.000304,3,0.986699,0.992981,0.991171,0.991087,0.986992,0.989786,0.002496,5,0.966187,0.982639,0.977967,0.977739,0.966906,0.974287,0.006562,5,0.978630,0.988800,0.985881,0.985742,0.979097,0.983630,0.004045,5,0.960408,0.986511,0.978595,0.978091,0.960821,0.972885,0.010455,5,110.573455,39.764349
5,mlp,search_01_initial,unsw_nb15_iot23,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.961573,0.959328,0.964610,0.964386,0.963194,0.962618,0.001967,4,0.968310,0.930251,0.965019,0.965922,0.927866,0.951474,0.018349,6,0.964930,0.944566,0.964815,0.965153,0.945200,0.956933,0.009841,6,0.992064,0.982694,0.991254,0.991477,0.982129,0.987924,0.004512,6,0.990326,0.990140,0.991149,0.991082,0.991135,0.990767,0.000440,5,0.991194,0.986403,0.991201,0.991280,0.986612,0.989338,0.002312,6,0.978062,0.965484,0.978008,0.978217,0.965906,0.973135,0.006077,6,0.985923,0.978163,0.985923,0.986050,0.978481,0.982908,0.003746,6,0.979318,0.960196,0.978084,0.978502,0.959501,0.971120,0.009215,6,51.600212,25.370677
9,mlp,search_01_initial,unsw_nb15_iot23,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.965106,0.961642,0.964874,0.961530,0.947011,0.960033,0.006687,12,0.966028,0.928871,0.963799,0.928712,0.969480,0.951378,0.018530,7,0.965567,0.944972,0.964336,0.944836,0.958114,0.955565,0.009064,7,0.991505,0.982368,0.990952,0.982329,0.992324,0.987896,0.004550,7,0.991268,0.990737,0.991228,0.990711,0.986438,0.990077,0.001835,12,0.991387,0.986535,0.991090,0.986502,0.989372,0.988977,0.002122,7,0.978477,0.965754,0.977713,0.965669,0.973743,0.972271,0.005592,7,0.986220,0.978364,0.985742,0.978311,0.983046,0.982337,0.003440,7,0.978648,0.959804,0.977513,0.959711,0.977959,0.970727,0.008964,7,48.614339,13.971624
1,mlp,search_01_initial,unsw_nb15_iot23,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.001, 'classifier__max_iter': 300}",0.961955,0.959542,0.964456,0.962356,0.963806,0.962423,0.001707,5,0.966346,0.930357,0.963586,0.928181,0.930042,0.943703,0.017400,8,0.964146,0.944724,0.964021,0.944959,0.946623,0.952895,0.009159,8,0.991577,0.982721,0.990899,0.982203,0.982662,0.986012,0.004276,8,0.990445,0.990193,0.991122,0.990923,0.991268,0.990790,0.000408,4,0.991011,0.986443,0.991010,0.986544,0.986946,0.988391,0.002146,8,0.977578,0.965584,0.977516,0.965752,0.966785,0.970643,0.005652,8,0.985626,0.978226,0.985615,0.978375,0.979022,0.981373,0.003478,8,0.978396,0.960275,0.977354,0.959552,0.960655,0.967247,0.008692,8,40.682071,8.750786
10,mlp,search_01_initial,unsw_nb15_iot23,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.960315,0.959176,0.960205,0.960159,0.962651,0.960501,0.001150,8,0.926111,0.924147,0.926005,0.922342,0.927548,0.925230,0.001803,11,0.942903,0.941335,0.942795,0.940871,0.944773,0.942535,0.001373,9,0.981691,0.981208,0.981665,0.980775,0.982050,0.981478,0.000441,11,0.990432,0.990167,0.990406,0.990432,0.991003,0.990488,0.000276,7,0.986042,0.985667,0.986016,0.985580,0.986506,0.985962,0.000328,9,0.964472,0.963501,0.964405,0.963225,0.965640,0.964249,0.000850,9,0.977568,0.976963,0.977526,0.976814,0.978311,0.977436,0.000529,9,0.958271,0.957157,0.958205,0.956387,0.959275,0.957859,0.000996,10,73.113932,9.157611
4,mlp,search_01_initial,unsw_nb15_iot23,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.959190,0.958830,0.960029,0.959899,0.962610,0.960111,0.001325,10,0.923244,0.927172,0.926854,0.923722,0.926486,0.925496,0.001664,9,0.940874,0.942735,0.943150,0.941463,0.944203,0.942485,0.001191,10,0.980989,0.981942,0.981870,0.981109,0.981791,0.981540,0.000406,9,0.990180,0.990047,0.990353,0.990353,0.991003,0.990387,0.000329,9,0.985563,0.985978,0.986093,0.985709,0.986376,0.985944,0.000286,10,0.963219,0.964357,0.964621,0.963586,0.965289,0.964214,0.000739,10,0.976793,0.977473,0.977653,0.977027,0.978099,0.977409,0.000462,10,0.956712,0.958610,0.958603,0.957037,0.958744,0.957941,0.000878,9,68.748438,10.445237
8,mlp,search_01_initial,unsw_nb15_iot23,470980,5,1,"{'classifier__alpha': 0.001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (100,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.960266,0.959121,0.960168,0.960391,0.962545,0.960498,0.001119,9,0.926217,0.924094,0.922554,0.924094,0.927548,0.924901,0.001763,12,0.942934,0.941281,0.940985,0.941893,0.944722,0.942363,0.001355,11,0.981717,0.981195,0.980827,0.981201,0.982049,0.981398,0.000432,12,0.990419,0.990154,0.990432,0.990472,0.990976,0.990491,0.000268,6,0.986049,0.985654,0.985606,0.985815,0.986492,0.985923,0.000324,11,0.964491,0.963468,0.963296,0.963854,0.965607,0.964143,0.000839,11,0.977579,0.976942,0.976857,0.977196,0.978290,0.977373,0.000523,11,0.958318,0.957124,0.956493,0.957283,0.959262,0.957696,0.000978,12,82.377551,9.821805
0,mlp,search_01_initial,unsw_nb15_iot23,470980,5,1,"{'classifier__alpha': 0.0001, 'classifier__early_stopping': True, 'classifier__hidden_layer_sizes': (50,), 'classifier__learning_rate_init': 0.0001, 'classifier__max_iter': 300}",0.959089,0.958880,0.960284,0.959905,0.962397,0.960111,0.001254,11,0.923350,0.927119,0.925368,0.923881,0.926486,0.925241,0.001450,10,0.940881,0.942732,0.942503,0.941549,0.944100,0.942353,0.001099,12,0.981015,0.981930,0.981510,0.981147,0.981790,0.981479,0.000354,10,0.990154,0.990061,0.990432,0.990353,0.990950,0.990390,0.000310,8,0.985563,0.985978,0.985951,0.985729,0.986349,0.985914,0.000265,12,0.963222,0.964355,0.964227,0.963639,0.965225,0.964133,0.000682,12,0.976793,0.977473,0.977419,0.977058,0.978056,0.977360,0.000427,12,0.956752,0.958590,0.957900,0.957117,0.958718,0.957815,0.000780,11,62.912287,7.282300

,model,search_stage,training_source,training_rows,best_parameters,elapsed_minutes,model_size_mb,model_file,precision_attack_mean,precision_attack_std,recall_attack_mean,recall_attack_std,f1_attack_mean,f1_attack_std,precision_benign_mean,precision_benign_std,recall_benign_mean,recall_benign_std,f1_benign_mean,f1_benign_std,f1_macro_mean,f1_macro_std,accuracy_mean,accuracy_std,balanced_accuracy_mean,balanced_accuracy_std
0,mlp,search_01_initial,cicids2017,235490,"{""classifier__alpha"": 0.0001, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.001, ""classifier__max_iter"": 300}",3.888754,0.156008,cicids2017.joblib,0.978111,0.001851,0.991273,0.000807,0.984647,0.000919,0.997811,0.000202,0.994453,0.000482,0.996129,0.000236,0.990388,0.000577,0.993817,0.000375,0.992863,0.000410
1,mlp,search_01_initial,unsw_nb15,235490,"{""classifier__alpha"": 0.0001, ""classifier__early_stopping"": false, ""classifier__hidden_layer_sizes"": [100], ""classifier__learning_rate_init"": 0.001, ""classifier__max_iter"": 200}",5.187929,0.062370,unsw_nb15.joblib,0.939766,0.001106,0.996433,0.000851,0.967270,0.000780,0.999095,0.000216,0.984033,0.000310,0.991507,0.000205,0.979388,0.000493,0.986513,0.000325,0.990233,0.000479
2,mlp,search_01_initial,iot23,235490,"{""classifier__alpha"": 0.0001, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.001, ""classifier__max_iter"": 300}",1.584303,0.156344,iot23.joblib,0.999764,0.000142,0.991146,0.001361,0.995436,0.000704,0.997791,0.000339,0.999942,0.000035,0.998865,0.000174,0.997151,0.000439,0.998183,0.000279,0.995544,0.000684
3,mlp,search_01_initial,cicids2017_unsw_nb15,470980,"{""classifier__alpha"": 0.0001, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.001, ""classifier__max_iter"": 300}",10.473304,0.156279,cicids2017_unsw_nb15.joblib,0.952751,0.001236,0.990021,0.002030,0.971027,0.000957,0.997481,0.000511,0.987725,0.000347,0.992579,0.000239,0.981803,0.000598,0.988184,0.000383,0.988873,0.000955
4,mlp,search_01_initial,cicids2017_iot23,470980,"{""classifier__alpha"": 0.001, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.001, ""classifier__max_iter"": 300}",7.343420,0.151773,cicids2017_iot23.joblib,0.987794,0.000863,0.987983,0.000751,0.987888,0.000651,0.996996,0.000187,0.996948,0.000218,0.996972,0.000163,0.992430,0.000407,0.995155,0.000261,0.992465,0.000420
5,mlp,search_01_initial,unsw_nb15_iot23,470980,"{""classifier__alpha"": 0.001, ""classifier__early_stopping"": true, ""classifier__hidden_layer_sizes"": [100, 50], ""classifier__learning_rate_init"": 0.001, ""classifier__max_iter"": 300}",9.262300,0.156699,unsw_nb15_iot23.joblib,0.966452,0.000823,0.990212,0.001747,0.978186,0.000591,0.997538,0.000438,0.991406,0.000230,0.994463,0.000143,0.986324,0.000367,0.991167,0.000231,0.990809,0.000785