In [1]:
import sys
from pathlib import Path
from time import perf_counter

import joblib
import pandas as pd
from sklearn.metrics import (
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
)

ROOT = Path(r"C:\tcc\network-ids-ml-generalization")
DATA_DIR = ROOT / "datasets" / "final" / "ml"
MODEL_DIR = ROOT / "models" / "randomized_search"
TRAINING_RESULTS_DIR = ROOT / "results" / "model_training" / "randomized_search"
OUTPUT_DIR = ROOT / "results" / "model_evaluation"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(ROOT))
from src.utils.features import split_features

reference_df = pd.read_parquet(DATA_DIR / "cicids2017_train.parquet")
numerical_features, categorical_features = split_features(reference_df)
feature_columns = numerical_features + categorical_features
del reference_df

TEST_CONFIGS = {
    "cicids2017": ["cicids2017", "iot23", "unsw_nb15"],
    "unsw_nb15": ["unsw_nb15", "cicids2017", "iot23"],
    "iot23": ["iot23", "cicids2017", "unsw_nb15"],
    "cicids2017_unsw_nb15": ["iot23"],
    "cicids2017_iot23": ["unsw_nb15"],
    "unsw_nb15_iot23": ["cicids2017"],
}

TEST_DATASETS = ["cicids2017", "iot23", "unsw_nb15"]
SINGLE_DATASET_TRAINING = set(TEST_DATASETS)
MODELS_TO_EVALUATE = [
    "decision_tree",
    "random_forest",
    "xgboost",
    "linear_svm",
    "mlp",
]
SELECTION_METHOD = "randomized_search"

In [2]:
CV_METRICS = [
    "precision_attack",
    "recall_attack",
    "f1_attack",
    "precision_benign",
    "recall_benign",
    "f1_benign",
    "f1_macro",
    "accuracy",
    "balanced_accuracy",
]


def load_training_summaries():
    frames = []

    for model_name in MODELS_TO_EVALUATE:
        summary_path = TRAINING_RESULTS_DIR / model_name / "summary.csv"
        if not summary_path.exists():
            raise FileNotFoundError(
                f"Resumo de treinamento não encontrado: {summary_path}. "
                "Execute primeiro o notebook 07_model_training.ipynb."
            )
        frames.append(pd.read_csv(summary_path))

    summaries = pd.concat(frames, ignore_index=True)
    return summaries.set_index(["model", "training_source"])


def scenario_type(training_name, test_name):
    if training_name == test_name:
        return "intra_dataset"
    if training_name in SINGLE_DATASET_TRAINING:
        return "cross_dataset"
    return "combined_to_unseen"


def training_metadata(summary_row):
    metadata = {
        "search_method": summary_row.get("search_method", SELECTION_METHOD),
        "selection_metric": summary_row.get("selection_metric"),
        "training_rows": summary_row.get("training_rows"),
        "params": summary_row.get("params", "{}"),
        "cv_n_splits": summary_row.get("n_splits"),
        "random_state": summary_row.get("random_state"),
        "training_elapsed_seconds": summary_row.get("elapsed_seconds"),
        "training_elapsed_minutes": summary_row.get("elapsed_minutes"),
        "final_fit_time_seconds": summary_row.get("refit_time_seconds"),
        "model_size_mb": summary_row.get("model_size_mb"),
    }

    for metric in CV_METRICS:
        metadata[f"cv_{metric}_mean"] = summary_row.get(f"{metric}_mean")
        metadata[f"cv_{metric}_std"] = summary_row.get(f"{metric}_std")

    return metadata

In [3]:
columns_to_load = feature_columns + ["label_binary"]
test_dataframes = {
    dataset_name: pd.read_parquet(
        DATA_DIR / f"{dataset_name}_test.parquet",
        columns=columns_to_load,
    )
    for dataset_name in TEST_DATASETS
}

training_summaries = load_training_summaries()
evaluation_results = []

for training_name, test_names in TEST_CONFIGS.items():
    for model_name in MODELS_TO_EVALUATE:
        model_path = MODEL_DIR / model_name / f"{training_name}.joblib"
        if not model_path.exists():
            raise FileNotFoundError(f"Modelo vencedor não encontrado: {model_path}")

        pipeline = joblib.load(model_path)
        summary_row = training_summaries.loc[(model_name, training_name)]
        report_dir = OUTPUT_DIR / training_name / model_name
        report_dir.mkdir(parents=True, exist_ok=True)

        for test_name in test_names:
            test_df = test_dataframes[test_name]
            X_test = test_df[feature_columns]
            y_test = test_df["label_binary"].eq("ATTACK").astype("int8")

            prediction_start = perf_counter()
            predictions = pipeline.predict(X_test)
            prediction_time_seconds = perf_counter() - prediction_start

            metrics_start = perf_counter()
            report_values = classification_report(
                y_test,
                predictions,
                labels=[0, 1],
                target_names=["BENIGN", "ATTACK"],
                output_dict=True,
                zero_division=0,
            )
            report_text = classification_report(
                y_test,
                predictions,
                labels=[0, 1],
                target_names=["BENIGN", "ATTACK"],
                digits=4,
                zero_division=0,
            )
            matrix_values = confusion_matrix(y_test, predictions, labels=[0, 1])
            balanced_accuracy = balanced_accuracy_score(y_test, predictions)
            metrics_calculation_time_seconds = perf_counter() - metrics_start

            matrix = pd.DataFrame(
                matrix_values,
                index=["Real BENIGN", "Real ATTACK"],
                columns=["Predito BENIGN", "Predito ATTACK"],
            )
            true_negative, false_positive, false_negative, true_positive = (
                matrix_values.ravel()
            )

            title = (
                f"Treino: {training_name} | Modelo: {model_name} | "
                f"Teste: {test_name}"
            )
            report_path = report_dir / f"randomized_search_{test_name}.txt"
            matrix_path = (
                report_dir / f"randomized_search_{test_name}_confusion_matrix.txt"
            )
            report_path.write_text(
                f"{title}\n\n{report_text}",
                encoding="utf-8",
            )
            matrix_path.write_text(
                f"{title}\n\n{matrix}",
                encoding="utf-8",
            )

            result = {
                "model": model_name,
                "selection_method": SELECTION_METHOD,
                "training_source": training_name,
                "test_source": test_name,
                "scenario_type": scenario_type(training_name, test_name),
                "test_rows": len(test_df),
                "benign_support": int(report_values["BENIGN"]["support"]),
                "attack_support": int(report_values["ATTACK"]["support"]),
                "accuracy": report_values["accuracy"],
                "balanced_accuracy": balanced_accuracy,
                "precision_benign": report_values["BENIGN"]["precision"],
                "recall_benign": report_values["BENIGN"]["recall"],
                "f1_benign": report_values["BENIGN"]["f1-score"],
                "precision_attack": report_values["ATTACK"]["precision"],
                "recall_attack": report_values["ATTACK"]["recall"],
                "f1_attack": report_values["ATTACK"]["f1-score"],
                "f1_macro": report_values["macro avg"]["f1-score"],
                "f1_weighted": report_values["weighted avg"]["f1-score"],
                "true_negative": int(true_negative),
                "false_positive": int(false_positive),
                "false_negative": int(false_negative),
                "true_positive": int(true_positive),
                "prediction_time_seconds": prediction_time_seconds,
                "prediction_rows_per_second": (
                    len(test_df) / prediction_time_seconds
                    if prediction_time_seconds > 0
                    else float("inf")
                ),
                "metrics_calculation_time_seconds": metrics_calculation_time_seconds,
                "model_file": str(model_path.relative_to(ROOT)),
                "classification_report_file": str(report_path.relative_to(ROOT)),
                "confusion_matrix_file": str(matrix_path.relative_to(ROOT)),
            }
            result.update(training_metadata(summary_row))
            evaluation_results.append(result)

evaluation_df = pd.DataFrame(evaluation_results).sort_values(
    ["training_source", "test_source", "model"]
)

expected_evaluations = len(MODELS_TO_EVALUATE) * sum(
    len(test_names) for test_names in TEST_CONFIGS.values()
)
assert len(evaluation_df) == expected_evaluations
assert not evaluation_df.duplicated(
    ["model", "training_source", "test_source"]
).any()

evaluation_df.to_csv(OUTPUT_DIR / "evaluation_summary.csv", index=False)
display(evaluation_df)

,model,selection_method,training_source,test_source,scenario_type,test_rows,benign_support,attack_support,accuracy,balanced_accuracy,...,cv_recall_benign_mean,cv_recall_benign_std,cv_f1_benign_mean,cv_f1_benign_std,cv_f1_macro_mean,cv_f1_macro_std,cv_accuracy_mean,cv_accuracy_std,cv_balanced_accuracy_mean,cv_balanced_accuracy_std
0,decision_tree,randomized_search,cicids2017,cicids2017,intra_dataset,100925,80740,20185,0.994055,0.992123,...,0.995377,0.000327,0.996133,0.000145,0.990361,0.000363,0.993817,0.000232,0.991478,0.000652
9,linear_svm,randomized_search,cicids2017,cicids2017,intra_dataset,100925,80740,20185,0.931504,0.942829,...,0.924174,0.001156,0.955983,0.000880,0.902885,0.001845,0.931916,0.001341,0.943530,0.001734
12,mlp,randomized_search,cicids2017,cicids2017,intra_dataset,100925,80740,20185,0.993906,0.993702,...,0.994225,0.000591,0.996274,0.000333,0.990762,0.000817,0.994051,0.000530,0.993790,0.000533
3,random_forest,randomized_search,cicids2017,cicids2017,intra_dataset,100925,80740,20185,0.995145,0.995832,...,0.994798,0.000482,0.996976,0.000235,0.992505,0.000577,0.995172,0.000374,0.995732,0.000407
6,xgboost,randomized_search,cicids2017,cicids2017,intra_dataset,100925,80740,20185,0.994570,0.994210,...,0.995186,0.000292,0.996715,0.000241,0.991836,0.000601,0.994751,0.000386,0.994100,0.000783
1,decision_tree,randomized_search,cicids2017,iot23,cross_dataset,100925,80740,20185,0.804865,0.523105,...,0.995377,0.000327,0.996133,0.000145,0.990361,0.000363,0.993817,0.000232,0.991478,0.000652
10,linear_svm,randomized_search,cicids2017,iot23,cross_dataset,100925,80740,20185,0.286242,0.552452,...,0.924174,0.001156,0.955983,0.000880,0.902885,0.001845,0.931916,0.001341,0.943530,0.001734
13,mlp,randomized_search,cicids2017,iot23,cross_dataset,100925,80740,20185,0.250671,0.460497,...,0.994225,0.000591,0.996274,0.000333,0.990762,0.000817,0.994051,0.000530,0.993790,0.000533
4,random_forest,randomized_search,cicids2017,iot23,cross_dataset,100925,80740,20185,0.097052,0.063296,...,0.994798,0.000482,0.996976,0.000235,0.992505,0.000577,0.995172,0.000374,0.995732,0.000407
7,xgboost,randomized_search,cicids2017,iot23,cross_dataset,100925,80740,20185,0.789814,0.495287,...,0.995186,0.000292,0.996715,0.000241,0.991836,0.000601,0.994751,0.000386,0.994100,0.000783
2,decision_tree,randomized_search,cicids2017,unsw_nb15,cross_dataset,100925,80740,20185,0.777221,0.486859,...,0.995377,0.000327,0.996133,0.000145,0.990361,0.000363,0.993817,0.000232,0.991478,0.000652
11,linear_svm,randomized_search,cicids2017,unsw_nb15,cross_dataset,100925,80740,20185,0.795066,0.497548,...,0.924174,0.001156,0.955983,0.000880,0.902885,0.001845,0.931916,0.001341,0.943530,0.001734
14,mlp,randomized_search,cicids2017,unsw_nb15,cross_dataset,100925,80740,20185,0.797860,0.499053,...,0.994225,0.000591,0.996274,0.000333,0.990762,0.000817,0.994051,0.000530,0.993790,0.000533
5,random_forest,randomized_search,cicids2017,unsw_nb15,cross_dataset,100925,80740,20185,0.799931,0.499957,...,0.994798,0.000482,0.996976,0.000235,0.992505,0.000577,0.995172,0.000374,0.995732,0.000407
8,xgboost,randomized_search,cicids2017,unsw_nb15,cross_dataset,100925,80740,20185,0.799782,0.499864,...,0.995186,0.000292,0.996715,0.000241,0.991836,0.000601,0.994751,0.000386,0.994100,0.000783
50,decision_tree,randomized_search,cicids2017_iot23,unsw_nb15,combined_to_unseen,100925,80740,20185,0.808462,0.531001,...,0.997293,0.000152,0.997468,0.000074,0.993673,0.000184,0.995949,0.000118,0.993933,0.000214
53,linear_svm,randomized_search,cicids2017_iot23,unsw_nb15,combined_to_unseen,100925,80740,20185,0.779876,0.492885,...,0.970784,0.000838,0.978716,0.000550,0.948462,0.001276,0.966221,0.000864,0.959377,0.000941
54,mlp,randomized_search,cicids2017_iot23,unsw_nb15,combined_to_unseen,100925,80740,20185,0.806104,0.519941,...,0.996672,0.000437,0.997033,0.000184,0.992594,0.000453,0.995255,0.000293,0.993129,0.000437
51,random_forest,randomized_search,cicids2017_iot23,unsw_nb15,combined_to_unseen,100925,80740,20185,0.805212,0.515166,...,0.997396,0.000235,0.997840,0.000131,0.994610,0.000326,0.996546,0.000210,0.995269,0.000253
52,xgboost,randomized_search,cicids2017_iot23,unsw_nb15,combined_to_unseen,100925,80740,20185,0.799832,0.500062,...,0.997280,0.000176,0.997710,0.000172,0.994285,0.000429,0.996337,0.000275,0.994924,0.000470
45,decision_tree,randomized_search,cicids2017_unsw_nb15,iot23,combined_to_unseen,100925,80740,20185,0.098608,0.067705,...,0.989830,0.000520,0.993250,0.000281,0.983355,0.000678,0.989237,0.000445,0.988349,0.000395
48,linear_svm,randomized_search,cicids2017_unsw_nb15,iot23,combined_to_unseen,100925,80740,20185,0.126639,0.152644,...,0.896490,0.006568,0.929919,0.003718,0.846883,0.006631,0.891919,0.005395,0.885063,0.005648
49,mlp,randomized_search,cicids2017_unsw_nb15,iot23,combined_to_unseen,100925,80740,20185,0.011385,0.010125,...,0.986462,0.001790,0.991896,0.000665,0.980180,0.001554,0.987106,0.001046,0.988071,0.001170
46,random_forest,randomized_search,cicids2017_unsw_nb15,iot23,combined_to_unseen,100925,80740,20185,0.096943,0.064138,...,0.989846,0.000475,0.994336,0.000289,0.986091,0.000701,0.990978,0.000459,0.992677,0.000486
47,xgboost,randomized_search,cicids2017_unsw_nb15,iot23,combined_to_unseen,100925,80740,20185,0.026842,0.019730,...,0.989952,0.000410,0.994163,0.000267,0.985651,0.000651,0.990700,0.000425,0.991823,0.000519
31,decision_tree,randomized_search,iot23,cicids2017,cross_dataset,100925,80740,20185,0.758543,0.479905,...,0.999883,0.000043,0.999093,0.000132,0.997725,0.000332,0.998548,0.000212,0.996544,0.000492
40,linear_svm,randomized_search,iot23,cicids2017,cross_dataset,100925,80740,20185,0.759336,0.496117,...,0.998896,0.000102,0.998310,0.000160,0.995766,0.000403,0.997295,0.000257,0.994894,0.000574
43,mlp,randomized_search,iot23,cicids2017,cross_dataset,100925,80740,20185,0.786852,0.491782,...,0.999899,0.000079,0.998992,0.000167,0.997472,0.000420,0.998386,0.000268,0.996117,0.000565
34,random_forest,randomized_search,iot23,cicids2017,cross_dataset,100925,80740,20185,0.809998,0.575062,...,0.999952,0.000039,0.999146,0.000124,0.997858,0.000312,0.998633,0.000199,0.996653,0.000481
37,xgboost,randomized_search,iot23,cicids2017,cross_dataset,100925,80740,20185,0.831459,0.668659,...,0.999926,0.000020,0.999133,0.000113,0.997825,0.000285,0.998611,0.000181,0.996640,0.000444
30,decision_tree,randomized_search,iot23,iot23,intra_dataset,100925,80740,20185,0.998821,0.997164,...,0.999883,0.000043,0.999093,0.000132,0.997725,0.000332,0.998548,0.000212,0.996544,0.000492
39,linear_svm,randomized_search,iot23,iot23,intra_dataset,100925,80740,20185,0.997255,0.995052,...,0.998896,0.000102,0.998310,0.000160,0.995766,0.000403,0.997295,0.000257,0.994894,0.000574
42,mlp,randomized_search,iot23,iot23,intra_dataset,100925,80740,20185,0.998147,0.995424,...,0.999899,0.000079,0.998992,0.000167,0.997472,0.000420,0.998386,0.000268,0.996117,0.000565
33,random_forest,randomized_search,iot23,iot23,intra_dataset,100925,80740,20185,0.998831,0.997226,...,0.999952,0.000039,0.999146,0.000124,0.997858,0.000312,0.998633,0.000199,0.996653,0.000481
36,xgboost,randomized_search,iot23,iot23,intra_dataset,100925,80740,20185,0.998831,0.997207,...,0.999926,0.000020,0.999133,0.000113,0.997825,0.000285,0.998611,0.000181,0.996640,0.000444
32,decision_tree,randomized_search,iot23,unsw_nb15,cross_dataset,100925,80740,20185,0.368541,0.355499,...,0.999883,0.000043,0.999093,0.000132,0.997725,0.000332,0.998548,0.000212,0.996544,0.000492
41,linear_svm,randomized_search,iot23,unsw_nb15,cross_dataset,100925,80740,20185,0.784850,0.510261,...,0.998896,0.000102,0.998310,0.000160,0.995766,0.000403,0.997295,0.000257,0.994894,0.000574
44,mlp,randomized_search,iot23,unsw_nb15,cross_dataset,100925,80740,20185,0.799623,0.502217,...,0.999899,0.000079,0.998992,0.000167,0.997472,0.000420,0.998386,0.000268,0.996117,0.000565
35,random_forest,randomized_search,iot23,unsw_nb15,cross_dataset,100925,80740,20185,0.759960,0.505796,...,0.999952,0.000039,0.999146,0.000124,0.997858,0.000312,0.998633,0.000199,0.996653,0.000481
38,xgboost,randomized_search,iot23,unsw_nb15,cross_dataset,100925,80740,20185,0.655596,0.495058,...,0.999926,0.000020,0.999133,0.000113,0.997825,0.000285,0.998611,0.000181,0.996640,0.000444
16,decision_tree,randomized_search,unsw_nb15,cicids2017,cross_dataset,100925,80740,20185,0.339678,0.281577,...,0.984893,0.000417,0.991723,0.000263,0.979864,0.000628,0.986849,0.000416,0.989782,0.000500
25,linear_svm,randomized_search,unsw_nb15,cicids2017,cross_dataset,100925,80740,20185,0.842596,0.707462,...,0.986199,0.000257,0.972313,0.000565,0.926585,0.001724,0.955068,0.000949,0.908372,0.002588
28,mlp,randomized_search,unsw_nb15,cicids2017,cross_dataset,100925,80740,20185,0.768848,0.658174,...,0.984033,0.000310,0.991507,0.000205,0.979388,0.000493,0.986513,0.000325,0.990233,0.000479
19,random_forest,randomized_search,unsw_nb15,cicids2017,cross_dataset,100925,80740,20185,0.361784,0.322182,...,0.985095,0.000408,0.992136,0.000185,0.980883,0.000434,0.987507,0.000291,0.991125,0.000222
22,xgboost,randomized_search,unsw_nb15,cicids2017,cross_dataset,100925,80740,20185,0.331048,0.268566,...,0.985021,0.000386,0.992186,0.000146,0.981013,0.000337,0.987588,0.000229,0.991438,0.000113
17,decision_tree,randomized_search,unsw_nb15,iot23,cross_dataset,100925,80740,20185,0.016349,0.030747,...,0.984893,0.000417,0.991723,0.000263,0.979864,0.000628,0.986849,0.000416,0.989782,0.000500
26,linear_svm,randomized_search,unsw_nb15,iot23,cross_dataset,100925,80740,20185,0.787050,0.494600,...,0.986199,0.000257,0.972313,0.000565,0.926585,0.001724,0.955068,0.000949,0.908372,0.002588
29,mlp,randomized_search,unsw_nb15,iot23,cross_dataset,100925,80740,20185,0.719861,0.452459,...,0.984033,0.000310,0.991507,0.000205,0.979388,0.000493,0.986513,0.000325,0.990233,0.000479
20,random_forest,randomized_search,unsw_nb15,iot23,cross_dataset,100925,80740,20185,0.090552,0.077068,...,0.985095,0.000408,0.992136,0.000185,0.980883,0.000434,0.987507,0.000291,0.991125,0.000222
23,xgboost,randomized_search,unsw_nb15,iot23,cross_dataset,100925,80740,20185,0.081278,0.054756,...,0.985021,0.000386,0.992186,0.000146,0.981013,0.000337,0.987588,0.000229,0.991438,0.000113
15,decision_tree,randomized_search,unsw_nb15,unsw_nb15,intra_dataset,100925,80740,20185,0.986485,0.989732,...,0.984893,0.000417,0.991723,0.000263,0.979864,0.000628,0.986849,0.000416,0.989782,0.000500
24,linear_svm,randomized_search,unsw_nb15,unsw_nb15,intra_dataset,100925,80740,20185,0.954164,0.906831,...,0.986199,0.000257,0.972313,0.000565,0.926585,0.001724,0.955068,0.000949,0.908372,0.002588
27,mlp,randomized_search,unsw_nb15,unsw_nb15,intra_dataset,100925,80740,20185,0.986188,0.990178,...,0.984033,0.000310,0.991507,0.000205,0.979388,0.000493,0.986513,0.000325,0.990233,0.000479
18,random_forest,randomized_search,unsw_nb15,unsw_nb15,intra_dataset,100925,80740,20185,0.986971,0.990760,...,0.985095,0.000408,0.992136,0.000185,0.980883,0.000434,0.987507,0.000291,0.991125,0.000222
21,xgboost,randomized_search,unsw_nb15,unsw_nb15,intra_dataset,100925,80740,20185,0.987159,0.991213,...,0.985021,0.000386,0.992186,0.000146,0.981013,0.000337,0.987588,0.000229,0.991438,0.000113
55,decision_tree,randomized_search,unsw_nb15_iot23,cicids2017,combined_to_unseen,100925,80740,20185,0.708080,0.510751,...,0.992622,0.000236,0.995312,0.000156,0.988406,0.000383,0.992520,0.000248,0.992367,0.000334
58,linear_svm,randomized_search,unsw_nb15_iot23,cicids2017,combined_to_unseen,100925,80740,20185,0.503899,0.682208,...,0.982221,0.003737,0.981890,0.002047,0.954697,0.004799,0.971020,0.003224,0.954219,0.002516
59,mlp,randomized_search,unsw_nb15_iot23,cicids2017,combined_to_unseen,100925,80740,20185,0.790706,0.703233,...,0.992011,0.000375,0.994682,0.000243,0.986845,0.000604,0.991513,0.000388,0.990767,0.000879
56,random_forest,randomized_search,unsw_nb15_iot23,cicids2017,combined_to_unseen,100925,80740,20185,0.714263,0.489088,...,0.992370,0.000243,0.995616,0.000079,0.989181,0.000188,0.993008,0.000125,0.993966,0.000184
57,xgboost,randomized_search,unsw_nb15_iot23,cicids2017,combined_to_unseen,100925,80740,20185,0.713421,0.466863,...,0.992420,0.000202,0.995607,0.000072,0.989156,0.000173,0.992993,0.000114,0.993853,0.000164

In [4]:
evaluation_counts = (
    evaluation_df.groupby("scenario_type", as_index=False)
    .size()
    .rename(columns={"size": "evaluations"})
)
display(evaluation_counts)

        scenario_type  evaluations
0  combined_to_unseen           15
1       cross_dataset           30
2       intra_dataset           15

In [5]:
def show_reports(
    training_name,
    test_name,
    show_classification_report=True,
    show_confusion_matrix=True,
):
    for model_name in MODELS_TO_EVALUATE:
        report_dir = OUTPUT_DIR / training_name / model_name

        if show_classification_report:
            report_path = report_dir / f"randomized_search_{test_name}.txt"
            print(report_path.read_text(encoding="utf-8"))

        if show_confusion_matrix:
            matrix_path = (
                report_dir / f"randomized_search_{test_name}_confusion_matrix.txt"
            )
            print(matrix_path.read_text(encoding="utf-8"))

In [6]:
show_reports("cicids2017", "cicids2017")

Treino: cicids2017 | Modelo: decision_tree | Teste: cicids2017

              precision    recall  f1-score   support

      BENIGN     0.9972    0.9953    0.9963     80740
      ATTACK     0.9815    0.9889    0.9852     20185

    accuracy                         0.9941    100925
   macro avg     0.9894    0.9921    0.9907    100925
weighted avg     0.9941    0.9941    0.9941    100925

Treino: cicids2017 | Modelo: decision_tree | Teste: cicids2017

             Predito BENIGN  Predito ATTACK
Real BENIGN           80364             376
Real ATTACK             224           19961
Treino: cicids2017 | Modelo: random_forest | Teste: cicids2017

              precision    recall  f1-score   support

      BENIGN     0.9992    0.9947    0.9970     80740
      ATTACK     0.9791    0.9970    0.9880     20185

    accuracy                         0.9951    100925
   macro avg     0.9892    0.9958    0.9925    100925
weighted avg     0.9952    0.9951    0.9952    100925

Treino: cicids2017 | Modelo: random_forest | Teste: cicids2017

             Predito BENIGN  Predito ATTACK
Real BENIGN           80311             429
Real ATTACK              61           20124
Treino: cicids2017 | Modelo: xgboost | Teste: cicids2017

              precision    recall  f1-score   support

      BENIGN     0.9984    0.9948    0.9966     80740
      ATTACK     0.9795    0.9936    0.9865     20185

    accuracy                         0.9946    100925
   macro avg     0.9890    0.9942    0.9916    100925
weighted avg     0.9946    0.9946    0.9946    100925

Treino: cicids2017 | Modelo: xgboost | Teste: cicids2017

             Predito BENIGN  Predito ATTACK
Real BENIGN           80321             419
Real ATTACK             129           20056
Treino: cicids2017 | Modelo: linear_svm | Teste: cicids2017

              precision    recall  f1-score   support

      BENIGN     0.9897    0.9240    0.9557     80740
      ATTACK     0.7597    0.9617    0.8489     20185

    accuracy                         0.9315    100925
   macro avg     0.8747    0.9428    0.9023    100925
weighted avg     0.9437    0.9315    0.9343    100925

Treino: cicids2017 | Modelo: linear_svm | Teste: cicids2017

             Predito BENIGN  Predito ATTACK
Real BENIGN           74600            6140
Real ATTACK             773           19412
Treino: cicids2017 | Modelo: mlp | Teste: cicids2017

              precision    recall  f1-score   support

      BENIGN     0.9983    0.9940    0.9962     80740
      ATTACK     0.9766    0.9934    0.9849     20185

    accuracy                         0.9939    100925
   macro avg     0.9875    0.9937    0.9905    100925
weighted avg     0.9940    0.9939    0.9939    100925

Treino: cicids2017 | Modelo: mlp | Teste: cicids2017

             Predito BENIGN  Predito ATTACK
Real BENIGN           80259             481
Real ATTACK             134           20051

In [7]:
show_reports("cicids2017", "unsw_nb15")

Treino: cicids2017 | Modelo: decision_tree | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.7957    0.9708    0.8746     80740
      ATTACK     0.0244    0.0029    0.0052     20185

    accuracy                         0.7772    100925
   macro avg     0.4101    0.4869    0.4399    100925
weighted avg     0.6414    0.7772    0.7007    100925

Treino: cicids2017 | Modelo: decision_tree | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           78382            2358
Real ATTACK           20126              59
Treino: cicids2017 | Modelo: random_forest | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8000    0.9999    0.8888     80740
      ATTACK     0.0000    0.0000    0.0000     20185

    accuracy                         0.7999    100925
   macro avg     0.4000    0.5000    0.4444    100925
weighted avg     0.6400    0.7999    0.7111    100925

Treino: cicids2017 | Modelo: random_forest | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80733               7
Real ATTACK           20185               0
Treino: cicids2017 | Modelo: xgboost | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8000    0.9997    0.8888     80740
      ATTACK     0.0000    0.0000    0.0000     20185

    accuracy                         0.7998    100925
   macro avg     0.4000    0.4999    0.4444    100925
weighted avg     0.6400    0.7998    0.7110    100925

Treino: cicids2017 | Modelo: xgboost | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80718              22
Real ATTACK           20185               0
Treino: cicids2017 | Modelo: linear_svm | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.7992    0.9934    0.8858     80740
      ATTACK     0.0601    0.0017    0.0033     20185

    accuracy                         0.7951    100925
   macro avg     0.4296    0.4975    0.4445    100925
weighted avg     0.6514    0.7951    0.7093    100925

Treino: cicids2017 | Modelo: linear_svm | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80208             532
Real ATTACK           20151              34
Treino: cicids2017 | Modelo: mlp | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.7997    0.9971    0.8875     80740
      ATTACK     0.0814    0.0010    0.0021     20185

    accuracy                         0.7979    100925
   macro avg     0.4405    0.4991    0.4448    100925
weighted avg     0.6560    0.7979    0.7104    100925

Treino: cicids2017 | Modelo: mlp | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80503             237
Real ATTACK           20164              21

In [8]:
show_reports("cicids2017_iot23", "unsw_nb15")

Treino: cicids2017_iot23 | Modelo: decision_tree | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8101    0.9934    0.8925     80740
      ATTACK     0.7231    0.0686    0.1253     20185

    accuracy                         0.8085    100925
   macro avg     0.7666    0.5310    0.5089    100925
weighted avg     0.7927    0.8085    0.7390    100925

Treino: cicids2017_iot23 | Modelo: decision_tree | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80210             530
Real ATTACK           18801            1384
Treino: cicids2017_iot23 | Modelo: random_forest | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8049    0.9986    0.8913     80740
      ATTACK     0.8479    0.0318    0.0612     20185

    accuracy                         0.8052    100925
   macro avg     0.8264    0.5152    0.4763    100925
weighted avg     0.8135    0.8052    0.7253    100925

Treino: cicids2017_iot23 | Modelo: random_forest | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80625             115
Real ATTACK           19544             641
Treino: cicids2017_iot23 | Modelo: xgboost | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8000    0.9997    0.8888     80740
      ATTACK     0.2571    0.0004    0.0009     20185

    accuracy                         0.7998    100925
   macro avg     0.5286    0.5001    0.4448    100925
weighted avg     0.6914    0.7998    0.7112    100925

Treino: cicids2017_iot23 | Modelo: xgboost | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80714              26
Real ATTACK           20176               9
Treino: cicids2017_iot23 | Modelo: linear_svm | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.7977    0.9712    0.8759     80740
      ATTACK     0.1123    0.0146    0.0258     20185

    accuracy                         0.7799    100925
   macro avg     0.4550    0.4929    0.4509    100925
weighted avg     0.6606    0.7799    0.7059    100925

Treino: cicids2017_iot23 | Modelo: linear_svm | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           78415            2325
Real ATTACK           19891             294
Treino: cicids2017_iot23 | Modelo: mlp | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8065    0.9969    0.8916     80740
      ATTACK     0.7750    0.0430    0.0815     20185

    accuracy                         0.8061    100925
   macro avg     0.7907    0.5199    0.4865    100925
weighted avg     0.8002    0.8061    0.7296    100925

Treino: cicids2017_iot23 | Modelo: mlp | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80488             252
Real ATTACK           19317             868

In [9]:
show_reports("unsw_nb15", "unsw_nb15")

Treino: unsw_nb15 | Modelo: decision_tree | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.9988    0.9843    0.9915     80740
      ATTACK     0.9407    0.9951    0.9672     20185

    accuracy                         0.9865    100925
   macro avg     0.9697    0.9897    0.9793    100925
weighted avg     0.9872    0.9865    0.9866    100925

Treino: unsw_nb15 | Modelo: decision_tree | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           79474            1266
Real ATTACK              98           20087
Treino: unsw_nb15 | Modelo: random_forest | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.9993    0.9844    0.9918     80740
      ATTACK     0.9413    0.9971    0.9684     20185

    accuracy                         0.9870    100925
   macro avg     0.9703    0.9908    0.9801    100925
weighted avg     0.9877    0.9870    0.9871    100925

Treino: unsw_nb15 | Modelo: random_forest | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           79484            1256
Real ATTACK              59           20126
Treino: unsw_nb15 | Modelo: xgboost | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.9995    0.9845    0.9919     80740
      ATTACK     0.9414    0.9980    0.9688     20185

    accuracy                         0.9872    100925
   macro avg     0.9704    0.9912    0.9804    100925
weighted avg     0.9879    0.9872    0.9873    100925

Treino: unsw_nb15 | Modelo: xgboost | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           79485            1255
Real ATTACK              41           20144
Treino: unsw_nb15 | Modelo: linear_svm | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.9582    0.9857    0.9718     80740
      ATTACK     0.9355    0.8279    0.8784     20185

    accuracy                         0.9542    100925
   macro avg     0.9468    0.9068    0.9251    100925
weighted avg     0.9536    0.9542    0.9531    100925

Treino: unsw_nb15 | Modelo: linear_svm | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           79587            1153
Real ATTACK            3473           16712
Treino: unsw_nb15 | Modelo: mlp | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.9992    0.9835    0.9913     80740
      ATTACK     0.9380    0.9968    0.9665     20185

    accuracy                         0.9862    100925
   macro avg     0.9686    0.9902    0.9789    100925
weighted avg     0.9870    0.9862    0.9863    100925

Treino: unsw_nb15 | Modelo: mlp | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           79410            1330
Real ATTACK              64           20121

In [10]:
show_reports("iot23", "iot23")

Treino: iot23 | Modelo: decision_tree | Teste: iot23

              precision    recall  f1-score   support

      BENIGN     0.9986    0.9999    0.9993     80740
      ATTACK     0.9997    0.9944    0.9970     20185

    accuracy                         0.9988    100925
   macro avg     0.9992    0.9972    0.9982    100925
weighted avg     0.9988    0.9988    0.9988    100925

Treino: iot23 | Modelo: decision_tree | Teste: iot23

             Predito BENIGN  Predito ATTACK
Real BENIGN           80734               6
Real ATTACK             113           20072
Treino: iot23 | Modelo: random_forest | Teste: iot23

              precision    recall  f1-score   support

      BENIGN     0.9986    0.9999    0.9993     80740
      ATTACK     0.9996    0.9946    0.9971     20185

    accuracy                         0.9988    100925
   macro avg     0.9991    0.9972    0.9982    100925
weighted avg     0.9988    0.9988    0.9988    100925

Treino: iot23 | Modelo: random_forest | Teste: iot23

             Predito BENIGN  Predito ATTACK
Real BENIGN           80732               8
Real ATTACK             110           20075
Treino: iot23 | Modelo: xgboost | Teste: iot23

              precision    recall  f1-score   support

      BENIGN     0.9986    0.9999    0.9993     80740
      ATTACK     0.9997    0.9945    0.9971     20185

    accuracy                         0.9988    100925
   macro avg     0.9991    0.9972    0.9982    100925
weighted avg     0.9988    0.9988    0.9988    100925

Treino: iot23 | Modelo: xgboost | Teste: iot23

             Predito BENIGN  Predito ATTACK
Real BENIGN           80733               7
Real ATTACK             111           20074
Treino: iot23 | Modelo: linear_svm | Teste: iot23

              precision    recall  f1-score   support

      BENIGN     0.9978    0.9987    0.9983     80740
      ATTACK     0.9949    0.9914    0.9931     20185

    accuracy                         0.9973    100925
   macro avg     0.9964    0.9951    0.9957    100925
weighted avg     0.9973    0.9973    0.9973    100925

Treino: iot23 | Modelo: linear_svm | Teste: iot23

             Predito BENIGN  Predito ATTACK
Real BENIGN           80637             103
Real ATTACK             174           20011
Treino: iot23 | Modelo: mlp | Teste: iot23

              precision    recall  f1-score   support

      BENIGN     0.9977    1.0000    0.9988     80740
      ATTACK     0.9999    0.9909    0.9953     20185

    accuracy                         0.9981    100925
   macro avg     0.9988    0.9954    0.9971    100925
weighted avg     0.9982    0.9981    0.9981    100925

Treino: iot23 | Modelo: mlp | Teste: iot23

             Predito BENIGN  Predito ATTACK
Real BENIGN           80737               3
Real ATTACK             184           20001