In [1]:
import sys
from pathlib import Path
from time import perf_counter

import joblib
import pandas as pd
from sklearn.metrics import (
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
)

ROOT = Path(r"C:\tcc\network-ids-ml-generalization")
DATA_DIR = ROOT / "datasets" / "final" / "ml"
BASELINE_MODEL_DIR = ROOT / "models" / "baseline"
RANDOMIZED_MODEL_DIR = ROOT / "models" / "randomized_search"
TRAINING_RESULTS_DIR = ROOT / "results" / "model_training"
OUTPUT_DIR = ROOT / "results" / "model_evaluation"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(ROOT))
from src.utils.features import split_features

reference_df = pd.read_parquet(DATA_DIR / "cicids2017_train.parquet")
numerical_features, categorical_features = split_features(reference_df)
feature_columns = numerical_features + categorical_features
del reference_df


TEST_CONFIGS = {
    "cicids2017": ["cicids2017", "iot23", "unsw_nb15"],
    "unsw_nb15": ["unsw_nb15", "cicids2017", "iot23"],
    "iot23": ["iot23", "cicids2017", "unsw_nb15"],
    "cicids2017_unsw_nb15": ["iot23"],
    "cicids2017_iot23": ["unsw_nb15"],
    "unsw_nb15_iot23": ["cicids2017"],
}

TEST_DATASETS = ["cicids2017", "iot23", "unsw_nb15"]
SINGLE_DATASET_TRAINING = set(TEST_DATASETS)
MODELS_TO_EVALUATE = [
    "decision_tree",
    "random_forest",
    "xgboost",
    "linear_svm",
    "mlp",
]

MODEL_VERSIONS = {
    "baseline": {
        "label": "padrão",
        "model_dir": BASELINE_MODEL_DIR,
    },
    "randomized_search": {
        "label": "RandomizedSearchCV",
        "model_dir": RANDOMIZED_MODEL_DIR,
    },
}

In [2]:
CV_METRICS = [
    "precision_attack",
    "recall_attack",
    "f1_attack",
    "precision_benign",
    "recall_benign",
    "f1_benign",
    "f1_macro",
    "accuracy",
    "balanced_accuracy",
]


def load_training_summaries(training_method):
    frames = []
    method_dir = TRAINING_RESULTS_DIR / training_method

    for model_name in MODELS_TO_EVALUATE:
        summary_path = method_dir / model_name / "summary.csv"
        if not summary_path.exists():
            raise FileNotFoundError(
                f"Resumo de treinamento não encontrado: {summary_path}. "
                "Execute primeiro os notebooks 07 e 08."
            )
        frame = pd.read_csv(summary_path)
        frame["training_method"] = training_method
        frames.append(frame)

    return pd.concat(frames, ignore_index=True).set_index(
        ["training_method", "model", "training_source"]
    )


def scenario_type(training_name, test_name):
    if training_name == test_name:
        return "intra_dataset"
    if training_name in SINGLE_DATASET_TRAINING:
        return "cross_dataset"
    return "combined_to_unseen"


def training_metadata(summary_row):
    metadata = {
        "training_rows": summary_row.get("training_rows"),
        "params": summary_row.get("params", "{}"),
        "cv_n_splits": summary_row.get("n_splits"),
        "random_state": summary_row.get("random_state"),
        "training_elapsed_seconds": summary_row.get("elapsed_seconds"),
        "training_elapsed_minutes": summary_row.get("elapsed_minutes"),
        "final_fit_time_seconds": summary_row.get("refit_time_seconds"),
        "model_size_mb": summary_row.get("model_size_mb"),
    }

    for metric in CV_METRICS:
        metadata[f"cv_{metric}_mean"] = summary_row.get(f"{metric}_mean")
        metadata[f"cv_{metric}_std"] = summary_row.get(f"{metric}_std")

    return metadata

In [3]:
columns_to_load = feature_columns + ["label_binary"]
test_dataframes = {
    dataset_name: pd.read_parquet(
        DATA_DIR / f"{dataset_name}_test.parquet",
        columns=columns_to_load,
    )
    for dataset_name in TEST_DATASETS
}

training_summaries = pd.concat(
    [
        load_training_summaries("baseline"),
        load_training_summaries("randomized_search"),
    ]
)

evaluation_results = []

for training_name, test_names in TEST_CONFIGS.items():
    for model_name in MODELS_TO_EVALUATE:
        report_dir = OUTPUT_DIR / training_name / model_name
        report_dir.mkdir(parents=True, exist_ok=True)

        for version, version_config in MODEL_VERSIONS.items():
            model_path = (
                version_config["model_dir"]
                / model_name
                / f"{training_name}.joblib"
            )
            pipeline = joblib.load(model_path)
            summary_row = training_summaries.loc[
                (version, model_name, training_name)
            ]

            for test_name in test_names:
                test_df = test_dataframes[test_name]
                X_test = test_df[feature_columns]
                y_test = test_df["label_binary"].eq("ATTACK").astype("int8")

                prediction_start = perf_counter()
                predictions = pipeline.predict(X_test)
                prediction_time_seconds = perf_counter() - prediction_start

                metrics_start = perf_counter()
                report_values = classification_report(
                    y_test,
                    predictions,
                    labels=[0, 1],
                    target_names=["BENIGN", "ATTACK"],
                    output_dict=True,
                    zero_division=0,
                )
                report_text = classification_report(
                    y_test,
                    predictions,
                    labels=[0, 1],
                    target_names=["BENIGN", "ATTACK"],
                    digits=4,
                    zero_division=0,
                )
                matrix_values = confusion_matrix(y_test, predictions, labels=[0, 1])
                balanced_accuracy = balanced_accuracy_score(y_test, predictions)
                metrics_calculation_time_seconds = perf_counter() - metrics_start

                matrix = pd.DataFrame(
                    matrix_values,
                    index=["Real BENIGN", "Real ATTACK"],
                    columns=["Predito BENIGN", "Predito ATTACK"],
                )
                true_negative, false_positive, false_negative, true_positive = (
                    matrix_values.ravel()
                )

                title = (
                    f"Treino: {training_name} | Modelo: {model_name} | "
                    f"Configuração: {version_config['label']} | Teste: {test_name}"
                )
                report_path = report_dir / f"{version}_{test_name}.txt"
                matrix_path = report_dir / f"{version}_{test_name}_confusion_matrix.txt"
                report_path.write_text(f"{title}\n\n{report_text}", encoding="utf-8")
                matrix_path.write_text(f"{title}\n\n{matrix}", encoding="utf-8")

                result = {
                    "model": model_name,
                    "training_method": version,
                    "training_source": training_name,
                    "test_source": test_name,
                    "scenario_type": scenario_type(training_name, test_name),
                    "test_rows": len(test_df),
                    "benign_support": int(report_values["BENIGN"]["support"]),
                    "attack_support": int(report_values["ATTACK"]["support"]),
                    "accuracy": report_values["accuracy"],
                    "balanced_accuracy": balanced_accuracy,
                    "precision_benign": report_values["BENIGN"]["precision"],
                    "recall_benign": report_values["BENIGN"]["recall"],
                    "f1_benign": report_values["BENIGN"]["f1-score"],
                    "precision_attack": report_values["ATTACK"]["precision"],
                    "recall_attack": report_values["ATTACK"]["recall"],
                    "f1_attack": report_values["ATTACK"]["f1-score"],
                    "f1_macro": report_values["macro avg"]["f1-score"],
                    "f1_weighted": report_values["weighted avg"]["f1-score"],
                    "true_negative": int(true_negative),
                    "false_positive": int(false_positive),
                    "false_negative": int(false_negative),
                    "true_positive": int(true_positive),
                    "prediction_time_seconds": prediction_time_seconds,
                    "prediction_rows_per_second": (
                        len(test_df) / prediction_time_seconds
                        if prediction_time_seconds > 0
                        else float("inf")
                    ),
                    "metrics_calculation_time_seconds": metrics_calculation_time_seconds,
                    "model_file": str(model_path.relative_to(ROOT)),
                    "classification_report_file": str(report_path.relative_to(ROOT)),
                    "confusion_matrix_file": str(matrix_path.relative_to(ROOT)),
                }
                result.update(training_metadata(summary_row))
                evaluation_results.append(result)

evaluation_df = pd.DataFrame(evaluation_results).sort_values(
    ["training_source", "test_source", "model", "training_method"]
)
evaluation_df.to_csv(OUTPUT_DIR / "evaluation_summary.csv", index=False)
display(evaluation_df)

,model,training_method,training_source,test_source,scenario_type,test_rows,benign_support,attack_support,accuracy,balanced_accuracy,...,cv_recall_benign_mean,cv_recall_benign_std,cv_f1_benign_mean,cv_f1_benign_std,cv_f1_macro_mean,cv_f1_macro_std,cv_accuracy_mean,cv_accuracy_std,cv_balanced_accuracy_mean,cv_balanced_accuracy_std
0,decision_tree,baseline,cicids2017,cicids2017,intra_dataset,100925,80740,20185,0.994055,0.992123,...,0.995377,0.000327,0.996133,0.000145,0.990361,0.000363,0.993817,0.000232,0.991478,0.000652
3,decision_tree,randomized_search,cicids2017,cicids2017,intra_dataset,100925,80740,20185,0.993579,0.992104,...,0.994846,0.000457,0.996057,0.000204,0.990190,0.000499,0.993698,0.000324,0.991977,0.000383
18,linear_svm,baseline,cicids2017,cicids2017,intra_dataset,100925,80740,20185,0.888135,0.763197,...,0.971527,0.000929,0.932627,0.000560,0.797837,0.001565,0.887706,0.000912,0.761975,0.001436
21,linear_svm,randomized_search,cicids2017,cicids2017,intra_dataset,100925,80740,20185,0.931504,0.942829,...,0.924174,0.001156,0.955983,0.000880,0.902885,0.001845,0.931916,0.001341,0.943530,0.001734
24,mlp,baseline,cicids2017,cicids2017,intra_dataset,100925,80740,20185,0.993678,0.992909,...,0.994427,0.000688,0.995521,0.000497,0.988847,0.001267,0.992840,0.000799,0.990461,0.002442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,mlp,randomized_search,unsw_nb15_iot23,cicids2017,combined_to_unseen,100925,80740,20185,0.790706,0.703233,...,0.991884,0.000453,0.994713,0.000215,0.986930,0.000540,0.991564,0.000345,0.991085,0.001020
112,random_forest,baseline,unsw_nb15_iot23,cicids2017,combined_to_unseen,100925,80740,20185,0.715799,0.486611,...,0.993028,0.000160,0.995202,0.000092,0.988108,0.000225,0.992339,0.000146,0.991307,0.000218
113,random_forest,randomized_search,unsw_nb15_iot23,cicids2017,combined_to_unseen,100925,80740,20185,0.711826,0.483311,...,0.992545,0.000184,0.995611,0.000119,0.989162,0.000292,0.993000,0.000189,0.993682,0.000287
114,xgboost,baseline,unsw_nb15_iot23,cicids2017,combined_to_unseen,100925,80740,20185,0.749547,0.549560,...,0.992489,0.000188,0.995595,0.000166,0.989124,0.000410,0.992974,0.000264,0.993702,0.000441
115,xgboost,randomized_search,unsw_nb15_iot23,cicids2017,combined_to_unseen,100925,80740,20185,0.744295,0.582766,...,0.992611,0.000187,0.995627,0.000130,0.989200,0.000321,0.993025,0.000208,0.993646,0.000312

In [4]:
comparison_keys = [
    "model",
    "training_source",
    "test_source",
    "scenario_type",
]
comparison_metrics = [
    "accuracy",
    "balanced_accuracy",
    "precision_attack",
    "recall_attack",
    "f1_attack",
    "f1_macro",
    "prediction_time_seconds",
    "cv_f1_attack_mean",
    "cv_f1_attack_std",
    "cv_balanced_accuracy_mean",
    "cv_balanced_accuracy_std",
    "training_elapsed_seconds",
]

baseline_comparison = evaluation_df.loc[
    evaluation_df["training_method"].eq("baseline"),
    comparison_keys + comparison_metrics,
].rename(columns={metric: f"{metric}_baseline" for metric in comparison_metrics})

randomized_comparison = evaluation_df.loc[
    evaluation_df["training_method"].eq("randomized_search"),
    comparison_keys + comparison_metrics + ["params"],
].rename(
    columns={
        **{metric: f"{metric}_randomized_search" for metric in comparison_metrics},
        "params": "params_randomized_search",
    }
)

comparison_df = baseline_comparison.merge(
    randomized_comparison,
    on=comparison_keys,
    how="inner",
)
for metric in comparison_metrics:
    comparison_df[f"{metric}_delta"] = (
        comparison_df[f"{metric}_randomized_search"]
        - comparison_df[f"{metric}_baseline"]
    )

comparison_df.to_csv(
    OUTPUT_DIR / "baseline_vs_randomized_search.csv",
    index=False,
)
display(comparison_df)

,model,training_source,test_source,scenario_type,accuracy_baseline,balanced_accuracy_baseline,precision_attack_baseline,recall_attack_baseline,f1_attack_baseline,f1_macro_baseline,...,precision_attack_delta,recall_attack_delta,f1_attack_delta,f1_macro_delta,prediction_time_seconds_delta,cv_f1_attack_mean_delta,cv_f1_attack_std_delta,cv_balanced_accuracy_mean_delta,cv_balanced_accuracy_std_delta,training_elapsed_seconds_delta
0,decision_tree,cicids2017,cicids2017,intra_dataset,0.994055,0.992123,0.981512,0.988903,0.985193,0.990737,...,-0.003015,0.000743,-0.001154,-0.000727,-0.001975,-0.000267,0.000211,0.000499,-0.000270,13.265274
1,linear_svm,cicids2017,cicids2017,intra_dataset,0.888135,0.763197,0.829225,0.554967,0.664926,0.798893,...,-0.069519,0.406738,0.183928,0.103393,-0.004761,0.186739,0.000202,0.181555,0.000298,40.298118
2,mlp,cicids2017,cicids2017,intra_dataset,0.993678,0.992909,0.977105,0.991627,0.984313,0.990177,...,-0.000532,0.001734,0.000583,0.000362,0.006075,0.003075,-0.000736,0.003328,-0.001909,146.944374
3,random_forest,cicids2017,cicids2017,intra_dataset,0.994848,0.994309,0.981066,0.993411,0.987200,0.991987,...,-0.000191,0.000050,-0.000072,-0.000045,0.600645,0.000227,0.000096,0.000279,-0.000062,572.989819
4,xgboost,cicids2017,cicids2017,intra_dataset,0.994580,0.994346,0.979256,0.993956,0.986551,0.991579,...,0.000280,-0.000347,-0.000029,-0.000017,0.194159,0.000136,0.000136,0.000058,0.000114,46.052998
5,decision_tree,cicids2017,iot23,cross_dataset,0.804865,0.523105,0.647094,0.053505,0.098838,0.494712,...,-0.631258,0.003418,-0.074059,-0.396767,-0.000812,-0.000267,0.000211,0.000499,-0.000270,13.265274
6,linear_svm,cicids2017,iot23,cross_dataset,0.110964,0.107809,0.028094,0.102551,0.044105,0.106593,...,0.190306,0.893584,0.314148,0.170547,-0.000986,0.186739,0.000202,0.181555,0.000298,40.298118
7,mlp,cicids2017,iot23,cross_dataset,0.251117,0.460887,0.185664,0.810503,0.302121,0.247096,...,-0.000138,-0.000297,-0.000203,-0.000485,-0.015838,0.003075,-0.000736,0.003328,-0.001909,146.944374
8,random_forest,cicids2017,iot23,cross_dataset,0.099846,0.064671,0.001721,0.006044,0.002679,0.091220,...,0.000026,0.000099,0.000041,-0.000792,0.326585,0.000227,0.000096,0.000279,-0.000062,572.989819
9,xgboost,cicids2017,iot23,cross_dataset,0.094922,0.063228,0.002934,0.010404,0.004577,0.087405,...,0.070864,-0.005995,0.003744,0.357981,0.237286,0.000136,0.000136,0.000058,0.000114,46.052998
10,decision_tree,cicids2017,unsw_nb15,cross_dataset,0.777221,0.486859,0.024410,0.002923,0.005221,0.439893,...,-0.019317,-0.002328,-0.004156,-0.002149,-0.000424,-0.000267,0.000211,0.000499,-0.000270,13.265274
11,linear_svm,cicids2017,unsw_nb15,cross_dataset,0.796889,0.498743,0.095361,0.001833,0.003597,0.445258,...,-0.035290,-0.000149,-0.000320,-0.000724,-0.000291,0.186739,0.000202,0.181555,0.000298,40.298118
12,mlp,cicids2017,unsw_nb15,cross_dataset,0.799514,0.499994,0.197531,0.000793,0.001579,0.445074,...,-0.116136,0.000248,0.000475,-0.000277,0.006194,0.003075,-0.000736,0.003328,-0.001909,146.944374
13,random_forest,cicids2017,unsw_nb15,cross_dataset,0.799861,0.499913,0.000000,0.000000,0.000000,0.444402,...,0.000000,0.000000,0.000000,0.000028,0.372525,0.000227,0.000096,0.000279,-0.000062,572.989819
14,xgboost,cicids2017,unsw_nb15,cross_dataset,0.799713,0.499820,0.000000,0.000000,0.000000,0.444356,...,0.000000,0.000000,0.000000,0.000021,0.425526,0.000136,0.000136,0.000058,0.000114,46.052998
15,decision_tree,cicids2017_iot23,unsw_nb15,combined_to_unseen,0.808462,0.531001,0.723093,0.068566,0.125255,0.508856,...,-0.089069,-0.024622,-0.043064,-0.022707,0.003223,-0.000760,0.000318,-0.000334,0.000120,23.832516
16,linear_svm,cicids2017_iot23,unsw_nb15,combined_to_unseen,0.779876,0.492885,0.112257,0.014565,0.025785,0.450853,...,0.261059,0.084270,0.130508,0.066215,-0.000176,-0.002049,-0.000264,-0.000944,-0.000098,98.372129
17,mlp,cicids2017_iot23,unsw_nb15,combined_to_unseen,0.803745,0.516683,0.662093,0.038246,0.072315,0.481290,...,0.112907,0.004756,0.009168,0.005257,0.019552,0.004293,-0.004084,0.002061,-0.001254,179.632696
18,random_forest,cicids2017_iot23,unsw_nb15,combined_to_unseen,0.805212,0.515166,0.847884,0.031756,0.061220,0.476276,...,-0.004633,-0.002973,-0.005552,-0.002902,0.597586,-0.000254,0.000104,0.000074,0.000029,1219.801053
19,xgboost,cicids2017_iot23,unsw_nb15,combined_to_unseen,0.799088,0.499579,0.074074,0.000396,0.000788,0.444552,...,0.183069,0.000050,0.000102,0.000280,0.239784,0.000032,-0.000084,0.000016,-0.000077,91.987143
20,decision_tree,cicids2017_unsw_nb15,iot23,combined_to_unseen,0.795323,0.501796,0.259184,0.012584,0.024002,0.454838,...,-0.254607,0.003617,-0.016864,-0.363946,-0.002437,0.005465,-0.000244,0.007423,-0.000200,26.070050
21,linear_svm,cicids2017_unsw_nb15,iot23,combined_to_unseen,0.111043,0.108100,0.028264,0.103195,0.044374,0.106695,...,0.023878,0.092792,0.037995,0.017906,-0.000224,0.059898,0.016521,0.093551,0.007558,86.105121
22,mlp,cicids2017_unsw_nb15,iot23,combined_to_unseen,0.176230,0.415754,0.171615,0.814962,0.283525,0.157332,...,-0.001263,-0.002824,-0.001895,-0.005947,0.000936,0.004307,-0.003669,0.004419,-0.004826,437.741573
23,random_forest,cicids2017_unsw_nb15,iot23,combined_to_unseen,0.726896,0.456577,0.016006,0.006044,0.008775,0.425203,...,-0.013515,0.003617,-0.004813,-0.397381,0.258006,0.001030,-0.000092,0.002117,-0.000009,1349.241416
24,xgboost,cicids2017_unsw_nb15,iot23,combined_to_unseen,0.027129,0.020058,0.002132,0.008273,0.003390,0.026577,...,-0.000102,-0.000396,-0.000163,-0.000282,0.270206,0.000358,-0.000227,0.000195,-0.000230,102.791422
25,decision_tree,iot23,cicids2017,cross_dataset,0.831221,0.713302,0.588956,0.516770,0.550507,0.723306,...,-0.523883,-0.501263,-0.525462,-0.279679,0.009943,0.000104,0.000034,-0.000141,0.000035,5.091525
26,linear_svm,iot23,cicids2017,cross_dataset,0.759336,0.496117,0.180473,0.057419,0.087120,0.474259,...,-0.074465,0.000099,-0.012546,-0.021368,-0.000170,-0.000127,0.000265,-0.000040,0.000054,34.246912
27,mlp,iot23,cicids2017,cross_dataset,0.778231,0.491243,0.095991,0.012930,0.022791,0.448857,...,-0.095991,-0.012930,-0.022791,-0.008501,0.035678,0.000609,0.000012,0.000533,-0.000050,102.078338
28,random_forest,iot23,cicids2017,cross_dataset,0.814833,0.574944,0.634308,0.175130,0.274478,0.584176,...,-0.050650,0.010305,0.006972,0.002022,0.209251,0.000158,0.000033,-0.000088,-0.000021,376.786745
29,xgboost,iot23,cicids2017,cross_dataset,0.830240,0.684766,0.603080,0.442309,0.510332,0.703827,...,0.020317,-0.044984,-0.025007,-0.011549,0.144711,0.000053,-0.000083,0.000037,-0.000051,42.634669
30,decision_tree,iot23,iot23,intra_dataset,0.998682,0.997207,0.998657,0.994749,0.996699,0.997938,...,0.001044,-0.000347,0.000345,0.000216,-0.000986,0.000104,0.000034,-0.000141,0.000035,5.091525
31,linear_svm,iot23,iot23,intra_dataset,0.997255,0.995052,0.994879,0.991380,0.993126,0.995706,...,-0.000049,0.000000,-0.000025,-0.000015,-0.003116,-0.000127,0.000265,-0.000040,0.000054,34.246912
32,mlp,iot23,iot23,intra_dataset,0.998365,0.996006,0.999750,0.992073,0.995897,0.997438,...,0.000100,-0.001189,-0.000550,-0.000343,0.040045,0.000609,0.000012,0.000533,-0.000050,102.078338
33,random_forest,iot23,iot23,intra_dataset,0.998662,0.997176,0.998607,0.994699,0.996649,0.997907,...,0.001044,-0.000149,0.000445,0.000278,0.227428,0.000158,0.000033,-0.000088,-0.000021,376.786745
34,xgboost,iot23,iot23,intra_dataset,0.998851,0.997238,0.999701,0.994550,0.997119,0.998201,...,-0.000050,-0.000050,-0.000050,-0.000031,0.283760,0.000053,-0.000083,0.000037,-0.000051,42.634669
35,decision_tree,iot23,unsw_nb15,cross_dataset,0.367084,0.354422,0.117729,0.333317,0.174001,0.330501,...,0.000424,0.000446,0.000524,0.001117,0.019732,0.000104,0.000034,-0.000141,0.000035,5.091525
36,linear_svm,iot23,unsw_nb15,cross_dataset,0.784850,0.510261,0.290720,0.052613,0.089101,0.483560,...,0.000194,0.000050,0.000080,0.000043,-0.003295,-0.000127,0.000265,-0.000040,0.000054,34.246912
37,mlp,iot23,unsw_nb15,cross_dataset,0.734278,0.492680,0.176975,0.090017,0.119335,0.481435,...,0.260111,-0.083478,-0.106449,-0.030744,0.041839,0.000609,0.000012,0.000533,-0.000050,102.078338
38,random_forest,iot23,unsw_nb15,cross_dataset,0.722873,0.507939,0.218542,0.149715,0.177697,0.505526,...,0.284894,-0.080753,-0.056390,-0.001234,0.323686,0.000158,0.000033,-0.000088,-0.000021,376.786745
39,xgboost,iot23,unsw_nb15,cross_dataset,0.697330,0.531694,0.249492,0.255635,0.252526,0.531387,...,-0.056210,-0.028140,-0.043528,-0.036949,0.217331,0.000053,-0.000083,0.000037,-0.000051,42.634669
40,decision_tree,unsw_nb15,cicids2017,cross_dataset,0.331781,0.244575,0.039075,0.099232,0.056070,0.269454,...,0.030089,0.085509,0.044576,0.020033,-0.005477,0.014460,-0.000389,0.017854,-0.000767,10.542460
41,linear_svm,unsw_nb15,cicids2017,cross_dataset,0.842596,0.707462,0.641703,0.482239,0.550659,0.727623,...,0.008459,-0.005400,-0.000486,0.000302,-0.000541,-0.001482,-0.000346,-0.001266,-0.000377,35.570780
42,mlp,unsw_nb15,cicids2017,cross_dataset,0.768848,0.658174,0.429405,0.473718,0.450475,0.652058,...,-0.177978,0.019173,-0.117482,-0.125810,0.067692,-0.000233,0.000467,-0.000234,0.000172,211.440944
43,random_forest,unsw_nb15,cicids2017,cross_dataset,0.474689,0.337664,0.059231,0.109289,0.076825,0.354862,...,0.030299,0.133020,0.053924,-0.045453,0.367547,0.002772,-0.000125,0.004408,-0.000253,542.849537
44,xgboost,unsw_nb15,cicids2017,cross_dataset,0.347040,0.281440,0.065967,0.172108,0.095377,0.292266,...,-0.004466,-0.007679,-0.005858,-0.011857,0.231403,0.000233,-0.000012,0.000592,-0.000161,47.574276
45,decision_tree,unsw_nb15,iot23,cross_dataset,0.024384,0.037701,0.014982,0.059896,0.023969,0.024384,...,-0.001390,-0.005152,-0.002192,-0.008066,0.002846,0.014460,-0.000389,0.017854,-0.000767,10.542460
46,linear_svm,unsw_nb15,iot23,cross_dataset,0.787050,0.494600,0.090795,0.007184,0.013314,0.446979,...,-0.005524,0.000446,0.000692,-0.000254,0.009111,-0.001482,-0.000346,-0.001266,-0.000377,35.570780
47,mlp,unsw_nb15,iot23,cross_dataset,0.719861,0.452459,0.016384,0.006787,0.009598,0.423228,...,-0.008039,-0.003369,-0.004748,-0.002454,0.009298,-0.000233,0.000467,-0.000234,0.000172,211.440944
48,random_forest,unsw_nb15,iot23,cross_dataset,0.092088,0.078251,0.015121,0.055189,0.023738,0.087616,...,-0.011953,-0.043745,-0.018775,-0.011057,0.128638,0.002772,-0.000125,0.004408,-0.000253,542.849537
49,xgboost,unsw_nb15,iot23,cross_dataset,0.077622,0.052731,0.003094,0.011246,0.004853,0.072663,...,-0.000175,-0.000694,-0.000280,0.003127,0.362290,0.000233,-0.000012,0.000592,-0.000161,47.574276
50,decision_tree,unsw_nb15,unsw_nb15,intra_dataset,0.981531,0.972238,0.951189,0.956750,0.953962,0.971205,...,-0.010479,0.038395,0.013201,0.008122,-0.005798,0.014460,-0.000389,0.017854,-0.000767,10.542460
51,linear_svm,unsw_nb15,unsw_nb15,intra_dataset,0.954164,0.906831,0.935460,0.827942,0.878423,0.925091,...,-0.000123,-0.001684,-0.001003,-0.000602,-0.006266,-0.001482,-0.000346,-0.001266,-0.000377,35.570780
52,mlp,unsw_nb15,unsw_nb15,intra_dataset,0.986188,0.990178,0.937998,0.996829,0.966519,0.978909,...,0.000179,-0.001437,-0.000581,-0.000361,0.035491,-0.000233,0.000467,-0.000234,0.000172,211.440944
53,random_forest,unsw_nb15,unsw_nb15,intra_dataset,0.986178,0.986772,0.945556,0.987763,0.966199,0.978756,...,-0.003708,0.008818,0.002243,0.001376,0.501628,0.002772,-0.000125,0.004408,-0.000253,542.849537
54,xgboost,unsw_nb15,unsw_nb15,intra_dataset,0.987070,0.990748,0.941865,0.996879,0.968591,0.980225,...,-0.000512,0.001090,0.000243,0.000149,0.406159,0.000233,-0.000012,0.000592,-0.000161,47.574276
55,decision_tree,unsw_nb15_iot23,cicids2017,combined_to_unseen,0.673351,0.460881,0.126082,0.106762,0.115621,0.457651,...,0.094809,0.075105,0.083868,0.052839,-0.001877,0.006409,-0.000577,0.007965,-0.000458,21.006020
56,linear_svm,unsw_nb15_iot23,cicids2017,combined_to_unseen,0.509824,0.685466,0.287091,0.978202,0.443902,0.502838,...,-0.002326,0.001189,-0.002665,-0.005257,-0.000960,0.002578,0.004502,0.008788,0.000833,87.031809
57,mlp,unsw_nb15_iot23,cicids2017,combined_to_unseen,0.800436,0.714051,0.500958,0.570077,0.533287,0.703185,...,-0.020965,-0.012633,-0.017460,-0.012022,0.013446,0.011435,-0.002623,0.008914,-0.002747,361.691011
58,random_forest,unsw_nb15_iot23,cicids2017,combined_to_unseen,0.715799,0.486611,0.166012,0.104632,0.128362,0.479291,...,-0.007362,-0.002180,-0.003858,-0.003276,0.637656,0.001698,0.000107,0.002375,0.000069,1030.251347
59,xgboost,unsw_nb15_iot23,cicids2017,combined_to_unseen,0.749547,0.549560,0.315801,0.216250,0.256712,0.553056,...,0.030424,0.097300,0.072367,0.032507,0.245483,0.000120,-0.000142,-0.000056,-0.000130,92.607777

In [5]:
def show_reports(
    training_name,
    test_name,
    show_baseline=True,
    show_randomized_search=False,
    show_classification_report=True,
    show_confusion_matrix=True,
):
    versions = []
    if show_baseline:
        versions.append("baseline")
    if show_randomized_search:
        versions.append("randomized_search")

    for model_name in MODELS_TO_EVALUATE:
        report_dir = OUTPUT_DIR / training_name / model_name

        for version in versions:
            if show_classification_report:
                report_path = report_dir / f"{version}_{test_name}.txt"
                print(report_path.read_text(encoding="utf-8"))

            if show_confusion_matrix:
                matrix_path = report_dir / f"{version}_{test_name}_confusion_matrix.txt"
                print(matrix_path.read_text(encoding="utf-8"))

In [6]:
show_reports("cicids2017", "cicids2017")

Treino: cicids2017 | Modelo: decision_tree | Configuração: padrão | Teste: cicids2017

              precision    recall  f1-score   support

      BENIGN     0.9972    0.9953    0.9963     80740
      ATTACK     0.9815    0.9889    0.9852     20185

    accuracy                         0.9941    100925
   macro avg     0.9894    0.9921    0.9907    100925
weighted avg     0.9941    0.9941    0.9941    100925

Treino: cicids2017 | Modelo: decision_tree | Configuração: padrão | Teste: cicids2017

             Predito BENIGN  Predito ATTACK
Real BENIGN           80364             376
Real ATTACK             224           19961
Treino: cicids2017 | Modelo: random_forest | Configuração: padrão | Teste: cicids2017

              precision    recall  f1-score   support

      BENIGN     0.9983    0.9952    0.9968     80740
      ATTACK     0.9811    0.9934    0.9872     20185

    accuracy                         0.9948    100925
   macro avg     0.9897    0.9943    0.9920    100925
weighted avg     0.9949    0.9948    0.9949    100925

Treino: cicids2017 | Modelo: random_forest | Configuração: padrão | Teste: cicids2017

             Predito BENIGN  Predito ATTACK
Real BENIGN           80353             387
Real ATTACK             133           20052
Treino: cicids2017 | Modelo: xgboost | Configuração: padrão | Teste: cicids2017

              precision    recall  f1-score   support

      BENIGN     0.9985    0.9947    0.9966     80740
      ATTACK     0.9793    0.9940    0.9866     20185

    accuracy                         0.9946    100925
   macro avg     0.9889    0.9943    0.9916    100925
weighted avg     0.9946    0.9946    0.9946    100925

Treino: cicids2017 | Modelo: xgboost | Configuração: padrão | Teste: cicids2017

             Predito BENIGN  Predito ATTACK
Real BENIGN           80315             425
Real ATTACK             122           20063
Treino: cicids2017 | Modelo: linear_svm | Configuração: padrão | Teste: cicids2017

              precision    recall  f1-score   support

      BENIGN     0.8972    0.9714    0.9329     80740
      ATTACK     0.8292    0.5550    0.6649     20185

    accuracy                         0.8881    100925
   macro avg     0.8632    0.7632    0.7989    100925
weighted avg     0.8836    0.8881    0.8793    100925

Treino: cicids2017 | Modelo: linear_svm | Configuração: padrão | Teste: cicids2017

             Predito BENIGN  Predito ATTACK
Real BENIGN           78433            2307
Real ATTACK            8983           11202
Treino: cicids2017 | Modelo: mlp | Configuração: padrão | Teste: cicids2017

              precision    recall  f1-score   support

      BENIGN     0.9979    0.9942    0.9960     80740
      ATTACK     0.9771    0.9916    0.9843     20185

    accuracy                         0.9937    100925
   macro avg     0.9875    0.9929    0.9902    100925
weighted avg     0.9937    0.9937    0.9937    100925

Treino: cicids2017 | Modelo: mlp | Configuração: padrão | Teste: cicids2017

             Predito BENIGN  Predito ATTACK
Real BENIGN           80271             469
Real ATTACK             169           20016

In [7]:
show_reports("cicids2017", "unsw_nb15")

Treino: cicids2017 | Modelo: decision_tree | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.7957    0.9708    0.8746     80740
      ATTACK     0.0244    0.0029    0.0052     20185

    accuracy                         0.7772    100925
   macro avg     0.4101    0.4869    0.4399    100925
weighted avg     0.6414    0.7772    0.7007    100925

Treino: cicids2017 | Modelo: decision_tree | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           78382            2358
Real ATTACK           20126              59
Treino: cicids2017 | Modelo: random_forest | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8000    0.9998    0.8888     80740
      ATTACK     0.0000    0.0000    0.0000     20185

    accuracy                         0.7999    100925
   macro avg     0.4000    0.4999    0.4444    100925
weighted avg     0.6400    0.7999    0.7110    100925

Treino: cicids2017 | Modelo: random_forest | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80726              14
Real ATTACK           20185               0
Treino: cicids2017 | Modelo: xgboost | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.7999    0.9996    0.8887     80740
      ATTACK     0.0000    0.0000    0.0000     20185

    accuracy                         0.7997    100925
   macro avg     0.4000    0.4998    0.4444    100925
weighted avg     0.6400    0.7997    0.7110    100925

Treino: cicids2017 | Modelo: xgboost | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80711              29
Real ATTACK           20185               0
Treino: cicids2017 | Modelo: linear_svm | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.7996    0.9957    0.8869     80740
      ATTACK     0.0954    0.0018    0.0036     20185

    accuracy                         0.7969    100925
   macro avg     0.4475    0.4987    0.4453    100925
weighted avg     0.6587    0.7969    0.7103    100925

Treino: cicids2017 | Modelo: linear_svm | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80389             351
Real ATTACK           20148              37
Treino: cicids2017 | Modelo: mlp | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8000    0.9992    0.8886     80740
      ATTACK     0.1975    0.0008    0.0016     20185

    accuracy                         0.7995    100925
   macro avg     0.4988    0.5000    0.4451    100925
weighted avg     0.6795    0.7995    0.7112    100925

Treino: cicids2017 | Modelo: mlp | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80675              65
Real ATTACK           20169              16

In [8]:
show_reports(
    "cicids2017_iot23",
    "unsw_nb15",
    show_randomized_search=True,
)

Treino: cicids2017_iot23 | Modelo: decision_tree | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8101    0.9934    0.8925     80740
      ATTACK     0.7231    0.0686    0.1253     20185

    accuracy                         0.8085    100925
   macro avg     0.7666    0.5310    0.5089    100925
weighted avg     0.7927    0.8085    0.7390    100925

Treino: cicids2017_iot23 | Modelo: decision_tree | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80210             530
Real ATTACK           18801            1384
Treino: cicids2017_iot23 | Modelo: decision_tree | Configuração: RandomizedSearchCV | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8061    0.9937    0.8901     80740
      ATTACK     0.6340    0.0439    0.0822     20185

    accuracy                         0.8037    100925
   macro avg     0.7201    0.5188    0.4861    100925
weighted avg     0.7717    0.8037    0.7285    100925

Treino: cicids2017_iot23 | Modelo: decision_tree | Configuração: RandomizedSearchCV | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80228             512
Real ATTACK           19298             887
Treino: cicids2017_iot23 | Modelo: random_forest | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8049    0.9986    0.8913     80740
      ATTACK     0.8479    0.0318    0.0612     20185

    accuracy                         0.8052    100925
   macro avg     0.8264    0.5152    0.4763    100925
weighted avg     0.8135    0.8052    0.7253    100925

Treino: cicids2017_iot23 | Modelo: random_forest | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80625             115
Real ATTACK           19544             641
Treino: cicids2017_iot23 | Modelo: random_forest | Configuração: RandomizedSearchCV | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8044    0.9987    0.8911     80740
      ATTACK     0.8433    0.0288    0.0557     20185

    accuracy                         0.8047    100925
   macro avg     0.8238    0.5137    0.4734    100925
weighted avg     0.8122    0.8047    0.7240    100925

Treino: cicids2017_iot23 | Modelo: random_forest | Configuração: RandomizedSearchCV | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80632             108
Real ATTACK           19604             581
Treino: cicids2017_iot23 | Modelo: xgboost | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.7999    0.9988    0.8883     80740
      ATTACK     0.0741    0.0004    0.0008     20185

    accuracy                         0.7991    100925
   macro avg     0.4370    0.4996    0.4446    100925
weighted avg     0.6547    0.7991    0.7108    100925

Treino: cicids2017_iot23 | Modelo: xgboost | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80640             100
Real ATTACK           20177               8
Treino: cicids2017_iot23 | Modelo: xgboost | Configuração: RandomizedSearchCV | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8000    0.9997    0.8888     80740
      ATTACK     0.2571    0.0004    0.0009     20185

    accuracy                         0.7998    100925
   macro avg     0.5286    0.5001    0.4448    100925
weighted avg     0.6914    0.7998    0.7112    100925

Treino: cicids2017_iot23 | Modelo: xgboost | Configuração: RandomizedSearchCV | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80714              26
Real ATTACK           20176               9
Treino: cicids2017_iot23 | Modelo: linear_svm | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.7977    0.9712    0.8759     80740
      ATTACK     0.1123    0.0146    0.0258     20185

    accuracy                         0.7799    100925
   macro avg     0.4550    0.4929    0.4509    100925
weighted avg     0.6606    0.7799    0.7059    100925

Treino: cicids2017_iot23 | Modelo: linear_svm | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           78415            2325
Real ATTACK           19891             294
Treino: cicids2017_iot23 | Modelo: linear_svm | Configuração: RandomizedSearchCV | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8097    0.9585    0.8778     80740
      ATTACK     0.3733    0.0988    0.1563     20185

    accuracy                         0.7866    100925
   macro avg     0.5915    0.5287    0.5171    100925
weighted avg     0.7224    0.7866    0.7335    100925

Treino: cicids2017_iot23 | Modelo: linear_svm | Configuração: RandomizedSearchCV | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           77391            3349
Real ATTACK           18190            1995
Treino: cicids2017_iot23 | Modelo: mlp | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8054    0.9951    0.8903     80740
      ATTACK     0.6621    0.0382    0.0723     20185

    accuracy                         0.8037    100925
   macro avg     0.7337    0.5167    0.4813    100925
weighted avg     0.7767    0.8037    0.7267    100925

Treino: cicids2017_iot23 | Modelo: mlp | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80346             394
Real ATTACK           19413             772
Treino: cicids2017_iot23 | Modelo: mlp | Configuração: RandomizedSearchCV | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.8065    0.9969    0.8916     80740
      ATTACK     0.7750    0.0430    0.0815     20185

    accuracy                         0.8061    100925
   macro avg     0.7907    0.5199    0.4865    100925
weighted avg     0.8002    0.8061    0.7296    100925

Treino: cicids2017_iot23 | Modelo: mlp | Configuração: RandomizedSearchCV | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           80488             252
Real ATTACK           19317             868

In [9]:
show_reports("unsw_nb15", "unsw_nb15")

Treino: unsw_nb15 | Modelo: decision_tree | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.9892    0.9877    0.9884     80740
      ATTACK     0.9512    0.9568    0.9540     20185

    accuracy                         0.9815    100925
   macro avg     0.9702    0.9722    0.9712    100925
weighted avg     0.9816    0.9815    0.9816    100925

Treino: unsw_nb15 | Modelo: decision_tree | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           79749             991
Real ATTACK             873           19312
Treino: unsw_nb15 | Modelo: random_forest | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.9969    0.9858    0.9913     80740
      ATTACK     0.9456    0.9878    0.9662     20185

    accuracy                         0.9862    100925
   macro avg     0.9712    0.9868    0.9788    100925
weighted avg     0.9866    0.9862    0.9863    100925

Treino: unsw_nb15 | Modelo: random_forest | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           79592            1148
Real ATTACK             247           19938
Treino: unsw_nb15 | Modelo: xgboost | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.9992    0.9846    0.9919     80740
      ATTACK     0.9419    0.9969    0.9686     20185

    accuracy                         0.9871    100925
   macro avg     0.9705    0.9907    0.9802    100925
weighted avg     0.9877    0.9871    0.9872    100925

Treino: unsw_nb15 | Modelo: xgboost | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           79498            1242
Real ATTACK              63           20122
Treino: unsw_nb15 | Modelo: linear_svm | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.9582    0.9857    0.9718     80740
      ATTACK     0.9355    0.8279    0.8784     20185

    accuracy                         0.9542    100925
   macro avg     0.9468    0.9068    0.9251    100925
weighted avg     0.9536    0.9542    0.9531    100925

Treino: unsw_nb15 | Modelo: linear_svm | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           79587            1153
Real ATTACK            3473           16712
Treino: unsw_nb15 | Modelo: mlp | Configuração: padrão | Teste: unsw_nb15

              precision    recall  f1-score   support

      BENIGN     0.9992    0.9835    0.9913     80740
      ATTACK     0.9380    0.9968    0.9665     20185

    accuracy                         0.9862    100925
   macro avg     0.9686    0.9902    0.9789    100925
weighted avg     0.9870    0.9862    0.9863    100925

Treino: unsw_nb15 | Modelo: mlp | Configuração: padrão | Teste: unsw_nb15

             Predito BENIGN  Predito ATTACK
Real BENIGN           79410            1330
Real ATTACK              64           20121

In [10]:
show_reports("iot23", "iot23")

Treino: iot23 | Modelo: decision_tree | Configuração: padrão | Teste: iot23

              precision    recall  f1-score   support

      BENIGN     0.9987    0.9997    0.9992     80740
      ATTACK     0.9987    0.9947    0.9967     20185

    accuracy                         0.9987    100925
   macro avg     0.9987    0.9972    0.9979    100925
weighted avg     0.9987    0.9987    0.9987    100925

Treino: iot23 | Modelo: decision_tree | Configuração: padrão | Teste: iot23

             Predito BENIGN  Predito ATTACK
Real BENIGN           80713              27
Real ATTACK             106           20079
Treino: iot23 | Modelo: random_forest | Configuração: padrão | Teste: iot23

              precision    recall  f1-score   support

      BENIGN     0.9987    0.9997    0.9992     80740
      ATTACK     0.9986    0.9947    0.9966     20185

    accuracy                         0.9987    100925
   macro avg     0.9986    0.9972    0.9979    100925
weighted avg     0.9987    0.9987    0.9987    100925

Treino: iot23 | Modelo: random_forest | Configuração: padrão | Teste: iot23

             Predito BENIGN  Predito ATTACK
Real BENIGN           80712              28
Real ATTACK             107           20078
Treino: iot23 | Modelo: xgboost | Configuração: padrão | Teste: iot23

              precision    recall  f1-score   support

      BENIGN     0.9986    0.9999    0.9993     80740
      ATTACK     0.9997    0.9946    0.9971     20185

    accuracy                         0.9989    100925
   macro avg     0.9992    0.9972    0.9982    100925
weighted avg     0.9989    0.9989    0.9988    100925

Treino: iot23 | Modelo: xgboost | Configuração: padrão | Teste: iot23

             Predito BENIGN  Predito ATTACK
Real BENIGN           80734               6
Real ATTACK             110           20075
Treino: iot23 | Modelo: linear_svm | Configuração: padrão | Teste: iot23

              precision    recall  f1-score   support

      BENIGN     0.9978    0.9987    0.9983     80740
      ATTACK     0.9949    0.9914    0.9931     20185

    accuracy                         0.9973    100925
   macro avg     0.9964    0.9951    0.9957    100925
weighted avg     0.9973    0.9973    0.9973    100925

Treino: iot23 | Modelo: linear_svm | Configuração: padrão | Teste: iot23

             Predito BENIGN  Predito ATTACK
Real BENIGN           80637             103
Real ATTACK             174           20011
Treino: iot23 | Modelo: mlp | Configuração: padrão | Teste: iot23

              precision    recall  f1-score   support

      BENIGN     0.9980    0.9999    0.9990     80740
      ATTACK     0.9998    0.9921    0.9959     20185

    accuracy                         0.9984    100925
   macro avg     0.9989    0.9960    0.9974    100925
weighted avg     0.9984    0.9984    0.9984    100925

Treino: iot23 | Modelo: mlp | Configuração: padrão | Teste: iot23

             Predito BENIGN  Predito ATTACK
Real BENIGN           80735               5
Real ATTACK             160           20025