In [1]:
# importações, caminhos, categorias e funções auxiliares
import os
from pathlib import Path

import kaleido
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from IPython.display import display

KALEIDO_CHROME_PATH = Path(kaleido.get_chrome_sync())
if not KALEIDO_CHROME_PATH.is_file():
    raise FileNotFoundError(
        f"Chrome gerenciado pelo Kaleido não encontrado: {KALEIDO_CHROME_PATH}"
    )
os.environ["BROWSER_PATH"] = str(KALEIDO_CHROME_PATH)
print(f"Chrome usado pelo Kaleido: {KALEIDO_CHROME_PATH}")

ROOT = Path(r"C:\tcc\network-ids-ml-generalization")
TRAINING_RESULTS_DIR = ROOT / "results" / "model_training" / "randomized_search"
EVALUATION_RESULTS_DIR = ROOT / "results" / "model_evaluation"
ANALYSIS_DIR = ROOT / "results" / "results_analysis"
TABLES_DIR = ANALYSIS_DIR / "tables"
FIGURES_DIR = ANALYSIS_DIR / "figures"
SVG_DIR = FIGURES_DIR / "svg"
PNG_DIR = FIGURES_DIR / "png"

for output_directory in [TABLES_DIR, SVG_DIR, PNG_DIR]:
    output_directory.mkdir(parents=True, exist_ok=True)

for output_directory, output_pattern in [
    (TABLES_DIR, "*.csv"),
    (SVG_DIR, "*.svg"),
    (PNG_DIR, "*.png"),
]:
    for previous_output in output_directory.glob(output_pattern):
        previous_output.unlink()

MODEL_ORDER = ["decision_tree", "random_forest", "xgboost", "linear_svm", "mlp"]
SCENARIO_ORDER = ["intra_dataset", "cross_dataset", "combined_to_unseen"]
TRAINING_SOURCE_ORDER = [
    "cicids2017",
    "unsw_nb15",
    "iot23",
    "cicids2017_unsw_nb15",
    "cicids2017_iot23",
    "unsw_nb15_iot23",
]
TEST_SOURCE_ORDER = ["cicids2017", "unsw_nb15", "iot23"]

MODEL_LABELS = {
    "decision_tree": "Árvore de decisão",
    "random_forest": "Random Forest",
    "xgboost": "XGBoost",
    "linear_svm": "SVM linear",
    "mlp": "MLP",
}
MODEL_ABBREVIATIONS = {
    "decision_tree": "DT",
    "random_forest": "RF",
    "xgboost": "XGB",
    "linear_svm": "SVM",
    "mlp": "MLP",
}
SCENARIO_LABELS = {
    "intra_dataset": "Intra-dataset",
    "cross_dataset": "Cross-dataset",
    "combined_to_unseen": "Combinado",
}
SCENARIO_FILE_LABELS = {
    "intra_dataset": "intra_dataset",
    "cross_dataset": "cross_dataset",
    "combined_to_unseen": "combined",
}
SOURCE_LABELS = {
    "cicids2017": "CICIDS2017",
    "unsw_nb15": "UNSW-NB15",
    "iot23": "IoT-23",
    "cicids2017_unsw_nb15": "CICIDS2017 + UNSW-NB15",
    "cicids2017_iot23": "CICIDS2017 + IoT-23",
    "unsw_nb15_iot23": "UNSW-NB15 + IoT-23",
}
SOURCE_ABBREVIATIONS = {
    "cicids2017": "CIC",
    "unsw_nb15": "UNSW",
    "iot23": "IoT",
    "cicids2017_unsw_nb15": "CIC+UNSW",
    "cicids2017_iot23": "CIC+IoT",
    "unsw_nb15_iot23": "UNSW+IoT",
}
MODEL_COLORS = {
    "Árvore de decisão": "#4C78A8",
    "Random Forest": "#F58518",
    "XGBoost": "#54A24B",
    "SVM linear": "#E45756",
    "MLP": "#B279A2",
}

EVALUATION_METRICS = [
    "accuracy",
    "balanced_accuracy",
    "precision_attack",
    "recall_attack",
    "f1_attack",
    "precision_benign",
    "recall_benign",
    "f1_benign",
    "f1_macro",
]
CV_METRICS = EVALUATION_METRICS.copy()

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 120)

saved_tables = []
saved_figures = []


def save_table(dataframe, filename):
    output_path = TABLES_DIR / filename
    dataframe.to_csv(output_path, index=False)
    saved_tables.append(output_path)
    return output_path


def format_table_for_display(dataframe):
    output = dataframe.copy()
    label_maps = {
        "model": MODEL_LABELS,
        "scenario_type": SCENARIO_LABELS,
        "training_source": SOURCE_LABELS,
        "test_source": SOURCE_LABELS,
    }
    for column, label_map in label_maps.items():
        if column in output.columns:
            output[column] = output[column].map(label_map).fillna(output[column])
    return output


def finalize_figure(
    figure,
    filename,
    width,
    height,
    top_margin=130,
    legend_y=1.08,
):
    figure.update_layout(
        template="plotly_white",
        font=dict(family="Arial", size=13),
        title_x=0.5,
        margin=dict(l=80, r=40, t=top_margin, b=80),
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=legend_y,
            xanchor="center",
            x=0.5,
        ),
    )

    svg_path = SVG_DIR / f"{filename}.svg"
    png_path = PNG_DIR / f"{filename}.png"

    display(figure)
    figure.write_image(svg_path, format="svg", width=width, height=height)
    figure.write_image(
        png_path,
        format="png",
        width=width,
        height=height,
        scale=2,
    )

    saved_figures.extend([svg_path, png_path])
    return svg_path, png_path

Chrome usado pelo Kaleido: C:\Users\valde\AppData\Local\plotly\choreographer\deps\chrome-win64\chrome.exe

In [2]:
# carregamento e validação dos resultados
training_summary_files = [
    TRAINING_RESULTS_DIR / model_name / "summary.csv"
    for model_name in MODEL_ORDER
]
training_summary = pd.concat(
    [pd.read_csv(summary_path) for summary_path in training_summary_files],
    ignore_index=True,
)
evaluation = pd.read_csv(EVALUATION_RESULTS_DIR / "evaluation_summary.csv")

assert len(training_summary) == 30, (
    "Os resumos do RandomizedSearchCV devem totalizar 30 registros."
)
assert len(evaluation) == 60, (
    "A avaliação deve possuir 60 registros."
)
assert not training_summary.duplicated(
    ["model", "training_source"]
).any()
assert not evaluation.duplicated(
    ["model", "training_source", "test_source"]
).any()
assert set(evaluation["selection_method"]) == {"randomized_search"}

required_evaluation_metrics = EVALUATION_METRICS + ["f1_weighted"]
required_cv_columns = [
    f"{metric}_{suffix}"
    for metric in CV_METRICS
    for suffix in ["mean", "std"]
]

assert not evaluation[required_evaluation_metrics].isna().any().any(), (
    "Há métricas finais ausentes."
)
assert not training_summary[required_cv_columns].isna().any().any(), (
    "Há métricas de validação cruzada ausentes."
)
for metric in required_evaluation_metrics:
    assert evaluation[metric].between(0, 1).all(), (
        f"Valores inválidos em {metric}."
    )

scenario_counts = (
    evaluation.groupby("scenario_type", as_index=False)
    .size()
    .rename(columns={"size": "evaluations"})
)
expected_scenario_counts = {
    "intra_dataset": 15,
    "cross_dataset": 30,
    "combined_to_unseen": 15,
}
assert scenario_counts.set_index("scenario_type")["evaluations"].to_dict() == (
    expected_scenario_counts
)

validation_summary = pd.DataFrame({
    "item": [
        "resumos de treinamento",
        "avaliações",
        "duplicidades",
        "métricas ausentes",
    ],
    "valor": [
        len(training_summary),
        len(evaluation),
        0,
        0,
    ],
    "status": "ok",
})
display(validation_summary)
display(format_table_for_display(scenario_counts))

                     item  valor status
0  resumos de treinamento     30     ok
1              avaliações     60     ok
2            duplicidades      0     ok
3       métricas ausentes      0     ok

   scenario_type  evaluations
0      Combinado           15
1  Cross-dataset           30
2  Intra-dataset           15

In [3]:
# tabelas de validação cruzada e avaliação
def format_mean_std(mean_value, std_value):
    return f"{mean_value:.4f} ± {std_value:.4f}"


model_order_map = {
    model: index for index, model in enumerate(MODEL_ORDER)
}
training_source_order_map = {
    source: index for index, source in enumerate(TRAINING_SOURCE_ORDER)
}
test_source_order_map = {
    source: index for index, source in enumerate(TEST_SOURCE_ORDER)
}

cv_source = training_summary.copy()
cv_source["model_order"] = cv_source["model"].map(model_order_map)
cv_source["training_source_order"] = (
    cv_source["training_source"].map(training_source_order_map)
)
cv_source = cv_source.sort_values(
    ["training_source_order", "model_order"]
)

cv_presentation = pd.DataFrame({
    "Conjunto de treinamento": cv_source["training_source"].map(SOURCE_LABELS),
    "Modelo": cv_source["model"].map(MODEL_ABBREVIATIONS),
    "Hiperparâmetros vencedores": cv_source["params"],
    "F1 macro (média ± desvio-padrão)": [
        format_mean_std(mean_value, std_value)
        for mean_value, std_value in zip(
            cv_source["f1_macro_mean"],
            cv_source["f1_macro_std"],
        )
    ],
    "Acurácia balanceada (média ± desvio-padrão)": [
        format_mean_std(mean_value, std_value)
        for mean_value, std_value in zip(
            cv_source["balanced_accuracy_mean"],
            cv_source["balanced_accuracy_std"],
        )
    ],
    "Precisão ATTACK (média ± desvio-padrão)": [
        format_mean_std(mean_value, std_value)
        for mean_value, std_value in zip(
            cv_source["precision_attack_mean"],
            cv_source["precision_attack_std"],
        )
    ],
    "Recall ATTACK (média ± desvio-padrão)": [
        format_mean_std(mean_value, std_value)
        for mean_value, std_value in zip(
            cv_source["recall_attack_mean"],
            cv_source["recall_attack_std"],
        )
    ],
    "F1 ATTACK (média ± desvio-padrão)": [
        format_mean_std(mean_value, std_value)
        for mean_value, std_value in zip(
            cv_source["f1_attack_mean"],
            cv_source["f1_attack_std"],
        )
    ],
    "Tempo total de treinamento (s)": cv_source["elapsed_seconds"].round(3),
})
save_table(cv_presentation, "cross_validation_summary.csv")

evaluation_source = evaluation.copy()
evaluation_source["model_order"] = (
    evaluation_source["model"].map(model_order_map)
)
evaluation_source["training_source_order"] = (
    evaluation_source["training_source"].map(training_source_order_map)
)
evaluation_source["test_source_order"] = (
    evaluation_source["test_source"].map(test_source_order_map)
)
evaluation_source = evaluation_source.sort_values([
    "training_source_order",
    "test_source_order",
    "model_order",
])

evaluation_presentation = pd.DataFrame({
    "Conjunto de treinamento": (
        evaluation_source["training_source"].map(SOURCE_LABELS)
    ),
    "Conjunto de teste": (
        evaluation_source["test_source"].map(SOURCE_LABELS)
    ),
    "Cenário de avaliação": (
        evaluation_source["scenario_type"].map(SCENARIO_LABELS)
    ),
    "Modelo": evaluation_source["model"].map(MODEL_ABBREVIATIONS),
    "Acurácia": evaluation_source["accuracy"].round(4),
    "Acurácia balanceada": (
        evaluation_source["balanced_accuracy"].round(4)
    ),
    "Precisão ATTACK": evaluation_source["precision_attack"].round(4),
    "Recall ATTACK": evaluation_source["recall_attack"].round(4),
    "F1 ATTACK": evaluation_source["f1_attack"].round(4),
    "Precisão BENIGN": evaluation_source["precision_benign"].round(4),
    "Recall BENIGN": evaluation_source["recall_benign"].round(4),
    "F1 BENIGN": evaluation_source["f1_benign"].round(4),
    "F1 macro": evaluation_source["f1_macro"].round(4),
})
save_table(evaluation_presentation, "evaluation_all.csv")

cv_metrics_for_evaluation = training_summary[[
    "training_source",
    "model",
    "f1_macro_mean",
    "f1_macro_std",
    "balanced_accuracy_mean",
    "balanced_accuracy_std",
]].copy()
tcc_table_source = evaluation_source.merge(
    cv_metrics_for_evaluation,
    on=["training_source", "model"],
    how="left",
    validate="many_to_one",
)
tcc_table_source = tcc_table_source.sort_values([
    "training_source_order",
    "test_source_order",
    "model_order",
]).reset_index(drop=True)

tcc_cv_columns = [
    "f1_macro_mean",
    "f1_macro_std",
    "balanced_accuracy_mean",
    "balanced_accuracy_std",
]
assert len(tcc_table_source) == len(evaluation_source) == 60
assert not tcc_table_source[tcc_cv_columns].isna().any().any(), (
    "A tabela do TCC possui métricas de validação cruzada ausentes."
)

tcc_results_table = pd.DataFrame({
    "Conjunto de treinamento": (
        tcc_table_source["training_source"].map(SOURCE_LABELS)
    ),
    "Conjunto de teste": (
        tcc_table_source["test_source"].map(SOURCE_LABELS)
    ),
    "Modelo": tcc_table_source["model"].map(MODEL_ABBREVIATIONS),
    "F1 macro": tcc_table_source["f1_macro"].round(4),
    "Acurácia balanceada": (
        tcc_table_source["balanced_accuracy"].round(4)
    ),
    "Precisão BENIGN": (
        tcc_table_source["precision_benign"].round(4)
    ),
    "Recall BENIGN": (
        tcc_table_source["recall_benign"].round(4)
    ),
    "Precisão ATTACK": (
        tcc_table_source["precision_attack"].round(4)
    ),
    "Recall ATTACK": (
        tcc_table_source["recall_attack"].round(4)
    ),
    "F1 macro CV (média)": (
        tcc_table_source["f1_macro_mean"].round(4)
    ),
    "F1 macro CV (desvio-padrão)": (
        tcc_table_source["f1_macro_std"].round(4)
    ),
    "Acurácia balanceada CV (média)": (
        tcc_table_source["balanced_accuracy_mean"].round(4)
    ),
    "Acurácia balanceada CV (desvio-padrão)": (
        tcc_table_source["balanced_accuracy_std"].round(4)
    ),
})
assert not tcc_results_table.isna().any().any(), (
    "A tabela do TCC não deve possuir células vazias."
)
save_table(tcc_results_table, "tcc_results_table.csv")

scenario_presentation_tables = {}
for scenario_type in SCENARIO_ORDER:
    scenario_table = evaluation_presentation[
        evaluation_presentation["Cenário de avaliação"].eq(
            SCENARIO_LABELS[scenario_type]
        )
    ].copy()
    scenario_presentation_tables[scenario_type] = scenario_table
    save_table(
        scenario_table,
        f"evaluation_{SCENARIO_FILE_LABELS[scenario_type]}.csv",
    )

best_algorithm_by_experiment = (
    evaluation.sort_values(
        ["f1_macro", "balanced_accuracy", "f1_attack"],
        ascending=[False, False, False],
    )
    .groupby(["training_source", "test_source"], as_index=False)
    .head(1)
    .sort_values(["training_source", "test_source"])
)
save_table(
    format_table_for_display(
        best_algorithm_by_experiment[
            [
                "training_source",
                "test_source",
                "scenario_type",
                "model",
            ] + EVALUATION_METRICS
        ]
    ),
    "best_algorithm_by_experiment.csv",
)

best_per_scenario = (
    evaluation.sort_values(
        ["scenario_type", "f1_macro", "balanced_accuracy"],
        ascending=[True, False, False],
    )
    .groupby("scenario_type", as_index=False)
    .head(1)
    .assign(result="Melhor")
)
worst_per_scenario = (
    evaluation.sort_values(
        ["scenario_type", "f1_macro", "balanced_accuracy"],
        ascending=[True, True, True],
    )
    .groupby("scenario_type", as_index=False)
    .head(1)
    .assign(result="Pior")
)
performance_extremes = pd.concat(
    [best_per_scenario, worst_per_scenario],
    ignore_index=True,
)
save_table(
    format_table_for_display(
        performance_extremes[
            [
                "result",
                "scenario_type",
                "model",
                "training_source",
                "test_source",
            ] + EVALUATION_METRICS
        ]
    ),
    "performance_extremes_by_scenario.csv",
)

metric_discrepancies = (
    evaluation.assign(
        accuracy_minus_f1_attack=(
            evaluation["accuracy"] - evaluation["f1_attack"]
        )
    )
    .nlargest(5, "accuracy_minus_f1_attack")
)
save_table(
    format_table_for_display(
        metric_discrepancies[
            [
                "model",
                "training_source",
                "test_source",
                "scenario_type",
                "accuracy",
                "f1_attack",
                "accuracy_minus_f1_attack",
            ]
        ]
    ),
    "performance_metric_discrepancies.csv",
)

display(cv_presentation)
for scenario_type in SCENARIO_ORDER:
    print(f"Avaliação - {SCENARIO_LABELS[scenario_type]}")
    display(scenario_presentation_tables[scenario_type])

print("Tabela consolidada para o TCC")
display(tcc_results_table)

,Conjunto de treinamento,Modelo,Hiperparâmetros vencedores,F1 macro (média ± desvio-padrão),Acurácia balanceada (média ± desvio-padrão),Precisão ATTACK (média ± desvio-padrão),Recall ATTACK (média ± desvio-padrão),F1 ATTACK (média ± desvio-padrão),Tempo total de treinamento (s)
0,CICIDS2017,DT,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_d...",0.9904 ± 0.0004,0.9915 ± 0.0007,0.9816 ± 0.0013,0.9876 ± 0.0015,0.9846 ± 0.0006,23.353
6,CICIDS2017,RF,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__c...",0.9925 ± 0.0006,0.9957 ± 0.0004,0.9796 ± 0.0019,0.9967 ± 0.0008,0.9880 ± 0.0009,829.363
12,CICIDS2017,XGB,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_...",0.9918 ± 0.0006,0.9941 ± 0.0008,0.9810 ± 0.0011,0.9930 ± 0.0015,0.9870 ± 0.0010,51.374
18,CICIDS2017,SVM,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier...",0.9029 ± 0.0018,0.9435 ± 0.0017,0.7605 ± 0.0031,0.9629 ± 0.0025,0.8498 ± 0.0028,59.615
24,CICIDS2017,MLP,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 1.9726066891840947e-05, ""classifier__batch_size"": ""auto"", ""c...",0.9908 ± 0.0008,0.9938 ± 0.0005,0.9773 ± 0.0023,0.9934 ± 0.0008,0.9852 ± 0.0013,263.605
1,UNSW-NB15,DT,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_d...",0.9799 ± 0.0006,0.9898 ± 0.0005,0.9427 ± 0.0015,0.9947 ± 0.0008,0.9680 ± 0.0010,20.747
7,UNSW-NB15,RF,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__c...",0.9809 ± 0.0004,0.9911 ± 0.0002,0.9436 ± 0.0014,0.9972 ± 0.0005,0.9696 ± 0.0007,822.875
13,UNSW-NB15,XGB,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_...",0.9810 ± 0.0003,0.9914 ± 0.0001,0.9434 ± 0.0014,0.9979 ± 0.0005,0.9698 ± 0.0005,53.169
19,UNSW-NB15,SVM,"{""classifier__C"": 1.0, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": tr...",0.9266 ± 0.0017,0.9084 ± 0.0026,0.9377 ± 0.0009,0.8305 ± 0.0053,0.8809 ± 0.0029,60.811
25,UNSW-NB15,MLP,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.0001, ""classifier__batch_size"": ""auto"", ""classifier__beta_...",0.9794 ± 0.0005,0.9902 ± 0.0005,0.9398 ± 0.0011,0.9964 ± 0.0009,0.9673 ± 0.0008,352.869
2,IoT-23,DT,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_d...",0.9977 ± 0.0003,0.9965 ± 0.0005,0.9995 ± 0.0002,0.9932 ± 0.0010,0.9964 ± 0.0005,10.008
8,IoT-23,RF,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criteri...",0.9979 ± 0.0003,0.9967 ± 0.0005,0.9998 ± 0.0002,0.9934 ± 0.0010,0.9966 ± 0.0005,435.616
14,IoT-23,XGB,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_...",0.9978 ± 0.0003,0.9966 ± 0.0004,0.9997 ± 0.0001,0.9934 ± 0.0009,0.9965 ± 0.0005,46.141
20,IoT-23,SVM,"{""classifier__C"": 1.0, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": tr...",0.9958 ± 0.0004,0.9949 ± 0.0006,0.9956 ± 0.0004,0.9909 ± 0.0011,0.9932 ± 0.0006,45.395
26,IoT-23,MLP,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 1.9726066891840947e-05, ""classifier__batch_size"": ""auto"", ""c...",0.9975 ± 0.0004,0.9961 ± 0.0006,0.9996 ± 0.0003,0.9923 ± 0.0011,0.9960 ± 0.0007,134.154
3,CICIDS2017 + UNSW-NB15,DT,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_d...",0.9834 ± 0.0007,0.9883 ± 0.0004,0.9604 ± 0.0020,0.9869 ± 0.0005,0.9735 ± 0.0011,43.113
9,CICIDS2017 + UNSW-NB15,RF,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": ""balanced"", ""classifier__c...",0.9861 ± 0.0007,0.9927 ± 0.0005,0.9608 ± 0.0018,0.9955 ± 0.0006,0.9778 ± 0.0011,2046.982
15,CICIDS2017 + UNSW-NB15,XGB,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_...",0.9857 ± 0.0007,0.9918 ± 0.0005,0.9611 ± 0.0015,0.9937 ± 0.0008,0.9771 ± 0.0010,112.076
21,CICIDS2017 + UNSW-NB15,SVM,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier...",0.8469 ± 0.0066,0.8851 ± 0.0056,0.6787 ± 0.0134,0.8736 ± 0.0100,0.7638 ± 0.0096,159.923
27,CICIDS2017 + UNSW-NB15,MLP,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.001026603003516424, ""classifier__batch_size"": ""auto"", ""cla...",0.9802 ± 0.0016,0.9881 ± 0.0012,0.9482 ± 0.0064,0.9897 ± 0.0033,0.9685 ± 0.0024,815.302
4,CICIDS2017 + IoT-23,DT,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_d...",0.9937 ± 0.0002,0.9939 ± 0.0002,0.9892 ± 0.0006,0.9906 ± 0.0005,0.9899 ± 0.0003,32.956
10,CICIDS2017 + IoT-23,RF,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criteri...",0.9946 ± 0.0003,0.9953 ± 0.0003,0.9896 ± 0.0009,0.9931 ± 0.0004,0.9914 ± 0.0005,1616.656
16,CICIDS2017 + IoT-23,XGB,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_...",0.9943 ± 0.0004,0.9949 ± 0.0005,0.9892 ± 0.0007,0.9926 ± 0.0008,0.9909 ± 0.0007,103.537
22,CICIDS2017 + IoT-23,SVM,"{""classifier__C"": 1.0, ""classifier__class_weight"": null, ""classifier__dual"": ""auto"", ""classifier__fit_intercept"": tr...",0.9485 ± 0.0013,0.9594 ± 0.0009,0.8903 ± 0.0029,0.9480 ± 0.0011,0.9182 ± 0.0020,153.347
28,CICIDS2017 + IoT-23,MLP,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.001026603003516424, ""classifier__batch_size"": ""auto"", ""cla...",0.9926 ± 0.0005,0.9931 ± 0.0004,0.9867 ± 0.0017,0.9896 ± 0.0010,0.9882 ± 0.0007,588.862
5,UNSW-NB15 + IoT-23,DT,"{""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criterion"": ""gini"", ""classifier__max_d...",0.9884 ± 0.0004,0.9924 ± 0.0003,0.9711 ± 0.0009,0.9921 ± 0.0006,0.9815 ± 0.0006,29.797
11,UNSW-NB15 + IoT-23,RF,"{""classifier__bootstrap"": true, ""classifier__ccp_alpha"": 0.0, ""classifier__class_weight"": null, ""classifier__criteri...",0.9892 ± 0.0002,0.9940 ± 0.0002,0.9703 ± 0.0009,0.9956 ± 0.0005,0.9827 ± 0.0003,1487.054
17,UNSW-NB15 + IoT-23,XGB,"{""classifier__base_score"": null, ""classifier__booster"": null, ""classifier__callbacks"": null, ""classifier__colsample_...",0.9892 ± 0.0002,0.9939 ± 0.0002,0.9704 ± 0.0008,0.9953 ± 0.0004,0.9827 ± 0.0003,101.167
23,UNSW-NB15 + IoT-23,SVM,"{""classifier__C"": 46.00306804490304, ""classifier__class_weight"": ""balanced"", ""classifier__dual"": ""auto"", ""classifier...",0.9547 ± 0.0048,0.9542 ± 0.0025,0.9289 ± 0.0139,0.9262 ± 0.0017,0.9275 ± 0.0076,109.003
29,UNSW-NB15 + IoT-23,MLP,"{""classifier__activation"": ""relu"", ""classifier__alpha"": 0.001026603003516424, ""classifier__batch_size"": ""auto"", ""cla...",0.9868 ± 0.0006,0.9908 ± 0.0009,0.9687 ± 0.0014,0.9895 ± 0.0019,0.9790 ± 0.0010,794.897

Avaliação - Intra-dataset

,Conjunto de treinamento,Conjunto de teste,Cenário de avaliação,Modelo,Acurácia,Acurácia balanceada,Precisão ATTACK,Recall ATTACK,F1 ATTACK,Precisão BENIGN,Recall BENIGN,F1 BENIGN,F1 macro
0,CICIDS2017,CICIDS2017,Intra-dataset,DT,0.9941,0.9921,0.9815,0.9889,0.9852,0.9972,0.9953,0.9963,0.9907
3,CICIDS2017,CICIDS2017,Intra-dataset,RF,0.9951,0.9958,0.9791,0.9970,0.9880,0.9992,0.9947,0.9970,0.9925
4,CICIDS2017,CICIDS2017,Intra-dataset,XGB,0.9946,0.9942,0.9795,0.9936,0.9865,0.9984,0.9948,0.9966,0.9916
1,CICIDS2017,CICIDS2017,Intra-dataset,SVM,0.9315,0.9428,0.7597,0.9617,0.8489,0.9897,0.9240,0.9557,0.9023
2,CICIDS2017,CICIDS2017,Intra-dataset,MLP,0.9939,0.9937,0.9766,0.9934,0.9849,0.9983,0.9940,0.9962,0.9905
50,UNSW-NB15,UNSW-NB15,Intra-dataset,DT,0.9865,0.9897,0.9407,0.9951,0.9672,0.9988,0.9843,0.9915,0.9793
53,UNSW-NB15,UNSW-NB15,Intra-dataset,RF,0.9870,0.9908,0.9413,0.9971,0.9684,0.9993,0.9844,0.9918,0.9801
54,UNSW-NB15,UNSW-NB15,Intra-dataset,XGB,0.9872,0.9912,0.9414,0.9980,0.9688,0.9995,0.9845,0.9919,0.9804
51,UNSW-NB15,UNSW-NB15,Intra-dataset,SVM,0.9542,0.9068,0.9355,0.8279,0.8784,0.9582,0.9857,0.9718,0.9251
52,UNSW-NB15,UNSW-NB15,Intra-dataset,MLP,0.9862,0.9902,0.9380,0.9968,0.9665,0.9992,0.9835,0.9913,0.9789
30,IoT-23,IoT-23,Intra-dataset,DT,0.9988,0.9972,0.9997,0.9944,0.9970,0.9986,0.9999,0.9993,0.9982
33,IoT-23,IoT-23,Intra-dataset,RF,0.9988,0.9972,0.9996,0.9946,0.9971,0.9986,0.9999,0.9993,0.9982
34,IoT-23,IoT-23,Intra-dataset,XGB,0.9988,0.9972,0.9997,0.9945,0.9971,0.9986,0.9999,0.9993,0.9982
31,IoT-23,IoT-23,Intra-dataset,SVM,0.9973,0.9951,0.9949,0.9914,0.9931,0.9978,0.9987,0.9983,0.9957
32,IoT-23,IoT-23,Intra-dataset,MLP,0.9981,0.9954,0.9999,0.9909,0.9953,0.9977,1.0000,0.9988,0.9971

Avaliação - Cross-dataset

,Conjunto de treinamento,Conjunto de teste,Cenário de avaliação,Modelo,Acurácia,Acurácia balanceada,Precisão ATTACK,Recall ATTACK,F1 ATTACK,Precisão BENIGN,Recall BENIGN,F1 BENIGN,F1 macro
10,CICIDS2017,UNSW-NB15,Cross-dataset,DT,0.7772,0.4869,0.0244,0.0029,0.0052,0.7957,0.9708,0.8746,0.4399
13,CICIDS2017,UNSW-NB15,Cross-dataset,RF,0.7999,0.5000,0.0000,0.0000,0.0000,0.8000,0.9999,0.8888,0.4444
14,CICIDS2017,UNSW-NB15,Cross-dataset,XGB,0.7998,0.4999,0.0000,0.0000,0.0000,0.8000,0.9997,0.8888,0.4444
11,CICIDS2017,UNSW-NB15,Cross-dataset,SVM,0.7951,0.4975,0.0601,0.0017,0.0033,0.7992,0.9934,0.8858,0.4445
12,CICIDS2017,UNSW-NB15,Cross-dataset,MLP,0.7979,0.4991,0.0814,0.0010,0.0021,0.7997,0.9971,0.8875,0.4448
5,CICIDS2017,IoT-23,Cross-dataset,DT,0.8049,0.5231,0.6471,0.0535,0.0988,0.8075,0.9927,0.8906,0.4947
8,CICIDS2017,IoT-23,Cross-dataset,RF,0.0971,0.0633,0.0020,0.0070,0.0031,0.3251,0.1196,0.1748,0.0890
9,CICIDS2017,IoT-23,Cross-dataset,XGB,0.7898,0.4953,0.0738,0.0044,0.0083,0.7985,0.9862,0.8824,0.4454
6,CICIDS2017,IoT-23,Cross-dataset,SVM,0.2862,0.5525,0.2184,0.9961,0.3583,0.9912,0.1088,0.1960,0.2771
7,CICIDS2017,IoT-23,Cross-dataset,MLP,0.2507,0.4605,0.1855,0.8102,0.3019,0.7001,0.1108,0.1913,0.2466
40,UNSW-NB15,CICIDS2017,Cross-dataset,DT,0.3397,0.2816,0.0692,0.1847,0.1006,0.6499,0.3784,0.4783,0.2895
43,UNSW-NB15,CICIDS2017,Cross-dataset,RF,0.3618,0.3222,0.0948,0.2562,0.1383,0.6761,0.3882,0.4932,0.3158
44,UNSW-NB15,CICIDS2017,Cross-dataset,XGB,0.3310,0.2686,0.0615,0.1644,0.0895,0.6408,0.3727,0.4713,0.2804
41,UNSW-NB15,CICIDS2017,Cross-dataset,SVM,0.8426,0.7075,0.6417,0.4822,0.5507,0.8781,0.9327,0.9046,0.7276
42,UNSW-NB15,CICIDS2017,Cross-dataset,MLP,0.7688,0.6582,0.4294,0.4737,0.4505,0.8649,0.8426,0.8536,0.6521
45,UNSW-NB15,IoT-23,Cross-dataset,DT,0.0163,0.0307,0.0136,0.0547,0.0218,0.0278,0.0068,0.0109,0.0163
48,UNSW-NB15,IoT-23,Cross-dataset,RF,0.0906,0.0771,0.0149,0.0546,0.0234,0.2963,0.0995,0.1490,0.0862
49,UNSW-NB15,IoT-23,Cross-dataset,XGB,0.0813,0.0548,0.0029,0.0106,0.0046,0.2857,0.0990,0.1470,0.0758
46,UNSW-NB15,IoT-23,Cross-dataset,SVM,0.7870,0.4946,0.0908,0.0072,0.0133,0.7982,0.9820,0.8806,0.4470
47,UNSW-NB15,IoT-23,Cross-dataset,MLP,0.7199,0.4525,0.0164,0.0068,0.0096,0.7834,0.8981,0.8369,0.4232
25,IoT-23,CICIDS2017,Cross-dataset,DT,0.7585,0.4799,0.0651,0.0155,0.0250,0.7932,0.9443,0.8622,0.4436
28,IoT-23,CICIDS2017,Cross-dataset,RF,0.8100,0.5751,0.5788,0.1835,0.2787,0.8256,0.9666,0.8906,0.5846
29,IoT-23,CICIDS2017,Cross-dataset,XGB,0.8315,0.6687,0.6234,0.3973,0.4853,0.8619,0.9400,0.8992,0.6923
26,IoT-23,CICIDS2017,Cross-dataset,SVM,0.7593,0.4961,0.1805,0.0574,0.0871,0.7987,0.9348,0.8614,0.4743
27,IoT-23,CICIDS2017,Cross-dataset,MLP,0.7869,0.4918,0.0000,0.0000,0.0000,0.7973,0.9836,0.8807,0.4404
35,IoT-23,UNSW-NB15,Cross-dataset,DT,0.3685,0.3555,0.1182,0.3338,0.1745,0.6937,0.3772,0.4887,0.3316
38,IoT-23,UNSW-NB15,Cross-dataset,RF,0.7600,0.5058,0.2254,0.0822,0.1205,0.8020,0.9294,0.8610,0.4907
39,IoT-23,UNSW-NB15,Cross-dataset,XGB,0.6556,0.4951,0.1933,0.2275,0.2090,0.7979,0.7626,0.7799,0.4944
36,IoT-23,UNSW-NB15,Cross-dataset,SVM,0.7849,0.5103,0.2907,0.0526,0.0891,0.8034,0.9679,0.8780,0.4836
37,IoT-23,UNSW-NB15,Cross-dataset,MLP,0.7996,0.5022,0.4371,0.0065,0.0129,0.8007,0.9979,0.8885,0.4507

Avaliação - Combinado

,Conjunto de treinamento,Conjunto de teste,Cenário de avaliação,Modelo,Acurácia,Acurácia balanceada,Precisão ATTACK,Recall ATTACK,F1 ATTACK,Precisão BENIGN,Recall BENIGN,F1 BENIGN,F1 macro
20,CICIDS2017 + UNSW-NB15,IoT-23,Combinado,DT,0.0986,0.0677,0.0046,0.0162,0.0071,0.3265,0.1192,0.1746,0.0909
23,CICIDS2017 + UNSW-NB15,IoT-23,Combinado,RF,0.0969,0.0641,0.0027,0.0095,0.0042,0.3242,0.1188,0.1739,0.0890
24,CICIDS2017 + UNSW-NB15,IoT-23,Combinado,XGB,0.0268,0.0197,0.0020,0.0079,0.0032,0.1130,0.0316,0.0494,0.0263
21,CICIDS2017 + UNSW-NB15,IoT-23,Combinado,SVM,0.1266,0.1526,0.0521,0.1960,0.0824,0.3522,0.1093,0.1668,0.1246
22,CICIDS2017 + UNSW-NB15,IoT-23,Combinado,MLP,0.0114,0.0101,0.0020,0.0080,0.0032,0.0470,0.0122,0.0194,0.0113
15,CICIDS2017 + IoT-23,UNSW-NB15,Combinado,DT,0.8085,0.5310,0.7231,0.0686,0.1253,0.8101,0.9934,0.8925,0.5089
18,CICIDS2017 + IoT-23,UNSW-NB15,Combinado,RF,0.8052,0.5152,0.8479,0.0318,0.0612,0.8049,0.9986,0.8913,0.4763
19,CICIDS2017 + IoT-23,UNSW-NB15,Combinado,XGB,0.7998,0.5001,0.2571,0.0004,0.0009,0.8000,0.9997,0.8888,0.4448
16,CICIDS2017 + IoT-23,UNSW-NB15,Combinado,SVM,0.7799,0.4929,0.1123,0.0146,0.0258,0.7977,0.9712,0.8759,0.4509
17,CICIDS2017 + IoT-23,UNSW-NB15,Combinado,MLP,0.8061,0.5199,0.7750,0.0430,0.0815,0.8065,0.9969,0.8916,0.4865
55,UNSW-NB15 + IoT-23,CICIDS2017,Combinado,DT,0.7081,0.5108,0.2209,0.1819,0.1995,0.8041,0.8396,0.8215,0.5105
58,UNSW-NB15 + IoT-23,CICIDS2017,Combinado,RF,0.7143,0.4891,0.1734,0.1138,0.1374,0.7960,0.8644,0.8288,0.4831
59,UNSW-NB15 + IoT-23,CICIDS2017,Combinado,XGB,0.7134,0.4669,0.1027,0.0559,0.0724,0.7881,0.8778,0.8305,0.4515
56,UNSW-NB15 + IoT-23,CICIDS2017,Combinado,SVM,0.5039,0.6822,0.2848,0.9794,0.4412,0.9868,0.3850,0.5539,0.4976
57,UNSW-NB15 + IoT-23,CICIDS2017,Combinado,MLP,0.7907,0.7032,0.4800,0.5574,0.5158,0.8847,0.8490,0.8665,0.6912

Tabela consolidada para o TCC

,Conjunto de treinamento,Conjunto de teste,Modelo,F1 macro,Acurácia balanceada,Precisão BENIGN,Recall BENIGN,Precisão ATTACK,Recall ATTACK,F1 macro CV (média),F1 macro CV (desvio-padrão),Acurácia balanceada CV (média),Acurácia balanceada CV (desvio-padrão)
0,CICIDS2017,CICIDS2017,DT,0.9907,0.9921,0.9972,0.9953,0.9815,0.9889,0.9904,0.0004,0.9915,0.0007
1,CICIDS2017,CICIDS2017,RF,0.9925,0.9958,0.9992,0.9947,0.9791,0.9970,0.9925,0.0006,0.9957,0.0004
2,CICIDS2017,CICIDS2017,XGB,0.9916,0.9942,0.9984,0.9948,0.9795,0.9936,0.9918,0.0006,0.9941,0.0008
3,CICIDS2017,CICIDS2017,SVM,0.9023,0.9428,0.9897,0.9240,0.7597,0.9617,0.9029,0.0018,0.9435,0.0017
4,CICIDS2017,CICIDS2017,MLP,0.9905,0.9937,0.9983,0.9940,0.9766,0.9934,0.9908,0.0008,0.9938,0.0005
5,CICIDS2017,UNSW-NB15,DT,0.4399,0.4869,0.7957,0.9708,0.0244,0.0029,0.9904,0.0004,0.9915,0.0007
6,CICIDS2017,UNSW-NB15,RF,0.4444,0.5000,0.8000,0.9999,0.0000,0.0000,0.9925,0.0006,0.9957,0.0004
7,CICIDS2017,UNSW-NB15,XGB,0.4444,0.4999,0.8000,0.9997,0.0000,0.0000,0.9918,0.0006,0.9941,0.0008
8,CICIDS2017,UNSW-NB15,SVM,0.4445,0.4975,0.7992,0.9934,0.0601,0.0017,0.9029,0.0018,0.9435,0.0017
9,CICIDS2017,UNSW-NB15,MLP,0.4448,0.4991,0.7997,0.9971,0.0814,0.0010,0.9908,0.0008,0.9938,0.0005
10,CICIDS2017,IoT-23,DT,0.4947,0.5231,0.8075,0.9927,0.6471,0.0535,0.9904,0.0004,0.9915,0.0007
11,CICIDS2017,IoT-23,RF,0.0890,0.0633,0.3251,0.1196,0.0020,0.0070,0.9925,0.0006,0.9957,0.0004
12,CICIDS2017,IoT-23,XGB,0.4454,0.4953,0.7985,0.9862,0.0738,0.0044,0.9918,0.0006,0.9941,0.0008
13,CICIDS2017,IoT-23,SVM,0.2771,0.5525,0.9912,0.1088,0.2184,0.9961,0.9029,0.0018,0.9435,0.0017
14,CICIDS2017,IoT-23,MLP,0.2466,0.4605,0.7001,0.1108,0.1855,0.8102,0.9908,0.0008,0.9938,0.0005
15,UNSW-NB15,CICIDS2017,DT,0.2895,0.2816,0.6499,0.3784,0.0692,0.1847,0.9799,0.0006,0.9898,0.0005
16,UNSW-NB15,CICIDS2017,RF,0.3158,0.3222,0.6761,0.3882,0.0948,0.2562,0.9809,0.0004,0.9911,0.0002
17,UNSW-NB15,CICIDS2017,XGB,0.2804,0.2686,0.6408,0.3727,0.0615,0.1644,0.9810,0.0003,0.9914,0.0001
18,UNSW-NB15,CICIDS2017,SVM,0.7276,0.7075,0.8781,0.9327,0.6417,0.4822,0.9266,0.0017,0.9084,0.0026
19,UNSW-NB15,CICIDS2017,MLP,0.6521,0.6582,0.8649,0.8426,0.4294,0.4737,0.9794,0.0005,0.9902,0.0005
20,UNSW-NB15,UNSW-NB15,DT,0.9793,0.9897,0.9988,0.9843,0.9407,0.9951,0.9799,0.0006,0.9898,0.0005
21,UNSW-NB15,UNSW-NB15,RF,0.9801,0.9908,0.9993,0.9844,0.9413,0.9971,0.9809,0.0004,0.9911,0.0002
22,UNSW-NB15,UNSW-NB15,XGB,0.9804,0.9912,0.9995,0.9845,0.9414,0.9980,0.9810,0.0003,0.9914,0.0001
23,UNSW-NB15,UNSW-NB15,SVM,0.9251,0.9068,0.9582,0.9857,0.9355,0.8279,0.9266,0.0017,0.9084,0.0026
24,UNSW-NB15,UNSW-NB15,MLP,0.9789,0.9902,0.9992,0.9835,0.9380,0.9968,0.9794,0.0005,0.9902,0.0005
25,UNSW-NB15,IoT-23,DT,0.0163,0.0307,0.0278,0.0068,0.0136,0.0547,0.9799,0.0006,0.9898,0.0005
26,UNSW-NB15,IoT-23,RF,0.0862,0.0771,0.2963,0.0995,0.0149,0.0546,0.9809,0.0004,0.9911,0.0002
27,UNSW-NB15,IoT-23,XGB,0.0758,0.0548,0.2857,0.0990,0.0029,0.0106,0.9810,0.0003,0.9914,0.0001
28,UNSW-NB15,IoT-23,SVM,0.4470,0.4946,0.7982,0.9820,0.0908,0.0072,0.9266,0.0017,0.9084,0.0026
29,UNSW-NB15,IoT-23,MLP,0.4232,0.4525,0.7834,0.8981,0.0164,0.0068,0.9794,0.0005,0.9902,0.0005
30,IoT-23,CICIDS2017,DT,0.4436,0.4799,0.7932,0.9443,0.0651,0.0155,0.9977,0.0003,0.9965,0.0005
31,IoT-23,CICIDS2017,RF,0.5846,0.5751,0.8256,0.9666,0.5788,0.1835,0.9979,0.0003,0.9967,0.0005
32,IoT-23,CICIDS2017,XGB,0.6923,0.6687,0.8619,0.9400,0.6234,0.3973,0.9978,0.0003,0.9966,0.0004
33,IoT-23,CICIDS2017,SVM,0.4743,0.4961,0.7987,0.9348,0.1805,0.0574,0.9958,0.0004,0.9949,0.0006
34,IoT-23,CICIDS2017,MLP,0.4404,0.4918,0.7973,0.9836,0.0000,0.0000,0.9975,0.0004,0.9961,0.0006
35,IoT-23,UNSW-NB15,DT,0.3316,0.3555,0.6937,0.3772,0.1182,0.3338,0.9977,0.0003,0.9965,0.0005
36,IoT-23,UNSW-NB15,RF,0.4907,0.5058,0.8020,0.9294,0.2254,0.0822,0.9979,0.0003,0.9967,0.0005
37,IoT-23,UNSW-NB15,XGB,0.4944,0.4951,0.7979,0.7626,0.1933,0.2275,0.9978,0.0003,0.9966,0.0004
38,IoT-23,UNSW-NB15,SVM,0.4836,0.5103,0.8034,0.9679,0.2907,0.0526,0.9958,0.0004,0.9949,0.0006
39,IoT-23,UNSW-NB15,MLP,0.4507,0.5022,0.8007,0.9979,0.4371,0.0065,0.9975,0.0004,0.9961,0.0006
40,IoT-23,IoT-23,DT,0.9982,0.9972,0.9986,0.9999,0.9997,0.9944,0.9977,0.0003,0.9965,0.0005
41,IoT-23,IoT-23,RF,0.9982,0.9972,0.9986,0.9999,0.9996,0.9946,0.9979,0.0003,0.9967,0.0005
42,IoT-23,IoT-23,XGB,0.9982,0.9972,0.9986,0.9999,0.9997,0.9945,0.9978,0.0003,0.9966,0.0004
43,IoT-23,IoT-23,SVM,0.9957,0.9951,0.9978,0.9987,0.9949,0.9914,0.9958,0.0004,0.9949,0.0006
44,IoT-23,IoT-23,MLP,0.9971,0.9954,0.9977,1.0000,0.9999,0.9909,0.9975,0.0004,0.9961,0.0006
45,CICIDS2017 + UNSW-NB15,IoT-23,DT,0.0909,0.0677,0.3265,0.1192,0.0046,0.0162,0.9834,0.0007,0.9883,0.0004
46,CICIDS2017 + UNSW-NB15,IoT-23,RF,0.0890,0.0641,0.3242,0.1188,0.0027,0.0095,0.9861,0.0007,0.9927,0.0005
47,CICIDS2017 + UNSW-NB15,IoT-23,XGB,0.0263,0.0197,0.1130,0.0316,0.0020,0.0079,0.9857,0.0007,0.9918,0.0005
48,CICIDS2017 + UNSW-NB15,IoT-23,SVM,0.1246,0.1526,0.3522,0.1093,0.0521,0.1960,0.8469,0.0066,0.8851,0.0056
49,CICIDS2017 + UNSW-NB15,IoT-23,MLP,0.0113,0.0101,0.0470,0.0122,0.0020,0.0080,0.9802,0.0016,0.9881,0.0012
50,CICIDS2017 + IoT-23,UNSW-NB15,DT,0.5089,0.5310,0.8101,0.9934,0.7231,0.0686,0.9937,0.0002,0.9939,0.0002
51,CICIDS2017 + IoT-23,UNSW-NB15,RF,0.4763,0.5152,0.8049,0.9986,0.8479,0.0318,0.9946,0.0003,0.9953,0.0003
52,CICIDS2017 + IoT-23,UNSW-NB15,XGB,0.4448,0.5001,0.8000,0.9997,0.2571,0.0004,0.9943,0.0004,0.9949,0.0005
53,CICIDS2017 + IoT-23,UNSW-NB15,SVM,0.4509,0.4929,0.7977,0.9712,0.1123,0.0146,0.9485,0.0013,0.9594,0.0009
54,CICIDS2017 + IoT-23,UNSW-NB15,MLP,0.4865,0.5199,0.8065,0.9969,0.7750,0.0430,0.9926,0.0005,0.9931,0.0004
55,UNSW-NB15 + IoT-23,CICIDS2017,DT,0.5105,0.5108,0.8041,0.8396,0.2209,0.1819,0.9884,0.0004,0.9924,0.0003
56,UNSW-NB15 + IoT-23,CICIDS2017,RF,0.4831,0.4891,0.7960,0.8644,0.1734,0.1138,0.9892,0.0002,0.9940,0.0002
57,UNSW-NB15 + IoT-23,CICIDS2017,XGB,0.4515,0.4669,0.7881,0.8778,0.1027,0.0559,0.9892,0.0002,0.9939,0.0002
58,UNSW-NB15 + IoT-23,CICIDS2017,SVM,0.4976,0.6822,0.9868,0.3850,0.2848,0.9794,0.9547,0.0048,0.9542,0.0025
59,UNSW-NB15 + IoT-23,CICIDS2017,MLP,0.6912,0.7032,0.8847,0.8490,0.4800,0.5574,0.9868,0.0006,0.9908,0.0009

In [4]:
# desempenho médio por algoritmo e cenário de avaliação
def plot_metric_by_scenario(metric, metric_label, filename):
    plot_data = (
        evaluation.groupby(
            ["scenario_type", "model"],
            as_index=False,
        )
        .agg(
            metric_mean=(metric, "mean"),
            metric_min=(metric, "min"),
            metric_max=(metric, "max"),
            experiments=(metric, "size"),
        )
    )
    plot_data["distance_to_min"] = (
        plot_data["metric_mean"] - plot_data["metric_min"]
    )
    plot_data["distance_to_max"] = (
        plot_data["metric_max"] - plot_data["metric_mean"]
    )
    plot_data["model_label"] = plot_data["model"].map(MODEL_LABELS)
    plot_data["scenario_label"] = (
        plot_data["scenario_type"].map(SCENARIO_LABELS)
    )

    figure = px.bar(
        plot_data,
        x="model_label",
        y="metric_mean",
        facet_col="scenario_label",
        error_y="distance_to_max",
        error_y_minus="distance_to_min",
        category_orders={
            "model_label": [
                MODEL_LABELS[model] for model in MODEL_ORDER
            ],
            "scenario_label": [
                SCENARIO_LABELS[scenario]
                for scenario in SCENARIO_ORDER
            ],
        },
        custom_data=["experiments", "metric_min", "metric_max"],
        labels={
            "model_label": "Algoritmo",
            "metric_mean": metric_label,
        },
        title=(
            f"{metric_label} por algoritmo e cenário de avaliação"
            "<br><sup>Barras: média entre pares treinamento-teste; "
            "intervalos: mínimo-máximo observado</sup>"
        ),
    )
    figure.for_each_annotation(
        lambda annotation: annotation.update(
            text=annotation.text.split("=")[-1]
        )
    )
    figure.update_traces(
        marker_color="#4C78A8",
        hovertemplate=(
            "Algoritmo: %{x}<br>Média: %{y:.4f}<br>"
            "Mínimo: %{customdata[1]:.4f}<br>"
            "Máximo: %{customdata[2]:.4f}<br>"
            "Número de avaliações: %{customdata[0]}<extra></extra>"
        ),
        error_y=dict(color="#333333", thickness=1.5, width=5),
    )
    figure.update_yaxes(range=[0, 1.05], matches="y")
    figure.update_xaxes(tickangle=-25)
    finalize_figure(figure, filename, width=1500, height=520)


plot_metric_by_scenario(
    "f1_attack",
    "F1 da classe ATTACK",
    "f1_attack_by_scenario_type",
)
plot_metric_by_scenario(
    "f1_macro",
    "F1 macro",
    "f1_macro_by_scenario_type",
)
plot_metric_by_scenario(
    "balanced_accuracy",
    "Acurácia balanceada",
    "balanced_accuracy_by_scenario_type",
)
plot_metric_by_scenario(
    "precision_attack",
    "Precisão da classe ATTACK",
    "precision_attack_by_scenario_type",
)
plot_metric_by_scenario(
    "recall_attack",
    "Recall da classe ATTACK",
    "recall_attack_by_scenario_type",
)

generalization_pivot = (
    evaluation.groupby(
        ["training_source", "test_source"]
    )["f1_macro"]
    .mean()
    .unstack("test_source")
    .reindex(
        index=TRAINING_SOURCE_ORDER,
        columns=TEST_SOURCE_ORDER,
    )
    .rename(index=SOURCE_LABELS, columns=SOURCE_LABELS)
)
generalization_figure = px.imshow(
    generalization_pivot,
    text_auto=".3f",
    color_continuous_scale="YlGnBu",
    zmin=0,
    zmax=1,
    aspect="auto",
    labels={
        "x": "Conjunto de teste",
        "y": "Origem do treinamento",
        "color": "F1 macro (média)",
    },
    title=(
        "F1 macro médio por origem de treinamento e conjunto de teste"
        "<br><sup>Cada célula representa a média dos cinco algoritmos "
        "na respectiva combinação treinamento-teste</sup>"
    ),
)
finalize_figure(
    generalization_figure,
    "generalization_f1_macro",
    width=900,
    height=720,
)

(WindowsPath('C:/tcc/network-ids-ml-generalization/results/results_analysis/figures/svg/generalization_f1_macro.svg'),
 WindowsPath('C:/tcc/network-ids-ml-generalization/results/results_analysis/figures/png/generalization_f1_macro.png'))

In [5]:
# extremos observados por cenário de avaliação
def plot_metric_extremes(metric, metric_label, filename):
    best_rows = (
        evaluation.sort_values(
            ["scenario_type", metric, "f1_macro"],
            ascending=[True, False, False],
        )
        .groupby("scenario_type", as_index=False)
        .head(1)
        .assign(result="Máximo observado")
    )
    worst_rows = (
        evaluation.sort_values(
            ["scenario_type", metric, "f1_macro"],
            ascending=[True, True, True],
        )
        .groupby("scenario_type", as_index=False)
        .head(1)
        .assign(result="Mínimo observado")
    )
    extremes = pd.concat(
        [best_rows, worst_rows],
        ignore_index=True,
    )
    extremes["scenario_label"] = (
        extremes["scenario_type"].map(SCENARIO_LABELS)
    )
    extremes["model_label"] = extremes["model"].map(MODEL_LABELS)
    extremes["training_source_label"] = (
        extremes["training_source"].map(SOURCE_LABELS)
    )
    extremes["test_source_label"] = (
        extremes["test_source"].map(SOURCE_LABELS)
    )
    extremes["point_label"] = extremes.apply(
        lambda row: (
            f"{MODEL_ABBREVIATIONS[row['model']]} · "
            f"{row[metric]:.3f}"
        ),
        axis=1,
    )

    figure = go.Figure()
    for scenario_type in SCENARIO_ORDER:
        scenario_rows = extremes[
            extremes["scenario_type"].eq(scenario_type)
        ]
        figure.add_trace(go.Scatter(
            x=[
                scenario_rows[metric].min(),
                scenario_rows[metric].max(),
            ],
            y=[
                SCENARIO_LABELS[scenario_type],
                SCENARIO_LABELS[scenario_type],
            ],
            mode="lines",
            line=dict(color="#B0B0B0", width=3),
            hoverinfo="skip",
            showlegend=False,
        ))

    styles = {
        "Máximo observado": "#2E7D32",
        "Mínimo observado": "#C62828",
    }
    for result_label, color in styles.items():
        result_rows = extremes[
            extremes["result"].eq(result_label)
        ]
        custom_data = result_rows[
            [
                "model_label",
                "training_source_label",
                "test_source_label",
                "f1_attack",
                "balanced_accuracy",
                "f1_macro",
            ]
        ].to_numpy()
        figure.add_trace(go.Scatter(
            x=result_rows[metric],
            y=result_rows["scenario_label"],
            mode="markers+text",
            text=result_rows["point_label"],
            textposition=(
                "top center"
                if result_label == "Máximo observado"
                else "bottom center"
            ),
            name=result_label,
            marker=dict(color=color, size=15),
            cliponaxis=False,
            customdata=custom_data,
            hovertemplate=(
                "Cenário: %{y}<br>"
                f"Extremo: {result_label}<br>"
                "Algoritmo: %{customdata[0]}<br>"
                "Treinamento: %{customdata[1]}<br>"
                "Teste: %{customdata[2]}<br>"
                f"{metric_label}: %{{x:.4f}}<br>"
                "F1 ATTACK: %{customdata[3]:.4f}<br>"
                "Acurácia balanceada: %{customdata[4]:.4f}<br>"
                "F1 macro: %{customdata[5]:.4f}<extra></extra>"
            ),
        ))

    figure.update_xaxes(
        title_text=metric_label,
        range=[-0.05, 1.05],
    )
    figure.update_yaxes(
        title_text="Cenário de avaliação",
        categoryorder="array",
        categoryarray=[
            SCENARIO_LABELS[scenario]
            for scenario in reversed(SCENARIO_ORDER)
        ],
    )
    figure.update_layout(
        title=f"Amplitude observada de {metric_label.lower()} por cenário de avaliação"
    )
    finalize_figure(
        figure,
        filename,
        width=1250,
        height=600,
    )


plot_metric_extremes(
    "f1_attack",
    "F1 da classe ATTACK",
    "f1_attack_best_worst_by_scenario",
)
plot_metric_extremes(
    "balanced_accuracy",
    "Acurácia balanceada",
    "balanced_accuracy_best_worst_by_scenario",
)
plot_metric_extremes(
    "f1_macro",
    "F1 macro",
    "f1_macro_best_worst_by_scenario",
)

In [6]:
# comparação entre origens individuais e treinamento combinado
TARGET_TRAINING_SOURCES = {
    "cicids2017": ("unsw_nb15", "iot23", "unsw_nb15_iot23"),
    "unsw_nb15": ("cicids2017", "iot23", "cicids2017_iot23"),
    "iot23": ("cicids2017", "unsw_nb15", "cicids2017_unsw_nb15"),
}

combined_comparison_rows = []
for test_source, sources in TARGET_TRAINING_SOURCES.items():
    individual_source_1, individual_source_2, combined_source = sources

    for model in MODEL_ORDER:
        experiment_rows = evaluation[
            evaluation["test_source"].eq(test_source)
            & evaluation["model"].eq(model)
            & evaluation["training_source"].isin(sources)
        ].set_index("training_source")

        assert len(experiment_rows) == 3, (
            f"Esperados três resultados para {model} "
            f"e teste em {test_source}."
        )

        metric_values = {}
        for metric in ["f1_macro", "balanced_accuracy", "f1_attack"]:
            individual_value_1 = float(
                experiment_rows.loc[individual_source_1, metric]
            )
            individual_value_2 = float(
                experiment_rows.loc[individual_source_2, metric]
            )
            combined_value = float(
                experiment_rows.loc[combined_source, metric]
            )
            metric_values.update({
                f"individual_{metric}_1": individual_value_1,
                f"individual_{metric}_2": individual_value_2,
                f"combined_{metric}": combined_value,
                f"best_individual_{metric}": max(
                    individual_value_1,
                    individual_value_2,
                ),
                f"combined_vs_best_individual_{metric}_delta": (
                    combined_value
                    - max(individual_value_1, individual_value_2)
                ),
            })

        combined_comparison_rows.append({
            "test_source": test_source,
            "model": model,
            "individual_source_1": individual_source_1,
            "individual_source_2": individual_source_2,
            "combined_source": combined_source,
            **metric_values,
        })

combined_comparison = pd.DataFrame(combined_comparison_rows)
assert len(combined_comparison) == 15

combined_comparison_presentation = pd.DataFrame({
    "Conjunto de teste": combined_comparison["test_source"].map(SOURCE_LABELS),
    "Modelo": combined_comparison["model"].map(MODEL_ABBREVIATIONS),
    "Origem individual A": (
        combined_comparison["individual_source_1"].map(SOURCE_LABELS)
    ),
    "F1 macro - A": combined_comparison["individual_f1_macro_1"].round(4),
    "Acurácia balanceada - A": (
        combined_comparison["individual_balanced_accuracy_1"].round(4)
    ),
    "F1 ATTACK - A": combined_comparison["individual_f1_attack_1"].round(4),
    "Origem individual B": (
        combined_comparison["individual_source_2"].map(SOURCE_LABELS)
    ),
    "F1 macro - B": combined_comparison["individual_f1_macro_2"].round(4),
    "Acurácia balanceada - B": (
        combined_comparison["individual_balanced_accuracy_2"].round(4)
    ),
    "F1 ATTACK - B": combined_comparison["individual_f1_attack_2"].round(4),
    "Origens combinadas A + B": (
        combined_comparison["combined_source"].map(SOURCE_LABELS)
    ),
    "F1 macro - A + B": combined_comparison["combined_f1_macro"].round(4),
    "Acurácia balanceada - A + B": (
        combined_comparison["combined_balanced_accuracy"].round(4)
    ),
    "F1 ATTACK - A + B": combined_comparison["combined_f1_attack"].round(4),
    "Δ F1 macro: combinado - melhor individual": (
        combined_comparison[
            "combined_vs_best_individual_f1_macro_delta"
        ].round(4)
    ),
    "Δ acurácia balanceada: combinado - melhor individual": (
        combined_comparison[
            "combined_vs_best_individual_balanced_accuracy_delta"
        ].round(4)
    ),
    "Δ F1 ATTACK: combinado - melhor individual": (
        combined_comparison[
            "combined_vs_best_individual_f1_attack_delta"
        ].round(4)
    ),
})
save_table(
    combined_comparison_presentation,
    "combined_vs_individual_training_sources.csv",
)
display(combined_comparison_presentation)

combined_plot_data = combined_comparison.copy()
combined_plot_data["test_source_label"] = (
    combined_plot_data["test_source"].map(SOURCE_LABELS)
)
combined_plot_data["model_label"] = (
    combined_plot_data["model"].map(MODEL_LABELS)
)


def plot_combined_vs_best_individual(metric, metric_label, filename):
    delta_column = f"combined_vs_best_individual_{metric}_delta"
    plot_data = combined_plot_data.copy()
    plot_data["delta_label"] = plot_data[delta_column].map(
        lambda value: f"{value:+.3f}"
    )

    figure = px.bar(
        plot_data,
        x="model_label",
        y=delta_column,
        facet_col="test_source_label",
        text="delta_label",
        custom_data=["test_source_label"],
        category_orders={
            "model_label": [
                MODEL_LABELS[model] for model in MODEL_ORDER
            ],
            "test_source_label": [
                SOURCE_LABELS[source] for source in TEST_SOURCE_ORDER
            ],
        },
        labels={
            "model_label": "Algoritmo",
            delta_column: f"Δ {metric_label}",
        },
        title=(
            f"Efeito do treinamento combinado sobre {metric_label}"
            "<br><sup>Δ = resultado com duas origens - maior "
            "resultado com uma origem; teste no terceiro conjunto</sup>"
        ),
    )
    figure.for_each_annotation(
        lambda annotation: annotation.update(
            text=(
                "Conjunto de teste: "
                f"{annotation.text.split('=')[-1]}"
            )
        )
    )
    figure.update_traces(
        marker_color="#4C78A8",
        textposition="outside",
        cliponaxis=False,
        hovertemplate=(
            "Algoritmo: %{x}<br>"
            "Conjunto de teste: %{customdata[0]}<br>"
            f"Δ {metric_label}: %{{y:+.4f}}<extra></extra>"
        ),
    )
    figure.add_hline(y=0, line_width=1, line_color="#444444")
    delta_limit = max(
        float(plot_data[delta_column].abs().max()) * 1.25,
        0.01,
    )
    figure.update_yaxes(
        range=[-delta_limit, delta_limit],
        matches="y",
    )
    figure.update_xaxes(tickangle=-25)
    finalize_figure(figure, filename, width=1500, height=620)


plot_combined_vs_best_individual(
    "f1_macro",
    "F1 macro",
    "combined_vs_best_individual_f1_macro",
)
plot_combined_vs_best_individual(
    "balanced_accuracy",
    "acurácia balanceada",
    "combined_vs_best_individual_balanced_accuracy",
)
plot_combined_vs_best_individual(
    "f1_attack",
    "F1 da classe ATTACK",
    "combined_vs_best_individual_f1_attack",
)

absolute_comparison_rows = []
configuration_specs = [
    (
        "A (individual)",
        "individual_source_1",
        "individual_f1_macro_1",
        "individual_balanced_accuracy_1",
        "individual_f1_attack_1",
    ),
    (
        "B (individual)",
        "individual_source_2",
        "individual_f1_macro_2",
        "individual_balanced_accuracy_2",
        "individual_f1_attack_2",
    ),
    (
        "A + B (combinado)",
        "combined_source",
        "combined_f1_macro",
        "combined_balanced_accuracy",
        "combined_f1_attack",
    ),
]
for _, row in combined_comparison.iterrows():
    for (
        configuration,
        source_column,
        f1_macro_column,
        balanced_accuracy_column,
        f1_attack_column,
    ) in configuration_specs:
        absolute_comparison_rows.append({
            "test_source": row["test_source"],
            "model": row["model"],
            "training_configuration": configuration,
            "training_source": row[source_column],
            "f1_macro": row[f1_macro_column],
            "balanced_accuracy": row[balanced_accuracy_column],
            "f1_attack": row[f1_attack_column],
        })

absolute_comparison = pd.DataFrame(absolute_comparison_rows)
absolute_comparison["test_source_label"] = (
    absolute_comparison["test_source"].map(SOURCE_LABELS)
)
absolute_comparison["model_label"] = (
    absolute_comparison["model"].map(MODEL_LABELS)
)
absolute_comparison["training_source_label"] = (
    absolute_comparison["training_source"].map(SOURCE_LABELS)
)

facet_titles = {
    SOURCE_LABELS[test_source]: (
        f"Conjunto de teste: {SOURCE_LABELS[test_source]}"
        f"<br><sup>A: {SOURCE_LABELS[sources[0]]}; "
        f"B: {SOURCE_LABELS[sources[1]]}</sup>"
    )
    for test_source, sources in TARGET_TRAINING_SOURCES.items()
}
configuration_colors = {
    "A (individual)": "#4C78A8",
    "B (individual)": "#F58518",
    "A + B (combinado)": "#54A24B",
}


def plot_individual_and_combined(metric, metric_label, filename):
    figure = px.bar(
        absolute_comparison,
        x="model_label",
        y=metric,
        color="training_configuration",
        facet_col="test_source_label",
        barmode="group",
        custom_data=["training_source_label"],
        color_discrete_map=configuration_colors,
        category_orders={
            "model_label": [
                MODEL_LABELS[model] for model in MODEL_ORDER
            ],
            "training_configuration": [
                "A (individual)",
                "B (individual)",
                "A + B (combinado)",
            ],
            "test_source_label": [
                SOURCE_LABELS[source] for source in TEST_SOURCE_ORDER
            ],
        },
        labels={
            "model_label": "Algoritmo",
            metric: metric_label,
            "training_configuration": "Composição do treinamento",
        },
        title=(
            f"{metric_label} por composição do conjunto de treinamento"
            "<br><sup>As origens A e B são avaliadas separadamente "
            "e combinadas; o terceiro conjunto é usado para teste</sup>"
        ),
    )
    figure.for_each_annotation(
        lambda annotation: annotation.update(
            text=facet_titles[annotation.text.split("=")[-1]]
        )
    )
    figure.update_traces(
        hovertemplate=(
            "Algoritmo: %{x}<br>"
            "Composição do treinamento: %{fullData.name}<br>"
            "Origem(ns) do treinamento: %{customdata[0]}<br>"
            f"{metric_label}: %{{y:.4f}}<extra></extra>"
        )
    )
    figure.update_yaxes(range=[0, 1.05], matches="y")
    figure.update_xaxes(tickangle=-25)
    finalize_figure(figure, filename, width=1600, height=650)


plot_individual_and_combined(
    "f1_macro",
    "F1 macro",
    "individual_and_combined_f1_macro",
)
plot_individual_and_combined(
    "balanced_accuracy",
    "Acurácia balanceada",
    "individual_and_combined_balanced_accuracy",
)
plot_individual_and_combined(
    "f1_attack",
    "F1 da classe ATTACK",
    "individual_and_combined_f1_attack",
)

,Conjunto de teste,Modelo,Origem individual A,F1 macro - A,Acurácia balanceada - A,F1 ATTACK - A,Origem individual B,F1 macro - B,Acurácia balanceada - B,F1 ATTACK - B,Origens combinadas A + B,F1 macro - A + B,Acurácia balanceada - A + B,F1 ATTACK - A + B,Δ F1 macro: combinado - melhor individual,Δ acurácia balanceada: combinado - melhor individual,Δ F1 ATTACK: combinado - melhor individual
0,CICIDS2017,DT,UNSW-NB15,0.2895,0.2816,0.1006,IoT-23,0.4436,0.4799,0.0250,UNSW-NB15 + IoT-23,0.5105,0.5108,0.1995,0.0669,0.0308,0.0988
1,CICIDS2017,RF,UNSW-NB15,0.3158,0.3222,0.1383,IoT-23,0.5846,0.5751,0.2787,UNSW-NB15 + IoT-23,0.4831,0.4891,0.1374,-0.1015,-0.0860,-0.1413
2,CICIDS2017,XGB,UNSW-NB15,0.2804,0.2686,0.0895,IoT-23,0.6923,0.6687,0.4853,UNSW-NB15 + IoT-23,0.4515,0.4669,0.0724,-0.2408,-0.2018,-0.4129
3,CICIDS2017,SVM,UNSW-NB15,0.7276,0.7075,0.5507,IoT-23,0.4743,0.4961,0.0871,UNSW-NB15 + IoT-23,0.4976,0.6822,0.4412,-0.2300,-0.0253,-0.1094
4,CICIDS2017,MLP,UNSW-NB15,0.6521,0.6582,0.4505,IoT-23,0.4404,0.4918,0.0000,UNSW-NB15 + IoT-23,0.6912,0.7032,0.5158,0.0391,0.0451,0.0654
5,UNSW-NB15,DT,CICIDS2017,0.4399,0.4869,0.0052,IoT-23,0.3316,0.3555,0.1745,CICIDS2017 + IoT-23,0.5089,0.5310,0.1253,0.0690,0.0441,-0.0493
6,UNSW-NB15,RF,CICIDS2017,0.4444,0.5000,0.0000,IoT-23,0.4907,0.5058,0.1205,CICIDS2017 + IoT-23,0.4763,0.5152,0.0612,-0.0145,0.0094,-0.0592
7,UNSW-NB15,XGB,CICIDS2017,0.4444,0.4999,0.0000,IoT-23,0.4944,0.4951,0.2090,CICIDS2017 + IoT-23,0.4448,0.5001,0.0009,-0.0496,0.0002,-0.2081
8,UNSW-NB15,SVM,CICIDS2017,0.4445,0.4975,0.0033,IoT-23,0.4836,0.5103,0.0891,CICIDS2017 + IoT-23,0.4509,0.4929,0.0258,-0.0327,-0.0174,-0.0633
9,UNSW-NB15,MLP,CICIDS2017,0.4448,0.4991,0.0021,IoT-23,0.4507,0.5022,0.0129,CICIDS2017 + IoT-23,0.4865,0.5199,0.0815,0.0359,0.0177,0.0686
10,IoT-23,DT,CICIDS2017,0.4947,0.5231,0.0988,UNSW-NB15,0.0163,0.0307,0.0218,CICIDS2017 + UNSW-NB15,0.0909,0.0677,0.0071,-0.4038,-0.4554,-0.0917
11,IoT-23,RF,CICIDS2017,0.0890,0.0633,0.0031,UNSW-NB15,0.0862,0.0771,0.0234,CICIDS2017 + UNSW-NB15,0.0890,0.0641,0.0042,0.0001,-0.0129,-0.0193
12,IoT-23,XGB,CICIDS2017,0.4454,0.4953,0.0083,UNSW-NB15,0.0758,0.0548,0.0046,CICIDS2017 + UNSW-NB15,0.0263,0.0197,0.0032,-0.4191,-0.4756,-0.0051
13,IoT-23,SVM,CICIDS2017,0.2771,0.5525,0.3583,UNSW-NB15,0.4470,0.4946,0.0133,CICIDS2017 + UNSW-NB15,0.1246,0.1526,0.0824,-0.3224,-0.3998,-0.2759
14,IoT-23,MLP,CICIDS2017,0.2466,0.4605,0.3019,UNSW-NB15,0.4232,0.4525,0.0096,CICIDS2017 + UNSW-NB15,0.0113,0.0101,0.0032,-0.4119,-0.4504,-0.2987

In [7]:
# distribuição das 60 avaliações e resumo dos artefatos
plot_data = evaluation.copy()
plot_data["model_label"] = plot_data["model"].map(MODEL_LABELS)
plot_data["scenario_label"] = (
    plot_data["scenario_type"].map(SCENARIO_LABELS)
)
plot_data["training_source_label"] = (
    plot_data["training_source"].map(SOURCE_LABELS)
)
plot_data["test_source_label"] = (
    plot_data["test_source"].map(SOURCE_LABELS)
)

absolute_evaluation_metrics = {
    "f1_attack": (
        "F1 da classe ATTACK",
        "f1_attack_by_algorithm_and_scenario",
    ),
    "balanced_accuracy": (
        "Acurácia balanceada",
        "balanced_accuracy_by_algorithm_and_scenario",
    ),
    "f1_macro": (
        "F1 macro",
        "f1_macro_by_algorithm_and_scenario",
    ),
}

for metric, (metric_label, filename) in (
    absolute_evaluation_metrics.items()
):
    figure = px.scatter(
        plot_data,
        x=metric,
        y="model_label",
        color="model_label",
        facet_col="scenario_label",
        color_discrete_map=MODEL_COLORS,
        category_orders={
            "model_label": [
                MODEL_LABELS[model] for model in MODEL_ORDER
            ],
            "scenario_label": [
                SCENARIO_LABELS[scenario]
                for scenario in SCENARIO_ORDER
            ],
        },
        custom_data=[
            "training_source_label",
            "test_source_label",
        ],
        labels={
            metric: metric_label,
            "model_label": "Algoritmo",
        },
        title=(
            f"{metric_label} por algoritmo e cenário de avaliação"
            "<br><sup>Cada ponto representa uma combinação de "
            "origem de treinamento, conjunto de teste e algoritmo</sup>"
        ),
    )
    figure.for_each_annotation(
        lambda annotation: annotation.update(
            text=annotation.text.split("=")[-1]
        )
    )
    figure.update_traces(
        marker=dict(size=9, opacity=0.75),
        hovertemplate=(
            "Algoritmo: %{y}<br>"
            "Treinamento: %{customdata[0]}<br>"
            "Teste: %{customdata[1]}<br>"
            f"{metric_label}: %{{x:.4f}}<extra></extra>"
        ),
    )
    figure.update_xaxes(range=[0, 1.02], matches="x")
    figure.update_layout(showlegend=False)
    finalize_figure(
        figure,
        filename,
        width=1500,
        height=650,
    )

evaluation_routes = (
    plot_data["training_source"].map(SOURCE_ABBREVIATIONS)
    + " → "
    + plot_data["test_source"].map(SOURCE_ABBREVIATIONS)
)
plot_data["evaluation_route"] = evaluation_routes
EVALUATION_ROUTES_BY_SCENARIO = {
    "intra_dataset": [
        "CIC → CIC",
        "UNSW → UNSW",
        "IoT → IoT",
    ],
    "cross_dataset": [
        "CIC → UNSW",
        "CIC → IoT",
        "UNSW → CIC",
        "UNSW → IoT",
        "IoT → CIC",
        "IoT → UNSW",
    ],
    "combined_to_unseen": [
        "CIC+UNSW → IoT",
        "CIC+IoT → UNSW",
        "UNSW+IoT → CIC",
    ],
}


def plot_all_training_test_combinations(
    metric,
    metric_label,
    filename,
):
    figure = px.strip(
        plot_data,
        x="evaluation_route",
        y=metric,
        color="model_label",
        facet_col="scenario_label",
        stripmode="group",
        custom_data=[
            "model_label",
            "training_source_label",
            "test_source_label",
            "scenario_label",
        ],
        color_discrete_map=MODEL_COLORS,
        category_orders={
            "model_label": [
                MODEL_LABELS[model] for model in MODEL_ORDER
            ],
            "scenario_label": [
                SCENARIO_LABELS[scenario]
                for scenario in SCENARIO_ORDER
            ],
        },
        labels={
            "evaluation_route": "",
            metric: metric_label,
            "model_label": "Algoritmo",
        },
        title=(
            f"Resultados individuais de {metric_label} por "
            "combinação treinamento-teste"
        ),
    )
    figure.for_each_annotation(
        lambda annotation: annotation.update(
            text=(
                "Cenário: "
                f"{annotation.text.split('=')[-1]}"
            )
        )
    )
    figure.update_layout(
        title=dict(
            y=0.985,
            yanchor="top",
        ),
    )
    for axis_name, scenario_type in zip(
        ["xaxis", "xaxis2", "xaxis3"],
        SCENARIO_ORDER,
    ):
        figure.layout[axis_name].update(
            categoryorder="array",
            categoryarray=(
                EVALUATION_ROUTES_BY_SCENARIO[scenario_type]
            ),
        )
    for column_index, scenario_type in enumerate(
        SCENARIO_ORDER,
        start=1,
    ):
        route_count = len(
            EVALUATION_ROUTES_BY_SCENARIO[scenario_type]
        )
        for separator_index in range(1, route_count):
            figure.add_vline(
                x=separator_index - 0.5,
                row=1,
                col=column_index,
                line_width=1,
                line_dash="dash",
                line_color="rgba(80, 80, 80, 0.28)",
            )
    figure.update_traces(
        jitter=0.12,
        marker=dict(size=9, opacity=0.82),
        hovertemplate=(
            "Algoritmo: %{customdata[0]}<br>"
            "Origem do treinamento: %{customdata[1]}<br>"
            "Conjunto de teste: %{customdata[2]}<br>"
            "Cenário: %{customdata[3]}<br>"
            f"{metric_label}: %{{y:.4f}}<extra></extra>"
        ),
    )
    figure.update_xaxes(
        matches=None,
        tickangle=-30,
        title_text=None,
        showgrid=False,
    )
    figure.update_yaxes(
        range=[0, 1.02],
        matches="y",
        showticklabels=True,
    )
    finalize_figure(
        figure,
        filename,
        width=1800,
        height=580,
        top_margin=115,
        legend_y=1.10,
    )


plot_all_training_test_combinations(
    "f1_macro",
    "F1 macro",
    "f1_macro_all_training_test_combinations",
)
plot_all_training_test_combinations(
    "balanced_accuracy",
    "Acurácia balanceada",
    "balanced_accuracy_all_training_test_combinations",
)

generated_tables = sorted(
    path.relative_to(TABLES_DIR).as_posix()
    for path in saved_tables
)
generated_svg = sorted(
    path.name for path in SVG_DIR.glob("*.svg")
)
generated_png = sorted(
    path.name for path in PNG_DIR.glob("*.png")
)

assert len(generated_svg) == len(generated_png)
assert len(generated_svg) == 20, (
    "A análise deve gerar exatamente 20 gráficos."
)
assert {
    Path(filename).stem for filename in generated_svg
} == {
    Path(filename).stem for filename in generated_png
}

print(f"Tabelas salvas: {len(generated_tables)}")
print(f"Gráficos salvos em SVG: {len(generated_svg)}")
print(f"Gráficos salvos em PNG: {len(generated_png)}")
display(pd.DataFrame({"tabelas": generated_tables}))
display(pd.DataFrame({
    "grafico_svg": generated_svg,
    "grafico_png": generated_png,
}))

Resorting to unclean kill browser.

Tabelas salvas: 10
Gráficos salvos em SVG: 20
Gráficos salvos em PNG: 20

                                       tabelas
0             best_algorithm_by_experiment.csv
1  combined_vs_individual_training_sources.csv
2                 cross_validation_summary.csv
3                           evaluation_all.csv
4                      evaluation_combined.csv
5                 evaluation_cross_dataset.csv
6                 evaluation_intra_dataset.csv
7         performance_extremes_by_scenario.csv
8         performance_metric_discrepancies.csv
9                        tcc_results_table.csv

,grafico_svg,grafico_png
0,balanced_accuracy_all_training_test_combinations.svg,balanced_accuracy_all_training_test_combinations.png
1,balanced_accuracy_best_worst_by_scenario.svg,balanced_accuracy_best_worst_by_scenario.png
2,balanced_accuracy_by_algorithm_and_scenario.svg,balanced_accuracy_by_algorithm_and_scenario.png
3,balanced_accuracy_by_scenario_type.svg,balanced_accuracy_by_scenario_type.png
4,combined_vs_best_individual_balanced_accuracy.svg,combined_vs_best_individual_balanced_accuracy.png
5,combined_vs_best_individual_f1_attack.svg,combined_vs_best_individual_f1_attack.png
6,combined_vs_best_individual_f1_macro.svg,combined_vs_best_individual_f1_macro.png
7,f1_attack_best_worst_by_scenario.svg,f1_attack_best_worst_by_scenario.png
8,f1_attack_by_algorithm_and_scenario.svg,f1_attack_by_algorithm_and_scenario.png
9,f1_attack_by_scenario_type.svg,f1_attack_by_scenario_type.png
10,f1_macro_all_training_test_combinations.svg,f1_macro_all_training_test_combinations.png
11,f1_macro_best_worst_by_scenario.svg,f1_macro_best_worst_by_scenario.png
12,f1_macro_by_algorithm_and_scenario.svg,f1_macro_by_algorithm_and_scenario.png
13,f1_macro_by_scenario_type.svg,f1_macro_by_scenario_type.png
14,generalization_f1_macro.svg,generalization_f1_macro.png
15,individual_and_combined_balanced_accuracy.svg,individual_and_combined_balanced_accuracy.png
16,individual_and_combined_f1_attack.svg,individual_and_combined_f1_attack.png
17,individual_and_combined_f1_macro.svg,individual_and_combined_f1_macro.png
18,precision_attack_by_scenario_type.svg,precision_attack_by_scenario_type.png
19,recall_attack_by_scenario_type.svg,recall_attack_by_scenario_type.png